### ISSUE TITLE
Setting marker indicators 

### ISSUE THREAD

**Issue by joshbedo** [nitaliano/react-native-mapbox-gl#10]
It would be nice if i could pass an array of objects that specified coordinates, a name, icon, etc. to display markers. I'd love to be able to show markers for search results. Let me know if i can help :)

![](https://api.monosnap.com/rpc/file/download?id=5rzn3IOcVnkLNxyEFN7g2DRBTEo2MC)

**Comment by 1ec5** [comment]
The relevant APIs are [`-addAnnotation:`, `-addAnnotations:`](https://github.com/mapbox/mapbox-gl-native/blob/master/include/mbgl/ios/MGLMapView.h#L205-211), etc. I’m not sure how React Native handles protocol conformance, since these APIs expect `MGLAnnotation`s.

**Comment by bsudekum** [comment]
all done
