### ISSUE TITLE
How to properly enabled/disable telemetry?

### ISSUE THREAD

**Issue by woodpav** [nitaliano/react-native-mapbox-gl#1000]
I need to be able to provide users with the ability to enable/disable telemtry.

How do I do this from react-native? No docs here or in mapbox-gl-native

**Comment by nitaliano** [comment]
are you hiding attribution?

**Comment by woodpav** [comment]
Yeah, I removed the default attribution because I need it in the top left. Everything (logo, copyright, etc.) is good to go, only telemtry logic left.

In original docs I found that you need to set `MGLMapboxMetricsEnabled` to `YES` or `NO` but when I initially load the app that key is not set. (I dont know if my setting it has any effect).

A `.setTelemetryEnabled` / `.getTelemetryEnabled` function would be 10/10.

**Comment by frankrowe** [comment]
Any updates on this? I need to enable/disable telemetry from a different button as well.

**Comment by samdelacruz** [comment]
+1

**Comment by nitaliano** [comment]
This has been merged into master thanks to @georific for the PR! Now you can use `MapboxGL.setTelemetryEnabled` and `MapboxGL.isTelemetryEnabled`

**Comment by ArtiPatel10** [comment]
Is this the right  way to enable and disable the telemetry services in android mapbox version 6.0.1? 
TelemetryEnabler.updateTelemetryState(TelemetryEnabler.State.ENABLED);

**Comment by ferdicus** [comment]
Would be nice to have these documented somewhere.

**Comment by fnusneha** [comment]
![image](https://user-images.githubusercontent.com/7800651/41205802-16c98d32-6caf-11e8-982a-fd175c25ba89.png)

**Comment by haydenkaizeta** [comment]
@nitaliano updates on this? @fnusneha 's bug is present in the most recent build

**Comment by georific** [comment]
`Mapbox.setAccessToken` should be used with a string param. From the example app

https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/App.js#L93
