### ISSUE TITLE
Styling the User Tracking puck

### ISSUE THREAD

**Issue by lucasgray** [nitaliano/react-native-mapbox-gl#1004]
Any way to style the user tracking circle?  It would be nice if we could provide a field to the `MapView` to specify how to draw it, maybe not necessarily a circle.  

I see that in the `DriveTheLine` example there is a `PulseCircleLayer` reading from state that one could probably use to fake something like this, but any first class support?

**Comment by nitaliano** [comment]
There is no first class support for this so doing something similar to the `DriveTheLine` example would be best. I do have plans for this in the future as having a component called `MapboxGL.UserLocation` that you would be able to style

**Comment by makirby** [comment]
@nitaliano Is this do-able (for now) by altering the native code?
