### ISSUE TITLE
Elevation artifacts in 6.0.3-rc1

### ISSUE THREAD

**Issue by lucasgray** [nitaliano/react-native-mapbox-gl#1005]
Upgraded to 6.0.3-rc1 and am now seeing a strange artifact on the phone that I can't reproduce in Mapbox Studio.  I believe it's a couple of elevation lines and a 1px stroke on either side from looking at my line styles but I'm not sure.  It pops in and goes away depending on the zoom level.  [video](https://drive.google.com/open?id=1XKXZwIxDokGIEuF0DyOW8qOAtZ3Vj_1p)

**Comment by nitaliano** [comment]
Hi, thanks for reporting would you mind reporting this in gl-native? We can link the upstream ticket here. We don't have any control over this issue on our level of the stack.

**Comment by lucasgray** [comment]
Sure thing, opened mapbox/mapbox-gl-native#11112

**Comment by kristfal** [comment]
This is a rather old issue. In an effort to clean up stale issues, I'll close this. Please retry on latest master and reopen the upstream issue if the problem still persists.
