### ISSUE TITLE
error on run

### ISSUE THREAD

**Issue by crowlKats** [nitaliano/react-native-mapbox-gl#1009]
When I run my app, this error comes up.
![screen shot 2018-01-29 at 14 01 54](https://user-images.githubusercontent.com/13135287/35511768-822ec89a-04fd-11e8-8367-3689cfae67a9.png)

```js
import React from 'react';
import { StyleSheet, Text, View, Button } from 'react-native';
import { TabNavigator } from 'react-navigation';
import MapboxGL from '@mapbox/react-native-mapbox-gl';

export default class mainScreen extends React.Component {
	static navigationOptions = {tabBarLabel: 'Map'};

  render() {
    return (
      <View style={styles.view}>
	      <MapboxGL.MapView />
      </View>
    );
  }
}

const styles = StyleSheet.create({
	view: {
		flex: 1,
		justifyContent: 'center',
		alignItems: 'center'
	}
});
```

**Comment by nitaliano** [comment]
Did you link the native code? Could you show my your gradle file and MainApplication.java?

**Comment by crowlKats** [comment]
sorry, but as I am new to react-native, or mobile development, I have no clue where those either are

**Comment by nitaliano** [comment]
You need to follow these install steps https://github.com/mapbox/react-native-mapbox-gl/blob/master/android/install.md going to close this out post back on this ticket if you need help

**Comment by crowlKats** [comment]
woops, maybe I should have specified ios

**Comment by crowlKats** [comment]
and I did follow the installation instructions for ios
