### ISSUE TITLE
iOS: Vertical content inset not applied to iOS compass

### ISSUE THREAD

**Issue by kristfal** [nitaliano/react-native-mapbox-gl#1013]
Works on Android, but not on iOS. Tested with and without contentInset.

Might be related: https://github.com/mapbox/mapbox-gl-native/issues/11068

**Comment by kristfal** [comment]
Update: Compass now renders in 6.1.0, but the vertical contentInset value doesn't work on iOS, only the horizontal inset.

**Comment by RobertSasak** [comment]
I can confirm this bug. In addition when I set any value then *undefined* for *contentInset* AND set new center or zoom value for map, then map pan to equator [0,0]. 
Have you found any workaround?

**Comment by ronal2do** [comment]
+ 1

**Comment by kristfal** [comment]
Closing this one. We should revisit all control components and use RN for rendering rather than relying on native side updates for this.

**Comment by brycedbjork** [comment]
any update on this?
