### ISSUE TITLE
Update Mapbox.framework fetch script to work with yarn on updates

### ISSUE THREAD

**Issue by alexgvozden** [nitaliano/react-native-mapbox-gl#1015]
Hi, 

I am using MapBox in React Native app
At first it compiles properly and runs - everything works 
but after some time on rerun it drops a load of errors
then you have to remove node_modules all the time and reinstall it in order for app to compile

<img width="1193" alt="screen shot 2018-01-31 at 10 11 58 am" src="https://user-images.githubusercontent.com/127109/35614644-1a17b3ba-0670-11e8-97c7-6981a5c2e515.png">

**Comment by nitaliano** [comment]
What version of the mapbox framework is under your node_module? I would try a fresh install those symbols should exist

**Comment by alexgvozden** [comment]
Hi

release is 6.0.3rc 

I do fresh install every day because of this error, after compiling this error comes haunting.
On removing node_modules and installing again it works so it's something in compilation or similar that removes the files or adds additional stuff

Thanks

**Comment by nitaliano** [comment]
are you using yarn or npm and what version are you using? I haven't run into this with the example app yet

**Comment by lesserj** [comment]
I've had similar and consistent issues with this library where the build breaks after some time with errors similar to above.  I have to pretty regularly run the following:
yarn remove @mapbox/react-native-mapgox-gl
yarn add @mapbox/react-native-mapbox-gl

I think it works until the xcode cache is removed.  Closing and reopening xcode seems to cause the problem as does the occasional yarn upgrade.  I'm currently on 6.0.3-rc1, but have had similar problems with past versions as well.

**Comment by nitaliano** [comment]
I've been using `npm` so I'll checkout `yarn` and see what's happening

**Comment by jmcneese** [comment]
I have this issue too, using yarn.

**Comment by nitaliano** [comment]
This will be fixed in version `6.0.4`

**Comment by alexgvozden** [comment]
awesome @nitaliano  
my mornings are going to be more beautiful now :) 

almost done with the app I'll share it once out

**Comment by jaltin** [comment]
Hi @nitaliano,

I am using 6.1.0 version and I just ran into this issue. Was it not fixed in the 6.0.4 version (as per your comment above) or has it perhaps reappeared?

@lesserj's solution/workaround works for me for now, but would be great to not have to do it every time the problem reappears.

Thanks!

**Comment by nitaliano** [comment]
@jaltin we ended up making a breaking change and made a release under `6.1.0` instead so `6.0.4` never happened, but we will see it at the end of next week under `6.1.1`. If you want to get around this annoying issue for now we generate a `.framework_version` file under `node_modules/@mapbox/react-native-mapbox-gl/ios/.framework_version` if you keep deleting that file it won't attempt to use what yarn is caching and prevent this issue. Sorry for the confusion!

**Comment by jaltin** [comment]
@nitaliano Thanks a lot for the update and for the fix until 6.1.1 is released!

**Comment by alexgvozden** [comment]
thanks @nitaliano for great work!

**Comment by nitaliano** [comment]
This PR https://github.com/mapbox/react-native-mapbox-gl/pull/1151 that was just merged into master has fixed the `yarn add` problem for me with the example app, would anyone like to also test out master? Would like to get a verification here before closing this issue out.

Also before testing could you wipe the yarn cache `yarn cache clean`

**Comment by lesserj** [comment]
I will be happy to test.

**Comment by lesserj** [comment]
This has been working for me.  Thank you!

**Comment by nitaliano** [comment]
Great going to close this out, if anyone else runs into this make sure you update to 6.1.1
