### ISSUE TITLE
App crashing immediately in offline mode

### ISSUE THREAD

**Issue by 386sx** [nitaliano/react-native-mapbox-gl#1016]
Could you please provide a working example of rendering a map while the device is offline. As soon as the connection is cut off the map gets black and the app crashes immediately.
I downloaded an offline pack and there must be a way of gracefully loading a map offline without the whole thing crashing. Unfortunately there is no documentation on displaying maps in offline mode whatsoever. Really struggling here (putting offlineManager.getPacks() in componentDidMount doesn't work either ).
In my opinion the offline functionality is one of the most important features here, but it is unfortunately practically undocumented.

My component:

import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,
  Button
} from 'react-native';

import MapboxGL from '@mapbox/react-native-mapbox-gl';
MapboxGL.setAccessToken(TOKEN);

export default class OfflinePacks extends Component {

  async onDidFinishLoadingStyle () {
    var packs = await MapboxGL.offlineManager.getPacks()
    console.log(packs);
    }
  render() {
    return (
      <View style={styles.container}>
        <MapboxGL.MapView
            zoomLevel={8}
            centerCoordinate={[17.775879,63.995235]}
            style={styles.container}>
        </MapboxGL.MapView>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});

**Comment by nitaliano** [comment]
What version are you using? You don't need to do anything to make offline packs loads gl-native handles that for you

**Comment by 386sx** [comment]
"@mapbox/geo-viewport": "^0.2.2",
"@mapbox/react-native-mapbox-gl": "^6.0.3-rc1",
It just won't work with the code above...

**Comment by nitaliano** [comment]
Can you show me the code you used to download the pack?

**Comment by 386sx** [comment]
RNMGL is crashing immediately once the connection breaks. Are there any prerequisites to mind when running an app with RNMGL in offline mode? Could you provide a working example of a map in offline mode?

**Comment by 386sx** [comment]
It's basically the example with changed bounds.


import React from 'react';

import {
  Alert,
  Text,
  View,
  TouchableOpacity,
  Dimensions,
  StyleSheet,
} from 'react-native';


import MapboxGL from '@mapbox/react-native-mapbox-gl';
import geoViewport from '@mapbox/geo-viewport';

MapboxGL.setAccessToken(KEY);

import Page from './Page';
import Bubble from './Bubble';

const CENTER_COORD = [17.775879,63.995235];
const MAPBOX_VECTOR_TILE_SIZE = 512;

const styles = StyleSheet.create({
  percentageText: {
    padding: 8,
    textAlign: 'center',
  },
  buttonCnt: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  button: {
    flex: 0.4,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 3,
    backgroundColor: 'blue',
    padding: 8,
  },
  buttonTxt: {
    color: 'white',
  },
  matchParent: {
    flex: 1,
  }
});

class CreateOfflineRegion extends React.Component {

  constructor (props) {
    super(props);

    this.state = {
      name: `sc-${Date.now()}`,
      offlineRegion: null,
      offlineRegionStatus: null,
    };

    this.onDownloadProgress = this.onDownloadProgress.bind(this);
    this.onDidFinishLoadingStyle =
this.onDidFinishLoadingStyle.bind(this);

    this.onResume = this.onResume.bind(this);
    this.onPause = this.onPause.bind(this);
    this.onStatusRequest = this.onStatusRequest.bind(this);
  }

  componentWillUnmount () {
    // avoid setState warnings if we back out before we finishing
downloading
    //MapboxGL.offlineManager.deletePack(this.state.name);
    MapboxGL.offlineManager.unsubscribe('test');
  }

  async onDidFinishLoadingStyle () {
    const { width, height } = Dimensions.get('window');
    const bounds = geoViewport.bounds(CENTER_COORD, 12, [width,
height], MAPBOX_VECTOR_TILE_SIZE);

    const options = {
      name: this.state.name,
      styleURL: MapboxGL.StyleURL.Street,
      bounds: [[3.955078,54.007769], [31.552734,71.357067]],
      minZoom: 1,
      maxZoom: 8,
    };

    // start download
    MapboxGL.offlineManager.createPack(
      options,
      this.onDownloadProgress,
    );


  }

  onDownloadProgress (offlineRegion, offlineRegionStatus) {
    this.setState({
      name: offlineRegion.name,
      offlineRegion: offlineRegion,
      offlineRegionStatus: offlineRegionStatus,
    });
  }

  onResume () {
    if (this.state.offlineRegion) {
      this.state.offlineRegion.resume();
    }
  }

  onPause () {
    if (this.state.offlineRegion) {
      this.state.offlineRegion.pause();
    }
  }

  async onStatusRequest () {
    if (this.state.offlineRegion) {
      const offlineRegionStatus = await
this.state.offlineRegion.status();
      Alert.alert('Get Status', JSON.stringify(offlineRegionStatus,
null, 2));
    }
  }

  _formatPercent () {
    if (!this.state.offlineRegionStatus) {
      return '0%';
    }
    return Math.round(this.state.offlineRegionStatus.percentage / 10) /
10;
  }

  _getRegionDownloadState (downloadState) {
    switch (downloadState) {
      case MapboxGL.OfflinePackDownloadState.Active:
        return 'Active';
      case MapboxGL.OfflinePackDownloadState.Complete:
        return 'Complete';
      default:
        return 'Inactive';
    }
  }

  render () {
    const offlineRegionStatus = this.state.offlineRegionStatus;

    return (
      <Page {...this.props}>
        <MapboxGL.MapView
            zoomLevel={10}
            ref={(c) => this._map = c}
            onPress={this.onPress}
            onDidFinishLoadingMap={this.onDidFinishLoadingStyle}
            centerCoordinate={CENTER_COORD}
            style={styles.matchParent} />

        {offlineRegionStatus !== null ? (
          <Bubble>
            <View style={{ flex : 1 }}>

              <Text>Download State:
{this._getRegionDownloadState(offlineRegionStatus.state)}</Text>
              <Text>Download Percent:
{offlineRegionStatus.percentage}</Text>
              <Text>Completed Resource Count:
{offlineRegionStatus.completedResourceCount}</Text>
              <Text>Completed Resource Size:
{offlineRegionStatus.completedResourceSize}</Text>
              <Text>Completed Tile Count:
{offlineRegionStatus.completedTileCount}</Text>
              <Text>Required Resource Count:
{offlineRegionStatus.requiredResourceCount}</Text>

              <View style={styles.buttonCnt}>
                <TouchableOpacity onPress={this.onResume}>
                  <View style={styles.button}>
                    <Text style={styles.buttonTxt}>Resume</Text>
                  </View>
                </TouchableOpacity>

                <TouchableOpacity onPress={this.onStatusRequest}>
                  <View style={styles.button}>
                    <Text style={styles.buttonTxt}>Status</Text>
                  </View>
                </TouchableOpacity>

                <TouchableOpacity onPress={this.onPause}>
                  <View style={styles.button}>
                    <Text style={styles.buttonTxt}>Pause</Text>
                  </View>
                </TouchableOpacity>
              </View>
            </View>
          </Bubble>
        ) : null}
      </Page>
    );
  }
}

export default CreateOfflineRegion;
'


on., 31.01.2018 kl. 12.50 +0000, skrev Nick Italiano:

**Comment by 386sx** [comment]
The thing is, the app crashes when the connection is cut off and I try to render a map. I realised that it seems to be independent of the offline packs. Rendering  MapView without a connection is not possible.

 `      <View style={styles.container}>

        {this.state.selectedPlace.name && <PlaceInfo place={this.state.selectedPlace} />}

        <MapboxGL.MapView
           ref={(c) => this._map = c}
           showUserLocation={true}
           centerCoordinate={[parseFloat(this.state.region.longitude), parseFloat(this.state.region.latitude)]}
           zoomLevel={8}
           style={styles.matchParent}
        >
          <MapboxGL.ShapeSource
            onPress={this._onPress.bind(this)}
            id='symbolLayerSource'
            shape={this.state.markers}
            images={{
              blue: blueStar,
              yellow: yellowStar,
              remote: remoteIcon,
            }}
            cluster={false}
            clusterRadius={10}
           >
             <MapboxGL.SymbolLayer id='symbol' style={mapStyles.parameterIcon}  />
          </MapboxGL.ShapeSource>
        </MapboxGL.MapView>
        <View style={styles.buttonContaier}>
          <Button large title={I18n.t("HierSuchen")}
            backgroundColor="#009688"
            icon={{ name: 'search' }}
            onPress={this.onButtonPress}
          />
        </View>
      </View>`

This map works, but just while being online. As soon as I turn of the connection the app crashes.

**Comment by kristfal** [comment]
Are you running the app through remote debugging, live reload or hot reload? If so, the app will crash because the JS thread is running on your PC when you put your device in flight mode / disconnect WiFi. 

To run the app offline, disable the settings mentioned above or run the app in production mode.
