### ISSUE TITLE
MapView not visible on Android Oreo 

### ISSUE THREAD

**Issue by glennverschooren** [nitaliano/react-native-mapbox-gl#1019]
Hey,

I have some issues rendering the MapView component on Android Oreo.
The map is not always visible. At first I thought is was an issue with the styling, but that's not the case. The parent has a height: "100%" and the map itself has a flex: 1.

It's only a problem when I render the map on Android Oreo. I'm using the PXL 2 XL simulator.

**Comment by nitaliano** [comment]
do you see the MapView attribution on the bottom left hand corner? If not the view is not filling the containers width/height and could be an Oreo RN issue. Mind also just posting a quick code snippet so I can copy and paste that into the example application

**Comment by glennverschooren** [comment]
I found a related [issue](https://github.com/mapbox/react-native-mapbox-gl/issues/955).
So I guess it is fixed in v6.0.3

Do you know when this version is going to be released?

**Comment by nitaliano** [comment]
@glennverschooren I've been on vacation for the last week. I'm expecting to release it this week
