### ISSUE TITLE
RasterSource/RasterLayer not displaying on Android

### ISSUE THREAD

**Issue by ClayChristmas** [nitaliano/react-native-mapbox-gl#1024]
I've got a map set up in React Native 0.51 with MapBox 6.0.3-rc1 running on IOS and displaying a RasterLayer sourcing from a URL.  On IOS everything works as expected, but the exact same React Native code does not work on Android.  The map displays without issues or javascript error messages, but the layer does not display.  A marker relying on the raster layer also doesn't display, but if I remove it's dependence on the raster layer then it does display.

```
const url = 'https://someurl.com/{x}/{y}/{z}';

                <Mapbox.MapView
                      styleURL={Mapbox.StyleURL.Street}
                      zoomLevel={8}
                      centerCoordinate={-99, 32}
                      style={styles.map}
                      ref={(ref) => this.map = ref}
                      zoomEnabled={false}
                      pitchEnabled={false}
                      scrollEnabled={false}
                      rotateEnabled={false}
                      logoEnabled={false}>
                        <Mapbox.RasterSource key='d' id='mySource' url={url}>
                          <Mapbox.RasterLayer id='myLayer' sourceID='mySource' style={{rasterOpacity:0.7}} />
                        </Mapbox.RasterSource>
                        <Mapbox.ShapeSource id='currentLocationMarkerSource' shape={this.state.featureCollection}>
                          <Mapbox.SymbolLayer
                            id='currentLocationMarkerSymbols'
                            style={[mapStyles.icon, {textField:markerText}]}
                            aboveLayerID='myLayer'
                            maxZoomLevel={16}
                            />
                        </Mapbox.ShapeSource>
                  </Mapbox.MapView>
```

**Comment by phuochau** [comment]
@ClayChristmas  Could you try to add `tileSize={256}` to `RasterSource`? I have same issue before.

**Comment by ClayChristmas** [comment]
That fixed it, thanks!  I thought that tileSize defaulted to 256 if not specified?  Seems to have worked on IOS before without that, but not on Android.  I also see some funkiness with the SymbolLayer opacity/aboveLayerID when using 512 tile sizes instead of 256 on Android.

**Comment by phuochau** [comment]
@ClayChristmas Cool, so if it's working well, you can close this issue.

**Comment by nitaliano** [comment]
@ClayChristmas it should default to 256, I just looked into the Android SDK and it is setting the default value to `512` so I'll need to override it in this repo to match the iOS default. I'll be looking into all of the properties to make sure they align correctly

**Comment by ClayChristmas** [comment]
@nitaliano and @phuochau  thanks!  Would you like for me to keep this issue open for now or close it?  My map URL was using 512 tile sizes initially when it did not work, so there may be some other issue when it is not specified.

**Comment by nitaliano** [comment]
Let's keep this open until I look into all the raster layer props and make any PRs under this ticket id

**Comment by ClayChristmas** [comment]
Not sure if related to this ticket or if I should open up a new ticket, but I'm also running into sporadic issues with the RasterSource/RasterLayer on Android.  I've looked through the other recent github issues since the rewrite and don't see any that seem to be quite the same as these.

The first issue is when zooming in/out sometimes tiles don't load.  I'm using a custom tile API for this and it seems like if you zoom at all too quickly like the tiles don't load and once they haven't loaded then they never load unless you refresh the whole react native application.
Here is a gif of what this looks like:
![zoom](https://user-images.githubusercontent.com/18467048/35880617-6b7faa92-0b4c-11e8-9ab0-1a4e58c641bd.gif)


The second issue that I'm seeing is that inside of a scrollview sometimes the map glitches and instead of staying pinned to its location inside of its container it does partial updates.  It is probably easiest to see in the gifs below.
This shows it working as expected:
![mapscrollworking](https://user-images.githubusercontent.com/18467048/35880529-2f29f0ca-0b4c-11e8-89ad-07b5996eac85.gif)


This shows the glitching that I am seeing sometimes on both emulated and physical devices:
![mapscrollissue](https://user-images.githubusercontent.com/18467048/35880518-2b25c0f8-0b4c-11e8-8caa-3c5139c7d2c3.gif)

**Comment by SurajPSyngenta** [comment]
> Not sure if related to this ticket or if I should open up a new ticket, but I'm also running into sporadic issues with the RasterSource/RasterLayer on Android. I've looked through the other recent github issues since the rewrite and don't see any that seem to be quite the same as these.
> 
> The first issue is when zooming in/out sometimes tiles don't load. I'm using a custom tile API for this and it seems like if you zoom at all too quickly like the tiles don't load and once they haven't loaded then they never load unless you refresh the whole react native application. Here is a gif of what this looks like: ![zoom](https://user-images.githubusercontent.com/18467048/35880617-6b7faa92-0b4c-11e8-9ab0-1a4e58c641bd.gif) [ ![zoom](https://user-images.githubusercontent.com/18467048/35880617-6b7faa92-0b4c-11e8-9ab0-1a4e58c641bd.gif) ](https://user-images.githubusercontent.com/18467048/35880617-6b7faa92-0b4c-11e8-9ab0-1a4e58c641bd.gif) [ ](https://user-images.githubusercontent.com/18467048/35880617-6b7faa92-0b4c-11e8-9ab0-1a4e58c641bd.gif)
> 
> The second issue that I'm seeing is that inside of a scrollview sometimes the map glitches and instead of staying pinned to its location inside of its container it does partial updates. It is probably easiest to see in the gifs below. This shows it working as expected: ![mapscrollworking](https://user-images.githubusercontent.com/18467048/35880529-2f29f0ca-0b4c-11e8-89ad-07b5996eac85.gif) [ ![mapscrollworking](https://user-images.githubusercontent.com/18467048/35880529-2f29f0ca-0b4c-11e8-89ad-07b5996eac85.gif) ](https://user-images.githubusercontent.com/18467048/35880529-2f29f0ca-0b4c-11e8-89ad-07b5996eac85.gif) [ ](https://user-images.githubusercontent.com/18467048/35880529-2f29f0ca-0b4c-11e8-89ad-07b5996eac85.gif)
> 
> This shows the glitching that I am seeing sometimes on both emulated and physical devices: ![mapscrollissue](https://user-images.githubusercontent.com/18467048/35880518-2b25c0f8-0b4c-11e8-8caa-3c5139c7d2c3.gif) [ ![mapscrollissue](https://user-images.githubusercontent.com/18467048/35880518-2b25c0f8-0b4c-11e8-8caa-3c5139c7d2c3.gif) ](https://user-images.githubusercontent.com/18467048/35880518-2b25c0f8-0b4c-11e8-8caa-3c5139c7d2c3.gif) [ ](https://user-images.githubusercontent.com/18467048/35880518-2b25c0f8-0b4c-11e8-8caa-3c5139c7d2c3.gif)

Did you found any solution for layer not loading issue?

**Comment by ClayChristmas** [comment]
@SurajPSyngenta I believe that we upgraded to the newer version of the library and that this has been resolved. I haven't looked at this in quite some time though.
