### ISSUE TITLE
[Android] MapView destroy got the error: "Attempt to invoke virtual method int android.view.View.getId() on a null object reference"

### ISSUE THREAD

**Issue by phuochau** [nitaliano/react-native-mapbox-gl#1026]
Hi,

Currently, When I back from Map screen to previous screen. It always returns the error as below:

![Image of Error](https://i.gyazo.com/af43b3043fc0205e06a3565809af04e5.png)

Maybe has something wrong at `onDestroy` MapView but I'm not sure.

Does anyone know this issue, thanks!

**Comment by nitaliano** [comment]
Can you try master a PR got merged in today that might help

**Comment by phuochau** [comment]
@nitaliano will do it and confirm, thanks

**Comment by phuochau** [comment]
@nitaliano You mean this PR: https://github.com/mapbox/react-native-mapbox-gl/pull/1010 ? the issue is still there

**Comment by phuochau** [comment]
Closing it right now because it's from our fork code, not in original
