### ISSUE TITLE
Remote image memory crash

### ISSUE THREAD

**Issue by atarsha** [nitaliano/react-native-mapbox-gl#1029]
<img width="796" alt="screen shot 2018-02-11 at 1 00 30 pm" src="https://user-images.githubusercontent.com/381173/36077747-d0742a6c-0f2b-11e8-8f37-96ec1d90b58a.png">

I am adding images to a ShapeSource, and randomly it crashes. I will try to debug my code and see if I can find reproducible steps.

**Comment by nitaliano** [comment]
Thanks for reporting will look into this

**Comment by atarsha** [comment]
Being tracked in https://github.com/mapbox/react-native-mapbox-gl/issues/920

Closing this.
