### ISSUE TITLE
Allow use of nearest-neighbor interpolation with ImageSource

### ISSUE THREAD

**Issue by CQCumbers** [nitaliano/react-native-mapbox-gl#1031]
I am using a relatively low resolution image with an ImageSource, and would like to be able to see the edges of individual pixels when zoomed in - that is, I would like the ImageSource to use nearest neighbor rather than linear interpolation.

I saw that `render_raster_layer.cpp` in mapbox-gl-native uses linear texture filtering so I thought patching that file could work, but I can't figure out where the image interpolation occurs in this library. I understand that this might be too niche of an issue for official support, but if anyone could suggest a workaround I would be grateful.

**Comment by nitaliano** [comment]
@CQCumbers would you mind posting this in `gl-native` this repo is only wrapping `gl-native` so we don't have control over this part of the stack here.
