### ISSUE TITLE
Map is zooming back after pitch or two taps zoom

### ISSUE THREAD

**Issue by Gp2mv3** [nitaliano/react-native-mapbox-gl#1035]
I updated from 5.x to 6.0.3-rc1 and now, the zoom is acting weird.

The map zooms as expected but 1/2 seconds after, it zooms back to the initial zoom level. Here is a video of the bug: https://drive.google.com/file/d/1Gqk1EP2aW5fmUvGkYnrriG1rIPxgryUj/view?usp=sharing

It doesn't seem to be related to user location updates (it was my first hypothesis).

Do you have an idea of the reason ?

**Comment by nitaliano** [comment]
can you share some code? You might be re rendering back to the initial zoom

**Comment by Gp2mv3** [comment]
Yes of course, your answer is just ultra fast ! 😮 

Here is the MapView:
```
		<MapboxGL.MapView
		  ref={map => {this._map = map}}
	          style={styles.map}
		  centerCoordinate={[this.state.position.lng, this.state.position.lat]}
                  showUserLocation={true}
                  userTrackingMode={MapboxGL.UserTrackingModes.FollowWithHeading}
                  userLocationVerticalAlignment={MapboxGL.UserLocationVerticalAlignment.center}
	          styleURL={Config.mapBox.mapUrl}
		  onRegionDidChange={this._onRegionDidChange.bind(this)}
		  onPress={this._openSmallHelpModal.bind(this)}
		></MapboxGL.MapView>
```

And here are my two functions (openSmallHelpModal and onRegionDidChange), they don't change anything on the map:

```
    _onRegionDidChange(fromMap) {
	let position = fromMap.geometry.coordinates;
        let pos = {
            lat: position[1],
            lng: position[0]
        };
        this._getAddress(pos); // Does nothing with the map (Only reverse geocoding)
    };

    _openSmallHelpModal() {
	AsyncStorage.getItem('mapClicks', (err, data) => {
	    var clicks = (data ? parseInt(data) : 0);
	    if(clicks < 3) this.setState({smallHelpVisible: true});
	    AsyncStorage.setItem('mapClicks', ""+(clicks + 1));
	});
    }
```

The only use of the reference to the map is done when touching the location button (not done in the video):
```
_centerMap(loc) {
	if(!loc && !this.state.userLocation) this._getLocation();
	
        let pos = (loc ? loc : this.state.userLocation);
        if(pos) this._map.moveTo([pos.lng, pos.lat], 500);
    }
```

I hope those extracts can help.

**Comment by Gp2mv3** [comment]
Ok, I found the issue. 
When loading the address, I update this.state.position, meaning that the centerCoordinate props changes. I think it's still a bug, why does the zoom level changes when centerCoordinate changes ?

**Comment by Darkilen** [comment]
Hello, I still experiment this issue.
Did you find a fix other than not using `centerCoordinate`?
