### ISSUE TITLE
Jest testing: Unexpected token import

### ISSUE THREAD

**Issue by Gp2mv3** [nitaliano/react-native-mapbox-gl#1036]
Hi guys, I'm trying to run my test suite on my app but I receive the following error since my update from react-native-mapbox-gl from 5.x to 6.0.3-rc1. Do you have an idea of solution ?

Here is the error:
 >    /home/gp2mv3/Programmation/reactNative/sParks/app/node_modules/@mapbox/react-native-mapbox-gl/javascript/index.js:1
>     ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { Animated, NativeModules, PermissionsAndroid } from 'react-native';
>                                                                                              ^^^^^^
>     
>     SyntaxError: Unexpected token import
> 
>       31 | 
>       32 | import LocalizedStrings from 'react-native-localization';
>     > 33 | import MapboxGL from '@mapbox/react-native-mapbox-gl';
>       34 | 
> 

And here is my .babelrc (I presume thecode at the beginning of the line is added by babel ?):
```
{
  "retainLines": true,
  "compact": true,
  "comments": false,
  "presets": ["react-native"],
  "sourceMaps": false
}
```

What am I doing wrong ?

Thanks !

**Comment by nitaliano** [comment]
Based off of this 
```
({"Object.":function(module,exports,require,__dirname,__filename,global,jest){import { Animated, NativeModules, PermissionsAndroid } from 'react-native';
^^^^^^
```

it looks like it's having trouble resolving react-native, what does your `package.json` look like?

**Comment by Gp2mv3** [comment]
Here is a sample of it:

```
{
    "name": "cPark",
    "version": "4.0.14",
    "private": true,
    "scripts": {
	"start": "node node_modules/react-native/local-cli/cli.js start",
	"lint": "eslint .",
	"test": "jest",
	"cover": "nyc --reporter=lcov --reporter=text --reporter=html npm run test",
	"styleguide": "styleguidist server",
	"styleguide:build": "styleguidist build"
    },
    "dependencies": {
	"@mapbox/react-native-mapbox-gl": "^6.0.3-rc1",
	"babel-plugin-transform-remove-console": "^6.8.5",
	"prop-types": "^15.5.10",
	"react": "^16.0.0-alpha.12",
	"react-native": "^0.52.0"
    },
    "devDependencies": {
	"babel-core": "^6.26.0",
	"babel-eslint": "^7.2.3",
	"babel-jest": "^22.2.2",
	"babel-preset-es2015": "^6.24.1",
	"babel-preset-react-native": "^4.0.0",
	"jest": "^22.0.4",
	"jest-fetch-mock": "^1.2.1"
    }
}
```

Thanks for your support !

**Comment by nitaliano** [comment]
can you add 

```
"jest": {
    "preset": "react-native"
}
```

to it and see if it resolves your issue?

**Comment by Gp2mv3** [comment]
It was already there, here is the jest block (I removed it too quickly...):

 ```
   "jest": {
	"preset": "react-native",
	"snapshotSerializers": [],
	"collectCoverage": true,
	"setupFiles": [
	    "./test/setup-tests.js"
	]
    }
```

**Comment by Gp2mv3** [comment]
I found a workaround, it's simply to ignore the files when transforming (in my package.json):
```
  "jest": {
	"preset": "react-native",
	"snapshotSerializers": [],
	"collectCoverage": true,
	"setupFiles": [
	    "./test/setup-tests.js"
	],
	"transformIgnorePatterns": [
	    "node_modules/(?!(@mapbox|react-native)/)"
	]
    }
```
I had to ignore a lot of other folders from my node_modules.

**Comment by nitaliano** [comment]
great glad you got this working I'm going to close this out
