### ISSUE TITLE
Updating centerCoordinates, also resets the zoomLevel

### ISSUE THREAD

**Issue by Gp2mv3** [nitaliano/react-native-mapbox-gl#1037]
When changing the centerCoordinates props of the MapView, the zoomLevel is reset, why ?
Isn't it supposed to stay at the same zoomLevel ?

Thanks

**Comment by kristfal** [comment]
This is a rather old issue. In an effort to clean up stale issues, I'll close this. 

Please update to latest master branch and reopen if the problem persists.
