### ISSUE TITLE
Map doesn't load further zoom levels

### ISSUE THREAD

**Issue by bcalik** [nitaliano/react-native-mapbox-gl#1042]
Map doesn't load any further zoom level. What is the issue?  
I already set the access token.  

![zoom-issue](https://user-images.githubusercontent.com/9222368/36260361-3b973480-1272-11e8-8f4c-a36637e96e53.gif)

**Comment by nitaliano** [comment]
I can't reproduce this mind sharing some code?

**Comment by bcalik** [comment]
@nitaliano 
Its just a simple map. Nothing really speacial, it was working well few months ago on previous versions.
I reproduced this on two different mac's with same environment.

```javascript
const initialRegion = {
  latitude: 41.084112,
  longitude: 28.985857,
  zoomLevel: 14,
};

...

<MapboxGL.MapView
  style={{ flex: 1, flexGrow: 1 }}
  ref={(c) => { this.map = c; }}
  centerCoordinate={[initialRegion.longitude, initialRegion.latitude]}
  zoomLevel={initialRegion.zoomLevel}
  textureMode={false} // tried both true and false
>
</MapboxGL.MapView>
```

I realized that, this **only** happens on **emulator**. Not on a real device.

**My environment:**
react-native-mapbox-gl: 6.0.3-rc1
react-native: 0.53
MacOs: 10.13.3
Android Studio 3.0.1
Pixel 2 Api 26 - Android 8.0 (Google APIs) x86 - Emulator

Also some version numbers from gradle file:
```
compileSdkVersion 26
buildToolsVersion '26.0.1'
defaultConfig {
  minSdkVersion 16
  targetSdkVersion 26 
}
```

**Comment by nitaliano** [comment]
We've updated to the newest Android SDK, this shouldn't be much of a problem but things are still going to be funky with the emulator until we update to the next major SDK release that will be released in a month or two
