### ISSUE TITLE
Layer Beneath MapBox Road Labels

### ISSUE THREAD

**Issue by EricPKerr** [nitaliano/react-native-mapbox-gl#1043]
With the JavaScript SDK it is possible to add a GeoJSON ShapeSource beneath things in the core map, like city and road labels.

https://www.mapbox.com/mapbox-gl-js/example/geojson-layer-in-stack/

Is this doable in react-native SDK?  There isn't a `this.map.getStyle()` type method to get the layers object to find the lowest IDs if that's doable in the native SDK.

Thanks

**Comment by nitaliano** [comment]
There are native calls to get the layers in z-index order, this is something we can look into adding.  For now you just need to figure out what layer id you're trying to put it under and add `belowLayerID`.

I will also merge in a PR if anyone is willing to do it.

**Comment by EricPKerr** [comment]
Cool thanks - where would I look for the layerID around MapBox's code that's used for road labels?  Fine to hardcode that for now for us.

**Comment by EricPKerr** [comment]
@nitaliano what would be necessary for us to make this work?  Willing to hardcode a layerID for now, just don't know where to look for that.  Thanks!

**Comment by nitaliano** [comment]
The easiest way might be opening up mapbox studio `https://www.mapbox.com/studio` clicking on the style that you're using and looking for the layer id that way.

**Comment by EricPKerr** [comment]
@nitaliano this works well for a single map style, but becomes problematic if we're allowing users to switch styles while the app is running (night mode, showing satellite/traffic, etc).

For example, the layer IDs in `MapboxGL.StyleURL.Street` are different than `MapboxGL.StyleURL.TrafficDay` and the `belowLayerID` crashes with the "cannot be placed below (null)" error even if you switch to match the corresponding `styleURL`.  Maybe that's not syncing?

**Comment by kristfal** [comment]
This is a rather old issue. In an effort to clean up stale issues, I'll close this. 

The interim solution would be to remove all custom layers that depend on native layers before making the switch, and reapply them afterwards. I know this is not an ideal solution, so if you have any repo level improvements, I'd be happy to accept PRs.
