### ISSUE TITLE
ScrollView map freeze/image stuck

### ISSUE THREAD

**Issue by ClayChristmas** [nitaliano/react-native-mapbox-gl#1044]
I had originally tacked this on to a different issue ticket I'd opened, but I think this seems to be a distinct issue so I thought it'd make sense to open a new issue.

If you put a MapView inside of a scrollview sometimes the map glitches and instead of staying pinned to its location inside of its container it does partial updates.  I've noticed this on emulators and on hardware devices.  I've seen it on android and ios, but it seems to happen more frequently on android.  The issue happens intermittently.  The visual aspect of this glitch is probably easiest to see in the gifs below.

Here is the issue:
![mapscrollissue](https://user-images.githubusercontent.com/18467048/36326570-89686a50-1329-11e8-9e6f-60afe73c329f.gif)

Here is a gif of it working as expected with no code changes made between recordings.  I just refreshed the app:
![mapscrollworking](https://user-images.githubusercontent.com/18467048/36326595-9b63c31c-1329-11e8-8298-387aeaf08b1c.gif)

**Comment by nitaliano** [comment]
@ClayChristmas would you mind sharing a quick code sample so I can just copy and paste it into the example app?

**Comment by ClayChristmas** [comment]
Sure, thanks for the response.  I'm using a custom tile API that I can't give you a working URL for though at the minute.  This is roughly what is being rendered right now.  It is essentially a mini-map that when you click opens up a full screen map.
```
<ScrollView style={styles.container}>
    <View style={styles.viewContainer}>
        <View style={styles.mapContainer}>
            <TouchableOpacity style={{flex:1}} onPress={() => {this.props.onPress()}}>
                <Mapbox.MapView
                      styleURL={Mapbox.StyleURL.Street}
                      zoomLevel={8}
                      centerCoordinate={[Number(this.props.longitude), Number(this.props.latitude)]}
                      style={styles.map}
                      ref={(ref) => this.map = ref}
                      zoomEnabled={false}
                      pitchEnabled={false}
                      scrollEnabled={false}
                      rotateEnabled={false}
                      logoEnabled={false}
                      onPress={() => { this.onPress() }}
                      minZoomLevel={2}>
                        <Mapbox.RasterSource key='d' id='mySource' url={url} tileSize={512}>
                          <Mapbox.RasterLayer id='myLayer' sourceID='mySource' style={{rasterOpacity:0.7}} />
                        </Mapbox.RasterSource>
                        <Mapbox.ShapeSource id='currentLocationMarkerSource' shape={this.state.featureCollection}>
                          <Mapbox.SymbolLayer
                            id='currentLocationMarkerSymbols'
                            style={[mapStyles.icon, {textField:markerText}]}
                            aboveLayerID='myLayer'
                            maxZoomLevel={16}
                            />
                        </Mapbox.ShapeSource>
                  </Mapbox.MapView>
            </TouchableOpacity>
        </View>
    </View>
</ScrollView>

const styles = StyleSheet.create({
    container: {
      backgroundColor: '#0C3D54',
      flex: 1
    },
viewContainer: {
      flex: 1,
      marginLeft: 8,
      marginRight: 8,
      position: 'relative',
      height: 208,
      marginTop: 11
    },
    mapContainer: {
      flex: 1
    },
    map: {
      ...StyleSheet.absoluteFillObject
    },
};
```

The shapesource above is created when the props are received using this code:
```
if (nextProps.latitude && nextProps.longitude) {
            const centerMarker = Mapbox.geoUtils.makeFeature({ type: 'Point', coordinates: [Number(nextProps.longitude), Number(nextProps.latitude)]});
            this.setState({
              centerMarker,
              featureCollection: Mapbox.geoUtils.addToFeatureCollection(
                Mapbox.geoUtils.makeFeatureCollection(), 
                centerMarker
            )});
          }
```

**Comment by ClayChristmas** [comment]
@nitaliano - have you had any luck reproducing this issue?  Just wanted to follow up and see if you need anything additional from me or if I can do anything to help with this fix.

**Comment by nitaliano** [comment]
I was trying to reproduce this yesterday and couldn't get it to happen in my emulator

**Comment by ClayChristmas** [comment]
I believe that I have figured out what is going on with this one, and it makes sense why you couldn't reproduce it in the sample app.  We are using react-native-router-flux for routing/navigation.  We have this minimap inside a ScrollView that is the root scene.  Selecting it opens up a new scene where the map is fullscreen.  When you select the minimap and it opens the fullscreen map react-native-router-flux overlays the new scene over top of the old one but keeps the old scene alive.  The result of this is that the minimap image freezes on screen wherever it is at and overlays itself as if it is a static image overtop of the fullscreen map view.  I think that in my above example it may have been doing something similar but instead on the minimap with the fullscreen map being frozen in a weird way in the background.

We can work around this on our end for now by forcing the minimap to not render when its scene isn't in view or by forcing react-native-router-flux to kill the app, but it does seem like there may be a weird rendering issue here when you have a mapview component hidden by another component that has a mapview.  I can send screenshots if needed or integrate react-native-router-flux into the sample app and email it to you if you'd like.  I see this on physical devices also, but it seems hard to reproduce on an emulator for some reason.

**Comment by nitaliano** [comment]
@ClayChristmas yes if you could send me a sample repo with the bug in it I will look at it and get it fixed

**Comment by ClayChristmas** [comment]
@nitaliano - sorry for the delay on this.  I'll try to get you a sample app ASAP.

**Comment by nitaliano** [comment]
@ClayChristmas no problem, I also suspect that if you update to `6.1.0` or if you're on an earlier version enabling `textureMode` might fix this problem for you since it will be using a different Android view under the hood that might prevent this issue

**Comment by ClayChristmas** [comment]
@nitaliano - updating to 6.1.0 definitely fixed quite a few of the issues that we were running into.  Great job to you and the team on that release!  I did see this still occurring in 6.1.0 I believe.  Do I still need to enable textureMode, or is that something that got turned on by default in that version?

**Comment by nitaliano** [comment]
that is something that we turn on by default now, I mentioned this because someone else had a similar issue on `6.0.3` and using textureMode fixed it so it was a shot in the dark 😄

**Comment by ClayChristmas** [comment]
Haha that makes sense.  Seems worth trying either way.  I'll give it a whirl when I get a spare minute and let you know.  If not I'll put together a sample repo.

**Comment by kristfal** [comment]
This is a rather old issue. In an effort to clean up stale issues, and this seems resolved, I'll close this.
