### ISSUE TITLE
min/max zoom level has no affect

### ISSUE THREAD

**Issue by digitaldavenyc** [nitaliano/react-native-mapbox-gl#1051]
Setting `minZoomLevel` or `maxZoomLevel` does not seem to have any affect on the ability to zoom to any level. I'm on RNMBGL`v6.0.2`

**Comment by ClayChristmas** [comment]
I'm using this feature on v6.0.3 and not having any issues for maxZoomLevel.  Could you post some example code?

**Comment by nitaliano** [comment]
I just tested this out on `6.1.0` and I'm not seeing the issue going to close out
