### ISSUE TITLE
mapview with usertrackingModes = follow not center at userlocation

### ISSUE THREAD

**Issue by YKK101** [nitaliano/react-native-mapbox-gl#1052]
I'm using version 6.0.3 and when I set
```
<MapboxGL.MapView
  centerCoordinate={[100, 9]}
  userTrackingMode
  showUserLocation
/>
```
on iOS everything looks good, but on android map will center at centerCoordinate until user location has moved. How can I fix this?

**Comment by nitaliano** [comment]
Is this happening on a physical device?

**Comment by butchmarshall** [comment]
I'm also getting this on Android.  Toggling from `MapboxGL.UserTrackingModes.None` to `MapboxGL.UserTrackingModes.FollowWithHeading` sets me to some seemingly random location every time (Galaxy S7).

**Comment by YKK101** [comment]
Yes, I'm testing on xperia z5 compact with android 7.
I found that it fixed if I wait until location permission granted and update UserTrackingModes from None to Follow, but...
- animation is weird
- sometime userlocation is correct, but sometime I got my last hour location instead

**Comment by nitaliano** [comment]
It does grab the last known location initially, I'll take a look and get this fixed up. There's also `onUserLocationUpdate` now in master if you wanted to work around this you can do it with that and move the camera yourself however you would like

**Comment by kristfal** [comment]
This is a rather old issue. In an effort to clean up stale issues, I'll close this. 

For now, I'd recommend using a custom layer and custom camera logic for handling this properly cross-platform. Long term, we should probably remove all native dependencies for location and camera, and use custom layers and camera models controlled by RN instead.
