### ISSUE TITLE
Mapbox examples would not work in my developer Environment

### ISSUE THREAD

**Issue by Friis1978** [nitaliano/react-native-mapbox-gl#1053]
###### 1. Go to make a new project in the folder: 
cd desktop/projects/

###### 2. Make new project: 
react-native init mapboxdemo

###### 3. Install all the needed repos: 
npm install --save @mapbox/geo-viewport @mapbox/react-native-mapbox-gl @turf/along mapbox react-native-elements react-native-vector-icons url

###### 4. Link the vector icons: 
react-native link react-native-vector-icons

###### 5. Install Cocoapods in you ios project
Then in terminal cd to "your XCode project root directory" (where your .xcodeproj file resides) and type: pod init

###### 7. Then open your project's podfile by typing in terminal: 
open -a Xcode Podfile

Your Podfile will get open in text mode. 

###### 8. Add this to the pod file:

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'

  pod 'React', path: '../node_modules/react-native', subspecs: [
    # Comment out any unneeded subspecs to reduce bundle size.
    'Core',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTCameraRoll',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTTest',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTLinkingIOS'
  ]

  pod 'react-native-mapbox-gl', :path => '../node_modules/@mapbox/react-native-mapbox-gl'

###### 10. Then install pods into your project by typing in terminal: 
pod install

###### 11. Copy your access token from your Mapbox account in here: 
env.json, and save the file.

###### 12. Build your project on the iOs simulator: 
react-native run-ios

**Comment by Friis1978** [comment]
This example project works just fine now, just copied my github readme file in here to let others know how i did it.

**Comment by nitaliano** [comment]
cool thanks for the info glad you got it working going to close out
