### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by jsaguiar** [nitaliano/react-native-mapbox-gl#1054]
Most of the times I am getting a blank screen when running on real IOS device.

"@mapbox/react-native-mapbox-gl": "6.0.3",
"react-native": "0.53.3",

**Comment by nitaliano** [comment]
Are you seeing the Mapbox logo?

**Comment by jsaguiar** [comment]
@nitaliano no logo

**Comment by nitaliano** [comment]
I haven't been able to reproduce the issue can you show me your styles that your parent container has, and what you're passing into the MapView

**Comment by jsaguiar** [comment]
mainMap: https://gist.github.com/jsaguiar/a5280e35dc213f8c84a2b092478979d6
parent: https://gist.github.com/jsaguiar/e359dd228492180eb5f0d04237c0d0f1

**Comment by jsaguiar** [comment]
it seams to be fixed in master.

**Comment by nitaliano** [comment]
I haven't been able to reproduce this yet on both versions. It seems like it's fixed for you and we'll be doing a release of master tomorrow so I'll be closing this out

**Comment by williamdarkocode** [comment]
I am getting a black screen with the mapbox logo at the bottom of the screen. Any help?

**Comment by scalactic** [comment]
Hi @williamdarkocode,
Change your mapbox sdk version in ../nodemodules/@mapbox/rea.....box-gl/android/rctml/build.gradle. It is currently @5.4.1. Change it to 5.5.3.

**Comment by williamdarkocode** [comment]
I found a solution to the black screen problem. When you define the styleUrl variable do this: 
cont {StyleURL} = ''url";

But, the correct map doesnt show for me..

**Comment by sandunadhikari** [comment]
#jsaguiar
sometimes show black screen without mabbox logo when  disabled wifi connection

**Comment by islamabujamea** [comment]
I have black screen with mapbox logo too !! please how i can solve this problem ! :(

**Comment by williamdarkocode** [comment]
@islamabujamea unfortunately I gave up on this problem, and the project, about a year ago. The tech is just too poorly maintained, and recently apparently, maintenance was handed over to the community.
