### ISSUE TITLE
Android timing crash

### ISSUE THREAD

**Issue by davidpricedev** [nitaliano/react-native-mapbox-gl#1055]
I found a very similar previous issue: https://github.com/mapbox/mapbox-gl-native/issues/10711

I believe this to be Android-only.

I can get this to happen pretty reliably by loading up my app with the map in view (or at least loaded up at some point) and leaving the app run for ~5-10 minutes. Then when I try to do anything with the app it crashes with the error below. This happens on both debug and release builds.

Let me know if I can provide any further info.

Relevant Versions: 

* Android SDK: 27
* react-native@0.51.0
* @mapbox/react-native-mapbox-gl@6.0.3

(maybe relevant?):

* react-navigation@1.0.0-beta.22
* native-base@2.3.5

#### Error

com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.GLSurfaceViewMapRenderer.<init>
GLSurfaceViewMapRenderer.java - line 27
java.lang.IllegalStateException: setRenderer has already been called for this instance.
setRenderer has already been called for this instance.
android.opengl.GLSurfaceView.checkRenderThreadState GLSurfaceView.java:1893
android.opengl.GLSurfaceView.setEGLContextClientVersion GLSurfaceView.java:473
com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.GLSurfaceViewMapRenderer.<init> GLSurfaceViewMapRenderer.java:27
com.mapbox.mapboxsdk.maps.MapView$6.<init> MapView.java:318
com.mapbox.mapboxsdk.maps.MapView.initialiseDrawingSurface MapView.java:318
com.mapbox.mapboxsdk.maps.MapView.access$100 MapView.java:70
com.mapbox.mapboxsdk.maps.MapView$1.onGlobalLayout MapView.java:143
android.view.ViewTreeObserver.dispatchOnGlobalLayout ViewTreeObserver.java:945
android.view.ViewRootImpl.performTraversals ViewRootImpl.java:2262
android.view.ViewRootImpl.doTraversal ViewRootImpl.java:1410
android.view.ViewRootImpl$TraversalRunnable.run ViewRootImpl.java:6834
android.view.Choreographer$CallbackRecord.run Choreographer.java:966
android.view.Choreographer.doCallbacks Choreographer.java:778
android.view.Choreographer.doFrame Choreographer.java:713
android.view.Choreographer$FrameDisplayEventReceiver.run Choreographer.java:952
android.os.Handler.handleCallback Handler.java:789
android.os.Handler.dispatchMessage Handler.java:98
android.os.Looper.loop Looper.java:164
android.app.ActivityThread.main ActivityThread.java:6809
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.Zygote$MethodAndArgsCaller.run Zygote.java:240
com.android.internal.os.ZygoteInit.main ZygoteInit.java:767

**Comment by nitaliano** [comment]
Can you try adding `textureMode` to your map and seeing if it helps solve the problem

**Comment by davidpricedev** [comment]
Yes, that does seem to prevent this from occurring.

**Comment by nitaliano** [comment]
what's happening here is there are two view options available on Androind. GLSurfaceView and TextureView. The default is set to GLSurfaceView because it is slightly more performant but it has been a nightmare to keep that view from not randomly crashing. IMO TextureView is much more stable and could become the future default Android view to avoid these types of issues.

GLSurfaceView's are better off in applications that have multiple Activities in the native code. React Native runs in a single Activity making the GLSurfaceView lifecycle behave weird sometimes. TextureView behaves more similar in lifecycle to a regular view and fits in with React Native more
