### ISSUE TITLE
Android freeze when re-enter android if the view have been unmounted first.

### ISSUE THREAD

**Issue by ricardochen** [nitaliano/react-native-mapbox-gl#1056]
"@mapbox/react-native-mapbox-gl": "^6.0.3"

Steps to reproduce:
Open app and load MainScreen with mapboxview.
Do some navigation to anotherScreen and MainScreen fires componentWillUnmount()
Go back to MainScreen from anotherScreen ( good so far)
Close the app
Reopen, white screen and freezes entire phone.

Real phone: Huawei p9 plus

**Comment by jussirantala** [comment]
I'm having the same problem with RN 0.53.0, react-native-mapbox-gl ^6.0.3, Android SDK 26 and Android 7.0
Stack trace: https://pastebin.com/raw/NzvNH4Ur

**Comment by nitaliano** [comment]
What you are experiencing is related to this issue https://github.com/mapbox/react-native-mapbox-gl/issues/925 and there is a PR out that seems to help solve the issue for newer device https://github.com/mapbox/react-native-mapbox-gl/pull/1033 I'm going to close this issue out as a duplicate so we can keep all the discussion for this issue in one ticket. I would also recommend trying the PR I mentioned above out to see if it helps the issue.

Thanks for reporting!
