### ISSUE TITLE
setCamera not centered to correct coords

### ISSUE THREAD

**Issue by benjaminkoetting** [nitaliano/react-native-mapbox-gl#1057]
sometimes when I call setCamera function with this code:

```
this.map.setCamera({
        centerCoordinate: coords,
        zoom: 12,
        duration: 0,
      })
```

the map is centered, but the lng, lat are in the right bottom corner, the coords
are checked and ok. On the atteched screenshot the green Element on the
right bottom corner is the coords which used in the function and set by the simulator.

It happend on physical devices too. I cannot see any trigger when its happend, after reloading the bundle or reopen the app it is working again.

During a "bad" session" I can call the function and everytime it is centered to
the wrong destination.

![simulator screen shot - iphone se - 2018-02-21 at 10 39 33](https://user-images.githubusercontent.com/5013404/36473059-c0a4a60a-16f3-11e8-8ac6-a6f3a6a0a75f.png)

**Comment by EricPKerr** [comment]
Are you updated to `master` or `6.0.3`?  This was fixed in https://github.com/mapbox/react-native-mapbox-gl/pull/1050

**Comment by bemazo** [comment]
at the moment 6.0.3-rc1 is installed

**Comment by nitaliano** [comment]
@bemazo mind testing out master to see if it fixes your issue? I believe you are experiencing the map extending past it's parent bounds like @EricPKerr mentioned, and it has been resolved on `master`

**Comment by benjaminkoetting** [comment]
@nitaliano I updated yesterday to the master branch and will test it, in the past hours I don't get the error again.

**Comment by EricPKerr** [comment]
@nitaliano potentially worth cutting off the current issues done in the `6.0.4` Project for an interim release?

**Comment by nitaliano** [comment]
I'll cut a npm beta release sometime this weekend

**Comment by nitaliano** [comment]
Going to close this issue out feel free to reopen @bemazo if you run into it again. I'll post back here once we have the next release out
