### ISSUE TITLE
v6.0.3 ANDROID upgrade

### ISSUE THREAD

**Issue by GuillotJessica** [nitaliano/react-native-mapbox-gl#1060]
Hello everyone and @nitaliano ,
I did the following command and get the following result 

```
C:\Users\BABAO\Work\Mobile2Store>npm update @mapbox/react-native-mapbox-gl --save
> @mapbox/react-native-mapbox-gl@6.0.3 preinstall C:\Users\BABAO\Work\Mobile2Store\node_modules\@mapbox\react-native-mapbox-gl
> npm run fetch:ios:sdk


> @mapbox/react-native-mapbox-gl@6.0.3 fetch:ios:sdk C:\Users\BABAO\Work\Mobile2Store\node_modules\@mapbox\react-native-mapbox-gl
> node ./scripts/download-mapbox-gl-native-ios-if-on-mac.js 3.7.3

+ @mapbox/react-native-mapbox-gl@6.0.3
added 1 package, removed 1442 packages and updated 4 packages in 135.918s

```

### and then 
> > cd android/ && gradlew clean && cd ..
> 
> Incremental java compilation is an incubating feature.
> Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
> java.lang.IllegalStateException: buildToolsVersion is not specified.
> 	at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
> 	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:645)
> 	at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:608)
> 	at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:605)
> 	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
> 	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
> 	at com.android.build.gradle.BasePlugin.lambda$createTasks$1(BasePlugin.java:603)
> 	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:93)
> 	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:82)
> 	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
> 	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
> 	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
> 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
> 	at com.sun.proxy.$Proxy12.afterEvaluate(Unknown Source)
> 	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
> 	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:61)
> 	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:540)
> 	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:93)
> 	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:47)
> 	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
> 	at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:124)
> 	at org.gradle.internal.Factories$1.create(Factories.java:22)
> 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
> 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
> 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:121)
> 	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
> 	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
> 	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
> 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
> 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
> 	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
> 	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
> 	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
> 	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
> 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
> 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
> 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
> 	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
> 	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
> 	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
> 	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
> 	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
> 	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
> 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:239)
> 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:212)
> 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
> 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
> 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
> 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
> 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:205)
> 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
> 	at org.gradle.launcher.Main.doAction(Main.java:33)
> 	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
> 	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
> 	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
> 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
> 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file 'C:\Users\BABAO\Work\Mobile2Store\android\app\build.gradle' line: 75
> 
> * What went wrong:
> A problem occurred evaluating project ':app'.
> > Could not read script 'C:\Users\BABAO\Work\Mobile2Store\node_modules\react-native\react.gradle' as it does not exist.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 6.577 secs
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! Mobile2Store@0.0.1 clean:android: `cd android/ && gradlew clean && cd ..`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the Mobile2Store@0.0.1 clean:android script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\BABAO\AppData\Roaming\npm-cache\_logs\2018-02-21T15_29_38_849Z-debug.log
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! Mobile2Store@0.0.1 cleanAll: `npm run clean && npm run clean:android`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the Mobile2Store@0.0.1 cleanAll script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\BABAO\AppData\Roaming\npm-cache\_logs\2018-02-21T15_29_38_890Z-debug.log
> 
> Process finished with exit code 1
>
>
> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file 'C:\Users\BABAO\Work\Mobile2Store\android\app\build.gradle' line: 75
> 
> * What went wrong:
> A problem occurred evaluating project ':app'.
> > Could not read script 'C:\Users\BABAO\Work\Mobile2Store\node_modules\react-native\react.gradle' as it does not exist.

##android\app\build.gradle' line: 75 I've got this
`apply from: "../../node_modules/react-native/react.gradle"`

Any idea is welcome

**Comment by nitaliano** [comment]
This error is saying it can't find React Native, I would `rm -rf node_modules` and also `rm -rf ~/.rncache/*` then try a fresh `npm i`, then clean your project and build and hopefully the error should go away. I've run into this error before on Android

Going to close out, if you need help ping me in Gitter would be happy to help out
