### ISSUE TITLE
iconAnchor crash

### ISSUE THREAD

**Issue by bojanjukic** [nitaliano/react-native-mapbox-gl#1061]
Hey. 

I am trying to fix the icon while zooming to the bottom end and not to the center and I have found the icon-anchor option for the stylesheet.

`const styles = MapboxGL.StyleSheet.create({
    icon: {
        iconAnchor: 'bottom',
        iconAllowOverlap: true,
        iconSize: Platform.OS === 'android' ? 0.25 : 0.10,
    },
});`

As soon as I add iconAnchor my app crashes: 
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSTaggedPointerString getValue:]: unrecognized selector sent to instance 0xa007265746e65636'

It seems that iconAnchor is not yet implemented in the react native library. Please check. 

Thank you!

**Comment by nitaliano** [comment]
@GituBojan you need to use the enums on the `MapboxGL` object give a try `MapboxGL.IconAnchor.Bottom` and it should work. The reason why we use the enums instead of strings directly is the Android and iOS SDKs take different values, so on Android it looks for a string but on iOS it looks for an integer

Going to close this out, if it does not work please reopen

**Comment by fmelp** [comment]
Sorry Nick, but doesn't work even with the enum... MapboxGL.IconAnchor.Bottom returns undefined

**Comment by nitaliano** [comment]
I just gave it a shot and all the values are populated for me
<img width="219" alt="screenshot 2018-03-26 13 39 04" src="https://user-images.githubusercontent.com/1761993/37931608-11add5e6-30fb-11e8-8fa0-d9d3228f04f0.png">

I'm wondering is it possible that you have two Mapbox frameworks included in your project somehow?

**Comment by fmelp** [comment]
hey Nick, thanks for the response. I think I'm running an old version of mapbox then. 6.0.1 according to my package.json. Tried upgrading to latest but breaks my whole app. oh well I can live without it

**Comment by nitaliano** [comment]
I would recommend being on `6.1.0` even if you have to fix some issues, it's very stable compared to `6.0.1`
