### ISSUE TITLE
MapView not rendering consistently at the correct size

### ISSUE THREAD

**Issue by webermn15** [nitaliano/react-native-mapbox-gl#1065]
Hello!

I'm simply trying to render a map in a View container, and without changing anything, each time I refresh my simulator there is a chance that the map renders larger than the container it's supposed to be inside. I've tested this using iPhone 8 in Xcode's simulator & on my own 6s.

These are the two ways it renders: 
Correct:
![screen shot 2018-02-23 at 9 18 22 am](https://user-images.githubusercontent.com/32818398/36601517-ea5b7040-187a-11e8-979c-030da5658d4d.png)

Incorrect:
![screen shot 2018-02-23 at 9 18 13 am](https://user-images.githubusercontent.com/32818398/36601535-f5d40ee6-187a-11e8-9059-d6e5819a875e.png)

"@mapbox/react-native-mapbox-gl": "^6.0.3"
"react": "16.2.0"
"react-native": "0.53.3"

iOS 11, using latest Mapbox SDK 

I'm simply using a bit of sample code from https://www.mapbox.com/help/first-steps-react-native-sdk/

```javascript      
import React, { Component } from 'react';
import { StyleSheet, TextInput, Text, View, Button } from 'react-native';
import styles from './styles';
import MapboxGL from '@mapbox/react-native-mapbox-gl';

MapboxGL.setAccessToken('pk.eyJ1Ijoid2ViZXJtbjE1IiwiYSI6ImNqZHl3N3k2eDBhNXkyeG1vdzhtanRwczMifQ.5q5Lm4AZSLn2DBNi5s2izQ');

export default class HuntCreate extends Component<{}> {
  render() {
    return (
      <View style={styles.huntCreate}>
        <View style={{flex: 1}}>
        	<Text>Form element placeholder</Text>
          <Button 
            title={'Create'} 
            onPress={this.props.handleCreate}
          />
        </View>
        <View style={{flex: 2}}>
          <MapboxGL.MapView
              styleURL={MapboxGL.StyleURL.Street}
              zoomLevel={15}
              centerCoordinate={[11.256, 43.770]}
              style={{flex: 1}}>
          </MapboxGL.MapView>
        </View>
      </View>
    );
  }
}

```

Thanks!

**Comment by nitaliano** [comment]
This was fixed on master a few days ago https://github.com/mapbox/react-native-mapbox-gl/pull/1050 another npm release will land this weekend
