### ISSUE TITLE
How to implement clusters using markers

### ISSUE THREAD

**Issue by SunSet1219** [nitaliano/react-native-mapbox-gl#1066]
I am going to make cluster using custom markers #
![image 7](https://user-images.githubusercontent.com/26632694/36620379-9e80b3b0-18a7-11e8-963c-00d278f54f77.png)

I want like this...
![img_e2408](https://user-images.githubusercontent.com/26632694/36620534-62577a94-18a8-11e8-9e17-2a6b84b9a9bf.JPG)

**Comment by nitaliano** [comment]
Follow this example and swap out the circle layers for symbol layers.

https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/EarthQuakes.js

Use token strings to refer to a different image in your single point layer like this example
https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/ShapeSourceIcon.js#L13

**Comment by SunSet1219** [comment]
@nitaliano I didn't catch you.
I hope to let me know how to use Mapbox.ShareShource without geoJson data.
I am using like this.
![image 2](https://user-images.githubusercontent.com/26632694/36635453-bfc53182-1969-11e8-8188-a410d7651694.png)

react-native-mapbox-gl: 6.0.1,
RN version: 0.43.4,
device: iPhone

how to make custom marker using React component?
Each markers is not same.

**Comment by lpfunding** [comment]
@nitaliano can you show us a simple example of this? I'm not following you 100%
