### ISSUE TITLE
PointAnnotations Infinite Loop

### ISSUE THREAD

**Issue by digitaldavenyc** [nitaliano/react-native-mapbox-gl#1068]
I recently started using the methods on `PointAnnotations`; `onSelected` and `onDeselected`. It seems like `onSelected` is being called somehow without interacting on the map, it seems to get stuck in an infinite loop of selecting and deselecting. 

I know what your probably thinking, I have some race condition causing it but I've looked through my code for the past few hours and I can't find anything that could cause this. Also I can see `onSelected` being called in console logs. I'll include my source code below.

My stack:
```
"@mapbox/react-native-mapbox-gl": "6.0.3"
"react-native": "0.53.0"
"react": "16.2.0"
```

```
render() {
       return (
		<Mapbox.MapView ref={map => { this._map = map }}
			style={{width: this.state.width, height: this.state.height}}
			onRegionDidChange={this.onRegionDidChange}
		>
			{this.onRenderAnnotations()}
		</Mapbox.MapView>
       )
}

onRenderAnnotations() {
		if(!this.props.store.explore.events) {
			return null
		}
		return this.props.store.explore.events.map((event, index) => {
			let isSelected = !!this.props.selected && this.props.selected.id === event.id
	
			return (
				<Mapbox.PointAnnotation key={event.id}
					id={event.id}
					coordinate={event.location}
					selected={isSelected}
					onSelected={() => {this.onOpenAnnotation(event)}}
					onDeselected={() => {this.onCloseAnnotation(event)}}
				>
					<View style={{width: 16, height: 23}}>
						<Image source={isSelected ? markerSelected : marker}
							style={{width: 16, height: 23}}
						/>
					</View>
				</Mapbox.PointAnnotation>
			)
		})
	}

onOpenAnnotation(event, i) {
	console.log('onOpenAnnotation') 
	_this.props.onPreview(event)
}

onCloseAnnotation(event) {
	console.log('onCloseAnnotation')
	_this.props.onPreview(null)
}
```

At no point in the below video am I touching the Map

![giphy](https://user-images.githubusercontent.com/243799/36638628-53032a9a-19c8-11e8-8dcb-b54911ec136f.gif)

Console Logs, you can clearly see that isSelected is set to `null` and the `onOpenAnnotation` is called selecting causing a marker to be selected.

```
isSelected: null false
isSelected: null false
isSelected: null false
onOpenAnnotation i: Object {geometry: Object, properties: Object, type: "Feature"}
isSelected: bcf5336b-4410-4bd4-b94a-35197c4ffeba false
isSelected: bcf5336b-4410-4bd4-b94a-35197c4ffeba true
isSelected: bcf5336b-4410-4bd4-b94a-35197c4ffeba false
onCloseAnnotation
```

A couple of questions:

1. Is it possible for `onSelected` to be called without a user interaction?
2. Are there any events in the MBGL framework fired after `onDeselected`?

**Comment by digitaldavenyc** [comment]
I ran a test without using `MapView.onSelected` and just wrapped the annotation in a `TouchableOpacity` and this issue does not occur. I would just use this approach but deselecting a marker is a bit glitchy.

**Comment by kristfal** [comment]
This is a rather old issue. In an effort to clean up stale issues, and considering it seems resolved, I'll close this.
