### ISSUE TITLE
How to make clusters without geoJson Data?

### ISSUE THREAD

**Issue by SunSet1219** [nitaliano/react-native-mapbox-gl#1069]
I am using like this.
![image 2](https://user-images.githubusercontent.com/26632694/36639489-b7671754-19c2-11e8-85cc-73ab20e3053d.png)
there is only coodinates and emojicon name(from database)
so I cannot use geoJson.
I would like to let me know more details about solutions.
react-native-mapbox-gl: 6.0.3,
RN version: 0.43.4,
device: iPhone

how to make custom marker using React component?
Each markers is not same.

**Comment by krvajal** [comment]
You can definitively use geojson by transforming your array of coordinates and icons to a geojson object.
For example: 
```
export function itemToGeoJSONPoint(item) {
  return {
    type: "Feature",
    geometry: {
      type: "Point",
      coordinates: item.coord
    },
    properties: item
  };
}

const geoJSONItems = items.map(itemToGeoJSONPoint);
```
And then you can use something like [supercluster](https://github.com/mapbox/supercluster) to cluster the points to be shown on the map.
