### ISSUE TITLE
fitBounds doesn't work right after setting pitch and heading

### ISSUE THREAD

**Issue by jussirantala** [nitaliano/react-native-mapbox-gl#1074]
Steps to reproduce
`        this.mapRef.setCamera({
          stops: [
            { pitch: 45, duration: 500 },
            { heading: 45, duration: 500 },
          ]
        });`
`// wait until animations finish `
`          this.mapRef.fitBounds(
            [20, 70],
            [30, 59],
            [50, 50, 50, 50],
            500
          );`

The fitBounds method doesn't fit to given bounds but does something and sets the pitch and heading to zero. After calling it again with the same parameters, it will do the job properly. As a workaround, I set pitch and heading to zero before calling fitBounds.

react-native 0.53, android 7.0, genymotion and a physical device, SDK 26

**Comment by jussirantala** [comment]
Also happens with RN 0.54, react-native-mabpx-gl 6.1.0

**Comment by kristfal** [comment]
This is a rather old issue. In an effort to clean up stale issues, I'll close this. 

Please update to latest master branch and reopen if the problem persists.
