### ISSUE TITLE
How to detect if user has panned/dragged the map?

### ISSUE THREAD

**Issue by dpyeates** [nitaliano/react-native-mapbox-gl#1079]
Is it possible to detect when the user has panned/dragged the map? 
I need to trigger a mode change from auto tracking to manual if the user interacts with the map....

**Comment by nitaliano** [comment]
That's built into the sdk if you use `userTrackingMode` there is a callback called `onUserTrackingModeChange`.

If you do want to do this manually you can listen for `onRegionDidChange` events and look for the `isUserInteraction` property https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/ShowRegionDidChange.js#L82. This will be `true` every time a user gesture caused the map camera to move

**Comment by DavoCg** [comment]
I don't know why but isUserInteraction seems to be always undefined.

I'm using version 6.0.1

**Comment by nitaliano** [comment]
Its not in 6.0.1 try 6.1.0 or 6.0.3

**Comment by jshearer** [comment]
Hi there,

Is this broken again? I don't seem to be getting any callbacks to `onUserTrackingModeChange`. I set tracking mode to follow, then pan the map away, and no callback.

Using
```
"@mapbox/react-native-mapbox-gl": "^6.1.1"
```

**Comment by jshearer** [comment]
@nitaliano FYI, in case you don't get notified for comments on closed issues.

I also tried `onRegionDidChange`, and get no events:

``` javascript
<Mapbox.MapView
                        styleURL={"mapbox://styles/..."}
                        zoomLevel={15}
                        centerCoordinate={shape.features[0] ? shape.features[0].geometry.coordinates[0][0] : [-35.15165038, 40.6235728]}
                        style={{flex:1}}
                        ref={(ref)=>this.map = ref}
                        //userTrackingMode={this.state.userTrackingMode}
                        //onUserTrackingModeChange={this.onTrackingUpdate.bind(this)}
                        onRegionDidChange={(features) => {
                            console.log(features);
                            if(features.properties.isUserInteraction){
                                this.setState({
                                    userTrackingMode: Mapbox.UserTrackingModes.None 
                                })
                            }
                        }}
/>
```
