### ISSUE TITLE
Capture touch on map to add marker at said coordinates

### ISSUE THREAD

**Issue by JoaoCnh** [nitaliano/react-native-mapbox-gl#108]
Is there a way to catch a user tap or even dragging the marker to certain coordinates?

If the user taps it would create the annotation there?

**Comment by bsudekum** [comment]
This is upstream right now https://github.com/mapbox/mapbox-gl-native/pull/2280

**Comment by JoaoCnh** [comment]
So it isn't implemented yet on this right? 

from what I understood it says they added those methods for iOS

**Comment by bsudekum** [comment]
This has not yet been implemented on iOS.

**Comment by friedbunny** [comment]
Though I don't know if the required functions are hooked here in reactland, [this example](https://www.mapbox.com/ios-sdk/examples/point-conversion/) demonstrates the currently recommended way to capture taps and convert to geographic coordinates.
