### ISSUE TITLE
Camera state race conditions

### ISSUE THREAD

**Issue by kristfal** [nitaliano/react-native-mapbox-gl#1082]
Updating `userTrackingMode`, `userLocationVerticalAlignment`, `bearing` and/or `pitch` at the same time causes one or more of the params to not be activated. Ex: Setting pitch to 40 when altering `userTrackingMode` and `userLocationVerticalAlignment` randomly sets the pitch, but other times fail.

When changing `userLocationVerticalAlignment`, iOS will instantly update the camera offset. Android doesn't, and requires a location update before the new `userLocationVerticalAlignment` setting is applied to the camera.

Code to reproduce both issues:
```js
const computeVerticalAlignment = mode => {
  switch (mode) {
    case MapboxGL.UserTrackingModes.FollowWithCourse:
      return MapboxGL.UserLocationVerticalAlignment.Bottom;
    default:
      return MapboxGL.UserLocationVerticalAlignment.Center;
  }
};

const computePitch = mode => {
  switch (mode) {
    case MapboxGL.UserTrackingModes.FollowWithCourse:
      return 40;
    default:
      return 0;
  }
}

<MapboxGL.MapView
        userLocationVerticalAlignment={computeVerticalAlignment(geolocateMode)}
        userTrackingMode={geolocateMode}
        pitch={computePitch(geolocateMode)}
/ >
```

For the code example above, iOS will apply the correct vertical offset as the `userTracingMode` is changed to and from `FollowWithCourse`. Android requires a new location update between changes for the vertical offset to apply.

**Comment by giantss** [comment]
@kristfal hey. #1408 Is this effect made on android? I also want to do the same effect.

**Comment by kristfal** [comment]
Closing as we'll need to control this from RN side to achieve cross-platform parity.
