### ISSUE TITLE
Access Token

### ISSUE THREAD

**Issue by danyeah** [nitaliano/react-native-mapbox-gl#1083]
Hello
Im trying to use the react native package, after hours of debugging (couldn't get the app running) i finally managed to get it working but now im stuck with:

"Using mapview requires setting a valid access token. Use mapbox.getIsnstance(Context context, String accessToken) to provide one.

I created the accesstoken file and i even tried with:
`import MapboxClient from 'mapbox';

const client = new MapboxClient('accessToken_string_here');`

But i still get the same error (i tried building the example app but it fails)

Any idea of what i am missing?

**Comment by nitaliano** [comment]
You need to set this https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/App.js#L93

**Comment by danyeah** [comment]
Thanks for the answer, that worked perfectly, now it works but all I'm seeing is a blank map
![screenshot_1520008732](https://user-images.githubusercontent.com/1651415/36910352-c077e1a2-1e40-11e8-8c66-3d9c82001423.png)
Any reason why I'm seeing this?
Im using the code in the Drive the line example, tried both on a phisical device and emulator still get the same blank screen. (tried with API 26 and API 23)

**Comment by nitaliano** [comment]
try adding `textureMode` as a prop on your map

**Comment by dviluk** [comment]
Hi!, same problem here. Blank map with logo. 
`textureMode` prop on <MapboxGL.MapView />? 
does not work and this prop does not exist.

[logcat](https://gist.github.com/dviluk/23359f62cf381f8d56af60bdc5ce3a8b)

Clean installation.
Android Emulator API 23.

```
  "dependencies": {
    "@mapbox/react-native-mapbox-gl": "^6.1.0",
    "react": "16.3.0-alpha.1",
    "react-native": "0.54.2",
    "react-native-mapbox-gl": "6.1.0"
  },
```

thank you!

Edited:
Here probably the solution: https://github.com/mapbox/react-native-mapbox-gl/issues/1041#issuecomment-375381751
