### ISSUE TITLE
Release 6.0.4

### ISSUE THREAD

**Issue by Gp2mv3** [nitaliano/react-native-mapbox-gl#1085]
Hi,
When do you think the next version will be released ?
You are merging a lot of great stuff that were available in previous version and that we want in this new one.

thanks !

**Comment by nitaliano** [comment]
We'll be releasing what is on master today

**Comment by nitaliano** [comment]
I forgot to mention this before but I'm going to be renaming `6.0.4` to `6.1.0` because on Android the default view will be a `TextureView` instead of the `GLSurfaceView`

**Comment by nitaliano** [comment]
https://github.com/mapbox/react-native-mapbox-gl/pull/1091#issuecomment-370096933
