### ISSUE TITLE
Caching tiles of the map

### ISSUE THREAD

**Issue by sroze** [nitaliano/react-native-mapbox-gl#1087]
Is it possible to cache the tiles that have been loaded by the map? 

I don't really know which region to ["pack" using the Offline manager](https://github.com/mapbox/react-native-mapbox-gl/blob/master/docs/OfflineManager.md#createpackoptions-progresslistener-errorlistener) but I'd love to keep the map background tiles in the cache once they've been loaded.

Thank you ❤️

**Comment by nitaliano** [comment]
@sroze the only fool proof way to cache tiles would be to use the `offlineManager` to create a pack. If you need any help with using the `offlineManager` let me know! You can figure out regions and such without actually having the map on the screen by using https://github.com/mapbox/geo-viewport#boundsviewport-zoom-dimensions-tilesize

The tiles that have been loaded on the map(not using `offlineManager`) are already being cached by Mapbox but that is just an intermittent cache.

**Comment by sroze** [comment]
I see. That's not the most convenient but I guess it would work. I guess what would be nice is to be able to have a sort TTL on the packs if they are not used, but obviously tricky. Would you be interested in reviewing/merging such feature in the library?

**Comment by nitaliano** [comment]
If this can be done in an elegant way on both platforms, we can merge a feature like this into `master`

**Comment by nitaliano** [comment]
I'm going to close this out if you want to send a PR/discussion about TTL offline packs we can open a another ticket with a proposal
