### ISSUE TITLE
Android example not working

### ISSUE THREAD

**Issue by erickreutz** [nitaliano/react-native-mapbox-gl#109]
- Followed all the steps in install.md for android.
- Copied example.js line for line.
- Added my access token

I've got a blank white screen with a red border. Any ideas?

package.json

``` json
{
  "name": "AwesomeProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node_modules/react-native/packager/packager.sh"
  },
  "dependencies": {
    "react-native": "^0.12.0",
    "react-native-mapbox-gl": "^1.0.0"
  }
}
```

logs

```
❯ adb logcat "*:S ReactNative:V ReactNativeJS:V"
--------- beginning of main
--------- beginning of system
10-20 19:52:10.807  2418  2437 W ReactNativeJS: 'Warning: Native component for "RCTModalHostView" does not exist'
10-20 19:52:10.864  2418  2437 W ReactNativeJS: 'Warning: Native component for "RCTMapbox" does not exist'
10-20 19:52:10.891  2418  2437 D ReactNativeJS: 'Running application "AwesomeProject" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF'
10-20 19:52:31.378  2418  2453 W ReactNativeJS: 'Warning: Native component for "RCTModalHostView" does not exist'
10-20 19:52:31.452  2418  2453 W ReactNativeJS: 'Warning: Native component for "RCTMapbox" does not exist'
10-20 19:52:31.455  2418  2453 D ReactNativeJS: 'Running application "AwesomeProject" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF'
```

screenshot
![image](https://cloud.githubusercontent.com/assets/59875/10626497/80e4aa5a-7764-11e5-8d1e-b41b6e2cc055.png)

**Comment by bsudekum** [comment]
Can you confirm that you `import`'ed 

```
import com.mapbox.reactnativemapboxgl.ReactNativeMapboxGLPackage;
```

ref step 4 https://github.com/mapbox/react-native-mapbox-gl/blob/master/android/install.md#step-4---register-react-package

**Comment by erickreutz** [comment]
Yes I have

``` java
...
import com.facebook.react.modules.core.DefaultHardwareBackBtnHandler;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;
import com.mapbox.reactnativemapboxgl.ReactNativeMapboxGLPackage;

public class MainActivity extends Activity implements DefaultHardwareBackBtnHandler {

    private ReactInstanceManager mReactInstanceManager;
    private ReactRootView mReactRootView;
...
```

**Comment by bsudekum** [comment]
To me this smells like something was missed during the install process.

**Comment by erickreutz** [comment]
Missed this step!

`.addPackage(new ReactNativeMapboxGLPackage()) // <-- Register package here`

**Comment by naveed89** [comment]
dear im getting sam eerror while reloading the emulator,

Running application "main" with appParams: {"initialProps":{"exp":{"initialUri":"exp://192.168.1.33:19000","manifest":{"isVerified":true,"version":"1.0.0","loading":{"iconUrl":"http://192.168.1.33:19001/assets/./assets/icons/loading-icon.png","icon":"./assets/icons/loading-icon.png"},"slug":"my-new-project","name":"my-new-project","iconUrl":"http://192.168.1.33:19001/assets/./assets/icons/app-icon.png","developer":{"tool":"xde","projectRoot":"E:\\MCS\\React Native\\Projects\\my-new-project"},"xde":true,"sdkVersion":"21.0.0","id":"@aziz89/my-new-project","mainModuleName":"node_modules/expo/AppEntry","packagerOpts":{"lanType":"ip","dev":true,"urlType":"exp","hostType":"lan","strict":false,"minify":false,"urlRandomness":"34-wwe"},"ios":{"supportsTablet":true},"bundleUrl":"http://192.168.1.33:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&strict=false&minify=false&hot=false&assetPlugin=E:\\MCS\\React Native\\Projects\\my-new-project\\node_modules\\expo\\tools\\hashAssetFiles","description":"An empty new project","orientation":"portrait","primaryColor":"#cccccc","privacy":"public","logUrl":"http://192.168.1.33:19000/logs","icon":"./assets/icons/app-icon.png","env":{},"debuggerHost":"192.168.1.33:19001"},"shell":false}},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
![screenshot_1514409050](https://user-images.githubusercontent.com/33197194/34393481-98a7a404-eb74-11e7-8df0-0bdb672efb15.png)

please help me i am new
