### ISSUE TITLE
Project with path ':mapbox-react-native-mapbox-gl' could not be found in project ':app'.

### ISSUE THREAD

**Issue by mealbarracin10** [nitaliano/react-native-mapbox-gl#1092]
hi, i tried install mapbox with android and ios, recently i create a app , with react-native init geroApp,  and try install  library mapbox, but after executed command  "npm install @mapbox/react-native-mapbox-gl@6.0.0-beta1 --save" and include this lot in Project builder " jcenter()
maven { url "$rootDir/../node_modules/react-native/android" }
        maven { url "https://jitpack.io" }
        maven { url "https://maven.google.com "
this show this error 
when try include add to app:build.gradle
 build.gradle compile project(':mapbox-react-native-mapbox-gl') throw this error "Gradle sync failed: Project with path ':mapbox-react-native-mapbox-gl' could not be found in project ':app'.
				Consult IDE log for more details (Help | Show Log)"

![captura de pantalla 2018-03-04 a la s 10 57 54 p m](https://user-images.githubusercontent.com/11824876/36957029-8ec7d976-1fff-11e8-8fa7-23d0cb7aa9b6.png)
![captura de pantalla 2018-03-04 a la s 10 58 05 p m](https://user-images.githubusercontent.com/11824876/36957030-8ee4ab14-1fff-11e8-8a8b-63b2736d3ee0.png)

**Comment by nitaliano** [comment]
Did you also add Mapbox to your settings.gradle https://github.com/mapbox/react-native-mapbox-gl/blob/master/android/install.md#settingsgradle?

**Comment by lintelbeam** [comment]
@nitaliano 
It's working well. Thanks

**Comment by grigvardanyan** [comment]
Hi, 
I have same issue . I am using it from react native.
I have added all necessary  options(from Documentation) but still wasnt able to run.
Please Could you help me?
![allprojects](https://user-images.githubusercontent.com/26326278/54276635-3b676e80-45a7-11e9-8bc0-4013e46e3b9d.PNG)
![dependencies](https://user-images.githubusercontent.com/26326278/54276638-3b676e80-45a7-11e9-99d5-4381f3a5d245.PNG)

![settigns](https://user-images.githubusercontent.com/26326278/54276665-4f12d500-45a7-11e9-83f1-eae943b2c989.PNG)

**Comment by dkotowicz** [comment]
> Hi,
> I have same issue . I am using it from react native.
> I have added all necessary options(from Documentation) but still wasnt able to run.
> Please Could you help me?
> ![allprojects](https://user-images.githubusercontent.com/26326278/54276635-3b676e80-45a7-11e9-8bc0-4013e46e3b9d.PNG)
> ![dependencies](https://user-images.githubusercontent.com/26326278/54276638-3b676e80-45a7-11e9-99d5-4381f3a5d245.PNG)
> 
> ![settigns](https://user-images.githubusercontent.com/26326278/54276665-4f12d500-45a7-11e9-83f1-eae943b2c989.PNG)

I am too. I created a new react-native project, added all and have error when i react-native run-android...

**Comment by lcnogueira** [comment]
I'm facing exactly the same problem when trying to use this lib inside a react-native project.

**Comment by louisnot** [comment]
I thought I was alone but I am also facing the same issue when trying to install mapbox on android react native...

**Comment by ferdicus** [comment]
hey all,
make sure you add this to your projects `package.json`

```
    "@mapbox/react-native-mapbox-gl": "nitaliano/react-native-mapbox-gl#master"
```

The version on npm isn't the latest.
Having this set as the dependency and following the installation guide should do the trick.

**Comment by psyKressX** [comment]
mine looks different, ive tried adding like this, 
`protected List<ReactPackage> getPackages() {
      List<ReactPackage> packages = new PackageList(this).getPackages();
      packages.add(new ModuleRegistryAdapter(mModuleRegistryProvider));
      packages.add(new RCTMGLPackage());
      return packages;
    }`
from what i read this is how you do it but maybe its a versioning issue?

**Comment by DanielAmah** [comment]
Hi anyone fix this? I am still getting the error

**Comment by DanielAmah** [comment]
Kindly share your solution. I have done everything here but I still have the issue.

**Comment by ferdicus** [comment]
@DanielAmah: 
https://github.com/nitaliano/react-native-mapbox-gl#deprecation-notice

**Comment by DanielAmah** [comment]
I followed this the installation guide but still got the error above
<img width="1292" alt="Screenshot 2020-09-01 at 14 40 00" src="https://user-images.githubusercontent.com/28534124/91858405-0c443180-ec61-11ea-8810-ea177afc43f5.png">

**Comment by DanielAmah** [comment]
@ferdicus. Pls any help would be highly appreciated.

**Comment by ferdicus** [comment]
Please read what I posted....

**Comment by systemlevel** [comment]
You're using an outdated and deprecated library.  Switch to the community-maintained version here: https://github.com/react-native-mapbox-gl/maps

**Comment by JackJBlundell** [comment]
> hey all,
> make sure you add this to your projects `package.json`
> 
> ```
>     "@mapbox/react-native-mapbox-gl": "nitaliano/react-native-mapbox-gl#master"
> ```
> 
> The version on npm isn't the latest.
> Having this set as the dependency and following the installation guide should do the trick.

This one worked! Thank you so much, hours of searching for a tiny bug when it's the wrong version installed.
