### ISSUE TITLE
Android - showUserLocation strange crash

### ISSUE THREAD

**Issue by stephenheron** [nitaliano/react-native-mapbox-gl#1093]
Hi,

Having quite a strange issue, I am toggling the showUserLocation prop and it works perfectly fine in iOS. When it's toggled on in Android I get the "Application has stopped" working popup however the app seems to continue functioning but the users location does not appear. After the popup appears it never seems to reappear until I close the app and open it again. The user's location is never displayed. I am using the latest version (6.1.0). 

Annoyingly I can't see anything in Logcat which is making debugging this issue very difficult. I have never seen an app crash like that before where the popup shows up but the app still continues to work. 

Anyone seen this before? I have attached a gif showing the issue as I know it's quite difficult to explain. 
The map moving is my code so it's still running and appearing to be moving the map to the user's correct location. 

![ezgif-5-bc41832746](https://user-images.githubusercontent.com/142855/36992765-dd2c052a-20a3-11e8-893f-99c30b151da5.gif)

Thanks,
Stephen

**Comment by nitaliano** [comment]
@stephenheron I'll take a look at it thanks for reporting!

**Comment by stephenheron** [comment]
Hi @nitaliano 

Think this is my problem actually. 

Just investigating further now. 

Thanks,
Stephen

**Comment by stephenheron** [comment]
Yup was my problem.

Strange one to be honest I had another look at Logcat and found this message: 

java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process

I am using Firebase on react using this libarary(https://github.com/invertase/react-native-firebase).  Initially I thought the message was incorrect as the app seems to work correctly and connect to Firebase and according to the documentation it should be initialised automatically. 

However when I add "FirebaseApp.initializeApp(this);" to the onCreate method in MainApplication the error goes away. I need to make sure it does not cause any other problems but for the moment it seems to be fixed.

Very interesting it seems that setting showUserLocation to true creates another process. I had a look in Android Device Monitor and before clicking the location button the process list looks like this:

<img width="396" alt="before" src="https://user-images.githubusercontent.com/142855/36997564-f12ad728-20b1-11e8-847c-ecc2ed1baa82.png">

and after

<img width="429" alt="after" src="https://user-images.githubusercontent.com/142855/36997670-4d8a1236-20b2-11e8-89ad-7861a772739f.png">

Interesting little issue.

**Comment by nitaliano** [comment]
Yes, it's firing up the lost location engine when we show the user location. I'm also using `react-native-firebase` in another project here and it's been a pleasure to work with so far once you get all of the configuration stuff out of the way.

Can this be closed?

**Comment by stephenheron** [comment]
Ahhh ok cheers for clarifying I was going to start digging as it was bugging me.

Yup `react-native-firebase` is ace this is the first odd problem I have had with it.

Feel free to close!
