### ISSUE TITLE
Error:Configuration with name 'default' not found.

### ISSUE THREAD

**Issue by mealbarracin10** [nitaliano/react-native-mapbox-gl#1094]
i tried integrated this module to my recently app, i continue step by step, but show an error, attachments screenshot for you review 

![image](https://user-images.githubusercontent.com/11824876/36993418-c2cb1b30-207b-11e8-9fe1-592986181832.png)
![image](https://user-images.githubusercontent.com/11824876/36993430-cad7f5b4-207b-11e8-926b-cf41d45662b4.png)
![image](https://user-images.githubusercontent.com/11824876/36993431-cccdbeda-207b-11e8-8456-c5305cd9b18e.png)
![image](https://user-images.githubusercontent.com/11824876/36993432-ce37c676-207b-11e8-983e-7c5a05af318c.png)

also try rm - rf node_modules,  && npm i , but show same error

**Comment by nitaliano** [comment]
it does look fine to me, can you try cleaning your project and restarting Android Studio? I just went through the install steps and they are working for me, normally when you get `default not found` something is misconfigured and gradle can't find that dep

**Comment by mealbarracin10** [comment]
clean project, and restart visual studio and try build project but this show this error cannot load module file 'C:\Users\mealbarracin\Documents\geroapp\geoapp\node_modules\@mapbox\react-native-mapbox-gl\android\rctmgl\mapbox-react-native-mapbox-gl.iml':
File C:\Users\mealbarracin\Documents\geroapp\geoapp\node_modules\@mapbox\react-native-mapbox-gl\android\rctmgl\mapbox-react-native-mapbox-gl.iml does not exist
i navigate to this path and it doesn't appear this,  in this position

i installed for npm so: npm install @mapbox/react-native-mapbox-gl --save

**Comment by nitaliano** [comment]
it looks like there is a typo somewhere based off this line `C:\Users\mealbarracin\Documents\geroapp\geoapp\node_modules@mapbox\react-native-mapbox-gl\android\rctmgl\mapbox-react-native-mapbox-gl.iml'` there's no slash between `node_modules` and `@mapbox`

you might even need to delete and regenerate your `.iml`

**Comment by mealbarracin10** [comment]
excuseme, when copy i deleted this character,

![image](https://user-images.githubusercontent.com/11824876/36998206-1fbe5088-208a-11e8-8096-7475184f8e5a.png)

![image](https://user-images.githubusercontent.com/11824876/36998212-24571cec-208a-11e8-9e61-b000f40373d3.png)

**Comment by nitaliano** [comment]
@mealbarracin10 you can click yes on that. Look in the bottom left hand corner of that screenshot, you'll see it says `Failed to find Build Tools revision 26.0.1`. You'll need to download those build tools with the [sdk manager](https://developer.android.com/studio/intro/update.html#sdk-manager) in Android Studio.
