### ISSUE TITLE
Refreshing a `VectorSource`

### ISSUE THREAD

**Issue by sroze** [nitaliano/react-native-mapbox-gl#1095]
Is there a way to force reload a `MapboxGL.VectorSource` ? The `url` points to my own titles' server and I know the tiles have changed. Any hint? :)

**Comment by nitaliano** [comment]
Is it happening on both iOS and Android?

**Comment by sroze** [comment]
I'd like to refresh the source on both iOS and Android, yep.

**Comment by nitaliano** [comment]
On your tile server you can try setting the `Expires` header to a specific non zero value or you can set your `Cache-Control` header to `no-cache`

**Comment by sroze** [comment]
Good point, I'll do this. But I'd like to refresh the tile without leaving the view on the mobile application (every 5 to 10 seconds). Is there an API I could use? 🤔

**Comment by nitaliano** [comment]
@sroze that API is currently planned and still hasn't made it's way into the native SDKs yet unfortunately.

**Comment by sroze** [comment]
Thanks for letting me know. Any trick to share to fake such thing?

**Comment by nitaliano** [comment]
I haven't tried this but you can try to add a debug timestamp parameter to the end of your url and try to hot reload

`...&debugTimestamp=${Date.now()}`

**Comment by sroze** [comment]
What do you mean by "hot reload" ?

**Comment by nitaliano** [comment]
when you shake the device and click the item on the dev menu that reloads the js bundle

**Comment by sroze** [comment]
Just to clarify, I'm not talking about the development, but a real-life example of an application in production. The vector source is backed by realtime data.

**Comment by nitaliano** [comment]
oooo, I see.

Is there anyway this can be done with GeoJSON and a ShapeSource instead of a VectorSource?

**Comment by sroze** [comment]
I think so, yep. What would be the procedure if it's the case? 🤔

**Comment by nitaliano** [comment]
1. Have a websocket listening for these update ticks
2. Feed the data into some sort of state managment system(redux, mobx, your own)
3. Have one or multiple ShapeSources rendered on the map
4. When you get an update, you should update the `shape` property on the ShapeSource and it will move.

Checkout this example https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/DriveTheLine.js

if you want things to animate smoothly between updates you'll want to interpolate between points using the Animated API

You can always pop into https://gitter.im/react-native-mapbox-gl/Lobby or direct message me on Gitter and we can talk about this more.

**Comment by sroze** [comment]
Fab, I'll give a try. Thanks @nitaliano!

**Comment by nitaliano** [comment]
Cool, going to close this out
