### ISSUE TITLE
"onRegionIsChanging" isn't called

### ISSUE THREAD

**Issue by ancyrweb** [nitaliano/react-native-mapbox-gl#1097]
I need some hook to be called when the user is zooming/dezooming or changing region. So far I've realized `onRegionIsChanging` doesn't trigger, at least on my phone (Samsung J5), so it seemed to be the wrong path.

The only way I found to mimic this is to use `onDidFinishRenderingFrameFully`. I'm not sure that's suppoed to be the way to do it.

**Comment by maqen** [comment]
I'm also seeing this behavior upon user interaction the `onRegionWillChange` or `onRegionIsChanging` is never called on Android 🤖 

I see the correct behavior on iOS both event handlers being called even when it is user initiated.

One way is if you "throw" the map you will get some `onRegionIsChanging` events on Android.

react-native: 0.53.3
react-native-mapbox-gl: 6.1.0

**Comment by nitaliano** [comment]
so the Android SDK doesn't fire events as reliable as the iOS SDK does, there are workarounds that we can add to this repo to get the events behaving the same

**Comment by maqen** [comment]
How could one get any `onRegionWillChange` as for now I get none. Are there any easy fixes that I can add to my code base? 

I have the sense that this has gotten worse with later versions of the SDK.

**Comment by Gp2mv3** [comment]
I think it's related to the issue I opened some days ago: https://github.com/mapbox/react-native-mapbox-gl/issues/1098
The event is called but not at the right moment and the second one was rejected.

**Comment by kidasov** [comment]
onRegionIsChanging still doesn't work for me.
git+https://github.com/mapbox/react-native-mapbox-gl#release/6.1.1

**Comment by kristfal** [comment]
This should now be fixed in master. Please reopen if you still have issues.
