### ISSUE TITLE
onRegionDidChange called twice when moving fast

### ISSUE THREAD

**Issue by Gp2mv3** [nitaliano/react-native-mapbox-gl#1098]
Hi,
I see a strange behaviour on onRegionDidChange since the last release. In my app, I see the event called twice when swiping on the map. The event is called when the camera movement stops but also when my finger leaves the screen.

Here is a video of the example app: https://drive.google.com/open?id=1NVarFNVrAhVmoVsaLl_e-R0YsKbyKRsC
As you can see, the first call is with Animated false and the second with animated true.

Is this a normal behaviour ?

I tried to debug the library but installing the example app already took me a lot of time...

**Comment by Gp2mv3** [comment]
The bug seems to come from the Android sdk: it's the exact same issue as this one: https://github.com/mapbox/mapbox-gl-native/issues/10923
Looking at the version used in the react-native wrapper, it seems to use a newer version (5.4.1) so it should be fixed...

**Comment by Gp2mv3** [comment]
I created a PR with workaround here: https://github.com/mapbox/react-native-mapbox-gl/pull/1100

**Comment by nitaliano** [comment]
Closing this out since it's been merged into master
