### ISSUE TITLE
JSON not allowed as a style file (needs to be URL)

### ISSUE THREAD

**Issue by jussirantala** [nitaliano/react-native-mapbox-gl#1099]
In [react-mapbox-gl](https://github.com/alex3165/react-mapbox-gl/blob/master/docs/API.md) it is possible to provide a JSON object as the style. Requiring an URL is not good for offline solutions.

This would be fixed by allowing `string | object` as the Mapbox [setStyle](https://www.mapbox.com/mapbox-gl-js/api#map#setstyle) method supports both. Prop name would be changed to _style_ and documentation would be updated.

**Comment by nitaliano** [comment]
It's slightly different with mobile devices and the native SDKs. A url means more than `http` or `https`, it can be `file`, `assets`, or any other protocol that you decide to define.

Providing json does work it just needs to be in a file and you pass the url down, you can use something like `react-native-fetch-blob` to help you obtain that file url

Here is the iOS documentation for reference https://www.mapbox.com/ios-sdk/api/3.7.5/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(py)styleURL

What you specified above is `gl-js`, there is not a one to one mapping of methods calls between `gl-js` and `gl-native`.

I'm going to close this out post back here or join our developer group https://gitter.im/react-native-mapbox-gl/Lobby if you have any questions or need help!

**Comment by jussirantala** [comment]
If I have the map tiles locally on the device, I need to update file paths in map style file. So I would need to generate a mapstyle file, save it on device and get the file URL. 

Giving the generated mapstyle json straight to the component would make things easier. Maybe I'll add this feature myself and make a pull request.

**Comment by jussirantala** [comment]
I tried it like this but got black map:
`styleURL={data:application/json;${mapstyle_base64_encoded}}`

**Comment by ansarikhurshid786** [comment]
@nitaliano can you give me example for ios.
