### ISSUE TITLE
iOS example not working

### ISSUE THREAD

**Issue by JoaoCnh** [nitaliano/react-native-mapbox-gl#110]
So I've done everything in terms of installation.

I tried the example. put in my access token and the app breaks with this warning:

Failed propType: typeChecker is not a function Check the render method of 'Example'

I've no clue what it is. I've tried removing the streets-v8.json entry, the styleURL. That doesn't throw the error but doesn't show the map either.

I'm stuck. Does anyone know what's up?

**Comment by bsudekum** [comment]
@JoaoCnh could I see a screenshot of 

> That doesn't throw the error but doesn't show the map either.

Also, could I see a screenshot of 

> Failed propType: typeChecker is not a function Check the render method of 'Example'

**Comment by JoaoCnh** [comment]
I don't think screenshots will be any good :|

When I remove styleURL it just is a blank screen. like it has nothing. Total blank screen. but it doesn't break the app.

The failed PropType is just a plain ExceptionsManager,js throwing a warning in the Chrome console:

Warning: Failed propType: typeChecker is not a function Check the render method of `Example`.

and in XCode it breaks in main function. So I have to restart the app and so on.

I'm using ReactNative 0.11.4 if that is of any help.

**Comment by bsudekum** [comment]
I'd just like to checkout the stack trace on these errors. Screenshots would really help.

**Comment by JoaoCnh** [comment]
Here is the first part of the stack-trace

![stack_trace](https://cloud.githubusercontent.com/assets/8489894/10631451/09124e7a-77d6-11e5-998b-2940d588ee02.png) note: WMIssueCreate is my version of the example.

![stack_trace2](https://cloud.githubusercontent.com/assets/8489894/10631496/5204860c-77d6-11e5-9150-e58f596c7a04.png)

![stack_trace3](https://cloud.githubusercontent.com/assets/8489894/10631499/5816c622-77d6-11e5-87d8-6811e247e86c.png)

**Comment by bsudekum** [comment]
Hmm if you strip it down to just 

``` jsx
<MapboxGLMap
  style={styles.map}
  accessToken={'your-mapbox.com-access-token'}
  styleURL={'asset://styles/streets-v8.json'} />
```

Does the error still persist? I'm wondering if there is prop in there that shouldn't be there. Are you using the example code? Any change I could check out your code?

**Comment by JoaoCnh** [comment]
@bsudekum I'm sorry but the code is copy pasted from the example :| 

with the MapBox like that I tried it doesn't throw the console error but it does break the app in main.

**Comment by bsudekum** [comment]
> console error but it does break the app in main.

Could you allborate? I'm not sure what you mean by this. Also, could you upload a screenshot of emulator? Anything you have will help me on my end.

**Comment by JoaoCnh** [comment]
It's this. the emulator just stops and I have to restart

![break](https://cloud.githubusercontent.com/assets/8489894/10631814/40a99576-77d8-11e5-8147-b04dc3200bdb.png)

**Comment by bsudekum** [comment]
Is this from scratch or are you upgrading from a previous version? There should also be an error in xcode's console.

**Comment by JoaoCnh** [comment]
It's from scratch. Here is the error on XCode a little bit more descriptive but I don't know how to fix it.

![console_error](https://cloud.githubusercontent.com/assets/8489894/10632133/49a2e5a4-77da-11e5-95e5-f3437eb726cf.png)

**Comment by bsudekum** [comment]
Well there is the problem, you don't have the `Mapbox.bundle` included.

Can you double check that `Mapbox.bundle` is directly under the name of your app in the table of contents on the left? Also, if you open it up, is `mapbox.png` there?

(Note, the screenshot is outdated, it is `Mapbox.bundle`, not `MapboxGL.bundle`)

![](https://camo.githubusercontent.com/4cfda5decd4069081e40a3e8277ab2220abd5d9a/68747470733a2f2f636c6475702e636f6d2f4f6937754878633146642e706e67)

**Comment by JoaoCnh** [comment]
Thanks. That was it. I added Settings.bundle because the installation tutorial in the text says to add that one. Maybe that's a typo?

But yeah it's working now. 

Thank you. And if I can I'll ask you to check another issue of mine here: https://github.com/mapbox/react-native-mapbox-gl/issues/108
