### ISSUE TITLE
Can't use URI for styleURL

### ISSUE THREAD

**Issue by jussirantala** [nitaliano/react-native-mapbox-gl#1103]
I tried it like this but I got a black map:
`styleURL={'data:application/json;base64,' + this.mapstyle_base64_encoded}`

Also tried this but got an error because it's expecting a string:
`styleURL={{uri: 'data:application/json;base64,' + this.mapstyle_base64_encoded}}`

**Comment by ansarikhurshid786** [comment]
have you got solution?
