### ISSUE TITLE
Optimizing or avoiding queryRenderedFeaturesAtPoint? 

### ISSUE THREAD

**Issue by hampelm** [nitaliano/react-native-mapbox-gl#1104]
I have a `CircleLayer` I'm using to display points on a map. When a user taps one, I highlight it using a separate GeoJSON layer. 

To find the tapped feature, I've been using `queryRenderedFeaturesAtPoint` When I time that operation (snippet below), I see really variable performance for the same data and same map viewport (zoom, extent, etc). Sometimes I get results back in 40-70ms, but sometimes it takes 300-400ms or way longer, which has a noticeable impact on usability.  I've gotten reports of longer lags out in the field. Typically 2-3 features are returned, including baselayer features like buildings.

Are there any tips and tricks for this type of situation? Is there a better way to detect and show selected objects (eg setting a property and using data-driven styles)?  Since I know what I want to be interactive, can I put a tap handler directly on circles or the circle layer? 

```
    const x = Date.now()
    console.log('Tap registered')
    const { screenPointX, screenPointY, } = e.properties
    let featureCollection = await this.mapRef.queryRenderedFeaturesAtPoint([
      screenPointX,
      screenPointY,
    ])
    console.log('Tapped map', Date.now() - x, featureCollection)
```

**Comment by nitaliano** [comment]
@hampelm yes there are two ways you can help shave off time

1. Use the `onPress` callback on the shapesource as it removes a pass over the react native bridge
2. You can add an array as the third param to that method call(the second param can be null, it's for filtering) and list only the layer ids that you care about to see if the reduced data being sent over the bridge helps to speed it up.

**Comment by hampelm** [comment]
Thank you! Looks like I use `e.nativeEvent.payload` to get the feature from the VectorSource event handler? Still see an intermittent lag from (1) but I wouldn't be surprised if that's from components re-rendering, pretty hard to isolate. 

I'm noticing that I get events from my VectorSource onPress handler even when it's not the top layer (the other sources don't have event handlers). The docs say the handler "gets called when a user presses one of the children layers only if that layer has a higher z-index than another source layers". Is that still the behavior?

**Comment by nitaliano** [comment]
I can update the docs when we're referring to that we're referring to touchable sources, so it only takes into account sources that have `onPress` handlers, so we're not always checking every layer on the map everytime a press happens, we only check layers that we deem "touchable"

**Comment by hampelm** [comment]
That would be super helpful, thanks! Just wanted to make sure I wasn't getting into danger territory. Might also be helpful to note the signature of `onPress`; it took a bit of spelunking to find `e.nativeEvent.payload`.

**Comment by nitaliano** [comment]
yea the docs aren't in the best shape right now they're pretty dry. Our next release we're completely redoing them, I'll make sure that we update how source presses work

**Comment by nitaliano** [comment]
I'm going to close this out feel free to post back in here or join our [Gitter](https://gitter.im/react-native-mapbox-gl/Lobby) if you have anymore questions!
