### ISSUE TITLE
layerIndex or zindex on PointAnnotation?

### ISSUE THREAD

**Issue by hampelm** [nitaliano/react-native-mapbox-gl#1109]
Does `PointAnnotation` support a `layerIndex` or other zindex-type property? I can't seem to place one above other layers by setting a high `layerIndex`.

**Comment by nitaliano** [comment]
when you're talking about layers are you referring to trying to put an annotation under/over a `Symbol, Circle, Fill, ...etc`?

**Comment by hampelm** [comment]
Yes, over a circle / fill.

**Comment by nitaliano** [comment]
Layers are being placed in your vector tiles, Annotations are views being placed on top of the map and being synchronized with the map every time you move the map. This is one of the many reasons why Annotations are not as good as Layers, there is no way to control the zIndex between the two unfortunately.

I'm going to close this out but feel free to post back here and continue the conversation

**Comment by petertoth-dev** [comment]
@nitaliano I doubt your statement is true, my problem is exactly the opposite, for some reason PointAnntotation is behind of everything when I'd need them on top of my layers.
