### ISSUE TITLE
Getting actual address

### ISSUE THREAD

**Issue by JoaoCnh** [nitaliano/react-native-mapbox-gl#111]
Is there any way to get an actual address? I mean if it is implemented.

To get the address of the current marker like "Street Something something" or should I just use for now the Google reverse geo-coding API?

**Comment by bsudekum** [comment]
Mapbox provides a forward and reverse geocoding api, see https://github.com/mapbox/mapbox-sdk-js

**Comment by JoaoCnh** [comment]
Well if I'm using your maps it makes sense that I use your service of geocoding. 
But does that work with react-native? I'm unsure where to ask this because installing and requiring like:

require('mapbox/lib/services/geocoder') throws an error:

Requiring unknown module "assert".

**Comment by PCharpentier** [comment]
I have the same problem. Do you have a solution ?
