### ISSUE TITLE
Layers vs PointAnnotation – How to Load Dynamically and Style

### ISSUE THREAD

**Issue by deerek** [nitaliano/react-native-mapbox-gl#1111]
We are using mapbox to display markers on a map. Some markers (2) refer to categories. We use layers for these because there is a finite number of category icons. These markers work well.

However, we are having problems with markers 1  and 3. When I click a marker, a react component should animate into/out of the view. Marker 1 opens a profile, Marker 3 opens a card over the map. These markers contain a given user's profile picture, so they have to be dynamically loaded. Right now, we are using pointAnnotation to handle this. It is causing lots of problems. Mainly, the app is crashing almost every time I click one of these markers.

After reading other issues, I see that using layers instead of pointAnnotation is the best way to handle this. However, I don’t understand how to use layers for dynamic icons/raster images, or how to style them to fit the design guidelines - they need to have a shadow at the bottom of the marker to fit the 60° pitch. Can someone please shed some light on using and styling dynamic markers with layers?
![mapbox-question](https://user-images.githubusercontent.com/15710430/37372337-06dfc99e-26d8-11e8-8ffe-de3a362f212c.jpeg)

**Comment by nitaliano** [comment]
@deerek if you can provide a sample repo with the crashes you're running into, I can debug them and put in fixes for your issues.

I'll write something up in here with how you can do this with layers post back sometime tomorrow

**Comment by deerek** [comment]
@nitaliano thanks for getting back to me on this! Were you able to check out that repo? Everything make sense?

**Comment by nitaliano** [comment]
yup I got the invites, I'll take a look through the repo tomorrow and update this ticket

**Comment by deerek** [comment]
Hey @nitaliano just checking in on this.

**Comment by arpitarora2891** [comment]
@nitaliano  any update here? as I have same question as @deerek

**Comment by nitaliano** [comment]
@deerek I cloned it yesterday, question I noticed that the Android codebase isn't linked so is this only happening on iOS?

**Comment by deerek** [comment]
Sorry @nitaliano, I must have closed the tab before sending. Thanks for checking it out. We are doing iOS only for now. No need to worry about Android.

**Comment by arpitarora2891** [comment]
is there any way to dynamically style in symbollayer icons just like deerek wants to do?

**Comment by deerek** [comment]
Hey @nitaliano checking up on this. We are 2 weeks out from our AppStore launch, and this feature/bug is set to be in our sprint that starts Monday. Just trying to figure out if that means we'll be spending the time taking it out or making it work. I don't want to rush you, I know things like this take time, just need to make some plans. Thanks again for looking into this!

**Comment by KevinHu2014** [comment]
Hi @deerek,  any update on this?

**Comment by deerek** [comment]
@KevinHu2014 nothing yet. I'm in no position to make an attempt to fix this myself haha. It looks like lily added the 'support' label a few days ago, so I'm hoping it's in the pipeline because we still really need it to work.

**Comment by atelierhyper** [comment]
Anyone here have an example of how to add an Annotation/Marker dynamically or from an async geojson webservice?  I can't find any tutorial or detailled example... thanks!

**Comment by onitzschke** [comment]
Closed due inactivity.
