### ISSUE TITLE
Failed to npm install in example project on Windows.

### ISSUE THREAD

**Issue by zasyadev** [nitaliano/react-native-mapbox-gl#1114]
I cloned react-native-mapbox-gl and navigated to example folder, as soon as I run npm install or yarn, I get the following error.

```
D:\projects\react-native-mapbox-gl-master\react-native-mapbox-gl-master\example>npm install

> react-native-mapbox-gl-demo@0.0.1 preinstall D:\projects\react-native-mapbox-gl-master\react-native-mapbox-gl-master\example
> npm run pack:gl


> react-native-mapbox-gl-demo@0.0.1 pack:gl D:\projects\react-native-mapbox-gl-master\react-native-mapbox-gl-master\example
> ./scripts/npm_pack_rngl.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-mapbox-gl-demo@0.0.1 pack:gl: `./scripts/npm_pack_rngl.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-native-mapbox-gl-demo@0.0.1 pack:gl script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Shivam\AppData\Roaming\npm-cache\_logs\2018-03-14T17_37_29_438Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-mapbox-gl-demo@0.0.1 preinstall: `npm run pack:gl`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-native-mapbox-gl-demo@0.0.1 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Shivam\AppData\Roaming\npm-cache\_logs\2018-03-14T17_37_29_544Z-debug.log
```

Node: v8.9.4
npm: 5.6.0

**Comment by nitaliano** [comment]
It's trying to run a bash script, you'll need to use Git Bash or a shell that runs bash since you're on Windows.

I can update the scripts to be node based so you don't have to do this in the future but for now you can try that as a workaround

**Comment by zasyadev** [comment]
@nitaliano I tried to run npm install from git bash but it gives me the same error.

**Comment by nitaliano** [comment]
it's only running `npm pack` in the root level of the project, I'll try to update the repo with a JS PR today

**Comment by zasyadev** [comment]
Ok. thanks for your concern. Is there any workaroud I can use to run example project on windows machine?

**Comment by nitaliano** [comment]
yup you can remove this line https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/package.json#L11 and just look at the script and manually run `npm pack` from the root of the directory before trying to build the example project

**Comment by zasyadev** [comment]
okay the above solution worked. thanks

**Comment by nitaliano** [comment]
cool glad you got it working

**Comment by Edison4mobile** [comment]
@nitaliano  Good thanks

**Comment by onitzschke** [comment]
Closed due inactivity.

**Comment by deekshithmr95** [comment]
> yup you can remove this line https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/package.json#L11 and just look at the script and manually run `npm pack` from the root of the directory before trying to build the example project

that worked for me also, thank you so much
