### ISSUE TITLE
Deployment Target can't be 7.0?

### ISSUE THREAD

**Issue by JoaoCnh** [nitaliano/react-native-mapbox-gl#112]
For the deployment target of 7.0 the build fails saying:

libRCTMapboxGL.a was built for a newer iOS version (8.3) than being linked (7.0).

Is there something that can be done about this or it's a requirement  iOS 8.3 or above devices?

**Comment by JoaoCnh** [comment]
I need urgent help on this matter I can't seem to be able to get this thing into any device.

linker command failed with exit code 1 (use -v to see invocation)

and more specifically:

libRCTMapboxGL.a(RCTMapboxGL.o) was built for newer iOS version (8.3) than being linked (7.0)

and another

libRCTMapboxGL.a(RCTMapboxGL.o) does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obvtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7

Can someone help?

**Comment by friedbunny** [comment]
The "was built for newer iOS version (8.3) than being linked" warning is non-fatal and we've seen it upstream (https://github.com/mapbox/mapbox-gl-native/issues/1707). It appears to be [an Xcode 7 bug](http://stackoverflow.com/questions/32270491/xcode-7-warning-was-built-for-newer-ios-version-5-1-1-than-being-linked-5-1).

Bitcode is where this is falling down. Mapbox iOS will support bitcode in v2.2 (https://github.com/mapbox/mapbox-gl-native/issues/2332), but for now you must disable bitcode on _every_ project, subproject, and target.

<img width="720" alt="screen shot 2015-10-22 at 11 00 20 am" src="https://cloud.githubusercontent.com/assets/1198851/10668854/28a3af96-78ac-11e5-8fb4-2a4392b11ae3.png">

**Comment by nevir** [comment]
> The "was built for newer iOS version (8.3) than being linked" warning is non-fatal and we've seen it upstream (mapbox/mapbox-gl-native#1707). It appears to be an Xcode 7 bug.

The iOS version warning is due to your project's settings. [It specifies `IPHONEOS_DEPLOYMENT_TARGET = 8.3`](https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/RCTMapboxGL.xcodeproj/project.pbxproj#L280)
