### ISSUE TITLE
Pass userLocation via lat lng instead of having it automatically updated

### ISSUE THREAD

**Issue by ferdicus** [nitaliano/react-native-mapbox-gl#1124]
Is there a way to provide the userLocation yourself, instead of having it updated automatically?

I would like to write a recorder/ playback functionality for saved trips and would like to use the given icons and animation of the userLocation/ followWithHeading features.

Thanks in advance

**Comment by nitaliano** [comment]
Not yet, you would need to add support for this yourself right now. These things will be possible once we

1. Add a location manager `MapboxGL.locationManger`
2. Add a user location component `MapboxGL.UserLocation`

Having the location decoupled from the map is ideal, and we would be able to support the built in user tracking modes this way.

For now you would have to use a different location manager, and use a `ShapeSource` and `SymbolLayer` to make things customizable.

**Comment by ferdicus** [comment]
Thanks, will do.
