### ISSUE TITLE
Does this library download offline maps even if RN app is killed?

### ISSUE THREAD

**Issue by gazedash** [nitaliano/react-native-mapbox-gl#1125]
E.g. does this library use BroadcastReceiver or I have to implement it myself or maybe I have to use mapbox-offline-plugin? 
`react-native-mapbox-gl` doesn't seem to resume download after app is killed (progressListener callbacks never run)
How can I make it resume download on iOS also after app was killed?

**Comment by nitaliano** [comment]
@gazedash we are currently not using a BroadcasrReceiver, there are plans to bring in most of the android plugins, and that would include the offline plugin.

You can try this out
```
const packs = await MapboxGL.offlineManger.getPacks();

for (let pack of packs) {
  await pack.resume();
}
```

This will be the best cross platform solution for now, I'm also not 100% if packs will exist if they are killed in the middle of the download. You also would have to add the progress listeners before resuming.

Going to close this out, please post back here to continue the conversation or join or Gitter https://gitter.im/react-native-mapbox-gl/Lobby if you want to get a group discussion going

**Comment by gazedash** [comment]
@nitaliano thanks, appreciated
