### ISSUE TITLE
Xcode Build Semantic Build Errors with MGLSymbolStyleLayer & MGLCircleStyleLayer

### ISSUE THREAD

**Issue by stdavis** [nitaliano/react-native-mapbox-gl#1128]
I'm getting the following build errors when I try to run my ios project:

![image](https://user-images.githubusercontent.com/1326248/37663134-32cee97c-2c1e-11e8-985c-555fcf43e994.png)

![image](https://user-images.githubusercontent.com/1326248/37663153-3c772804-2c1e-11e8-85bb-3fbdc44e6205.png)

Would love any advice on troubleshooting. Thanks!

```
"@mapbox/react-native-mapbox-gl": "^6.1.0",
"react-native": "0.54.2",
```

**Comment by nitaliano** [comment]
If you're using yarn try to yarn remove then yard add

**Comment by stdavis** [comment]
Fixed! This fixed it...
![image](https://user-images.githubusercontent.com/1326248/37665492-038613ca-2c23-11e8-9c5c-006754e70678.png)
Did I have an old version of a Mapbox dependency or something?

I _really_ appreciate the help.

**Comment by nitaliano** [comment]
Yea there's a problem right now whenever you yarn add the yarn cache holds onto a previous version of the iOS framework. The only way to fix it for good will be with cocoapods. There's another ticket floating around that mentions this problem I'll post back here when I add instructions for it today.
