### ISSUE TITLE
Overlap PointAnnotations

### ISSUE THREAD

**Issue by ancyrweb** [nitaliano/react-native-mapbox-gl#1133]
Hello !
I'm running into the problem of showing off a custom cursor that represent the user position as it follows

![29134239_203026520282424_454849103_n](https://user-images.githubusercontent.com/12291995/37821526-2242e064-2e84-11e8-89e9-7a0a97e79d33.png)

The problem is that when zooming out, when I click on the circle with "2" wrote it in, it actually clicks on the user's position cursor. And I don't know if there's actually an other way of displaying "unclickable annotations" on the map.

I looked into the code and I have no idea how to overcome this. Ideally i've thought of either : 
* Using ordering in annotations (kind of zIndex) and taking it into account into MarkerHitResolver
* Allowing some annotations not to be selectable. It would be great to be able to provide a custom instance of MarkerHitResolver in AnnotationManager::onTap. This is the logical place to customize resolution based on marker's custom properties.

Any help would be really welcomed
Thanks !

**Comment by ancyrweb** [comment]
@nitaliano please, can you provide any feedback about this ? Like should I send a PR, is this even a considerable issue for you, is it going to be fixed in next releases, or something ?
I really need to take decision based on what's going next

**Comment by nitaliano** [comment]
If you switched from using PointAnnotations to sources and layers you would be able to query the map everytime it's pressed and get the features at that point in z order which seems like this would work in your use case

**Comment by tbergquist-godaddy** [comment]
Can you provide some example on how to do this?

We are thinking about switching to MapBox because of a problem with overlapping markers from our current map plugin. So far, I cannot see how to solve this problem with mapbox either. 

<img width="340" alt="skjermbilde 2018-04-18 kl 15 58 32" src="https://user-images.githubusercontent.com/7705041/38936645-892cd59e-4321-11e8-8a9c-808515311555.png">

This is how it looks like now, and I would really like to get the selected one to the front.

**Comment by tbergquist-godaddy** [comment]
@nitaliano

**Comment by kormang** [comment]
Same problem here. I always somehow get back to this problem.

**Comment by onitzschke** [comment]
> Can you provide some example on how to do this?
> 
> We are thinking about switching to MapBox because of a problem with overlapping markers from our current map plugin. So far, I cannot see how to solve this problem with mapbox either.
> 
> <img alt="skjermbilde 2018-04-18 kl 15 58 32" width="340" src="https://user-images.githubusercontent.com/7705041/38936645-892cd59e-4321-11e8-8a9c-808515311555.png">
> 
> This is how it looks like now, and I would really like to get the selected one to the front.

Do you found a solution? The order by layer is not supported yet, right?

**Comment by tbergquist-godaddy** [comment]
Well, not really, we are still using `react-native-maps` but as soon as mapbox upgrades to 7.0 (#1377) we are planning to switch. 

I will revisit this when that time comes.

**Comment by onitzschke** [comment]
> Well, not really, we are still using `react-native-maps` but as soon as mapbox upgrades to 7.0 (#1377) we are planning to switch.
> 
> I will revisit this when that time comes.

Giving the selected annotation the highes key. That's the solution.

**Comment by onitzschke** [comment]
I'm using this feature without any issue. Closed due inactivity.

**Comment by alexpanov** [comment]
> > Well, not really, we are still using `react-native-maps` but as soon as mapbox upgrades to 7.0 (#1377) we are planning to switch.
> > I will revisit this when that time comes.
> 
> Giving the selected annotation the highes key. That's the solution.

What's the highest key? A code sample would really help here.
