### ISSUE TITLE
StyleSheet.source doesn't work with `lineWidth` ?

### ISSUE THREAD

**Issue by matthieupinte** [nitaliano/react-native-mapbox-gl#1141]
Hi,

I'm using `v6.1` with:
``` 
// package.json
"react": "^16.3.0-alpha.1",
"react-native": "0.53.3",
```

and experiencing a little issue...

```
const styles = MapboxGL.StyleSheet.create({
  zone: {
    fillColor: MapboxGL.StyleSheet.source(
      [[1, MAP_ZONE_FILL_COLOR], [2, MAP_EXCL_ZONE_FILL_COLOR]],
      'type',
      MapboxGL.InterpolationMode.Categorical
    ),
    fillOpacity: MapboxGL.StyleSheet.source(
      [[1, MAP_ZONE_FILL_ALPHA], [2, MAP_EXCL_ZONE_FILL_ALPHA]],
      'type',
      MapboxGL.InterpolationMode.Categorical
    ),
  },
  border: {
    lineColor: MapboxGL.StyleSheet.source(
      [[1, MAP_ZONE_STROKE_COLOR], [2, MAP_EXCL_ZONE_STROKE_COLOR]],
      'type',
      MapboxGL.InterpolationMode.Categorical
    ),
    lineOpacity: MapboxGL.StyleSheet.source(
      [[1, MAP_ZONE_STROKE_ALPHA], [2, MAP_EXCL_ZONE_STROKE_ALPHA]],
      'type',
      MapboxGL.InterpolationMode.Categorical
    ),
    lineWidth: MapboxGL.StyleSheet.source(
      [[1, MAP_ZONE_STROKE_WIDTH], [2, MAP_EXCL_ZONE_STROKE_WIDTH]],
      'type',
      MapboxGL.InterpolationMode.Categorical
    ),
  },
})
```

Everyting is working well, when I'm passing `type: 2` in my properties... but not for `lineWidth`...

In fact :
```
const MAP_ZONE_STROKE_WIDTH = 5
const MAP_EXCL_ZONE_STROKE_WIDTH = 5
```
whatever I'm passing `type: 1` or `type: 2` in `properties`... `lineWidth` still be `1px`.

When I force it manually:
```
border: {
  ...,
  lineWidth: 5,
}
```
it's working...

Thanks for your help ;)

**Comment by nitaliano** [comment]
gl-native doesn't support lineWidth and the source style function https://github.com/mapbox/react-native-mapbox-gl/blob/master/docs/LineLayer.md#supported-style-functions-8 only camera is supported.

If you want to work around this you can have a line layer for each type and use a filter to target what styles you want on each line. When the upcoming expressions support lands in the native SDKs we'll be able to do this

**Comment by matthieupinte** [comment]
Thanks for your reply, I didn't know information was here. Now I know.
