### ISSUE TITLE
[iOS] Hitbox is only using default hitarea values

### ISSUE THREAD

**Issue by nitaliano** [nitaliano/react-native-mapbox-gl#1142]
* Right now when you try to update the hitbox on a `ShapeSource` the default values are overriding the user set values, so the hitbox is always `44x44` pixels.

**cc** @matthieupinte

**Comment by nitaliano** [comment]
The fix for this issue is out in a PR https://github.com/mapbox/react-native-mapbox-gl/pull/1143

**Comment by ewindso** [comment]
I am using 6.1.2-beta and this seems to still be an issue...  is there a way I can color the hitbox?  (Sometimes a ShapeSource will be slightly behind another, and there's no way to reach it unless I touch way outside of it's bounds, then it gets selected.)
