### ISSUE TITLE
[Security] - move setAccessToken function to android/ios

### ISSUE THREAD

**Issue by jpudysz** [nitaliano/react-native-mapbox-gl#1145]
As a customer of Mapbox I'm concerned about security of the `react-native-mapbox-gl` auth flow.
I enabled pay-as-you-go plan and if my key will be stolen I will be charge for each request.

In my opion `setAccessToken` function should be set in the native code, rather than JS runtime, because I can easly decompile any `.apk`...

Another solution is to combine Bundle ID with access token to add additional security layer on top of react native.

Loking forward for discussion.

**Comment by krystianpach** [comment]
+1

**Comment by nitaliano** [comment]
These methods already exists you have complete access to the native SDK you don't need to do this from the JavaScript. Add this line to your activity https://github.com/mapbox/react-native-mapbox-gl/blob/master/android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLModule.java#L279

I agree the access tokens should be scoped but this repo is not something that has control over that unfortunately. You can contact our customer service to explain your issues with them not being scoped and maybe that could result in the backend changes that would be required.

**Comment by jpudysz** [comment]
@nitaliano thanks! It worked for Android. How can I do it on iOS?

**Comment by jpudysz** [comment]
For future reference, you can add mapbox key throughout `Info.plist` like here https://www.mapbox.com/install/ios/app-permission/

Thanks for help @nitaliano :)

For me issue can be closed.

**Comment by FernandezEnrique** [comment]
I understand that this issue dates back to 2018, but I'm still encountering a similar problem. Despite adding the MBXAccessToken key with my public token to the Info.plist file as outlined in the [Mapbox iOS installation guide](https://docs.mapbox.com/ios/maps/guides/install/), I continue to receive prompts to set the access token programmatically using MapboxGL.setAccessToken(PUBLIC_TOKEN);.

Is there a way to configure the access token solely through the Info.plist without needing to set it during the JavaScript runtime? Or is it completely safe to set it this way in JS runtime?
