### ISSUE TITLE
RasterResouce: not update following 'url' util MapView.styleURL change.

### ISSUE THREAD

**Issue by sewerrat** [nitaliano/react-native-mapbox-gl#1152]
I tried to change 'url' of RasterResource dynamically. Here my code:
```
        renderRaster() {
		if (!this.props.url) {
			return null;
		}
		return (
			<MapboxGL.RasterSource
			id='test'
			tileSize={256}
			tms={true}
			url={this.props.url}>
					<MapboxGL.RasterLayer id='testLayer' sourceID='test'/>
			</MapboxGL.RasterSource>
		);
	}

	render() {
		if (this.props.isAndroidPermissionGranted) { 
			return(
				<View style={styles.havePermission}>
					<MapboxGL.MapView
					style={styles.map}
					zoomLevel={12}
					styleURL={this.props.styleURL}
					showUserLocation={true}
					userTrackingMode={MapboxGL.UserTrackingModes.Follow}
					showUserLocation={true} >
						 {this.renderRaster()}
					</MapboxGL.MapView>
				</View>
			)
		}
		return (
			<View style={styles.container}>
					<Text>Location, plzzz</Text>
			</View>
		);
	}
```

 When I changed 'this.props.url', the map didn't load new tile. It only apply new 'url' when I change 'this.props.styleURL'. So, if I want to change 'url' of RasterSource, I always have to change MapView's styleURL?

**Comment by nitaliano** [comment]
In the native sdks changing a `RasterSource` url is not allowed I would recommend wrapping each one in a different component and based on a enum render the one that you need

**Comment by ansarikhurshid786** [comment]
@nitaliano can you give example how to achieve dynamic update url or any other similar to update raster ?
