### ISSUE TITLE
[Question] Can I add my custom layer for existing source in styleURL

### ISSUE THREAD

**Issue by YKK101** [nitaliano/react-native-mapbox-gl#1153]
I try adding my custom layer for existing source in styleURL like [this link](https://www.mapbox.com/mapbox-gl-js/example/data-join/), Can I do this with RNMGL?

**Comment by nitaliano** [comment]
You can try this example out https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/ChoroplethLayerByZoomLevel.js

It has a custom style url that already has a source with some data on the map
`state_county_population_2014_cen`

we are then adding a VectorSource to the map with some more data and adding two FillLayers inside of that source that reference the `state_county_population_2014_cen` source layer.

It's also based on the example you provided, minus the expressions

Let me know how it goes!
