### ISSUE TITLE
Correct method to stop offline pack download

### ISSUE THREAD

**Issue by stephenheron** [nitaliano/react-native-mapbox-gl#1156]
Hi, 

What is the correct way to stop an in progress offline pack download?

I am currently calling `MapboxGL.offlineManager.deletePack` and that seems to do the trick however I am getting a error that crops up on Android: `void abort_message(const char *, ...): assertion "terminating with uncaught exception of type std::runtime_error: Malformed offline region definition" failed`

Strangely if I wrap the `MapboxGL.offlineManager.deletePack` call in a setTimeout it seems happier however that seems a bit odd.  

The only other reference to this error was one that I found in this issue. https://github.com/mapbox/mapbox-gl-native/issues/9858. That issue however looks to be fixed. 

I noticed in the Android RCTMGLOfflineModule.java class there is a pausePackDownload so I tried to use that and then delete the pack but still go that strange C++ error. 

Thanks,
Stephen

**Comment by nitaliano** [comment]
@stephenheron check out this example https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/CreateOfflineRegion.js#L111 there is an actual pack object that contains methods `resume` and `pause`
