### ISSUE TITLE
Application crashing when opening the map

### ISSUE THREAD

**Issue by sroze** [nitaliano/react-native-mapbox-gl#1159]
I'm running into a very weird bug at the moment. Everything looks to be running well (map and its layers works, no warning, ...) when running the application in Debug or Release mode on both a simulator or my device. Though, after archiving the application and running it on a device, it fails all the time when the map is just starting to load.

**Sometimes** (not all the times) I have a crash report which looks like the following:

<img width="556" alt="screen shot 2018-04-06 at 16 06 41" src="https://user-images.githubusercontent.com/804625/38428874-c13da650-39b4-11e8-9805-c6d023d0fae1.png">

Do you have any clue on how I could debug this forward? \o/

**Comment by nitaliano** [comment]
Can you show me your linejoin styles?

**Comment by sroze** [comment]
Here's (simplified) what I have:
```js
import MapboxGL from '@mapbox/react-native-mapbox-gl';

const styles = MapboxGL.StyleSheet.create({
    path: {
        lineColor: '#2f9ed7',
        lineWidth: 5,
        lineOpacity: 0.50,
        lineJoin: MapboxGL.LineJoin.Round,
        lineCap: MapboxGL.LineCap.Round
    }
});

// ...

class TheComponent
{
    render() {
        return (
                <MapboxGL.VectorSource id='travelPathsSource' url={this.props.pathsUrl}>
                    <MapboxGL.LineLayer
                        id='travelPathsLayer'
                        sourceLayerID='paths'
                        style={styles.path} />
                </MapboxGL.VectorSource>
        )
   }
}
```

**Comment by nitaliano** [comment]
@sroze I'm wondering if somehow an outdated version of `Mapbox.framework` is making it into your archive? Could be worth cracking open the archive and seeing if the `Mapbox.framework` is the same expected version

**Comment by nitaliano** [comment]
@sroze did you ever resolve this?

**Comment by sroze** [comment]
Mapbox was definitely the last version. I « resolved » it by removing the
lineJoin style.

**Comment by nicoten** [comment]
Is anyone else having this same issue? We just started having it. It happens as soon as we add a MapboxGL.VectorSource to the map. Here's the logs

```Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]```

**Comment by nitaliano** [comment]
@sroze I'm going to close this out then, since I don't see any action I can take on this issue.

@nicotejera you might be referencing a bad id or something you can post some code in here if you would like.

**Comment by nicoten** [comment]
I believe the issue is that VectorSource expects a TileJSON url exclusively. I recall passing an MVT url as in `<base>/{z}/{x}/{y}` and it used to work just fine. I now had to add another step in between that returns TileJSON that then points to the MVT url.
