### ISSUE TITLE
flex:1 + state change problem

### ISSUE THREAD

**Issue by orgreeno** [nitaliano/react-native-mapbox-gl#116]
When I put a mapbox with flex:1 and a sibling View with flex:1 backgroundColor: 'red' inside an enclosing parent View flex:1 backgroundColor: 'pink'  I see the expected result:
![image](https://cloud.githubusercontent.com/assets/5549189/10703314/1da73800-799d-11e5-95c4-2d03c130bc83.png)

However, when a state change removes the sibling View the mapview does not fill the parent <View>
![image](https://cloud.githubusercontent.com/assets/5549189/10703353/7e9e83ac-799d-11e5-87cb-f15bff3f447f.png)

If I test this by replacing the mapbox with a View flex:1 backgroundColor: orange it works as expected. 
![image](https://cloud.githubusercontent.com/assets/5549189/10703442/32e39ca8-799e-11e5-821d-285e923e7d58.png)
with red sibling

![image](https://cloud.githubusercontent.com/assets/5549189/10703457/4c29e71c-799e-11e5-828c-532443b9a373.png)
without red sibling

Is this a bug or am I missing something?

Thanks.

**Comment by orgreeno** [comment]
I'm not explaining this clearly I think. Here's another try:

This is a mapbox and a View sharing a parent View. The View that is the sibling to the mapbox has a background color of red. They are both flex:1. They share the parent view like you would expect.
![image](https://cloud.githubusercontent.com/assets/5549189/10848335/e00a0a7c-7ef1-11e5-8eb8-553565352aaf.png)

On a state change the sibling View is not displayed and the mapbox should fill the parent View.
The mapbox has a background color of blue. This image shows the mapbox filling the parent. However the map is not updated and the mapbox backgroundColor: 'blue' is visible.
![image](https://cloud.githubusercontent.com/assets/5549189/10848283/8ffa48e4-7ef1-11e5-9ba2-4ddaf8dcfb4a.png)

**Comment by orgreeno** [comment]
This problem is gone in 2.0.0  (thanks!)

**Comment by bsudekum** [comment]
Awesome, good to hear.
