### ISSUE TITLE
Dynamic adding of annotations - force order

### ISSUE THREAD

**Issue by papayuca** [nitaliano/react-native-mapbox-gl#1168]
Hi guys,

I have a situation where some annotations are shown initially on map render, but also other group of annotations which are added after fetching the data from the server.  
However the problem is that I need the initially rendered annotations to be displayed on top of the ones that are rendered later. I tried to wrap Annotation content in View and then give it zIndex, but that didn't work. 
Any ideas how should I approach this? 
Cheers!

**Comment by kristfal** [comment]
Check out belowLayerId. When you add another layer’s I’d to that prop, your new layer is inserted underneath the referenced layer.

**Comment by papayuca** [comment]
Hmmm, tnkx. That sounds like a nice idea. So basically I should wrap the point annotations groups in layers and then give them below- or aboveLayerID. What sort of layer would be the best for this?

**Comment by kristfal** [comment]
Hey,

the recommended practice is to not use annotations at all if you have the needs you describe. What you should do is something like this:

https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/CustomIcon.js

This way, you put all your "annotations" inside different layers and can control their zIndex as you'd like. Afterwards you'll need to add your own press handler to pick up clicks on your points in this way:

https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/QueryAtPoint.js

**Comment by papayuca** [comment]
Oh, didn't know Annotations are not recommended. Gonna do it the way you reccomend, thanks a lot!

A side question not related to the issue: If I have multiple "annotations" is it better to have one ShapeSource per item with shape set to Point of the item, or one single ShapeSource for all of them with shape set to feature collection? Let me know if I should open another issue. Apart from that you can close this one.

**Comment by kristfal** [comment]
@papayuca I'd recommend one ShapeSource per "entity" that you want a different style rule for. Ex: If you have a collection of restaurants that you want to show with one style rule and a set of airports that you want to show with a different rule, those two should be different ShapeSources. Each of those sources should contain all of the respective items as a geoJSON feature collection.

**Comment by papayuca** [comment]
Tnx a lot mate!
