### ISSUE TITLE
Cannot read property 'UserTrackingModes' of undefined

### ISSUE THREAD

**Issue by danmcgill6** [nitaliano/react-native-mapbox-gl#1172]
Project was working fine until i cloned my remote repository and tried to re install Mapbox

here is a link to the git repository: https://github.com/danmcgill6/codeUp

using: @mapbox/react-native-mapbox-gl": "^6.1.0"

it looks like this line `const MapboxGL = NativeModules.MGLModule;` in MapView.js is evaluating to Undefined  because this line is causing the error `MapboxGL.UserTrackingModes.None`

Ive re-installed 3 times this , i have  used "react-native link" , "pod install" , and "npm install"

this is my pod file:
`pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
   
    # React Native
    pod 'React', path: '../node_modules/react-native', subspecs: [
      # Comment out any unneeded subspecs to reduce bundle size.
      'Core',
      'DevSupport',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTBlob',
      'RCTCameraRoll',
      'RCTGeolocation',
      'RCTImage',
      'RCTNetwork',
      'RCTPushNotification',
      'RCTSettings',
      'RCTTest',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
      'RCTLinkingIOS'
    ]
    # Mapbox
    pod 'react-native-mapbox-gl', :path => '../node_modules/@mapbox/react-native-mapbox-gl'
`

and this is my Info.plist: 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>1</key>
	<string>LSRequiresIPhoneOS</string>
	<key>CFBundleDevelopmentRegion</key>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>en</string>
	<key>CFBundleDisplayName</key>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>This is the plist item for NSLocationWhenInUseUsageDescription</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>This is the plist item for NSLocationAlwaysUsageDescription</string>
	<key>codeUp9</key>
	<string>CFBundleExecutable</string>
	<key>$(EXECUTABLE_NAME)</key>
	<string>CFBundleIdentifier</string>
	<key>org.reactjs.native.example.$(PRODUCT_NAME:rfc1034identifier)</key>
	<string>CFBundleInfoDictionaryVersion</string>
	<key>6.0</key>
	<string>CFBundleName</string>
	<key>$(PRODUCT_NAME)</key>
	<string>CFBundlePackageType</string>
	<key>APPL</key>
	<string>CFBundleShortVersionString</string>
	<key>1.0</key>
	<string>CFBundleSignature</string>
	<key>????</key>
	<string>CFBundleVersion</string>
	<key>true</key>
	<string>UILaunchStoryboardName</string>
	<key>LaunchScreen</key>
	<string>UIRequiredDeviceCapabilities</string>
	<key>armv7</key>
	<string>UISupportedInterfaceOrientations</string>
	<key>UIInterfaceOrientationPortrait,UIInterfaceOrientationLandscapeLeft,UIInterfaceOrientationLandscapeRight</key>
	<string>UIViewControllerBasedStatusBarAppearance</string>
	<key>false</key>
	<string>NSLocationWhenInUseUsageDescription</string>
	<key/>
	<string>NSAppTransportSecurity</string>
	<key>[object Object]</key>
	<string>UIAppFonts</string>
	<key>UIAppFonts</key>
	<array/>
</dict>
</plist>
```

Fix would much appreciated, Thank you!

**Comment by drummonda** [comment]
Hey Dan, I'm experiencing exactly the same issue with Mapbox and React Native; any insight into how you solved the issue would be greatly appreciated!

#fullstackers

**Comment by chrisid** [comment]
Same issue to me

**Comment by nitaliano** [comment]
If you ever see this error it means you haven't linked your native deps correctly.

**Comment by iamstevechow** [comment]
I am having this exact issue as well. Can you elaborate further?

**Comment by chrisid** [comment]
@nitaliano do you mean react-native link is needed or follow the iOS install steps? 
I followed install steps, "pod install" broke my App because it added a duplicated React ref to my Podfile, removing the folder from ./Pods fixed that.
But then the error above error shows up.

**Comment by mertunsall** [comment]
I'm having the same issue as well. I'm using an Android emulator and I was just trying to run an example app that shows the Mapbox map. I copy paste the code in this website to my App.js after downloading the package for my project. Then I got this error.

`Cannot read property 'UserTrackingModes' of undefined
<unknown>
    C:\Users\Mert Unsal\Desktop\reactnative\mapboxProject\node_modules\@mapbox\react-native-mapbox-gl\javascript\components\MapView.js:270:31
loadModuleImplementation
    C:\Users\Mert Unsal\Desktop\reactnative\mapboxProject\node_modules\metro\src\lib\polyfills\require.js:214:4
guardedLoadModule
    C:\Users\Mert Unsal\Desktop\reactnative\mapboxProject\node_modules\metro\src\lib\polyfills\require.js:148:11
_require
    C:\Users\Mert Unsal\Desktop\reactnative\mapboxProject\node_modules\metro\src\lib\polyfills\require.js:132:2
<unknown>
    C:\Users\Mert Unsal\Desktop\reactnative\mapboxProject\node_modules\@mapbox\react-native-mapbox-gl\javascript\index.js:6
loadModuleImplementation
    C:\Users\Mert Unsal\Desktop\reactnative\mapboxProject\node_modules\metro\src\lib\polyfills\require.js:214:4
guardedLoadModule
    C:\Users\Mert Unsal\Desktop\reactnative\mapboxProject\node_modules\metro\src\lib\polyfills\require.js:148:11
_require
    C:\Users\Mert Unsal\Desktop\reactnative\mapboxProject\node_modules\metro\src\lib\polyfills\require.js:132:2
<unknown>
    C:\Users\Mert Unsal\Desktop\reactnative\mapboxProject\App.js:3
loadModuleImplementation
    C:\Users\Mert Unsal\Desktop\reactnative\mapboxProject\node_modules\metro\src\lib\polyfills\require.js:214:4
`

I think this is because I didn't do the configurations for Android (given in this link: https://github.com/mapbox/react-native-mapbox-gl/blob/master/android/install.md ) because I didn't know how to do. This documentation of Mapbox is for older versions of RN so in new version of RN I don't know where that build.gradle inside the project and app files are. It would be great if someone can show me how to do these configurations. I mean which file is the correct file to configure because when I search in project I find several files have the same name build.gradle.

**Comment by erenakbltt** [comment]
For android in app:build.gradle, change 
`  compile project(':mapbox-react-native-mapbox-gl')`
to this;
`
    compile (project(':mapbox-react-native-mapbox-gl')) { 
        compile ('com.squareup.okhttp3:okhttp:3.6.0') {
            force = true
        }
    }
`
worked for me.

**Comment by guizmo** [comment]
I had the same issue on android. ... and i feel so silly, i don't know how but the command "react-native link"  did not finish the job... I was missing the Class in MainApplication.java 
- import com.mapbox.rctmgl.RCTMGLPackage;
- new RCTMGLPackage()

Everything else was setup
