### ISSUE TITLE
Annotation moving first then shape-source with line-layer follows, why ?

### ISSUE THREAD

**Issue by Amalp** [nitaliano/react-native-mapbox-gl#1174]
I am drawing a poly-line with **point annotations**(arrows in my output) 

When i **move the map the annotations moves first then the line drawn by shapesource follows** 

I have created a sample picture of this (it was drawn to show my situation when moving the map)

![arrow moviing](https://user-images.githubusercontent.com/14848054/38868147-bcc9f198-4263-11e8-875b-fc7c9d287c2e.png)

the below is the actual output -

![violet](https://user-images.githubusercontent.com/14848054/38868284-2506d852-4264-11e8-8f81-d1b69544affb.png)

Why does this occur in my i want **the annotations have to move along with the line**  and i am unable to use shape-source with symbol layer due to this issue **already raised by my friend link below**

https://github.com/mapbox/react-native-mapbox-gl/issues/1173

point annotation code below -
```
renderArrowAnnotations(lat, lon, index, angle) {
        return (
            <Mapbox.PointAnnotation
                key={index.toString()}
                id={index.toString()}
                coordinate={[lon, lat]}
                style={[styles.annotationStyle,
                { transform: [{ rotate: angle.toString() + 'deg' }] }]}
            >
                <Image source={Images.right_arrow} style={styles.arrowImageStyle} />
            </Mapbox.PointAnnotation>
        );
    }
```
And i have drawn **line** using **line-layer and shape-source**  

line-layer code below - 
```
<MapboxGL.ShapeSource id='line1' shape={line}>
       <MapboxGL.LineLayer style={layerStyles.route} id='linelayer1' />
</MapboxGL.ShapeSource>
```

**Is there anyway to handle this issue ?**

**Comment by sandroferrari** [comment]
Same issue, PointAnnotation don't move at the same time with the map.

**Comment by makirby** [comment]
There is some good discussion here on PointAnnotation behaviour https://github.com/mapbox/react-native-mapbox-gl/issues/825#issuecomment-348265375

**Comment by nitaliano** [comment]
Yes, PointAnnotations will be officially deprecated in our next major release, they are already deprecated in our native Android SDK.

If you want control and incredible performance use Sources/Layers, there is a learning curve at first but your product will be better for it, so instead of a PointAnnotation use a SymbolLayer
