### ISSUE TITLE
undefined is not an object (evaluating 'MapboxGL.UserTrackingModes' Only in Android

### ISSUE THREAD

**Issue by fcochim** [nitaliano/react-native-mapbox-gl#1175]
I link every instruction on Android and iOS, in android give me an error related to UserTrackingModes, but in iOs works fine. the error ocurres when build. the app run & show only a white screen.

**Comment by rolignu2** [comment]
Ok , same issue but in my case is in IOS not ANDROID, i followed the install instructions

**Comment by nitaliano** [comment]
That only comes up because it's the first property that get's hit and it won't exist because the native code is not properly linked.

Going to close this out you all can post back in here and I can try to help troubleshoot when I have time

**Comment by AnthonyCalderaio** [comment]
> That only comes up because it's the first property that get's hit and it won't exist because the native code is not properly linked.
> 
> Going to close this out you all can post back in here and I can try to help troubleshoot when I have time

I still get this issue even after running: react-native link

**Comment by nitaliano** [comment]
react native link can only handle simple cases, not for projects that have multiple native deps, react native link is also very bug prone. You should follow these steps https://github.com/mapbox/react-native-mapbox-gl/blob/master/android/install.md#android-installation and in general getting familiar with how gradle works will save you alot of pain
