### ISSUE TITLE
layer id for VectorSource onPress?

### ISSUE THREAD

**Issue by ctaggart** [nitaliano/react-native-mapbox-gl#1177]
Is it possible to get the `id` of the layer when this event is tiriggered:
``` ts
<MapboxGL.VectorSource onPress={this.onSourcePress} >
```

I can't seem to find it:
``` ts
  onSourcePress = (e: NativeSyntheticEvent<any>) => {
    const feature = e.nativeEvent.payload
    console.log("onSourcePress", feature)
  }
```

I have a dozen or so layers in the `VectorSource` and I need to do a different action for several of them. It would be nice to have an `onPress` for an individual layer.

**Comment by onitzschke** [comment]
Please read the [docs](https://github.com/nitaliano/react-native-mapbox-gl/blob/master/docs/ShapeSource.md) and use onPress function. Closed due inactivity.
