### ISSUE TITLE
Drag and Drop of Annotations

### ISSUE THREAD

**Issue by exbucks** [nitaliano/react-native-mapbox-gl#1180]
Is there a way to drag and drop annotations?

**Comment by exbucks** [comment]
@nitaliano When can we expect the DnD functionality for annotations?

**Comment by nitaliano** [comment]
Sometime this summer we'll probably add support for dragging layers. As far as annotations goes they are being removed in the next major release in favor of layers. If users want to see support for it before it get's removed they would need to send a PR our way.

**Comment by exbucks** [comment]
@nitaliano Thanks for your reply. Are there any ways to implement DnD functionality on mapbox?

**Comment by nitaliano** [comment]
It is supported in the native sdks, it just needs to be bridged to react native. It would be straight forward to implement

**Comment by nitaliano** [comment]
Going to close this out since there's no actions to take

**Comment by fnLog0** [comment]
have any updates?

**Comment by dvovk** [comment]
This is really important feature, any updates on it ? You should reopen issue
