### ISSUE TITLE
ShapeSource onPress prop

### ISSUE THREAD

**Issue by krvajal** [nitaliano/react-native-mapbox-gl#1182]
When using a `ShapeSource` one of its props is `onPress`. Where can I find a documentation of the arguments that are passed to the `onPress` handler?

**Comment by nitaliano** [comment]
@krvajal the only thing that gets returned is the feature you clicked on. Here is an example https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/CustomIcon.js#L46
