### ISSUE TITLE
Annotations don't appear in device

### ISSUE THREAD

**Issue by JoaoCnh** [nitaliano/react-native-mapbox-gl#119]
I have a map with an annotation. In the simulator sometimes it draws the point marker. sometimes it doesn't. 

It's weird. When I deploy to my device it never ever draws the marker. But here is the strange part. It doesn't draw the marker but the marker is there. If by any chance I click on the exact spot of the marker the popup title appears.

Anyone knows anything that can be causing this?

**Comment by bsudekum** [comment]
This is an upstream issue that will be fixed in the next version mapbox-gl-native. It was fixed in [ios-v2.2.0-pre1](https://github.com/mapbox/mapbox-gl-native/releases), waiting for a non pre-release version and I will update here.

**Comment by JoaoCnh** [comment]
Any predictions on when it will be released?
