### ISSUE TITLE
example app not building

### ISSUE THREAD

**Issue by uvishere** [nitaliano/react-native-mapbox-gl#1192]
Whenever I try to run the react-native run-android, the project build fails for `:app:processDebugResources` with the following error:
`... /react-native-mapbox-gl/example/android/app/build/intermediates/manifests/full/debug/AndroidManifest.xml:2: Tag <manifest> attribute package has invalid character '-'.
`
Do others have faced the similar issues? Your help will be appreciated. 
Thanks.

**Comment by Nivas78** [comment]
Yes i got same issue, two different packages came for 2 manifest files.
