### ISSUE TITLE
No movement of Naavigation marker in NavigationView Activity

### ISSUE THREAD

**Issue by Meerz** [nitaliano/react-native-mapbox-gl#1194]
dear team,
i am developing a gps application using mapbox sdk turn by turn navigation 
i am facing a problem i give origin  point and destination point to start a navigation but marker does not move i remove . 
`
    @Override
    public void onNavigationReady() {

        MapboxNavigationOptions navigationOptions = MapboxNavigationOptions.builder()
                .unitType(NavigationUnitType.TYPE_METRIC)
                .build();
        Point origin = Point.fromLngLat(74.263890,31.381527);
        Point destination = Point.fromLngLat(74.331868, 31.504256);
        String awsPoolId = null;
        boolean simulateRoute = true;
        NavigationViewOptions options = NavigationViewOptions.builder()
                .origin(origin)
                .destination(destination)
                .navigationListener(this)
                .navigationOptions(navigationOptions)
                .directionsProfile(DirectionsCriteria.PROFILE_DRIVING)
                .build();
        navigationView.startNavigation(options);
    }
`
navigation marker does not move where is mistake?

**Comment by nitaliano** [comment]
@Meerz you would be best posting any support needed for the native Android nav sdk here https://github.com/mapbox/mapbox-navigation-android
