### ISSUE TITLE
[Android] Map partially rendered

### ISSUE THREAD

**Issue by Gp2mv3** [nitaliano/react-native-mapbox-gl#1202]
Hi,
I'm experiencing a bug on Android with the latest update. The map renders partially and only a zoom in/out solves the issue. Is there a particular reason ? Do you have something to counteract that issue ?

Here is a screenshot of the issue (on One plus 5).
![screenshot_20180518-102933](https://user-images.githubusercontent.com/1221806/40225140-88d4dda2-5a88-11e8-89f2-5682830d929b.jpg)

Regards,

Nicolas

**Comment by Gp2mv3** [comment]
Playing with that bug, it seems to be related to the location marker. The "displayed box" follows the position of the user.

It's not always on the center of the screen: When the position changes, the box follows it.

**Comment by Gp2mv3** [comment]
~~The bug seems to be present only when using TextureView.~~
I saw the bug in GLSurfaceView too...

**Comment by Gp2mv3** [comment]
The bug is also present in the Example App.
I'll try to investigate the Android code.

![screenshot_20180518-105216](https://user-images.githubusercontent.com/1221806/40227249-39a7e192-5a8e-11e8-9f27-c2934059ebee.jpg)
![screenshot_20180518-112418](https://user-images.githubusercontent.com/1221806/40227250-39c913b2-5a8e-11e8-9116-13c6f7846336.jpg)

**Comment by onitzschke** [comment]
Closed due inactivity.
