### ISSUE TITLE
Inconsistent SymbolLayer icon rendering when running from packager vs. static bundle

### ISSUE THREAD

**Issue by mattijsf** [nitaliano/react-native-mapbox-gl#1203]
## Environment
```
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.3.0
  Yarn: 1.3.2
  npm: 6.0.1
  Watchman: 4.9.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
  @mapbox/react-native-mapbox-gl: ^6.1.2-beta, => 6.1.2-beta
```

## Steps to Reproduce

- Import an [static image resource](https://facebook.github.io/react-native/docs/images.html#static-image-resources) with multiple densities (I used 2x, 3x, 4x): [iconPinOrigin.zip](https://github.com/mapbox/react-native-mapbox-gl/files/2019467/iconPinOrigin.zip)
- Create a `SymbolLayer` and use the imported image as `iconImage` (no specific `iconSize`)
- Run the application from static bundle
- Run the application from the packager

*Used iPhone 5s simulator & Pixel emulator*

<details>
  <summary>App.js</summary>

```jsx
import React, { Component } from 'react';
import { Platform, StyleSheet, Image, View } from 'react-native';
import MapboxGL from '@mapbox/react-native-mapbox-gl';

import config from './config'
import pinIcon from './icons/iconPinOrigin.png'

MapboxGL.setAccessToken(config.mapboxAccessToken);

const styles = StyleSheet.create({
  container: { flex: 1, },
  image: {
    position: 'absolute',
    left: '50%',
    top: '50%',
    marginTop: -40,
  },
  map: {
    flex: 1,
  }
});


const mapStyles = MapboxGL.StyleSheet.create({
  icon: { iconImage: pinIcon },
});

const amsterdam = [4.895168, 52.370216]
const features = MapboxGL.geoUtils.makeFeatureCollection([
MapboxGL.geoUtils.makePoint(amsterdam),
]);

export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        
        <MapboxGL.MapView zoomLevel={10} centerCoordinate={amsterdam} style={styles.map}>
          <MapboxGL.ShapeSource id="symbolLocationSource" shape={features}>
            <MapboxGL.SymbolLayer id="symbolLocationSymbols" minZoomLevel={1} style={mapStyles.icon} />
          </MapboxGL.ShapeSource>
        </MapboxGL.MapView>
        {/* <Image> for referencing the react-native Image rendering (at expected scale) */}
        <Image source={pinIcon} style={styles.image} />

      </View>
    );
  }
}
```

</details>

## Expected Behavior
Consistent icon size render regardless running from static bundle or packager

## Actual Behavior
- Android: icon size seem consistent all the time _(doesn't render at original size but I don't want this issue to be about that)_

- iOS:
  - Static bundle: renders icon at original size
  - Packager: renders icon at larger size 

## Screenshots

**Note:** The top most icon on top of the water is actually an `<Image>` tag with the same icon source which I added for reference and to check if Mapbox is rendering at the correct scale _(which it does only when running on iOS with Static Bundle)_.

<details>
  <summary>Click to expand</summary>
 
Android (Static Bundle):
![android-bundle2](https://user-images.githubusercontent.com/706368/40269010-7285bde6-5b78-11e8-8f02-087d60232dff.png)

Android (Packager):
![android-packager2](https://user-images.githubusercontent.com/706368/40269013-7550f5ea-5b78-11e8-930d-6b69fdfc1d49.png)

iOS (Static Bundle): 
![ios-bundle2](https://user-images.githubusercontent.com/706368/40269014-78c685b4-5b78-11e8-91ae-957d33ccdb3e.png)

iOS (Packager):
![ios-packager2](https://user-images.githubusercontent.com/706368/40269015-7c5ea1a2-5b78-11e8-8b4c-79d9930119bd.png)

</details>

**Comment by mattijsf** [comment]
After PR #1206:

Using same code snippet from message above I now have these results:

<details>
  <summary>Click to expand</summary>
 
Android (Static Bundle):
![android-bundle](https://user-images.githubusercontent.com/706368/40279121-67cc65ec-5c3d-11e8-83b2-587c72b85b29.png)

Android (Packager):
![android-packager](https://user-images.githubusercontent.com/706368/40279122-6acc6b98-5c3d-11e8-8995-e83337b7bd2f.png)

iOS (Static Bundle): 
![ios-bundle](https://user-images.githubusercontent.com/706368/40279123-6ea688b6-5c3d-11e8-9557-d00ae6f9e670.png)

iOS (Packager):
![ios-packager](https://user-images.githubusercontent.com/706368/40279124-722595f4-5c3d-11e8-9563-47a52f70389c.png)

</details>

**Comment by olliekav** [comment]
Not sure the best place to ask about this, but hopefully @mattijsf or @nitaliano know. Since testing this PR out on master my icons have gone really small. 

So before this I was using one marker at 3x the original size, then using icon size to make it the proper size based on a responsive approach, e.g. `iconSize: 0.33`, but now this seems to be `iconSize: 0.66` to get the right size? Am I approaching this wrong?

**Comment by mattijsf** [comment]
@olliekav It should present images similarly as React Native would render them according to https://facebook.github.io/react-native/docs/images.html
Which means it should render your image file at the original scale. So if you provide an image called <span>image</span>@3x.png with the actual bitmap size of lets say 72x72 Pixels it should render on screen with 24x24 Points. Any scaling factor on top of that can be controlled using `iconSize`

What could have happened is that previously it was always loading your image at 1x and scaled it up to the device's screen scale after which you had to downscale it using `iconSize` to get the desired size. _Note that this behavior was inconsistent based on whether you loaded it from assets or packager on Android vs. iOS._ But after this PR you ended up with small images because of the `iconSize` you had to use before to get the desired size.

As the code snippet above you could try adding an `<Image>` component to your app to verify if Mapbox is rendering the image at the same size (without using `iconSize`).

**Comment by olliekav** [comment]
@mattijsf Okay cool, and thanks for the thorough explanation. Sounds like I was using the broken way to manipulate it to my needs :) I'll update my markers.

**Comment by makirby** [comment]
@olliekav I was in the same boat. Though It's nice to **not** have to use a workaround now to get images to display properly. Thankyou @mattijsf for the PR!
