### ISSUE TITLE
Cluster details on ShapeSource

### ISSUE THREAD

**Issue by ronal2do** [nitaliano/react-native-mapbox-gl#1213]
Hello,
I have this context 
<img width="356" alt="screen shot 2018-05-24 at 12 10 20" src="https://user-images.githubusercontent.com/4389565/40480018-8983369e-5f4d-11e8-9e35-81717195c8b2.png">

I need to get the points informations inside the cluster but, don't have this data on payload

<img width="408" alt="screen shot 2018-05-24 at 12 23 59" src="https://user-images.githubusercontent.com/4389565/40480010-80847e2c-5f4d-11e8-949b-2662e1e47722.png">

how would it be possible to do an action similar to the web version?
![giphy](https://user-images.githubusercontent.com/4389565/40480971-485f3426-5f50-11e8-8de1-1f9ef703611b.gif)

**Comment by deerek** [comment]
Came here for the same reason.

Question for you @ronal2do. Does that cluster represent 2 points at same address/coordinates? If so, it looks like you have a spiderify effect happening. How did you do that? I've been dying over that haha

**Comment by lilykaiser** [comment]
Hi @deerek @ronal2do thanks for reporting this! This is an issue upstream in iOS being tracked here: https://github.com/mapbox/supercluster.hpp/issues/8. You can follow that ticket for updates.

**Comment by ronal2do** [comment]
@lilykaiser Thanks for your feedback, do you know any think about the points inside cluster? if its possible to pass ids?

**Comment by ronal2do** [comment]
@deerek the spiderify effect is on web version.

**Comment by johncadengo** [comment]
For anyone interested in a workaround. 

What you know from the payload is the coordinates of the cluster and the number of points in the cluster, `N`.

If you have access to all the points, you can sort the points by distance to the cluster's coordinates and then slice off the first `N` points. This should correspond to the points in a cluster regardless of cluster radius or zoom level. 

Although inefficient, it is feasible when the total number of points is small.

**Comment by onitzschke** [comment]
Closed due inactivity.
