### ISSUE TITLE
Error: undefined is not an object (evaluating 'MapBoxGL.UserTrackingModes')

### ISSUE THREAD

**Issue by EwanValentine** [nitaliano/react-native-mapbox-gl#1216]
I'm getting the error noted in the title of this issue when attempting to use Mapbox with React Native. I've followed the Android installation steps, but I'm still getting this issue. I even deleted my project, re-initialised it using `create-react-native-app`, using Expo. I then do `exp eject`, then follow the instruction on updating the gradle scripts and the settings etc. 

Are there any other commands I need to run, or possibly missing anything else?

**Comment by EwanValentine** [comment]
Doing a little more digging, it looks like a potential incompatibility with Expo could be the cause. Which is tricky because that's what `create-react-native-app` uses by default.

**Comment by kristfal** [comment]
@EwanValentine Expo doesn't support `react-native-mapbox-gl` as this repo implements native code changes. Wanna see this in Expo? Vote for it in Expo's feature prio board.

**Comment by EwanValentine** [comment]
Okay cool, I'll get voting! Cheers.
