### ISSUE TITLE
Custom Annotations + Adding View inside Annotation

### ISSUE THREAD

**Issue by bryantAXS** [nitaliano/react-native-mapbox-gl#122]
I know this isn't currently possible, but what would it take to get something like this in place? Ideally, being able to pass another View to the annotation to be rendered. I'd like to look into this more, not really sure where to start though.

thanks!

**Comment by bsudekum** [comment]
This is all dependent on mapbox-gl-native adding support for this, ref https://github.com/mapbox/mapbox-gl-native/issues/1784

**Comment by bryantAXS** [comment]
Ah ok, thanks
