### ISSUE TITLE
Google Play Services Required?

### ISSUE THREAD

**Issue by joshuapinter** [nitaliano/react-native-mapbox-gl#1220]
Hi There, 

Just curious if Google Play Services are required in order to use this library on Android? I don't see it being a requirement anywhere but let me know if it is and I can send a PR to update the README/docs. 

Thanks!

**Comment by onitzschke** [comment]
Closed due inactivity.

**Comment by joshuapinter** [comment]
Instead of closing it can you answer the question and then I can update the README with the answer?

**Comment by kristfal** [comment]
As far as I can tell, the only requirement is API level 23, and no strict requirement for google play services.

**Comment by joshuapinter** [comment]
Okay, great. Thanks @kristfal!
