### ISSUE TITLE
[Android] MapView.getCenter() promise is not resolved

### ISSUE THREAD

**Issue by Yousefjb** [nitaliano/react-native-mapbox-gl#1228]
calling 
```
const center = await this._map.getCenter();
```
never return any thing, I assume it's waiting a callback from the native module.

React: 0.55.3
react-native-mapbox-gl: 6.1.2-beta2
Android: 7.0

**Comment by nitaliano** [comment]
where are you calling it?

**Comment by Yousefjb** [comment]
```
<TouchableOpacity onPress={this.save}>
   <Text style={styles.saveButton}>Save</Text>
</TouchableOpacity>
```

```
    save = async () => {
        let center = await this.map.getCenter();
        ... other code here that it never reach .. 
    }
```

**Comment by whitesnow9291** [comment]
Hello, @Yousefjb, did you solve this?
I am getting same problem, but it works on IOS

**Comment by Yousefjb** [comment]
not yet, i had other priorities and put this issue aside for awhile. Still waiting for mapbox guys to help out

**Comment by Yousefjb** [comment]
@nitaliano Any ideas where/how should I investigate ? Currently this issue is blocking our development and I will be forced to try another one if this not resolved soon.

**Comment by Yousefjb** [comment]
[AbstractEventEmiiter Line 35](https://github.com/mapbox/react-native-mapbox-gl/blob/master/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/AbstractEventEmitter.java#L35) 

```Java
public void handleEvent(IEvent event) {
        String eventCacheKey = getEventCacheKey(event);

        // fail safe to protect bridge from being spammed
        if (shouldDropEvent(eventCacheKey, event)) {
            return;
        }

        mRateLimitedEvents.put(eventCacheKey, System.currentTimeMillis());
        getEventEmitter().receiveEvent(event.getID(), event.getKey(), event.toJSON());
    }
```

could it be `shouldDropEvent` ? maybe something flooding the bridge and prevent getCenter from being resolved ?

**Comment by Yousefjb** [comment]
@whitesnow9291  I added a comment to `node_modules\@mapbox\react-native-mapbox-gl\android\rctmgl\src\main\java\com\mapbox\rctmgl\components\mapview\RCTMGLMapViewManager.java`  then cleaned android by `gradlew clean` in my android folder and run `react-native run-android` now getCenter is resolved and you can get values like this   
```
let center = await mapview.getCenter();
let lng = center[0];
let lat = center[1];
```

also I should mention that somewhere afterwards it didn't resolve and I had to close the app and reopen it. weird

**Comment by whitesnow9291** [comment]
Thanks @Yousefjb 
I found it working on real device well.
But not working on emulator.

**Comment by andrewyohanes123** [comment]
i have the same issues and not working on real device

**Comment by andrewyohanes123** [comment]
> @whitesnow9291 I added a comment to `node_modules\@mapbox\react-native-mapbox-gl\android\rctmgl\src\main\java\com\mapbox\rctmgl\components\mapview\RCTMGLMapViewManager.java` then cleaned android by `gradlew clean` in my android folder and run `react-native run-android` now getCenter is resolved and you can get values like this
> 
> ```
> let center = await mapview.getCenter();
> let lng = center[0];
> let lat = center[1];
> ```
> also I should mention that somewhere afterwards it didn't resolve and I had to close the app and reopen it. weird

what comment should i add?

**Comment by Yousefjb** [comment]
any comment, just change the file so it recompile again.  
By the way, it is not working on a real device in debug mode but works great in release mode.

**Comment by lgcantarelli** [comment]
`getCenter()` and `getZoom()` not resolving on Android and iOs on emulators for me.

react-native: 0.60.5
react-native-mapbox-gl: 7.0.1
