### ISSUE TITLE
example project not running

### ISSUE THREAD

**Issue by jsina** [nitaliano/react-native-mapbox-gl#1234]
when I try to run the project on android I've get the error because the `env.json` not found.
```
he module `./../../env.json` could not be found from `/Users/jsinamaleki/Documents/project/react-native-mapbox-gl/example/src/utils/config.js`. Indeed, none of these files exist:
```

**Comment by jsina** [comment]
I've just delete all references on example that used `env.json` file and set all `accessToken` manually.

```
MapboxGL.setAccessToken(config.get('accessToken'));
...

const client = new MapboxClient(config.get('accessToken'));

```
change it to :
```
MapboxGL.setAccessToken('your token);
...
const client = new MapboxClient('your token')

```

**Comment by scalactic** [comment]
Hi @jsina,

I got this env.json error, too. And deleted imports for config.js and set tokens like you. Whenever I did this, I encountered with this. Did you solve it?
![adsiz](https://user-images.githubusercontent.com/19242970/43387388-f7f24612-93ee-11e8-8ea0-df7e3e44b4c7.png)

**Comment by jsina** [comment]
@ahmetGurbuzz maybe you import something that get you this error. Please send me the code to check it.

**Comment by scalactic** [comment]
@jsina, i was forgot to insall some dependencies in example/package.json. after i install them with npm, it worked for me. But in the ShowPointAnnotation example, after regresh the app(R+R), it doesnt work like at first run. I have to close app and run it again and again.

**Comment by jsina** [comment]
@AhmetGurbuzz are you running the app on emulator? try to run it on real device then check the app.

**Comment by sandunadhikari** [comment]
I've just delete all references on example that used env.json file and set all accessToken manually.

MapboxGL.setAccessToken(config.get('accessToken'));
...

const client = new MapboxClient(config.get('accessToken'));

change it to :

MapboxGL.setAccessToken('your token);
...
const client = new MapboxClient('your token')

and i install dependencies

{
  "name": "react-native-mapbox-gl-demo",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@mapbox/geo-viewport": "^0.4.0",
    "@mapbox/react-native-mapbox-gl": "^6.1.3",
    "@turf/along": "^5.1.5",
    "@turf/bearing": "^5.1.5",
    "@turf/distance": "^5.1.5",
    "@turf/helpers": "^4.7.3",
    "@turf/line-distance": "^4.7.3",
    "@turf/nearest": "^4.7.3",
    "install": "^0.12.2",
    "mapbox": "^1.0.0-beta10",
    "moment": "^2.24.0",
    "npm": "^5.10.0",
    "prop-types": "^15.7.2",
    "react": "16.6.3",
    "react-native": "0.58.1",
    "react-native-elements": "^1.1.0",
    "react-native-safe-area-view": "^0.13.1",
    "react-native-vector-icons": "^6.3.0",
    "url": "^0.11.0"
  },
  "devDependencies": {
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "^24.4.0",
    "jest": "^24.4.0",
    "metro-react-native-babel-preset": "^0.53.0",
    "react-test-renderer": "16.6.3",
    "@babel/core": "^7.3.4",
    "@babel/plugin-proposal-class-properties": "7.3.4",
    "@babel/plugin-transform-exponentiation-operator": "7.2.0",
    "@babel/plugin-transform-flow-strip-types": "7.3.4",
    "@babel/plugin-transform-runtime": "7.3.4",
    "@babel/runtime": "^7.3.4",
    "babel-plugin-transform-remove-console": "6.9.4",
    "fs-extra": "^4.0.3",
    "minimatch": "^3.0.4",
    "node-watch": "^0.6.0",
    "rimraf": "^2.6.3",
    "flow-bin": "^0.95.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
