### ISSUE TITLE
show only one symbol on zooming out

### ISSUE THREAD

**Issue by jsina** [nitaliano/react-native-mapbox-gl#1235]
why we see only one symbol on zooming out when showing multiple symbol with `SymbolLayer`. we have this issue also in [ShapeSourceIcon example](https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/ShapeSourceIcon.js). as you could see on picture below when map is zoomed out the map only shows one symbol on screen.
![1](https://user-images.githubusercontent.com/2977960/40929668-b84514fc-683a-11e8-88a4-089fa5d8432a.jpg)
![2](https://user-images.githubusercontent.com/2977960/40929673-bc19ea3a-683a-11e8-8343-939b6723f60f.jpg)

**Comment by nitaliano** [comment]
closing this out since it seems you found your solution which is `iconAllowOverlap: true`

**Comment by jsina** [comment]
@nitaliano I'm already actually add it on style but it's not solved the problem.

```
 icon: {
    iconImage: '{icon}',
    iconSize: 0.5,
    iconAllowOverlap: true,
}
```
if there is a way please let me know.

**Comment by jsina** [comment]
@nitaliano I'm adding ` textAllowOverlap: true,` and its solved because I'm using `    textField: '{name}',`
however how  could I add boxes like callout for `SymbolLayer`?

**Comment by nitaliano** [comment]
you can use a SymbolLayer to show more text with a white background, other than we don't support Callouts like that on mobile that is a legacy web pattern and it's based to adjust your UI elsewhere to show that information

**Comment by jsina** [comment]
@nitaliano thanks a lot :). however how could I add background for SymbolLayer? and also could I add onPress for it?

**Comment by jannunen** [comment]
You can add ```onPress={this.onPress}``` to ShapeSource. And then as follows:

```
 onPress(e) {
    const feature = e.nativeEvent.payload;
    console.log('Symbol clicked', feature); 
  }
```
