### ISSUE TITLE
Any feature for Identifying whether a symbol is in a cluster or alone ?

### ISSUE THREAD

**Issue by aurimusblack** [nitaliano/react-native-mapbox-gl#1239]

**Comment by nitaliano** [comment]
you need to use filtering https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/EarthQuakes.js#L87, you can also have two separate ShapeSources each containing a layer, one filters out single points, the other filters out clusters, then you add an onPress to the ShapeSource
