### ISSUE TITLE
App has stopped (Android)

### ISSUE THREAD

**Issue by kramarenkoartur777** [nitaliano/react-native-mapbox-gl#1245]
I created a new project for MapBox. I get this always when starting app. 
Help me please.
![screenshot_1528477816](https://user-images.githubusercontent.com/34880825/41171106-01cad718-6b58-11e8-8725-2f961e0b4b24.png)
![1](https://user-images.githubusercontent.com/34880825/41171111-06719b08-6b58-11e8-8a64-5c47865ecf9f.png)

**android/settings.gradle** 
include ':mapbox-react-native-mapbox-gl'
project(':mapbox-react-native-mapbox-gl').projectDir = new File(rootProject.projectDir, '../node_modules/@mapbox/react-native-mapbox-gl/android/rctmgl')

**android/build.gradle**
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        maven { url "https://maven.google.com" }
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven { url "https://jitpack.io" }
    }
}

**android/app/build.gradle**
compileSdkVersion 26
    buildToolsVersion "26.0.1"

    defaultConfig {
        applicationId "com.qwe"
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
dependencies {
    compile project(':mapbox-react-native-mapbox-gl')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
}

**MainApplication**
import com.mapbox.rctmgl.RCTMGLPackage;
new RCTMGLPackage()

**Comment by nitaliano** [comment]
what is logcat saying in Android Studio?

**Comment by kramarenkoartur777** [comment]
Thank you ;)
sorry! I forgot add token ;(

**Comment by jorgermiranda** [comment]
Same issue... where did you add the token? The accesstoken file? You have to do it after or before npm i.

Thanks!
