### ISSUE TITLE
how to identify which feature(Point) called the onPress( ) function of a single shape Source symbol Layer 

### ISSUE THREAD

**Issue by aurimusblack** [nitaliano/react-native-mapbox-gl#1246]
ex: 

say consider
featureCollection = {
type: 'FeatureCollection',
                  features: [
                  {
                   type: 'Feature',
                   id:'cup1'
                   geometry: {
                     type: 'Point',
                     coordinates: [78.32,17.3053],
                   },
                 },
                 {
                   type: 'Feature',
                   id:'cup2'
                   geometry: {
                     type: 'Point',
                     coordinates: [78.31,17.2053],
                   },
                 },
               ],
}

<MapboxGL.ShapeSource
        id={this.props.id}
        shape={featureCollection}
        onPress={this.onPress}
        >
          <MapboxGL.SymbolLayer id={..} style={..}/>
 </MapboxGL.ShapeSource>
Say the user wants the map camera to go to the particular point he presses. 

I had no problem implementing it for a single point. but how do I handle multiple points of a single shape source

**Comment by aurimusblack** [comment]
Also Does onPress of shape Source return anything ?

**Comment by lutzer** [comment]
is there an answer to this?

**Comment by lutzer** [comment]
found the solution here: #1104
