### ISSUE TITLE
Convert custom PointAnnotation

### ISSUE THREAD

**Issue by ewindso** [nitaliano/react-native-mapbox-gl#1247]
I have very custom PointAnnotations (reliant on Views containing multiple Images, and Text) and was looking for an example of converting something custom like this to Layers, if that’s is possible at the moment?

**Comment by nitaliano** [comment]
@ewindso it will be better to hold off until `7.0.0` I will provide helper methods for this, that will convert your Views to a bitmap that can be placed on the map

**Comment by ewindso** [comment]
@nitaliano sounds good, thank you!

**Comment by nitaliano** [comment]
Closing this out.

@ewindso can you post a screenshot of your PointAnnotation so I can test layers out with something like it?
