### ISSUE TITLE
Local custom tiles (app bundle)

### ISSUE THREAD

**Issue by Zeldroxe** [nitaliano/react-native-mapbox-gl#1248]
Hello,

I'm developing a tourism app that requires a small offline map area. I want to include this zone in the app bundle (apk). How can I do that?

it's been over a week that I'm looking for a solution. Thank you in advance !

PS: If you have a solution that uses react-native-maps, I'm interested too.

**Comment by zeromonad** [comment]
There are a couple of options here depending on the quality that you want. You could go with `react-native-maps` instead and use the overlay component to just display an image over lat+long bounds. However, the quality might not be so great, but this would be the easiest.

Your other option is by using the `<MapboxGL.RasterSource />`  and `<MapboxGL.RasterLayer />` component where the `url` prop points to a tileJSON file: [https://github.com/mapbox/tilejson-spec/tree/master/2.2.0](https://github.com/mapbox/tilejson-spec/tree/master/2.2.0)
And inside the tilejson file you define your location to your own tiles (can be internally stored on the device or an external server as seen in the example)
`
 "tiles": [
        "http://localhost:8888/admin/1.0.0/world-light,broadband/{z}/{x}/{y}.png"
    ],
`
You'll have to make your own tiles (I've used QGIS with the Qtiles plugin in the past). After generating the tiles they will be output to a folder, and you can place that folder on the device and just point to it:
`
 "tiles": [
        "./generatedTileFolder/{z}{x}{y}.png"
    ],
`

React-native-maps also has a similar `LocalTile`  component that is much simpler to use and doesn't require setting up a tilejson file.

**Comment by nitaliano** [comment]
thanks for the description @dcherniy, going to close this out @Zeldroxe let me know if you have any more questions
