### ISSUE TITLE
A lot of issues

### ISSUE THREAD

**Issue by JAStanton** [nitaliano/react-native-mapbox-gl#125]
I was very excited to use Mapbox, unfortunately it's far too flaky for me to use at this time. 

These were the issue I ran into on the objective C side:
- Deployment target is set to  `8.3` for no apparent reason.
- libRCTMapboxGL.a(RCTMapboxGL.o) does not contain bitcode

These were the issue I ran into on the react side:
- turning off user zoom breaks the ability to call setVisibleCoordinateBoundsAnimated completely .
- randomly annotations don't display,
- `this.addAnnoations` bashes over old annotations,
- Annotations need `id` or it will share the resource image even though it’s documented as optional.
- `styleUrl` is required even though documentation says it’s optional.
- I have to set my zoom level on next tick or my annotations simply don’t show up.
- annotations all can be clicked with a little tooltip that pops up that is mandatory, when no data is provided it pops up a white dialog
- This might be how I set it up but occasionally the ref is bashed over making calls to `setVisibleCoordinateBoundsAnimated` explode. This might be my bad though.

Here is my redacted code looked like when I decided enough was enough: https://gist.github.com/JAStanton/e1c408ca63ad55a95e04

**Comment by bsudekum** [comment]
Thanks for the feedback @JAStanton. I'm going to look into these issues this week, stay tuned.

**Comment by bsudekum** [comment]
> turning off user zoom breaks the ability to call setVisibleCoordinateBoundsAnimated completely .

I'm not sure I understand which option you're referring to. Turning off `scrollEnabled` and/or `zoomEnabled` and using `setVisibleCoordinateBoundsAnimated` works fine for me.

**Comment by bsudekum** [comment]
I opened https://github.com/mapbox/react-native-mapbox-gl/pull/130 and https://github.com/mapbox/react-native-mapbox-gl/pull/131 which addresses a couple issues here.

**Comment by 1ec5** [comment]
> libRCTMapboxGL.a(RCTMapboxGL.o) does not contain bitcode

Bitcode support is coming in the next release of the Mapbox iOS SDK. It’s already enabled in the prereleases. The prereleases are probably compatible with an unmodified react-native-mapbox-gl: just replace [`2.1.2`](https://github.com/mapbox/react-native-mapbox-gl/blob/a76d10f081886dba6f6e0624df4e187b14c24217/package.json#L25) with `3.0.0-pre.5-symbols` (or “pre.6” when it becomes available in the next day or so) then run install the npm module.

**Comment by bryantAXS** [comment]
I've been running into quite a few of these as well. Within various Issues it seems like  there is a reference to the release of 3.0.0 -- is there a more formal timeline for when those changes would be incorporated into this component? I'm trying to make the decision whether this is stable enough for production, or if we should revert back to the standard React Native MapView.

**Comment by bsudekum** [comment]
@bryantAXS @JAStanton Could you check out v2.0.0? I addressed a bunch of outstanding issues, I think it should feel more solid. Let's close this out, open a new ticket for individual issues.
