### ISSUE TITLE
MapView map scrolling isnt smooth

### ISSUE THREAD

**Issue by aurimusblack** [nitaliano/react-native-mapbox-gl#1253]
![unnamed](https://user-images.githubusercontent.com/18366236/41417673-a444eee0-700b-11e8-9852-b20239176d82.gif)

  "dependencies": {
    "@mapbox/react-native-mapbox-gl": "^6.1.2-beta2",
    "firebase": "^5.0.4",
    "react": "16.3.1",
    "react-native": "^0.52.0",
  }

**Comment by maxence-machu** [comment]
Hi @aurimusblack,

Is your app running in release mode ?

**Comment by nitaliano** [comment]
@aurimusblack after you try this in release mode and if you're still unhappy with the map please open this in the gl-native repo.
