### ISSUE TITLE
Replace the source of a SymbolLayer that was created in mapbox studio?

### ISSUE THREAD

**Issue by salah-ghanim** [nitaliano/react-native-mapbox-gl#1257]
I've defined a very simple layer that displays a label. 

<img width="1269" alt="screen shot 2018-06-19 at 5 32 12 pm" src="https://user-images.githubusercontent.com/1613032/41607646-c1a093ca-73e6-11e8-80e6-dc1209dcae71.png">

and in the mobile I'm trying to use a very simple ShapeSource to control the position of said layer

```javascript
const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});
 <MapboxGL.MapView
    styleURL="mapbox://styles/...."
    zoomLevel={12}
    centerCoordinate={[13.397401, 52.53262]}
    style={styles.container}
  >
    <MapboxGL.ShapeSource
      id="label-test-shape-source"
      shape={{
        type: 'FeatureCollection',
        features: [
          {
            geometry: { coordinates: [13.416355, 52.522236], type: 'Point' },
            type: 'Feature',
          },
        ],
      }}
    >
      <MapboxGL.SymbolLayer
        id="label-test"
        sourceLayerID="label-test-shape-source"
      />
    </MapboxGL.ShapeSource>
  </MapboxGL.MapView>
```

version:6.1.2-beta2
react-native:55.4

am I missing something here? or this simply is not possible (dynamic data sources for layers designed in mapbox studio) ?

**Comment by ryanoconnor7** [comment]
Hi @salah-ghanim, I'm facing the same issue. Did you ever find a solution for this? 

Thanks in advance.

**Comment by salah-ghanim** [comment]
@ryanoconnor7 no not really the team promised a new SDK but it's not out yet.
