### ISSUE TITLE
Help to save map offiline

### ISSUE THREAD

**Issue by hersonrodrigues** [nitaliano/react-native-mapbox-gl#1263]
Hello Guys, please I would like to save the map offline, did I try the example on CreateOfflineRegion.js but after I closed the App and opened again the map did needs to loading again, exist something to do to save it on a temp folder or something like that, thanks for your helping.

**Comment by onitzschke** [comment]
You can check https://github.com/mapbox/react-native-mapbox-gl/blob/master/docs/OfflineManager.md
