### ISSUE TITLE
Is it possible to use font-awesome icons with the ShapeSource?

### ISSUE THREAD

**Issue by chayanbhaisare** [nitaliano/react-native-mapbox-gl#1267]
I am planning to use font-awesome icons with the ShapeSource. I went through the documentation but couldn't find anything related to it.

**Comment by cglacet** [comment]
I don't think there is anything special about font-awsome, you just need to add a [`<MapboxGL.SymbolLayer />`](https://github.com/mapbox/react-native-mapbox-gl/blob/master/docs/SymbolLayer.md#mapboxglsymbollayer-) for your text to be displayed:
```es6
const mapStyle = Mapbox.StyleSheet.create({
      fontawesome: {
            textField: "{name_of_your_property}",
            textFont: [/*name of your font*/]
      }
});

return <Mapbox.ShapeSource
      shape={/*name of your shape*/}
   >
      <MapboxGL.SymbolLayer style={mapStyle.fontawesome}  /> 
</Mapbox.ShapeSource>;
```

You need to define three things here: the shape, the property that will be used to select the character depending on the feature (I guess that's what you want), and the name of your font.

You'll need to parse your shape (GeoJSON that you give as the `shape` prop), for example if you have two types of features in your shape named `data`: 
```json
data = {
   "type": "FeatureCollection",
   "features": [
       {
           "type": "Feature",
           "id": "f0",
           "geometry": {
               "type": "Point",
               "coordinates": [100.0, 0.0]
           },
           "properties": {
               "type": "typeA"
           }
       },
       {
           "type": "Feature",
           "id": "f1",
           "geometry": {
               "type": "Point",
               "coordinates": [101.0, 0.0]
           },
           "properties": {
               "type": "typeB"
           }
       }
   ]
}
```
Here `type` would be the name of your property and you'll simply need to replace (in the feature collection)  every occurence of `typeA` (same for `typeB`) by the character that match the icon you want for that category.

**Comment by onitzschke** [comment]
Closed due the inactivity.

**Comment by jafarpishdadi** [comment]
hello ...not work for me
icon not display

const mapStyle = MapboxGL.StyleSheet.create({
    fontawesome: {
          textField: '{text}',
         textFont: ['FontAwesome']
    }
});

 properties: {
                         
                            text:'home'
                        }


 <MapboxGL.SymbolLayer
                            id="exampleIconName"
                           style={mapStyle.fontawesome}
                        />

**Comment by dancherb** [comment]
I'm also having an issue where any custom fonts passed in cause symbols to no longer appear at all @cglacet
