### ISSUE TITLE
Querying Source Features of Clustered Layers

### ISSUE THREAD

**Issue by stdavis** [nitaliano/react-native-mapbox-gl#1268]
Is there any way to query the underlying source features of a clustered CircleLayer? When I query using `queryRenderedFeaturesInRect()` I get the clustered feature properties like this:
![image](https://user-images.githubusercontent.com/1326248/41942026-21808e52-795b-11e8-8473-6524cdb52284.png)
Is there any way to get to the features that this cluster represents?

**Comment by stdavis** [comment]
I ended up using finding a workaround. I'm using turfjs to query the source geoJson data directly using the map extent.

**Comment by nitaliano** [comment]
Yes turfjs is the way to go, you can also use supercluster as well

**Comment by stdavis** [comment]
I was a little worried about the parity between https://github.com/mapbox/supercluster and https://github.com/mapbox/supercluster.hpp. Thanks for the tips.

**Comment by nitaliano** [comment]
supercluster.hpp is not fully ported yet, you can use the JS version directly in your codebase and apply that to a ShapeSource. It does add extra complexity, so it depends how complex the feature your working on is.
