### ISSUE TITLE
Error: MapView has no propType for native prop RCTMapbox.onRegionChange of native type Map

### ISSUE THREAD

**Issue by jforaker** [nitaliano/react-native-mapbox-gl#127]
Red screen of death with error (using Genymotion): `Error: MapView has no propType for native prop RCTMapbox.onRegionChange of native type Map`

```
    "react-native": "^0.13.2",
    "react-native-mapbox-gl": "^1.1.0",
```

Always happens after I do a build, then seems to go away after I reload it a couple times. Very disconcerting for the time being, especially worried if this will occur in production.

**Comment by bsudekum** [comment]
Is this on iOS or Android?

**Comment by jforaker** [comment]
Android

**Comment by jforaker** [comment]
seems to be resolved. i updgraded to rn 0.14
