### ISSUE TITLE
How to run the example?

### ISSUE THREAD

**Issue by JankiRD** [nitaliano/react-native-mapbox-gl#1270]
Hi,

I am new to react-native. Started exploring since two days only.
I want to run example but, not sure how to run.

Gone through the installation instruction but stuck in second step.

How to create tokenaccess file and how to paste it in Mapbox? Is it text file? Does it contains anything? and exactly under which folder it should be?

Also, need help in understanding folder structure.

Thanks, I know it seems to be silly question but your help will be appreciated a lot.

**Comment by ryardley** [comment]
try something like: 

```
echo "pk.XXXXXXXXXXX" > accesstoken
npm install
```

**Comment by onitzschke** [comment]
All steps are describe in the [README.md](https://github.com/nitaliano/react-native-mapbox-gl/blob/master/README.md).
