### ISSUE TITLE
Cannot change scrollEnabled through changing in state

### ISSUE THREAD

**Issue by Schabaani** [nitaliano/react-native-mapbox-gl#1271]
I have a button to change state of a bool variable (boolVar). It initialized with **false**.
```
    _changeState = () => {
        this.setState({boolVar: !this.state.boolVar})
    }; 
```
And 

```
<MapBoxGL.MapView
               style={StyleSheet.InnerMap}
               logoEnabled={false}
               ref={(c) => (this.map = c)}
               centerCoordinate{[this.state.userLocation.longitude,this.state.userLocation.latitude]}
               zoomLevel={12}
               scrollEnabled={!this.state.boolVar}
               zoomEnabled={!this.state.boolVar}
               pitchEnabled={!this.state.boolVar}
               rotateEnabled={!this.state.boolVar}
/>
```

At first, I can scroll, zoom, pitch and rotate. When I click on the button to change it's state (it's state is now true), rotate, pitch, zoom are disable, however, **I can scroll again** (it's value is !true). I decided to initialize boolVar with true and doing again. At first every thing is disable, but after clicking on button rotate, pitch, zoom are reachable, however, **I cannot scroll again**.
I guess there is a bug in **updateUISettings();**  in java codes.

```
        if (mScrollEnabled != null && uiSettings.isRotateGesturesEnabled() != mScrollEnabled) {
            uiSettings.setScrollGesturesEnabled(mScrollEnabled);
        }
```
Instead of **isRotateGesturesEnabled** should be **isScrollGesturesEnabled**
```
  "dependencies": {
    "@mapbox/react-native-mapbox-gl": "git+https://github.com/mapbox/react-native-mapbox-gl#release/6.1.2",
    "react": "16.2.0",
    "react-native": "0.53.0",
}
```

**device:**
**LG-H870S - 7.0**

**Comment by kristfal** [comment]
Thanks for the PR. Issue is now closed.
