### ISSUE TITLE
Custom callout when the annotation is clicked not working on IOS.

### ISSUE THREAD

**Issue by fnusneha** [nitaliano/react-native-mapbox-gl#1278]
I’m showing PointAnnotation in a MapView, and need to show a custom callout when the annotation is clicked. I’m iterating over features of a GeoJSON, and showing point annotations.

This works correctly in Android, and shows the callout. However, in iOS simulator, it prints “Point selected”, but doesn’t show the callout. What could be the issue here?

I’m using a fixed zoom-level of 3 in MapView. Here is the code to generate point annotations and the styles.

return geoJSON.features.map((feature, index) => {
            let iconSize = 16;
            let key = "point-" + index;
            if (feature.dtype == 3) { iconSize = 32; }
               return (<Mapbox.PointAnnotation key={key} id={key} coordinate={feature.geometry.coordinates} onSelected={()=>{console.log("Point selected");}}>
                      <View style={{width: 32, height: 32, backgroundColor: "transparent"}} />
                      <Mapbox.Callout style={styles.calloutContainer}>
                        <View style={styles.calloutContent}>
                           <Text style={styles.calloutText}>{feature.properties.tn} {feature.properties.n}</Text>
                        </View>
                       <View style={styles.calloutTip} />
                      </Mapbox.Callout>
                    </Mapbox.PointAnnotation>);
        });

    calloutContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      width: 272,
      zIndex: 999999
    },
    calloutTip: {
      zIndex: 1000,
      marginTop: -2,
      elevation: 0,
      backgroundColor: 'transparent',
      borderTopWidth: 16,
      borderRightWidth: 8,
      borderBottomWidth: 0,
      borderLeftWidth: 8,
      borderTopColor: 'white',
      borderRightColor: 'transparent',
      borderBottomColor: 'transparent',
      borderLeftColor: 'transparent',
    },
    calloutContent: {
      position: 'relative',
      padding: 8,
      flex: 1,
      borderRadius: 3,
      borderWidth: 1,
      borderColor: 'rgba(0, 0, 0, 0.2)',
      backgroundColor: 'white',
    },
    calloutText: {
      color: 'black'
    }

**Comment by nitaliano** [comment]
@fnusneha I replied on Gitter lmk if the solution worked!

**Comment by fnusneha** [comment]
Thanks @nitaliano 
The following solution worked-
Add a title prop to your callout
the iOS SDK requires a title be provided
https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/ShowPointAnnotation.js#L118
follow that example for props
