### ISSUE TITLE
Significant lower performance compared to native mapbox.

### ISSUE THREAD

**Issue by gunters63** [nitaliano/react-native-mapbox-gl#128]
Played around with the react-native and the all-native map-box components and noticed that there is a significant performance difference.

I created simple demo apps for both, displaying only a US map with one annotation and the same style. The all-native app has smooth 60 fps, the react-native one probably 20.

Didn't manage to make a release build with react-native yet, could that be the issue?

**Comment by gunters63** [comment]
Compared the native mapbox sample to a react-native equivalent. Same performance difference here, the all native is much smoother.

I tried the same also with the Apple MapVIew, here the all native and the react-native version have no perceptible differences.

**Comment by geezmo** [comment]
Thanks for this module, i'm really enjoying it so far.
I ran into the same performance issues. Is community responsibility to get them solved?

**Comment by bsudekum** [comment]
I'm seeing this too. I have a couple ideas of where this could be coming from:
- One/all event listeners is firing too much making move events heavy https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/RCTMapboxGL/RCTMapboxGL.m#L282-L293
- Adding annotations to the map is heavy https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/RCTMapboxGL/RCTMapboxGL.m#L110-L124

@geezmo I can take a look at this this week but community involvement would be amazing. Simply just removing each of the code chunks above, running and testing would be a good start.

**Comment by gunters63** [comment]
Annotations weren't the culprit in my case, i also tried it without.

The react native (Apple) MapView which I am using now doesn't have any problems with more than hundred annotations.

But the Apple maps really look ugly and are not customizable at all, mapbox is miles ahead in this category :).

**Comment by geezmo** [comment]
I tried to follow the whole function calls stack in RCTMapboxGL.m with Xcode debugger - it seems that the map initialization is doing fine. I'm experiencing poor performances in the map rendering phase, and an (abnormal?) peak in CPU usage when the region is changed after dragging or pinching. My other components in the screen are unresponsive for a while when map is being re-rendered. Hope it helps, tomorrow i'll try to find some time to dig a little deeper.

**Comment by bsudekum** [comment]
@geezmo I definitely have seen this issue locally however I just updated to react native v0.14.2 and it seems that performance is back to normal. I thought that this might be due to me upgrading to the iphone 6s, however I just tested on the first gen ipad mini (not the most performant device) and it feels silky smooth.

Can you try and upgrade to react native 0.14.2+ and see if the performance still lags?

**Comment by bsudekum** [comment]
v2.0.0 is feeling much better. Re-open if you think it's not on par with native.
