### ISSUE TITLE
can't run npm install cmd

### ISSUE THREAD

**Issue by Edison4mobile** [nitaliano/react-native-mapbox-gl#1281]
I hope anyone helps me to build in android and ios

**Comment by jsina** [comment]
what you mean you cant run `npm install`
could you explain more?

**Comment by ansarikhurshid786** [comment]
@Edison4mobile this is not right to ask question. exaplain your question with environment details

**Comment by Edison4mobile** [comment]
I have resolved issue.
Thanks for your reply.
I have removed "pack:gl": "./scripts/npm_pack_rngl.sh", from package.json
and got success build in android.
