### ISSUE TITLE
Invalid LngLat latitude value: must be between -90 and 90

### ISSUE THREAD

**Issue by VentsislavDinev** [nitaliano/react-native-mapbox-gl#1282]
How to setup start position in Los angelis when coordinates is 34.0544779, -118.2443409?!
![image](https://user-images.githubusercontent.com/10218246/42419875-c8e52950-82c5-11e8-817f-41d5798abbd5.png)

**Comment by Gp2mv3** [comment]
Try by inverting lat and long ? Did you try with [-118, 34] ?

**Comment by nitaliano** [comment]
@VentsislavDinev this code snippet is for `mapbox-gl-js` this is the react-native repo you will want to open up issues here https://github.com/mapbox/mapbox-gl-js. 

I agree that your coordinates look like they are in `[lat, lng]` order and they need to be in `[lng, lat]` order.

**Comment by kevintanhongann** [comment]
LMAO I thought I was doing something wrong on my end until I saw this error message on my Chrome debug window.
