### ISSUE TITLE
How to load offline Pack to MapView

### ISSUE THREAD

**Issue by yaduc** [nitaliano/react-native-mapbox-gl#1285]
Hi, I am downloading a Region in the splash screen of my app. How can I load the downloaded pack to the map. This is the code I use for downloading the pack 

` await MapboxGL.offlineManager.createPack({
        name: 'spain',
        styleURL: Mapbox.StyleURL.Light,
        minZoom: 14,
        maxZoom: 20,
        bounds: [[NE_LON, NE_LAT], [SW_LON, SW_LAT]]
    }, progressListener, errorListener)`

**Comment by yaduc** [comment]
@nitaliano

**Comment by nitaliano** [comment]
@yaduc you don't need to load the pack

* The tiles get saved to the file system
* They are referenced from a local database

so once you download the pack 100% it will just work in offline mode. LMK if it doesn't work! Closing this out for now

**Comment by FashionCStar** [comment]
If I have downloaded several packs, which one will be used?
@nitaliano

**Comment by sabarikobagapau** [comment]
Same issue here i am facing

**Comment by NitayMG** [comment]
Has anyone made any progress with this?
