### ISSUE TITLE
How to position the callout below the point ?

### ISSUE THREAD

**Issue by fnusneha** [nitaliano/react-native-mapbox-gl#1289]
We’re using Callout and PointAnnotation to show a callout above a point.

Is it possible to position the callout below the point instead? We’re using custom content in the callout, not the default layout.

<Mapbox.PointAnnotation key={key} id={key} title={title} selected={feature.properties.dtype == 3}
                         coordinate={feature.geometry.coordinates} onSelected={()=>{
                            console.log("Point selected");
                            this.map.flyTo(feature.geometry.coordinates);
                       }}>
                      <View style={{width: 32, height: 32, backgroundColor: "transparent"}} />
                      <Mapbox.Callout style={styles.calloutContainer}  title={title}>
                        <View style={styles.calloutContent}>
                            <Text style={styles.calloutText}>{title}</Text>
                            <Text style={[styles.calloutText, {fontWeight: "bold"}]}>{positionType}</Text>
                            <Text style={styles.calloutText}>{dateString}</Text>
                            <Text style={styles.calloutText}>{latLonString}</Text>
                            <Image source={icon} style={[styles.rightTop, {height: iconSize, width: iconSize}]}/>
                            <Text style={[styles.calloutText, styles.rightBottom]}>{randomString}</Text>
                        </View>
                       <View style={styles.calloutTip} />
                      </Mapbox.Callout>
                    </Mapbox.PointAnnotation>

**Comment by samfader** [comment]
Hey @fnusneha - do you mind sharing some more detail on what you're hoping to do? When you say Callout, are you referring to the popup that displays information about the given point? Where were you hoping for the Callout to be positioned?

**Comment by onitzschke** [comment]
I think you are looking for anchor, see [PointAnnotation.md](https://github.com/nitaliano/react-native-mapbox-gl/blob/master/docs/PointAnnotation.md).
Closed due inactivity.
