### ISSUE TITLE
Not able to take screenshot of map- Android

### ISSUE THREAD

**Issue by fnusneha** [nitaliano/react-native-mapbox-gl#1290]
I am trying to take screenshot of current screen on Android which has mapbox showing map and share on social media. 
I use normal way of doing it on android side
Intent emailIntent = new Intent(Intent.ACTION_SEND);
 
It takes screenshot and opens the share dialog as expected. 
However, the screenshot doesn’t capture the map. It captures everything else on the screen except the map.

Here is my mapbox implementation. Is there any param missing here that I need to add?
const map = <Mapbox.MapView
                      styleURL={Mapbox.StyleURL.SatelliteStreet}
                      zoomLevel={3}
                      centerCoordinate={centerCoordinates}
                      style={mapStyle}
                      ref={ref => (this.map = ref)}
                      zoomEnabled={this.state.showCallouts}
                      pitchEnabled={false}
                      scrollEnabled={this.state.showCallouts}
                      rotateEnabled={false}
                      logoEnabled={false}
                      onPress={() => {this.onPress();}}
                      minZoomLevel={1}
                      maxZoomLevel={10}>

**Comment by nitaliano** [comment]
`MapView.takeSnap(true)` will allow you to take a snapshot of the map write it to the local file system and return the uri of the image to you https://github.com/mapbox/react-native-mapbox-gl/blob/master/docs/MapView.md#takesnapwritetodisk
