### ISSUE TITLE
app crash on android api 21,19

### ISSUE THREAD

**Issue by jsina** [nitaliano/react-native-mapbox-gl#1292]
on android 5 api 21 the app was crashed when navigate to the page with map.
actually I'm using this branch for some reason

```
"@mapbox/react-native-mapbox-gl": "git+https://github.com/mapbox/react-native-mapbox-gl#release/6.1.2",

 "react": "16.3.1",
 "react-native": "0.55.2",
‍‍‍‍‍‍‍‍‍‍
```

I'm actually get same error when running the [official example](https://github.com/mapbox/react-native-mapbox-gl/tree/master/example) on api 21.
on logcat I've get this error:

```
com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigException: eglChooseConfig() failed
at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.getNumberOfConfigurations(EGLConfigChooser.java:85)
at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.chooseConfig(EGLConfigChooser.java:62)
at com.mapbox.mapboxsdk.maps.renderer.textureview.TextureViewRenderThread$EGLHolder.prepare(TextureViewRenderThread.java:360)
	at com.mapbox.mapboxsdk.maps.renderer.textureview.TextureViewRenderThread.run(TextureViewRenderThread.java:247)
```

<img width="324" alt="screen shot 1397-04-25 at 16 18 32" src="https://user-images.githubusercontent.com/2977960/42757164-2c0dd9f6-8914-11e8-800a-c94d5541a4c4.png">

also on android api 19 version 4.4.4 the map just show the entire universe instead of specific location that set on the code. actually the mapbox example has the same problem as you see below.

<img width="514" alt="screen shot 1397-04-25 at 16 40 00" src="https://user-images.githubusercontent.com/2977960/42757976-225bad54-8917-11e8-8424-65f6834ce937.png">

**Comment by jsina** [comment]
I've actually resolve the second problem that **'on android api 19 version 4.4.4 the map just show the entire universe instead of specific location that set on the code. actually the mapbox example has the same problem as you see below.'**  with checking user location permission then show the map. the `key` props is important on `<Mapbox.MapView` because user could see the map also before permission granted.

```

state = {
    hasLocationPerm: false,
  };

 componentDidMount() {
    this.requestCameraPermission().then((hasLocationPerm) => {
      this.setState({
        hasLocationPerm,
      });
    });
  }

requestCameraPermission = async () => {
    try {
      const granted = await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
        {
          title: 'دسترسی مکان جغرافیایی',
          message: `${consts.APP_NAME} نیاز به دسترسی نقطه جغرافیایی شما برای مرتب سازی کلاس‌های ورزشی دارد.`,
        },
      );
      if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        return true;
      }
    } catch (err) {
      console.log(err, ' errr');
    }

    Alert.alert(
      strings.PERMISSION_TITLE_ALERT,
      strings.PERMISSION_MESSAGE_ALERT,
      [
        {
          text: strings.OK,
          onPress: () => {},
        },
      ],
    );

    return false;
  }



render() {
...
<Mapbox.MapView
          key={`map_key_perm_${this.state.hasLocationPerm}`}
          styleURL={Mapbox.StyleURL.Street}
          zoomLevel={5}
          centerCoordinate={consts.IRAN_LONG_LAT}
          style={styles.container}
          attributionEnabled={false}
          showUserLocation={this.state.hasLocationPerm}
        >
}
```

but the first problem on android 5 api 21 hasn't solved been yet.

**Comment by nitaliano** [comment]
are you testing on a device? `com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigException: eglChooseConfig() failed` normally happens on emulators

**Comment by jsina** [comment]
@nitaliano I’ve got this problem just on api 21 emulator, unfortunately I don’t have a device with this api but if you sure that this this the common problem with emulator I’m gonna close this comment?!

**Comment by kristfal** [comment]
Closing as this issue is stale. Please reopen if the issue still persists on master.
