### ISSUE TITLE
mapbox force close

### ISSUE THREAD

**Issue by cyaxares** [nitaliano/react-native-mapbox-gl#1294]
my application dont have problem on Andriod and IOS when  in IOS  i come to the episode Map is force stop and close, i think this reason is interference MapBox and wix,, i using these: 
"react": "^16.0.0",
"react-native": "^0.51.0",
 "@mapbox/react-native-mapbox-gl": "6.1.0",
 "react-native-navigation": "^1.1.381",

and this pic is explain about problem
![myapp](https://user-images.githubusercontent.com/9538639/42843150-e67c0c28-8a17-11e8-8165-3ae8c85f6699.jpg)

**Comment by nitaliano** [comment]
We'll need a stacktrace

**Comment by cyaxares** [comment]
@nitaliano 
how can i trace  ios ?

**Comment by onitzschke** [comment]
Please open a new issue with stack trace. Closed due inactivity.
