### ISSUE TITLE
Having issues using mapbox 

### ISSUE THREAD

**Issue by dsall** [nitaliano/react-native-mapbox-gl#1300]
Hi guys, i have just tried using mapbox with my android app, but am facing an issue when i try using it. 
![image](https://user-images.githubusercontent.com/11328128/43033015-633bf35c-8c90-11e8-9aa9-f6051104c834.png)
@nitaliano I followed all the steps in the readme file by modifying my build.gradle and setup.gradle as suggested in the documents. 
here is some screenshots:

![image](https://user-images.githubusercontent.com/11328128/43033054-463a6918-8c91-11e8-97a5-75f5daef3fe4.png)

![image](https://user-images.githubusercontent.com/11328128/43033062-56cede6c-8c91-11e8-88df-cebbcf6a966c.png)

![image](https://user-images.githubusercontent.com/11328128/43033070-6f58865e-8c91-11e8-8295-19f3ab465cf0.png)
![image](https://user-images.githubusercontent.com/11328128/43033071-775daeb0-8c91-11e8-9045-01142ec0982d.png)

![image](https://user-images.githubusercontent.com/11328128/43033078-8bfc173a-8c91-11e8-8af3-9561fd36f882.png)

![image](https://user-images.githubusercontent.com/11328128/43033091-b75450d2-8c91-11e8-96ae-a23f3fe91ab8.png)

I followed all the steps and it's still giving me this error. I would really appreciate your help. 

Thanks

**Comment by dsall** [comment]
Am still trying to find some help @nitaliano

**Comment by onitzschke** [comment]
Please follow the install instruction. Closed due inactivity.
