### ISSUE TITLE
Android: JS FPS Drop

### ISSUE THREAD

**Issue by georgesitoniv** [nitaliano/react-native-mapbox-gl#1303]
I have noticed that the JS thread FPS drops while navigating, pinching, swiping on the map on both the example app and in my app. Since it is the fps drop is experienced on the example app, is this normal? What can I do to prevent those drops?

**Comment by nitaliano** [comment]
Are you testing on a device in a release build?

**Comment by georgesitoniv** [comment]
Sorry, haven't got a chance to test it in a release build. But, I tested this on a device. I will try to test this in a release build within this week.

**Comment by kristfal** [comment]
Closing this stale issue. Please reopen if you experience issues with master in production mode.
