### ISSUE TITLE
Cannot add task ':app:prepareMapboxAppMapboxReactNativeMapboxGlUnspecifiedLibrary' as a task with that name already exists.

### ISSUE THREAD

**Issue by ansarikhurshid786** [nitaliano/react-native-mapbox-gl#1305]
Hi, 
Yesterday I was created new project and installed in device it was working fine. Today i tried to install in device by giving command as below:
react-native run-android

I am getting error :
Cannot add task ':app:prepareMapboxAppMapboxReactNativeMapboxGlUnspecifiedLibrary' as a task with that name already exists.

How can I resolve this ?

**Comment by giantss** [comment]
@ansarikhurshid786 
+1,Is the problem solved?

**Comment by ansarikhurshid786** [comment]
Yes it resolved..

**Comment by gino8080** [comment]
how solved please? i got same problem
Cannot add task ':app:prepareRNMapboxGLExampleMapboxReactNativeMapboxGlUnspecifiedLibrary' as a task with that name already exists.

**Comment by giantss** [comment]
@gino8080 I guess you used a react-native link, resulting in a duplicate application package.

**Comment by gino8080** [comment]
ok solved removing duplicates from setting.gradle and app/build.gradle thank you!
