### ISSUE TITLE
App crash on android emulator when i press CTRL+M

### ISSUE THREAD

**Issue by dopey2** [nitaliano/react-native-mapbox-gl#1307]
Hello, I just setup mapbox for android. Everything work fine except for the developer menu (CTRL + M) .The app crash on emulator only. I don't have this behavior on a real device.

### react-native: 0.48.3

**Comment by kristfal** [comment]
This is an old issue, and since it’s only reported for emulators not a high priority. Please open a PR if you do find a fix.
