### ISSUE TITLE
Couldn't get touched screen point coordinates on MapView with PanResponder

### ISSUE THREAD

**Issue by scalactic** [nitaliano/react-native-mapbox-gl#1313]
Hello,
I can get screen coordinates from touched point with PanResponder, but I couldn't get screen coordinates when i touch on Mabbox MapView. Here is my code block:
<View style={{ flex: 1, backgroundColor: '#263238', }} >
    <View style={[styles.point, { top: parseFloat(this.state.locationY - 15), left: parseFloat(this.state.locationX - 15) }]} />
        <View style={{ flex: 1, backgroundColor: 'transparent' }}  {...this.panResponder.panHandlers}>
        <MapboxGL.MapView
            zoomLevel={5}
            styleURL={MapboxGL.StyleURL.Dark}
            centerCoordinate={[11.123, 43.123]}
            style={{ flex: 0.5, backgroundColor: 'transparent' }}>
        </MapboxGL.MapView>
    </View>
</View>

![screenshot_1532793332](https://user-images.githubusercontent.com/19242970/43358406-dea50db2-9299-11e8-9a1b-f2f4c7dcd1d5.png)

I will be glad if you help me. Thanks...

**Comment by kristfal** [comment]
Not supported (yet). See #1058 for more details.

**Comment by scalactic** [comment]
Thank you @kristfal for ur reply,

I have found my solution one hour ago by the way . It is exactly what i am looking for.
-> https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/ShowClick.js

**Comment by scalactic** [comment]
But I was thought that i can make it work with PanResponder before seeing this component.
