### ISSUE TITLE
Purpose of sourceID for Layer components?

### ISSUE THREAD

**Issue by nbolten** [nitaliano/react-native-mapbox-gl#1315]
### Intro

I'm trying to build a map view with a few different layers that share the same source. In `mapbox-gl` (or even `react-mapbox-gl`), I define a source first, give it an ID, and then create layers that refer to that source ID. None of the layers are children of the source, they're just instantiated after it.

This strategy does not seem to work in `react-native-mapbox-gl`, which makes me wonder whether the `sourceID` prop for vector layers has an intended purpose. In addition, all of the example code uses layers that are children of a single source.

### The problem

When I use code that looks like this:

    <MapboxGL.VectorSource                                                        
      id='mysource'                                                             
      url='tileJSON URL'
    />                                                                      
    <MapboxGL.LineLayer                                                           
      id='layer1'                                                              
      sourceID='mysource'                                                       
      sourceLayerID='layer1'
      style={styles.layer1}
      aboveLayerID='bridge-street'                                                
    />

I get an error like this:

    Index: 3, Size: 2

Without many useful messages (caveat: I'm somewhat new to native mobile development, so my debugging chops might not be great).

The code works fine if I nest that LineLayer as a child of the VectorSource, with no error messages.

### Wrap-up

Mostly, I feel like I'm encountering behavior that conflicts with expectations set by the documentation, and the examples code doesn't cover my particular attempt at using `sourceID`. It would be super helpful to have the intended purpose of `sourceID` clarified and an example that distinguishes its intended use from just nesting layers as a child of source components.

In addition, it would be help to have more useful error messages relating to sources / vectors. In this particular case, I don't really know where to go to figure out the issue. In other cases, I've added source components with typos and received no warnings/errors/debug messages, just layers that don't render for unknown reasons, so I have to stab in the dark.

Thanks for any responses! This library is super helpful to our group and we appreciate your hard work.

Best,

Nick

**Comment by nbolten** [comment]
Maybe I should make this issue about modular sources / layers in general, because I also encounter another issue that may be related: creating components that render a VectorSource in a separate module and trying to use them like a VectorSource downstream also doesn't work. i.e. this doesn't work:

    <MyCustomSource>
      <LineLayer (...) />
    </MyCustomSource>

But this does:

    <VectorSource {...samePropsAsMyCustomSource}>
      <LineLayer (...) />
    </VectorSource>

It seems like layers are very picky about their parent components, or something along those lines.

**Comment by nbolten** [comment]
To add to the confusion, it appears that `sourceID` is necessary when a layer component is rendered by a custom class from a separate module and imported for use as a child of `<VectorSource>`, but not when instantiated directly as a `<*Layer>`.

**Comment by kristfal** [comment]
Closing as this issue is old. We haven’t made any changes on the way we wrap components. If you have any ideas for improvements, don’t hesitate to open a PR :)
