### ISSUE TITLE
Execution failed for task ':@mapbox_react-native-mapbox-gl:compileReleaseJavaWithJavac'

### ISSUE THREAD

**Issue by antariess** [nitaliano/react-native-mapbox-gl#1319]
OS: Ubuntu 16.04
Node: 10.7.0
Yarn: 1.9.2
npm: 6.2.0
Watchman: Not Found
Xcode: N/A
Android Studio: to generate emulator
react-native: 0.56.0
"@mapbox/react-native-mapbox-gl": "github:mapbox/react-native-mapbox-gl"

I have followed the instructions on [](https://facebook.github.io/react-native/docs/signed-apk-android.html ) and got to the 
`./gradlew assembleRelease` 
command. I encounter the following issue: 

`FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':@mapbox_react-native-mapbox-gl:compileReleaseJavaWithJavac'.`

Building for android. 
build tools version 26.0.3

android/build.gradle: 
`allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        maven { url "https://jitpack.io" }
    }
}`

android/app/build.gradle:
`dependencies {
    ...
    implementation project(':@mapbox_react-native-mapbox-gl')
    ...
}`
I have looked into all past issues raised here (there were 10 or so) and none applied to the problem I'm encountering. Any help is appreciated.

**Comment by rghorbani** [comment]
This seems to be the [solution](https://github.com/mapbox/react-native-mapbox-gl/issues/1139#issuecomment-379647942).

**Comment by onitzschke** [comment]
@nitaliano can be closed.
