### ISSUE TITLE
Telemetry opt-in/opt-out 

### ISSUE THREAD

**Issue by MapYourShow** [nitaliano/react-native-mapbox-gl#1321]
Are there ways to opt-in or opt-out of telemetry within the app, apart from the built in "i" icon functionality? We hoping to opt users out by default and give them an option to opt-in. The fact that a user is automatically opted in worries us as GDPR and it's new guidelines are something we have worked hard to stay in line with.

**Comment by hillbillysurf** [comment]
This is probably what you need, from 6.1.1 release: https://github.com/mapbox/react-native-mapbox-gl/pull/1096

**Comment by BurnedChris** [comment]
I had a problem understanding the pull request. demo code would be great!

**Comment by hillbillysurf** [comment]
Mapbox.setTelemetryEnabled() and isTelemetryEnabled() was added, maybe this is a little more clear. https://github.com/mapbox/react-native-mapbox-gl/issues/1000

**Comment by BurnedChris** [comment]
its still not 100% clear. I looked though these but an official like docs/demo would be better!

**Comment by zugaldia** [comment]
Though from a different Mapbox SDK, the conversation on https://github.com/mapbox/mapbox-navigation-android/issues/963 can be useful to understand the GDPR flow for our Maps SDK. The summary is that the app is responsible to request consent from the user and the SDK has mechanisms to honor that. Let me know if you have specific questions.

**Comment by onitzschke** [comment]
```
MapboxGL.setAccessToken(MapUtils.getAccessToken('accessToken'));
↓↓↓↓↓↓↓↓↓↓↓↓↓↓
MapboxGL.setTelemetryEnabled(false);
```

@nitaliano answered, can be closed.

**Comment by vishalshah6153** [comment]
Is there any property same as _setTelemetryEnabled_ available for [react-map-gl](https://www.npmjs.com/package/react-map-gl)? I need to disable telemetry, but I'm using the mentioned package. 

> ```
> MapboxGL.setAccessToken(MapUtils.getAccessToken('accessToken'));
> ↓↓↓↓↓↓↓↓↓↓↓↓↓↓
> MapboxGL.setTelemetryEnabled(false);
> ```
> 
> @nitaliano answered, can be closed.

How Can I do the same for [react-map-gl](https://www.npmjs.com/package/react-map-gl)?
