### ISSUE TITLE
custom styleURL gray screen

### ISSUE THREAD

**Issue by cosmosof** [nitaliano/react-native-mapbox-gl#1322]
` <Mapbox.MapView
           showUserLocation={true}
            styleURL="mapbox://styles/kahramanm/cjkbdd66c8jy82rqrshqaxblj"
            zoomLevel={15}
            centerCoordinate={[-71.082754, 42.33079512206621]}
            style={styles.container}>
       </Mapbox.MapView>`

it wont generate background map, just gray background. When I try it on web app, it works fine. please help me to figure this out.

<img width="639" alt="screen shot 2018-08-02 at 6 17 29 pm" src="https://user-images.githubusercontent.com/7368238/43614266-b9e7134a-9680-11e8-850f-d84947adf014.png">

**Comment by tylergaw** [comment]
@cosmosof Not sure if this helps, but if you're seeing this on an Android emulator you may need to change your OpenGL renderer. I hit the same issue. Here's a couple convos on the topic:
 https://github.com/mapbox/react-native-mapbox-gl/issues/1041#issuecomment-375381751 https://github.com/mapbox/react-native-mapbox-gl/pull/1131

**Comment by alburdette619** [comment]
~I'm seeing this on an iOS simulator~

Disregard, client gave me the wrong api key.

**Comment by zugaldia** [comment]
@cosmosof Did the suggestion mentioned on https://github.com/mapbox/react-native-mapbox-gl/issues/1322#issuecomment-413659790 help?

**Comment by kristfal** [comment]
Closing as this issue is stale. If it is still an issue, please try on master and reopen if you still experience the issue.
