### ISSUE TITLE
Catastrophic performance

### ISSUE THREAD

**Issue by ALexandreM75013** [nitaliano/react-native-mapbox-gl#1326]
react-native 0.51.0
react-native-mapbox-gl 6.1.2-beta2

Hi,
I am using react-native-mapbox to implement a map in my app : everything works, I mean it shows a map on the screen but the performance are not really good. 

Indeed, I'm not using any particular style, but each time I move the map on the screen, I have a blank screen while it is loading to render. Also, in the Android Profiler, when the map is shown, the memory explodes, about 250 mb, and the CPU is at 50%. (the JS Dev Mode is deactivated to have better performance).

I have tried on two Android devices, and same problem appears.

I don't know why the performance are terrible, is there a way to improve this ? I have already try to set a style with MapBoxStudio with just few layers, but it is still slow. 

Just to compare, the react-native-maps module works way better, everything is smooth, but I want to use the mapbox map.

**Comment by scalactic** [comment]
Hi @AlexandreMaistret,
I am using mapbox in my react native app and it works fine for me on RN 0.55.4 and react-native-mapbox-gl 6.1.2 (added it manually to node modules, couldnt install with npm 6.1.2)

**Comment by ALexandreM75013** [comment]
I tried with a brand new react-native project with 0.55.4, and react-native-mapbox-gl 6.1.2-beta2, and the performances are still not good.

I must miss a point, or I am too demanding, but my map is still not all as performant as the one on Snapchat which uses also MapBox.

It is really a pity, I will use react-native-maps while the performances of this package are still not good.

**Comment by kristfal** [comment]
@alexandreMaistret can you build and run the example repo on your device and benchmark the performance? 

In general, maps are resource intensive, but we don’t notice any significant slowness in RN compared to pure android as long as we don’t clog the bridge or do any costly processing while interacting with the map.

**Comment by nitaliano** [comment]
Closing this out since there's nothing actionable here. @AlexandreMaistret if you can provide us with information on how to repo this we can reopen. I have not see any performance issues like the one you have described above.
