### ISSUE TITLE
RasterSource Layer Blurry

### ISSUE THREAD

**Issue by dliff** [nitaliano/react-native-mapbox-gl#1327]
Platform: iOS (looks fine on Android)
Version: `"@mapbox/react-native-mapbox-gl": "^6.1.2-beta2",`

![image](https://user-images.githubusercontent.com/2548613/43802021-82282972-9a49-11e8-8ef5-e4f24d7be37f.png)

![image](https://user-images.githubusercontent.com/2548613/43803694-61959bfe-9a4e-11e8-8320-23ba352e5e5d.png)

```
<Mapbox.MapView
                        styleURL={Mapbox.StyleURL.Light}
                        zoomLevel={15}
                        centerCoordinate={[longitude, latitude]}
                        style={styles.map}
                    >
                        <Mapbox.RasterSource
                            id="osm"
                            tileSize={256}
                            url="http://c.tile.openstreetmap.org/{z}/{x}/{y}.png"
                        >
                            <Mapbox.RasterLayer id="osm" />
                        </Mapbox.RasterSource>
                    </Mapbox.MapView>
```
Raster tiles are very blurry.
Tested with OpenStreetMap as well as Google Maps vector tiles. 
Attempted both 256 and 512 tileSize. (tileSize seems to make no difference on how the tiles are rendered.
It appears iOS is ignoring `tileSize`. If I change tileSize to 512, Android looks just like iOS (pixelated).

Thanks,
Daniel

**Comment by twelch** [comment]
I also ran into this.  PR opened with fix
