### ISSUE TITLE
Draw a custom 3d polygon

### ISSUE THREAD

**Issue by huunghipham95** [nitaliano/react-native-mapbox-gl#1328]
How can I add an 3d polygon from geojson to Mapbox.
My problem is:
I've building footprint geojson of Karnataka in India. I want to draw building from this geojson, but in the doc it look like mapbox didn't support.

**Comment by ferdicus** [comment]
Checkout this example: https://github.com/mapbox/react-native-mapbox-gl/blob/78fb83e7aa2bdbd29cdf89aa111e5580ce9c0244/example/src/components/IndoorBuilding.js

**Comment by kristfal** [comment]
@ferdicus Thanks for the reply. @huunghipham95 hope this answers your question. If not, please use Stackoverflow or our gitter channel (https://gitter.im/react-native-mapbox-gl) for questions and only post issues/bugs in github.
