### ISSUE TITLE
showUserLocation ={true} doesnt render blue dot in Real Device

### ISSUE THREAD

**Issue by scalactic** [nitaliano/react-native-mapbox-gl#1329]
Hi all, 
I am gettin blue dot on MapView whenever i set mock location on Emulator  from "..." button but I dont see blue dot in real device after i release apk. Any solutions ? Also I am getting user location with
navigator.geolocation.getCurrentPosition(
      (position) => {
        this.setState({
          latitude: position.coords.latitude,
          longitude: position.coords.longitude,
          error: null,
        });
      },
      (error) => this.setState({ error: error.message }),
      this.options,
    );
<MapboxGL.MapView
            showUserLocation={true}
            styleURL={MapboxGL.StyleURL.Dark}
            zoomLevel={5}
            centerCoordinate={[this.state.longitude, this.state.latitude]}
            style={styles.container}
            onPress={this.onPress} onLongPress={this.onLongPress}
            logoEnabled={false} attributionEnabled={false}
          >

**Comment by 24dev** [comment]
@AhmetGurbuzz Did you fix this? We are experiencing this issue, no blue dot displayed but the location is working.

**Comment by scalactic** [comment]
No, I couldn't.

27 Nis 2019 Cmt 15:04 tarihinde AlcuinGuest <notifications@github.com> şunu
yazdı:

**Comment by dliff** [comment]
For me, this happens when the component with the MapView has already rendered, but the user hasn't accepted Location permissions. After the user accepts the permissions the Dot should show, but it doesn't until the app restarts (or possibly the MapView component is reinitialized, I have yet to try that). I'm currently working on a solution to not render the MapView component until user has accepted Location permissions.

This only seems to affect Android.

**Comment by Anzormumladze** [comment]
> For me, this happens when the component with the MapView has already rendered, but the user hasn't accepted Location permissions. After the user accepts the permissions the Dot should show, but it doesn't until the app restarts (or possibly the MapView component is reinitialized, I have yet to try that). I'm currently working on a solution to not render the MapView component until user has accepted Location permissions.
> 
> This only seems to affect Android.




Hi, Did you fix this issue ?
