### ISSUE TITLE
Static annotation images in 0.14

### ISSUE THREAD

**Issue by priithaamer** [nitaliano/react-native-mapbox-gl#133]
Since static image loading was changed in react-native 0.14 and `require('image!...')` has been dropped, is there any way to load static images as annotation images?

**Comment by bsudekum** [comment]
So the only way to consume static images with this module will be under the old `require('image!...')` way. It's actually a custom implementation under the hood.

Ideally, you could do something like `<Image source={require('./foo.png')} />` and it would just work. I'm not actually sure how to implement this though. Do you know of any modules that consume react components on the objective c side?

**Comment by priithaamer** [comment]
Did i understand correctly that even `require('image!...')` is also custom re-implementation in MapBox library? In this case, providing something similar to this, e.g. `require('mapboximage!...')` would be also good enough.

**Comment by shravyadalvai** [comment]
for android ?

**Comment by tyao1** [comment]
+1 for android

**Comment by maqen** [comment]
Any news on using local images on android?

**Comment by jayfunk** [comment]
According to the Android source you provide an annotation like the following:
`{
        id: event.id,
        coordinates: event.coordinates,
        type: 'point',
        title: event.name,
        annotationImage: {
          url: 'image!pin'
        },
}
`
The url in annotation image is supposed to be a string which references a drawable in your android resources folder. The source looks to be ok but it never actually replaces the annotation image as expected. No exception or anything. Is this broken on Android?

**Comment by bsudekum** [comment]
@jayfunk This feature is not in a release yet.

**Comment by dapetcu21** [comment]
The format changed from `'image!name'` to `{ uri: 'name' }` as of #365 to more closely fit the output of `require()`, but actual `require()` support is still pending.
