### ISSUE TITLE
Using a my own compiled version of Mapbox GL Native on Android

### ISSUE THREAD

**Issue by RNMBuser** [nitaliano/react-native-mapbox-gl#1333]
I compiled my own version (adding some minor custom changes) of Mapbox GL Native. 
On iOS, I have to replace Mapbox.framework. Could you tell me please what file do I need to put and where on Android?

**Comment by kristfal** [comment]
You'll have to for the library and change the `android/rctmgl/build.gradle` from `com.mapbox.mapboxsdk:mapbox-android-sdk:5.4.1@aar` to your [local jar](https://docs.gradle.org/current/userguide/introduction_dependency_management.html#sub:file_dependencies).
