### ISSUE TITLE
SymbolLayer Text duplication on zoom

### ISSUE THREAD

**Issue by isabelle-butterfield** [nitaliano/react-native-mapbox-gl#1334]
On my MapView, I have a ShapeSource with a FillLayer and a SymbolLayer. The SymbolLayer contains one piece of text; however, when I zoom in to a certain point, the text in the SymbolLayer gets duplicated. Pictures are included below to help describe the issue. Is there a way to prevent this from happening?

<img width="593" alt="screen shot 2018-08-15 at 2 13 54 pm" src="https://user-images.githubusercontent.com/40366252/44177277-0db65780-a0a2-11e8-9174-b0840d030c31.png">
<img width="592" alt="screen shot 2018-08-15 at 2 13 45 pm" src="https://user-images.githubusercontent.com/40366252/44177283-13ac3880-a0a2-11e8-88d1-8fcee090ab7d.png">

**Comment by kristfal** [comment]
This is as expected (shape sources are sliced into tiles which causes this effect). 

To work around this behaviour, pre-generate the centroids for each polygon [with for instance Turf](http://turfjs.org/docs/#centroid), and add those as a separate source and style.
