### ISSUE TITLE
SET MAPBOX ACCESS TOKEN NOT WORKING!!!

### ISSUE THREAD

**Issue by alexxsanchezm** [nitaliano/react-native-mapbox-gl#1341]
To start this report I already review the issue #1083.

I really appreciate the work this community is doing, but this issue is real and very easy to reproduce.

It seems the current way to `setAccessToken('token_string')` is not working properly at least on android. After follow every step of the documentation there is no way to get any of my demos running with the mapbox implementation for RN, any time this is the result.

<img width="257" alt="screen shot 2018-08-22 at 7 42 31 pm" src="https://user-images.githubusercontent.com/3522488/44498367-a705e080-a643-11e8-80ea-53dd48c69b4c.png">

My guess is, there is something missing in the documentation which is vital to get this running on android.

Steps to reproduce the issue:

1. Create a RN project with `react-native init mapboxcrash`
2. Setup your project with mapbox.
    * yarn add @mapbox/react-native-mapbox-gl
    * Setup this files build.gradle, app:build.gradle, settings.gradle, MainApplication.java, [see doc](https://github.com/mapbox/react-native-mapbox-gl/blob/master/android/install.md).
 3. Impement jsx code in the App.js file.
 4. Run `react-native run-android`.
 5. Boom!!! got the error.

Some configuration files in case some one wants to check.
```
import React, {Component} from 'react';
import { StyleSheet } from 'react-native';
import MapboxGL from '@mapbox/react-native-mapbox-gl';
import conf from './conf';

MapboxGL.setAccessToken(conf['accestoken']);

type Props = {};
export default class App extends Component<Props> {
  render() {
    return (
        <MapboxGL.MapView
            showUserLocation={true}
            zoomLevel={ 16 }
            styleURL={ MapboxGL.StyleURL.Street }
            centerCoordinate={[-82.437465, 8.431490]}
            style={ styles.container }
        />
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1
  }
});
```
package.json
```
{
  "name": "maptest",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@babel/core": "7.0.0-beta.47",
    "@mapbox/react-native-mapbox-gl": "^6.1.2",
    "babel-core": "^6.26.3",
    "react": "16.4.1",
    "react-native": "0.56.0"
  },
  "devDependencies": {
    "babel-jest": "23.4.2",
    "babel-preset-react-native": "^5",
    "jest": "23.5.0",
    "react-test-renderer": "16.4.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
Working under osx high sierra.
RN: 0.56
RN-CLI: 2.0.1

I know I should request permissions, but i just want to get this issue over. I'm wiling to help no just report issues.

Finally I'm begging to not close this issue without take a look.

**Comment by kristfal** [comment]
Try setting it in `componentWillMount`. If that doesn't work, add a file in the root project (where your index.js is) named `accesstoken` and paste your access token in that file.

**Comment by alexxsanchezm** [comment]
Hi @kristfal , I did both of your suggestion, but it didn't work.
This is what I did so far:

1. Run your suggestions.
2. Add some unmet dependencies with prop-types, mapbox seems to need prop-types@>=15.x.x
3. Remove node_modules dir, reset RN cache, took the postinstall scrip on package.json from the example project and the the script itself under example/scrips/*
4. Try to set up the access token from the native code(java), also didn't worked.

I will run some experiments using the example from the repo to clear out some suspicions.
Let me know if there is anything I forgot to check, thnks.

**Comment by kristfal** [comment]
Can you try running the example project? Note: it does grab the accesstoken from the file in the root folder. We’re running 6.1.2 without any issue, so this seems quite strange.

**Comment by alexxsanchezm** [comment]
Yeah, I agree, very strange. I did a fresh clone and run the example, it's working perfectly on ios simulator, but android don't.

At first instance I notice there is no gradlew script in example/android, so I opened Android studio to get gradlew created and updated, once created, I ran the app on the emulator, but got black screeen, so I ran into my device and now it works.

**Note**: In the sample it uses a dependency from `file:../mapbox-react-native-mapbox-gl-6.1.2.tgz` from the repo instead the one provided by npm.

I'll try this setup variations so se how it behaves, please, still don't close the issue.
thanks

**Comment by alexxsanchezm** [comment]
There **MUST** be something very different in the documentation and the example. If you use the example project it will work, that's for sure, but not when you init a blank RN project, no matter if you follow the doc guide, it will run just on ios.
I'll keep trying...

**Comment by alexxsanchezm** [comment]
Ok @kristfal finally I get this running.
It seems after doing all the setup I found out there was [another issue around](https://github.com/mapbox/react-native-mapbox-gl/issues/1139#issuecomment-379647942).

I think details like this one should be in  documentation as well.
Thanks @kristfal

**Comment by chuprik** [comment]
@alexxsanchezm thanks, man! you did my life easier today.

**Comment by virus2016** [comment]
Does anyone else have this issue on android only? iOS seems to allow us to use it without a token…
