### ISSUE TITLE
Pan map camera

### ISSUE THREAD

**Issue by adoniscoder** [nitaliano/react-native-mapbox-gl#1344]
Hi, is there any way to pan maps camera ? I want to move camera a little after user selects a coordinate but I did not found anything to do so in the documentation.

**Comment by kristfal** [comment]
Your best bet is to use `setCamera`. It is available through the [mapView ref](https://github.com/mapbox/react-native-mapbox-gl/blob/master/docs/MapView.md#setcameraconfig). You can also check out the examples for use cases.

**Comment by adoniscoder** [comment]
Thanks but I don't have near coordinate to the selected coordinate to use `setCamera`

**Comment by kristfal** [comment]
Just to understand: You want to pan the camera by a few pixels?

**Comment by adoniscoder** [comment]
I want show user that the previous point has submitted and he/she can go for the next point so I want to move camera a little to show the marker of previous point on the map
