### ISSUE TITLE
My Callouts don´t render in iOS simulator

### ISSUE THREAD

**Issue by carloscrovara** [nitaliano/react-native-mapbox-gl#1345]
Hello. I'm having an error where the callouts don´t appear when I click on the point. This happens in iOS Simulator (I don´t have an iOS device to try). I don´t have problems in Android devices or simulator.

My dependencies in package.json:
 "dependencies": {
    "@mapbox/react-native-mapbox-gl": "^6.1.2",
    "native-base": "^2.7.0",
    "react": "^16.4.1",
    "react-native": "^0.56.0",
    "react-native-communications": "^2.2.1",
    "react-native-onesignal": "^3.2.6",
    "react-native-splash-screen": "^3.1.1",
    "react-navigation": "^2.11.2"
  },

I attached you my current code.
[Oficinas.ios.txt](https://github.com/mapbox/react-native-mapbox-gl/files/2320703/Oficinas.ios.txt)

**Comment by pjay79** [comment]
Having same issue. Tried applying styles to Callout and no change.

"@mapbox/react-native-mapbox-gl": "^6.1.3",
"react-native": "0.56.0",

Regards

**Comment by mumapu** [comment]
Hello,
I had the same issue...
Just add a title prop to Point Annotation... 

<MapboxGL.PointAnnotation
        key='pointAnnotation'
        id='pointAnnotation'
        title='Look! An annotation!' <----- HERE
        coordinate={[11.254, 43.772]}>

        <View style={styles.annotationContainer}>
          <View style={styles.annotationFill} />
        </View>
        <MapboxGL.Callout title='Look! An annotation!' style={{width: 152, height: 80}} />
      </MapboxGL.PointAnnotation>

**Comment by carloscrovara** [comment]
@mumapu Your solutions works excellent! Thanks a lot!

**Comment by pjay79** [comment]
@mumapu thanks for this
