### ISSUE TITLE
React Native App using mapbox crashes immediately after ruuning command ```react-native run-android```

### ISSUE THREAD

**Issue by aditya2000** [nitaliano/react-native-mapbox-gl#1349]
Hey there
I'm just getting started with mapbox but I have got a problem. Whenever I'm trying to run my app on emulator, it just crashes immediately showing no errors in log.

Please Help!

**Comment by ashavyrin** [comment]
Same issue. I made a new project with react-native init. Did the android install steps. If I add any Mapbox function and run react-naive run-android the app crashes with error "Unfortunately, [app name] has stopped." IOS runs fine however.

**Comment by nitaliano** [comment]
You need to check your adb logs for an error there will be one there

**Comment by aditya2000** [comment]
@ashavyrin You need to downgrade your RN to 0.55.4

**Comment by ddolheguy** [comment]
There is a fix for this and the real issue is with the command below and you do not need to roll back your React Native.

```
Mapbox.setAccessToken(.....);
```

Fix here:
https://github.com/mapbox/react-native-mapbox-gl/issues/1139#issuecomment-379647942

**Comment by onitzschke** [comment]
@nitaliano can be closed.
