### ISSUE TITLE
Mapbox studio private beta

### ISSUE THREAD

**Issue by jlc467** [nitaliano/react-native-mapbox-gl#135]
Designed a map with mapbox studio classic, published it, and was excited to use it with this project. Did not realize mapbox-gl uses different style system (not CartoCSS) and you can't just specify a project id like you can with mapbox JS classic (non-gl). 

How soon will mapbox studio be released?

**Comment by bsudekum** [comment]
Hey @jlc467, Mapbox Studio will be released very soon. If you give me your mapbox username, I can invite you to the beta however.

**Comment by jlc467** [comment]
Thanks. Very soon is going to workout perfect for the project i'm working on.
