### ISSUE TITLE
Could not find a declaration file for module '@mapbox/react-native-mapbox-gl'

### ISSUE THREAD

**Issue by Lucastrike** [nitaliano/react-native-mapbox-gl#1350]
![screenshot_20180830_173420](https://user-images.githubusercontent.com/18655258/44864747-bce95600-ac80-11e8-8e28-a876a890dab6.jpg)

Does anyone know how to solve this issue?
This is a full javascript project so i dont completly understand why im getting a ts problem, ...wondering is inside the mapbox module.

Anyway i tried to init a new project and still the same problem, switching into an older version and even installing `@types` but it still no sense

**Comment by Lucastrike** [comment]
After working for a few days on this problem i found out that mapbox is not working with react-native 0.56.0
Fow anyone having this problem just downgrade your react native version to 0.55.4 and babel-preset-react-native to 4.0.0
Hope it helps someone while mapbox fix the compatibility!

**Comment by moschap** [comment]
Hi @Lucastrike, please how do i downgrade the version of RN that i have, i currently have the latest version - v0.57 and i have the same issue as you did.

Please is there any plan to resolve the in-compatibility issues anytime soon?

**Comment by moschap** [comment]
@Lucastrike, never mind i saw this solution - https://github.com/mapbox/react-native-mapbox-gl/issues/1139#issuecomment-379647942

**Comment by Lucastrike** [comment]
Hi @moschap 
By the moment the best option I found is to downgrade the following packages with this commands:
`npm install react-native@0.55.4`
`npm install babel-preset-react-native@4.0.0`

Anyway, the issue I mentioned above its because the plugin isn't ready to work with typescript, but it can run anyway, the problem is somewhere else and the solution I said, prevents the app's crashing.

**Comment by edenkras** [comment]
> @Lucastrike, never mind i saw this solution - [#1139 (comment)](https://github.com/nitaliano/react-native-mapbox-gl/issues/1139#issuecomment-379647942)

Did it work for you? Tried it and it changed nothing.

**Comment by edenkras** [comment]
> Hi @moschap
> By the moment the best option I found is to downgrade the following packages with this commands:
> `npm install react-native@0.55.4`
> `npm install babel-preset-react-native@4.0.0`
> 
> Anyway, the issue I mentioned above its because the plugin isn't ready to work with typescript, but it can run anyway, the problem is somewhere else and the solution I said, prevents the app's crashing.

Do you know if there is another way solving this problem?
If not, is there newer version that I can use to fix this?

**Comment by kristfal** [comment]
Master branch has some typings now, but we are not 100% there. Master also supports RN59, so please use that instead.

**Comment by edenkras** [comment]
Hi @kristfal, I am using RN 0.59.1 and still encountering this problem. How can I fix it?

**Comment by kristfal** [comment]
I don’t use TS, so I can’t help you much there. Propose you look up the issue on stackoverflow. Happy to accept PRs with fixes.

**Comment by athomann** [comment]
You can add `declare module '@mapbox/react-native-mapbox-gl';` to a *.d.ts file. This will at least suppress the error until the official types are out.
