### ISSUE TITLE
Speed Limit

### ISSUE THREAD

**Issue by Edison4mobile** [nitaliano/react-native-mapbox-gl#1351]
How can I show speed limit in react-native navigation app?
Is there any api to get that?

**Comment by nitaliano** [comment]
we don't have an api that I know of that can help you out here, some of our directions responses might contain that info, but for the most part you'll need a third party api for this

**Comment by Edison4mobile** [comment]
ok. thanks.

**Comment by defi-bear** [comment]
Is there any way that we can get speed limit now?
