### ISSUE TITLE
[Android] Map is just black

### ISSUE THREAD

**Issue by leiter84** [nitaliano/react-native-mapbox-gl#1355]
Hello, 

After following the tutorial I can see that map is just black with Mapbox logo in left bottom corner. Access token is valid as it works on iOS.
Seems that issue is only with simulator (Nexus 5X API 23), it works well on real device.

Here is my package.json:
```
"@mapbox/react-native-mapbox-gl": "^6.1.2",
    "prop-types": "^15.6.2",
    "react": "16.4.1",
    "react-native": "0.56.0",
```

and js code:

```
<Mapbox.MapView
          ref={_map => (this._map = _map)}
          styleURL={Mapbox.StyleURL.Street}
          zoomLevel={8}
          centerCoordinate={[-79.766235, 36.044659]}
          style={[styles.flexItem]}
        >
          {this.renderLocations()}
        </Mapbox.MapView>
```

**Comment by kristfal** [comment]
This is a know issue and will be fixed in V7.0.0 when we're moving to a more up-to-date mapbox-gl-native version for android :)

**Comment by leiter84** [comment]
Thanks, looking forward to 7.0.0

**Comment by amirkheirabadi73** [comment]
I have this problem on the physical device.
`"@mapbox/react-native-mapbox-gl": "^6.1.3"`
How I can fix this?

**Comment by IbrahimSassi** [comment]
Is there any way or workaround to fix this issue before v7 ?

**Comment by kristfal** [comment]
@IbrahimSassi use genymotion emulator
