### ISSUE TITLE
Missing release notes

### ISSUE THREAD

**Issue by hannta** [nitaliano/react-native-mapbox-gl#1357]
From recent [releases](https://github.com/mapbox/react-native-mapbox-gl/releases), there is no release notes. Release 6.1.3 is not even tagged 😟

With out release notes, I need to go through commits/pr's to understand what has changed and is there some breaking changes.

**Comment by nitaliano** [comment]
The releases were meant for one of our enterprise customers, that's why there is no tags or notes for them they were done quickly. We weren't planning on doing any releases on 6.x.x anymore and are still not planning on doing any releases under 6.x.x anymore

**Comment by hannta** [comment]
@nitaliano so next release is going to be v 7?

**Comment by nitaliano** [comment]
Yes
