### ISSUE TITLE
Class is implemented in both

### ISSUE THREAD

**Issue by dmitryHarkusha93** [nitaliano/react-native-mapbox-gl#1360]
Hi,

The application with the mapbox on simulator ios does not start.
In the Xcode logs, messages appear below.
Install mapbox manually, with cocoapods same problem.
I would be grateful for any help 

Thanks in advance!

`objc[93659]: Class MGLUserLocationHeadingBeamLayer is implemented in both /Users/dima/Library/Developer/CoreSimulator/Devices/7FCD034F-F83A-4891-AAFD-F45EEC0A4318/data/Containers/Bundle/Application/4592797D-393B-47ED-86C8-90FD56168DF5/GeoApp.app/Frameworks/Mapbox.framework/Mapbox (0x10f266248) and /Users/dima/Library/Developer/CoreSimulator/Devices/7FCD034F-F83A-4891-AAFD-F45EEC0A4318/data/Containers/Bundle/Application/4592797D-393B-47ED-86C8-90FD56168DF5/GeoApp.app/GeoApp (0x10e704150). One of the two will be used. Which one is undefined.
objc[93659]: Class MGLUserLocationHeadingArrowLayer is implemented in both /Users/dima/Library/Developer/CoreSimulator/Devices/7FCD034F-F83A-4891-AAFD-F45EEC0A4318/data/Containers/Bundle/Application/4592797D-393B-47ED-86C8-90FD56168DF5/GeoApp.app/Frameworks/Mapbox.framework/Mapbox (0x10f265528) and /Users/dima/Library/Developer/CoreSimulator/Devices/7FCD034F-F83A-4891-AAFD-F45EEC0A4318/data/Containers/Bundle/Application/4592797D-393B-47ED-86C8-90FD56168DF5/GeoApp.app/GeoApp (0x10e704830). One of the two will be used. Which one is undefined.
objc[93659]: Class MGLFaux3DUserLocationAnnotationView is implemented in both /Users/dima/Library/Developer/CoreSimulator/Devices/7FCD034F-F83A-4891-AAFD-F45EEC0A4318/data/Containers/Bundle/Application/4592797D-393B-47ED-86C8-90FD56168DF5/GeoApp.app/Frameworks/Mapbox.framework/Mapbox (0x10f264f88) and /Users/dima/Library/Developer/CoreSimulator/Devices/7FCD034F-F83A-4891-AAFD-F45EEC0A4318/data/Containers/Bundle/Application/4592797D-393B-47ED-86C8-90FD56168DF5/GeoApp.app/GeoApp (0x10e704a60). One of the two will be used. Which one is undefined.`

**Comment by dmitryHarkusha93** [comment]
Problem solved, thanks

**Comment by deepmehtait** [comment]
@yoyq: How did you solve this issue? I am getting the same issue on iOS 12.

**Comment by vedovato** [comment]
@yoyq Any solution for this? Please add it here

**Comment by Sairapp** [comment]
+1

**Comment by qlerebours** [comment]
@yoyq can you give your solution please ?

**Comment by StevieWag** [comment]
Same issue here. Came out of nowhere today with XCode 11.2.1 and iOS 13.1.2 
@yoyq: would be great if you could share your solution. Big thx!

**Comment by rossslaney** [comment]
for me this was resolved by adding 

`  MapboxGL.setAccessToken(props.Map.MapboxToken);
`

**Comment by systemlevel** [comment]
This library has been moved to here:  https://github.com/react-native-mapbox-gl/maps

**Comment by xaiamov** [comment]
My App was crashing on iOS simulator with the same "implemented in both" error in logs (which is not connected with crash). In system log I found this error: 

> Service exited due to SIGABRT

And finally the @rossslaney 's solution helped. I just missed the `MapboxGL.setAccessToken` statement.
I wonder why the library doesn't print the appropriate error message.
