### ISSUE TITLE
Vector tiles from a custom source

### ISSUE THREAD

**Issue by atkingtornado** [nitaliano/react-native-mapbox-gl#1365]
Hey all, hopefully this is the right place to post this...

I am attempting to add a VectorSource and associated LineLayer to my map from self-hosted .pbf tiles.  I can add raster layers using a url in the format "https://.../{z}/{x}/{y}.png", but I can't seem to figure out the proper way to do this for vector tiles. 

As far as I can tell, there is nothing in the documentation for non-mapbox hosted vector layers. Can anyone point me in the right direction here?

Thanks!

**Comment by kristfal** [comment]
Hey, this is fully possible. Host your own custom style.json and use that url when you initialize the map.

**Comment by stepankuzmin** [comment]
Hi there @kristfal! It seems, that there is some issues with third-party vector sources.

Consider example. I've vector source tilejson endpoint, which works perfectly with mapbox-gl-js:

```js
map.addSource('gamma.density_seasons', {
  type: 'vector',
  url: 'https://agglomerations.org/tiles/gamma.density_seasons.json'
});

map.addLayer({
  id: 'gamma.density_seasons',
  type: 'fill',
  source: 'gamma.density_seasons',
  'source-layer': 'gamma.density_seasons'
});
```

But I can't display the same source using `MapboxGL.VectorSource`:

```js
...

<MapboxGL.VectorSource
  id='gamma.density_seasons'
  url='https://agglomerations.org/tiles/gamma.density_seasons.json'
>
  <MapboxGL.FillLayer
    id='gamma.density_seasons'
    sourceID='gamma.density_seasons'
    sourceLayerID='gamma.density_seasons'
    style={mapStyles.fill}
  />
</MapboxGL.VectorSource>

...

const mapStyles = MapboxGL.StyleSheet.create({
  fill: {
    fillColor: 'blue'
  }
});
```

<img width="1077" alt="screenshot 2018-10-28 19 46 04" src="https://user-images.githubusercontent.com/533564/47618968-21daf400-daea-11e8-8b24-34bbf9efee87.png">

Am I missing something?

**P.S.** TileJSON contents: 

```json
{
  "tilejson": "2.2.0",
  "name": "gamma.density_seasons",
  "description": null,
  "version": "1.0.0",
  "attribution": null,
  "template": null,
  "legend": null,
  "scheme": "tms",
  "tiles": ["https://agglomerations.org/tiles/gamma.density_seasons/{z}/{x}/{y}.pbf"],
  "grids": null,
  "data": null,
  "minzoom": 0,
  "maxzoom": 30,
  "bounds": [-180, -90, 180, 90],
  "center": null
}
```

**Comment by kristfal** [comment]
@stepankuzmin I've actually never done a combo of mapbox basemap and custom data via VectorSource. I don't know how well/if it is supported, but you can probably check the examples.

We do the following:

```js
<MapboxGL.MapView styleURL={computedStyleUrl}>
  {this.props.children}
</MapboxGL.MapView>
```

`computedStyleUrl` is then pointing towards our custom source `style.json`. Note: This is not a tilejson, but a [fully compliant mapbox style.json](https://www.mapbox.com/mapbox-gl-js/style-spec/).

Any custom layers we append on the client side beyond what is defined in the `style.json` from `computedStyleUrl` is added as children of the mapview component. Ex:

```js
<MapboxGL.FillLayer
  id={ID.DEPCOL_LOW}
  sourceLayerID={ID.DEPCOL_LOW}
  maxZoomLevel={7}
  sourceID={SOURCE_ID}
  style={styleSheet.DEPCOL_LOW}
/>
```

Where: 

`ID.DEPCOL_LOW` is the layer name in the tile data
`sourceID` is the name of the source, matched in `style.json`

**Comment by Gnative** [comment]
@stepankuzmin did you work this one out ? Thank you in advance.
