### ISSUE TITLE
Building issue on ios

### ISSUE THREAD

**Issue by ghost** [nitaliano/react-native-mapbox-gl#1366]
When i run `react-native run-ios` i get the following error:

```
CompileC /path/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-mapbox-gl.build/Objects-normal/x86_64/RCTMGLVectorSource.o /path/node_modules/@mapbox/react-native-mapbox-gl/ios/RCTMGL/RCTMGLVectorSource.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

So i decided to open the xcode project, where i get a `Module Mapbox not found` on the CameraStop.h file.

I dont know what to do, i tried reinstalling the library and the same happens.

The versions are:
"@mapbox/react-native-mapbox-gl": "^6.1.3",
"react": "16.5.0",
"react-native": "0.57.1",

**Comment by udha19** [comment]
same issue here

**Comment by nguyenhose** [comment]
Hey guys, after 5 hours struggling with this and make it worked, there are some recommended  things you should try:
- Make sure you don't mixed between react-native-maps and mapbox, if yes, please remove react-native-maps, `rm -rf /Pods` and `pod install` again.
- `react-native link` seems not work some ways, so try to **manual** link it. Make sure you link it in .xcworkspace file. (maybe you miss this part)
- If you `react-native run-ios` fail, open X-Code: **clean and build** to determine errors, if build is success, then try `react native run-ios` again.

**Comment by udha19** [comment]
> Hey guys, after 5 hours struggling with this and make it worked, there are some recommended things you should try:
> 
> * Make sure you don't mixed between react-native-maps and mapbox, if yes, please remove react-native-maps, `rm -rf /Pods` and `pod install` again.
> * `react-native link` seems not work some ways, so try to **manual** link it. Make sure you link it in .xcworkspace file. (maybe you miss this part)
> * If you `react-native run-ios` fail, open X-Code: **clean and build** to determine errors, if build is success, then try `react native run-ios` again.

no luck, i have try this a lot

**Comment by giantss** [comment]
#1402 , Look at my ending plan, maybe I can help you.

**Comment by onitzschke** [comment]
Please follow the install instruction and checkout the example.
@nitaliano can be closed.
