### ISSUE TITLE
Why not publish react native example to PlayStore?

### ISSUE THREAD

**Issue by fuaditrockz** [nitaliano/react-native-mapbox-gl#1367]
I recommend to publish this RN example to PlayStore like Lottie, etc. Because not every people could to run the repository in local computer. So, this is solution to get live example about MapBox and we can use this code more easily.

And run the example repository is more effort and possible to get data corrupt on our local Android Studio. I got crash on my ubuntu twice to run this repo on Android Studio. And computer drop me to the black screen `(initramfs)` again and again. :disappointed: 

I know if MapBox have to publish it, but the title of the features is different with your component's title in React Native example. And we dont know where the right services that our needs. :+1:

**Comment by huyansheng3** [comment]
or provide the android example apk file

**Comment by onitzschke** [comment]
Please follow the new compile instruction and make your own apk from the source.
