### ISSUE TITLE
isUserInteraction in onRegionDidChange is incorrectly set to true

### ISSUE THREAD

**Issue by kormang** [nitaliano/react-native-mapbox-gl#1372]
Apparently this PR #1310 resolves this, but got no feedback from maintainers.

I tested this with 6.1.0 and 6.1.3.

Sometimes after calling `setCamera` `onRegionDidChange` is triggered, with `isUserInteraction` set to true, which is obviously not true. However, it is not always the case.

**Comment by kormang** [comment]
It is very difficult to reproduce, and it may have something to do with 500 miliseconds hardcoded constant in RCTMGLMapView.java

**Comment by kristfal** [comment]
This was fixed in master a few weeks ago.
