### ISSUE TITLE
Build error : library not found for -lRNTuneSDKBridge xcode 10, React Native

### ISSUE THREAD

**Issue by rcmahapatra** [nitaliano/react-native-mapbox-gl#1373]
In xcode 10 I am able to build the project in debug mode but in Release mode, build failed with the following error.

ld: library not found for -lRNTuneSDKBridge clang: error: linker command failed with exit code 1 (use -v to see invocation)

I am developing the project with React Native. It was working fine in xcode 9, after updating to xcode 10 this error comes.

Any one faced this problem? How can I resolve it?

Any help appreciated.
Thanks in advance.

**Comment by kristfal** [comment]
AFAIK, RN doesn’t fully support Xcode 10. Our workaround have been to do the initial build (that builds all packages) in Xcode 9, and then incremental builds in Xcode 10 with the legacy build system enabled to test on iOS 12 devices.
