### ISSUE TITLE
GPS accuracy

### ISSUE THREAD

**Issue by kenobi91** [nitaliano/react-native-mapbox-gl#1374]
I'm building an app where I need very accurate GPs data, is there a way to configure underlying navigation service to gain more responsive user location updates or is it better way to ditch showUserLocation altogether and manually draw circle and handle user arrow and map rotation. Also, I can't find the meaning of location object properties:

accuracy: 5
altitude: 0
heading: 0
latitude: 44.80778
longitude: 15.87092
speed: -1

on what does accuracy refers to ?

**Comment by kristfal** [comment]
Yes, you can use your own Location provider and draw a custom user location marker on top of the map. Nothing prevents you from doing this. Ex: We’re using TrnasistorSoft’s background and foreground geolocation plugin for this in production. 

Oh, and accuracy should be deviation in meters with an 80% confidence interval iirc.

**Comment by kenobi91** [comment]
Thank you for your answer I really appreciate it :)
