### ISSUE TITLE
Installation on Android

### ISSUE THREAD

**Issue by nguyenhose** [nitaliano/react-native-mapbox-gl#1378]
I tried to set up as instruction and  `react-native run-android`  but got this error

```
What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':mapbox-react-native-mapbox-gl'.
      > Could not download mapbox-android-sdk.aar (com.mapbox.mapboxsdk:mapbox-android-sdk:5.4.1)
         > Could not get resource 'https://jcenter.bintray.com/com/mapbox/mapboxsdk/mapbox-android-sdk/5.4.1/mapbox-android-sdk-5.4.1.aar'.
            > Tag mismatch!
```

The thing is I have used `react-native link` first and my config in gradle files was `@mapbox_react-native-mapbox-gl')` not `mapbox-react-native-mapbox-gl` as instruction. I have update all to `mapbox-react-native-mapbox-gl` but it doesn't work, too. Any help will be appreciated.

**Comment by FibreFoX** [comment]
I've updated the `settings.gradle` after linking using these lines:
```groovy
include ':mapbox-react-native-mapbox-gl'
project(':mapbox-react-native-mapbox-gl').projectDir = new File(rootProject.projectDir, '../node_modules/@mapbox/react-native-mapbox-gl/android/rctmgl')
```

Please make sure to include the project inside the `android/app/build.gradle` of your project.

Coming to your issue: as jcenter sometimes is buggy, you might want to update the repository-configuration, make sure to have `google()` above jcenter. This even was changed in the RN-project itself after jcenter was buggy several times.

**Comment by onitzschke** [comment]
@nguyenhose please follow the install instructions.
@nitaliano can be closed.
