### ISSUE TITLE
ShapeSource onPress not working

### ISSUE THREAD

**Issue by 386sx** [nitaliano/react-native-mapbox-gl#1380]
ShapeSource onPress seems to not work any more in my app. 
I tried several RN and RNMB versions. 
This is my code, it is basically the CustomIcon.js example since I was thinking, that it might have something to do with my, more complicated code. 

```
import React, { Component } from 'react'
import {
  StyleSheet,
  View,
} from 'react-native';

import MapboxGL from '@mapbox/react-native-mapbox-gl';

MapboxGL.setAccessToken(token);

import blueStar from '../images/bluestar.png';

const IS_ANDROID = true;

class MapScreen extends Component {
  constructor(props) {
    super(props);

    this.state = {
      featureCollection: MapboxGL.geoUtils.makeFeatureCollection(),
    };

    this.onPress = this.onPress.bind(this);
    this.onSourceLayerPress = this.onSourceLayerPress.bind(this);
  }

  async onPress(e) {
    let feature = MapboxGL.geoUtils.makeFeature(e.geometry);
    feature.id = '' + Date.now();

    this.setState({
      featureCollection: MapboxGL.geoUtils.addToFeatureCollection(
        this.state.featureCollection,
        feature,
      ),
    });
  }

  onSourceLayerPress(e) {
    const feature = e.nativeEvent.payload;
    console.log('You pressed a layer here is your feature', feature); // eslint-disable-line
}

  async onPress(e) {
   let feature = MapboxGL.geoUtils.makeFeature(e.geometry);
   feature.id = '' + Date.now();

   this.setState({
     featureCollection: MapboxGL.geoUtils.addToFeatureCollection(
       this.state.featureCollection,
       feature,
     ),
   });
 }

 onSourceLayerPress(e) {
   const feature = e.nativeEvent.payload;
   console.log('You pressed a layer here is your feature', feature); // eslint-disable-line
 }

 render() {
   return (
     <View style={styles.matchParent}>
     <MapboxGL.MapView
               zoomLevel={9}
               ref={(c) => (this._map = c)}
               onPress={this.onPress}
               centerCoordinate={[-73.970895, 40.723279]}
               style={styles.matchParent}>
               <MapboxGL.ShapeSource
                 id="symbolLocationSource"
                 hitbox={{ width: 20, height: 20 }}
                 onPress={this.onSourceLayerPress}
                 shape={this.state.featureCollection}>
                 <MapboxGL.SymbolLayer
                   id="symbolLocationSymbols"
                   minZoomLevel={1}
                   style={styles.icon}
                 />
               </MapboxGL.ShapeSource>
     </MapboxGL.MapView>
     </View>
   );
 }

}

const mapStyles = MapboxGL.StyleSheet.create({
  icon: {
     iconImage: blueStar,
     iconAllowOverlap: true,
     iconSize: 0.5,
 },
});

const styles = StyleSheet.create({
  matchParent: {
    flex: 1,
  },
});

export default MapScreen;
```
"@mapbox/react-native-mapbox-gl": "^6.1.3",
"react": "16.4.1",
"react-native": "0.56.0",

Android 8.1, tried on several devices.
With my code the app even crashes, Android log is just showing code 11, nothing meaningfull else. 
Has someone experienced anything similar?

EDIT: just tried, basically no onPress events work any more. Either on MapView nor ShapeSource...

**Comment by beisert1** [comment]
@386sx We are having the same issue, did you resolve this?

**Comment by 386sx** [comment]
Sorry, did not solve it. However I found out that the events are firing just after I ran react-native run-android. After reloading the app they won't work any more.

**Comment by beisert1** [comment]
We are experiencing the same thing. Its odd because on release build its opposite, on first launch the events dont fire at all but if you hard close and reopen they work fine. 

Can you reopen this ticket?

**Comment by 386sx** [comment]
I tried also several versions of RN and RNMBG (0.55 - 0.57. / 6.1.1 - 6.1.3). And set up a fresh project, without success.

**Comment by 386sx** [comment]
@beisert1 anything new on this issue from your side? I've been trying lots of things, removed every not vital package, still no success.

**Comment by beisert1** [comment]
@386sx We were using the react-native-restart package which was breaking the mapbox events on Android when that package initiated a restart.

**Comment by 386sx** [comment]
Ok, thanks. I'm not using that. I'll just leave this open.

**Comment by equesteo** [comment]
I am also experiencing this on `mapbox/react-native-mapbox-gl#937977ef573c7bd4ae69972720eb1ec9fd8b6be9`. Sometimes the events will fire if you uninstall and reinstall, but not always, and they definitely don't fire after a reload.

**Comment by onitzschke** [comment]
@nitaliano sounds like the hot reloading issue. I have no problems.

**Comment by onitzschke** [comment]
@kristfal is this issue still valid?

**Comment by kristfal** [comment]
This is fixed in master.
