### ISSUE TITLE
What is the difference between Mapbox and MapboxGL

### ISSUE THREAD

**Issue by allthetime** [nitaliano/react-native-mapbox-gl#1388]
So, I wrote a small app for MapboxGL and it runs flawlessly on iOS but freezes and crashes on Android when trying to load 100 markers. I switched over to Mapbox and now it actually works. 

What is the difference between the two?

I know this isn't a proper issue, I'll close it quickly after.

**Comment by nitaliano** [comment]
I'm not sure I follow what are you referring to as MapboxGL and Mapbox?

**Comment by allthetime** [comment]
@nitaliano 

You can do this:

`import Mapbox from '@mapbox/react-native-mapbox-gl'`

or this:

`import MapboxGL from '@mapbox/react-native-mapbox-gl'`

and then use either: `Mapbox.MapView` or `MapboxGL.MapView`

MapboxGL crashes quickly on Android with a minimal app, Mapbox does not.

**Comment by nitaliano** [comment]
there is no difference between those imports it's just the name of the `default` that get's exported in es6. I personally use `MapboxGL` but this in no way shape or form will cause different behavior something else is up

**Comment by allthetime** [comment]
@nitaliano  interesting. From the outset it seems like Android had much worse performance than iOS with this package. Is this an anomaly for me or is this a well known issue?

**Comment by nitaliano** [comment]
react native works better on iOS, but you need to make sure that when you're testing for performance on React Native that it's in release mode and on a device. We've used this library in the past to release apps and make demos and have had no performance issues in what we've deployed.
