### ISSUE TITLE
The dependency `yoga (from `../node_modules/react-native/ReactCommon/yoga/Yoga.podspec`)` is not used in any concrete target.

### ISSUE THREAD

**Issue by eugle** [nitaliano/react-native-mapbox-gl#1393]
project > ios > Podfile

# Flexbox Layout Manager Used By React Native
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'

  # React Native
  pod 'React', path: '../node_modules/react-native', subspecs: [
    # Comment out any unneeded subspecs to reduce bundle size.
    'Core',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTCameraRoll',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTTest',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTLinkingIOS'
  ]

  # Mapbox
  pod 'react-native-mapbox-gl', :path => '../node_modules/@mapbox/react-native-mapbox-gl'

appledeMac-Pro:ios apple$ pod install
Analyzing dependencies
[!] The dependency `yoga (from `../node_modules/react-native/ReactCommon/yoga/Yoga.podspec`)` is not used in any concrete target.
The dependency `React/Core (from `../node_modules/react-native`)` is not used in any concrete target.
The dependency `React/DevSupport (from `../node_modules/react-native`)` is not used in any concrete target.
The dependency `React/RCTActionSheet (from `../node_modules/react-native`)` is not used in any concrete target.
The dependency `React/RCTAnimation (from `../node_modules/react-native`)` is not used in any concrete target.
The dependency `React/RCTBlob (from `../node_modules/react-native`)` is not used in any concrete target.
The dependency `React/RCTCameraRoll (from `../node_modules/react-native`)` is not used in any concrete target.
The dependency `React/RCTGeolocation (from `../node_modules/react-native`)` is not used in any concrete target.
The dependency `React/RCTImage (from `../node_modules/react-native`)` is not used in any concrete target.
The dependency `React/RCTNetwork (from `../node_modules/react-native`)` is not used in any concrete target.
The dependency `React/RCTPushNotification (from `../node_modules/react-native`)` is not used in any concrete target.
The dependency `React/RCTSettings (from `../node_modules/react-native`)` is not used in any concrete target.
The dependency `React/RCTTest (from `../node_modules/react-native`)` is not used in any concrete target.
The dependency `React/RCTText (from `../node_modules/react-native`)` is not used in any concrete target.
The dependency `React/RCTVibration (from `../node_modules/react-native`)` is not used in any concrete target.
The dependency `React/RCTWebSocket (from `../node_modules/react-native`)` is not used in any concrete target.
The dependency `React/RCTLinkingIOS (from `../node_modules/react-native`)` is not used in any concrete target.
The dependency `react-native-mapbox-gl (from `../node_modules/@mapbox/react-native-mapbox-gl`)` is not used in any concrete target.

Did I do something wrong？

**Comment by eugle** [comment]
# The first step is wrong

The Podfile is in the project>ios folder

**Comment by GrosJob** [comment]
Hey there,

I just have faced the same issue as u.
I got it fixed by deleting the podfile, using 'pod init', and adding the required code after the generated content of the podfile.
I think you may have erased everything in the Podfile before pasting the content, that might be causing the issue.

Let me know if this works =)

**Comment by eugle** [comment]
I understand, it has been successful, thanks
