### ISSUE TITLE
Calculating coorQuad for ImageSource

### ISSUE THREAD

**Issue by nzwnabdulwahid** [nitaliano/react-native-mapbox-gl#1395]
![screen shot 2018-10-16 at 11 21 28 am](https://user-images.githubusercontent.com/15116775/46990822-aebe9e80-d135-11e8-8d8e-0934caa52025.png)
Hi everyone. Stated there that Animated.ImageSource would require me to provide the bounding box. From the image size, zoom level and center coordinate how would I calculate the coorQuad ?

**Comment by kristfal** [comment]
There are many utils you can use depending on the size you want for the image. Tilebelt is one of those.
