### ISSUE TITLE
How I can render only offline maps

### ISSUE THREAD

**Issue by ricardodrs** [nitaliano/react-native-mapbox-gl#1397]
Hello everyone,

I have an issue, I need to render only offline maps, without saving tiles automatically when I open my map.

I wanna know if this is possible,

thx everyone!

**Comment by RobertSasak** [comment]
This is not possible. In order to do so, you need to change code in underlying Mapbox lib.

**Comment by ricardodrs** [comment]
@RobertSasak thx for the answer.
