### ISSUE TITLE
Softer error on Styles for layers

### ISSUE THREAD

**Issue by Gp2mv3** [nitaliano/react-native-mapbox-gl#1398]
Hey guys,
I'm looking for a solution to avoid Fatal errors (Red screen) when the style isn't completely correct (error in the object).
Here is the error I receive:

<img src="https://user-images.githubusercontent.com/1221806/47168007-17f20d80-d300-11e8-99e1-49c997dcc25c.png" width="300">

I tried to put it in an ErrorBoundary element (which has a componentDidCatch method) but it doesn't help.

Is there any plan to avoid throwing a fatal error in that case ?

**Comment by kristfal** [comment]
I think the only solution for this would be very complex JavaScript side validation. That would be quite a lot of work (and maybe related to typing this lib properly). I’m up for accepting PRs, but this is something we won’t be able to prioritize moving forward as the effort will be substantial.
