### ISSUE TITLE
How to change the property of a Feature

### ISSUE THREAD

**Issue by an-kumar** [nitaliano/react-native-mapbox-gl#1401]
Let's say I want to handle the map view's onPress function and query for Features. I then want to change the property of the feature the user tapped on so that it is rendered differently (e.g, a different Layer ultimately renders it due to some filter function).

Is it efficient to simply call a `setState` to re-render the `ShapeSource`? I thought maybe not; in general, you'd want to be able to just update a single property imperatively, but that doesn't seem supported.

What's the best practice here?

**Comment by kristfal** [comment]
Speaking of experience, a scalable and declarative approach to picking is to give every feature in your source an id property. You then change rendering with runtime styling to highlight/emphasize the picked feature by having a separate layer filtered to that id. 

The main argument for this approach is that updating filters is less expensive than updating sources (and the cost of updating sources grows as the GeoJSON size grows). This approach is also fully declarative.

**Comment by onitzschke** [comment]
Closed due inactivity.
