### ISSUE TITLE
absolute icon size

### ISSUE THREAD

**Issue by an-kumar** [nitaliano/react-native-mapbox-gl#1403]
Is there a way to provide an absolute icon size rather than using the scale factor?

I have images being used as icons and I'm not sure the size before querying for it. I tried to use react-native's syntax (`{ uri, width: someWidth, height: someHeight}`) but that didn't work. I'd like to just provide absolute pixel sizes and have the renderer resize accordingly.

**Comment by onitzschke** [comment]
Closed due inactivity.

**Comment by Ballardian** [comment]
This still seems to be an issue. I also have unique use images being used as icons, so they are all different sizes, is there a way to style the icons e.g. absolute height, width and shape (circle)? This was possible with react mapbox libraries.
