### ISSUE TITLE
SymbolLayer doesn't display special characters or emojis

### ISSUE THREAD

**Issue by lightlii** [nitaliano/react-native-mapbox-gl#1407]
The app I'm trying to build sometimes requires to display emojis as part of a marker on the map but unfortunately I've been unable to make it work. Here's the code for my map :
```
<Mapbox.MapView
          styleURL={MapStyle}
          showUserLocation
          zoomLevel={15}
          centerCoordinate={this.state.userLocation}
          style={{ flex: 1 }}
          rotateEnabled={false}
          attributionEnabled={false}
          logoEnabled={false}
          animated
          ref={mapRef => (this.map = mapRef)}
          onRegionIsChanging={throttle(this.onMapBoundsChange, 500)}
        >
          <Mapbox.ShapeSource id="marker-source" shape={this.props.events}>
            <Mapbox.CircleLayer
              id="circl"
              style={{
                circleRadius: 10,
                circleColor: colours.ui.highlight,
                circleStrokeWidth: 4,
                circleStrokeColor: colours.ui.error,
                circleStrokeOpacity: 0.5,
              }}
            />

            <Mapbox.SymbolLayer
              id="ptext"
              style={{
                textField: '🏀 ⚈', // <-- the interesting bit 
              }}
            />
      </Mapbox.ShapeSource>
</Mapbox.MapView>
```

here's what happens (the CircleLayer shows where it should be):
<img width="377" alt="capture d ecran 2018-10-23 a 16 31 14" src="https://user-images.githubusercontent.com/32508751/47369129-4b0f1500-d6e3-11e8-9606-41d8ebeebbd5.png">

I've tried with plain text and it displays fine.

**Comment by KasparasGud** [comment]
Same. Not working with emojis

**Comment by kristfal** [comment]
Not sure if it is supported, but you may have better luck changing the text font to something that supports Unicode, such as Arial MS Unicode for the layer in question.

**Comment by lightlii** [comment]
Hi thanks for getting back on this one :)

@kristfal actually this was my first thought too after seeing the default value for the textFont was `[Open Sans Regular,Arial Unicode MS Regular]`. But unfortunately none of the fonts I've tried are working (including `['System']` or `['Apple Color Emoji']` which should include the glyphs for emojis.

Finally we're likely to end up using emojione's emojiset but I've had some trouble loading that into the app at the moment (I suspect it may be because EmojiOne also call their font `Apple Color Emoji` so it replaces your system's default emoji set but that's another story).

I'm increasingly sure that the problem lies with this library and would argue that it's a required feature given the it's increasing prevalence in digital communication.

**Comment by lightlii** [comment]
Hey, so I've been able to load in emojiOne now and can verify that the problem is not just a missing font. In fact the `ShapeSource` don't actually render anything when setting the `SymbolLayer`'s `textFont` to `['emojiOne']` so there's something strange going on. Here's another screenshot of what I'm getting (I've put a 🎉in the top left to confirm I've loaded in emojiOne):

<img width="375" alt="capture d ecran 2018-10-30 a 19 17 36" src="https://user-images.githubusercontent.com/32508751/47740616-82983700-dc78-11e8-8fa1-a9f1497e15fa.png">

Thanks!

**Comment by kristfal** [comment]
Could you post this issue in the native-gl repo? It is likely an upstream issue as this repo doesn’t do anything special with char codes. Feel free to reopen here if we can do something.

**Comment by dancherb** [comment]
Was any progress made on this, here or otherwise? I had a look at the native-gl repo but couldn't find a ticket there.

Has anyone found any solutions/workarounds? A few ideas (not sure if they are actually possible):

- Use a custom font specially built to contain the emojis we need. At the moment I'm having trouble making any custom font work, though (the whole symbol no longer renders).
- Refer to PNG files for every single emoji. In my app this would require me to combine two images into one symbol as I need more than just the emoji on its own, and I don't know if this is possible.
