### ISSUE TITLE
OnSelected PointAnnotation not firing

### ISSUE THREAD

**Issue by ricardodrs** [nitaliano/react-native-mapbox-gl#1409]
Hello, everyone!

I have a issue with the method OnSelected on the PointAnnotation component. When I press this point, the balloon with points information not render, but when I change my cellphone orientation the method works normally.

PS: When I press the point the method can call a console.log normally, just not render the ballon information.

(Sorry, english is not my better language)

Thx!

**Comment by claudioviola** [comment]
+1
Only in Android

```
"mapbox": "^1.0.0-beta9",
"@mapbox/geo-viewport": "^0.2.2",
"@mapbox/mapbox-sdk": "^0.4.1",
"@mapbox/react-native-mapbox-gl": "^6.1.3",
 "react": "16.6.0-alpha.8af6728",
"react-native": "0.57.4",
```

Seems there is duplicate issue here [https://github.com/mapbox/react-native-mapbox-gl/issues/1189](1189)

**Comment by ricardodrs** [comment]
@nitaliano , any solution for this?

**Comment by kristfal** [comment]
This should be fixed in master.
