### ISSUE TITLE
Option to disable callouts on annotations

### ISSUE THREAD

**Issue by priithaamer** [nitaliano/react-native-mapbox-gl#141]
Hi, is it any way possible to disable callout popovers when tapping on annotations? I see that [annotationCanShowCallout](https://github.com/mapbox/react-native-mapbox-gl/blob/ee3203b49f940b3fa6ad3c209765e6954f75f4c2/ios/RCTMapboxGL/RCTMapboxGL.m#L310) is implemented to return NO when title and subtitle are empty, but when providing annotation `{type: 'point', title: '', subtitle: ''}`it sill shows empty callout popover:

<img width="240" alt="screen shot 2015-11-18 at 16 58 29" src="https://cloud.githubusercontent.com/assets/194640/11244313/9d4c54be-8e15-11e5-9409-badf39533875.png">

**Comment by bsudekum** [comment]
Yes this will be fixed in the v2 release today.

**Comment by skeie** [comment]
Hi, is it possible to disable popovers even if title or subtitle is present?

![image](https://cloud.githubusercontent.com/assets/1346122/11834985/651a3ce2-a3d1-11e5-8727-456e34f7f12e.png)

**Comment by dsusviela** [comment]
Im having this issue with version 6.1.3 of mapbox right now
