### ISSUE TITLE
MapBoxGL Crashing when Release Uses Proguard

### ISSUE THREAD

**Issue by jimjeffers** [nitaliano/react-native-mapbox-gl#1414]
I'm having an issue when running the release variant of my application. When running in dev my maps are working just fine. But the release variant crashes when I render any map. Even the basic example from the docs. I found disabling progaurd solves the problem but that's not ideal. This is the error I get:

```
ReactNativeJS: Unexpected context found on stack. This error is likely caused by a bug in React. Please file an issue.
```

In proguard I had to add the following Mapbox related rules to get the project to compile:

```
-dontwarn com.bumptech.glide.load.resource.bitmap.VideoDecoder
-dontwarn com.mapbox.rctmgl.modules.RCTMGLSnapshotModule
```

Since the error is so cryptic I'm having trouble figuring out what may be getting stripped out of the application. Do you have any recommended progaurd rules related to this package?

**Comment by onitzschke** [comment]
@jimjeffers did you found a way you want share and can the issue be closed?

**Comment by onitzschke** [comment]
Closed due inactivity.
