### ISSUE TITLE
setCamera with mode: MapboxGL.CameraModes.Flight always zooms to 22

### ISSUE THREAD

**Issue by brendangkchan** [nitaliano/react-native-mapbox-gl#1416]
When using setCamera with `mode: MapboxGL.CameraModes.Flight`, I found that regardless what zoom value I pass, it always zooms all the way to `22`.

However if I use `mode: MapboxGL.CameraModes.Ease`, it sets the zoom correctly.

```
this._map.setCamera({
  zoom: 10,
  duration: 2000,
  centerCoordinate: geometry.coordinates,
  mode: MapboxGL.CameraModes.Flight,
});
```

**Comment by aprilzero** [comment]
we've also had some similar issues with zooming not working correctly, and going way too far in or out when setting camera (but only when building with xcode10)

**Comment by kristfal** [comment]
Fixed in master thanks to @mattijsf's PR.
