### ISSUE TITLE
Touch zoom event latency

### ISSUE THREAD

**Issue by zolero** [nitaliano/react-native-mapbox-gl#1419]
Hi Devs. I have installed a clean version of react-native and used your installation tutorial for Android.

ANDROID:
buildToolsVersion = "27.0.3"
minSdkVersion = 16
compileSdkVersion = 27
targetSdkVersion = 26
supportLibVersion = "27.1.1"

PACKAGE.json
"@mapbox/react-native-mapbox-gl": "^6.1.3",
"react": "16.6.1",
"react-native": "0.57.4"

But currently when I test touch zoom on the map on my One Plus 5T it really feels like it has latency. 
Video proof: https://drive.google.com/file/d/0B8YmIXGD6yIjVWtub2p3TXRhT1pvR1JEd1R0MUZEZno4bFZv/view

Can someone tell me why this happens? And do others experience the same?

**Comment by dariusmartin** [comment]
Same problem, any ideas ?

**Comment by kristfal** [comment]
All interactions in the map are handled by the native side. If there is an issue with performance, it is upstream in the native android lib. Please try again installing from master (it uses a newer version of the native android lib), and make sure you run the app in release mode when you test for performance.
