### ISSUE TITLE
Set the center to user location

### ISSUE THREAD

**Issue by gundam-wing** [nitaliano/react-native-mapbox-gl#142]
How can I set the center of the map to the coordinates of the user's location?

**Comment by priithaamer** [comment]
Currently, i was only able to do it in a slightly hacky way but it kind of works with something like this:

``` javascript
constructor() {
  super();
  this.state = {centered: false};
}

handleUpdateUserLocation(center) {
  if (this.state.centered === false) {
    this.setCenterCoordinateAnimated('map', center.latitude, center.longitude);
    this.setState({centered: true});
    // You may also want to turn off user location tracking here
  }
}

render() {
  return (<MapBox
    ref="map"
    onUpdateUserLocation={this.handleUpdateUserLocation.bind(this)}
  />);
}
```

**Comment by friedbunny** [comment]
It looks like we're lacking access to the `userTrackingMode` setting on iOS, which would allow the map to automatically recenter on user location updates — see #145.

**Comment by gundam-wing** [comment]
@priithaamer Thanks

**Comment by bsudekum** [comment]
You can now use `userTrackingMode={this.userTrackingMode.follow}` in v2.0.0 and it will center on the user.

**Comment by doriansgithub** [comment]
i can't get it to work, even with the follow tracking mode.  I can see the my location beacon, but it will not center and/or zoom on it's own. 

- (void)zoomToUserLocationMapBox{
    NSLog(@"zoomToUsersLocationMapBox");
    
    _mapBoxView.userTrackingMode = MGLUserTrackingModeFollowWithHeading;
    _mapBoxView.showsUserLocation = YES;
   _mapBoxView.showsHeading = YES;
    
    CLLocationCoordinate2D centerCoordinate =
    CLLocationCoordinate2DMake(38.894368, -77.036487);
    
    [_mapBoxView setCenterCoordinate:centerCoordinate
                           zoomLevel:15
                            animated:YES];
}

I also don't understand why the sample provides these random coordinates, instead of the user's location code.

**Comment by doriansgithub** [comment]
It now works when I do a search off a code that has nothing to do with Mapbox.  There must be something linked between Mapbox and MapKit that's triggering it.  I'll find it.
