### ISSUE TITLE
Not able to install example npm dependencies

### ISSUE THREAD

**Issue by JGeraldoLima** [nitaliano/react-native-mapbox-gl#1422]
Hi, great lib you guys have here!

I'm trying to run the example, I already generated a token and created `accesstoken` file, but when I run `npm install`, the following errors occurs:
![image](https://user-images.githubusercontent.com/6726996/48496852-b2674300-e811-11e8-9ec7-152a4fc21a6b.png)

In fact, the **mapbox-react-native-mapbox-gl-6.1.3.tgz** does not exist in the project, and it is declared as `file` dependency on `package.json`.

Could anyone help me?

**Comment by JGeraldoLima** [comment]
Just solved it by changing the dependency version to `6.1.2` (latest release available) and the file extension to `tar.gz` (instead of `tgz`) and downloading manually the release file to **project root** (not inside **example** folder).

But, when I run `npm start`:

![image](https://user-images.githubusercontent.com/6726996/48498194-74b7e980-e814-11e8-9792-40951366e7d9.png)

Please, fix it :/

**Comment by onitzschke** [comment]
@nitaliano the example is updated and proofed that it works. 
This issue can be closed.
