### ISSUE TITLE
Support for custom annotations on Map like Airbnb

### ISSUE THREAD

**Issue by arunshan** [nitaliano/react-native-mapbox-gl#143]
Is there a way to show text/description on all annotations something like this:
![slack for ios upload 7](https://cloud.githubusercontent.com/assets/1124102/11252468/35d2394a-8deb-11e5-96e3-60dab49c1169.png)

**Comment by guofoo** [comment]
This would be nice

**Comment by sonnylazuardi** [comment]
+1

**Comment by brianjd** [comment]
I was thinking support for custom view annotations.  But for something like this, as a workaround, you can always just create the images for all of the possible values, then programatically reference the correct image when creating the annotation.

**Comment by dhruvappstack** [comment]
Can you suggest code for iOS

**Comment by ghost** [comment]
Is anyone willing to help implementing this on the iOS side?
I have a working Android prototype:
![custom](https://cloud.githubusercontent.com/assets/16978609/15351105/51c8ebc2-1c92-11e6-994f-19936897460c.gif)

**Comment by dhruvappstack** [comment]
I have implemented # **Airbnb like scroll effect** steps:-
Part-1 : When collectionview is scrolled
Make custom annotation class
Plot annotation using categories of custom image icons while adding the annotaion to map

1.Create categories of custom images
2.Using custom annotation class pass the title for annotation
3.Now when bottom collection view is scrolled the indexpath of collection view will matched with annotions which have same data like "array with dictionary."
4.In view scrollviewdidend delegate method calculate index path by visible collection view cell
indexpath = self.collectionviewCustom.origin.x/self.collectionviewCustom.bounds.size.width
this will give correct indexpath of visible cell
5.Now you have correct indexPath now them highlight the annotation by using 
for annotation in self.mapview.annotations
{
if customAnnotion.title == annotion.title{
select the annotion 
} You have to reload the annotations
6.When you select the annotion it will call viewfor annnotion
7.Now you can easily change the annotionView.image = UIImage(name:"abc.png")
you can take a variable which is like isSelected(Bool) .It will assign custom categories of images in view for annotation in viewforannotation
**Part -II** 
When you tap on annotation
1.When you tap on annotation the didtapOnAnnotion is called .Now you have annotionview 
2.Pass this view to viewforAnnotions and set it selected 
3.When selected it will go at viewforannotion and using isSelected(Bool) custom  variable set true in didTapOnAnnotation change the annotaionView.image = UIImage.(named"custom.png")
4.For scrollong the bootim collection you have to set the tag variable for custom annotation view then on didTapOnAnnotation view match the title of annoation view with arrayModal data title or tag variable modal object
5.Using self.collectionview scrollToindexPath:annotion.tag animated:true

**Comment by dhruvappstack** [comment]
**AlexLourenco**
For problem you are using third party library MapBox but you can use native mapkit
Now you use same procedure i mentioned above
1.To change the tapped annotation view title you have to reload it by selecting it 
2.When you select it or tap it the didTapOnAnnotion called and you have annotationview pass it to viewforannotation
3.it will call viewforannotation For **MapBox** it will have some method like viewforannotaion
4.Now in viewforannotation you can change the title ,image and anything you assinged to annotion view .In you your case i think you are changing the title or subtitle.

**Comment by brianjd** [comment]
@AlexLourenco Is there a fork somewhere? 

@bsudekum Is this anywhere in the roadmap?

**Comment by ghost** [comment]
@dapetcu21 Are you going to take a stab at implementing Annotation Views or are you able to provide any guidance/references on how to implement it properly do it?
On the Android side I had it working in the same fashion as react-native-maps (passing the View as children of the map, although it did not feel quite right).

**Comment by dapetcu21** [comment]
Hi. Unfortunately, I’m in a very busy period and I don’t know how much time
I can put into open source for the immediate future.

As far as implementation is concerned, I have no idea how to pass views up
to the native side. I guess, if you could pass them as children that’d be
nice, but I’m not sure that’s optimal (as you’re ideally only supposed to
render markers when they’re in view and the map requests them.

**Comment by gravitinos** [comment]
@AlexLourenco do you have this in a branch somewhere? I'm very interested in taking a stab at this.

**Comment by ghost** [comment]
@xvalentino I should have my changes backup'ed up somewhere. I am extremely busy for the next couple of days but afterwards I will make sure to take a look and adapt the changes to the newest version (again its going to be android only and it wont be a perfect implementation) and make a branch. If you don't hear from me by then feel free to ping me just as a reminder.

**Comment by ghost** [comment]
@dapetcu21 Today I had a couple of hours to look into this and was able to get it to work on iOS. I wanted to double check with you if there's any performance hit in keeping the annotation in the state of the Map component rather than just relying on the props? My ReceiveNewProps still needs some work as it was highly monkey patch - I need to make sure to clear the View's when the annotation is removed/mutated.

Hopefully I will be able to make some time to do the same work on Android.

Here's some views being animated on the react side:

![hover](https://cloud.githubusercontent.com/assets/16978609/18046499/0bae9a00-6d8d-11e6-8057-54c52efe929b.gif)

**Comment by dapetcu21** [comment]
Hi. That's awesome. About the performance hit, I don't know what you mean. Can you make a pull request so that I can look over the code?

**Comment by wafisher** [comment]
Do you mind describing/showing how this is done?
