### ISSUE TITLE
MGLMapboxMetricsEnabledSettingShownInApp=YES not being seen in Info.plist

### ISSUE THREAD

**Issue by binaryminutia0l** [nitaliano/react-native-mapbox-gl#1431]
I've added MGLMapboxMetricsEnabledSettingShownInApp=YES in my app's Info.plist:
```
...
<key>NSLocationWhenInUseUsageDescription</key>
<string/>
<key>MGLMapboxMetricsEnabledSettingShownInApp</key>
<true/>
<key>NSAppTransportSecurity</key>
...
```

But when I use `attributionEnabled={false}` with a `MapView` I still get the error that it is required:

<img width="426" alt="screenshot 2018-11-21 at 14 06 52" src="https://user-images.githubusercontent.com/10885475/48846306-b73e7080-ed96-11e8-8844-e47d46de0755.png">

**Comment by systemlevel** [comment]
@sfyfe31 It needs to be a boolean value.  Not a `<string/>`.

**Comment by ospfranco** [comment]
I have this problem as well, the plist posted by sfyfe is correct, the <true/> value is a boolean, but I still get the same error

**Comment by ospfranco** [comment]
Cleaning the project and doing a fresh build solved my problem, the property seems to be recognized just fine
