### ISSUE TITLE
Any way to ensure SymbolLayer text and Map Labels don't overlap?

### ISSUE THREAD

**Issue by KasparasGud** [nitaliano/react-native-mapbox-gl#1434]
I Have a ShapeSource and I render some text with SymbolLayer having an offset. However, this text overlaps with the labels of the map like for example the street names. Is there any way to avoid this? Tried playing with every setting at this point and nothing seemed to work. Help would be much appreaciated 🙏🏻

This is the problem: 

![simulator screen shot - iphone 8 - 2018-11-24 at 00 59 19](https://user-images.githubusercontent.com/21368701/48962748-04803500-ef85-11e8-95e7-ee8eb2786356.png)

Code: 

<img width="785" alt="screen shot 2018-11-24 at 01 07 40" src="https://user-images.githubusercontent.com/21368701/48962768-63de4500-ef85-11e8-95a5-e2bbf275cf58.png">

**Comment by onitzschke** [comment]
Please check https://github.com/nitaliano/react-native-mapbox-gl/issues/1483

If you solved your problem please close this issue and share the way you did it.

**Comment by kristfal** [comment]
Cross source label collision is not supported by the underlying native SDK versions we currently use in this repo. This will be resolved once we get the 6.0.0 branch finished.
