### ISSUE TITLE
master fails to render map on iOS using RN 0.15.0-rc

### ISSUE THREAD

**Issue by jsierles** [nitaliano/react-native-mapbox-gl#144]
Using the following example, the map renders fine on Android but is completely blank on iOS. I have installed the Settings and Mapbox bundle as directed. Any ideas?

```
  <Mapbox
            accessToken={'mytoken'}
            styleUrl={'asset://styles/streets-v8.json'}
            direction={0}
            onRegionChange={this.onRegionChange}
            rotationEnabled={true}
            scrollEnabled={true}
            showsUserLocation={true}
            UserLocationTrackingMode={'FOLLOW'}
            zoomEnabled={true}
            zoomLevel={10}
            style={styles.map}
       />

```

**Comment by friedbunny** [comment]
With #140 and the update to Mapbox iOS SDK v3.0.0pre7, the `styleUrl` properties for default styles changed from URL strings to constants. The new format looks like: `styleUrl={this.styles.streets}`

See the [API docs](https://github.com/mapbox/react-native-mapbox-gl/blob/ee3203b49f940b3fa6ad3c209765e6954f75f4c2/ios/API.md#styles) for the full details and other styles.

**Comment by jsierles** [comment]
How can I access these without using the mixin? I'm using es6 classes.

**Comment by friedbunny** [comment]
You could skip the constants and use the style URLs directly, e.g. `mapbox://styles/mapbox/streets-v8`.

**Comment by bsudekum** [comment]
@jsierles the next release is going to be a breaking release and the `assets://` path is no longer going to be supported. If you'd like something that will work on both android and iOS, use the `mapbox://` url path. 
- mapbox://styles/mapbox/streets-v8
- mapbox://styles/mapbox/emerald-v8
- mapbox://styles/mapbox/dark-v8
- mapbox://styles/mapbox/light-v8
- mapbox://styles/mapbox/satellite-v8
- mapbox://styles/mapbox/streets-hybrid-v8

Or create a style in [mapbox studio](https://www.mapbox.com/studio/) and add it to the map

**Comment by bsudekum** [comment]
Note: [I just changed](https://github.com/mapbox/react-native-mapbox-gl/pull/149) this.styles.streets -> this.mapStyles.streets so there is not a collision in projects. The word `styles` is used a lot in react projects.
