### ISSUE TITLE
Best camera config for navigation

### ISSUE THREAD

**Issue by hamswaldenkv** [nitaliano/react-native-mapbox-gl#1440]
Hello
I'm working on a navigation test app, but i can have the correct camera perspective for navigation
that my example 
`this.map.setCamera({
	stops: [
		{ centerCoordinate: payloads.locationToShow, duration: 100 },
		{ zoom: 17, duration: 100 },
		{ pitch: 45, duration: 100 },
		{ heading: 180, duration: 100 },
	],
});`

How can i have the best pitch and heading for setCamera in navigation mode?

**Comment by EricPKerr** [comment]
You're going to have a lot better luck setting all of those properties at once (at least potentially until v7 drops) instead of doing them sequentially with the `stops`

**Comment by hamswaldenkv** [comment]
Whats the best config for having this cameraView @EricPKerr 
![Image of Yaktocat](http://soileiragusgonta.com/wp-content/uploads/2018/04/road-map-navigation-16-google-maps-for-motorola-droid-beta.jpg)

**Comment by EricPKerr** [comment]
You essentially have it right, just do the setCamera all at once like:

```
this.map.setCamera({
  centerCoordinate: payloads.locationToShow,
  zoom: 17,
  pitch: 45,
  heading: 180,
  duration: 100,
  mode: MapboxGL.CameraModes.Ease
});
```

**Comment by hamswaldenkv** [comment]
thanks a lot @EricPKerr
