### ISSUE TITLE
Good resource/example using offline maps in RN ?

### ISSUE THREAD

**Issue by 29er** [nitaliano/react-native-mapbox-gl#1443]
Hi !
Could anyone point me to a good resource, docs, etc that show examples of using offline maps in RN?
Thanks so much !

**Comment by kristfal** [comment]
Your best bet is the official [offline manager docs](https://github.com/mapbox/react-native-mapbox-gl/blob/master/docs/OfflineManager.md). If you need more help, check out this repo's gitter.

**Comment by NathanNovak** [comment]
@kristfal I am having some issues using offlineManager and the implementation of it.  It keeps crashing through xcode.  Is there any clear docs or examples to look at?

**Comment by systemlevel** [comment]
You’re using the old RN map box lib here. Please first try on the new community supported RN mapbox gl library and open issues there.
