### ISSUE TITLE
Satellite view gets black

### ISSUE THREAD

**Issue by shrikantkunte** [nitaliano/react-native-mapbox-gl#1444]
@kkaefer  I'm using react-native-mapbox-gl in my project. I have added some RasterLayers to map. When I set map styleURL to "MapboxGL.StyleURL.Satellite" and zoomed in over zoom level 15, the map becomes black. Zoom-in over level 15 works fine for "MapboxGL.StyleURL.Street". Also when I remove RasterLayers it works fine for both "MapboxGL.StyleURL.Satellite" and "MapboxGL.StyleURL.Stree"

**Comment by kristfal** [comment]
Satellite tiles has a max zoom level of 15, whereas other layers have other max zoom levels. You'll need to limit the max zoom level of the app to 15 if you want to show Satellite.
