### ISSUE TITLE
userTrackingMode not working correctly on Android

### ISSUE THREAD

**Issue by shrikantkunte** [nitaliano/react-native-mapbox-gl#1446]
@nitaliano in my react-native app, I have set 'userTrackingMode={Mapbox.UserTrackingModes.FollowWithHeading}'. In iOS I can see pulsating point to track user location but in Android user location is denoting by just a point. How can I get pulsating point in Android as well.

**Comment by kristfal** [comment]
@shrikantkunte the native implementation for these platforms are different. This wrapper just exposes those implementations. 

If you want to have a completely similar style between iOs and Android, your best bet is to create your own user location layer and style that yourself.
