### ISSUE TITLE
iOS: support `userTrackingMode`

### ISSUE THREAD

**Issue by friedbunny** [nitaliano/react-native-mapbox-gl#145]
The iOS SDK offers the `mapView.userTrackingMode` property to allow the map view to automatically center on and follow the user's coordinates. It looks like Android has support here via [`UserLocationTrackingMode`](https://github.com/mapbox/react-native-mapbox-gl/blob/3a7109b6ed0c3982dfc3b2cec100fa16f77e185e/index.android.js#L29), but the iOS implementation is missing.

[Here are the possible values](https://github.com/mapbox/mapbox-gl-native/blob/ddc4a8193e775d9cd9280ad7d9bb6975b4a323ee/include/mbgl/ios/MGLTypes.h#L17-L27) for `MGLMapView.userTrackingMode`:

``` objc
/** The mode used to track the user location on the map. */
typedef NS_ENUM(NSUInteger, MGLUserTrackingMode) {
    /** The map does not follow the user location. */
    MGLUserTrackingModeNone              = 0,
    /** The map follows the user location. */
    MGLUserTrackingModeFollow,
    /** The map follows the user location and rotates when the heading changes. */
    MGLUserTrackingModeFollowWithHeading,
    /** The map follows the user location and rotates when the course changes. */
    MGLUserTrackingModeFollowWithCourse,
};
```

/cc @bsudekum

**Comment by gundam-wing** [comment]
How would one implement this?
