### ISSUE TITLE
Cannot read property '_currentGeohashesQueried' of undefined

### ISSUE THREAD

**Issue by felixchan** [nitaliano/react-native-mapbox-gl#1458]
When I am updating the criteria for the query, oftentimes I get this error thrown.  I have tried to put a try/catch block around `updateCriteria`, but this error still happens. Perhaps I am updating too quickly, and I should throttle it?

Is there a way to check if the query is currently updating, and if so, do not update?

**Comment by daniyal-intellicel** [comment]
I am facing the same issue I am recursively updating radius using update criteria, but I get this error after fixed number of calls always.

**Comment by jcampana** [comment]
@felixchan @daniyal-intellicel I have the same issue, what solution we applied? Thanks!!!
