### ISSUE TITLE
[iOS] Code Signing Issue on Distribute App

### ISSUE THREAD

**Issue by fantasywind** [nitaliano/react-native-mapbox-gl#1463]
- Version: 6.1.3
- RN Version: 0.57.8

Running on development mode is normally (Simulator and Real Device). But after archiving distribute to app store, always showing the code sign error on Mapbox.framework.

### Debug:
Build Phase Script (Already set)
```
"${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Mapbox.framework/strip-frameworks.sh"
```
### Archive Log:
![screen shot 2019-01-07 at 00 03 15](https://user-images.githubusercontent.com/1902526/50738502-a7c49b00-120f-11e9-9932-da215c5b1d60.png)

Seems SDK signing script issue, tried to replace
```shell
for file in $(find . -type f -perm +111); do
```
with
```shell
for file in $(find . -type f -perm 111); do
```

But still not working after the find invalid message missing.

**Comment by fantasywind** [comment]
It fixed if replace the script into
```shell
for file in $(find . -type f); do
```
sign for each files

**Comment by ansarikhurshid786** [comment]
can you post steps because i coudnt find script info

**Comment by systemlevel** [comment]
Hey guys, this repo is no longer officially maintained.  Head on over here https://github.com/react-native-mapbox-gl/maps and join the new club.
