### ISSUE TITLE
onPress is too slow

### ISSUE THREAD

**Issue by dannylazarow2** [nitaliano/react-native-mapbox-gl#1464]
* Version: 6.1.3
* RN Version: 0.57.8

When I press on map and register `onPress` call back on MapView like this
`<MapBoxGl.MapView onPress={() => console.log('test')} />` 

I receive events with 1s delay.
If I put the mapview inside a `TouchableOpacity` it fires onPress immediately like theis
`<TouchableOpacity onPress={() => console.log('test')}><MapBoxGl.MapView /></TouchableOpacity>`

All good however the upper hack works only on iOS because Mapview passes gestures (bubles them up) to the upper component. On Android it does not however

I need faster feedback, right now the map feels sluggish when try show popup after I press it

**Comment by jussirantala** [comment]
I'm using the same versions on Android and the onPress event doesn't get called at all. It worked before upgrading versions. Double clicking the map does zoom in though.

EDIT: For now it does work for some reason.

**Comment by felixgourdeau** [comment]
Same issue here, there is 500ms-1sec delay before the onPress callback gets fired.

**Comment by karlguillotte** [comment]
I have the same issue. More noticeable on Android. 

@jussirantala Running 6.1.1 in production due to press event handling issues on Android.

**Comment by aprilzero** [comment]
We have seen this issue too

**Comment by zolero** [comment]
Same issue here...

**Comment by ippa** [comment]
Not sure if related, but `<Mapbox.ShapeSource onPress ...` that's been working fine on iOS seems to be broken on Android. RN 0.58.6 and latest mapbox.

**Comment by Blind12** [comment]
Get this issue on Android too

**Comment by kristfal** [comment]
We just updated this repo to support RN59 and fixed a few issues around reconnecting event listeners in dev mode for Android. I'd recommend you try RN59 with the new Android JSC to see if the problems still persists.

**Comment by LeVadim** [comment]
Same issue remains, even on IOS, there is a slight delay of 05-1s and afterwards, Annotations don't get clicked at all

**Comment by kristfal** [comment]
We use shape sources with onPress in the main map view and queryRenderedFeatures to identify what is pressed on. 

There is a small delay from press to interaction, but the performance of our app is equivalent to that of google maps, so I think it is good enough. You may want to try that approach.

**Comment by LeVadim** [comment]
The performance of Mapbox is absolutely perfect, no doubt in that.
I am just comparing PointAnnotations and mentioning that when I prerss on PointAnnotation is fires onPress event right away, instantly.. vs Shape which has a great delay..
Just wanted to see how to reduce the delay for Shape because I saw that PointAnnotation will be deprecated some time in the future..
Thank you

**Comment by ghost** [comment]
This is not a very good solution but you can try this on your `View`
`<View onTouchStart-{ funtionName }>....</View>`

This might help -
https://reactnative.dev/docs/gesture-responder-system

**Comment by mglonnro** [comment]
Any news on this? I'm running a development mode expo app and am noticing the same kind of delays (0.3 - 0.5 sec) between a `<Pressable onPress...>` wrapped around a `<MapView onPress...>` (which fires at the same times as the `<ShapeSource onPres...>`).

I guess there is a lot going on between the actual press and the `onPress` (I have a shapesource with ~40 000 objects, for sintance), but to get a responsible UI it would be great to be able to react quickly on the "finger down" event. 

`Pressable` would be a workaround, but I don't know how to filter out all the other press events (ie when panning the map). Ideally mapbox could send one event immediately when it notices the press, and another after it has finished processing it.

**Comment by dilotec-2015** [comment]
the problem is still there. any solution for this issue?
