### ISSUE TITLE
How to use sprites in layer ?

### ISSUE THREAD

**Issue by qlerebours** [nitaliano/react-native-mapbox-gl#1465]
Hi,

i'd like to use sprites to prevent loading a lot of .png files in my app (approximatively 800 files), but I can't make it work. I found two ways to use it:
 - The first way is with custom StyleURL but for the moment, it seems broken, related to #1215 
 - The second way would be to use `sprite` property referenced in [style-spec](https://github.com/mapbox/react-native-mapbox-gl/blob/master/style-spec/v8.json), but I don't know what are those specs. Do they match with Mapbox Studio styles specs ? Or is there somewhere (In a `Source`, a `Layer` or somewhere else) where I can use this property an give a base URL that will be suffixed by `.json` or `.png` to find the sprite I want ?

Help would be appreciated here, 
Thanks for the great work

**Comment by kristfal** [comment]
Custom StyleURL works just fine. I'd recommend building that along with a custom spritesheet.

**Comment by qlerebours** [comment]
This is related to #1215 but there is still no documentation about which SDK version should be used to make the customStyleUrl works.
You repeated multiple times that custom styles are working fine, but it seems that no one can make it work ...
