### ISSUE TITLE
GeoJSON LineString (a closed loop) display broken at zoom levels above 18 

### ISSUE THREAD

**Issue by mehdialouafi** [nitaliano/react-native-mapbox-gl#1467]
Hello,

I have the exact same problem described here : https://github.com/mapbox/mapbox-gl-js/issues/4202

Here is the copy if you do not want to click : 

**Version**
react-native-mapbox-gl version: : 6.1.3
react-native : 0.56.0

**Steps to Trigger Behavior**
If you zoom out, the LineString displays properly, zooming in to levels above 18 breaks LineString display. This only occurs with LineStrings which are closed loops.

**Expected Behavior**
The LineString should display at all zoom levels

**Actual Behavior**
The LineString is broken at all zoom levels above 18

Edit : I ended up using the react-native-maps library coupled with a google provider and it works like a charm, I hope this will be resolved soon, Many thanks for this great library !

**Comment by kristfal** [comment]
Thanks for reporting. This is an upstream issue with the native SDKs. It may very well have been fixed in the native side, but we're quite far behind. Closing.
