### ISSUE TITLE
Using local style JSON rather than a URL

### ISSUE THREAD

**Issue by jliebrand** [nitaliano/react-native-mapbox-gl#1468]
How can I pass a local JSON style object to MapView rather than pointing it to a hosted style?

(and in addition to that, can the JSON also contain a pointer to a local sprite png?)

**Comment by kristfal** [comment]
You can use a file URL to point towards a style.json locally on your devuce or serve an empty style.json (just containing sources) from the server side and repopulate it fully by runtime styling.
