### ISSUE TITLE
Running example results in white screen with red border

### ISSUE THREAD

**Issue by sammosampson** [nitaliano/react-native-mapbox-gl#147]

**Comment by sammosampson** [comment]
Stupidity in set up thats all

**Comment by zakir2k** [comment]
@sammosampson please share. getting the same issue - can't for the life of me figure out the setup problems.

**Comment by sammosampson** [comment]
For me it was because I didn't follow the setup instructions (
https://github.com/mapbox/react-native-mapbox-gl/blob/master/android/install.md)
exactly. Specifically the changes to MainActivity and Gradle settings.
