### ISSUE TITLE
Local data join with JSON

### ISSUE THREAD

**Issue by smol-honk** [nitaliano/react-native-mapbox-gl#1470]
I'm trying to achieve this 
https://www.mapbox.com/mapbox-gl-js/example/data-join/ 
but I'm not sure how to do this via the React Native version.

**Comment by kristfal** [comment]
The example uses expressions, a feature that haven't hit this repo yet. It will be available in a few weeks I believe. You can achieve the same result with filters, but the code and approach will be different.

You can look at:

https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/DataDrivenCircleColors.js

and

https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/YoYo.js

and merge those two approaches using filters to achieve the same result. I recommend you ask on stackoverflow if you need more guidance.
