### ISSUE TITLE
Dynamically Loaded ShapeSource's not displaying [React-Native]

### ISSUE THREAD

**Issue by addboa** [nitaliano/react-native-mapbox-gl#1473]
I am trying to dynamically load multiple Shapesources in a Mapview in my React Native App.
In the iOS View Hierarchy Debugger I can see that the ShapeSources are being created; however, they are not visible.
<img width="592" alt="screen shot 2019-01-14 at 5 49 52 am" src="https://user-images.githubusercontent.com/45373286/51098394-afb5a980-17d2-11e9-9f9a-fcd515ab82fd.png">

Is there a reason these views are not displaying?

**Code**
```
renderParkingSpaces() {
  const parking_space_shapes = [];
  all_parking_space_shapes.forEach((parking_shape, index) => {
        parking_space_shapes.push(
          <Mapbox.ShapeSource
            id={parking_shape["id"]}
            key={'parking_spaces' + index}
            shape={parking_shape}>
            <Mapbox.FillLayer
              id ='parking_space_fill'
              key={'parking_spaces_fill' + index}
              style={layerStyles.parking_spaces} />
          </Mapbox.ShapeSource>
        ) 
      });

  return parking_space_shapes
}

.
.
.

render() {
    return (
      <View style={styles.container}>

        <Mapbox.MapView
        centerCoordinate={this.state.centerCoordinate}
        showUserLocation={true}
        style={styles.container}
        styleURL={Mapbox.StyleURL.Street}
        zoomLevel={16}>

          <Mapbox.ShapeSource
            id='parking_lot'
            shape={this.getLot()}>
            <Mapbox.FillLayer
              id='fill_parking_lot'
              style={layerStyles.parking_lot} />
          </Mapbox.ShapeSource>

          <Mapbox.ShapeSource
            id ='buildings'
            shape={this.getBuildings()}>
            <Mapbox.FillLayer
              id ='fill_buildings_lot'
              style={layerStyles.buildings} />
          </Mapbox.ShapeSource>

          {this.renderParkingSpaces()}

        </Mapbox.MapView>

      </View>

    )
  }
```

NOTE: When I pursue another route to display these polygons (using the coordinates to construct a multipolygon) the shapes display so the issue is not with my polygon's coordinates.

<img width="316" alt="screen shot 2019-01-14 at 7 39 31 am" src="https://user-images.githubusercontent.com/45373286/51098389-a0cef700-17d2-11e9-94ec-b18831b90f5d.png">

Related Issues that have not quite helped me solve the issue on React Native: https://github.com/mapbox/react-native-mapbox-gl/issues/948

**Comment by addboa** [comment]
I think it's important for me to have multiple ShapeSource's because I would like to have unique on-click handling for each polygon.

**Comment by addboa** [comment]
I went in another direction and used FeatureCollection whose individual Features are returned by the FeatureCollection's onPress action 

Props to @alexneigher for this direction

**Comment by shafiqshams** [comment]
@addboa how you solved this problem to click a unique polygon of specific Feature.
I have tried FeatureCollection already, it worked well but I don't have a clue to get the specific onClick for each polygon.
Can you help me?

**Comment by systemlevel** [comment]
This is an old, stale library. Please move to new community supported one: https://github.com/rnmapbox/maps
