### ISSUE TITLE
Changing Circle Radius instead of zooming

### ISSUE THREAD

**Issue by zgrybus** [nitaliano/react-native-mapbox-gl#1475]
I am using circle from [turf.js/circle](https://github.com/Turfjs/turf/tree/master/packages/turf-circle). 

Actually, I want to change circle radius ( when Its clicked and then moved ) instead of zooming in / out.

How can I achieve that? Is it even possible with that library?

**Comment by nitaliano** [comment]
update the `circleRadius` on your `CircleLayer` and it will automatically update it for you
