### ISSUE TITLE
calling `Mapbox.setAccessToken()` function makes my application to crash

### ISSUE THREAD

**Issue by blueturtle13g** [nitaliano/react-native-mapbox-gl#1477]
hello I'm following mapbox tutorial for react native https://www.mapbox.com/help/tutorials/first-steps-react-native-sdk/ .
this is the code that they've given as the first example:
`
    import React, { Component } from 'react';
    import { StyleSheet, View } from 'react-native';
    import Mapbox from '@mapbox/react-native-mapbox-gl';
Mapbox.setAccessToken('pk.eyJ1IjoicGlhMTMiLCJhIjoiY2pyMHFkbjd2MG42eDQycXF1ODg5em5yOCJ9.of1u8U450sFMBUsZ8TkkCQ');
export default class App extends Component<{}> {
  render() {
    return (
      <View style={styles.container}>
        <Mapbox.MapView
            styleURL={Mapbox.StyleURL.Street}
            zoomLevel={15}
            centerCoordinate={[11.256, 43.770]}
            style={styles.container}>
        </Mapbox.MapView>
      </View>
    );
  }
}
const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});
`

but my application kept crashing(I get this error "applicationName has stopped"), so I removed some codes step by step and noticed that commenting out `Mapbox.setAccessToken` function prevents my app from crashing.
I also change the `AccessToken` to  my own accesToken but didn't work.
OS: windows 10
`  "dependencies": {
    "@mapbox/react-native-mapbox-gl": "^6.1.3",
    "react": "16.6.3",
    "react-native": "0.57.8",`

**Comment by Naop** [comment]
Hello, I was having the same issue with the following dependencies:
```
"dependencies": {
    "@mapbox/react-native-mapbox-gl": "^6.1.3",
    "react": "16.7.0",
    "react-native": "0.57.8",
  }
```
I found that the solution proposed in [#1139 (comment)](https://github.com/mapbox/react-native-mapbox-gl/issues/1139#issuecomment-379647942) worked.

**Comment by onitzschke** [comment]
It's dependencies related and updated in the example.
