### ISSUE TITLE
No Map Display at All

### ISSUE THREAD

**Issue by jasoncoffman** [nitaliano/react-native-mapbox-gl#1478]
I have been developing an application with a mapbox component, and have never had an issue with it not rendering. I recently tried to load the application onto a tablet running Android 4.2.2 and the flex box region where the map is embedded is completely blank -- not even displaying the mapbox logo. 

I have generated a second API token in hopes of that being the issue, but it didn't work. When i try to inspect the region within the application I get an error that reads: "expected to find at least one react renderer".

**Comment by systemlevel** [comment]
+1

<img width="559" alt="screen shot 2019-01-19 at 1 17 01 am" src="https://user-images.githubusercontent.com/894983/51424202-f23b0580-1b87-11e9-8c40-d616d198d312.png">

New install of react-native-mapbox-gl and I can't get a basic map to load.

I've imported: `import MapboxGL from '@mapbox/react-native-mapbox-gl';`

I've set the Mapbox Key.

Here's what's rendering in the screenshot:

```
      <View style={styles.container}>
        <MapboxGL.MapView
          zoomLevel={9}
          centerCoordinate={[-73.970895, 40.723279]}
          style={{ flex: 1 }}
        />
        <Button title="Show me the map" onPress={this._showMoreApp} />
        <Button title="Actually, sign me out :)" onPress={this._signOutAsync} />
      </View>
```

Blank.  

I've run through the manual installation process twice already to ensure all steps were done.  No errors in the console or during build.  

Anyone experience this?

**Comment by systemlevel** [comment]
When I remove react navigation my maps start to appear.  What would react navigation be doing to prevent mapbox from displaying?

**Comment by onitzschke** [comment]
Did you fixed your problem?

**Comment by systemlevel** [comment]
> Did you fixed your problem?

@onitzschke Mine was fixed when I removed react navigation. Then the map started to display for me. I’m not exactly sure if I can pin down what the exact issue was.

**Comment by onitzschke** [comment]
I'm using react-navigation without problems. Did you checked your app with an layout viewer?
I'm sure its not mapbox related so we should close this issue.

**Comment by systemlevel** [comment]
Yeah go ahead and close. This was a while back so it’s hard to recall what exactly the issue was but it could be related to what you’re discussing right now. I don’t have this issue anymore I have a bigger issue with the map not even displaying correctly due to being outdated. My other issue is the ghostly white map issue I opened up a number of weeks ago. That issue does remain and I haven’t been able to use the library until 7.0 comes out.

**Comment by onitzschke** [comment]
@nitaliano can be closed.

**Comment by vinhtq** [comment]
I have the same issue, not sure why.

I am using it with react-navigation

<img width="559" alt="Screen Shot 2019-03-15 at 11 32 23 AM" src="https://user-images.githubusercontent.com/3962520/54408835-24935a00-4716-11e9-890a-e6c4e14f1c10.png">
