### ISSUE TITLE
Mapbox causing React Navigation header problems

### ISSUE THREAD

**Issue by SoleimanyBBB** [nitaliano/react-native-mapbox-gl#1480]
When using Mapbox and React Navigation together, the header created by React Navigation seems to have faint black lines running horizontally from the top to bottom. 

I just tried running a fresh installation of React Navigation without any problem but once I installed Mapbox the same problem showed up for the header.

[Example of what the issue looks like](https://media.discordapp.net/attachments/288388742929055765/533662853090115594/Screen_Shot_2019-01-12_at_10.02.16_AM.png)

**Comment by kristfal** [comment]
We've use React Navigation in production with RNMGL for months and haven't seen anything like this.

Two questions:

1) Is your map overflowing the header (positioned underneath) or is it positioned flush with the header? 
2) Does this issue reproduce on a device? It could be that the emulator surfaces some kind of rendering artefacts.

**Comment by nitaliano** [comment]
@SoleimanyBBB  thanks for reporting. I've also never seen this happen before and we've released plenty of apps with React Navigation, closing this out until we have steps to reproduce the issue.

**Comment by numandev1** [comment]
but i am also facing this type of problem

**Comment by numandev1** [comment]
I am using react-native-router-flux. after loading map, every screen that I push from map screen have header problem with iPhone x curve
