### ISSUE TITLE
Street names labels overlap ShapeSource

### ISSUE THREAD

**Issue by Revocsid** [nitaliano/react-native-mapbox-gl#1483]
I'm using this library for an app and I have a problem. I would like to display street names below shapeSource. 
As you can see on this screenshot, actually is not the case. 

![screenshot](https://user-images.githubusercontent.com/6648115/51601292-40436680-1f04-11e9-850f-7372e3f9015a.png)

How can I achieve that? Is it even possible with that library?

**Comment by onitzschke** [comment]
Use `belowLayerID` or `aboveLayerID` as in the docs describes.

Check your style.json for map, for example:

`belowLayerID={'road_major_label'}
`

@nitaliano i think it's answered. Can be closed.

**Comment by Revocsid** [comment]
In my Mapbox Studio I can see that road ids are "road-label-large" but when I add the prop belowLayerID={"road-label-large"} or belowLayerID={"road-label-large"} in my MapboxGL.FillLayer it doesn't work. Street names are still above my FillLayer.
