### ISSUE TITLE
Vector sources not included in offline pack

### ISSUE THREAD

**Issue by carsonaaberle** [nitaliano/react-native-mapbox-gl#1487]
I have a custom vector source that pulls the TileJSON from our server. I tried to create an offline pack with:

```
await MapboxGL.offlineManager.createPack({
            name: 'offlinePack',
            styleURL: this.props.mapSettings.style,
            minZoom: 0,
            maxZoom: 18,
            bounds: [[-107.058700, 40.004562], [-106.958700, 39.904562]]
        }, progressListener, errorListener)

```
The above appears to only be downloading the map style, and not the vector sources. Is it possible to download the vector sources in the pack?

**Comment by kristfal** [comment]
You need to use a style.json instead of a tileJson for custom offline maps.

**Comment by carsonaaberle** [comment]
Just to be clear, that mean that it is not possible to download third party VectorSources for offline use?

**Comment by kristfal** [comment]
No, you can (we do).  But you will need to declare the styleURL to a mapbox style json. 

See https://docs.mapbox.com/mapbox-gl-js/style-spec/ for more info about this. 

The reason for this is that the lib has to know which other assets to download, such as fonts and sprites. Think of a style json as an extension of a tile json.
