### ISSUE TITLE
Can't render View inside <Mapbox.MapView>

### ISSUE THREAD

**Issue by mahdidavoodi7** [nitaliano/react-native-mapbox-gl#1488]
Hi
This is my code and as you can see i put some element in Mapbox.MapView: 
```javascript
<Mapbox.MapView
   styleURL={Mapbox.StyleURL.Street}
   zoomLevel={10}
   centerCoordinate={[51.4013785 ,35.7006177]}
   style={{flex: 1,rowDirection: 'column' ,justifyContent:'space-between'}}
   showUserLocation={true}
>
   {this.renderAnnotations()}
    <View style={{flex: 1, justifyContent:"space-between"}} pointerEvents='box-none'>
         <View>
              <Header>neighbor</Header>
              <SearchBar/>
         </View>
         <TouchableHighlight>
              <View style={{flexDirection: 'row', alignSelf: 'center', marginBottom: 20, backgroundColor:'#ffffff', padding:10, borderRadius:5}}>
                <MaterialCommunityIcons name='barcode-scan' size={25} style={{alignSelf:"center", marginRight: 10}}/>
                <Text style={{alignSelf:"center", fontFamily: 'B Yekan'}}>barcode scanner</Text>
              </View>
         </TouchableHighlight>
     </View>
</Mapbox.MapView>
```
Then i got this error on android : 

` com.facebook.react.views.image.ReactImageView cannot be cast to android.view.ViewGroup`

Any help regarding this would be helpful

**Comment by kristfal** [comment]
You can’t render regular views within the MapView. If you want anything positioned on top of the view, you’ll need to move it outside the MapView and use position absolute.

**Comment by bojanjukic** [comment]
Do you have an idea how to render a logo + background but keep the map still scrollable bellow and next to the logo. The View has to be outside of the MapView to work on Android like you mentioned. On iOS the desired functionality is working perfectly as soon as I add the View inside of the MapView component.

**Comment by nhammad** [comment]
> You can’t render regular views within the MapView. If you want anything positioned on top of the view, you’ll need to move it outside the MapView and use position absolute.

Really? Is this still applied? I was doing something like this :
```
  return (
    <MapboxGL.MapView
      style={styles.map}
      logoEnabled={false}
      localizeLabels={true}>
      <MapboxGL.Camera
        zoomLevel={15}
        animationMode={'flyTo'}
        animationDuration={2000}
        centerCoordinate={coordinates}
      />
      {/* <View>
      <AddressTextBox placeName={placeName} />
      </View> */}
      {/* <MapboxGL.PointAnnotation
        id={favouritePlaceId.toString()}
        title={customisedName}
        coordinate={coordinates}>
          <View>
        <MapboxGL.Callout title={customisedName} />
        </View>
      </MapboxGL.PointAnnotation> */}
      <View>
        <MapboxGL.MarkerView
          id={favouritePlaceId.toString()}
          coordinate={coordinates}>
          <View>
            <AnnotationContent title={customisedName} />
          </View>
        </MapboxGL.MarkerView>
      </View>
    </MapboxGL.MapView>
  );
};
```
and the AddressTextBox which is a view, worked fine in iOS but not on Android. How come it was working in iOS?

**Comment by johnneuland** [comment]
> You can’t render regular views within the MapView. If you want anything positioned on top of the view, you’ll need to move it outside the MapView and use position absolute.

Really? Is this still applied? I was doing something like this :
```
  return (
    <MapboxGL.MapView
      style={styles.map}
      logoEnabled={false}
      localizeLabels={true}>
      <MapboxGL.Camera
        zoomLevel={15}
        animationMode={'flyTo'}
        animationDuration={2000}
        centerCoordinate={coordinates}
      />
      {/* <View>
      <AddressTextBox placeName={placeName} />
      </View> */}

      <View>
        <MapboxGL.MarkerView
          id={favouritePlaceId.toString()}
          coordinate={coordinates}>
          <View>
            <AnnotationContent title={customisedName} />
          </View>
        </MapboxGL.MarkerView>
      </View>
    </MapboxGL.MapView>
  );
};
```
and the AddressTextBox which is a view, worked fine in iOS but not on Android. How come it was working in iOS?

Is there no other way to render a view inside the map? (let's say on top of the screen but not outside the map)

**Comment by shawnlauzon** [comment]
> and the AddressTextBox which is a view, worked fine in iOS but not on Android. How come it was working in iOS?

I had the same thing, worked on iOS not on Android. Frustrating.

**Comment by Mohammad-R-Rashid** [comment]
did you manage to fix it @shawnlauzon

**Comment by shawnlauzon** [comment]
> did you manage to fix it @shawnlauzon 

Unfortunately I don't remember
