### ISSUE TITLE
Vector map stops showing after 16 level of zoom with ESRI V2

### ISSUE THREAD

**Issue by eacbkk** [nitaliano/react-native-mapbox-gl#1489]
The issue happens with Esri maps V2 on both iOS and Android. Map shows properly till zoom level 15. But from 16 it starts disappering problem. Tested in multiple version of iOS and Android. Both in simulator and devices. 

Style url contains following: 

```
style: {
    "version": 8,
    "sources": {
      "esri": {
        "type": "vector",
        "tiles": [ "https://basemaps.arcgis.com/arcgis/rest/services/World_Basemap_v2/VectorTileServer/tile/{z}/{y}/{x}.pbf" ]
      }
    },
    "layers": [
    ...
    ]
  }

```

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/30823806/51819211-2d65d300-2304-11e9-95c2-b0f95ab3682a.gif)

Please note, it works fine with the mapbox javascript library.

**Comment by kristfal** [comment]
You likely need to declare a maxZoom of 15 on the source, ex:

```
"sources": {
    "composite": {
      "type": "vector",
      "tiles": [
        "https://foo.com"
      ],
      "minzoom": 0,
      "maxzoom": 15
    }
  },
```
