### ISSUE TITLE
show map not work in android

### ISSUE THREAD

**Issue by javadmohammadis** [nitaliano/react-native-mapbox-gl#1490]
i'm use this code , but my map not displaying!!

```
import Mapbox from '@mapbox/react-native-mapbox-gl';
Mapbox.setAccessToken('<my token >');
export class googleMap extends Component<{}>{ 
    render() {
        return (
        <View style={{flex:1}}>
        <Mapbox.MapView
        logoEnabled={false}
        styleURL={Mapbox.StyleURL.Street}
        zoomLevel={15}
        centerCoordinate={[11.256, 43.770]}
        style={styles.container}>
        </Mapbox.MapView>
        </View>
        );
        }
    } ;
const styles = StyleSheet.create({
   
    container: {
        flex: 1,
      },

})
export default googleMap;
```
![screenshot_1548852827](https://user-images.githubusercontent.com/17460694/51982808-40b3a280-24ac-11e9-977b-ab01c116336c.png)

**Comment by systemlevel** [comment]
Mine crashes when I call:  Mapbox.setAccessToken()  ...  Application just stops and closes in the Android simulator.

**Comment by systemlevel** [comment]
@javadmohammadis Mine ended up being a problem with the Android Studio emulators.  I switched to another emulator (genymotion) and now the maps appear.

**Comment by javadmohammadis** [comment]
thanks. I run the app on an Android device, is ok

**Comment by onitzschke** [comment]
@nitaliano issue can be closed, it's an known problem with android emulators.

**Comment by kristfal** [comment]
This is fixed in master.
