### ISSUE TITLE
[Feature Request] Using Mapbox Map Matching API

### ISSUE THREAD

**Issue by cedricdelpoux** [nitaliano/react-native-mapbox-gl#1493]
Hello, I can't find a way to use the [Mapbox Map Matching API](https://docs.mapbox.com/help/glossary/mapbox-map-matching-api/) to match GeoJSON geometries to the OpenStreetMap streets network. 

Maybe I just missing something.

There is [mapbox-match.js](https://github.com/mapbox/mapbox-match.js/tree/master), a javascript plugin to do that.

**Comment by nitaliano** [comment]
@xuopled use https://github.com/mapbox/mapbox-sdk-js/blob/master/docs/services.md#mapmatching and supply the geojson to a `ShapeSource` and use a `LineLayer` to render it
