### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_helpers.default.point')

### ISSUE THREAD

**Issue by cedricdelpoux** [nitaliano/react-native-mapbox-gl#1494]
Hello, I have an error when I try to center the map but the same error happen for everything

**Without `centerCoordinate` prop:**
```
<MapboxGL.MapView
        ref={c => (this._map = c)}
        zoomLevel={15}
        styleURL={MapboxGL.StyleURL.Street}
      />
```
<img width="398" alt="screenshot 2019-01-31 at 14 03 21" src="https://user-images.githubusercontent.com/2683300/52055917-0bb55780-2561-11e9-98a4-e20dc5087e42.png">

**With `centerCoordinate` prop:**
```
<MapboxGL.MapView
        ref={c => (this._map = c)}
        centerCoordinate={[1.43738, 43.63331]}
        zoomLevel={15}
        styleURL={MapboxGL.StyleURL.Street}
      />
```
<img width="400" alt="screenshot 2019-01-31 at 14 02 39" src="https://user-images.githubusercontent.com/2683300/52055921-0f48de80-2561-11e9-9e77-26b1d2c6957d.png">

**build.gradle:**
```
    implementation project(':mapbox-react-native-mapbox-gl') {
        implementation ('com.squareup.okhttp3:okhttp:3.6.0') {
            force = true
        }
    }
```

**settings.gradle:**
```
include ':mapbox-react-native-mapbox-gl'
project(':mapbox-react-native-mapbox-gl').projectDir = new File(rootProject.projectDir, '../node_modules/@mapbox/react-native-mapbox-gl/android/rctmgl')
```

**Comment by nitaliano** [comment]
that error is telling you that it can't find `@turf/helpers` are you sure it's installed?

**Comment by cedricdelpoux** [comment]
Is it mandatory per default ? I did not see it in the doc

**Comment by kristfal** [comment]
Likely your NPM/Yarn install failed. This lib depends on turf as a dependency, make sure it is in node_modules under /node_modules/@mapbox/react-native-mapbox-gl
