### ISSUE TITLE
linker command failed with exit code 1

### ISSUE THREAD

**Issue by klase** [nitaliano/react-native-mapbox-gl#1495]
I followed the instructions for intalling on iOS using CocoaPods, and it builds and runs fine on the simulator. However, when building to my device (iPhone SE, iOS 12.1.2) I get the following error:

<img width="616" alt="xcode rror" src="https://user-images.githubusercontent.com/1711650/52067431-7d49d180-2572-11e9-8739-c63abd5569b4.png">

@mapbox/react-native-mapbox-gl 6.1.3
react-native 0.57.8
Xcode Version 10.1 (10B61)

**Comment by ferdicus** [comment]
@klase, did you try the [Manual installation steps](https://github.com/agius/react-native-mapbox-gl/blob/master/ios/install.md#manual-installation)?
