### ISSUE TITLE
Custom map can be displayed, but the custom layer doesn't appear

### ISSUE THREAD

**Issue by winseyli** [nitaliano/react-native-mapbox-gl#1501]
I have a custom map which adds a custom text symbol layer for house number. This layer can be displayed on web/Android/iOS but it disappears on React Native (i.e. the map looks as same as `Mapbox.StyleURL.Street`, but not blank)

On the custom map style, I downgrade the compatibility for React Native.
<img width="818" alt="screenshot 2019-02-05 at 2 01 52 pm" src="https://user-images.githubusercontent.com/7858565/52247545-2f0c4800-294f-11e9-93e1-1b20807663ad.png">

This is the react native coding.

```
<MapboxGL.MapView
  style={{flex: 1}}
  styleURL={this.state.isSatelliteOn ? MapboxGL.StyleURL.Satellite : "mapbox://styles/username/123456abcdef123456abcdefm"}
  zoomLevel={this.state.zoomLevel}
  centerCoordinate={[this.state.lng, this.state.lat]} // Initial center coordinate on map [lng, lat]
  showUserLocation={true}>
</MapboxGL.MapView>
```

Did I miss anything?

P.S. `housenumber` is my custom layer
<img width="586" alt="screenshot 2019-02-05 at 2 02 03 pm" src="https://user-images.githubusercontent.com/7858565/52247550-303d7500-294f-11e9-9488-6771f82b055b.png">

**Comment by winseyli** [comment]
Not sure if it needs to take a while to process the map? I can see the layer after 2 hours. Thanks you. Case closed. But I think this would be a good reference for someone need to use custom style (yes you need to downgrade the compatibility)
P.S. current react-native-mapbox-gl latest release is 6.1.1

**Comment by udaysagartammina** [comment]
<MapboxGL.MapView
  style={{flex: 1}}
  styleURL={"mapbox://styles/username/cfnkn3ql227ss17o1pw2dj5vf"}
  zoomLevel={16}
  centerCoordinate={[this.state.lng, this.state.lat]}
  showUserLocation={true}>
</MapboxGL.MapView>

My custom url not loading 
    "react-native": "0.61.5",
    "@react-native-mapbox-gl/maps": "^8.1.0",

Any one can help me.
