### ISSUE TITLE
How is it possible to use dynamic-styles

### ISSUE THREAD

**Issue by soleimani21** [nitaliano/react-native-mapbox-gl#1503]
How is it possible to use dynamic-styles to set individual fill colors for each polygon within the same layer or FeatureCollection? Currently, I'm passing one FeatureCollection object to MapboxGL.ShapeSource, and I do not know how to access the "loop" and set individual style from a feature property. How can I do this?

**Comment by nitaliano** [comment]
Check this example out https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/DataDrivenCircleColors.js
