### ISSUE TITLE
Unable to resolve dependencies

### ISSUE THREAD

**Issue by kurisubrooks** [nitaliano/react-native-mapbox-gl#1513]
Hi, i'm trying to get mapbox-gl working under my react-native app (android) and it seems to be unable to build/download/resolve dependencies from this module.

I've followed all the standard install instructions in the main README, _and_ the [Android build instructions](https://github.com/mapbox/react-native-mapbox-gl/blob/master/android/install.md) carefully but I still can't get it to resolve the dependencies. I've listed the error below.

```
ERROR: Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:3.9.1.
Show Details
Affected Modules: mapbox-react-native-mapbox-gl


ERROR: Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.squareup.okio:okio:1.13.0.
Show Details
Affected Modules: mapbox-react-native-mapbox-gl


ERROR: Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.android.support:appcompat-v7:27.0.2.
Show Details
Affected Modules: mapbox-react-native-mapbox-gl

...
```

**Comment by tankers746** [comment]
See: https://github.com/mapbox/react-native-mapbox-gl/issues/1511

For now this can be fixed by reverting the gradle plugin version by editing: 
**android/build.gradle**
replacing: `classpath 'com.android.tools.build:gradle:3.3.1'`
with: `classpath 'com.android.tools.build:gradle:3.2.1'`

**Comment by kurisubrooks** [comment]
Thanks for your response.
Since it's a duplicate of #1511, i'll close this issue.

**Comment by joshuapinter** [comment]
As of [March 18th, 2019 (yesterday)](https://github.com/nitaliano/react-native-mapbox-gl/issues/1511#issuecomment-473885457), this is now fixed in `master`.

**Comment by ManishSharmaApporio** [comment]
Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:3.9.1.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.squareup.okio:okio:1.13.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.android.support:appcompat-v7:27.0.2.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.android.support:support-annotations:27.0.2.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.android.support:support-core-utils:27.0.2.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.android.support:support-compat:27.0.2.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve android.arch.lifecycle:runtime:1.0.3.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve android.arch.lifecycle:common:1.0.3.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve android.arch.core:common:1.0.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.android.support:support-fragment:27.0.2.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.android.support:support-core-ui:27.0.2.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.android.support:support-vector-drawable:27.0.2.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.android.support:animated-vector-drawable:27.0.2.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.android.support:appcompat-v7:25.4.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.android.support:support-compat:25.4.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.android.support:support-annotations:25.4.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.android.support:support-fragment:25.4.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:3.9.1.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.android.support:appcompat-v7:27.0.2.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.android.support:appcompat-v7:28.0.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:3.12.1.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.squareup.okio:okio:1.15.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:3.6.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.android.support:support-annotations:25.3.1.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.android.support:appcompat-v7:25.3.1.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.android.support:support-annotations:28.0.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.android.support:support-compat:28.0.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.android.support:support-core-utils:28.0.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.android.support:support-fragment:28.0.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.android.support:support-vector-drawable:28.0.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.android.support:animated-vector-drawable:28.0.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:3.10.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve android.arch.lifecycle:runtime:1.1.1.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.android.support:support-core-ui:28.0.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve android.arch.lifecycle:common:1.1.1.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve android.arch.core:common:1.1.1.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@debug/compileClasspath': Could not resolve com.android.support:support-annotations:26.1.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:3.9.1.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.squareup.okio:okio:1.13.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.android.support:appcompat-v7:27.0.2.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.android.support:support-annotations:27.0.2.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.android.support:support-core-utils:27.0.2.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.android.support:support-compat:27.0.2.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve android.arch.lifecycle:runtime:1.0.3.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve android.arch.lifecycle:common:1.0.3.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve android.arch.core:common:1.0.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.android.support:support-fragment:27.0.2.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.android.support:support-core-ui:27.0.2.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.android.support:support-vector-drawable:27.0.2.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.android.support:animated-vector-drawable:27.0.2.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.android.support:appcompat-v7:25.4.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.android.support:support-compat:25.4.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.android.support:support-annotations:25.4.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.android.support:support-fragment:25.4.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:3.9.1.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.android.support:appcompat-v7:27.0.2.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.android.support:appcompat-v7:28.0.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:3.12.1.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.squareup.okio:okio:1.15.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:3.6.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.android.support:support-annotations:25.3.1.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.android.support:appcompat-v7:25.3.1.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.android.support:support-annotations:28.0.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.android.support:support-compat:28.0.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.android.support:support-core-utils:28.0.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.android.support:support-fragment:28.0.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.android.support:support-vector-drawable:28.0.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.android.support:animated-vector-drawable:28.0.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:3.10.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve android.arch.lifecycle:runtime:1.1.1.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.android.support:support-core-ui:28.0.0.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve android.arch.lifecycle:common:1.1.1.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve android.arch.core:common:1.1.1.
Open File
Show Details


Unable to resolve dependency for ':mapbox-react-native-mapbox-gl@release/compileClasspath': Could not resolve com.android.support:support-annotations:26.1.0.
Open File









dependency does  not reslove.
