### ISSUE TITLE
Issue with react-native@0.55.4

### ISSUE THREAD

**Issue by jutaz** [nitaliano/react-native-mapbox-gl#1515]
Trying to run with latest (`6.1.3`) `react-native-mapbox-gl`, and RN @ 0.55, and I seem to be getting this error:
<img width="864" alt="screen shot 2019-02-21 at 14 14 06" src="https://user-images.githubusercontent.com/1277553/53168283-f755ff00-35e2-11e9-9345-9c1cf6ced5d2.png">

Not sure how to proceed from here - is this SDK not compatible with certain React native versions?

**Comment by goodryanboy** [comment]
Did you do the manual linking?
[https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/install.md](url)

**Comment by kristfal** [comment]
This is likely a install issue. We’ve run on 55.X without issues. I recommend you repeat the install instructions.
