### ISSUE TITLE
The app works well with MapboxGL.StyleURL.Street but crashes with custom map, just for some specific area in NZ

### ISSUE THREAD

**Issue by winseyli** [nitaliano/react-native-mapbox-gl#1517]
My react native app was successfully integrated with custom map (refer to #1501 ) but when we test the apps we found that it crashes when we navigate to some address/area.

e.g. Lyall Bay, Wellington, New Zealand
It works when we use MapboxGL.StyleURL.Street but if it points to custom map it crashes without any error.
<img width="300" src="https://user-images.githubusercontent.com/7858565/53398380-57e3a280-3a0e-11e9-9627-1dd8a7f6cb6f.png">

**Comment by kristfal** [comment]
This may be caused by multiple issues: Broken style, sprites, fonts or underlying vector data. From your description, it’s not possibly to figure out why. 

I recommend you try to run the same style in mapbox-gl-js to see if you get any errors at the same location.

**Comment by winseyli** [comment]
Thanks for reply. We have similar issue on native SDK and finally we found that our tilesets have max zoom of 18 and they are using a zoom-based style expression on the street number. After removing the expression it has no crash. Thank you.
