### ISSUE TITLE
 "RCTMGLAndroidTextureMapView" was not found in the UIManager.

### ISSUE THREAD

**Issue by goodryanboy** [nitaliano/react-native-mapbox-gl#1518]
Hello guys can someone help me with this issue. In debug i have no problem in opening the map but in release I got this error

> Invariant Violation: Invariant Violation: Invariant Violation: requireNativeComponent: "RCTMGLAndroidTextureMapView" was not found in the UIManager.
E/unknown:ReactNative(14406): 
E/unknown:ReactNative(14406): This error is located at:
E/unknown:ReactNative(14406):     in RCTMGLAndroidTextureMapView
E/unknown:ReactNative(14406):     in RCTView
E/unknown:ReactNative(14406):     in b
E/unknown:ReactNative(14406):     in RCTView
E/unknown:ReactNative(14406):     in n
E/unknown:ReactNative(14406):     in inject-n-with-biz
E/unknown:ReactNative(14406):     in v
E/unknown:ReactNative(14406):     in RCTView
E/unknown:ReactNative(14406):     in RCTView
E/unknown:ReactNative(14406):     in RCTView
E/unknown:ReactNative(14406):     in f
E/unknown:ReactNative(14406):     in RCTView
E/unknown:ReactNative(14406):     in f
E/unknown:ReactNative(14406):     in C
E/unknown:ReactNative(14406):     in n
E/unknown:ReactNative(14406):     in P
E/unknown:ReactNative(14406):     in RCTView
E/unknown:ReactNative(14406):     in n
E/unknown:ReactNative(14406):     in RCTView
E/unknown:ReactNative(14406):     in f
E/unknown:ReactNative(14406):     in b
E/unknown:ReactNative(14406):     in y
E/unknown:ReactNative(14406):     in L
E/unknown:ReactNative(14406):     in RCTView
E/unknown:ReactNative(14406):     in h
E/unknown:ReactNative(14406):     in C
E/unknown:ReactNative(14406):     in k
E/unknown:ReactNative(14406):     in v
E/unknown:ReactNative(14406):     in v
E/unknown:ReactNative(14406):     in RCTView
E/unknown:ReactNative(14406):     in RCTView
E/unknown:ReactNative(14406):     in l
E/unknown:ReactNative(14406):     in RCTView
E/unknown:ReactNative(14406):     in n
E/unknown:ReactNative(14406):     in RCTView
E/unknown:ReactNative(14406):     in n
E/unknown:ReactNative(14406):     in _
E/unknown:ReactNative(14406):     in k
E/unknown:ReactNative(14406):     in k
E/unknown:ReactNative(14406):     in f
E/unknown:ReactNative(14406):     in v
E/unknown:ReactNative(14406):     in l
E/unknown:ReactNative(14406):     in k
E/unknown:ReactNative(14406):     in k
E/unknown:ReactNative(14406):     in n
E/unknown:ReactNative(14406):     in RCTView
E/unknown:ReactNative(14406):     in n
E/unknown:ReactNative(14406):     in RCTView
E/unknown:ReactNative(14406):     in RCTView
E/unknown:ReactNative(14406):     in c
E/unknown:ReactNative(14406): 
E/unknown:ReactNative(14406): This error is located at:
E/unknown:ReactNative(14406):     in k
E/unknown:ReactNative(14406):     in f
E/unknown:ReactNative(14406):     in v
E/unknown:ReactNative(14406):     in l
E/unknown:ReactNative(14406):     in k
E/unknown:ReactNative(14406):     in k
E/unknown:ReactNative(14406):     in n
E/unknown:ReactNative(14406):     in RCTView
E/unknown:ReactNative(14406):     in n
E/unknown:ReactNative(14406):     in RCTView
E/unknown:ReactNative(14406):     in RCTView
E/unknown:ReactNative(14406):     in c
E/unknown:ReactNative(14406): 
E/unknown:ReactNative(14406): This error is located at:
E/unknown:ReactNative(14406):     in k
E/unknown:ReactNative(14406):     in n
E/unknown:ReactNative(14406):     in RCTView
E/unknown:ReactNative(14406):     in n
E/unknown:ReactNative(14406):     in RCTView
E/unknown:ReactNative(14406):     in RCTView
E/unknown:ReactNative(14406):     in c, stack:
E/unknown:ReactNative(14406): exports@172:1070
E/unknown:ReactNative(14406): <unknown>@170:118
E/unknown:ReactNative(14406): get@164:712
E/unknown:ReactNative(14406): qr@88:59535
E/unknown:ReactNative(14406): Jr@88:61732
E/unknown:ReactNative(14406): Kr@88:62132
E/unknown:ReactNative(14406): zi@88:69082
E/unknown:ReactNative(14406): Ii@88:68425
E/unknown:ReactNative(14406): Ae@88:75098
E/unknown:ReactNative(14406): ze@88:13671
E/unknown:ReactNative(14406): Oe@88:13844
E/unknown:ReactNative(14406): receiveEvent@88:14220
E/unknown:ReactNative(14406): value@25:3449
E/unknown:ReactNative(14406): <unknown>@25:960
E/unknown:ReactNative(14406): value@25:2703
E/unknown:ReactNative(14406): value@25:932

this is the version I use

>  "@mapbox/geo-viewport": "^0.4.0",
    "@mapbox/react-native-mapbox-gl": "^6.1.3",
    "mapbox": "^1.0.0-beta10",
    "react": "16.6.3",
    "react-native": "0.58.4",

**Comment by kylesziv** [comment]
@kristfal Here is another example of https://github.com/mapbox/react-native-mapbox-gl/issues/1514 -- is this just an incompatibility with react-native 0.58.4?

**Comment by kristfal** [comment]
I’ll have to investigate. Closing in favor of #1514

**Comment by goodryanboy** [comment]
I got it working,,, thanks, I just remove codes in the proguards

**Comment by doodlemoonch** [comment]
@goodryanboy could you share your proguard rules?
