### ISSUE TITLE
Some items on SymbolLayer disappear if overlapped

### ISSUE THREAD

**Issue by winseyli** [nitaliano/react-native-mapbox-gl#1521]
We use the `ShapeSource` with `SymbolLayer` to display the map markers. For `MapboxGL.StyleSheet` style applied on this markers, `iconAllowOverlap: true` and `iconIgnorePlacement: true` are set. Is there any other settings are required to prevent the markers from disappearing? Thank you.

![53702643-06a03c80-3e6e-11e9-9485-2e6a5a0f12e5](https://user-images.githubusercontent.com/7858565/53721625-91158a00-3ec8-11e9-8676-5c9ae8d6fa62.png)![53702644-0738d300-3e6e-11e9-8913-e53c4b528ebf](https://user-images.githubusercontent.com/7858565/53721628-9246b700-3ec8-11e9-9b3b-1fd2c98f01cd.png)

**Comment by onitzschke** [comment]
Is it zoom dependent? I have the same issue with SymbolLayer. There is a option for point shape to disable the clustering.

**Comment by onitzschke** [comment]
Duplicate https://github.com/mapbox/react-native-mapbox-gl/issues/1356

**Comment by kristfal** [comment]
Ok, closing in favor of #1356

**Comment by winseyli** [comment]
Yes it is happening when zoom out. So the solution is `cluster={false}` on `MapboxGL.ShapeSource` but it doesn't work as mentioned in #1356 ?

**Comment by winseyli** [comment]
Hi there. I think the issue is not exactly the same as #1356 because if I remove the `textField` value on the `SymbolLayer`'s `style`, the map markers will not disappear.

**Comment by winseyli** [comment]
Hey I found the problem is solved when I add `textAllowOverlap: true` as style of the `SymbolLayer`.
For anyone reading this and having the same problem please make sure
```
    iconAllowOverlap: true,
    textAllowOverlap: true,
    iconIgnorePlacement: true,
    textIgnorePlacement: true,
```
are added!

**Comment by LucasYver** [comment]
THANKS THANKS THANKS !!!
