### ISSUE TITLE
How to use and setup react-native-mapbox-gl for users in china ?

### ISSUE THREAD

**Issue by kiki-le-singe** [nitaliano/react-native-mapbox-gl#1525]
Hello guys!

Is it possible to set up react-native-mapbox-gl to use it for users in china ?

I don't find any documentation about that in this repository.

Thanks for your help

**Comment by kristfal** [comment]
Hey!

This repo does not contain the China-specific extras available via the regular native SDKs. This repo is not officially maintained either, so your best bet is to create a PR with the required changes.
