### ISSUE TITLE
Update npm package to remove namespace

### ISSUE THREAD

**Issue by nitaliano** [nitaliano/react-native-mapbox-gl#1529]
Now that this repo has moved out of the Mapbox org, we will update the npm package to go back to `react-native-mapbox-gl` instead of `@mapbox/react-native-mapbox-gl`

**Comment by ansarikhurshid786** [comment]
do we need to update with new name ?

**Comment by nitaliano** [comment]
Not yet, once I publish the package yes. I'll update this ticket and the README once I deploy it

**Comment by ansarikhurshid786** [comment]
@nickells can you give me answer for question https://github.com/nitaliano/react-native-mapbox-gl/issues/1528. I am waiting last 2 days.

**Comment by mlg87** [comment]
@nitaliano do you have an estimate on when the next version will be published?

**Comment by kristfal** [comment]
This finished.
