### ISSUE TITLE
symbolPlacement with iconIgnorePlacement

### ISSUE THREAD

**Issue by onitzschke** [nitaliano/react-native-mapbox-gl#1530]
`iconIgnorePlacement` is not working with ` symbolPlacement: 'line',`
 
https://github.com/mapbox/mapbox-gl-native/issues/13969 describes my issue with direction arrow on line.

```
  directionIcon: {
    iconImage: '{icon}', // icon is tinted in AppColor.red
    iconIgnorePlacement: true, // not working with symbolPlacement: 'line'
    iconAllowOverlap: true,
    symbolPlacement: 'line',
    iconSize: Platform.OS === 'ios' ? 0.4 : 0.2
  }
```

**Comment by kristfal** [comment]
This is an upstream issue and will be fixed when 7.0.0 lands. Closing for now.
