### ISSUE TITLE
Mapbox watermark

### ISSUE THREAD

**Issue by Hermanyo** [nitaliano/react-native-mapbox-gl#1532]
Hi, there. May I reference `©Mapbox` as a link to `https://www.mapbox.com/about/maps/`, `©OpenStreetMap` as a link to` http://www.openstreetmap.org/copyright`, and `Improve this map `as a link to `https://www.mapbox.com/map-feedback/` on "about" page? Or attributions only must be on the map?

for example, 
![b42be227-1cfa-4601-9159-97cb323fedb0](https://user-images.githubusercontent.com/43192176/54056787-e48d1e00-41cf-11e9-9115-4f79389c856f.jpg)

**Comment by onitzschke** [comment]
@Hermanyo i think this is helpful:
https://docs.mapbox.com/help/how-mapbox-works/attribution/

**Comment by Hermanyo** [comment]
Thanks! I have a question, how do I move watermark? What is the property to do this? I didn't found how to do this

**Comment by onitzschke** [comment]
I've found only this: https://github.com/nitaliano/react-native-mapbox-gl/issues/96 but feel free to contribute.

**Comment by Hermanyo** [comment]
@onitzschke thanks a lot.
