### ISSUE TITLE
Raster layer not rendering in android

### ISSUE THREAD

**Issue by ansarikhurshid786** [nitaliano/react-native-mapbox-gl#1534]
I have added one rastersource and rasterlayer. It is working in ios emulator and device but not working in android device or emulator. 

can anyone help me? 

sample code : 

 ```
<MapboxGL.RasterSource
   id="idCities"
   url="url/export?layers=show:197,198,220&bbox={bbox-epsg-3857}&bboxSR=3857&imageSR=3857&size=256,256&transparent=true&format=png&f=image">
      <MapboxGL.RasterLayer
         id="idCities"
         source="idCities"
         style={{ visibility: "visible" }}>
      </MapboxGL.RasterLayer>
   </MapboxGL.RasterSource>
```

**Comment by onitzschke** [comment]
Did you already tried to restart the app completely?

**Comment by kristfal** [comment]
Without any code samples or other ways to reproduce, we can’t help. Please reopen with a link to an example repo.

**Comment by ansarikhurshid786** [comment]
@kristfal can you check question again ?

**Comment by ansarikhurshid786** [comment]
I have tested in ios simulator and real device, working great but not working neither in simulator nor in real device.
