### ISSUE TITLE
App crashing after starting from a  real android device

### ISSUE THREAD

**Issue by jonathangaldino** [nitaliano/react-native-mapbox-gl#1537]
First, some info:

Android  8.0.0 OPR1.....
Xiaomi Mi 6 - MiUI Global 10.2
6gb ram, etc

After running the installation example, I tried to upload the app to my real device, so I can debug first hand. 

I got some issues, like in this picture:

![Error image](https://user-images.githubusercontent.com/13936071/54330039-f9fcb080-45f2-11e9-9c7d-b3ee1a89f8be.jpeg)

I'm using React-native 0.58.6.
You can check my repo [here](https://github.com/JohnzBallad/react-native-devmapper/tree/dev/android)

**Comment by kristfal** [comment]
See https://github.com/nitaliano/react-native-mapbox-gl/issues/1139
