### ISSUE TITLE
question: exclude gravel from navigation

### ISSUE THREAD

**Issue by Benetzz** [nitaliano/react-native-mapbox-gl#1539]
Hi all, just one question: is it possible to get navigation info, excluding some kind of terrain?
Like exclude the gravel streets?
Thanks

**Comment by kristfal** [comment]
Hey! I’m not sure if you refer to rendering in the map or the mapbox directions API, but both should be doable. 

I’d recommend stackoverflow or mapbox documentation for questions like this.
