### ISSUE TITLE
Version 6.1.3 is missing from Github's Releases.

### ISSUE THREAD

**Issue by joshuapinter** [nitaliano/react-native-mapbox-gl#1549]
![Screenshot 2019-03-19 10 30 08](https://user-images.githubusercontent.com/180819/54623920-1012d280-4a32-11e9-88da-c2b1692a3a15.png)

**Comment by kristfal** [comment]
Hey, yes, aware of this. Ideally we’d get master out as 6.1.4 on NPM and keep github in sync from this version. I’m not able to do this, only the owner of the repo @nitaliano  is able to publish. 

Keeping this open until 6.1.4 is up on NPM.

**Comment by nickitaliano** [comment]
Hey Kris- unfortunately, I am not the owner of that particular repo. Sorry guys =-/

**Comment by kristfal** [comment]
Typo there. Sorry Nick :)

**Comment by joshuapinter** [comment]
Thanks for the response, @kristfal! I know it's tough to keep these aligned and updated. :)

**Comment by nitaliano** [comment]
@kristfal now that we're switching back to the non mapbox scoped npm package I will add you and all of the maintainers so I don't become a bottleneck.

**Comment by Oscarz90** [comment]
guys, I'm having the same problem but with 6.1.4 version, What should I do?

**Comment by ferdicus** [comment]
There is probably not going to be any more releases on this rep.
You can get `6.1.4` when installing from #master (install steps are detailed on the README).

For future releases please head over to [react-native-mapbox/maps](https://github.com/react-native-mapbox/maps)


@kristfal, I think this can be closed
