### ISSUE TITLE
Expo Support?

### ISSUE THREAD

**Issue by jmandel1027** [nitaliano/react-native-mapbox-gl#1550]
Hi there,

I've been following this project for a bit now and was curious to see if there are any workarounds to support using this package with Expo, i have a project that would greatly benefit form this though unwilling to de-couple from expo as it's supporting a build and deploy pipeline for a cross platform project.

What are the main blockers / Is there anything i can help with / contribute to make this happen?

Thanks for all the hard work!

**Comment by kristfal** [comment]
There is currently no way to get support with expo without ejecting. The only way to get support is to have the expo team include this project in their core.

The expo team has a voting board for new features. I’d say the only actionable thing you can do is go vote there, and if possible, join in maintaining/making the project overall better. 

You’ll find a link to this voting board in the readme of this repo.
