### ISSUE TITLE
Offline map not being used by MapView

### ISSUE THREAD

**Issue by atomheartother** [nitaliano/react-native-mapbox-gl#1553]
Hello,

I'm hoping that this is due to me mis-using the OfflineManager, I'm using it pretty simply and it doesn't seem to work. This bug is on Android and iOS.

## Behavior
- Without visiting the map page, I download the entire offline pack for the region. The download is successful (Pack state is 2,  percentage is 100, requiredResourceCount is equal to completedResourceCount)
- After I've downloaded the offline pack for the region I turn off my phone's internet and visit the map page. It gives me a black screen.
- The `onDidFailLoadingMap` event isn't fired or anything, the map just seems to be waiting for internet
- If I connect to the internet with my device, the visible region immediately loads
- However even then if I turn internet back off and move around off the region that was loaded online, the rest of the map is blank, even though that region definitely was downloaded in the offline pack.

Is this expected behavior, did I misunderstand what the OfflineManager does? In my head the expected behavior would be:
- Load the offline pack
- Turn off internet
- Open the map
- The map is there

**Comment by kristfal** [comment]
Questions:

Which style are you using for offline download and map view (you'll declare the style twice)? 
Does it have the same behaviour if you view the map before you download the offline bundles?
What happens if you restart the app after downloading the bundle?

**Comment by atomheartother** [comment]
> Which style are you using for offline download and map view

Yeah, no, i'm an absolute idiot. This is what I get for not setting a single const for all my styleURLs... Sorry for the bother, I indeed had 2 different styleURLs.

**Comment by kristfal** [comment]
Done that myself, hence the question ;)

**Comment by trankhacvy** [comment]
@kristfal Do I need to download two packs if I use two modes (street and satellite) ? Do the `createPack` function has an option to download multiple packs in a same time ?

**Comment by kristfal** [comment]
@levi-ackerman, yes, you download a pack by specifying a style along with zoom and bounds. That given style is then downloaded, nothing else. 

In your case, you’d need to download both street and satellite. You can run multiple downloads in parallel, so just start both at the same time for the same zoom and bounds.
