### ISSUE TITLE
type differences on coordinates

### ISSUE THREAD

**Issue by lauherk** [nitaliano/react-native-mapbox-gl#1559]
looking at index.d.ts, i've noticed that for coordinates, it's always of type` Array<number>.` for example,

`interface MapViewProps extends ViewProperties {
    centerCoordinate?: Array<number>;
    ......
}`

however, looking at the type for `PointAnnotationProps,` i see that `coordinate: Array<string>`.  Example: 
`interface PointAnnotationProps {
    coordinate: Array<string>;
  ...
}`

is there a reason for this? It seems to make sense to me for everything to be `Array<number>,` but i wanted to ask here first as this is causing type errors. Thanks a ton in advance for the help! 😄

**Comment by nitaliano** [comment]
It's just a typo for sure it should be `Array<number>`

**Comment by kristfal** [comment]
Should be Array<number>. Feel free to open a PR with a fix.

**Comment by lauherk** [comment]
thanks so much for the feedback! I will open a pr tonight 👍 😄
