### ISSUE TITLE
Fit to the bounds of a LineString

### ISSUE THREAD

**Issue by klase** [nitaliano/react-native-mapbox-gl#1560]
I'm trying to fit bounds to a LineString as in this example: https://docs.mapbox.com/mapbox-gl-js/example/zoomto-linestring/  

How can I create a LngLatBounds instance that has the extend method with this library? I can't find it on the MapboxGL.MapView ref or the default import from @mapbox/react-native-mapbox-gl. There's a geoUtils.makeLatLngBounds but the returned object doesn't have an extend method.

**Comment by kristfal** [comment]
You can use turf.js for getting the bounds of a linestring.
