### ISSUE TITLE
onPress() not works 

### ISSUE THREAD

**Issue by ManishSharmaApporio** [nitaliano/react-native-mapbox-gl#1562]
when i press on the map console  didn't show.Please help me out  how  to solve this 

 <MapboxGL.MapView
          onRegionDidChange={this.onRegionDidChange}
          ref={c => (this._map = c)}
          style={{ flex: 1 }}
          zoomLevel={11}
          onPress={() => console.warn("aeqsa")}
          showUserLocation={true}
          compassEnabled={false}
          styleURL={this.mapStyleURI}
          attributionEnabled={false}
          onUserLocationUpdate={this.onUserLocationUpdate}
          //userTrackingMode={MapboxGL.UserTrackingModes.Follow}
          centerCoordinate={this.state.coordinates[0]}
        >
    
        </MapboxGL.MapView>

**Comment by kristfal** [comment]
I assume this is on Android after a hot reload. This bug is fixed in master, so install from there and all should be well. Closing, please reopen if issue persists after master install and rebuild.

**Comment by ManishSharmaApporio** [comment]
@kristfal  can  you please send link where i access the proper  documentation of that ?i couldn't found .Please help me out

**Comment by ManishSharmaApporio** [comment]
@kristfal   Have you published  the code on NPM after updating the code in master?
