### ISSUE TITLE
onRegionChange : slowing down app

### ISSUE THREAD

**Issue by PCharpentier** [nitaliano/react-native-mapbox-gl#157]
Hi,

I use your mapbox in my app and I have a problem with onRegionChange.
I think that onRegionChange is too much called.

This is my code :

```
  _onRegionChange(event){
      coord=event;
      this.setState((state) => {return {};});
  }
```

With this code, my app already change my global variable coord. And it's impossible to make another thing.

I tried this code :

```
  _onRegionChange(event){
    if(((Math.round(coord.latitude*1000)/1000)!=(Math.round(event.latitude*1000)/1000)) || ((Math.round(coord.longitude*1000)/1000)!=(Math.round(event.longitude*1000)/1000))){
      coord=event;
      this.setState((state) => {return {};});
    }
  }
```

It's better but it's a bad solution I think.
Do you have another solution ?

An other question : how can I find the adress with the coord ? Thanks

**Comment by bsudekum** [comment]
Not seeing any problems with onRegionChange. Re-open if this still persists.
