### ISSUE TITLE
Create polygon from coordinates

### ISSUE THREAD

**Issue by trankhacvy** [nitaliano/react-native-mapbox-gl#1572]
I just wonder how we can create a Polygon from a list of coordinates. I have researched but can't find any solution.

Coordinates look like: 
`const coordinates = [{lng1, lat1}, {lng2, lat2}, {lng3, lat3}, {lng4, lat4}, {lng5, lat5} ] `.

Please help !!

**Comment by kristfal** [comment]
Use stackoverflow for questions like this.
