### ISSUE TITLE
Bug: Android: Does not compile on Android 28

### ISSUE THREAD

**Issue by mvniekerk** [nitaliano/react-native-mapbox-gl#1575]
**Reproduce steps:**
`yarn global add react-native`
`react-native init test`
`cd test/`
`yarn add @mapbox/react-native-mapbox-gl`
`npm link`
`react-native run-android`

**Versions**
Android:
```
{
        buildToolsVersion = "28.0.0"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 26
        supportLibVersion = "28.0.0"
    }

```
`classpath 'com.android.tools.build:gradle:3.3.2'`

**Fix**
Change `node_modules/@mapbox/react-native-mapbox-gl/android/rctmgl/build.gradle`:
https://gist.github.com/mvniekerk/07f1c71abff69f81d1aaee548737fea8

**Comment by kristfal** [comment]
Thanks for reporting. This is fixed in master, just waiting for publish to NPM. We already got an issue for that, so closing.

**Comment by mvniekerk** [comment]
Excellent.
Will wait for the new version.
