### ISSUE TITLE
ShapeSource with custom view as children

### ISSUE THREAD

**Issue by aprados** [nitaliano/react-native-mapbox-gl#1577]
I'm migrating from PointAnnotation to ShapeSource, but I have a 
custom component inside the PointAnnotation that changes based 
on the feature's properties, and if it's selected or not. Is there a way to do this with ShapeSource?

**Comment by kristfal** [comment]
I'm not sure if I understand your question fully. However, I'll try:

1) It is possible to assign custom icons to a shapeSource
2) If you update the shape source (ex: If a feature is selected) you can update the icon
3) Shapesources expect you to handle everything around selection yourself, and you'll need to build your own custom "callout" UI or something similar

Let me know if you have further questions
