### ISSUE TITLE
example

### ISSUE THREAD

**Issue by tongsanghua** [nitaliano/react-native-mapbox-gl#1578]
Unable to resolve module `./index` from `xxx/react-native-mapbox-gl/example/node_modules/react-native/.

**Comment by nitaliano** [comment]
did you npm install? Closing this out since there isn't enough info

**Comment by sharadkatre19** [comment]
Hello @nitaliano 
Yes I have executed `npm install` still getting the same error

> Unable to resolve module ./index from `xxx/react-native-mapbox-gl/example/node_modules/react-native/.

Can you please help me with that?
Thanks.
