### ISSUE TITLE
Help needed: Does this library support canvas source type?

### ISSUE THREAD

**Issue by awdhootlele** [nitaliano/react-native-mapbox-gl#1581]
Hi,
The Mapbox JS library has a source type of canvas and I was wondering if this library has support for canvas type of source.
As per documentation, it has Vector, Shape and Raster source.
But there was one style specification I found [here](https://github.com/nitaliano/react-native-mapbox-gl/blob/master/style-spec/v8.json). This style lists the canvas source in the list of sources.
So id the canvas_source already present in the library but the documentation  is missing or need to add support for the same?
If support needs to be added for IOS and android, can someone point me to exactly how I can do that? Maybe any links about how to contribute to this lib by extending some functionality?

Thanks.

**Comment by nitaliano** [comment]
The gl-native would need to add support for this in the c++ codebase https://github.com/mapbox/mapbox-gl-native
