### ISSUE TITLE
Using surfaceView prop crashes app on Android

### ISSUE THREAD

**Issue by kantorm** [nitaliano/react-native-mapbox-gl#1586]
When I use `MapView` component with `surfaceView` prop set to `true` app crashes on Android.
Steps to reproduce:
- open app with `MapView` using `surfaceView` prop
- open context menu and kill the app
- tap to open the app again
- phone stops responding
- after a while system alert pops up with information that app has stopped responding

Environment
 - os: Android 8/9
 - react-native: 0.59.4

**Comment by kristfal** [comment]
This is during hot reload right? It won’t happen in production right?

**Comment by kantorm** [comment]
@kristfal It does happen on production.
