### ISSUE TITLE
iOS RN0.59 app crashes when rendering lines

### ISSUE THREAD

**Issue by aprilzero** [nitaliano/react-native-mapbox-gl#1589]
We've been on RN0.57 and things were working fine.

On upgrading to 0.59, the app ends up crashing instantly when rendering the map, which has some lines on it.

Same code worked fine on 0.57 though and only the version has been changed, so I think it is some incompatibility with the react native upgrade. Is this a known issue or is anyone else running into this?

The error is something about linecap..
![image](https://user-images.githubusercontent.com/114380/56403617-26b08180-629d-11e9-8dfd-0c0a2b6df8ee.png)

**Comment by dorthwein** [comment]
getting this as well

**Comment by dorthwein** [comment]
For me, if I remove <code>lineJoin: "round"</code> from my style props, line string works as expected
