### ISSUE TITLE
Map display is black

### ISSUE THREAD

**Issue by ghamaide** [nitaliano/react-native-mapbox-gl#159]
I'm trying to display a map and I got only a black screen... Xcode outputs : ERROR] {Map}[Setup]: loading style failed: no such file or directory. I tried with : 
styleURL={'asset://styles/mapbox-streets-v7.json'}
styleURL={'asset://styles/dark-v7.json'}

![screen shot 2015-11-27 at 9 37 02 pm](https://cloud.githubusercontent.com/assets/6986811/11447938/065e850e-954f-11e5-8819-47956ef01e54.png)

**Comment by jetaix** [comment]
Same for me :(

'[ERROR] {Map}[Setup]: loading style failed: HTTP status code 401'

My token is valid and permission access right
<img width="412" alt="screen shot 2015-11-28 at 4 37 26 pm" src="https://cloud.githubusercontent.com/assets/4866709/11452641/53308300-95ef-11e5-9b20-56c65b4abdfd.png">

screenshot of my code : 
<img width="908" alt="screen shot 2015-11-28 at 4 43 11 pm" src="https://cloud.githubusercontent.com/assets/4866709/11452642/6227eac4-95ef-11e5-915d-0d2eb4ab073b.png">

**Comment by ghamaide** [comment]
OK, the styles are not in the packages by default anymore. You should now put a personal style and : 
`styleURL={'mapbox://styles/<user>/<style>'}`

**Comment by wywzixin** [comment]
Is your solution solved? My mistake is also this.
