### ISSUE TITLE
Is it possible to add Turn by turn offline navigation using mapbox in react native.?

### ISSUE THREAD

**Issue by qdevelopergithub** [nitaliano/react-native-mapbox-gl#1596]
Hi Mapbox-gl team,
I am developing an app where i need to use turn by turn navigation while user is offline. 
1 .Is it possible with the current version of mapbox for react native?

2.Is there any other mapbox library which i am not aware of for offline navigation like Android and IOS ?

3.Is it possible to implement this with mapbox gl in react native?

**Comment by kristfal** [comment]
1. No, it's not part of the library. The only "easy" solution I can think of is for you to build the bridge between the Mapbox Directions API and the map rendering yourself. This will only work while online.

2. No

3. No, unless you build your own client side routing engine. Something like Valhalla is a starting point (but doing this is likely in the scope of months/years if you want it done properly for both iOS and Android)
