### ISSUE TITLE
Add docs about new repo / deprecate this repo / change mapbox forward

### ISSUE THREAD

**Issue by gmaclennan** [nitaliano/react-native-mapbox-gl#1600]
I see that this repo is still receiving issues and PRs. As far as I understand all development is now happening in https://github.com/react-native-mapbox/maps, but I couldn't see this documented anywhere except from buried in this [closed issue](https://github.com/nitaliano/react-native-mapbox-gl/issues/1555).

I imagine that many users of react-native-mapbox-gl are coming here, and it is currently the repo you reach when you visit https://github.com/mapbox/react-native-mapbox-gl (the previous repo when this was officially supported by Mapbox).

@nitaliano my understanding is has moved to community ownership under https://github.com/react-native-mapbox/maps/ and you do not have the time to review issues here. Is it possible to close issues on this repo, or transfer them to the new repo? Can I help with this? I think there is still some confusion about the status of this library, and I know the explanations are in some (sometimes heated) discussions in issues, but it would be good to find a way of letting others know the status of things.

I could open a PR with an update to the README that just has:

```md
# Deprecated

Development of this library has move to https://github.com/react-native-mapbox/maps/
```

**Comment by systemlevel** [comment]
@gmaclennan check out this comment at the new repository for additional context on this issue https://github.com/react-native-mapbox/maps/issues/7#issuecomment-488007880

**Comment by kristfal** [comment]
We'll do this when we have NPM publishing right for the new org. Right now, that sits with @nitaliano alone.

**Comment by kristfal** [comment]
This is now done.
