### ISSUE TITLE
Erro React-Native Android - react-native": "0.59.1"

### ISSUE THREAD

**Issue by BrunoLagoa** [nitaliano/react-native-mapbox-gl#1602]
It seems that the mapbox does not work on the new versions of react, I'm using the

**"react": "16.8.3",
"react-native": "0.59.1",**

`Dependency path 'mapbox-react-native-mapbox-gl:unspecified' --> 'com.mapbox.mapboxsdk:mapbox-android-sdk:5.4.1' --> 'com.android.support:support-fragment:28.0.0' --> 'com.android.support:loader:28.0.0' --> 'android.arch.lifecycle:livedata:1.1.1' --> 'android.arch.core:runtime:1.1.1' --> 'com.android.support:support-annotations:26.1.0'`

**Comment by zeljkoX** [comment]
Same bug here. It is like npm published version does not have all latest changes from build gradle and it uses old mapbox-android-sdk:5.4.1 version.

When I locally overwrite content of build gradle with the latest one it works beacuse it uses latest mapbox sdk 5.5.3.

**Workaround** is it change `package.json` dependency to: 
```json
    "@mapbox/react-native-mapbox-gl": "https://github.com/nitaliano/react-native-mapbox-gl.git",
```

so it will use latest code from git repo.

**Comment by raphaellopes** [comment]
> Same bug here. It is like npm published version does not have all latest changes from build gradle and it uses old mapbox-android-sdk:5.4.1 version.
> 
> When I locally overwrite content of build gradle with the latest one it works beacuse it uses latest mapbox sdk 5.5.3.
> 
> **Workaround** is it change `package.json` dependency to:
> 
> ```json
>     "@mapbox/react-native-mapbox-gl": "https://github.com/nitaliano/react-native-mapbox-gl.git",
> ```
> 
> so it will use latest code from git repo.

Same here, and it resolves to me too
