### ISSUE TITLE
[ANDROID] Execution failed for task ':mapbox-react-native-mapbox-gl:compileDebugJavaWithJavac'

### ISSUE THREAD

**Issue by ValeraShklyarov** [nitaliano/react-native-mapbox-gl#1605]
`> Task :mapbox-react-native-mapbox-gl:compileDebugJavaWithJavac FAILED
/home/valera/projects/idthiscar/mobile/node_modules/@mapbox/react-native-mapbox-gl/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLImageSourceManager.java:10: error: package com.facebook.react.views.imagehelper does not exist
import com.facebook.react.views.imagehelper.ImageSource;
                                           ^
/home/valera/projects/idthiscar/mobile/node_modules/@mapbox/react-native-mapbox-gl/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyleValue.java:5: error: cannot find symbol
import com.facebook.react.bridge.Dynamic;
                                ^
  symbol:   class Dynamic
  location: package com.facebook.react.bridge
/home/valera/projects/idthiscar/mobile/node_modules/@mapbox/react-native-mapbox-gl/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyleValue.java:63: error: cannot find symbol
    public Dynamic getDynamic(String key) {
           ^
  symbol:   class Dynamic
  location: class RCTMGLStyleValue
/home/valera/projects/idthiscar/mobile/node_modules/@mapbox/react-native-mapbox-gl/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyleFunctionParser.java:5: error: cannot find symbol
import com.facebook.react.bridge.Dynamic;
                                ^
  symbol:   class Dynamic
  location: package com.facebook.react.bridge
/home/valera/projects/idthiscar/mobile/node_modules/@mapbox/react-native-mapbox-gl/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyleFunctionParser.java:6: error: cannot find symbol
import com.facebook.react.bridge.DynamicFromMap;
                                ^
  symbol:   class DynamicFromMap
  location: package com.facebook.react.bridge
/home/valera/projects/idthiscar/mobile/node_modules/@mapbox/react-native-mapbox-gl/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.java:321: error: method does not override or implement a method from a supertype
        @Override
        ^
/home/valera/projects/idthiscar/mobile/node_modules/@mapbox/react-native-mapbox-gl/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.java:323: error: cannot find symbol
            super.dispose();
                 ^
  symbol: method dispose()
/home/valera/projects/idthiscar/mobile/node_modules/@mapbox/react-native-mapbox-gl/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyleFunctionParser.java:49: error: cannot find symbol
                Dynamic dynamicPropertyValue = innerStyleValue.getDynamic("propertyValue");
                ^
  symbol:   class Dynamic
  location: class RCTMGLStyleFunctionParser<T,V>
  where T,V are type-variables:
    T extends Object declared in class RCTMGLStyleFunctionParser
    V extends Object declared in class RCTMGLStyleFunctionParser
/home/valera/projects/idthiscar/mobile/node_modules/@mapbox/react-native-mapbox-gl/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyleValue.java:64: error: cannot find symbol
        return mPayload.getDynamic(key);
                       ^
  symbol:   method getDynamic(String)
  location: variable mPayload of type ReadableMap
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
9 errors
`

`dependencies {
    implementation project(':mapbox-react-native-mapbox-gl')
    implementation 'com.android.support:support-annotations:28.0.3'
    implementation project(':react-native-video')
    implementation project(':react-native-image-crop-picker')
    implementation project(':react-native-keychain')
    implementation project(':react-native-fingerprint-scanner')
    implementation project(':react-native-google-signin')
    implementation 'com.facebook.android:facebook-android-sdk:4.37.0'
    implementation project(':react-native-fbsdk')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation 'com.android.support:design:28.0.0'
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation project(':react-native-navigation')
    implementation 'com.squareup.okhttp3:okhttp:3.12.1'
}`

`buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 20
        compileSdkVersion = 28
        targetSdkVersion = 26
        supportLibVersion = "28.0.0"
        googlePlayServicesAuthVersion = "15.0.1"
        // okhttpVersion = "3.12.1"
    }
    repositories {
        google()
        mavenLocal()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2'
        classpath 'com.google.gms:google-services:3.2.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        mavenCentral()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
            url 'https://jitpack.io'
            url 'https://maven.google.com'
        }
        maven { url 'https://maven.google.com' }
        maven { url 'https://jitpack.io' }
    }
}

subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "28.0.0"
            }
        }
    }
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 28
                buildToolsVersion '28.0.3'
            }
        }
    }
}`

` "react": "16.8.3",
    "react-native": "^0.59.5",`

**Comment by SemionPar** [comment]
Hey. How did you solve this?

@ValeraShklyarov

**Comment by sublimedatasystem** [comment]
@ValeraShklyarov I'm facing the same issue. have anybody found a solution for that??

**Comment by steubs** [comment]
Were you able to get this fixed? I'm having the same issue.

**Comment by steubs** [comment]
@sublimedatasystem 
@SemionPar 
If you're still looking into this try this, it fixed it for me.

https://github.com/react-native-mapbox-gl/maps/issues/163#issuecomment-511542096

**Comment by ngrcode** [comment]
hi I have the same issue for 
"react-native": "0.71.2",
and graddle 8

any suggestion?

**Comment by joaolvcas** [comment]
I'm getting the same issue! 
I run `yarn android`, and got this error:
```Execution failed for task ':rnmapbox_maps:compileDebugKotlin'.
> Compilation error. See log for more details

**Comment by joaolvcas** [comment]
> hi I have the same issue for "react-native": "0.71.2", and graddle 8
> 
> any suggestion?

have you resolve this issue? I'm still getting the same.
