### ISSUE TITLE
accessToken is required on Android?

### ISSUE THREAD

**Issue by awdhootlele** [nitaliano/react-native-mapbox-gl#1607]
Hello,

I am using custom styles in my application, so I removed the setAccessToken() call.
Since then, my app started to crash on Android with the error pointing to above call. It seems, on Android, the setAccessToken() is required.

On IOS, app runs properly without the accessToken.

Also, on the [mapbox-gl-native](https://github.com/mapbox/mapbox-gl-native) repo, the [PR to make the accesToken optional has been merged.](https://github.com/mapbox/mapbox-gl-native/pull/12001)

Is is possible to make the accessToken optional on Android SDK as well?

Thanks.

btw the error is - 
com.mapbox.mapboxsdk.exceptions.MapboxConfigurationException: 
    Using MapView requires setting a valid access token. Use Mapbox.getInstance(Context context, String accessToken) to provide one. 
    Please see https://www.mapbox.com/help/create-api-access-token/ to learn how to create one.

**Comment by sfratini** [comment]
The current version of the RN repo uses an Android native sdk that is before that PR so yes, it is needed. I understand this will change once v7 drops.
