### ISSUE TITLE
How to change react-native-mapbox-gl default language to Farsi / Persian or arabic

### ISSUE THREAD

**Issue by jafarpishdadi** [nitaliano/react-native-mapbox-gl#1610]
hello
How to change react-native-mapbox-gl default language to Farsi / Persian or arabic

in all device  default language change to Farsi / Persian or arabic

**Comment by phiilu** [comment]
Put this prop on the MapView `localizeLabels` 
This will use the sysem language.

**Comment by club9822** [comment]
Use cedarmap or map.Ir.  For style
