### ISSUE TITLE
crash when generate apk react native maps

### ISSUE THREAD

**Issue by jingfreeks** [nitaliano/react-native-mapbox-gl#1616]
hello good day,

I have a problem regarding react native maps, it crashes when I generate into apk, however it works fine when I run it on the debug mode.

hoping for your reply,

**Comment by kristfal** [comment]
You need to provide error logs and a better description for how to reproduce.

**Comment by jingfreeks** [comment]
here is the error log when I check on adb logcat

05-15 15:49:53.819 18537 18556 E ReactNativeJS: s is not a function. (In 's()', 's' is 3)
05-15 15:49:53.828 18537 18557 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
05-15 15:49:53.828 18537 18557 E AndroidRuntime: Process: com.beaheromobile, PID: 18537
05-15 15:49:53.828 18537 18557 E AndroidRuntime: com.facebook.react.common.JavascriptException: s is not a function. (In 's()', 's' is 3), stack:

**Comment by ferdicus** [comment]
I'm assuming proguard is enabled for production builds?
