### ISSUE TITLE
How to render a Offline-Map

### ISSUE THREAD

**Issue by robert599** [nitaliano/react-native-mapbox-gl#1625]
Hi,
i've downloaded the offlinePack (see console output). But when I cut the internet, the mapScreen is still empty. What I need to do, to render this map. Is this a out of the box solution by mapbox or is there something in need to do?
In the documentation I found good descriptions how to download, get and delete a map, but not how to display the offline map.

here is the output of my downloaded map:
![downloaded mapview](https://user-images.githubusercontent.com/48709864/58306516-0889f400-7dfc-11e9-8ef2-caa34958c7be.JPG)

**Comment by robert599** [comment]
I found the solution by my self. Mapbox is rendering the offline map automatically if there is an offline map available and there is no connection to the internet. My problem was that my emulator had location coordinates far away from my offline map detail. And when the zoom is also far away, the map seems to be empty.

**Comment by Babar-Memon** [comment]
same issue any help??
