### ISSUE TITLE
Will this support Apple's new Metal framework?

### ISSUE THREAD

**Issue by awdhootlele** [nitaliano/react-native-mapbox-gl#1626]
Apple from IOS 12 have deprecated the OpenGL support and encouraging devs to migrate to the new Metal framework.

Will this library work on the new metal framework? Not sure if Apple will still support openGl but if it decides to get rid of the openGL from IOS13, what will be the roadmap of this library.

Should we all follow [this thread](https://github.com/mapbox/mapbox-gl-native/issues/12061) for any updates on this?

Thanks.

**Comment by kristfal** [comment]
This will be handled upstream in the mapbox-gl-native library. The issue in their repo #12061 is almost a year old. We just have to make sure we update when they do. Keep in mind that the current repo here is being deprecated. you should move over to https://github.com/react-native-mapbox/maps
