### ISSUE TITLE
MapboxGL OfflineManager in 6.1.3 seems not working

### ISSUE THREAD

**Issue by bastien-hugon** [nitaliano/react-native-mapbox-gl#1629]
Hi,

I'm using the offlineManager like this:
```javascript
await MapboxGL.offlineManager.createPack({
    name: 'offlinePack',
    styleURL: MAP_URL,
    minZoom: 18,
    maxZoom: 20,
    bounds: [[1.82373046875, 43.85450320338616], [-1.4316386198818236, 43.6592276576182]],
});
```
And when my phone is in Airplane Mode, and when I delete the cache, I don't see the map in this area and this zoom level.

I don't remove the local storage of my application, only the cache.

Is it my MapBox version or something like this ? Thank you for your future answers.

Best regards,
Bastien

**Comment by bastien-hugon** [comment]
I have resolved the problem.

If you want to save an offline Map Pack you have to wait for the map to be fully charged. And then you can start the download.

Sorry for this issue.

**Comment by allthetime** [comment]
@bastien-hugon what do you mean by the map needs to be "fully charged" I am trying to download map tiles and they are not showing up with the phone disconnected after downloading.

**Comment by FernandesTeu** [comment]
@allthetime I had this problem too, and works for me with the code example bellow:

async **onDidFinishLoadingStyle**() {
    const {width, height} = Dimensions.get('window');
    const bounds = geoViewport.bounds(
      CENTER_COORD,
      12,
      [width, height],
      MAPBOX_VECTOR_TILE_SIZE,
    );

    const options = {
      name: this.state.name,
      styleURL: MapboxGL.StyleURL.Street,
      bounds: [
        [bounds[0], bounds[1]],
        [bounds[2], bounds[3]],
      ],
      minZoom: 10,
      maxZoom: 20,
    };

    // start download
    MapboxGL.offlineManager.createPack(options, this.onDownloadProgress);

  }


`<MapboxGL.MapView
          ref={(c) => (this._map = c)}
          onDidFinishLoadingMap={this.onDidFinishLoadingStyle}
          style={{flex: 1}}>
          />`


after this, I can close the app, turn of the internet and when I open the app, the map appears
