### ISSUE TITLE
Annotations location duplicate update

### ISSUE THREAD

**Issue by sonnylazuardi** [nitaliano/react-native-mapbox-gl#163]
when I try to update the annotations (like real time map), the old annotations were still there. So, it makes duplicate annotations since the old annotation is not removed. Do you have any solutions for this?

**Comment by kouya0219** [comment]
+1

**Comment by rajkissu** [comment]
I have the same problem. I tried working around by removing the annotations, but this causes an undesirable flash-like effect.

+1 to getting this feature out!

**Comment by tmcw** [comment]
Folding into https://github.com/mapbox/react-native-mapbox-gl/issues/304#issue-140745330 which covers making all APIs idempotent.
