### ISSUE TITLE
'RCTView.h' file not found when installing with Cocoapod

### ISSUE THREAD

**Issue by dagatsoin** [nitaliano/react-native-mapbox-gl#165]
Following the [installation instructions](https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/install.md) with Cocoa Pods

When I hit run:

```
/Users/vikti/dev/Wizar/node_modules/react-native-mapbox-gl/ios/RCTMapboxGL/RCTMapboxGL.h:11:9: 'RCTView.h' file not found
```

My environment:
Node v4.2.2
React Native v.0.15.0

**Comment by bsudekum** [comment]
I'm seeing the same thing now too. @jerolimov have you seen this. ref https://github.com/mapbox/react-native-mapbox-gl/pull/123

**Comment by dagatsoin** [comment]
The weird thing is that RCTView.h is present (imported with React). But outside the /Pod group in the Xcode hierarchy browser.

**Comment by AgtLucas** [comment]
Hey @dagatsoin.

Adding this...

``` ruby
pod 'React', :path => '../node_modules/react-native'
pod 'React/RCTGeolocation', :path => '../node_modules/react-native'
pod 'React/RCTImage', :path => '../node_modules/react-native'
pod 'React/RCTNetwork', :path => '../node_modules/react-native'
pod 'React/RCTText', :path => '../node_modules/react-native'
pod 'React/RCTWebSocket', :path => '../node_modules/react-native'
```

...in my `Podfile` solve the problem for me.

**Comment by christoph-jerolimov** [comment]
@AgtLucas is right, you need to import React also in your Podfile. I expect we can close this?!

**Comment by AgtLucas** [comment]
@jerolimov I agree, but would be helpful to add this in the installation guide. :)

**Comment by christoph-jerolimov** [comment]
Here is a PR for an extended documetation for the CocoaPods part: https://github.com/mapbox/react-native-mapbox-gl/pull/218/files

**Comment by tmcw** [comment]
Covered by new, merged documentation for CocoaPods install https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/install-cocoapods.md#troubleshooting-with-cocoapods
