### ISSUE TITLE
types ShapeSourceProps onPress func

### ISSUE THREAD

**Issue by rbonillajr** [nitaliano/react-native-mapbox-gl#1659]
please fix issue. add eventArgs 

interface ShapeSourceProps {
    id?: string;
    url?: string;
    shape?: any;
    cluter?: boolean;
    clusterRadius?: number;
    clusterMaxZoomLevel?: number;
    maxZoomLevel?: number;
    buffer?: number;
    tolerance?: number;
    images?: any;
    **onPress?: (e: any) => void;**
    hitbox?: any;
}

**Comment by kristfal** [comment]
Open a PR and I’ll get it in.

**Comment by rbonillajr** [comment]
thanks @kristfal. here the PR
https://github.com/nitaliano/react-native-mapbox-gl/pull/1660
