### ISSUE TITLE
Clearer dependencies version

### ISSUE THREAD

**Issue by dagatsoin** [nitaliano/react-native-mapbox-gl#167]
As React Native as MapboxGL is growing quickly with breaking changes it will be clearer for everyone if you write the compatibility with the last versions of React Native and MapboxGL on the readme.
For example 

```
build failed with mapbox-gl@v3.0.0 and react-native@v0.15
build passes with mapbox-gl@v3.0.0 and react-native@v0.14
```

**Comment by bsudekum** [comment]
Yeah, at one point there was a `peerDependency` but since npm 3+ is depricating this api, I removed it. I think clearer callout in the readme is a good alternative.

**Comment by tmcw** [comment]
Right now react-native-mapbox calls to its own node_modules dir https://github.com/mapbox/react-native-mapbox-gl/blob/master/package.json#L28 with the expectation that react-native will be there - should that be nixed?

**Comment by bsudekum** [comment]
Yeah I dont think this should be here.

**Comment by tmcw** [comment]
okay, if not in this repo, could we have a react-native-mapbox-gl-example repo?

**Comment by bsudekum** [comment]
Sure, I'm okay with adding an example app to this repo
