### ISSUE TITLE
Change the preinstall and start script to something less *nix based

### ISSUE THREAD

**Issue by rmevans9** [nitaliano/react-native-mapbox-gl#170]
With React Native going to android the use of bash scripts becomes problematic for users on Windows. For example on my windows machine I can't get NPM to install mapbox gl because it attempts to execute the bash script in the /scripts directory which obviously will fail.

**Comment by tmcw** [comment]
At least I'm not sure about the potential solution here:
- A node script - no built-in zip file support
- A bat script that does the same thing as the shell script?

@rmevans9 if the Windows user has cygwin installed, will the bash script work?

**Comment by rmevans9** [comment]
Since the bash script only is required for iOS in theory it could be a script that simply checks for OS and then executes the current if you are on OSX. Kinda a hacky way to do it but it would solve the problem

**Comment by vessp** [comment]
Just installed cygwin and tried it, got the same error:

> '.' is not recognized as an internal or external command, operable program or batch file.

**Comment by jayfunk** [comment]
Overall I think that script should not be executed on anything except OSX.
