### ISSUE TITLE
[suggestion] Get access to GL camera props

### ISSUE THREAD

**Issue by dagatsoin** [nitaliano/react-native-mapbox-gl#174]
Would it be a good/bad idea to get access to GL camera props?
It could be usefull to make custom GL View overlays matching perfectly the underlying MapView.

**Comment by dagatsoin** [comment]
I will ask on the main mapbox gl repo to ask if those props are accessible. If so, I will try to implement that in react native component.

**Comment by bsudekum** [comment]
Yeah, I thinking adding this would be a great idea @dagatsoin. Happy to review a PR :smile:
