### ISSUE TITLE
Android demo doesn't work

### ISSUE THREAD

**Issue by Otouto** [nitaliano/react-native-mapbox-gl#175]
Trying to run [default demo](https://github.com/mapbox/react-native-mapbox-gl/blob/master/android/example.js) and get an error:

![image](https://cloud.githubusercontent.com/assets/1306915/11615471/e4349564-9c69-11e5-9ca8-111caca00e57.png)

**Comment by Otouto** [comment]
#177

**Comment by bsudekum** [comment]
This has been fixed and released
