### ISSUE TITLE
Proptype issues with 0.16.0: RCTMapbox` has no propType for native prop `RCTMapbox.renderToHardwareTextureAndroid` of native type `boolean

### ISSUE THREAD

**Issue by jforaker** [nitaliano/react-native-mapbox-gl#177]
see https://github.com/facebook/react-native/issues/4605

`RCTMapbox` has no propType for native prop `RCTMapbox.renderToHardwareTextureAndroid` of native type `boolean`

After manually setting the `renderToHardwareTextureAndroid` Proptype in the plugin, it proceeds to throw more Proptype errors for all of the following :

```
  renderToHardwareTextureAndroid

  onLayout

  accessibilityLiveRegion

  accessibilityComponentType

  importantForAccessibility

  accessibilityLabel

  testID
```

**Comment by bsudekum** [comment]
Fixed in https://github.com/mapbox/react-native-mapbox-gl/pull/176
