### ISSUE TITLE
Fatal signal 11 for React Native Android use

### ISSUE THREAD

**Issue by zj-lin-zj** [nitaliano/react-native-mapbox-gl#186]
I encountered the error below which crashes the app completely. I am now using RN0.15 on Android, Genymotion Android 4.2.2 and Mac OS X.

My code snippet is as below

  < Mapbox
          accessToken={'token'}
          debugActive={true}
          direction={0}
          rotationEnabled={true}
          scrollEnabled={true}
          style={styles.map}
          showsUserLocation={true}
          styleUrl={'asset://styles/streets-v8.json'}
          UserLocationTrackingMode={'FOLLOW'}
          zoomEnabled={true}
          zoomLevel={10}
        / >

Error:
12-13 17:29:01.283 7423-7423/com.xyz E/mbgl: {Main}[OpenGL]: eglChooseConfig() returned no configs.
12-13 17:29:01.283 7423-7423/com.xyz A/libc: Fatal signal 11 (SIGSEGV) at 0xdeadcab1 (code=1), thread 7423 (com.xyz)

**Comment by tmcw** [comment]
Folding into newer issue that discusses the same crash under genymotion <= 5 #267
