### ISSUE TITLE
Indicate project's lack of official support in readme, etc

### ISSUE THREAD

**Issue by friedbunny** [nitaliano/react-native-mapbox-gl#191]
We should warn users against using this in production, especially as it cannot currently conform to our mobile telemetry requirements (https://github.com/mapbox/react-native-mapbox-gl/issues/190).

/cc @bsudekum @mapbox/support

**Comment by tmcw** [comment]
We don't do this in any other projects, and I don't think that statuses send much of a signal to devs. I think we should do #190 and shipit.

**Comment by bsudekum** [comment]
@tmcw we can add that to the list. Also on the list is: https://github.com/mapbox/react-native-mapbox-gl/issues/102
