### ISSUE TITLE
Are plugins supported?

### ISSUE THREAD

**Issue by bartonhammond** [nitaliano/react-native-mapbox-gl#192]
[https://www.mapbox.com/mapbox.js/plugins/](https://www.mapbox.com/mapbox.js/plugins/) shows numerous plugins.

How do I include a specific plugin and how do I know it's even supported?

-thanks

**Comment by bsudekum** [comment]
The plugins on https://www.mapbox.com/mapbox.js/plugins/ are for the most part meant to be used with mapbox.js, a library for creating maps on the web. However, some of these plugins can be used with react native. Turf for instance does not need a browser and therefore can be used with react native. 

From this list, I'm seeing the following can be used with React Native:
- turf
- point in polygon
- leaflet-omnivore
- geojson-extent
- geo-viewport

**Comment by bartonhammond** [comment]
Thanks for the clarity.
