### ISSUE TITLE
[Question] Is there an easy way to generate a circle and add it to the map?

### ISSUE THREAD

**Issue by ivanbrens** [nitaliano/react-native-mapbox-gl#194]
To display an area instead of a point?

**Comment by bsudekum** [comment]
Yes, you can [draw a circle here](http://geojson.io/#map=2/12.0/-9.5) and then add it to the `annotations` prop.

**Comment by munkh-altai** [comment]
Hello @bsudekum can you provide example, I tired with http://geojson.io/
