### ISSUE TITLE
Remove points, polylines

### ISSUE THREAD

**Issue by Lonsss** [nitaliano/react-native-mapbox-gl#195]
Hi. I use react-native with mapbox-gl and my task remove markers from map. 
Can u help with this question?

**Comment by bsudekum** [comment]
You can use the method `removeAnnotation`, ref https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/API.md#methods-for-modifying-the-map-state

**Comment by Lonsss** [comment]
thanks. Is it possible to do in Android too???

**Comment by bsudekum** [comment]
It will be once https://github.com/mapbox/react-native-mapbox-gl/pulls is merged.
