### ISSUE TITLE
Option to disable that the default title is shown when annotation is pressed

### ISSUE THREAD

**Issue by skeie** [nitaliano/react-native-mapbox-gl#196]
Hi, is it possible to disable popovers even if title or subtitle is present?

![image](https://cloud.githubusercontent.com/assets/1346122/11834985/651a3ce2-a3d1-11e5-8727-456e34f7f12e.png)

**Comment by bsudekum** [comment]
I'm not sure I follow. Are you looking to disable the popover completely?

**Comment by skeie** [comment]
Yep, that would be nice.

**Comment by bsudekum** [comment]
There is no way to disable popovers if you provide a title and/or a subtitle. If you do not want a popover, simply do not provide a title and subtitle.
