### ISSUE TITLE
geoJson support

### ISSUE THREAD

**Issue by bartonhammond** [nitaliano/react-native-mapbox-gl#197]
How do I load geoJSON as in this example:
[https://www.mapbox.com/help/markers/#with-geojson](https://www.mapbox.com/help/markers/#with-geojson)

snippet:

```
var geojson = [
  {
    "type": "Feature",
    "geometry": {
      "type": "Point",
      "coordinates": [-77.031952,38.913184]
    }
  },
  {
    "type": "Feature",
    "geometry": {
      "type": "Point",
      "coordinates": [-122.413682,37.775408]
    }
  }
];

var mapGeo = L.mapbox.map('map_geo', 'mapbox.light')
  .setView([37.8, -96], 4);

var myLayer = L.mapbox.featureLayer().setGeoJSON(geojson).addTo(mapGeo);
```

**Comment by bsudekum** [comment]
This project does not support geojson directly. You will have conform the geojson object to fit the properly with the annotations prop. Please see the [example](https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/example.js#L23) and the [docs](https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/API.md#annotations) for a reference. 

For your example above, it would look like: 

``` jsx
annotations={[{
  type: 'point',
  coordinates: [38.913184, -77.031952]
}, {
  type: 'point',
  coordinates: [37.775408, -122.413682]
}]}
```

**Comment by bartonhammond** [comment]
bummer
