### ISSUE TITLE
Mixin Not working

### ISSUE THREAD

**Issue by reactor81** [nitaliano/react-native-mapbox-gl#203]
It seems MapBox.Mixin is not defined, and all of the mixin methods, vars are undefined. I'm just using the example for Android. 

When I removed the two bits from the mixin, the map renders, but none of the methods from the mixin work so it redscreens when I try to removeannotations, etc from the example. 

Is this a known issue?

**Comment by bsudekum** [comment]
On android, `Mapbox.Mixin` has not yet been released on npm. This will come in a v3.0.0 release which will becoming soon. Please reference the example.js file that ships with version that you `npm install`.
