### ISSUE TITLE
MGLAccountManager.h file not found

### ISSUE THREAD

**Issue by reactor81** [nitaliano/react-native-mapbox-gl#204]
I followed all of the instructions in the ios Manual Installation. Indeed, I did them twice.. But I am receiving this error when building. Any tips?

thanks.

**Comment by reactor81** [comment]
It also looks like, in XCode that MGLAnnotation.h, MGLMapView.h, MGLMApView+IBAdditions.h, MGLTypes.h and MGLUserLocation.h are all empty. Hmmm

**Comment by bsudekum** [comment]
This sounds like something went wrong during npm install. Can you see if there was an error output there.

**Comment by reactor81** [comment]
Thanks, After deleting folder and redoing npm install, it looks like the files are there.

Now I get a compile error 'library not found for -lMapbox' . Hmm wIll check around

**Comment by reactor81** [comment]
Okay, iOS is building now. I had linked in libMapbox.a as well as libRCTMapBoxGL.a. removing libMapbox.a fixed it. 

Now my issue is just that callouts are not opening when clicking a marker on Android. I think this is a known issue? Will create another thread

**Comment by vinhtq** [comment]
I also have the same problem and Could not build module Mapbox
