### ISSUE TITLE
Android - touching markers no effect

### ISSUE THREAD

**Issue by reactor81** [nitaliano/react-native-mapbox-gl#205]
Hi, 

Is this a known issue? It sounds similar to another one posted but it is not clear.. 

When touching markers on Android, no popup / description comes. Is this a known issue? Where should I look to try and resolve / add this?

Also, for the 'rightCalloutAccessorry' as in the iOS example. Is it possible for that to navigate to another view when clicking the 'gear' icon? That should be possible correct?

**Comment by fxhereng** [comment]
+1

**Comment by bsudekum** [comment]
Closing in favor of https://github.com/mapbox/react-native-mapbox-gl/issues/102
