### ISSUE TITLE
Compass Property Issue!

### ISSUE THREAD

**Issue by dcflow** [nitaliano/react-native-mapbox-gl#206]
Hello,

I am using Mapbox for android on react-native and the property `compassIsHidden={true}` doesn't hide the compass on the initial render.

Thank You!

**Comment by gendronb** [comment]
I had the same issue, it seems that if the initial direction is not 0 ( as in the example, `direction={10}`), the compass will be visible anyway...

**Comment by dcflow** [comment]
Thank you for your help  @gendronb . :)
