### ISSUE TITLE
Android incorrectly propagating touch / gesture event

### ISSUE THREAD

**Issue by reactor81** [nitaliano/react-native-mapbox-gl#208]
iOS correctly stops propagation of the touch / pan event when scroll the map. So, when I have the MapBox in a scrollable tab view (e.g. horizontal scroll view), the scroll view does not pan. This is good because I just want to pan the map.

However, Android is not stopping the propagation. The scrollview is also scrolling, moving the entire mapbox out of view. 

How can this be resolved? I am willing to fork and fix, but is it possible in JS or must I modify the native Java code?

**Comment by nineteeneightyeight** [comment]
This is causing me issues as well. Did you have any luck remedying it reactor81?

**Comment by Gnative** [comment]
Curious as how I can prevent any touch events on the map to be able to have just a static map, woudl you guys know how this is supported ?

**Comment by ujazdowskip** [comment]
@Gnative There are config props:

`rotateEnabled`
`scrollEnabled`
`zoomEnabled`

If you set them to false map will be static.

**Comment by ujazdowskip** [comment]
I noticed that MapView does not passing events to parents panResponder on Android. So this works only  on iOS:

`
<View
         style={[styles.container]}
         onStartShouldSetResponder={() => {
           console.log('logs only on ios');
         }}
       >
       <Map />
</View>
`

Wondering if this is related to this issue or is it separate bug?

**Comment by joshuapinter** [comment]
Take a look at this SO question: https://stackoverflow.com/questions/6546108/mapview-inside-a-scrollview

Looks like the solution was used to fix the same scrolling issue on react-native-maps: https://github.com/airbnb/react-native-maps/pull/343
