### ISSUE TITLE
Android - add a marker

### ISSUE THREAD

**Issue by fxhereng** [nitaliano/react-native-mapbox-gl#209]
I'm trying out your example but all the interactions including adding a marker doesn't work.

![device-2015-12-23-163414](https://cloud.githubusercontent.com/assets/5686128/11979398/50edd022-a993-11e5-8733-f0bc8fd87e78.png)

Additionnally, clicking on markers doesn't work as well.

Am I missing something? or is it going to be fixed soon?

Best regards,

**Comment by gendronb** [comment]
From what I understand, the `Mapbox.Mixin` is not yet implemented on Android, see #203

**Comment by bsudekum** [comment]
Yes, master is ahead of the current release. There are a few last items I need to hit before the 3.0 release.

**Comment by fxhereng** [comment]
All right, thank you for the quick answer
