### ISSUE TITLE
Map not rendered

### ISSUE THREAD

**Issue by gilbox** [nitaliano/react-native-mapbox-gl#21]
I'm trying out the example code in the README, seems to work except that the map doesn't render. No errors in the console. Any ideas?

![image](https://cloud.githubusercontent.com/assets/2136203/7555134/e8ee7366-f707-11e4-84d9-1f95c501ed81.png)

**Comment by bsudekum** [comment]
@gilbox I've seen this happen a couple of times. Can you try:
- changing the style, see https://github.com/bsudekum/react-native-mapbox-gl#gl-styles
- cleaning the build

Not really certain where the error is coming from. This could be a caching issue.

**Comment by gilbox** [comment]
I did both those things and it's working. Thanks so much!

**Comment by bsudekum** [comment]
:+1:
