### ISSUE TITLE
[Error] - NativeModules.MapboxGLManager.mapStyles

### ISSUE THREAD

**Issue by AgtLucas** [nitaliano/react-native-mapbox-gl#212]
Hey people! :)

I'm trying to use React Native + Mapbox with `Cocoapods`.

I'm getting this error when the app is built.

![screen shot 2015-12-28 at 10 15 32 am](https://cloud.githubusercontent.com/assets/1909761/12018619/607c38e6-ad4c-11e5-8a25-aafeaebf5649.png)

And this one in the Xcode's console:

![screen shot 2015-12-28 at 10 23 40 am](https://cloud.githubusercontent.com/assets/1909761/12018668/1f5f1602-ad4d-11e5-99cd-a936931e55a6.png)

```
2015-12-28 10:15:26.358 [error][tid:com.facebook.React.RCTExceptionsManagerQueue] Unhandled JS Exception: Invariant Violation: Application Sirens has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.
```

Here's my code:

``` javascript
'use strict'

var React = require('react-native')
var Mapbox = require('react-native-mapbox-gl')
var mapRef = 'mapRef'

var {
  AppRegistry,
  StyleSheet,
  StatusBarIOS,
  View
} = React

var Sirens = React.createClass({
  mixins: [Mapbox.Mixin],

  getInitialState () {
    return {
      center: {
        latitude: -26.4537736,
        longitude: -49.1179425
      },
      zoom: 11
    }
  },

  onRegionChange (location) {
    this.setState({ currentZoom: location.zoom })
  },

  onRegionWillChange (location) {
    console.log(location)
  },

  onUpdateUserLocation (location) {
    console.log(location)
  },

  onLongPress (location) {
    console.log('Long pressed', location)
  },

  render: function () {
    StatusBarIOS.setHidden(true)
    return (
      <View>
        <Mapbox
          style={styles.map}
          direction={0}
          rotateEnabled={true}
          scrollEnabled={true}
          zoomEnabled={true}
          showsUserLocation={true}
          ref={mapRef}
          accessToken={'the-mapbox-token'}
          styleURL={this.mapStyles.emerald}
          userTrackingMode={this.userTrackingMode.none}
          centerCoordinate={this.state.center}
          zoomLevel={this.state.zoom}
          onRegionChange={this.onRegionChange}
          onRegionWillChange={this.onRegionWillChange}
          onUpdateUserLocation={this.onUpdateUserLocation}
          onLongPress={this.onLongPress}
        />
      </View>
    )
  }
})

var styles = StyleSheet.create({
  container: {
    flex: 1
  },
  map: {
    flex: 1
  }
})

AppRegistry.registerComponent('Sirens', () => Sirens)
```

Currently I'm using:
- El Capitan
- Xcode 7.2 (7C68)
- Node.js: 5.2.0
- React Native: 0.1.7
- Ruby: 2.2.1
- Cocoapods: 0.39.0

Any ideas?

Thanks!

**Comment by christoph-jerolimov** [comment]
I have the same problem with react-native 0.17. Maybe it is a problem with the new "lazy loading" mechanism for modules. See also the [release notes](https://github.com/facebook/react-native/releases/tag/v0.17.0) or the verbose [commit message](https://github.com/facebook/react-native/commit/060664fd3d9331f062696e68179bac9cd4544a06).

**Comment by christoph-jerolimov** [comment]
@AgtLucas I found a problem with my Xcode project which was generated with `react-native init`. When running `pod install` or `pod update` CocoaPods prints also this relevant warning at the end:

```
[!] The `$appname [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `../Pods/Target Support Files/Pods/Pods.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `$appname [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `../Pods/Target Support Files/Pods/Pods.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

For my project the solution was to open the build settings (of your app), search for `OTHER_LDFLAGS` and remove the predefined configuration (`-objc`). Just select the line other linker flags and press the DEL key.

@AgtLucas Could you verify this fix? Then I think we could update the [installation docs](https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/install.md).

See also http://stackoverflow.com/questions/19213782/undefined-symbols-for-architecture-arm64

**Comment by AgtLucas** [comment]
@jerolimov Thanks! I'll give a try ASAP! :)

Edit: Thank you so much @jerolimov! Removing `(-objc)` did the trick! :)

**Comment by christoph-jerolimov** [comment]
Here is a PR for an extended documetation for the CocoaPods part: https://github.com/mapbox/react-native-mapbox-gl/pull/218/files

**Comment by AgtLucas** [comment]
@jerolimov :+1:

**Comment by AgtLucas** [comment]
I'm going to reopen this issue 'cause I'm getting the same error, now on Android...

@jerolimov Any idea?

**Comment by AzizAK** [comment]
@AgtLucas try to install it without --ignore-scripts ..

just install it like this ( npm install react-native-mapbox-gl --save )

it worked for me

**Comment by AgtLucas** [comment]
@AzizAK Yep! I already did that. :/

**Comment by AzizAK** [comment]
@AgtLucas try uninstalling it and reinstall it without --ignore script

**Comment by AgtLucas** [comment]
@AzizAK Yep, but I had installed without `--ignore-scripts` when I did it for the first time. :(

But I'll give a try!

Thanks!

**Comment by rajkissu** [comment]
I'm getting this error on android too, after upgrading to react-native 0.18. Any luck finding a fix?

**Comment by jordangarside** [comment]
I'm running into this issue (NativeModules.MapboxGLManger.mapStyles) on iOS.
I can't remove -ObjC because it crashes my app with the error:
`Requiring module "InitializeJavaScriptAppEngine" which threw an exception`
at line:
`if (self.reactTag && _bridge.isValid) {      // Thread 1: singal SIGABRT error`
I'm using the latest `react-native init` and `react-native-mapbox-gl` so I'm not sure if you guys have gotten it to work.

**Comment by joshuaferrara** [comment]
I too am running into this issue. I tried removing `-ObjC` but had the same issue as @jordangarside

**Comment by vinhtq** [comment]
I also had this problem on android. Did anyone solve it?

**Comment by sjfldk** [comment]
Any word on this? Same problem on Android.

**Comment by vinhtq** [comment]
I removed the old package and reinstall new version 4.0.0. Problem solved!

**Comment by AgtLucas** [comment]
@vinhtq Good to know! I'll give a try. :)

**Comment by vinhtq** [comment]
Just to make sure you should do everything over again and install the ver 4.0

Because if you removed the old one, the references in the xcode project maybe still there

**Comment by AgtLucas** [comment]
@vinhtq Got it. Probably I'll start a new project. :)

**Comment by vinhtq** [comment]
If everything still does not work. Please download this project from link:
https://cloudup.com/c9J25rX9Jla

This is made by @bsudekum 

This is 100% working for me. No error!

**Comment by sjfldk** [comment]
Don't know if this is of help to anyone, but I realised I was getting this error due to forgetting to add `new ReactNativeMapboxGLPackage()` to `getPackages()` in my MainActivity.

**Comment by tmcw** [comment]
@bsudekum is this issue closable?

**Comment by bsudekum** [comment]
Yes, this is stale. If this issue re-appears, open a fresh ticket.
