### ISSUE TITLE
Clearing memory on component unmount

### ISSUE THREAD

**Issue by nickfujita** [nitaliano/react-native-mapbox-gl#215]
When placing a Mapbox component on a page, and using navigational elements like SegmentedControlIOS or NavigatorIOS, it appears that the memory that was allocated for the element is not cleared. By repeatedly navigation between screens with the map, memory usage is constantly increasing until it hits the limit, and crashes the app. The problem is amplified when rendering multiple instances of the Mapbox component on a page (such as in a list).

Is there a method that needs to be manually called to unmount the component, and free up memory. If so, I would like to do so in the component lifecycle method componentWillUnmount. Else, is would it be possible to have the component clean itself up when it is unmounting?

For my implementation, I used the same format provided in the example that adds the mixins in the component, and am using custom styles (providing the access token and style url).

Any help would be greatly appreciated. Thanks in advance!

**Comment by bsudekum** [comment]
Yep, this should happen. I'm think in [index.ios.js](https://github.com/mapbox/react-native-mapbox-gl/blob/master/index.ios.js), `componentWillUnmount` is called which backgrounds the map somehow.

**Comment by bsudekum** [comment]
Woof ![3](https://cloud.githubusercontent.com/assets/1058624/12133101/f3f8f8da-b3d6-11e5-9cc2-77e1050fe8d9.gif)

**Comment by 1ec5** [comment]
The issue likely lies upstream in the Mapbox iOS SDK. We’re tracking a known memory leak in mapbox/mapbox-gl-native#3130; it’s on my priority list to investigate.

**Comment by 1ec5** [comment]
A fix for mapbox/mapbox-gl-native#3130 is in [v3.1.0-pre.2](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.1.0-pre.2) of the Mapbox iOS SDK. @bsudekum, can you verify that memory is reclaimed after destroying the map? Thanks!

**Comment by Taakn** [comment]
I am seeing this issue. The app crashes after 5 or 6 reloads

**Comment by vicapow** [comment]
Can I ask why this issue was closed? Also, I'm still seeing this behavior on the latest version.

**Comment by nitaliano** [comment]
All old issues from the unsupported codebase were closed out to focus on 6.0.0 since it is a complete rewrite. We can reopen if you're still seeing this issue I haven't personally tried this repo with SegmentedControlIOS or NavigatorIOS. Only react-native-navigation, react-navigation, and the Modal component

**Comment by vicapow** [comment]
That makes sense. Looking at this again, I’m not even 100% my issue is the same as I’m using android. I’ll see if I can put together a separate demonstration of the issue. If I can, I’ll create a new ticket

**Comment by Kendesi** [comment]
@bsudekum finally you found how to fix it?
