### ISSUE TITLE
Warning: Failed propType: typeChecker is not a function..

### ISSUE THREAD

**Issue by ryandury** [nitaliano/react-native-mapbox-gl#216]
Hey folks,

I am receiving this warning when loading annotations.  They appear fine, but I get this yellow notice:
Warning: Failed propType: typeChecker is not a function..

It doesn't happen if i remove annotations={this.state.annotations} from:

```
            <MapboxGLMap
                style={this.props.style}
                zoomLevel={this.state.zoom}
                centerCoordinate={this.state.center}
                annotations={this.props.annotations}
                styleURL={'mapbox://styles/mapbox/streets-v8'}
                />
```

My annotation looks like this:
                        {
                            id: 'random'
                            coordinates: [point.location.latitude, point.location.longitude],
                            title: point.objectId,
                            'type': 'point'
                        }

No warnings in Xcode.

Any ideas?

Thank you!

**Comment by guofoo** [comment]
I get the same warning after upgrading to the latest from an older version.

**Comment by yonahforst** [comment]
same here
