### ISSUE TITLE
existing annotations aren't removed when updated via props

### ISSUE THREAD

**Issue by yonahforst** [nitaliano/react-native-mapbox-gl#217]
say I have a component that renders a mapbox map, where the annotations are passed down by the parent component via properties:

```
<Mapbox
....
annotations={this.props.annotations}
/>
```

When the parent component sends down an update, `this.props.annotations` is added on top of the existing annotations without clearing them. This might be the correct and desired behaviour, but then I'm lost for how to update existing annotations via props.

**Comment by guofoo** [comment]
I'm seeing the same problem. I upgraded from an older version, where the behaviour is that the previous annotations are cleared and replaced with the current ones.

**Comment by christopherdro** [comment]
@bsudekum I'm noticing this from `addAnnotations`.
I was under the impression that the latest changes were supposed update an existing annotation based on its id. 

Will start taking a closer look.

**Comment by yonahforst** [comment]
thanks for the fix! is there a way to include the package directly from github:master in my app? or do i need to wait for the next release

**Comment by markhaasjes** [comment]
This fix does not work for custom annotations, can you help me fixing that for those as well?
