### ISSUE TITLE
Example crashes on start (RN 0.17)

### ISSUE THREAD

**Issue by mattiamanzati** [nitaliano/react-native-mapbox-gl#219]
Hi all! I have followed the install instructions but when starting an app with the code copy&pasted from the example, it crashes. Here's the full log:
https://gist.github.com/mattiamanzati/50495fe12ef6f336c4e3
Hope that helps!

**Comment by fxhereng** [comment]
+1 doing the same for me when I upgraded to RN 0.17 and MapBox 3.0.0. (on Android)

**Comment by AidenMontgomery** [comment]
I have found that the annotationImage in the annotations list crashes the app. Removing that from the first annotation in the list means that the example runs.

I am using Genymotion and I have attempted this on the following devices.
- Google Nexus 5 - 5.1.0 - API 22 - 1080x1920 `crashes`
- Google Nexus 10 - 5.1.0 - API 22 - 2560x1600 `works ok`
- Google Nexus 9 - 5.1.0 - API 22 - 2046x1536 `works ok`
- Custom Phone - 5.0.0 - API 21 - 768x1280 `works ok`

When I say that it works ok, it looks like the image is loaded, but it is not being resized based on the settings in the annotationImage property.

I have the following installed
- react-native 0.17.0
- react-native-mapbox-gl 3.0.0

When the application does crash this is the logcat entry

``` bash
F/libc    ( 1938): Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdeadcab1 in tid 1938 (.androidmaptest)
I/DEBUG   (   85): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (   85): Build fingerprint: 'generic/vbox86p/vbox86p:5.1/LMY47D/buildbot11172007:userdebug/test-keys'
I/DEBUG   (   85): Revision: '0'
I/DEBUG   (   85): ABI: 'x86'
I/DEBUG   (   85): pid: 1938, tid: 1938, name: .androidmaptest  >>> com.androidmaptest <<<
I/DEBUG   (   85): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xdeadcab1
I/DEBUG   (   85):     eax df898af0  ebx df9c1b14  ecx df898af0  edx e1876880
I/DEBUG   (   85):     esi e18768b0  edi e0b5c000
I/DEBUG   (   85):     xcs 00000023  xds 0000002b  xes 0000002b  xfs 00000007  xss 0000002b
I/DEBUG   (   85):     eip df898b06  ebp ff9aebe8  esp ff9aebd0  flags 00210296
I/DEBUG   (   85):
I/DEBUG   (   85): backtrace:
I/DEBUG   (   85):     #00 pc 0036eb06  /data/app/com.androidmaptest-1/lib/x86/libmapbox-gl.so
I/DEBUG   (   85):     #01 pc 0036eb45  /data/app/com.androidmaptest-1/lib/x86/libmapbox-gl.so
I/DEBUG   (   85):     #02 pc 0036eae6  /data/app/com.androidmaptest-1/lib/x86/libmapbox-gl.so (std::terminate()+38)
I/DEBUG   (   85):     #03 pc 0036d715  /data/app/com.androidmaptest-1/lib/x86/libmapbox-gl.so
I/DEBUG   (   85):     #04 pc 0036cf26  /data/app/com.androidmaptest-1/lib/x86/libmapbox-gl.so
I/DEBUG   (   85):     #05 pc 0036cea3  /data/app/com.androidmaptest-1/lib/x86/libmapbox-gl.so
I/DEBUG   (   85):     #06 pc 001936b5  /data/app/com.androidmaptest-1/lib/x86/libmapbox-gl.so (mbgl::SpriteImage::SpriteImage(unsigned short, unsigned short, float, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, bool)+357)
I/DEBUG   (   85):     #07 pc 000da474  /data/app/com.androidmaptest-1/lib/x86/libmapbox-gl.so
I/DEBUG   (   85):     #08 pc 00234dd7  /data/dalvik-cache/x86/data@app@com.androidmaptest-1@base.apk@classes.dex
I/DEBUG   (   85):
I/DEBUG   (   85): Tombstone written to: /data/tombstones/tombstone_02
```

This is the marker loaded at the incorrect size
![screenshot-2016-01-08_17 56 04 716](https://cloud.githubusercontent.com/assets/364538/12205419/6e77b6de-b632-11e5-9da8-79b5040535a3.png)

**Comment by dapetcu21** [comment]
This seems related to #234 and has probably been fixed since. Reopen if it still happens.

**Comment by pewh** [comment]
+1 still got same issue, on RNMG latest version and RN 0.39

**EDIT:** working on real device, but crash on genymotion
