### ISSUE TITLE
Set the map view size properly

### ISSUE THREAD

**Issue by bsudekum** [nitaliano/react-native-mapbox-gl#22]
Right now, the `UIView` is set to 100% the height and width. This is accomplished by:

``` obj-c
CGFloat width = [UIScreen mainScreen].bounds.size.width;
CGFloat height = [UIScreen mainScreen].bounds.size.height;
CGRect windowFrame = CGRectMake(0, 0, width, height);

MGLMapView *map = [[RCTMapboxGL alloc] initWithFrame:windowFrame accessToken:@"placeHolder"];
map.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
map.clipsToBounds = YES;
```

> [code](https://github.com/bsudekum/react-native-mapbox-gl/blob/master/RCTMapboxGL/RCTMapboxGLManager.m#L95-L101)

There is an issue with this method: if the map is not set to 100% the screen width and height, **markers and marker popups are shifted by the difference in the screen height and/or width minus the actual screen width and or height**. Example: 
![ios simulator screen shot may 10 2015 10 04 54 am](https://cloud.githubusercontent.com/assets/1058624/7555317/b2136afa-f6fc-11e4-9f34-44a0a6f90961.png)
### Possible Solutions:
1. Wait until the `<MapboxGLView />` has been added, then set the map height and width to this size
2. Listen for resize events, resize the map accordingly
3. Does `UIView` have some sort of `ViewDidLoad` event? Listen for this, get bounds
4. ?

Setting `MGLMapView *map = [[RCTMapboxGL alloc] initWithFrame:self.window.bounds accessToken:@"placeHolder"];` fails with the following error: 

```
Failed: Current draw framebuffer is invalid.
libc++abi.dylib: terminating with uncaught exception of type mbgl::util::ShaderException: Program plain failed to link: Validation Failed: Current draw framebuffer is invalid.
```

**Comment by bsudekum** [comment]
fixed with https://github.com/bsudekum/react-native-mapbox-gl/pull/25

**Comment by 1ec5** [comment]
Just to follow up: there’s no `-[UIView viewDidLoad]` method, but there are `-[UIView didMoveToSuperview]` and `-updateConstraints` that often come in handy.
