### ISSUE TITLE
[Android] setRotateEnabled doesn't work

### ISSUE THREAD

**Issue by christopherdro** [nitaliano/react-native-mapbox-gl#224]
I've spent the last hour trying to debug this issue but have had no luck.

What's strange is the prop gets set correctly and even returns `false` when calling `view.isRotateEnabled()` after the prop has been set. 

@bsudekum Any ideas what might be causing this?

**Comment by bsudekum** [comment]
Confirmed. Took a look at this today, I think this is related to popups not opening and the react main view messing with touch events. I both this issues are attributed to activity not being properly handled in the map view, [example](https://www.mapbox.com/android-sdk/examples/).

**Comment by christopherdro** [comment]
Disabled scroll and zoom seem to work just fine.

Will take a closer look.

**Comment by tobrun** [comment]
I verified this upstream and there `setRotateEnabled(false)` works as designed.

**Comment by dapetcu21** [comment]
Is this still the case after #365? Can you check?

**Comment by tmcw** [comment]
No update, likely that #365 resolved this issue.
