### ISSUE TITLE
Undefined symbols for architecture arm64: "_RCTDefaultLogFunction", referenced from:

### ISSUE THREAD

**Issue by hasen6** [nitaliano/react-native-mapbox-gl#226]
Undefined symbols for architecture arm64:
  "_RCTDefaultLogFunction", referenced from:
      -[bodyfatTests testRendersWelcomeScreen] in bfTests.o
  "_RCTSetLogFunction", referenced from:
      -[bodyfatTests testRendersWelcomeScreen] in bfTests.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by tmcw** [comment]
@hasen6 can you add more information to this ticket: are you running a custom app or the react-native-mapbox-gl example? What version of React-Native and XCode do you use? If you remove the map component, does the error persist?

**Comment by hasen6** [comment]
That was a month and a half ago. I don't remember what it was now.
