### ISSUE TITLE
how to load static asset for annotations

### ISSUE THREAD

**Issue by Georgette** [nitaliano/react-native-mapbox-gl#227]
I tried: 

```
"url": 'image!./assets/marker.png'

```

and 

```
"url": {require('./assets/marker.png')

```

on version 2.1.2 (which it might be that I have to upgrade to another version, that is not 3.0 because I have issues with 3.0), and using RN 0.17.0

**Comment by Georgette** [comment]
I figured this out.

**Comment by rmevans9** [comment]
It might be helpful to comment in the ticket what you had to do to resolve for others

**Comment by Georgette** [comment]
Sure, I didn't add the image to the application image assets. Instructions here on how to do that:

[add image assets](https://developer.apple.com/library/ios/recipes/xcode_help-image_catalog-1.0/chapters/AddingImageSets.html) 

then the proper url would be:

"url": 'image!marker'

where marker (in my case) is the name of the image added to the image sets

**Comment by shravyadalvai** [comment]
how do we load static asset in android

**Comment by maqen** [comment]
Can we open this again for android assets? Don't see anyway this is possible today?
