### ISSUE TITLE
rotating an iOS device resets the map's center and zoom level to 0

### ISSUE THREAD

**Issue by yonahforst** [nitaliano/react-native-mapbox-gl#229]
When I resize the Mapbox component, the map center and zoom level reset to 0. This can also be observed by simply rotating the device.

This issue does not occur on the simulator; the map resizes or rotates as expected, without losing it's center

**Comment by dapetcu21** [comment]
Can you, please check if the same thing happens with 5.0.0?

**Comment by tmcw** [comment]
Closing; no confirmation - @yonahforst please post back if you can confirm that this bug persists post-5.0.0.
