### ISSUE TITLE
Support for raster tiles or third party tiles

### ISSUE THREAD

**Issue by gendronb** [nitaliano/react-native-mapbox-gl#239]
Is it possible to use raster tiles or third party tiles? As mentionned here : https://github.com/mapbox/mapbox-gl-native/issues/2879 (https://www.mapbox.com/ios-sdk/examples/raster-styles/)

**Comment by bsudekum** [comment]
Same answer applies. Try `styleURL={'https://www.mapbox.com/ios-sdk/files/mapbox-raster-v8.json'}`

**Comment by gendronb** [comment]
Thanks @bsudekum.

Works perfectly, and runs much smoother on my old Samsung S3...

**Comment by norbertsongin** [comment]
It has to be URL pointing to json? I need to load style from inside application but it doesn't seem to be working :/
