### ISSUE TITLE
`onOpenAnnotation` callback not implemented on Android

### ISSUE THREAD

**Issue by jsierles** [nitaliano/react-native-mapbox-gl#240]
Are there plans to add this? Or, could you point me in the right direction to where this could be added in the ReactNativeMapboxGLManager? Cheers!

**Comment by bsudekum** [comment]
hey @jsierles , most of this is blocked by https://github.com/mapbox/react-native-mapbox-gl/issues/102

However, it can be implemented beforehand. I think it'd be very similar to the region [move event listener](https://github.com/mapbox/react-native-mapbox-gl/blob/master/android/src/main/java/com/mapbox/reactnativemapboxgl/ReactNativeMapboxGLManager.java#L210)

**Comment by thibthibaut** [comment]
Up! We _really_ need onOpenAnnotation callback for our project. Do you think it will be implemented in the next days ?
btw thank you a lot for you work!
