### ISSUE TITLE
Step4

### ISSUE THREAD

**Issue by rufisayev** [nitaliano/react-native-mapbox-gl#241]
I cannot write Step 4, what can i write in MainActivity.java or how it must be?

**Comment by rufisayev** [comment]
I am speaking from this installation guide https://github.com/mapbox/react-native-mapbox-gl/blob/master/android/install.md

**Comment by bsudekum** [comment]
What version of react-native are you on? For react native 0.18.0, there should be a file at `your-project-name -> android -> app -> src -> main -> java -> com -> your-project-name -> MainActivity.java`

Here you should update the file as outlined in step 4.

**Comment by rufisayev** [comment]
Yes I use react native 0.18.0 version but my question is,should i replace my default MainActivity.java code with this(which describe in step 4):
My default MainActivity.java:

package com.testmap;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;

import java.util.Arrays;
import java.util.List;

public class MainActivity extends ReactActivity {

```
/**
 * Returns the name of the main component registered from JavaScript.
 * This is used to schedule rendering of the component.
 */
@Override
protected String getMainComponentName() {
    return "testMap";
}

/**
 * Returns whether dev mode should be enabled.
 * This enables e.g. the dev menu.
 */
@Override
protected boolean getUseDeveloperSupport() {
    return BuildConfig.DEBUG;
}
```

   /**
- A list of packages used by the app. If the app uses additional views
- or modules besides the default ones, add more packages here.
  */
  @Override
  protected List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
      new MainReactPackage());
  }
  }

And how can i change this in step 4?

**Comment by bsudekum** [comment]
Sorry that was a typo, I'm running 0.17.0 - 0.18.0 is not yet supported since it's currently in pre-release. You'll have to install 0.17.0 to get this to work.
