### ISSUE TITLE
How to retreive the viewport or bounding coordinates?

### ISSUE THREAD

**Issue by bartonhammond** [nitaliano/react-native-mapbox-gl#245]
Is it possible to know what the viewport or bounding coordinates are?  

I am loading all annotations for the world, which takes a long time.  But only a segment are displayed given the centerCoordinate and zoom level. 

Is there a way to obtain or calculate the boundary points of the view?  If so, I could load only those annotations that would appear within.

**Comment by bartonhammond** [comment]
I used `geoViewPort` along with `react-native-orientation` to determine the bounds and then filter the annotations that were within.

**Comment by gravitinos** [comment]
for anyone looking here you can do this a little easier by setting a ref to the map, then calling `this.map.getBounds(callback => doThings)`
