### ISSUE TITLE
Content inset

### ISSUE THREAD

**Issue by 1ec5** [nitaliano/react-native-mapbox-gl#247]
Once mapbox/mapbox-gl-native#3583 makes it into a prerelease, RNMBGL should expose MGLMapView’s `contentInset` property, which is useful for shifting the map view’s center to account for translucent top or bottom bars. MGLMapView [automatically insets the content](https://github.com/mapbox/mapbox-gl-native/blob/8dfba0ef0b92c9ec3f84a4263b96e4e35c8fab30/platform/ios/src/MGLMapView.mm#L777-L817) if the containing view controller has top and bottom Auto Layout guides, but React Native co-opts Auto Layout for its own layout system, so most likely RNMBGL will have to detect the top and bottom bars manually.

/cc @bsudekum

**Comment by bsudekum** [comment]
This is done
