### ISSUE TITLE
Can't get iOS running through CocoaPods or Manually with react-native init Project

### ISSUE THREAD

**Issue by jordangarside** [nitaliano/react-native-mapbox-gl#251]
I can't seem to get the map running in iOS by following either setup guide, everything is working great for Android.

---

If I try to do the installation manually then nothing renders (tested on simulator and device), but I don't get any errors.
This is what it looks like:
<img width="319" alt="screenshot 2016-01-19 20 45 56" src="https://cloud.githubusercontent.com/assets/6321824/12440185/bbf2eaa0-beed-11e5-87f4-cb758f4d4a90.png">

DemoMap is the container for the Mapbox component, and works in Android.
Also, if I attach a function to ref on the Mapbox component it does trigger.

---

If I try to do the installation with CocoaPods then I get an error saying:

```
ld: library not found for -lPods
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

---

I've tried this like 5 times now following the instructions for both and can't get either one to work. I have very little Xcode experience, but I did follow each step in the installation instructions.
The project was created with `react-native init` recently. I have also tried it with completely new projects and the same things happen.
Node 4.2.3
react-native-mapbox-gl 3.1.1
react-native 0.18.8
Xcode 7.2
CocoaPods 0.39.0

**Comment by jordangarside** [comment]
I got past the CocoaPods problem by installing the latest Ruby and Reinstalling CocoaPods.
Although, now it's giving me the known error [here](https://github.com/mapbox/react-native-mapbox-gl/issues/212) which I can't fix because removing `-ObjC` flag breaks my iOS app.

Still not sure why manually installing the packages doesn't work, I may try again now with the new Pods installed.

**Comment by AgtLucas** [comment]
@jordangarside Good to know!

**Comment by tharrington** [comment]
@jordangarside did you figure out this issue?

**Comment by jordangarside** [comment]
@tharrington I gave up installing this with CocoaPods, I think you're better off doing it manually
