### ISSUE TITLE
Documentation setup development environement

### ISSUE THREAD

**Issue by tobrun** [nitaliano/react-native-mapbox-gl#252]
Currently this repo exposes documentation on how to use the library as a dependency but it doesn't expose documentation for setting up a development enviroment to contribute to this repo. An example of this type of documentation can be found in the [GL-repo](https://github.com/mapbox/mapbox-gl-native/blob/master/INSTALL.md). 

cc @bsudekum

**Comment by bsudekum** [comment]
done in https://github.com/mapbox/react-native-mapbox-gl/pull/253
