### ISSUE TITLE
ld: library not found for -lMapbox

### ISSUE THREAD

**Issue by meafmira** [nitaliano/react-native-mapbox-gl#255]
After install I got an error:
ld: library not found for -lMapbox
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by edward-at-intelex** [comment]
Hi everyone, I am getting this issue  right now. Followed the instructions to a T. any advice?

**Comment by rsimbu89** [comment]
I'm also getting this error while make Production build
