### ISSUE TITLE
Get annotation bounds

### ISSUE THREAD

**Issue by rajkissu** [nitaliano/react-native-mapbox-gl#257]
Is there a way to retrieve the bounds of a polyline/polygon/group of markers - kinda like how Leaflet does with getBounds?

E.g:

```
// create a red polyline from an array of LatLng points
const polyline = L.polyline(latlngs, {color: 'red'}).addTo(map)

// zoom the map to the polyline
map.fitBounds(polyline.getBounds())
```

**Comment by bsudekum** [comment]
I don't think this will be added as there is no native method for this. What you could do is use something like [bound-points](https://www.npmjs.com/package/bound-points) on your added polyline.
