### ISSUE TITLE
Clustering

### ISSUE THREAD

**Issue by maqen** [nitaliano/react-native-mapbox-gl#258]
Now that JS SDK has gotten clustering support [#1931](https://github.com/mapbox/mapbox-gl-js/pull/1931) what needs to happen to get this on react native version?

As this is built upon native sdk:s guess something similar needs to be added to those projects.

**Comment by bsudekum** [comment]
It first have to be supported in mapbox-gl-native.

**Comment by ptomasroos** [comment]
Any news on this?

**Comment by bcalik** [comment]
Looks like mapbox-gl-native now supports clustering. It is about to be merged @bsudekum 
https://github.com/mapbox/mapbox-gl-native/pull/5724

Reopen this please.

**Comment by ptomasroos** [comment]
Great work!

**Comment by ouya99** [comment]
@ptomasroos: is it merged?

**Comment by ptomasroos** [comment]
@java99 nope just happy it landed in mapbox-gl-native

**Comment by ouya99** [comment]
So how to Import it to react native Maps?

Am 31.08.2016 10:27 vorm. schrieb "Tomas Roos" notifications@github.com:
