### ISSUE TITLE
No Mapbox.framework after installing

### ISSUE THREAD

**Issue by dikuye** [nitaliano/react-native-mapbox-gl#263]
I'm trying to install Mapbox manually for iOS as described on this page:
https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/install.md

However, I can't find 'node_modules/react-native-mapbox-gl/ios/Mapbox.framework'

I've created several new react-native projects and ran 'npm install react-native-mapbox-gl --save' but it never appeared.

react-native 0.18.0
react-native-mapbox-gl 3.1.1

**Comment by bsudekum** [comment]
The readme and what is published are not in sync currently, I still have to do a new release. See for https://github.com/mapbox/react-native-mapbox-gl/blob/2a20b5b059129e1856c4c828b5b1056963102f59/ios/install.md

**Comment by dikuye** [comment]
I'm not quite sure if I'm doing something wrong - but the link that you posted still shows to add node_modules/react-native-mapbox-gl/ios/Mapbox.framework to Embedded Libraries.

**Comment by bsudekum** [comment]
Sorry my mistake, did not go back far enough. Here is what you're looking for: https://github.com/mapbox/react-native-mapbox-gl/blob/0a0c4ad82a8c7e51e1d4b6d6a9c1811b31196139/ios/install.md

**Comment by dominicmh** [comment]
I had the same problem.
When following your linked readme I can't find `Mapbox.bundle` as described in step 5.

**Comment by pppluto** [comment]
same problem here. no mapboxframework and mapbox.bundle

**Comment by jayfunk** [comment]
Can you show what is in your node_modules/react-native-mapbox-gl/ios
directory?

**Comment by mmelchio** [comment]
@jayfunk 
API.md
example.js
install-cocoapods.md
install.md

RCTMapboxGL (folder)
-RCTMapboxGL.h
-RCTMapboxGL.m
-RCTMapboxGLManager.h
-RCTMapboxGLManager.m

RCTMapboxGL.podspec
RCTMapboxGL.xcodeproj

RCTMapboxGLTests (folder)
-Info.plist

**Comment by jayfunk** [comment]
Have you tried using a newer release of react-native-mapbox-gl? I have not run into this issue with all the versions I have used thus far. I am currently on 4.1.0.

**Comment by pppluto** [comment]
sorry for delay.for me just re-install the module and fixed this problem. thank you very much @jayfunk  :beers:

**Comment by ghost** [comment]
Same problem for me :( Any Fix?

**Comment by Taakn** [comment]
Same problem

**Comment by jayfunk** [comment]
See MrPluto's answer. For some reason this package is downloaded without all the necessary files. Try deleting it and re-installing the package. If that doesn't work you may want to try clearing your local npm cache and doing another install (Be careful of doing this as you may have to re-build a very large cache).
