### ISSUE TITLE
Map is black in Android simulator

### ISSUE THREAD

**Issue by btmcnellis** [nitaliano/react-native-mapbox-gl#264]
The map is not rendering correctly when running in the Android simulator in Genymotion. When following the example code exactly, the Text views all render, and there's a black box with the Mapbox logo in the right place, but the map itself is just black. I've tried uninstalling and reinstalling everything multiple times, following the instructions exactly, I've tried different API access tokens and different Mapbox-hosted styles, and I've tried both the example code on here and from example.js in node_modules.

I've tried everything I can think of and searched time and time again but I can't figure out the solution.

I'm using React Native 0.19.0 and react-native-mapbox-gl version 3.1.1. 

Here's a screenshot of what it looks like:

![screenshot 2016-02-01 12 23 13](https://cloud.githubusercontent.com/assets/7916026/12725040/aeb45c3e-c8de-11e5-9786-4a217b7a16f0.png)

And here's my code (access token and other specific information removed):

```
'use strict';

var React = require('react-native');
var Mapbox = require('react-native-mapbox-gl');
var {
  AppRegistry,
  StyleSheet,
  View,
  Text
} = React;
var mapRef = 'map';

var MapExample = React.createClass({
  mixins: [Mapbox.Mixin],
  getInitialState() {
    return {
      center: {
        latitude: 40.7223,
        longitude: -73.9878
      },
      annotations: [{
        coordinates: [40.7223, -73.9878],
        type: 'point',
        title: 'Important!',
        subtitle: 'Neat, this is a custom annotation image',
        id: 'marker2',
        annotationImage: {
          url: 'https://cldup.com/7NLZklp8zS.png',
          height: 25,
          width: 25
        }
      }, {
        coordinates: [40.7923, -73.9178],
        type: 'point',
        title: 'Important!',
        subtitle: 'Neat, this is a custom annotation image'
      }, {
        coordinates: [[40.76572150042782,-73.99429321289062],[40.743485405490695, -74.00218963623047],[40.728266950429735,-74.00218963623047],[40.728266950429735,-73.99154663085938],[40.73633186448861,-73.98983001708984],[40.74465591168391,-73.98914337158203],[40.749337730454826,-73.9870834350586]],
        type: 'polyline',
        strokeColor: '#00FB00',
        strokeWidth: 3,
        alpha: 0.5,
        id: 'foobar'
      }, {
        coordinates: [[40.749857912194386, -73.96820068359375], [40.741924698522055,-73.9735221862793], [40.735681504432264,-73.97523880004883], [40.7315190495212,-73.97438049316406], [40.729177554196376,-73.97180557250975], [40.72345355209305,-73.97438049316406], [40.719290332250544,-73.97455215454102], [40.71369559554873,-73.97729873657227], [40.71200407096382,-73.97850036621094], [40.71031250340588,-73.98691177368163], [40.71031250340588,-73.99154663085938]],
        type: 'polygon',
        alpha:1,
        fillColor: '#FFFFFF',
        strokeColor: '#FFFFFF',
        strokeWidth: 1,
        id: 'zap'
      }]
    }
  },
  onUserLocationChange(location) {
    console.log(location);
  },
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.text} onPress={() => this.setDirectionAnimated(mapRef, 0)}>
          Set direction to 0
        </Text>
        <Text style={styles.text} onPress={() => this.setCenterCoordinateAnimated(mapRef, 40.68454331694491, -73.93592834472656)}>
          Go to New York at current zoom level
        </Text>
        <Text style={styles.text} onPress={() => this.setCenterCoordinateZoomLevelAnimated(mapRef, 35.68829, 139.77492, 14)}>
          Go to Tokyo at fixed zoom level 14
        </Text>
        <Text style={styles.text} onPress={() => this.addAnnotations(mapRef, [{
          coordinates: [40.73312,-73.989],
          type: 'point',
          title: 'This is a new marker',
          id: 'foo'
        }, {
          'coordinates': [[40.75974059207392, -74.02484893798828], [40.68454331694491, -73.93592834472656]],
          'type': 'polyline'
        }])}>
          Add new marker
        </Text>
        <Text style={styles.text} onPress={() => this.setUserTrackingMode(mapRef, this.userTrackingMode.follow)}>
          Set userTrackingMode to follow
        </Text>
        <Text style={styles.text} onPress={() => this.removeAllAnnotations(mapRef)}>
          Remove all annotations
        </Text>
        <Text style={styles.text} onPress={() => this.setTilt(mapRef, 50)}>
          Set tilt to 50
        </Text>
        <Text style={styles.text} onPress={() => this.setVisibleCoordinateBoundsAnimated(mapRef, 40.712, -74.227, 40.774, -74.125, 100, 100, 100, 100)}>
          Set visible bounds to 40.7, -74.2, 40.7, -74.1
        </Text>
        <Text style={styles.text} onPress={() => {
            this.getDirection(mapRef, (direction)=>{
             console.log(direction);
           })
          }}>
          Get direction
        </Text>
        <Text style={styles.text} onPress={() => {
            this.getCenterCoordinateZoomLevel(mapRef, (location)=>{
             console.log(location);
           })
          }}>
          Get location
        </Text>
        <Mapbox
          annotations={this.state.annotations}
          accessToken={'my-access-token'}
          centerCoordinate={this.state.center}
          debugActive={false}
          direction={10}
          ref={mapRef}
          onRegionChange={this.onRegionChange}
          rotateEnabled={true}
          scrollEnabled={true}
          style={styles.map}
          showsUserLocation={true}
          styleUrl={'mapbox://styles/user/style-id'}
          userTrackingMode={this.userTrackingMode.none}
          zoomEnabled={true}
          zoomLevel={10}
          compassIsHidden={true}
          onUserLocationChange={this.onUserLocationChange}
        />
      </View>
    );
  }
});

var styles = StyleSheet.create({
  container: {
    flex: 1
  },
  text: {
    padding: 3,
    marginLeft: 5
  },
  map: {
    flex: 1
  }
});

AppRegistry.registerComponent('my-app-name', () => MapExample);
```

**Comment by bsudekum** [comment]
This looks like an access token issue. Can you see if there are any errors in your logs?

**Comment by btmcnellis** [comment]
Perhaps I'm looking in the wrong place, but there are no relevant logs (just the standard startup output) in either the Chrome Debugger or when running `adb logcat *:S ReactNative:V ReactNativeJS:V`.

I tried multiple access tokens, some with all scopes selected, some with none, and some in between, and the results haven't changed.

~~Edit: Looking at the full logs with `adb logcat`, I don't see anything related to a Mapbox token, but I'm attaching the logs just in case.~~

Edit: Somehow I missed the second-to-last line where it says "{Map}[Setup]: loading style failed: HTTP status code 401." This occurs with both my own styles and `this.mapStyles.emerald`.

[android.txt](https://github.com/mapbox/react-native-mapbox-gl/files/113080/android.txt)

**Comment by btmcnellis** [comment]
On further testing, I don't think that this is an issue with my access token. It works correctly with Mapbox GL JS in a browser and other Mapbox services; it seems that react-native-mapbox-gl is the problem.

Combined with https://github.com/mapbox/react-native-mapbox-gl/issues/266, it looks to me like something is broken when this is used with React Native 0.19.0.

**Comment by mattiamanzati** [comment]
Same problem and error log here! :/

**Comment by bsudekum** [comment]
Replicated. Getting: 

```
02-03 21:42:40.199 2512-3578/com.testbed19 D/: HostConnection::get() New Host Connection established 0xe4569790, tid 3578
02-03 21:42:40.398 2512-2564/com.testbed19 D/com.mapbox.mapboxsdk.http.HTTPContext$HTTPRequest: [HTTP] Request with response code = 401: Unauthorized
02-03 21:42:40.592 2512-3578/com.testbed19 E/mbgl: {Map}[Setup]: loading style failed: HTTP status code 401
```

@bleege @zugaldia have you seen this recently? running v3.2.0

**Comment by bleege** [comment]
@bsudekum Yep, the HTTP 401 would indicate that it's an access token issue.  I'm not sure how the React Native binding sets and stores this value however.  The underlying Mapbox Android SDK doesn't have this issue.

**Comment by JonnyBGod** [comment]
Getting same behaviour on Android device. Same logs as @bsudekum .

**Comment by bsudekum** [comment]
I'm thinking the access token `prop` is not being properly set.

**Comment by jordangarside** [comment]
Getting the same issue on React-Native 0.19.0 and MapboxGL 3.2.0,
Was working correctly with React-Native 0.18.0 and MapboxGL 3.1

**Comment by bsudekum** [comment]
Something has changed rn v0.19.0. All props are currently ignored not just `accessToken`.

**Comment by ghost** [comment]
I believe it has to do with them moving `ReactProp` to another package because I had to update some my own code. I don't remember exactly but try changing `...ui.ReactProp` to `...ui.annotation.ReactProp`?

**Comment by mmelchio** [comment]
I also had blackscreens on my testing device (Xperia z3)
What fixed it for me was: I checked that the timezone and time is being synced with the network. I don't know why, but since then I have no blackscreens anymore.
Also check your access token and style url.
