### ISSUE TITLE
Developing custom map applications in React Native

### ISSUE THREAD

**Issue by ebrehault** [nitaliano/react-native-mapbox-gl#271]
Right now, there is no API to handle simple things like handling the click on a marker, displaying a popup, letting the user move a marker on the map, etc.

Can we imagine it will be possible in the future or will React Native Mapbox GL is just supposed to be a MapboxGL viewer?

**Comment by bsudekum** [comment]
@ebrehault is this in reference to iOS or Android? iOS has all these features minus dragging and on Android these are coming. 

Ref [iOS docs](https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/API.md) and [Android docs](https://github.com/mapbox/react-native-mapbox-gl/blob/master/android/API.md)

**Comment by ebrehault** [comment]
@bsudekum yes sorry I was refering to Android.
Good to hear those features are coming :)

**Comment by tmcw** [comment]
Closing; individual tickets will track the requested features.
