### ISSUE TITLE
StyleUrl is inconsistent on Android and iOS (styleURL vs styleUrl)

### ISSUE THREAD

**Issue by jordangarside** [nitaliano/react-native-mapbox-gl#273]
So...
It appears that sometime recently iOS started using `styleURL` while Android and iOS I believe were previously both using `styleUrl`.
Not sure if Android is still using the latter version, but the current examples on the README demonstrate the inconsistency.

Don't think the inconsistency is intentional, but it led me to about an hour or so of testing.
I couldn't figure out why my map was a blank white screen in iOS.

Thanks, keep up the good work.

**Comment by tmcw** [comment]
Yep, thanks for the report @jordangarside this is definitely a bug. Working on a PR now.
