### ISSUE TITLE
Are YES/NO equivalent to bool?

### ISSUE THREAD

**Issue by tmcw** [nitaliano/react-native-mapbox-gl#277]
For this code: https://github.com/mapbox/react-native-mapbox-gl/blob/44311c6ec7a02c39cbaea4a5f242252f965813f8/ios/RCTMapboxGL/RCTMapboxGL.m#L350-L358

``` objc
- (BOOL)mapView:(RCTMapboxGL *)mapView annotationCanShowCallout:(id <MGLAnnotation>)annotation {
    NSString *title = [(RCTMGLAnnotation *) annotation title];
    NSString *subtitle = [(RCTMGLAnnotation *) annotation subtitle];
    if ([title length] != 0 || [subtitle length] != 0 ) {
        return YES;
    } else {
        return NO;
    }
}
```

This would be refactored to 

``` objc
- (BOOL)mapView:(RCTMapboxGL *)mapView annotationCanShowCallout:(id <MGLAnnotation>)annotation {
    NSString *title = [(RCTMGLAnnotation *) annotation title];
    NSString *subtitle = [(RCTMGLAnnotation *) annotation subtitle];
    return ([title length] != 0 || [subtitle length] != 0);
}
```

In JavaScript-land - the original code is a symptom of the "not expecting the results of boolean operations to be values" misunderstanding in JS. Does the same rule apply to objcland? @1ec5 @bsudekum ?

**Comment by 1ec5** [comment]
You’re correct, this code can be condensed into a single return statement. Unlike in JavaScript, any non-Boolean value in Objective-C (C, really) is automatically cast into a Boolean value when used as a Boolean.

You could get even more condensed:

``` objc
return title.length || subtitle.length;
```
