### ISSUE TITLE
Rotation for custom marker image

### ISSUE THREAD

**Issue by aksonov** [nitaliano/react-native-mapbox-gl#279]
Any documentation for it? All I see is example polygon and custom image. Could i pass react native view or something like that?

**Comment by tmcw** [comment]
You can add lines, polygons, and image-based markers to the map. Sorry, passing react native views is not supported.

**Comment by aksonov** [comment]
@tmcw thanks, is it possible to rotate custom image? Would you accept PR to allow set angle for image?

**Comment by tmcw** [comment]
@bsudekum rotation of point annotations would be possible if we exposed the underlying gl-native method, right?

**Comment by aksonov** [comment]
Looks like I need to change `- (MGLAnnotationImage *)mapView:(MGLMapView *)mapView imageForAnnotation:(id<MGLAnnotation>)annotation`

`image = [UIImage imageNamed:localImagePath];`

rotate that image if not 'image!' prefix passed but something like 'rotatedImage!_degree_!

**Comment by aksonov** [comment]
RCTMapBoxGL.m  file

**Comment by aksonov** [comment]
I've added PR for this.
