### ISSUE TITLE
Send fucntions from js to obj c land

### ISSUE THREAD

**Issue by bsudekum** [nitaliano/react-native-mapbox-gl#28]
So events can happen without having to redraw the view:
- `resetNorth()`
- [`setCenterCoordinate:animated`](https://www.mapbox.com/mapbox-gl-ios/api/Classes/MGLMapView.html#//api/name/setCenterCoordinate:animated:)

**Comment by bsudekum** [comment]
hey @brentvatne, I'm working on sending functions from JS to objective c and I was wondering if you could answer some questions for me.

I attempted to add a `resetNorth()` function in this commit: https://github.com/bsudekum/react-native-mapbox-gl/commit/e16211f1cf01467b0a290f8c11d323d875f6fb45. But for some reason, when [resetNorth is called](https://github.com/bsudekum/react-native-mapbox-gl/commit/e16211f1cf01467b0a290f8c11d323d875f6fb45#diff-bea3f6469d29a272c0cf23632fe64853R92), `_map` is `null` so nothings happens. One issue I'm seeing is that I'm mixing the `RCTBridgeModule` with the `RCTViewManager` which is something I have not seen done anywhere. 

Also note, I could not call `NativeModules.MapboxGL.resetNorth();` on any other 'NativeModule' object. 

I've also tried to subclass `RCTBridgeModule` in `RCTMapboxGLManager` but the problem here is there is no map object to `resetNorth` on.

Have any thoughts on how to best implement this?

**Comment by brentvatne** [comment]
I think what we want to do here is something similar to this:
https://github.com/brentvatne/react-native-video/commit/8e2deae1c0112601eda72c9f2a3cbf59515091b6

Then we can call functions on it directly, which just use `setNativeProps`:
https://github.com/brentvatne/react-native-video/commit/5e4d55a4005671532e299fbae5ea8fb5467eed16#diff-7ed13e9e797b0601fefe21a55e08f460R82

**Comment by bsudekum** [comment]
@brentvatne I'm not sure this solves the problem. Your example is modifying props but I'd like actually  call a function in obj c.

Let's take the [`setCenterCoordinate:animated`](https://www.mapbox.com/mapbox-gl-ios/api/Classes/MGLMapView.html#//api/name/setCenterCoordinate:animated:) function for example. With your method, we'd be resetting the `centerCoordinate` each time the center needed to change causing a not so pleasing redraw.

Instead, if you use the `setCenterCoordinate:animated` directly, the map will animate the move to the new coordinates. I'm not sure this can happen by solely modifying props.

**Comment by brentvatne** [comment]
@bsudekum - another approach that could work is something like what is done in Libraries/Animation/RCTAnimationExperimentalManager.m - in particular, `startAnimation` - notice how you pass in a reactTag and then grab the view that it represents from the `viewRegistry`\- you could do this same thing for direct function calls :smile:

**Comment by bsudekum** [comment]
@brentvatne nice I got it working with `viewRegistry`! It seems a little hacky, do you think this is best way to do this?

One issue I'm seeing is that `AnimationUtils.allocateTag()` is returning the main `RCTRootContentView` tag instead of the `RCTMapboxGL` view tag. Because of this, I'm thinking that I will loop over `viewRegistry`, check if it's of type RCTMapboxGL and then call resetNorth on it. If someone has multiple maps on the same page, all maps will resetNorth. Is there a way for me to send the correct RCTMapboxGL tag to obj c?

**Comment by brentvatne** [comment]
I don't think you need to use `AnimationUtils.allocateTag()` at all, just pass in the `nodeHandle` - [like this](https://github.com/facebook/react-native/blob/master/Libraries/Animation/AnimationExperimental.js#L51) and grab the view from that :smile:

**Comment by bsudekum** [comment]
:+1: rad

**Comment by bsudekum** [comment]
@brentvatne made some progress on this! How do you feel about exposing the functions to the user via mixins? I've got this working here: https://github.com/bsudekum/react-native-mapbox-gl/blob/add-events/RCTMapboxGL.ios.js#L7-L14

Notice how I'm requiring that you pass in a `ref`. This makes sure that action is happening on the correct map view. Here is an example of how it would be consumed:

``` jsx
var map = React.createClass({
   mixins: [MapboxGLMap.Mixin],
   render: function() {
     var mapRef = 'mapRef';
     return (
       <View style={styles.container}>
         <Text onPress={() => this.resetNorth(mapRef)}>
          Reset North
        </Text>
        <Text onPress={() => this.setCenterCoordinateAnimated(mapRef, 0, 0, 0)}>
         Zoom to 0,0
       </Text>
        <MapboxGLMap
          style={styles.map}
          direction={40}
          ref={mapRef}
          accessToken={'foo'}
          styleURL={'asset://styles/mapbox-streets-v7.json'}
          centerCoordinate={20, 20}
          zoomLevel={10} />
       </View>
     );
   }
 });
```

What do you think? Is this the best way to implement this?

**Comment by brentvatne** [comment]
It might be simpler to call it directly on the ref, eg:

```
 <Text onPress={() => this.refs.map.setCenterCoordinateAnimated(0, 0, 0)}>
    Zoom to 0,0
 </Text>
```

Just define those functions on the map component and have them call the native module :smile:

**Comment by bsudekum** [comment]
@brentvatne interesting. The only problem I'm seeing with this is that I still need to pass in a `ref` to the native function https://github.com/bsudekum/react-native-mapbox-gl/blob/add-events/RCTMapboxGL.ios.js#L9 (first argument here). There a way to get the ref which called `setCenterCoordinateAnimated` in `RCTMapboxGL.ios.js`?

**Comment by brentvatne** [comment]
@bsudekum - I believe you could just pass in `this` in that case

**Comment by bsudekum** [comment]
done!

**Comment by bsudekum** [comment]
Thanks for your help @brentvatne

**Comment by brentvatne** [comment]
Awesome! no problem @bsudekum - I'm looking forward to getting the chance to use this :smile:
