### ISSUE TITLE
Is it possible to add map layer containing custom data?

### ISSUE THREAD

**Issue by lincoln310** [nitaliano/react-native-mapbox-gl#284]
Hi, we have a feature to display our indoor map (served on our geoserver).
It is very easy to do this in mapbox.js or leaflet or openlayer, but how to do this in sdk?

**Comment by lincoln310** [comment]
Hi, i found that the custom data can be set in [styles](https://www.mapbox.com/mapbox-gl-style-spec/#sources).
I will try it!

**Comment by bsudekum** [comment]
Yep, you can create the style in [Mapbox Studio](mapbox.com/studio/), then add the style via the `styleURL` prop.
