### ISSUE TITLE
Cache title already loaded

### ISSUE THREAD

**Issue by vinhtq** [nitaliano/react-native-mapbox-gl#285]
I made a demo and use it on the phone.

The problem I have is that the tiles which were already loaded when i navigate to it instead
display that tiles instantly it displays blank tiles a moment before.

Can i have option like: cached or preload for the map?

**Comment by bsudekum** [comment]
See the new offline documentation https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/API.md#offline
