### ISSUE TITLE
Current version now only works for iOS 8 and above, support iOS 7

### ISSUE THREAD

**Issue by notj** [nitaliano/react-native-mapbox-gl#287]
Support for iOS 7 can be done by downloading the [whole build](https://mapbox.s3.amazonaws.com/mapbox-gl-native/ios/builds/mapbox-ios-sdk-3.1.1.zip) instead of the dynamic one, and adding another option for installing the static files– maybe copy instructions from [mapbox-gl-native](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/INSTALL.md).

**Comment by bsudekum** [comment]
As you pointed out in your comment, you can still build for iOS 7 by downloading the whole build. To keep installs easy and consistent, I've chosen to use the dynamic lib offering Mapbox-gl-native has (which is where the ios8+ requirement is derived). I think for devs who do need iOS 7 however a note on how to install via downloading the whole bundle is a good middle ground (you will be on your own on this adventure however).

**Comment by jeveloper** [comment]
I would suggest that you don't need to bother with IOS7, we're almost close to IOS10 
:)

**Comment by bsudekum** [comment]
We're going to stick with iOS 8+
