### ISSUE TITLE
Building from source instructions?

### ISSUE THREAD

**Issue by tmcw** [nitaliano/react-native-mapbox-gl#290]
There are installation instructions in this repo, but no instructions for building from source afaik

**Comment by tmcw** [comment]
More specifically, I'm trying to test https://github.com/mapbox/react-native-mapbox-gl/pull/282 and can't figure out how to produce the required `libRCTMapboxGL.a` file.

**Comment by dapetcu21** [comment]
Is this still the case or are instructions in CONTRIBUTING.md enough documentation? Should I close this?

**Comment by tmcw** [comment]
The CONTRIBUTING.md docs are great.
