### ISSUE TITLE
fillAlpha does not appear to effect transparency

### ISSUE THREAD

**Issue by jayfunk** [nitaliano/react-native-mapbox-gl#292]
I have been messing around with annotations and it appears the fillAlpha does not effect the transparency. Am I using it correctly? [Here](https://github.com/jayfunk/pocketguide/blob/master/src/data/annotationsMapData.json) is the annotation data that I am using in my map. No matter if I use 0 or 1 the fill is fully transparent. I am testing this with android.

**Comment by dapetcu21** [comment]
`fillAlpha` is implemented as `alpha` on Android, for some reason. I'll open a more general issue to track parity between platforms with regards to annotations.

**Comment by dapetcu21** [comment]
Now tracking this in #380
