### ISSUE TITLE
change ios markers

### ISSUE THREAD

**Issue by texas697** [nitaliano/react-native-mapbox-gl#295]
how can i change the red location markers with the blue polyline ? I saw a previous post about the user location animated blue dot image but not sure if it applies to this.

**Comment by jayfunk** [comment]
Are you wanting to change the pin image? If so see [annotation api](https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/API.md#annotations). See the annotation image example block.

**Comment by dapetcu21** [comment]
Since the question has been answered, I'm closing this. Btw, meanwhile, the annotations API has moved [here](https://github.com/mapbox/react-native-mapbox-gl/blob/master/API.md#annotations)
