### ISSUE TITLE
Incompatible block pointer types sending 'void 

### ISSUE THREAD

**Issue by symmetriccurve** [nitaliano/react-native-mapbox-gl#296]
I switched the export version and ended with this error.

(^)(RCTUIManager *__strong, NSDictionary *__strong)' to parameter of type 'RCTViewManagerUIBlock' (aka 'void (^)(RCTUIManager *__strong, RCTSparseArray *__strong)')

**Comment by bsudekum** [comment]
What versions are you using?

**Comment by bsudekum** [comment]
Re-open with more information if you continue to see this.
