### ISSUE TITLE
Fix exporting style

### ISSUE THREAD

**Issue by tmcw** [nitaliano/react-native-mapbox-gl#304]
A general 'desired refactoring backlog'

**Stop calling the map Mapbox**

We do this in example https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/example.js#L157 - we shouldn't. Mapbox is not a map view. Call this a map view.

**Stop abusing mixins**

There's no sense in throwing [random values into a mixin just to get them to a component](https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/example.js#L166): stop doing that.

**Make annotations and other APIs idempotent**

We [pass an annotations prop to the map view](https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/example.js#L172) but then [call methods that changes it in place](https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/example.js#L116). This goes against the flow of React in general: props and state should define the application, not imperative function calls.

Strawman example of how we might structure our exports:

``` js
var { MapView, mapStyles } = require('react-native-mapbox-gl');
```

cc @bsudekum

**Comment by bsudekum** [comment]
These are all great points

**Comment by dapetcu21** [comment]
I'm currently implementing a few of these suggestions in #365

**Comment by tmcw** [comment]
#365 resolves this issue afaik, thanks @dapetcu21 !
