### ISSUE TITLE
add geojson example

### ISSUE THREAD

**Issue by bsudekum** [nitaliano/react-native-mapbox-gl#31]

**Comment by ericflo** [comment]
Is this possible right now, or will it need changes in the underlying component implementation?

Context: Trying to port this from the web to use react-native-mapbox-gl on mobile https://gyrosco.pe/aprilzero/sport/4195dfba-f5f3-11e4-8c18-0e7d76e55171/

**Comment by bsudekum** [comment]
I have not tested it, but I'm thinking some underlying changes will need to be made. It's definitely on my radar.

**Comment by bsudekum** [comment]
Per chat this morning with @1ec5, geojson is supported but only points. Line/polygon work is happening [here](https://github.com/mapbox/mapbox-gl-native/issues/893) and slated for beta 2, ~2-3 weeks.

**Comment by ericflo** [comment]
Thanks for the update!

**Comment by bsudekum** [comment]
I've got a branch of shapes working here: https://github.com/bsudekum/react-native-mapbox-gl/commit/723d4183c0c1659ece6258e565c427adde52151b. Still some design choices to make.

**Comment by bsudekum** [comment]
@ericflo 1.0.0 now supports polyline/polygons on both android and ios https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/example.js

**Comment by bartonhammond** [comment]
Excuse me, I'm new at all this.

I created a GeoJson file which validates [http://geojsonlint.com/](http://geojsonlint.com/).  I don't see in the example mentioned by @bsudekum that GeoJson is being utilized.  I see there is a Polygon but that's not GeoJson.  

Are you saying that we have to mung the GeoJson in to Annotations?

Pardon my confusion...
