### ISSUE TITLE
[Android] GPS is still on after component is unmounted.

### ISSUE THREAD

**Issue by tyao1** [nitaliano/react-native-mapbox-gl#310]
After the mapview with showsUserLocation set to true is mounted, the gps will be working forever until application is closed. Shouldn't it stop after component is unmounted?

**Comment by salttis** [comment]
Also if you pass a function to `onRegionChange`, it will continue to use the GPS. :hankey:

**Comment by dapetcu21** [comment]
Can you confirm this still happens in 5.0.0?

**Comment by jayfunk** [comment]
I just tested this in 5.0.0. I was experiencing this in 4.2.1, but it seems your refactors resolved this issue. I would recommend closing this issue.

**Comment by tmcw** [comment]
👍 Closing, as it's fixed by @dapetcu21's excellent work.
