### ISSUE TITLE
Directions from mapbox-sdk-js

### ISSUE THREAD

**Issue by julioahurtado** [nitaliano/react-native-mapbox-gl#311]
When trying to use the mapbox-sdk-js for directions I get the error 

> Requiring unknown module "assert". If you are sure the module is there, try restarting the packager.

I then installed the package it wanted using `npm install --save assert` it then proceeded to give me the error.

> when.lift is not a function.

It seems that this error was encountered in #111 but an actual solution was never found.

**Comment by tmcw** [comment]
@julioahurtado I ran into this error a few days ago, ticketed it https://github.com/mapbox/mapbox-sdk-js/issues/74 and fixed it - the next release will be react native compatible.

**Comment by julioahurtado** [comment]
@tmcw Ok thank you for the fast reply. Does said fix also fix the problem with the when.lift function?

**Comment by bsudekum** [comment]
Fixed in https://github.com/mapbox/mapbox-sdk-js/pull/44

**Comment by tmcw** [comment]
No, we still need https://github.com/mapbox/mapbox-sdk-js/issues/79 to be finished for React Native support.
