### ISSUE TITLE
Can't render raster layers.

### ISSUE THREAD

**Issue by javierbyte** [nitaliano/react-native-mapbox-gl#315]
Hello!

I'm trying to render a raster layer on iOS. A new project with a freshly installed react-native-mapbox-gl.

I created this `styleURL`:
https://gist.github.com/javierbyte/162ea8a03fac49f0d320

It's just the wikipedia logo on top of a white map.

It works well on browsers:
https://jsbin.com/tirecopelo/edit?html,output

But although I can render the white map on iOS, the logo never appears, and xcode logs this:
`2016-03-24 21:33:59.339 dashboard[432:124435] [WARNING] {Map}[Render]: can't find source for layer 'overlay'`

`overlay` is defined in `sources` as:

```
      "overlay": {
          "type": "image",
          "url": "https://www.wikipedia.org/portal/wikipedia.org/assets/img/Wikipedia-logo-v2.png",
          "coordinates": [
              [-80.425, 46.437],
              [-71.516, 46.437],
              [-71.516, 37.936],
              [-80.425, 37.936]
          ]
      }
```

And requested in layers as:

```
        {
            "id": "overlay",
            "source": "overlay",
            "type": "raster"
        }
```

Is raster layers and unsupported feature for mobile?

Thanks!

**Comment by friedbunny** [comment]
> Is raster layers and unsupported feature for mobile?

Georeferenced raster overlays [aren’t supported yet in native](https://github.com/mapbox/mapbox-gl-native/issues/1350), but [raster tile layers are](https://www.mapbox.com/ios-sdk/examples/raster-styles/). This means that you could upload a GeoTIFF to Mapbox and then use the resulting raster tileset in a native-compatible style.
