### ISSUE TITLE
[Android] selectAnnotationAnimated

### ISSUE THREAD

**Issue by jorgenskogmo** [nitaliano/react-native-mapbox-gl#316]
Hi,

Using v. 4.0.0, Im getting `NativeModules.MapboxGLManager.selectAnnotationAnimated is not a function` errors.

Checked the [Android API reference](https://github.com/mapbox/react-native-mapbox-gl/blob/master/android/API.md), and found its apparently not implemented for Android.
Then checked the [source](https://github.com/mapbox/react-native-mapbox-gl/blob/master/index.android.js#L23) - to find it defined... 

Can you please clarify?

Thanks in advance!

j.

**Comment by impurist** [comment]
Same issue here...

**Comment by Thetortuga** [comment]
Hello,
On Android, the selection of an annotation does nothing. I suppose that this is linked with this issue.
Any update ?

**Comment by dapetcu21** [comment]
This method has been implemented for Android in 5.0.0 and is confirmed working. Closing this 😀
