### ISSUE TITLE
Custom annotation images (Android)

### ISSUE THREAD

**Issue by falconx** [nitaliano/react-native-mapbox-gl#317]
1. I can't get `image!yourImage.png` to load a local asset when I have the image at `android/app/src/main/res/drawable`. Though I'd prefer to follow react-native approach and `require` it.
2. Is there anyway to specify an override to the user dot (showsUserLocation) image? — specifically I'd like to be able to represent it with a (facebook) profile image, ideally from a uri.

**Comment by jayfunk** [comment]
1. This was fixed in android with version 4.1.0. There are still some issues with it but it works for the most part. I tested it out last night.
2. There isnt an API available that I am aware of.

**Comment by KevinHu2014** [comment]
Same problem on 1.
(version 4.1.1)

**Comment by dapetcu21** [comment]
The API has changed significantly in 5.0.0, but I can confirm local annotation images work on Android. Check out [the docs](https://github.com/mapbox/react-native-mapbox-gl/blob/master/API.md#annotations) on how to use them. I'll close this for the moment. If you still can't get them to work, I'll reopen it and we'll investigate.

 As for 2, please open a separate issue for that.
