### ISSUE TITLE
Bring annotation to front

### ISSUE THREAD

**Issue by jorgenskogmo** [nitaliano/react-native-mapbox-gl#318]
Hi,

Is there a way to bring the selected annotation to front?

Maybe even as the default behavior of `selectAnnotationAnimated()`?

j.

**Comment by cupofjoakim** [comment]
+1 for this. I just tried ordering the array fed to addAnnotations to see if the later appeared above the ones sent in before, which I would say would be the expected behaviour, to no avail. Any solutions would be appreciated.

**Comment by cupofjoakim** [comment]
Although no work has been done at it, the issue is being tracked upstream over at https://github.com/mapbox/mapbox-gl-native/issues/991
