### ISSUE TITLE
[Error] - NativeModules.MapboxGLManager.mapStyles

### ISSUE THREAD

**Issue by jcgertig** [nitaliano/react-native-mapbox-gl#319]
Stats:
- react-native 0.22.0
- react-native-mapbox-gl 4.0.0
- cocoapods 0.39.0
- node 5.5.0

I am using pods i am updating from 3.0.0 which was working fine

yes my other linkers has `$(inherited)` and that's it

**Comment by jcgertig** [comment]
It seems to be 3.2.x and higher is the issue 3.1.0 is fine

**Comment by jorgenskogmo** [comment]
I "solved" this by letting [react-mixin](https://github.com/brigand/react-mixin) do the mix'n for me
`reactMixin(MapPage.prototype, Mapbox.Mixin);` (where `MapPage` is my extended Component).

**Comment by JorritPosthuma** [comment]
I'm having the same problem `NativeModules.MapboxGLManager` just isn't available. I've followed https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/install-cocoapods.md to the letter (including clearing `OTHER_LDFLAGS` before pod install, and after that `), and tried from scratch with a clean RN project.

My PodFile is as follows:

```
platform :ios, '8.0'
use_frameworks!

target 'Mobile' do
  pod 'React', :path => '../node_modules/react-native'
  pod 'React/RCTGeolocation', :path => '../node_modules/react-native'
  pod 'React/RCTImage', :path => '../node_modules/react-native'
  pod 'React/RCTNetwork', :path => '../node_modules/react-native'
  pod 'React/RCTText', :path => '../node_modules/react-native'
  pod 'React/RCTWebSocket', :path => '../node_modules/react-native'

  pod 'RCTMapboxGL', :path => '../node_modules/react-native-mapbox-gl/ios'
end

target 'MobileTests' do
  pod 'React', :path => '../node_modules/react-native'
end
```

And when I do a `console.log(React.NativeModules.MapboxGLManager);`, it is undefined.

Manual method works fine btw 😊

**Comment by tharrington** [comment]
@baseio I am new to react, did you use the react mixin in your component?

var Service = React.createClass({
    reactMixin(this.prototype, MapBox.Mixin),

Service is the component that renders the map

**Comment by tharrington** [comment]
By the way, I am not using cocoapods.

**Comment by jorgenskogmo** [comment]
I installed [manually](https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/install.md), and then used [react-mixin](https://github.com/brigand/react-mixin) (see my post above) to successfully access Mapbox things on `this` , e.g. `<Mapbox styleURL={this.mapStyles.light} />`

Seems the mixin approach is [far from the recommended practice](https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750#.8suxt9mfp) though.

**Comment by tmcw** [comment]
We plan to [stop using mixins for this purpose](https://github.com/mapbox/react-native-mapbox-gl/issues/304) in the near future.

**Comment by dapetcu21** [comment]
The way stuff (including `styles`) gets exported from the module has changed in 5.0.0. We are also not using mixins anymore. I will assumed this is fixed, but feel free to reopen if you're still having issues with 5.0.0.

**Comment by amaury1093** [comment]
Still having issues with 5.1.0. I have the following error. I followed instruction here from a clean app: https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/install-cocoapods.md.

`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RCTMapboxAnnotation", referenced from:
      objc-class-ref in libRCTMapboxGL.a(RCTMapboxGL.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

My podfile:


> platform :ios, '8.0'
> 
> target 'MyApp' do
>   pod 'React', :path => '../node_modules/react-native'
>   pod 'React/RCTGeolocation', :path => '../node_modules/react-native'
>   pod 'React/RCTImage', :path => '../node_modules/react-native'
>   pod 'React/RCTNetwork', :path => '../node_modules/react-native'
>   pod 'React/RCTText', :path => '../node_modules/react-native'
>   pod 'React/RCTWebSocket', :path => '../node_modules/react-native'
> 
>   pod 'RCTMapboxGL', :path => '../node_modules/react-native-mapbox-gl/ios'
> end

Any ideas?

**Comment by gbme** [comment]
@amaurymartiny I have exactly the same issue, did you manage to solve this or work around this?
