### ISSUE TITLE
"RCTMapboxGL" registered bubbling event "topLongPress" as a direct event

### ISSUE THREAD

**Issue by skizzo** [nitaliano/react-native-mapbox-gl#320]
After a manual install on iOS, I get this error when trying to run the example:
![screen shot 2016-04-01 at 10 52 46](https://cloud.githubusercontent.com/assets/2892572/14202395/fbc9839e-f7f7-11e5-86c4-6ac17c10be38.png)
using React Native 0.22.2.
Thanks for any help.

**Comment by dapetcu21** [comment]
This should probably be fixed now in #365, if not earlier on. I know I used `onLongPress` and ran the example successfully with master.

**Comment by ReggaePanda** [comment]
I get the same error, when I …

start a project with expo XDE
```
npm install --save react-native-mapbox-gl
```

Add to app.json
```
 {
   "expo": {
    "ios": {
      "bundleIdentifier": "com.mycompany.myappname"
    },
    "android": {
      "package": "com.mycompany.myappname"
    }
   }
 }
```

```
exp detach
```
add `pod 'RCTMapboxGL', :path => '../node_modules/react-native-mapbox-gl/ios'` to ./ios/Podfile
```
cd ios
pod install
```
start simulator in xcode 

<img width="616" alt="bildschirmfoto 2017-07-31 um 16 07 25" src="https://user-images.githubusercontent.com/2183135/28781454-615feebe-760a-11e7-8edb-b12f4687fd10.png">

npm: 4.6.1
node: v8.2.1

package.json 
```
{
  "name": "mapbox-expo-react-native",
  "version": "0.0.0",
  "description": "Hello Expo!",
  "author": null,
  "private": true,
  "main": "node_modules/expo/AppEntry.js",
  "dependencies": {
    "expo": "^19.0.0",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-19.0.0.tar.gz",
    "react-native-mapbox-gl": "^5.2.0"
  }
}
```

**Comment by lucasbento** [comment]
@dapetcu21: I'm running into that same problem on version `5.2.0`, react-native `0.47.2`:

![image](https://user-images.githubusercontent.com/6207220/30113452-0c1eb214-9315-11e7-87c4-cadd73829d37.png)

Is there something that I can do?

**Comment by StasDoskalenko** [comment]
@lucasbento have you deleted AIRBNB Maps? And unlinked the lib?

**Comment by lucasbento** [comment]
@StasDoskalenko: hey, thanks for answering.

I actually have to use rn-maps and rn-mapbox-gl together.
