### ISSUE TITLE
setCenterCoordinateZoomLevelAnimated not working after returning from other view with map on it

### ISSUE THREAD

**Issue by cupofjoakim** [nitaliano/react-native-mapbox-gl#322]
setCenterCoordinateZoomLevelAnimated works perfectly fine when visiting the a view with a mapbox component for the first time, or after returning from other view. 

After visiting a sibling view with another instance of the Mapbox component being rendered however, the method no longer seems to run. 

I'm quite unsure about what information I could provide to make this report as informative as possible, so just ping me and I'll get you whatever you'd need that's not sensitive for the project.

**Comment by dapetcu21** [comment]
This component was heavily refactored in #365 recently and your bug probably has been fixed. Can you check to see if you can reproduce this now?

**Comment by tmcw** [comment]
Closing; please re-open this issue if you can confirm that it persists @cupofjoakim
