### ISSUE TITLE
[Error] Requiring unknown module "Subscribable"

### ISSUE THREAD

**Issue by MaximLeonov** [nitaliano/react-native-mapbox-gl#324]
I intstalled module according to instructions. Then I imported module in index.android.js file. After building an app 2 errors occured:
Requiring unknown module "Subscribable". If you are sure the module is there, try restarting the packager or running "npm install".
and
Module AppRegistry is not a registered callable module.

Restarting packager and running "npm install" didn't help.

**Comment by orelmax** [comment]
Same problem here. It works fine with react-native@0.22 but threw an error on 0.23.

**Comment by rbeers** [comment]
Same here, also tried "react-native": "^0.24.0-rc4"

**Comment by bsudekum** [comment]
Confirmed, digging into this now. A quick bandaid can be applied with:

``` js
var Subscribable = require('../react-native/Libraries/Components/Subscribable');
```

in `/node_modules/react-native-mapbox-gl/index.android.js`.

Not totally sure what the issue is, but for some reason when you require react native, `Subscribable` is not shipped with it.

**Comment by MaximLeonov** [comment]
Thank you! this helped.

**Comment by KevinHu2014** [comment]
Same problem on 0.23.

**Comment by pppluto** [comment]
@bsudekum   helped,thanks a lot :beer: i think is because the npm. npm 3+ change their package manager Algorithm.

**Comment by Thetortuga** [comment]
Hello, 
Same problem with RN 0.24 released few days ago.
@MrPluto I run npm 2.14.12 with the same issue

However, calling`require('Subscribable')` into my project worked well.

**Comment by psychoz971** [comment]
Hello,
Same problem with react-native@0.24 npm@3.8.3 node@v5.10.1

Downgrade to react-native@0.22 and all work well

++

**Comment by atmanat** [comment]
+1

**Comment by vespakoen** [comment]
Made a pull request over here: https://github.com/mapbox/react-native-mapbox-gl/pull/339
