### ISSUE TITLE
Support annotation type: circle

### ISSUE THREAD

**Issue by nickdaugherty** [nitaliano/react-native-mapbox-gl#328]
The `RMCircle` class should be supported, via an annotation type of `circle`.

https://www.mapbox.com/mapbox-ios-sdk-legacy/examples/drawing-circle/

**Comment by bsudekum** [comment]
You're actually linking to the legacy api, this project uses https://www.mapbox.com/ios-sdk/

This is an upstream issue: https://github.com/mapbox/mapbox-gl-native/issues/2167

**Comment by jesperbjerke** [comment]
What is the best approach to draw circles with the current toolset? My actual goal is to have a lat/long point on the map and show a radius around it.
