### ISSUE TITLE
Error Building 4.1.0 on iOS

### ISSUE THREAD

**Issue by jayfunk** [nitaliano/react-native-mapbox-gl#332]
I was unable to build the iOS version of 4.1.0. Do I need to re-run the iOS setup?

![image](https://cloud.githubusercontent.com/assets/2545666/14626936/dd49f2ea-05bd-11e6-82c2-10dbce213592.png)

**Comment by bsudekum** [comment]
Yes, you have to re npm install and then go through the install process. Make sure to first remove the old `Mapbox.framework` before starting the new installation.

**Comment by jayfunk** [comment]
That did it. Thanks!
