### ISSUE TITLE
Can't use local image for annotationImage

### ISSUE THREAD

**Issue by meafmira** [nitaliano/react-native-mapbox-gl#336]

**Comment by jayfunk** [comment]
What version of the lib are you using and what platform?

**Comment by meafmira** [comment]
Lib version: 4.0
Platform: iOS

**Comment by jayfunk** [comment]
Code snippet? Have you registered the image you wish to use with
image.xcassets?

**Comment by vespakoen** [comment]
In case of android, support was added for this in 4.1.0.

**EDIT** Whoops, missed your "Platform: iOS" there ;)

**Comment by jayfunk** [comment]
Have you resolved this yet? I think this should be closed since nothing has been reported from the user.
