### ISSUE TITLE
incorrect compass location when screen rotated

### ISSUE THREAD

**Issue by bsudekum** [nitaliano/react-native-mapbox-gl#34]
![ios simulator screen shot may 14 2015 5 34 57 pm](https://cloud.githubusercontent.com/assets/1058624/7644815/a2f9a960-fa5f-11e4-969a-89280f50f4e8.png)

/cc @1ec5

**Comment by friedbunny** [comment]
@bsudekum Hrm, did this start with this afternoon's https://github.com/mapbox/mapbox-gl-native/pull/1560? :sweat:

**Comment by bsudekum** [comment]
@friedbunny uncertain, this the first time i've rotated the map :wink: . I can try this in a earlier release pretty easily.

**Comment by bsudekum** [comment]
Not seeing anymore
