### ISSUE TITLE
[Android] Width and Height is not being applied on annotations

### ISSUE THREAD

**Issue by xphaul** [nitaliano/react-native-mapbox-gl#341]
annotationImage: {
          url: 'https://s3-ap-southeast-1.amazonaws.com/dutchbag/bag-orange.png',
          height: 10,
          width: 10
        }

Here is my code for the annotations . I followed the documentation but the width and height props are not being applied .

**Comment by dapetcu21** [comment]
Can you confirm you're still having the same issue with 5.0.0? That code got refactored.

**Comment by tmcw** [comment]
Closing; no confirmation - @xphaul can you reopen if you can confirm this behavior persists post-5.0.0?

**Comment by idomaz00** [comment]
hi @tmcw I have the same issue in 5.2.2 version on Android, but it worked perfectly on version 5.2.0. here is my code: 
`annotationImage: {
          source : { uri: 'pin' },
          height: 25,
          width: 15,
 },`
