### ISSUE TITLE
ReactIOSViewAttributes removed in 0.4.3

### ISSUE THREAD

**Issue by hasdavidc** [nitaliano/react-native-mapbox-gl#35]
Under Breaking Changes here: https://github.com/facebook/react-native/releases/tag/v0.4.3

"If you were using the undocumented createReactIOSNativeComponentClass or ReactIOSViewAttributes to create iOS wrappers, now you should use requireNativeComponent"

Also.. Is ReactIOSViewAttributes being consumed?

**Comment by bsudekum** [comment]
Thanks for the heads up, I'll look into removing it.

**Comment by bsudekum** [comment]
fixed in https://github.com/bsudekum/react-native-mapbox-gl/issues/36
