### ISSUE TITLE
onLongPress and onOpenAnnotation are not functioning

### ISSUE THREAD

**Issue by KevinHu2014** [nitaliano/react-native-mapbox-gl#355]
onLongPress and onOpenAnnotation are not functioning on Android
"react-native-mapbox-gl": "^4.1.1"

**Comment by Dacello** [comment]
I think this is related to #356. Seems like event handlers on the java side aren't correctly triggering events on the react side.

**Comment by dapetcu21** [comment]
Fixed in #365
