### ISSUE TITLE
[Android] Annotation Artifacts

### ISSUE THREAD

**Issue by dmkmedina** [nitaliano/react-native-mapbox-gl#360]
I've noticed that when adding and removing annotations via the annotations prop, artifacts start to appear where annotations should be. 

![screenshot_2016-06-10-11-00-41](https://cloud.githubusercontent.com/assets/1490472/15959629/f5a7b4f0-2efb-11e6-86b3-f743ee46908b.png)

**Comment by KevinHu2014** [comment]
Hi @dmkmedina ,
 How did you make this ?
![f5a7b4f0-2efb-11e6-86b3-f743ee46908b](https://cloud.githubusercontent.com/assets/7204070/15983543/a3700f92-2fdd-11e6-9eeb-1e0322d34c01.png)

**Comment by dmkmedina** [comment]
They're just TouchableHighlights absolutely positioned on top of the map view. The icons come from a custom icon font.

**Comment by KevinHu2014** [comment]
Thanks

**Comment by dapetcu21** [comment]
Hi. This sounds like a bug in [the Mapbox SDK](https://github.com/mapbox/mapbox-gl-native). We've since updated the underlying SDK with the new 5.0.0. Can you confirm this still happens with 5.0.0? Also, can you provide a way to reproduce the bug?

**Comment by dmkmedina** [comment]
The update has improved the Android performance significantly. It also seems to have fixed the issue with the artifacts we were seeing. Thanks a lot!!
