### ISSUE TITLE
Mixins and this.refs are deprecated

### ISSUE THREAD

**Issue by dapetcu21** [nitaliano/react-native-mapbox-gl#361]
React is in the process of deprecating this.refs and mixins. The correct way of implementing imperative methods is by attaching the methods directly to the component class, so the user can do 
`<MapView ref={map => { this.mapRef = map; }} />`, then the simpler `this.mapRef.addAnnotations(annotations)`.

Mixins are unusable, for example, if you use the new ES6 `class MyComponents extends Component {...}` syntax.

This transition to this API can be implemented in a backwards compatible fashion. I am willing to submit a PR for this if you agree that this is what should be done.

**Comment by urbancvek** [comment]
I am not a maintainer of this project but I also agree with you and I thought about it myself. 
All map methods should than be rewritten without first argument which is now MAP_REF.

If you decide to do it I would be willing to help. 😄

**Comment by dapetcu21** [comment]
I'll do it. It shouldn't take me more than a few hours. I'll actually make a bigger PR (#365) with some more API improvements. Any help on an Android port for these changes will be appreciated.

**Comment by dapetcu21** [comment]
Closing this after fixing it in #365
