### ISSUE TITLE
Animating an annotation as the user drags a slider

### ISSUE THREAD

**Issue by vessp** [nitaliano/react-native-mapbox-gl#371]
Hello, 
  I am looking for a way to smoothly move an annotation across my map in response to the user dragging a slider.  Right now I am using the **updateAnnotation** method  to change the position of the annotation more than 10 times a second.  However this way of doing it is giving me laggy results as well as some flickering.  I noticed in the ios mapbox project that the **updateAnnotation** method is just a wrapper for removing and then re-adding the annotation.  

  So my question is, is there a way to modify the coordinates of an annotation directly (like they do on web [here](https://www.mapbox.com/mapbox-gl-js/example/animate-point-along-line/)) to get smoother results?

**Comment by dapetcu21** [comment]
If I'm not mistaken the Mapbox SDK for both iOS and Android doesn't allow for updating annotations. 
In #365 I tried to minimise some of this flicker by adding the new annotation before removing the old one.

**Comment by dapetcu21** [comment]
Try 5.0.0. If this still isn't ok for your usecase, then I suggest creating an issue upstream on [mapbox/mapbox-gl-native](https://github.com/mapbox/mapbox-gl-native)
