### ISSUE TITLE
Please add setTilt method to documentation for android

### ISSUE THREAD

**Issue by nemot** [nitaliano/react-native-mapbox-gl#372]
Hey guys. I spend a while trying to understand how to set pitch in android. Realized that just after reading a code. Let's add it to documentation to be consistent.

**Comment by dapetcu21** [comment]
The API for setting tilt was changed in 5.0.0 and documented [here](https://github.com/mapbox/react-native-mapbox-gl/blob/master/API.md#methods). I am closing this for now.
