### ISSUE TITLE
Poor performance when adding large numbers of annotations.

### ISSUE THREAD

**Issue by siegesmund** [nitaliano/react-native-mapbox-gl#374]
Adding ~ 100 annotations on iOS causes the entire app to slow to a crawl and become unresponsive for 5 seconds or so. 

Is there a pattern to follow to avoid this performance hit?

**Comment by dapetcu21** [comment]
Can you confirm this is still the case with 5.0.0, after the recent #365 merge?

**Comment by tmcw** [comment]
Merging into #425, as both issues are about lots of annotations.
