### ISSUE TITLE
this.setCameraAnimated not working in react-native

### ISSUE THREAD

**Issue by ericchen0121** [nitaliano/react-native-mapbox-gl#375]
I have used `this.setCenterCoordinateZoomLevelAnimated` and `this.setZoomLevelAnimated` working in my react-native codebase. However, I tried to change one of those calls to `this.setCameraAnimated` with corresponding arguments and it doesn't seem to work. 

Is there a good example of this in a codebase or a working example?

**Comment by dapetcu21** [comment]
This family of functions got replaced in the recent refactor with the `_map.easeTo()` family of functions. Check it out [here](https://github.com/mapbox/react-native-mapbox-gl/blob/master/API.md#methods). With `easeTo()`, you can now set an arbitrary number of parameters (with some small limitations) at the same time.

**Comment by tmcw** [comment]
Closing; this is resolved in v5.0.0 with the improved camera API.
