### ISSUE TITLE
[iOS] Map is not created if no annotations exist on the initial subview layout of RCTMapboxGL

### ISSUE THREAD

**Issue by abeck99** [nitaliano/react-native-mapbox-gl#377]
updateMap is called from layoutsubviews, which will in turn create the map if it doesn't exist. This is because the map view needs the bounds from RCTMapboxGL before it's created.

However updateMap is only called if there are no annotations (not sure why). If annotations exist before the initial subview layout, then the map needs to be created anyway.

**Comment by dapetcu21** [comment]
This got fixed in #365. That whole piece of code got refactored.
