### ISSUE TITLE
Add +1 addons

### ISSUE THREAD

**Issue by bsudekum** [nitaliano/react-native-mapbox-gl#38]
- [turf](http://turfjs.org/)
- geocoding
- routing

I'm thinking that these ship with the module instead of having them be separate dependencies/repos.

**Comment by 1ec5** [comment]
There would be little benefit to implementing Turf as a native module, since it’s already written in JavaScript. Would it be possible for React Native applications to use Turf as-is?

**Comment by KevinHu2014** [comment]
So, is it possible to use turf now?

**Comment by bsudekum** [comment]
@KevinHu2014 yep, just `npm install turf`

**Comment by KevinHu2014** [comment]
@bsudekum Thanks~

**Comment by KevinHu2014** [comment]
@bsudekum Does routing means [Driving directions](https://www.mapbox.com/mapbox.js/example/v1.0.0/mapbox-directions/)?
