### ISSUE TITLE
setStyle Url to external mapbox GL style

### ISSUE THREAD

**Issue by Biboba** [nitaliano/react-native-mapbox-gl#381]
Hello,

I am trying to set the 'styleURL' props of the map to an external mapbox GL style json file.
It is working with mapbox-gl-js api with the map.setStyle method, but I cannot make it work with android SDK. 
The app is crashing complaining :  unexpected url: /mysprite@2x.json but the file does exist. It is as if the hostname had been truncated somewhere. Have I missed anything or is it an expected behavior ?

Cheers

**Comment by dapetcu21** [comment]
Hi. What version of RNMGL are you using?

**Comment by Biboba** [comment]
Oups, apologies, yes that can be helpful : 
$ npm list react-native-mapbox-gl
react-native-mapbox-gl@4.1.1

**Comment by dapetcu21** [comment]
How are you using the component? More specifically, how does your styleURL look like?

Also, can you try with 5.0.0 (it's not on npm yet, so you'd need to do `npm install mapbox/react-native-mapbox-gl`)? Beware the API has changed quite a lot. 

Maybe try to isolate the problem in a new project?

**Comment by Biboba** [comment]
I am using :
styleURL={'http://hostname/path/to/style.json'} and it works with 5.0.0 =)
Cheers

**Comment by dapetcu21** [comment]
Great. It's probably because we updated the Mapbox SDKs.
