### ISSUE TITLE
Unhandled JS Exception: _reactNativeMapboxGl2.default.setAccessToken is not a function

### ISSUE THREAD

**Issue by AntonioRossi** [nitaliano/react-native-mapbox-gl#384]
I receive this error when starting on IOS.

I installed using `npm install react-native-mapbox-gl --save` and then followed the instructions for manually configuring in XCode, and also the troubleshooting configuration related to my 'zsh' shell.

If I try to manually run `sudo ./ios/build/Build/Products/Debug-iphonesimulator/MapTest.app/Frameworks/Mapbox.framework/strip-frameworks.sh` the script hang producing the following output:

``` Shell
Stripping frameworks
find: ./dev/fd/3: Not a directory
find: ./dev/fd/4: Not a directory
```

Those are my dependecies:

``` Shell
  "dependencies": {
    "react": "15.2.1",
    "react-native": "0.30.0",
    "react-native-mapbox-gl": "^4.1.1"
  }
```

My node versions is `v4.4.7`,  npm is `3.10.6`, and I'm using nvm.

This is how I load `react-native-mapbox-gl`:

``` Javascript
import React, { Component } from 'react';
import {
  AppRegistry,
  Navigator,
  StyleSheet,
  Text,
  TouchableHighlight
} from 'react-native';

import Mapbox, { MapView } from 'react-native-mapbox-gl';
const accessToken = 'my acces token';
Mapbox.setAccessToken(accessToken);
```
### cocoapods install

Then I tried the installation using cocoapods, everything goes fine without any warning:

``` Shell
Analyzing dependencies
Fetching podspec for `RCTMapboxGL` from `../node_modules/react-native-mapbox-gl/ios`
Fetching podspec for `React` from `../node_modules/react-native`
Downloading dependencies
Using RCTMapboxGL (3.2.0)
Using React (0.30.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 7 dependencies from the Podfile and 2 total pods installed.
```

 and instead when lauching the app it is produced the error:
 `Cannot read propery 'mapStyles' of undefind`

**Comment by dapetcu21** [comment]
The version of RNMGL that's on npm is older and doesn't have the same API. Use `npm install --save mapbox/react-native-mapbox-gl` until 5.0.0 gets published on npm.

**Comment by dapetcu21** [comment]
ref #379 
cc @bsudekum

**Comment by AntonioRossi** [comment]
Nice, it worked, thanks!
