### ISSUE TITLE
deselect annotation

### ISSUE THREAD

**Issue by HananeAlSamrout** [nitaliano/react-native-mapbox-gl#385]
hello, 
in my project, i was using the old module, and i changed in the module files in order to not display the annotation pop up, because i wanted to open a custom view from inside react-native on onOpenAnnotation, 
can you add this option in the module so i don't change in its files?
something like disableAnnotationsPopUp 
and also a function  
this._map.deselectAnnotation('marker1')} ...  so i can close the annotation pop up from react-native

**Comment by dapetcu21** [comment]
Hi. This sounds like a nice feature. If you want to, you can implement this and create a PR with the changes.

Also, `this._map.deselectAnnotation()` shouldn't probably take any arguments.

**Comment by HananeAlSamrout** [comment]
okay, thank you
