### ISSUE TITLE
Undefined is not an object (evaluating 'MapboxGLManager.mapStyles')

### ISSUE THREAD

**Issue by pianetarosso** [nitaliano/react-native-mapbox-gl#387]
When starting the example project, I get on "index.js" line 18 this error.

**Comment by dapetcu21** [comment]
Your native bindings aren't properly loaded in your project. Make sure to follow the installation guide for your platform.

**Comment by pianetarosso** [comment]
I followed the instructions listed there @dapetcu21 https://github.com/mapbox/react-native-mapbox-gl/blob/master/android/install.md

**Comment by dapetcu21** [comment]
With rnpm or manually? Make sure the plugin is present in getPackages()

**Comment by pianetarosso** [comment]
Redone all steps:
- npm install --save react-native-mapbox-gl
- rnpm link
- set https://github.com/mapbox/react-native-mapbox-gl/blob/master/example.js as index.android.js
- run

I still getting the mapStyles undefined error.

**Comment by dapetcu21** [comment]
Firstly, these steps are not complete. You skipped step 3 from [here](https://github.com/mapbox/react-native-mapbox-gl/blob/master/android/install.md) where you add permissions and the mapbox telemetry service.

Secondly, I can you please verify that `ReactNativeMapboxGLPackage` thas been added by rnpm to `getPackages()` in `MainActivity.java`?

**Comment by pianetarosso** [comment]
I had already done the android steps @dapetcu21.
After I re-created the project for the third time, it seems to work now. 
Probably it was a problem with **rnpm**.

Thank you

**Comment by Dammmien** [comment]
I have the same issue, i follwoed these [steps](https://github.com/mapbox/react-native-mapbox-gl/blob/master/android/install.md) both manual and with rnpm.

my android/settings.graddle : 

```
rootProject.name = 'ReactNativeProject'

include ':app'
include ':react-native-mapbox-gl'
project(':react-native-mapbox-gl').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-mapbox-gl/android')
```

my android/app/build.gradle

```
...
dependencies {
    compile project(':react-native-mapbox-gl')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
}
...
```

my MainActivity.java

```
    @Override
    protected String getMainComponentName() {
        return "ReactNativeProject";
    }

    protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new ReactNativeMapboxGLPackage()
        );
    }
```

and the AndroidManifest.xml

```
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
...
<service android:name="com.mapbox.mapboxsdk.telemetry.TelemetryService"/>
```

**Comment by ouya99** [comment]
are these Android steps necessary?

I am having this issue -  #396 -  on the iOS simulator

**Comment by ouya99** [comment]
@Dammmien

i assume you are using RN < 0.29.. cause in new version it is a complete different approach with implementing ReactApplication
