### ISSUE TITLE
Mapbox hangs after setting zoomLevel={20}

### ISSUE THREAD

**Issue by aksonov** [nitaliano/react-native-mapbox-gl#390]
App starts eating memory to 4-5GB and then machine hangs. For zoomLevel=19 everything works fine.

**Comment by dapetcu21** [comment]
How can we reproduce? What are the exact steps?

**Comment by aksonov** [comment]
Do you have ready to run iOS example project? (so i will set zoom size to 20 and see)? All I've found is example.js but it is very outdated and cannot be run with latest RN & MapBox.

**Comment by dapetcu21** [comment]
[example.js](https://github.com/mapbox/react-native-mapbox-gl/blob/master/example.js) has been updated recently along with the whole library. What version of RNMGL are your using? 5.0.0 is the latest.

**Comment by aksonov** [comment]
I've just tried 5.0.0, issue still the same there. How to run that example? I've made a lot of steps to install it as iOS app for my project (add static framework and so on), why this component just doesn't have Example.xcodeproj file and ready to run example?

**Comment by aksonov** [comment]
I'm trying to setup Example project with cocoa pods but got following:

```
Undefined symbols for architecture x86_64:
  "_convertToMGLAnnotation", referenced from:
      ___65-[RCTMapboxGLManager spliceAnnotations:deleteAll:toDelete:toAdd:]_block_invoke in libRCTMapboxGL.a(RCTMapboxGLManager.o)
  "_imageFromSource", referenced from:
      -[RCTMapboxGL mapView:imageForAnnotation:] in libRCTMapboxGL.a(RCTMapboxGL.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by dapetcu21** [comment]
True. Maybe a full example project could have been a great idea, but the example, I assure you, works.

It looks like something's off with RNMGL's xcodeproj. It doesn't seem to include the conversions file. Close your xcodeproj, remove `node_modules`, make sure `react-native-mapbox-gl` is set to `5.x`  or `^5.0.0` in your `package.json`, then run `npm install` again. Open your project's xcodeproj and do a clean build.

**Comment by dapetcu21** [comment]
After that, the only steps required to make the example work, different from the usual project setup are using your API key and setting the name of the app in `AppRegistry.registerComponent`

**Comment by aksonov** [comment]
It just don't work with all proposed steps (with CocoaPods). Will try to install map box manually...

**Comment by dapetcu21** [comment]
The error you referenced above could not have happened unless the `xcodeproj` you have for RNMGL was from an older version of RNMGL. Try the manual setup. Maybe that helps. But make sure the RNMGL that you have in `node_modules` is 5.0.0, complete with its `xcodeproj`

**Comment by aksonov** [comment]
After many experiments and trying to reproduce my problem on some test project i've found the reason - outdated Mapbox.framework (Apr, 2016). After i've replaced it to latest one it starts working as expected. Maybe you could consider some automatic copying script or something like that, because when i'm removing node_modules and run 'npm install', i'm expecting to have latest version - however now i have to remove Mapbox.framework and add new one after each upgrade, right? It seems not intuitive and not documented well...

**Comment by dapetcu21** [comment]
Hmmm. I find this weird as well. `npm install` should have updated the framework. I wonder when does Xcode pick it up and from where? I haven't tried the Cocoapods setup yet, so I can't tell how that works, but in the manual setup it seems that it links Mapbox.framework from inside node_modules, which is correct.

**Comment by aksonov** [comment]
CocoaPods install is broken for 5.0.0 - I've sent you error i've got. Manual install works fine and I was NOT able to reproduce my problem with the same react component. So i've replaced my app Mapbox framework and problem is gone, so i could close this ticket. I don't know why my Mapbox was not updated automatically, hope it will be updated at the future (but i will keep eyes on this ;)

**Comment by vjpr** [comment]
@dapetcu21 

> It doesn't seem to include the conversions file. 

The fix is to modify the podspec to:

```
  s.source_files        = "RCTMapboxGL/RCTMapboxGL.{h,m}", "RCTMapboxGL/RCTMapboxGLManager.{h,m}", "RCTMapboxGL/RCTMapboxGLConversions.{h,m}"
```
