### ISSUE TITLE
Remote images don't work on Android

### ISSUE THREAD

**Issue by dapetcu21** [nitaliano/react-native-mapbox-gl#391]
On Android, remote images should be loaded on a different thread than the UI, so that the `NetworkOnMainThread` exception doesn't happen.

**Comment by dapetcu21** [comment]
Ref #388

**Comment by rmevans9** [comment]
Anyone working on the solution for this? I need this pretty badly.

**Comment by rmevans9** [comment]
I have went ahead and resolved this issue. Doing some additional testing then will get a PR opened.
