### ISSUE TITLE
map on ios takes time to load

### ISSUE THREAD

**Issue by HananeAlSamrout** [nitaliano/react-native-mapbox-gl#392]
hello, 
on ios, when the app is in background and then opened, the map becomes black and takes time to load.
do you have any idea why this is happening ?

**Comment by HananeAlSamrout** [comment]
i noticed that the map is being downloaded each time the app returns from the background

**Comment by HananeAlSamrout** [comment]
only on production

**Comment by 1ec5** [comment]
This issue doesn’t reproduce when using the Mapbox iOS SDK directly in Objective-C or Swift. Maybe React Native reloads the view whenever the application returns to the foreground.
