### ISSUE TITLE
Local style file

### ISSUE THREAD

**Issue by vespakoen** [nitaliano/react-native-mapbox-gl#393]
It seems Mapbox GL bundles assets "from the root of the project"

I tried adding my style file in:
- myapp/style.json
- myapp/ios/style.json
- myapp/ios/myapp/style.json
- myapp/assets/style.json

And loading it with:

`styleURL={'asset://style.json'}`

(on iOS), unfortunately without success.

```
2016-08-01 09:24:24.023 myapp[70385:1212023] [ERROR] {}[Setup]: loading style failed: 
```

Is this supposed to be working or am I doing it wrong?

**Comment by dapetcu21** [comment]
Make sure it's added in xcode to the "copy bundle resources" build phase?

**Comment by vespakoen** [comment]
That worked! Thanks
