### ISSUE TITLE
Crash when adding large polyline annotations

### ISSUE THREAD

**Issue by RagnarHal** [nitaliano/react-native-mapbox-gl#394]
I am creating an app where I need to draw driving directions over road networks. I've been using annotations to draw the routes, but I am experiencing a crash without an error message if my route annotation is too large (typically occurs at over 3000 points). I've solved my particular problem by splitting the points up into smaller chunks and drawing many smaller annotations instead of one large annotation, but performance is still less than ideal (the component hangs while drawing the annotations). I wonder if there's a better way of drawing driving directions (or any large polylines) on the map? [How is it done in the Java SDK itself](https://www.mapbox.com/directions/)? Should some directions interface be implemented in this library?

I've put up a repo where you can reproduce the problem: https://github.com/RagnarHal/MapboxLargeAnnotationExample

**Comment by 1ec5** [comment]
There definitely should be no problem with a polyline that consists of over 3,000 points in the Mapbox Android SDK or iOS SDK.

@bsudekum, does @carlcraig’s fix in #412 look good to you?
