### ISSUE TITLE
undefined is not an object ( evaluating 'MapboxGLManager.mapstyles')

### ISSUE THREAD

**Issue by ouya99** [nitaliano/react-native-mapbox-gl#396]
I followed the installation instructions, but now I am facing a runtime issue

react: 15.0.2
react-native: 0.26.3

happy for any advice you have.

**Comment by dapetcu21** [comment]
This happens when you don't add the native bindings to your project. Make sure `getPackages` contains the RNMGL package constructor call.

**Comment by dapetcu21** [comment]
Oh. You're on iOS. Then, make sure the RNMGL library is linked with your binary.

**Comment by java99** [comment]
Actually I had an issue with adding the following without "bash" command at the beginning

"${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Mapbox.framework/strip-frameworks.sh"

`Connection to localhost port 8081 [tcp/sunproxyadmin] succeeded!

PhaseScriptExecution Run\ Script /Users/alexander/Dev/web/sharePoint/RNApp/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Script-142C4F7F1B582EA6001F0B58.sh
    cd /Users/alexander/Dev/web/sharePoint/RNApp/node_modules/react-native/React
    /bin/sh -c /Users/alexander/Dev/web/sharePoint/RNApp/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Script-142C4F7F1B582EA6001F0B58.sh

** BUILD FAILED **


The following build commands failed:
	CompileC /Users/alexander/Dev/web/sharePoint/RNApp/ios/build/Build/Intermediates/RCTMapboxGL.build/Debug-iphonesimulator/RCTMapboxGL.build/Objects-normal/x86_64/RCTMapboxGL.o RCTMapboxGL/RCTMapboxGL.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)`

**Comment by java99** [comment]
![bildschirmfoto 2016-08-06 um 00 09 07](https://cloud.githubusercontent.com/assets/2676451/17451829/15793ac0-5b6a-11e6-8373-a3eb7b8e65d7.png)

Problem being also, that after I did a complete reinstall upgrade and setup.. so now I cannot select the xcode.Project file you mentioned (the bindings?).. the rest of the installation process I can do

**Comment by java99** [comment]
When I re-add all binaries. and compile it does not find MapBox

see

![bildschirmfoto 2016-08-06 um 00 40 49](https://cloud.githubusercontent.com/assets/2676451/17452326/87368858-5b6e-11e6-9eae-63a6335ae51d.png)
![bildschirmfoto 2016-08-06 um 00 40 40](https://cloud.githubusercontent.com/assets/2676451/17452324/873147c6-5b6e-11e6-843b-d48e5753cf50.png)
![bildschirmfoto 2016-08-06 um 00 40 33](https://cloud.githubusercontent.com/assets/2676451/17452325/87345420-5b6e-11e6-844b-6db986e9b752.png)
![bildschirmfoto 2016-08-06 um 00 40 24](https://cloud.githubusercontent.com/assets/2676451/17452327/87376944-5b6e-11e6-996d-ecadcffbeebd.png)

**Comment by ouya99** [comment]
xcode 7.3

bash: /Users/alexander/Library/Developer/Xcode/DerivedData/RNApp-djrrlxepyrvqbhakuxdchetpdage/Build/Products/Debug-iphonesimulator/RNApp.app/Frameworks/Mapbox.framework/strip-frameworks.sh: No such file or directory

but build is successful with "react-native run-ios" and starting until reaching red screen with topics error msg (undefined ...)

**Comment by Taakn** [comment]
@java99 did you get it working on iOS? I have the same issue about MapboxGLManager being undefined, and I reinstalled multiple times. Thanks!

**Comment by ouya99** [comment]
yes i got i working.. install xcode 8.1 (or latest release version). and do a clean re-install and add all bindings as the documentation suggests

**Comment by Taakn** [comment]
ok thanks I've done that already and it's still not working. But what you're telling me gives me hope haha. I'm going to try again who knows.
