### ISSUE TITLE
Mapbox.framework strip-frameworks.sh

### ISSUE THREAD

**Issue by ouya99** [nitaliano/react-native-mapbox-gl#398]
How would you call this sh script? (where to find it and how to call it)

I am getting....on both xcode and command line

```
** BUILD FAILED **
The following build commands failed:
    PhaseScriptExecution Run\ Script build/Build/Intermediates/RNApp.build/Debug-iphonesimulator/RNApp.build/Script-113815A51D5625530022B566.sh

#!/bin/sh
"${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Mapbox.framework/strip-frameworks.sh"

line 2: /RNApp/ios/build/Build/Products/Debug-iphonesimulator/RNApp.app/Frameworks/Mapbox.framework/strip-frameworks.sh: No such file or directory
```

**Comment by ouya99** [comment]
solved it..

always run scripts listed below "Embed Framework" section in Build Phases...

**Comment by ghost** [comment]
What do you mean with this??

**Comment by ouya99** [comment]
Solved

**Comment by ghost** [comment]
And how?

via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=9.0.77&pv=10.12.1&source=email_footer_2]
On Do., Sep. 29, 2016 at 9:01 PM, java99 notifications@github.com wrote:
Solved

**Comment by ouya99** [comment]
in xcode:

always run scripts listed below "Embed Framework" section in Build Phases...

**Comment by ghost** [comment]
I don't understand what you mean with the "run scripts below?" Could you provide some screenshots?

**Comment by olliekav** [comment]
@alexanderniebuhr I just ran into this, drag your 'Run script' below 'Embed Frameworks'. That list is drag & droppable in in build phases.

**Comment by ghost** [comment]
Ahhh. I got the point. I'll try, but I think it already is the last item in
the list. :/  

Kind regards

--

Alexander Niebuhr

**Comment by alexanderniebuhr** [comment]
Dear, 

I guess  you  are interested in that stuff,  here  is a useful link  <http://flat.dandkstore.info/e8xtk>

Wishes, Alexander Niebuhr

**Comment by alexanderniebuhr** [comment]
Hello, 

Have you seen that place already? It's just  spectaculous, you've  got to look at it  here <http://centre.trunkdeadfall.com/e8mfg/8>

My Best, Active Planet Tours

**Comment by alexanderniebuhr** [comment]
Hi,
I know you were  looking  for  this stuff, I've found it for  you, take a look at <http://period.nudeplayer.tv/e8vwe/8>


Thx, Alexander Niebuhr

**Comment by ekimlinger** [comment]
Also seeing this issue. The "Run Scripts" section that contains: 
` "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Mapbox.framework/strip-frameworks.sh"`
is currently under "Embed Frameworks". Were you able to solve this @alexanderniebuhr ?

**Comment by ekimlinger** [comment]
Received the following error:
```
ld: warning: directory not found for option '-L/Users/<myusername>/Library/Developer/Xcode/DerivedData/<myprojectname>-axaboucbdhckaddojsnmqhfxihwy/Build/Products/Debug-iphonesimulator/react-native-mapbox-gl'
ld: library not found for -lreact-native-mapbox-gl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by nitaliano** [comment]
Have you followed the install instructions https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/install.md? `react-native-mapbox-gl` is not a library that can be linked I'm assuming you ran `react-native link`
