### ISSUE TITLE
token is required even when using custom map tiles

### ISSUE THREAD

**Issue by moimael** [nitaliano/react-native-mapbox-gl#400]
Hi,

Right now, even if I provide a custom style URL with my custom styles, the component ask me for an accessToken. It should be optional and not required in this case.

Thanks.

**Comment by ouya99** [comment]
+1

**Comment by 1ec5** [comment]
On iOS, it looks like [this line](https://github.com/mapbox/react-native-mapbox-gl/blob/3ee56f50751ed8a018a8870052f5144290acfd62/ios/RCTMapboxGL/RCTMapboxGL.m#L72) is unconditionally requiring the access token even though the Mapbox Android and iOS SDKs do not. If you aren’t using any Mapbox-hosted resources, try setting a bogus access token. If that doesn’t work and you don’t mind writing your application in Java, Objective-C, or Swift, you could also use the Mapbox Android or iOS SDK directly.

**Comment by benvium** [comment]
@1ec5 We tried setting an bogus access token as you suggested and while it works fine on iOS, we get the following screen on Android.

![image](https://cloud.githubusercontent.com/assets/288569/20105181/8c045cf8-a5c8-11e6-90cc-11ec882e37a9.png)

.. so it appears that we do need a 'real' token after all. :-(

**Comment by tmcw** [comment]
Looks like we should be able to remove the access-token checking code from this module entirely, right, since it's enforced by gl-native?

**Comment by hamidhadi** [comment]
@moimael  How did you use your custom tiles?

**Comment by norbertsongin** [comment]
Does that mean there is no way of using maps without token (even when using custom tiles) ?

**Comment by tmcw** [comment]
See the linked commit: I removed the premature token check for iOS and there wasn't one for Android. This issue is resolved; you can use your own custom tiles and styles.

**Comment by norbertsongin** [comment]
Forgot to add that im asking about Android. iOS is working without token just fine.
Does using mapbox with custom tiles count towards `50,000 map views / month, or 50,000 mobile users / month` limit?

**Comment by bcalik** [comment]
@Lichwa Did you find the answer? Does it count towards limits using custom tiles?

**Comment by tuukka** [comment]
Seems there was a similar bug in mapbox-gl-native on Android, only fixed 6 days ago? https://github.com/mapbox/mapbox-gl-native/issues/4972
