### ISSUE TITLE
mapbox gl rastersource scheme tms setting not work

### ISSUE THREAD

**Issue by wangtun** [nitaliano/react-native-mapbox-gl#403]
I have a raster source with the scheme "tms" in the style, but it seems not working.I find the Android Sdk has the funciton "setScheme". will react native support the tms setting?

![image](https://cloud.githubusercontent.com/assets/14052340/17687266/34bcc5b6-63a6-11e6-904f-7505e3b67f3b.png)

**Comment by 1ec5** [comment]
Support for the `tms` value was implemented in mapbox/mapbox-gl-native#2270 and will be in the next releases of the Mapbox Android SDK and Mapbox iOS SDK. Then this library will have to upgrade to those releases.

**Comment by wangtun** [comment]
@1ec5 thanks!

**Comment by wangtun** [comment]
@1ec5 when will you plan to support for the tms, I notice the android sdk have been upgraded

**Comment by 1ec5** [comment]
@wangtun, TMS support is in [iOS SDK v3.4.0-alpha.3](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.4.0-alpha.3). (Be sure to monitor [our releases page](https://github.com/mapbox/mapbox-gl-native/releases/) to find out when bug fixes and features make it into a release.) If you’re using the SDK directly, you can start developing against it, but note that the other changes will be quite fluid until we reach beta.
