### ISSUE TITLE
View-backed annotations

### ISSUE THREAD

**Issue by santong** [nitaliano/react-native-mapbox-gl#404]
Hi, thanks for the repo.
But I found it's really inconvenient that we can't customize annotations. 

So hope to add this feature. Thank you!

**Comment by gravitinos** [comment]
Anyone have an idea to where we can start to implement this? I'm transitioning from react-native-maps which had this feature.

**Comment by santong** [comment]
@xvalentino 
I have read the`../react-native-mapbox-gl/index.js`. It seems that the map logic are implemented by native methods.

So the only way that I can see is use remote images if we want to customize annotations. Maybe we could add some interfaces to transfer some data to display.

BUT the url image still not work on Android #391.

**Comment by digitaldavenyc** [comment]
+1 for this feature

**Comment by nunull** [comment]
+1

**Comment by aksonov** [comment]
Looks like iOS SDK master already has this feature. When we could expect usage of React Native Views for annotations?

https://github.com/mapbox/mapbox-gl-native/pull/5882

**Comment by 1ec5** [comment]
If I understand correctly, the RNMBGL component isn’t currently designed to function as a container for other views rendered by React Native. This will prevent RNMBGL from being able to take direct advantage of the view-backed annotation support added in mapbox/mapbox-gl-native#4801 for mapbox/mapbox-gl-native#1784. I don’t know if this is a fundamental limitation of React Native or just an enhancement that will need to be made to RNMBGL, but there definitely isn’t a timetable for bringing this feature over to React Native yet.

If you need view-backed annotations in the meantime and don’t mind writing your application in (truly) native iOS technologies, I’d recommend using the Mapbox iOS SDK directly in Objective-C or Swift.

**Comment by 1ec5** [comment]
It’s the same story on Android, where the Mapbox Android SDK also supports view-backed markers, but RNMBGL would have to work like a container somehow.

**Comment by aksonov** [comment]
@1ec5 I don't see any fundamental problem to support custom views, like react-native-maps package does with native MapView. I would like to try, will you accept PR when it will be finished?

**Comment by 1ec5** [comment]
@aksonov, if that’s possible, by all means, please open a PR for it. @bsudekum would be more qualified to review it, though. 😄

**Comment by aksonov** [comment]
@1ec5  please check https://github.com/mapbox/react-native-mapbox-gl/pull/421

**Comment by 1ec5** [comment]
As of #421, arbitrary React Native views can be used as view-backed annotations on iOS.

#423 takes a markedly different approach for Android. Instead of arbitrary React Native views, the developer specifies the usual annotation options (plus a few more) and those options are implemented using MarkerViews.
