### ISSUE TITLE
Cannot find symbol

### ISSUE THREAD

**Issue by ErkanSensei** [nitaliano/react-native-mapbox-gl#405]
Hello, there seems to be an issue with Mapbox on Android; I followed the manual installation instructions and am now getting this error:

a:17: error: cannot find symbol
   protected List<ReactPackage> getPackages() {
             ^
  symbol:   class List
  location: class MainActivity
/Github/ReactApp/android/app/src/main/java/com/reactapp/MainActivity.java:17: error: cannot find symbol
   protected List<ReactPackage> getPackages() {
                  ^
  symbol:   class ReactPackage
  location: class MainActivity
/Github/ReactApp/android/app/src/main/java/com/reactapp/MainActivity.java:16: error: method does not override or implement a method from a supertype
    @Override
    ^
/Github/ReactApp/android/app/src/main/java/com/reactapp/MainActivity.java:19: error: cannot find symbol
       new MainReactPackage(),
           ^
  symbol:   class MainReactPackage
  location: class MainActivity
/Github/ReactApp/android/app/src/main/java/com/reactapp/MainActivity.java:18: error: cannot find symbol
     return Arrays.<ReactPackage>asList(
                    ^
  symbol:   class ReactPackage
  location: class MainActivity
/Github/ReactApp/android/app/src/main/java/com/reactapp/MainActivity.java:18: error: cannot find symbol
     return Arrays.<ReactPackage>asList(
            ^
  symbol:   variable Arrays
  location: class MainActivity
6 errors

**Comment by PelegBerko** [comment]
I'm having the same issue.. :(

**Comment by turbochef** [comment]
bump

**Comment by polbins** [comment]
I had a similar error on react-native: 0.39.2, I just didn't implement `getPackages()` and it worked out okay.
