### ISSUE TITLE
Could not build module 'Mapbox' / Only factory methods can have the 'swift_name' attribute

### ISSUE THREAD

**Issue by etaiklein** [nitaliano/react-native-mapbox-gl#408]
Running into the titular errors while [installing manually](https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/install.md). How should I proceed from here?
![screen shot 2016-08-30 at 1 36 09 am](https://cloud.githubusercontent.com/assets/4458476/18077174/aeaf453c-6e51-11e6-8abc-e9b9d8448a45.png)

Update: Installing via cocoapods led to the same error

**Comment by etaiklein** [comment]
update: installing via cocoapods led to the same error

**Comment by etaiklein** [comment]
Solved via http://stackoverflow.com/questions/38966740/only-factor-methods-can-have-swift-name-attribute-mapbox

**Comment by lixiaodongdg** [comment]
If you are using less than or equal to Xcode7.2.1 it is recommended that you use Xcode7.3.1 or more (including Xcode7.3.1)
