### ISSUE TITLE
Undefined is not a function _reactNativeMapboxGl2.default.SetAccessToken()

### ISSUE THREAD

**Issue by chc200** [nitaliano/react-native-mapbox-gl#420]
Hello I have been trying to get my mapbox working on my android app and for some reason I cannot get rid of this.  I am running react-native-mapbox-gl 5.0.0 on an android device running 6.0.0.  I've now tried react-native versions 0.33.0 - 0.29.0 and still have the issue.

There is nothing anywhere about this.  My project builds, but on running it immediately
 crashes with this error.

![screen shot 2016-09-21 at 9 49 14 pm](https://cloud.githubusercontent.com/assets/10255146/18734717/425cce62-8045-11e6-8d5e-86786be4f049.png)

**Comment by skylarmb** [comment]
I have sort of the opposite problem. The app runs fine but when I run my tests (Jest) I get this error.
