### ISSUE TITLE
Street Names - Styles

### ISSUE THREAD

**Issue by yacomon** [nitaliano/react-native-mapbox-gl#424]
Im using the default street style for map, but the streets names are not showing well. 

![screenshot_2016-09-23-11-04-45](https://cloud.githubusercontent.com/assets/6243630/18790722/d4878258-817d-11e6-8de1-bc5682c0305c.png)

**Comment by 1ec5** [comment]
It looks like the map isn't getting a chance to finish the transition animation that allows the labels to fade in. @yacomon, can you provide additional details about the environment you're running in (which device, sim, OS version, etc.)? @tobrun, have we seen anything like this in the SDK proper lately?

**Comment by yacomon** [comment]
- Android 5.0.1
- Samsung Galaxy 4 
- Its the default Example.

**Comment by tobrun** [comment]
I haven't, need to look into doing some tests with this device
