### ISSUE TITLE
How to get the best performance at 50k+ annotations?

### ISSUE THREAD

**Issue by etaiklein** [nitaliano/react-native-mapbox-gl#425]
**1. Are there general resources/tips on getting the best performance at scale?
2. Do you have any advice on where to proceed in my app's specific case?** 

---

My redux app has 50k+ global annotations which _frequently change_ as the user filters the type of places to include (100+ types). The operation to load annotations could be faster, but I'm not sure how.

**Some ideas for performance improvements:**
1. **Clustering**. I think Mapbox has tooling for it- but we haven't adapted it to react-native-mapbox-gl yet? It seems like a big pain to build from scratch.
2. **Use fewer annotations.** If a place's distance from the center is greater than x, then don't move the annotation from `all_places_by_type` to `annotations`. Would having fewer annotations offscreen make it faster for Mapbox to re-render annotations? Or would doing that calculation just make it take longer?
3. **Always use all annotations**, but modify the annotation image to make it visible/invisible on `TOGGLE_LOCATION`. This might be a faster operation to update annotations.

---

Here is a my simplified reducer to give you a sense of how I'm fitting things together.

``` javascript
const annotate = (json) => {
  return _.map(_.flatMap(json), (place) => {
    return {
      coordinates: [parseFloat(place.lt), parseFloat(place.ln)],
      type: 'point',
      id: `${place.id}`,
      annotationImage: {...},
    }
  })
}

const filterAnnotations = (all_places_by_type, selected_place_types) => {
  return _.flatMap(_.pick(all_places_by_type, selected_place_types));
}

const toggle_place = (selected_place_types, place_name) => {
  let place_id = idNameMap[place_name];
  let index = selected_place_types.indexOf(place_id);
  (index > -1) ? selected_place_types.splice(index, 1) : selected_place_types.push(place_id);
  return selected_place_types;
}

const initialState = {
  center: {
      latitude: 40,
      longitude: -73
    },
  zoom: 11,
  annotations: [], // annotations currently used in the map. filtered from all_places_by_type
  selected_place_types: [], //ids of places the user has selected
  all_places_by_type: { //dict place_type_id: places
    1: annotate(file1),
    2: annotate(file2), 
    3: annotate(file3),
    ...
  },
};

const atlas = (state = initialState, action) => {
  switch(action.type) {

    ...

    case ActionTypes.RECEIVE_LOCATIONS:
      return Object.assign({}, state, {
        annotations: filterAnnotations(state.all_places_by_type, state.selected_place_types),
      });

    case ActionTypes.TOGGLE_LOCATION:
      return Object.assign({}, state, {
        selected_place_types: toggle_place(state.selected_place_types, action.place_name)
      });

    default:
      return state;
  }
}
```

**Comment by tmcw** [comment]
Step one would definitely be _profiling_ and figuring out what step performance is struggling at: is it loading data from JavaScript to native? Processing markers? Map interaction after markers are loaded? Each of these steps points to a different place to optimize.

**Comment by etaiklein** [comment]
We solved this problem with a take on (2).

On a load or move event, we grab the 200 closest data points _from the server_. If more than 200 _could_ be displayed on a map at the given zoom level, then we show the user an alert to zoom in more. This turns out to be a good balance of performant, lightweight and simple.

**Comment by club9822** [comment]
Try to  implement without lodash o runderscore.
In node. Js performance tips, discouraged ged using this utilities

**Comment by h2soheili** [comment]
Try to  implement without lodash or underscore.
In node. Js performance tips, discouraged ged using this utilities

**Comment by etaiklein** [comment]
> Try to implement without lodash or underscore.
> In node. Js performance tips, discouraged ged using this utilities

Agreed! I’ve learned a lot in the years since I posted this.
Check out https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore
