### ISSUE TITLE
Navigating map very slow on Android

### ISSUE THREAD

**Issue by ouya99** [nitaliano/react-native-mapbox-gl#427]
Hello,

I am testing on a Nexus5 with rn-mapbox-gl "version": "5.0.0".

The zoom (in and out) is very slow and unresponsive. Same for "pan". 

I only have 3 markers (annotations) on the map.

Any idea why it is so slow?

Thanks
java99

**Comment by ouya99** [comment]
solved it

**Comment by Ulydev** [comment]
Could you share what solved your problem? I'm having the same issue :(

**Comment by ouya99** [comment]
check your rendering and whether you have additional layers that should not be rendered every time. i had some widgets (not related to this component) which cause a render overflow
