### ISSUE TITLE
Annotation z-index

### ISSUE THREAD

**Issue by digitaldavenyc** [nitaliano/react-native-mapbox-gl#430]
Is it possible to control the z-index of map markers? When markers are close together, it is very difficult to see which one is active, having control of the z-index would help the user experience quite a bit.

**Comment by mrooding** [comment]
I'm interested in the same feature. It seems that they have not yet implemented this in mapbox-gl-native according to [#1728](https://github.com/mapbox/mapbox-gl-native/issues/1728)

**Comment by 1ec5** [comment]
Correct, we haven’t implemented this feature yet for non-view-backed annotations. However, as I explain in https://github.com/mapbox/mapbox-gl-native/issues/1728#issuecomment-250844066, it might be possible for this project to implement z-index options for the view-based annotations that were added to iOS in #421 or the MarkerView annotations being added to Android in #423.

**Comment by tmcw** [comment]
Thanks for the bug report - folding this into the previous request at #411 as well as the upstream issues Minh refers to above.
