### ISSUE TITLE
Rendering an icon with heading

### ISSUE THREAD

**Issue by mrooding** [nitaliano/react-native-mapbox-gl#431]
I'm trying to create an icon of a car which shows a heading arrow or indicator around the car. For this, I started looking at the MapBox user location indicator and noticed that I could use the `MarkerView` annotation provided by the Android SDK and I implemented that on Android in #423. With this PR I can rotate an icon, but in my case I want the icon to be the front of a car which should obviously not pivot itself. 

I tried rendering the car itself as a regular `Marker` and a heading arrow as a `MarkerView`, but somehow it seems that `Marker` and `MarkerView` are positioned differently from each other when given the same latitude and longitude.

I'd love to know how I would be able to achieve this.

**Comment by EricPKerr** [comment]
@nitaliano Know this was closed due to inactivity, but what's the recommended way to handle this? Rotating an icon/image?

Thanks for your help here

**Comment by nitaliano** [comment]
@EricPKerr SymbolLayer has an `iconRotate` style property https://github.com/mapbox/react-native-mapbox-gl/blob/master/docs/SymbolLayer.md#name-11

**Comment by EricPKerr** [comment]
@nitaliano works - thanks
