### ISSUE TITLE
Rendering MapView in a Navigator scene

### ISSUE THREAD

**Issue by rlski** [nitaliano/react-native-mapbox-gl#432]
Hi everyone ! 

I was wondering if anyone tried to render a MapView in a Navigator scene. I'm fairly new to RN so I might be missing something but if I set the access token and render the MapView outside of the Navigator it loads without any problem. However if I want to load it in a specific scene of my app it doesn't seem to load at all, e.g I don't receive anything on the onStartLoadingMap callback prop.

**Comment by dapetcu21** [comment]
Hi. In my app, the MapView worked perfectly in a Navigator without doing anything special. Just make sure you set the access token before the component is mounted (I do it right before I declare my component).

One thing to note, though, while using a MapView (or any other expensive to render component for that matter) in a Navigator, is that it might slow down your page entry transition. What you should do is something like this:

``` jsx
state = { placeholder: true };

componentDidMount() {
  InteractionManager.runAfterInteractions(() => { 
    // This gets called after all Navigator transitions finished
    this.setState({ placeholder: false });
  });
}

render() {
  if (this.state.placeholder) { 
    return <View style={{ backgroundColor: '#somethingplaceholdery' }}/>;
  }
  return <MapView ...allYourFancyProps/>;
}
```

**Comment by rlski** [comment]
I got it working by tweaking the styles of the container that were messing with the layout. Sorry for the disturbance, I should have made more tests before opening an issue. Thanks a lot for the perf tips, I'll definitely look into it.
