### ISSUE TITLE
Example doesn't work: "undefined is not an object" (MapboxGLManager.mapStyles)

### ISSUE THREAD

**Issue by fab1an** [nitaliano/react-native-mapbox-gl#434]
When I try to run the example I get the following error:

![screen shot 2016-10-03 at 15 01 41](https://cloud.githubusercontent.com/assets/55547/19038174/a0df3298-897a-11e6-9e82-96d5dd0d9661.png)

**Comment by fab1an** [comment]
Ok, I forgot to add the native libraries…

**Comment by aavalos41** [comment]
I know this is an old, closed ticket, but I am having a similar issue. What do you mean with 'add the native libraries'?
