### ISSUE TITLE
'children' how to use this prop?

### ISSUE THREAD

**Issue by anupkale1984** [nitaliano/react-native-mapbox-gl#436]
I have tried it using in following ways but does not show children on Map View
`</MapView> 
         <Annotation>
           <Text> I AM HERE </Text>
         </Annotation>
  </MapView>`

**Comment by tmcw** [comment]
Have you checked out the [example code](https://github.com/mapbox/react-native-mapbox-gl/blob/master/example.js)? Annotations are provided as a prop called `annotations`: they are not provided as children.

**Comment by corymsmith** [comment]
@anupkale1984 This only works on iOS now and I believe that each annotation has to have a unique `id` and a coordinate property as specified here: https://github.com/mapbox/react-native-mapbox-gl/blob/a77830dea5f5b035c9364e0c419b603f02f639bf/Annotation.js

**Comment by vbuch** [comment]
This feature seems not to have been merged in 5.x so you will need to use master if you want it @anupkale1984
