### ISSUE TITLE
showsUserLocation Disables Map Markers

### ISSUE THREAD

**Issue by digitaldavenyc** [nitaliano/react-native-mapbox-gl#437]
Enabling `showsUserLocation` has been causing issues for us because the radar animation effect is on occasion expanding way beyond what it typically does. If there are map marker in the radius of the blue userLocation animation, those markers are not clickable. This is actually a serious problem and we had to disable `showsUserLocation`.  

Radius way to big
![thumb_img_1696_1024](https://cloud.githubusercontent.com/assets/243799/19254324/4cc677b0-8f20-11e6-900b-707a7de1eaab.png)

Normal Radius
![screen-shot-2016-10-10-at-5 26 01-pm](https://cloud.githubusercontent.com/assets/243799/19254363/cd453eb2-8f20-11e6-99db-f2b952ad71b9.png)

**Comment by digitaldavenyc** [comment]
I can't believe no one has even responded to this....

**Comment by tmcw** [comment]
Hi Dave,

It's been 10 days since you opened this issue. Given that this is an issue on an open source repository and not a paid support channel, please allot some patience for a reply, or take the time to dig deeper and potentially find the cause of the issue for yourself.

Thanks,
- Tom

**Comment by digitaldavenyc** [comment]
someone from mapbox actually just responded this way to an unanswered question .... wow

**Comment by digitaldavenyc** [comment]
I'd be happy to start investigating if there was some mapbox to at least start a discussion as to a potential cause.

**Comment by tmcw** [comment]
Hi Dave,

Sorry if that seemed curt: this project is [experimental](https://github.com/mapbox/react-native-mapbox-gl#support), and, while we do guarantee response times for official products and under [help](https://www.mapbox.com/help/), this isn't either of those things. The support for this project is a labor of love for now, by myself and a few interested contributors. And, alas, that love fades when the tone of support issues and their follow-ups doesn't sound friendly, and yours certainly didn't, at least to my late-night cognition.

In terms of this issue, [showsUserLocation](https://github.com/mapbox/react-native-mapbox-gl/blob/933e70007b61066657336ff03eb845a405081f28/ios/RCTMapboxGL/RCTMapboxGL.m#L386) goes straight down to the native object, and it looks like [issue 5816](https://github.com/mapbox/mapbox-gl-native/pull/5816) recently changed hit-testing in GL Native and [5894](https://github.com/mapbox/mapbox-gl-native/pull/5894) followed that up, so it's potentially a matter of whether RN is up to date with those fixes.

Hope that helps,
- Tom

**Comment by digitaldavenyc** [comment]
Tom,
I was just sounding an alarm that there is a problem that was getting no attention that seemed critical, if it seemed unfriendly, it was not my intention. I've been a huge advocate of the mapbox platform and I do appreciate the work that has been put into it this repo. I hope it is able to get much more attention because it has been a huge asset to us.

Thank you for relaying info on other related issues, perhaps we can look into this and work on PR.

Cheers,
Dave

**Comment by markusekblad** [comment]
Any updates on this?

**Comment by AdamJakiela** [comment]
+1

**Comment by ManAnRuck** [comment]
+1
