### ISSUE TITLE
[question] dotted line for type: polyline

### ISSUE THREAD

**Issue by kiszadr** [nitaliano/react-native-mapbox-gl#438]
Hi guys,
I need a dotted line, something like `line-dasharray` in [https://www.mapbox.com/mapbox-gl-style-spec/](url)
Can I/ How can I achieve this?

Regards

**Comment by tmcw** [comment]
Have you tried using the `line-dasharray` property in a style? Does that not work, or do something other than what you intend?

**Comment by kiszadr** [comment]
Thanks for your comment, but I'm not sure where should I add a style:

`[{
  **coordinates**, // required. For type polyline and polygon must be an array of arrays. For type point, single array with 2 coordinates

  **type**, // required. One of 'point', 'polyline' or 'polygon'

  **title**, // optional. Title string. Appears when marker pressed

  **subtitle**, // optional. Subtitle string. Appears when marker pressed

  **fillAlpha**, // optional. number. Only for type=polygon. Controls the opacity of the polygon

  **fillColor**, // optional. string. Only for type=polygon. CSS color (#rrggbb). Controls the fill color of the polygon

  **strokeAlpha**, // optional. number. Only for type=polygon or type=polyline. Controls the opacity of the line

  **strokeColor**, // optional. string. Only for type=polygon or type=polyline. CSS color (#rrggbb). Controls line color.

  **strokeWidth**, // optional. number. Only for type=polygon or type=polyline. Controls line width.

  **id**, // required. string. Unique identifier used for adding or selecting an annotation.

  **annotationImage**: { // optional. Marker image for type=point
    source: {
      uri // required. string. Either remote image URL or the name (without extension) of a bundled 

image
    },
    height, // required. number. Image height
    width, // required. number. Image width
  },

  **rightCalloutAccessory**: { // optional. iOS only. Clickable image that appears when type=point marker pressed
    source: {
      uri // required. string. Either remote image URL or the name (without extension) of a bundled 
image
    },
    height, // required. number. Image height
    width, // required. number. Image width
  },
}]`

[https://github.com/mapbox/react-native-mapbox-gl/blob/4ef787d8f99a1b917f06141da33125b4a01f1cd0/API.md](url)

Any idea?
Thanks!

**Comment by kiszadr** [comment]
I found this: [https://www.mapbox.com/help/style-line-layer-studio/](url)
Looks like this solve my issue.
Regards
