### ISSUE TITLE
Installation via react-native link?

### ISSUE THREAD

**Issue by wafisher** [nitaliano/react-native-mapbox-gl#441]
Are there any plans to allow this to be installed via `react-native link`? I see no discussion of this but it seems like the obvious easy way to allow users to install this.

Thanks!

**Comment by tmcw** [comment]
Do you mean rnpm link? https://facebook.github.io/react-native/docs/linking-libraries-ios.html

**Comment by wafisher** [comment]
I think it's the same thing. I'm pretty sure rnpm has been [rolled into](https://github.com/rnpm/rnpm) React Native Core.

**Comment by nickells** [comment]
`react native link` just runs a `rnpm link` -- btw, I've tried installing it this way and it seems to work on Android, at least.

**Comment by wafisher** [comment]
Yeah it works on iOS. No problems so far for me so it probably just works but would love someone to confirm that.

**Comment by ryanthegiantlion** [comment]
react-native link did not work for me

A few of the steps in https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/install.md were not performed for me by react-native link. (2, 3 and 5)

**Comment by etaiklein** [comment]
rnpm link doesn't work for me for ios, but does for android
