### ISSUE TITLE
[android] Warning RCTMapboxAnnotation does not exist

### ISSUE THREAD

**Issue by ericpalakovichcarr** [nitaliano/react-native-mapbox-gl#443]
I'm using the latest source code from master at the time of posting this issue.  When running my app in an emulator, React gives me a yellow box with `Warning: Native component for "RCTMapboxAnnotation" does not exist.`.

Briefly looking through the source code, I don't see a java file with the native `RCTMapboxAnnotation` implementation.  I have no experience bridging native code with React Native, so it's quite possible I just don't understand how this is supposed to work.

Does anybody else see this warning, or is it just me?

**Comment by marvinernst** [comment]
Hey, I get the same error.

**Comment by Shane98c** [comment]
@bigsassy @devilop3rz 
Did either of you find a solution to this issue?

**Comment by ericpalakovichcarr** [comment]
@Shane98c No, I haven't.  I've just been ignoring the warning for now.

**Comment by dlvx** [comment]
Getting the same warning, no errors tho

**Comment by UrbanChrisy** [comment]
I have the same issue, any one found out a work around?

**Comment by mmckinley8** [comment]
any update on this?

**Comment by ryanwilliams** [comment]
I think this is also why custom annotation images don't work on Android. Duplicate of issue https://github.com/mapbox/react-native-mapbox-gl/issues/493
