### ISSUE TITLE
Build as jar

### ISSUE THREAD

**Issue by fab1an** [nitaliano/react-native-mapbox-gl#445]
Is it really necessary to compile this from source?
- Android Studio automatically imports it a module, that I don't really need.
- `build.gradle` is constantly outdated and using old android-gradle-plugin and old buildTools etc.

It should be easy to ship the few classes as a jar so I can include it along my normal dependencies.

**Comment by tmcw** [comment]
Certainly open to the possibility, though I don't know how this will mix with the module's internals - the main component of this module is a C++ extension connected via JNI... as long as we can compile it in such a way that it's cross-platform and can be installed automatically when you install the module, I'm game. Have you seen any examples of RN modules doing that or documentation for how they could do that?

**Comment by fab1an** [comment]
As far as I see the native-code is not in this project, but mapbox-sdk, so JNI should not be a problem.

I found this issue: https://github.com/facebook/react-native/issues/2679

As far as I see it the way to go would be to compile the code to an Android library like described here: https://developer.android.com/studio/projects/android-library.html

And then publish the jar or add it to node_modules: http://stackoverflow.com/questions/20700053/how-to-add-local-jar-file-dependency-to-build-gradle-file

**Comment by fab1an** [comment]
I think this should more or less suffice:

```
task clearJar(type: Delete) {
    delete 'build/outputs/ProjectName.jar'
}

task makeJar(type: Copy) {
    from('build/intermediates/bundles/release/')
    into('build/outputs/')
    include('classes.jar')
    rename ('classes.jar', 'ProjectName.jar')
}
```

**Comment by fab1an** [comment]
Well no, if I build that jar and include it I get the following error: 

![screen shot 2016-11-04 at 11 40 08](https://cloud.githubusercontent.com/assets/55547/20002899/9f731ef2-a283-11e6-88be-0f3ef9896255.png)

This are the contents of the jar, maybe `R.class` etc. are needed as well?

```
$> jar tf react-native-mapbox-gl.jar 
com/mapbox/reactnativemapboxgl/BuildConfig.class
com/mapbox/reactnativemapboxgl/ReactNativeMapboxGLManager$1CallbackRunnable.class
com/mapbox/reactnativemapboxgl/ReactNativeMapboxGLManager.class
com/mapbox/reactnativemapboxgl/ReactNativeMapboxGLModule$1.class
com/mapbox/reactnativemapboxgl/ReactNativeMapboxGLModule$2.class
com/mapbox/reactnativemapboxgl/ReactNativeMapboxGLModule$3$1.class
com/mapbox/reactnativemapboxgl/ReactNativeMapboxGLModule$3.class
com/mapbox/reactnativemapboxgl/ReactNativeMapboxGLModule$4$1.class
com/mapbox/reactnativemapboxgl/ReactNativeMapboxGLModule$4.class
com/mapbox/reactnativemapboxgl/ReactNativeMapboxGLModule$OfflineRegionProgressObserver$1.class
com/mapbox/reactnativemapboxgl/ReactNativeMapboxGLModule$OfflineRegionProgressObserver.class
com/mapbox/reactnativemapboxgl/ReactNativeMapboxGLModule$OfflineRegionsInitialRequest$1.class
com/mapbox/reactnativemapboxgl/ReactNativeMapboxGLModule$OfflineRegionsInitialRequest.class
com/mapbox/reactnativemapboxgl/ReactNativeMapboxGLModule.class
com/mapbox/reactnativemapboxgl/ReactNativeMapboxGLPackage.class
com/mapbox/reactnativemapboxgl/ReactNativeMapboxGLView$1.class
com/mapbox/reactnativemapboxgl/ReactNativeMapboxGLView$1CameraCallback.class
com/mapbox/reactnativemapboxgl/ReactNativeMapboxGLView$RegionChangedThrottleRunnable.class
com/mapbox/reactnativemapboxgl/ReactNativeMapboxGLView$TrackingModeChangeRunnable.class
com/mapbox/reactnativemapboxgl/ReactNativeMapboxGLView.class
com/mapbox/reactnativemapboxgl/RNMGLAnnotationOptions.class
com/mapbox/reactnativemapboxgl/RNMGLAnnotationOptionsFactory.class
com/mapbox/reactnativemapboxgl/RNMGLMarkerOptions.class
com/mapbox/reactnativemapboxgl/RNMGLPolygonOptions.class
com/mapbox/reactnativemapboxgl/RNMGLPolylineOptions.class
```
