### ISSUE TITLE
NSScanner: nil string argument

### ISSUE THREAD

**Issue by wafisher** [nitaliano/react-native-mapbox-gl#448]
The following error is logged to the console when adding a polyline annotation with no `strokeColor` set.

```
NSScanner: nil string argument
```

Take a look at the [offending function](https://github.com/mapbox/react-native-mapbox-gl/blob/933e70007b61066657336ff03eb845a405081f28/ios/RCTMapboxGL/RCTMapboxGL.m#L649). Happy to create a PR to fix this very locally at that function though someone with more familiarity with the codebase might want to make a broader change.

**Comment by tmcw** [comment]
Yep, we should have a `nil` check there, happy to accept a PR implementing one - thanks!
