### ISSUE TITLE
Adding Mapbox.framework in step 2 in iOS setup instructions results in 5000+ line diff, use symlink instead

### ISSUE THREAD

**Issue by skylarmb** [nitaliano/react-native-mapbox-gl#451]
In [step 2 of the iOS setup instructions](https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/install.md#2-adding-mapboxframework), entitled `Adding Mapbox.framework` says to add `node_modules/react-native-mapbox-gl/ios/Mapbox.framework` to `General -> Embedded Binaries` and select the `Copy items if needed` checkbox. For me, this indeed copies all the files to a new `Mapbox.framework` folder in the root of the project, resulting in a 5000+ line diff in source control. I tried without selecting the 'Copy items if needed' checkbox and the project did not build, so it looks like that instruction was intentional. 

<img width="808" alt="screen shot 2016-11-04 at 4 18 19 pm" src="https://cloud.githubusercontent.com/assets/7543705/20025305/57e8bbce-a2aa-11e6-99c9-04cf2801d273.png">

What I did instead was made a symlink `Mapbox.framework` in the project root to `../node_modules/react-native-mapbox-gl/ios/Mapbox.framework`. I then added the symlinked `Mapbox.framework` to `General -> Embedded Binaries` instead. Everything works fine, no massive diff, everything just points at the `Mapbox.framework` shipped with this library instead of a copy of it in your own source control. I don't know why this method works but XCode's built in 'create folder references' option doesn't work.

**Comment by tmcw** [comment]
As far as I know/have been told, the one case where _Copy items if needed_ will copy items is if the files are on a different drive than the project. Is that the case here?

**Comment by skylarmb** [comment]
Nope. Same drive. Just running on my macbook... Although I have tested this with dragging other things into my xcode project and it _always_ seems to copy the items if I check that box. Could be just my system.

**Comment by skylarmb** [comment]
I am happy to close this issue if you like as it has been 2 weeks an no one else seems to have had the same problem.
