### ISSUE TITLE
userTrackingMode w/ Mapbox.userTrackingMode.followWithHeading does not yield icon w/ heading

### ISSUE THREAD

**Issue by timfpark** [nitaliano/react-native-mapbox-gl#458]
Using a MapView with userTrackingMode w/ Mapbox.userTrackingMode.followWithHeading does not yield icon that indicates heading but instead the same "pulsing blue dot" for the current location.

eg. 

<MapView
    ...
    userTrackingMode={Mapbox.userTrackingMode.followWithHeading}
    ...
/>

This is with 5.1.0 of the library and React Native 0.36.

**Comment by timfpark** [comment]
You can also repro this with example.js and clicking "Set userTrackingMode to followWithHeading".

**Comment by Guitouxx** [comment]
Hello,
Same error for me. Do you have any news on this point @timfpark  ?

**Comment by timfpark** [comment]
Nope - I'm willing to take a stab at fixing it if one of the maintainers will point me in the right direction as to what might be going wrong though and things to investigate.

**Comment by alexbonhomme** [comment]
Hey guys,

I've observed a curious thing. During the first execution the heading was working, but I've clicked on the compass icon and after that it was gone forever. I'm unable to active it again :(

EDIT : In fact, it appear like 1s, and disappear after. Like it was repainted by an other function.

**Comment by phuonglam1510** [comment]
Hi,

I am facing the same issue. I even had to add the arrow to show the direction myself but it does not work properly. Now i find down the solution. Look like at the initial loading the map turn off tracking mode. That why we see the arrow for around one second and gone forever. I try to turn it on dynamically but it does not work. But adding setTimeout will work perfectly


```javascript
recenter() {
            setTimeout(() => {
                this.setState({
                    userTrackingMode: Mapbox.userTrackingMode.followWithHeading
                });
            }, 500);
        }
    }
```
in the re-center button i turn on the tracking mode again but put it in SetTimeout work perfectly.

I don't know if it is still an bug or not i am working with version 5.2.0
