### ISSUE TITLE
Android Setup: Step 2 (option B) - Error

### ISSUE THREAD

**Issue by lukezirngibl** [nitaliano/react-native-mapbox-gl#459]
React-Native 0.37

Getting this error after making changes to the MainActivity.java.

`error: method does not override or implement a method from a supertype @Override`

**Comment by taufiqibrahim** [comment]
@lukezirngibl I also faced the same problem when following the guide. So, the guide is telling us to add some lines to MainActivity.java
However, it brings me the same error as you got.
So, I just did some trials n errors.

This is what I did:

1. No change in MainActivity.java
2. Add this line in MainApplication.java
`import com.mapbox.reactnativemapboxgl.ReactNativeMapboxGLPackage;`

3. Change this lines from
```
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage()
      );
    }
```

into:

```
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new ReactNativeMapboxGLPackage()
      );
    }
```

I don't know what is happening, but in my case it works.
