### ISSUE TITLE
Oblique view does not show topography

### ISSUE THREAD

**Issue by timfpark** [nitaliano/react-native-mapbox-gl#464]
When you use the two finger gesture on the map to adjust the straight down view to a more oblique view of the map the perspective changes but you do not get a 3D effect with the topology of the map in view.

I am using the map in an outdoor application and it would be great to be able to represent the surrounding terrain such that the user can visualize it to help navigate it.

**Comment by tmcw** [comment]
Hi Tim,

Thanks for the question. Mapbox GL Native does not currently support 3D topography: we just launched building extrusion support and topography is a few more steps away. We're working on this quietly for now, and the change will land in [Mapbox GL Native](https://github.com/mapbox/mapbox-gl-native) first.

- Tom
