### ISSUE TITLE
NPM out of sync with project

### ISSUE THREAD

**Issue by ddolheguy** [nitaliano/react-native-mapbox-gl#471]
Hey Guys,

I just wanted to advise that the NPM package is missing commits against the release number in this project.

For example, the latest version 5.1.0 is missing the below commit (which is part of 5.1.0 GitHub tagging):
- https://github.com/mapbox/react-native-mapbox-gl/pull/467/files/0aabca07cafaf78e717d58945e825520ccf19f90#diff-d0ace68cb3e436e36c7bb0bca305815c

I noticed the tagging in Github of 5.1 was also complete after the NPM package was released so this might have something to do with it?

Anyway for the time being, I'm using the GitHub reference to master as my NPM ref

**Comment by daltondanis** [comment]
+1
