### ISSUE TITLE
How to get Directions and Navigation in react-native using react-native-mapbox-gl

### ISSUE THREAD

**Issue by shivaakumar** [nitaliano/react-native-mapbox-gl#478]
I have been trying to implement map with navigation/direction in react-native-mapbox-gl. But How to get this directions thing in here.
Even if we use mapbox/directions api to get direction result, how do we use those in our code. There seems to be no attribute or method in API documentation also.

**Comment by sntran** [comment]
It does not support, but you can simply render a polyline annotation from your direction result.

**Comment by tsemerad** [comment]
This component is strictly for displaying and manipulating a Mapbox GL map view. You can easily use the navigation and direction APIs by calling them as you normally would from Javascript, then passing the resulting route into the Mapbox component via the [annotations](https://github.com/mapbox/react-native-mapbox-gl/blob/master/API.md#annotations) prop. Also take a look at the [example](https://github.com/mapbox/react-native-mapbox-gl/blob/master/example.js#L116) where it shows setting annotations.

**Comment by ankitgauravapporio** [comment]
hello anybody alive ,the provided link is expired @ tsemerad , can anyone please guide how to implement polylines on mapbox using geo JSON
