### ISSUE TITLE
Doesn't work on RN 0.39 Android

### ISSUE THREAD

**Issue by pewh** [nitaliano/react-native-mapbox-gl#480]
It shows `undefined is not an object MapboxGLManager.mapStyles` redbox. I have followed the instruction, I also have make sure native modules is installed. I've tried clear watchman, restart emulator, etc. 
I have create example on https://github.com/pewh/mapbox-example

**Comment by Taakn** [comment]
@pewh did you get it working on iOS? I have the same issue there (manual install)

**Comment by pewh** [comment]
Unfortunately, I didn't have mac for test

**Comment by Taakn** [comment]
ok too bad thanks!

**Comment by lyw0149** [comment]
You should try `rnpm link` after instruction.
