### ISSUE TITLE
undefined is not an object (evaluating 'MapboxGLManager.mapstyles')

### ISSUE THREAD

**Issue by Taakn** [nitaliano/react-native-mapbox-gl#483]
I'm getting this issue on iOS (master). I've followed multiple times the instruction (manual install) but nothing works. Everything works fine on Android. Is there a known issue on iOS?

Thanks so much

**Comment by Taakn** [comment]
React Native 0.36, mapbox gl 5.1.0. After multiple installs it still doesn't work. The project builds fine.  If anyone has suggestions I'll be happy to hear them

**Comment by timfpark** [comment]
I'm using that same combination (RN 0.36 with 5.1.0) in my app and it is working for me.   Can you share any more details?

**Comment by AmirolAhmad** [comment]
Im also facing the same issue:

```zsh
"dependencies": {
    "react": "15.4.1",
    "react-native": "^0.41.2",
    "react-native-mapbox-gl": "^5.1.0"
}
```

```zsh
$ react-native link
rnpm-install info iOS module react-native-autocomplete is already linked
rnpm-install info Android module react-native-device-info is already linked
rnpm-install info iOS module react-native-device-info is already linked
rnpm-install info Android module react-native-image-picker is already linked
rnpm-install info iOS module react-native-image-picker is already linked
rnpm-install info Android module react-native-mapbox-gl is already linked
rnpm-install info iOS module react-native-mapbox-gl is already linked
rnpm-install info iOS module react-native-multi-slider is already linked
rnpm-install info iOS module react-native-simple-toast is already linked
rnpm-install info Android module react-native-tcp is already linked
rnpm-install info iOS module react-native-tcp is already linked
rnpm-install info Android module react-native-udp is already linked
rnpm-install info iOS module react-native-udp is already linked
rnpm-install info Android module react-native-vector-icons is already linked
rnpm-install info iOS module react-native-vector-icons is already linked
rnpm-install info Android module react-native-view-shot is already linked
rnpm-install info iOS module react-native-view-shot is already linked
rnpm-install info Linking assets to ios project
rnpm-install info Linking assets to android project
rnpm-install info Assets have been successfully linked to your project
```

**Comment by nirabpudasaini** [comment]
This happens to me if i forget to do react-native --link and create a new build

**Comment by MathieuDebit** [comment]
Same issue for me on iOS:

```json
"dependencies": {
   "react": "~15.4.0",
   "react-native": "0.41.2",
   "react-native-mapbox-gl": "^5.1.0"
}
```

I followed the [Manual installation process](https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/install.md) and simply included `MapView` in a basic project:

```js
'use strict';
/* eslint no-console: 0 */

import React, { Component } from 'react';
import Mapbox, { MapView } from 'react-native-mapbox-gl';
import { AppRegistry, Text } from 'react-native';

class MapExample extends Component {
  render() {
    return (
      <Text>Mapbox</Text>
    );
  }
}

AppRegistry.registerComponent('NativeMapbox', () => MapExample);
```

I don't have any errors during the build process.

**Comment by peitalin** [comment]
Any updates on this issue?

**Comment by Taakn** [comment]
I contacted support last month and they told me that React Native was not being actively maintained. They need to figure out how to move forward with RN and recommend to use the native iOS and Android SDKs instead.

**Comment by Taakn** [comment]
My memory was a little fuzzy about the exchange so here is the exact reply from support given the reactions to my last comment. I was inquiring about the future of this repo since I was seeing a bunch of open issues and not a lot of updates. I was also stressing the growing popularity of React and React Native and if they were going to allocate more resources.

> Hey thanks for the feedback, which I've passed to our mobile team. The React Native repo is indeed a work in progress and there's internal discussion around how to best maintain the project, if it will stay under the Mapbox umbrella. Can you use the native iOS and Android SDKs, without React?

**Comment by Taakn** [comment]
It ended up working for me on both iOS and Android. This is my current configuration, the only one that's actually working. Please note that it wasn't working with RN 0.39.0 but it did work with RN 0.39.2:

```
"react": "^15.4.2",
"react-native": "^0.39.2",
"react-native-mapbox-gl": "^5.1.0",
```

**Comment by igor9silva** [comment]
I'm still having this issue on 0.44.

**Comment by josdejong** [comment]
@igor9silva  I had this issue too, resolved it by running `react-native link` to install native dependencies in the ios/android projects

**Comment by Matus-Stastny** [comment]
Same issue here. Running `react-native link` didn't help.
RN version: 0.45
I am using [example](https://github.com/mapbox/react-native-mapbox-gl/blob/master/example.js) app and it works well with Andriod.

**Comment by digitaldavenyc** [comment]
@here also having a similar issue using RN version: `0.44` and RNMBGL `5.2.0`

**Comment by pkshefi** [comment]
react-native link react-native-simple-toast
react-native link

tried , seems not working,
