### ISSUE TITLE
How can I change the language of the map?

### ISSUE THREAD

**Issue by shaharl** [nitaliano/react-native-mapbox-gl#485]

**Comment by ddolheguy** [comment]
Looks like unless I'm wrong this functionality is only available for Android (not iOS) and isn't available in this library.  You can raise a PR though :)

https://www.mapbox.com/help/change-language/

**Comment by alexey-kuznetsov** [comment]
Is there any progress in this issue?

**Comment by nitaliano** [comment]
This should be supported now that the runtime and data driven styling api is implemented.

**Comment by henrikra** [comment]
Can this be reopened? Now there is api for the language: https://www.mapbox.com/help/change-language/#change-label-language-dynamically
So `localizesLabels` should be set to true.

**Comment by nitaliano** [comment]
`mapView.propTypes.localizeLabels` have been merged into master going to close out

**Comment by proffesor888** [comment]
Hey,
I'm setting localizeLabels to True but nothing changes. For example, default language on the phone is Russian. But town names and places are still in English. Is there any ways to change language of city names ?

**Comment by PetrVasilev** [comment]
The same issue with @proffesor888

**Comment by ancyrweb** [comment]
Same here, only on Android though.

**Comment by totoblabla1** [comment]
Ребят, удалось найти решение?

**Comment by thomasgauvin** [comment]
Has there been an update regarding this issue? localizeLabels does not work

**Comment by benkeegan98** [comment]
has there been any resolution here? would like to be able to dynamically toggle localizeLabels, or at least toggle the language of the map by accessing the layer styles like is possible in Mapbox GL JS. is there any solution for this?
