### ISSUE TITLE
RN0.40 conversion

### ISSUE THREAD

**Issue by aksonov** [nitaliano/react-native-mapbox-gl#486]
All iOS components now must use different 'import' paths for React (like '#import <React/RCTView.h> instead of '#import 'RCTView.h'), any plans to release new version for RN 0.40?

**Comment by sntran** [comment]
There is a [PR](https://github.com/mapbox/react-native-mapbox-gl/pull/487) to support RN 0.40. However, there seems to be an issue with installation using CocoaPods.

**Comment by and01** [comment]
+1

**Comment by beachygreg** [comment]
+1

**Comment by ddolheguy** [comment]
Check out the current PR going through the system https://github.com/mapbox/react-native-mapbox-gl/pull/487

**Comment by corymsmith** [comment]
PR #487 is now merged into master, is there a plan to publish 5.2.0 to NPM any time soon?

**Comment by gardner** [comment]
Thanks for this. I was able to use the following to get mapbox working.

```
react-native init NewProjects --version react-native@0.39.0
mv NewProjects mobile && cd mobile
npm install --save react-native-mapbox-gl
pod init ios/NewProject.xcodeproj
```

Then add `  pod 'RCTMapboxGL', :path => 'node_modules/react-native-mapbox-gl/ios'` to Podfile and run:

```
pod install 
react-native run-ios
```

Then I got:
`** BUILD SUCCEEDED **`

It will be great when 5.2 gets published to npm.
