### ISSUE TITLE
Initial Center Coordinates not working?

### ISSUE THREAD

**Issue by chc200** [nitaliano/react-native-mapbox-gl#488]
So I am trying to set my initial center coordinates for mapbox so they are not 0,0. On the api it says mapbox expects a prop of

`initialCenterCoordinate object  Optional    Initial latitude/longitude the map will load at.    { latitude:0, longitude: 0 }`
So I am doing
`<Mapbox initialCenterCoordinate={latitude: 40.444328, longitude: -79.953155} .... other props/>`

This is giving me an error on that line saying unexpected token, expecting }.

Whenever I do something like
`<Mapbox initialCenterCoordinate={{latitude: 40.444328, longitude: -79.953155}} .... other props/>`

It still sets my initial spot to 0,0. Anyone have any ideas?

**Comment by bebz229** [comment]
What happens if you add this prop `userTrackingMode={ Mapbox.userTrackingMode.follow }`?
-> forget about that. I think i  misunderstood you.

What if you use MapView instead of Mapbox ?
```javascript
import Mapbox, { MapView } from 'react-native-mapbox-gl';

<MapView initialCenterCoordinate={{latitude: 40.444328, longitude: -79.953155}} .... other props/>
```

**Comment by chc200** [comment]
When I do that I get this error 
![screen shot 2017-01-13 at 1 24 12 pm](https://cloud.githubusercontent.com/assets/10255146/21940727/a0791c1a-d993-11e6-9af0-5e57d3cf8b11.png)

**Comment by ddolheguy** [comment]
Are you sure this is MapBox error?  The term 'Navigator' indicates the error is within your component and not the Mapbox control itself.

**Comment by chc200** [comment]
@ddolheguy whenever I do it how I originally have everything setup the initial center coordinates don't work at all.  When I try to do what jude said I have that error.  I'm not sure why that occurs however that seems like it's issues with importing mapbox. 

Currently this is what I have

```
var Mapbox = require('react-native-mapbox-gl');

import mixins from 'es6-mixins';

mixins([Mapbox.Mixin], this, {mergeDuplicates: false, warn: false});


<Mapbox
        initialCenterCoordinate={{latitude: 40.444328, longitude: -79.953155}}
        style={{flex: .9}}
        direction={0}
        rotateEnabled={true}
        scrollEnabled={true}
        zoomEnabled={true}
        zoomLevel={17}
        compassIsHidden={true}
        showsUserLocation={true}
        annotations={this.state.temp}
        styleURL={''}
        accessToken={''}
        userTrackingMode={this.userTrackingMode.follow}
        onRightAnnotationTapped={this.onTapMapMarker}
        onOpenAnnotation={this.onOpenAnnotation}
        logoIsHidden={true}
      />
```

the setup above doesn't red screen but the initialCenterCoordinate just doesn't work.

**Comment by cfdhbd** [comment]
can't get initialCenter to work either.

```
state = {userLocation: {lat:4, lng: -95.6088634}, loading: true};


  componentDidMount(props) {
    navigator.geolocation.getCurrentPosition(
      position => {
        const {latitude, longitude} = position.coords;

        this.setState({
          userLocation: {lat: latitude, lng: longitude},
          loading:false
        });
      },
      () => {
        this.setState({loading:false});
      }
    );
  }
```

and 

`<ReactMapGL initialCenterCoordinate={userLocation} />`

tried initialCenter and initialCenterCoordinate. Can't even change the initial center (regardless of userLocation). Also I know userLocation works because I used that same code for google maps user location. Old thread but any help would be appreciated.

**Comment by surenderkhowal** [comment]
Follow this solution:-
https://stackoverflow.com/a/78308868/5479089
