### ISSUE TITLE
Polyline styles

### ISSUE THREAD

**Issue by likethemammal** [nitaliano/react-native-mapbox-gl#492]
I just dove into Map styling with Mapbox Studio. My goal was to create a dark-like map with colorful line-segments for each annotation I have. I'm getting position data on the fly and feeding it to the MapView. This  is where I started to become confused.

Looking around Mapbox Studio and the documention I was expecting a 'custom-line' layer or a layer that would explain where the styling for the polylines that are generated using this lib come from. I messed around with Datasets and the like, trying to figure out where the styles for the Polylines of this lib are. Took me a while to realize that the styling options I was looking for were the `strokeWidth` and `strokeColor` for the annotations provided to MapView. This ended up solving my problem in a basic form. I was able to make colorful polylines and even have multiple on a map at once, each with a different color. Thanks for that!

At any rate, after playing with Mapbox Studio I realized how much control is missing for styling Polylines with this library. Is there a plan to add more freedom with styling Polylines? Ideally, thered just be a layer in Mapbox Studio (like 'generated-lines' or something) that would handle the styling for Polylines generated from code. I get why this functionality is separate at the moment but I was very confused by the 2 different places to style the Map.

**Comment by MrPixelr** [comment]
Is this an issue with react-native-mapbox-gl, or Mapbox Studio?

**Comment by likethemammal** [comment]
"issue" is subjective. I see it as `react-native-mapbox-gl` missing features, but who knows. It may be a better feature for Mapbox Studio to have since it has more flexibility and wouldn't require writing a bunch of similar functionality into the React Native lib. Probably a question for the Mapbox Studio lead devs.

**Comment by nitaliano** [comment]
I would checkout the `v6` alpha now runtime and data driven styling is implemented, so you have complete freedom to use all the layer style props now.

**Comment by likethemammal** [comment]
Sweet, thanks for the heads up
