### ISSUE TITLE
Custom annotation image not showing in the example.

### ISSUE THREAD

**Issue by mjsolidarios** [nitaliano/react-native-mapbox-gl#493]
Tested the example on an Android Emulator and the custom annotation images are still not showing. No changes with the [example](https://github.com/mapbox/react-native-mapbox-gl/blob/master/example.js) code.
![screenshot](https://cloud.githubusercontent.com/assets/7346165/22191405/6870a886-e165-11e6-88c8-85a62ba7e9ee.png)

**Comment by Kottidev** [comment]
fixed on #388  

custom marker work with local image
