### ISSUE TITLE
React-Native-Mapbox-GL fails to link

### ISSUE THREAD

**Issue by aikitpete** [nitaliano/react-native-mapbox-gl#495]
When reproducing step by step this this [original example](https://github.com/mapbox/react-native-mapbox-gl) of RCTMapboxGL (5.1.0) I run into an error with the linker. This happened to me several times (each time with clean project) and I assume this is a bug.

![image](https://cloud.githubusercontent.com/assets/11034626/22461935/9e647d18-e7ab-11e6-8cc8-e5340af5c127.png)

I tried both the:

- Manual installation process for iOS
- Installation process with CocoaPods

My solution was fixing all React import statements across the MapboxGL library.

Turning them into global imports in the form #import <React/MissingClass.h> solved the problem:

e.g. #import RCTView.h to #import <React/RCTView.h>

(9 files in total):

RCTMapboxAnnotation.m:

#import "RCTMapboxAnnotation.h"
#import <React/RCTEventDispatcher.h>
#import <React/UIView+React.h>
#import <React/RCTBridge.h>
#import <React/RCTUtils.h>
RCTMapboxAnnotation.h:

#import "RCTMapboxAnnotation.h"
#import <MapBox/MapBox.h>
#import <UIKit/UIKit.h>
#import <React/RCTConvert+MapKit.h>
#import <React/RCTComponent.h>
#import "RCTMapboxGL.h"
RCTMapboxAnnotationManager.m:

#import "RCTMapboxAnnotationManager.h"
#import <React/RCTUIManager.h>
#import <React/RCTConvert+CoreLocation.h>
#import <React/UIView+React.h>
#import "RCTMapboxAnnotation.h"
RCTMapboxAnnotationManager.h:

#import <React/RCTViewManager.h>
RCTMapboxGL.h:

#import <Mapbox/Mapbox.h>
#import <React/RCTView.h>
#import <React/RCTEventDispatcher.h>
#import <React/RCTBridgeModule.h>
RCTMapboxGL.m:

#import "RCTMapboxGL.h"
#import <React/RCTBridgeModule.h>
#import <React/RCTEventDispatcher.h>
#import <React/UIView+React.h>
#import <React/RCTLog.h>
#import "RCTMapboxGLConversions.h"
#import "RCTMapboxAnnotation.h"
RCTMapboxGLManager.h:

#import <React/RCTViewManager.h>
RCTMapboxGLManager.m:

#import "RCTMapboxGLManager.h"
#import "RCTMapboxGL.h"
#import <Mapbox/Mapbox.h>
#import <React/RCTConvert+CoreLocation.h>
#import <React/RCTConvert+MapKit.h>
#import <React/RCTBridge.h>
#import <React/RCTEventDispatcher.h>
#import <React/UIView+React.h>
#import <React/RCTUIManager.h>
#import "RCTMapboxGLConversions.h"
#import "MGLPolygon+RCTAdditions.h"
#import "MGLPolyline+RCTAdditions.h"
RCTMapboxGLConversions.m:

#import <Foundation/Foundation.h>
#import <React/RCTConvert+CoreLocation.h>
#import <React/RCTConvert+MapKit.h>
#import "RCTMapboxGL.h"

**Comment by kevando** [comment]
Thanks! There error that brought me here is: 

```Duplicate interface definition for class 'RCTView'```

Thanks for taking the time to upload your fixes! 

@petegerhat I am going to edit your comment so it's a bit more legible because it helped me so much. Cheers.


edit: I guess you cant edit people's comments

**Comment by Gnative** [comment]
Thanks @petegerhat

**Comment by guestn** [comment]
Thanks for the above changes. I think I fixed that... but now when I clean and build, I'm now getting a Apple Macho-O Linker Error - the error messages aren't helping me much... Any ideas?

Undefined symbols for architecture x86_64:
  "std::__1::__call_once(unsigned long volatile&, void*, void (*)(void*))", referenced from:
      facebook::react::systemJSCWrapper() in libReact.a(JSCWrapper.o)
  "std::__1::__next_prime(unsigned long)", referenced from:
      std::__1::__hash_table<std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::__unordered_map_hasher<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::hash<unsigned long>, true>, std::__1::__unordered_map_equal<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::equal_to<unsigned long>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned long, unsigned long> > >::rehash(unsigned long) in libReact.a(RCTJSCExecutor.o)
  "std::__1::mutex::lock()", referenced from:
      -[RCTModuleData setUpInstanceAndBridge] in libReact.a(RCTModuleData.o)
  "std::__1::mutex::unlock()", referenced from:
      -[RCTModuleData setUpInstanceAndBridge] in libReact.a(RCTModuleData.o)
  "std::__1::mutex::~mutex()", referenced from:
      -[RCTModuleData .cxx_destruct] in libReact.a(RCTModuleData.o)
  "std::terminate()", referenced from:
      ___clang_call_terminate in libReact.a(RCTJSCExecutor.o)
  "operator delete[](void*)", referenced from:
      -[RCTJSCExecutor dealloc] in libReact.a(RCTJSCExecutor.o)
      executeRandomAccessModule(RCTJSCExecutor*, unsigned int, unsigned long, unsigned long) in libReact.a(RCTJSCExecutor.o)
      readRAMBundle(std::__1::unique_ptr<__sFILE, int (*)(__sFILE*)>, RandomAccessBundleData&) in libReact.a(RCTJSCExecutor.o)
      RandomAccessBundleData::~RandomAccessBundleData() in libReact.a(RCTJSCExecutor.o)
  "operator delete(void*)", referenced from:
      std::__1::__hash_table<std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::__unordered_map_hasher<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::hash<unsigned long>, true>, std::__1::__unordered_map_equal<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::equal_to<unsigned long>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned long, unsigned long> > >::~__hash_table() in libReact.a(RCTJSCExecutor.o)
      std::__1::__hash_table<std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::__unordered_map_hasher<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::hash<unsigned long>, true>, std::__1::__unordered_map_equal<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::equal_to<unsigned long>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned long, unsigned long> > >::__deallocate(std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, unsigned long>, void*>*) in libReact.a(RCTJSCExecutor.o)
      ____ZL37installBasicSynchronousHooksOnContextP9JSContext_block_invoke_5 in libReact.a(RCTJSCExecutor.o)
      std::__1::unique_ptr<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, unsigned long>, void*>, std::__1::__hash_node_destructor<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, unsigned long>, void*> > > > std::__1::__hash_table<std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::__unordered_map_hasher<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::hash<unsigned long>, true>, std::__1::__unordered_map_equal<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::equal_to<unsigned long>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned long, unsigned long> > >::__construct_node_hash<std::__1::pair<unsigned long const, unsigned long> const&>(unsigned long, std::__1::pair<unsigned long const, unsigned long> const&&&) in libReact.a(RCTJSCExecutor.o)
      std::__1::__hash_table<std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::__unordered_map_hasher<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::hash<unsigned long>, true>, std::__1::__unordered_map_equal<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::equal_to<unsigned long>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned long, unsigned long> > >::__rehash(unsigned long) in libReact.a(RCTJSCExecutor.o)
      std::__1::__hash_table<std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::__unordered_map_hasher<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::hash<unsigned long>, true>, std::__1::__unordered_map_equal<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::equal_to<unsigned long>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned long, unsigned long> > >::erase(std::__1::__hash_const_iterator<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, unsigned long>, void*>*>) in libReact.a(RCTJSCExecutor.o)
  "operator new[](unsigned long)", referenced from:
      executeRandomAccessModule(RCTJSCExecutor*, unsigned int, unsigned long, unsigned long) in libReact.a(RCTJSCExecutor.o)
      readRAMBundle(std::__1::unique_ptr<__sFILE, int (*)(__sFILE*)>, RandomAccessBundleData&) in libReact.a(RCTJSCExecutor.o)
  "operator new(unsigned long)", referenced from:
      std::__1::unique_ptr<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, unsigned long>, void*>, std::__1::__hash_node_destructor<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, unsigned long>, void*> > > > std::__1::__hash_table<std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::__unordered_map_hasher<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::hash<unsigned long>, true>, std::__1::__unordered_map_equal<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::equal_to<unsigned long>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned long, unsigned long> > >::__construct_node_hash<std::__1::pair<unsigned long const, unsigned long> const&>(unsigned long, std::__1::pair<unsigned long const, unsigned long> const&&&) in libReact.a(RCTJSCExecutor.o)
      std::__1::__hash_table<std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::__unordered_map_hasher<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::hash<unsigned long>, true>, std::__1::__unordered_map_equal<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::equal_to<unsigned long>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned long, unsigned long> > >::__rehash(unsigned long) in libReact.a(RCTJSCExecutor.o)
  "___cxa_begin_catch", referenced from:
      ___clang_call_terminate in libReact.a(RCTJSCExecutor.o)
  "___cxa_demangle", referenced from:
      ____RCTLogNativeInternal_block_invoke in libReact.a(RCTLog.o)
  "___gxx_personality_v0", referenced from:
      _RCTDefaultLogFunction_block_invoke in libReact.a(RCTLog.o)
      _RCTFormatLog in libReact.a(RCTLog.o)
      _RCTAddLogFunction in libReact.a(RCTLog.o)
      ___RCTAddLogFunction_block_invoke in libReact.a(RCTLog.o)
      _RCTPerformBlockWithLogFunction in libReact.a(RCTLog.o)
      _RCTPerformBlockWithLogPrefix in libReact.a(RCTLog.o)
      RCTGetLocalLogFunction() in libReact.a(RCTLog.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by kevando** [comment]
@guestn That is caused by something unrelated to mapbox. I've run into that several times and I usually solve it by restating xcode or adjusting some config that I can't think of at the moment.

**Comment by guestn** [comment]
you are right! thanks. It is the Build Settings Other Linker Flags which needs to be set '-lc++' to enable these functions...

**Comment by cokealmonacid** [comment]
i tried this but get the following error: "<React/RCTConvert+CoreLocation.h> file not found, after trying to install through cocoapods and manually, clean and making the build again, any suggestions?

**Comment by cokealmonacid** [comment]
Can comment on your post on stackoverflow (stupid rules) but yeah, this works perfectly for me, maybe this one need to be a PR? anyway, THANK YOU!

**Comment by RobertSasak** [comment]
@guestn Can you please specify where exactly do you set Other Linker Flags?
Do you keep `$(inherited)` and  `-ObjC`?

I have `$(inherited) -ObjC -lc++` by default and I still get error "Duplicate interface definition".

**Comment by evansiroky** [comment]
Looks like https://github.com/mapbox/react-native-mapbox-gl/pull/487 fixes this.

**Comment by daominhsangvn** [comment]
I tried this but still not working. Here my steps:
```
$ npm install -g create-react-native-app
$ create-react-native-app my-app
$ cd my-app
$ npm run eject
```
Then select options with ExpoKit
Next add `pod 'RCTMapboxGL', :path => '../node_modules/react-native-mapbox-gl/ios'`
```
$ cd ios
$ pod install
```
Open workspace, click Play and got this:
```
"_OBJC_CLASS_$_RCTMapboxAnnotation", referenced from:
objc-class-ref in libRCTMapboxGL.a(RCTMapboxGL.o)
ld: symbol(s) not found for architecture x86_64
```
_(if you get some error with `RCT/...` not found, remove `node_modules` and `$ npm install` and `$ pod install` again )_
Then i tried to edit all files in `Pod/Development Pods/RCTMapboxGL/RCTMapboxGL` as above reply and i still get this error. Anyone can help me with this? Thanks!!

**Comment by Gp2mv3** [comment]
I have the exact same error as @daominhsangvn. Started after a version update of my app...
Do you have a solution ?

**Comment by helderdb** [comment]
Same issue... Any updates?

**Comment by daominhsangvn** [comment]
@Gp2mv3 @helderdb 
Try manual link and doing following:
1. Select the project with `RCT/...` not found
2. `Build Settings > Header Search Path` then clear everything (Ignore the one that point to another xCode project which is not React)
3. Add this magic code to `Header Search Path`: `"$(SRCROOT)/../../../ios/Pods/Headers/Public"`. Make sure you point to the correct path, `SRCROOT` is the project place, make sure you point it correct the `ios/Pods` folder at the root
4. Clean and build.

:)

**Comment by helderdb** [comment]
@daominhsangvn What if you're not using pods?

**Comment by hssrrw** [comment]
After updating the files from #487 i'm getting this error:
```
`MapView` has no propType for native prop `RCTMapboxGL.onCloseAnnotation` of native type `BOOL`
If you haven't changed this prop yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.
```
Trying to understand what I need to fix as well 🤔

**UPD:**
I can't figure that out 😅
Just replaced all files with ones from `master` and everything works now.

**Comment by gino8080** [comment]
so please which are ALL the CORRECT STEPS to use it in a new fresh create-react-native app?

thank you very much
