### ISSUE TITLE
App crashes when cancelling a Save Offline Pack

### ISSUE THREAD

**Issue by amaury1093** [nitaliano/react-native-mapbox-gl#496]
I found a bug in the example.js file, tried to reproduce in my own project and have the same crash. I only tried in iOS, so I don't know if this bug exists in Android.

Steps to reproduce:
- Run the example.js with `react-native run-ios`
- Click on "Create offline pack"
- *Before the pack finishes saving*, click on "Remove pack with name 'test'" to cancel the download. Now for me, this step works without problem.
- Click again on "Create offline pack"
- *Before the pack finishes saving*, click on "Remove pack with name 'test'". **Here's the crash**. The app closes and the iOS home screen is shown.

I tried 3 times on my machine, same crash. Note: if I wait for the pack to finish downloading, then there's no error when deleting the pack.

My environment:
- OSX Sierra
- Xcode Version 8.2.1 (8C1002)
- Simulator iphone 6, iOS 10.2

If someone can try to reproduce it to confirm it it'd be great.

**Comment by f1qwase** [comment]
same problem

**Comment by nitaliano** [comment]
Closing in favor of https://github.com/mapbox/react-native-mapbox-gl/issues/632.
