### ISSUE TITLE
onRegionDidChange constantly firing up while panning/zooming map

### ISSUE THREAD

**Issue by nirabpudasaini** [nitaliano/react-native-mapbox-gl#497]
I am running the MapView component to render map in Android. I am running my code on Xaomi Mi3 running MM 6.0.1. 

Here is the code i am writing 
` onRegionDidChange: function(region){
  console.log(region);}`

Expected behavior: 
The console log will be triggered once panning or zooming gesture is complete.

Error:
The console log is triggered throughout the process of panning and pinch to zoom. I get 10-15 console log in one map pan. 

The following is the log that i got from a single pan gesture.

![logfromsinglegesture](https://cloud.githubusercontent.com/assets/3871904/22625625/23770d60-ebc4-11e6-96ec-f61d1a6780c6.png)

**Comment by corymsmith** [comment]
I have the exact same issue on Android, I was pretty sure this wasn't happening before. This works as expected on iOS.

**Comment by corymsmith** [comment]
I see the code in here to throttle those events: https://github.com/mapbox/react-native-mapbox-gl/blob/933e70007b61066657336ff03eb845a405081f28/android/src/main/java/com/mapbox/reactnativemapboxgl/ReactNativeMapboxGLView.java#L521

Any idea what changed that may have caused this regression? Wondering if its the latest MapBox Android SDK thats causing this? Currently I'll have to implement throttling in my app which isn't ideal.
