### ISSUE TITLE
"Open your Xcode project and ensure that the "Build Settings" parameter "Other linker flags..."

### ISSUE THREAD

**Issue by mmckinley8** [nitaliano/react-native-mapbox-gl#500]
"Open your Xcode project and ensure that the "Build Settings" parameter "Other linker flags" (OTHER_LDFLAGS) contains the CocoaPods generated linker options!
* if you have used react-native init to setup your project you can just remove this parameter. Just select the line and press the Delete key.
* Alternative, if you setup your Xcode project yourself, ensure that the parent configuration was included with a $(inherited) variable."

I was hoping someone could clarify this step of the installation instructions. I am receiving errors when building, and I'm thinking it is because of this step. I created my project with react-native init. I see three values when I tap into Other Linker Flags: 

$(inherited)
-ObjC
-lc++

Does anyone know if I need to delete one of these? I have other cocoapods using the $(inherited) flag.

**Comment by ansarikhurshid786** [comment]
Did you got solution?
