### ISSUE TITLE
5.1.0 is working on Android, but not iOS. 5.2.0 (latest commit) vice versa.

### ISSUE THREAD

**Issue by mmckinley8** [nitaliano/react-native-mapbox-gl#508]
Has anyone else ran into this issue? Crashes on android on latest commit, but works on iOS. Android works on 5.1.0 (latest release) but iOS doesn't...fails with several errors.

**Comment by gillessed** [comment]
It looks like Android on latest head is broken (see #507). However, iOS does work on the 5.1.0 release. What errors are you seeing for iOS?

**Comment by mmckinley8** [comment]
@gillessed it's the import headers...the fix is in this commit, but this hasn't been released yet. https://github.com/mapbox/react-native-mapbox-gl/commit/3df91c52448a77fa9972cf8147eaf6a9f513a2e8
