### ISSUE TITLE
react-native 0.5.0

### ISSUE THREAD

**Issue by mxstbr** [nitaliano/react-native-mapbox-gl#51]
Hey,

I'm currently working on a project using react-native 0.5.0, which obviously isn't ^0.4.3. Any ideas if/when this module will be usable with 0.5.0?

Cheers!

**Comment by bsudekum** [comment]
I'll can hit this today.

**Comment by mxstbr** [comment]
That's awesome, thanks so much!

**Comment by christocracy** [comment]
+1

**Comment by cyprusglobe** [comment]
+1

**Comment by iSimar** [comment]
Hey bobby, great module. When do you think it will be compatible for react-native ^0.6.0 (latest one).

**Comment by bsudekum** [comment]
It's taking a little longer than expected. I hope to have it done by COB Monday.

**Comment by iSimar** [comment]
Cool, looking forward to it. Thanks.

**Comment by christocracy** [comment]
While we're all waiting for our host to fix the map, If anyone's interested
in "background location tracking", I'm working on porting my
popular Cordova plugin:
http://christocracy.github.io/cordova-background-geolocation/

To React Native
https://github.com/christocracy/react-native-background-geolocation

It works, but I haven't pushed any code yet.  Star the repo if you're
intererested.

On Saturday, June 27, 2015, Simar notifications@github.com wrote:

> Cool, looking forward to it. Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bsudekum/react-native-mapbox-gl/issues/51#issuecomment-116189912
> .

## 

Snet from Gmail Mobile

**Comment by bsudekum** [comment]
All set, just published `0.3.0` which will be compatible with `0.4.3` through `0.7.0`.

**Note: there is a new step added to the install process requiring you to add a `Settings.bundle` file**. Click Build Phases then Copy Bundle Resources. Click the + button. When the modal appears, click Add other. Add `node_modules/react-native-mapbox-gl/RCTMapboxGL/Settings.bundle` See [install.md](https://github.com/mapbox/react-native-mapbox-gl/blob/master/install.md) for more information.

**Comment by mxstbr** [comment]
:+1: great work!

**Comment by iSimar** [comment]
Thanks bobby :+1:  cheers
