### ISSUE TITLE
iOS Example Build Fail - Print: Entry, ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by NatEvatt** [nitaliano/react-native-mapbox-gl#510]
iOS Example Build Fail - Print: Entry, ":CFBundleIdentifier", Does Not Exist

Using Xcode Version 8.2.1 
react-native-cli: 2.0.1
react-native: 0.41.2
Latest react-native-mapbox-gl
npm 3.8.6
node 5.11.0

I am getting the same error after running the install from the [manual instructions](https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/install.md) and the [cocoapods instructions](https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/install-cocoapods.md) 

My project install was through react-native init

and using the [example code](https://github.com/mapbox/react-native-mapbox-gl/blob/master/example.js)

I am getting the following error:

> The following build commands failed:
> 	CompileC /Users/MyComp/servers/workspace/mapboxGl2/ios/build/Build/Intermediates/RCTMapboxGL.build/Debug-iphonesimulator/RCTMapboxGL.build/Objects-normal/x86_64/RCTMapboxGL.o RCTMapboxGL/RCTMapboxGL.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> (1 failure)
> 
> Installing build/Build/Products/Debug-iphonesimulator/mapboxGl2.app
> An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
> Failed to install the requested application
> An application bundle was not found at the provided path.
> Provide a valid path to the desired application bundle.
> Print: Entry, ":CFBundleIdentifier", Does Not Exist
> 
> Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/mapboxGl2.app/Info.plist
> Print: Entry, ":CFBundleIdentifier", Does Not Exist

I see that this error has come up a few times through react-native but the solutions i have found haven't worked for me.  Has any one seen this specifically with react-native-mapbox-gl?

Thanks,

**Comment by NatEvatt** [comment]
I solved the problem.  I had misread the error because the CompileC error was just the bottom or a long list of errors which pointed to "error: property has a previous declaration"
In the end the problem was caused by the update of react-native 0.40 and above which has been pointed out by #486 
In the end I was able to get the example working by downgrading react-native to 0.39.0.  However, I am looking forward to react-native-mapbox-gl 5.2.0 so that i can use the current react-native

**Comment by yoavrofe** [comment]
Please see #495 for solution.
