### ISSUE TITLE
Android crash after loading map

### ISSUE THREAD

**Issue by cokealmonacid** [nitaliano/react-native-mapbox-gl#511]
Been using Mapbox for a while and never get a problem like this, everything works perfectly but now, when launch the app on the android emulator (genymotion) it crash. 

![captura de pantalla 2017-03-01 a las 00 06 48](https://cloud.githubusercontent.com/assets/16389394/23444300/f1915d30-fe12-11e6-8cf7-7df23414a550.png)

This is the code that im using: 

componentWillMount() {
    API.getEvaluationPoints().then(json => {

      for (var i = 0; i < json.length; i++) {
        var id = String(json[i].evp_id);
        this.setState({
          annotations: [ ...this.state.annotations, {
            coordinates: [json[i].evp_lat, json[i].evp_lon],
            type: 'point',
            title: json[i].evp_nam,
            id: id
          }]
        });
      }
    });
  }

  _changeZoom(zoom){
    var actualZoom = this.state.zoom;
    this.setState({
      zoom: actualZoom + zoom
    });
    this._map && this._map.setZoomLevel(actualZoom);
  }

  _centerMap(){
    this._map && this._map.setCenterCoordinate(this.state.center.latitude, this.state.center.longitude);
  }

  render() {
    return(
      <View style={{flex: 1}}>
        <Header title='Ciudad Fácil' action={this.props.openDrawer} size='18'/>
        <View style={styles.container}>
        <MapView
          ref={map => { this._map = map; }}
          style={styles.map}
          initialCenterCoordinate={this.state.center}
          initialZoomLevel={this.state.zoom}
          initialDirection={0}
          rotateEnabled={true}
          scrollEnabled={true}
          zoomEnabled={true}
          showsUserLocation={false}
          styleURL={Mapbox.mapStyles.streets}
          annotations={this.state.annotations}
        />
        <View style={styles.zoomButtons}>
          <TouchableHighlight style={styles.button} underlayColor='rgba(151,151,151,0.9)' onPress={() => this._changeZoom(1)}>
            <Icon name="plus" size={20} />
          </TouchableHighlight>
          <TouchableHighlight style={styles.button} underlayColor='rgba(151,151,151,0.9)' onPress={() => this._changeZoom(-1)}>
            <Icon name="minus" size={20} />
          </TouchableHighlight>
        </View>
        <View style={styles.geoLocation}>
          <TouchableHighlight style={styles.button} underlayColor='rgba(151,151,151,0.9)' onPress={() => this._centerMap()}>
            <Icon name="map-marker" size={20} />
          </TouchableHighlight>
        </View>
      </View>
      </View>
    );
  }
}

Im using a Custom API, has been working perfectly with this one and then from nothing just crash, but still works on iOS:

![captura de pantalla 2017-03-01 a las 00 09 41](https://cloud.githubusercontent.com/assets/16389394/23444349/4e6afcfa-fe13-11e6-9ebc-9f1740fe44a7.png)

**Comment by Kottidev** [comment]
Same Problem
