### ISSUE TITLE
queryRenderedFeatures on Android

### ISSUE THREAD

**Issue by kevando** [nitaliano/react-native-mapbox-gl#513]
Hi, can I access the `queryRenderedFeatures()` function on android? Even if it's in beta, I would still like to try this out.

**Comment by tsemerad** [comment]
Hi @kevando. I've been using `queryRenderedFeatures` on Android in my fork for awhile now. I submitted PR #519 about a month ago which adds it. I'm really hoping it will be added to the next release, I just have no idea when that will be.

**Comment by kevando** [comment]
Thanks for the update and the PR @tsemerad ! 

I will forward this along to our new developer. Much appreciated homie.

**Comment by nitaliano** [comment]
This is implemented in the `v6` alpha closing this out
