### ISSUE TITLE
iOS MapBox.h file not found on case-sensitive system

### ISSUE THREAD

**Issue by ghost** [nitaliano/react-native-mapbox-gl#514]
file : react-native-mapbox-gl/ios/RCTMapboxGL/RCTMapboxAnnotation.h
line 3 : #import <MapBox/MapBox.h>

On case-sensitive file system causes a compilation error : MapBox.h file not found on case-sensitive system

The mapbox framework case is Mapbox.

Replacing the import line by the following one, the application can compile without error 
 #import <Mapbox/Mapbox.h>

**Comment by friedbunny** [comment]
The master branch of this project [has this correctly as Mapbox.h](https://github.com/mapbox/react-native-mapbox-gl/blob/4453983022f1e983579697cd54e5c74bd2115af1/ios/RCTMapboxGL/RCTMapboxAnnotation.h#L3). If this is incorrect in some other branch, please let the maintainer of that branch know.
