### ISSUE TITLE
E/OfflineManager: Failed to read the storage key: Attempt to invoke virtual method 'boolean android.os.Bundle.getBoolean(java.lang.String, boolean)' on a null object reference

### ISSUE THREAD

**Issue by thepinyo** [nitaliano/react-native-mapbox-gl#515]
app crash when run on android , how to fix this problem

**Comment by henrikra** [comment]
@thepinyo I have the same problem. How did you fix this?

**Comment by henrikra** [comment]
Ah lol :') The problem was that the phone did not have internet connection :D Now I can see the map!
