### ISSUE TITLE
Cannot find Mapbox.framework in the package

### ISSUE THREAD

**Issue by aganglada** [nitaliano/react-native-mapbox-gl#518]
I have been following the installation steps for ios and I find out something interesting.

I cannot see `node_modules/react-native-mapbox-gl/ios/Mapbox.framework` in the package, also if you check here `https://github.com/mapbox/react-native-mapbox-gl/tree/master/ios`, there is no such a file.

Could you explain why? And what do I have to add to Embedded Binaries?

**Comment by RichardLindhout** [comment]
I did have that issue myself. Try to install via npm a few times and it will show up (at least for me).
Very strange.

**Comment by aganglada** [comment]
OMG! How is that possible, I've been doing this for 3 days and I reinstalled just now and it appears.

Thanks! It works so 👍

**Comment by sepion02** [comment]
Same issue... It eventually appears when doing a **non sudo** npm install.
!?

**Comment by Gnative** [comment]
Thank you @sepion02, this save me after ages trying to figure why the framework was not included

**Comment by znchen1989** [comment]
I still don't have the Mapbox.framework file after several times' reinstall

**Comment by sepion02** [comment]
Try to install it on another machine or virtual machine. Windows... Linux.

**Comment by Gnative** [comment]
I found it appeared after a non "sudo" npm install as @sepion02 has mentioned. Took me a while to figure this out.
