### ISSUE TITLE
Offline Support

### ISSUE THREAD

**Issue by mxstbr** [nitaliano/react-native-mapbox-gl#52]
It would be a great addition to have offline support, i.e. caching certain regions on first app start (or bundle them?) and then using them if the user is not connected to a network. 

I'm not sure if this is possible, or too much effort, but I'd love that.

**Comment by 1ec5** [comment]
Depends on mapbox/mapbox-gl-native#584.

**Comment by jayfunk** [comment]
It appears issue #584 is coming along. How much effort would be involved to integrate what they release? It appears they are targeting an end of March release.

**Comment by bsudekum** [comment]
@jayfunk It shouldn't be too bad. Although this has been implemented in mapbox-gl-native core, the Android and iOS bindings have not yet been created. Once they are released, I'll update this module.

**Comment by jayfunk** [comment]
With [official offline support](https://www.mapbox.com/blog/offline-mobile-maps/) what would the timeframe for this repo to support the offline mechanisms?

**Comment by bsudekum** [comment]
@jayfunk working on this now, I'm hoping for a release with it included by the end of the month. You can track changes here: https://github.com/mapbox/react-native-mapbox-gl/compare/offline

**Comment by robertg** [comment]
Really excited for this, we have thousands of users waiting for offline maps on their phone!

https://getwi.fi

**Comment by jayfunk** [comment]
I saw [this](https://github.com/mapbox/react-native-mapbox-gl/pull/312) for IOS. Is Android going to have offline support in your projected timeline?

**Comment by bsudekum** [comment]
@jayfunk yes, android is coming soon too.

**Comment by jayfunk** [comment]
Just wanted to check in again about offline support for both platforms. Haven't seen any  new updates for a bit. I have a deliverable coming soon that I REALLY wanted offline support for. Super excited to have that working since it will make a massive difference for usability.

**Comment by rbeers** [comment]
We are also very excited about offline support for Android.  It will be a great addition for our app.

**Comment by ghost** [comment]
Same thing, without offline support we have to wait before being able to use this library. Any ETA?

**Comment by bsudekum** [comment]
Offline is in v4.1.0.
