### ISSUE TITLE
consider changing the annotation API to have point as [lon, lat]

### ISSUE THREAD

**Issue by carocad** [nitaliano/react-native-mapbox-gl#520]
Hey guys,

first of all many thanks for this great library. It has worked perfectly for me :)

I am doing some prototyping with react-native-mapbox-gl and I am also using the geocoding API to fetch some coordinates and display them on the map.

The "problem" that I found was that the annotations API for react-native-mapbox-gl takes the points as [lat lon] whereas the geocode API returns the points as [lon lat]. This is definitely a small thing but it can get very confusing because there is no error/warning nor similar to help pinpoint where the problem is.

I guess that the geocode API is more stable since there is a proper specification for it, which is why I am raising the question of whether or not it makes sense to change the annotations API to supoort the common [lon lat] standard as defined in GeoJson as well.

Hope it helps

**Comment by nitaliano** [comment]
In the `v6` rewrite all coordinates are in [lng, lat] format
