### ISSUE TITLE
Offline map on device loads extremely slow

### ISSUE THREAD

**Issue by wd021** [nitaliano/react-native-mapbox-gl#525]
When loading map initially on an offline iOS device, it takes a much longer time than on iOS simulator (minutes). The wait time between `onStartLoadingMap` and `onFinishLoadingMap` is minutes in which only a black screen can be seen on device.

During troubleshooting, i added `addOfflinePackProgressListener` and disocvered that its emitting a lot of notifications on the offline device, seemingly emulating a download process, even though the device is offline and not connected to the internet. When `countOfResourcesCompleted` = `countOfResourcesExpected` after a couple minutes, the map finally loads and `onFinishLoadingMap` is triggered. This doesn't happen on the simulator, it loads instantly. 

Obviously, nothing is being downloaded since the device isn't connected. But this is causing the map to take a long long time to load. Anyone know how to make this go away?

**Comment by wd021** [comment]
It appears that the offline map loads when `loading style failed: The Internet connection appears to be offline.` is triggered. This happens immediately on the simulator when it is offline, but takes forever to trigger on an offline device. It waits until `addOfflinePackProgressListener` has completed.

**Comment by butchmarshall** [comment]
Hi @wd021 - I've also experienced the `addOfflinePackProgressListener` emitting downloading even after the map has been downloaded.

This seems to happen after I kill the app completely, and re-launch it.

I had thought it lost the map entirely and was re-downloading it again - you're sure this is not the case?  I wonder what the point of these events are, then...

**Comment by wd021** [comment]
It's definitely not re-downloading since i tried it without a network connection. It emits events as if its downloading though and once it completes, the map displays.

**Comment by butchmarshall** [comment]
That's a relief!  I was concerned my users were going to have to re-download every single time.

Still kind of annoying.  I still haven't figured out how to "load" a map once it's available for offline access.  Any pointers there?

**Comment by wd021** [comment]
It does load eventually, problem is initial map load waits for the events from `addOfflinePackProgressListener` to complete. What you can do is disable these notifications from the `init` and implement your own method of tracking complete downloads. 

If you remove `[pack resume];` in `RCTMapboxGLManager.m`, it'll remove these events, but then you'll have to make sure you manually delete and restart downloads that don't complete.

**Comment by butchmarshall** [comment]
Yea, it also seems Mapbox.removeOfflinePack does not work properly while these events are being emitted?

1) Add a new pack with Mapbox.addOfflinePack
2) Remove the pack with Mapbox.removeOfflinePack - it says it succeeds (has deleted key)
3) Kill the app
4) Reload the app
5) Call Mapbox.getOfflinePacks

It's still there.  App size also lines up with it still being there.

**Comment by butchmarshall** [comment]
Attempted to use latest master version from Git repo - it seems to fix this issue!

I believe it is because of the mapbox sdk upgrade?

Unfortunately I cannot use it as a drop-in - It also breaks a bunch of other stuff.

**Comment by atarsha** [comment]
I have been tinkering with this slightly (not too seriously yet) to try to overcome this terrible hanging while loading that is really playing havoc on some of my RN startup logic.

in `RCTMapboxGLManager.m` `offlinePacksDidFinishLoading()` there is the following code:
```
for (MGLOfflinePack * pack in packs) {
    [pack resume];
}
```

Replacing that with:
```
    for (MGLOfflinePack * pack in packs) {
        MGLOfflinePackProgress progress = pack.progress;
        uint64_t completedResources = progress.countOfResourcesCompleted;
        uint64_t expectedResources = progress.countOfResourcesExpected;
        
        if (completedResources < expectedResources) {
            [pack resume];
        }
    }
```

solves the issue with hanging on every single load, but still maintains the pack resuming for packs that have not yet completed.

CAVEAT: The startup still hangs as usual in the event that a pack is not complete.

It seems as though `[pack resume]` must complete prior to relinquishing the thread to your JS code.

I'm not a very strong Objective-C developer, so I'm probably not the guy to take this across the finish line, but I wanted to pass along my findings in case someone else wants to give it a whirl.

EDIT: As a followup, I even tried tossing the pack resume into a dispatch_async, which made no difference. At this point, I'm at a loss, so it would be awesome if a more experienced Objective-C engineer could chime in.

**Comment by atarsha** [comment]
Tagging the other contributors because I'd really like some feedback on this. I'd be happy to submit a PR, but would prefer to first resolve the issue where the main thread is blocked waiting for resume to complete. Do you guys have any ideas? @wd021 @butchmarshall @robertsasak

**Comment by RobertSasak** [comment]
I had the same issue and for now I came up with the similar solution as you did. I am not fluent in Obj-C either. So I used the constant 3 directly.
```
    for (MGLOfflinePack * pack in packs) {
        if (pack.state != 3) {
            [pack resume];
        }
    }
```
I am also interested in how we can unblock the main thread. I will look into it more.

**Comment by atarsha** [comment]
You should be able to use something like `if (pack.state != MGLOfflinePackStateComplete)` instead

**Comment by RobertSasak** [comment]
Thanks. Since `resume` is SDK function I don't see any option how it would be possible to unblock downloading thread. So it will be possible to use map while downloading tiles for offline.
Have you tried to upgrade SDK?

**Comment by butchmarshall** [comment]
FYI I'm now running react-native-mapbox-gl v5.2.0 in my app to get around this issue.

**Comment by RobertSasak** [comment]
I followed your advice and also updated my package.json to use latest master. Then I run npm install and link and copy Mapbox SDK. However I still had the same issue. Downloading at the start would block loading of map tiles. So I guess I am doing something wrong. @butchmarshall, can you please describe how are you running react-native-mapbox-gl 5.2.0?

**Comment by atarsha** [comment]
You have to modify the package.json in node_modules/react-native-mapbox-gl

There is an argument passed to the install script.

**Comment by atarsha** [comment]
Sorry, I misunderstood. The instructions I gave were for how to change the mapbox-gl-native sdk version. I found that mapbox-gl-native 3.5.4 does not block map loading while downloading, but I haven't tested it on iOS yet to see if it solves the issue above.

**Comment by atarsha** [comment]
@butchmarshall @RobertSasak check out the PR I just submitted. The change to package.json resolves the blocked UI issue in my testing. It also adds some additional features to offline maps.
