### ISSUE TITLE
Attempt to invoke virtual method 'void android.view.View.unFocus'

### ISSUE THREAD

**Issue by butchmarshall** [nitaliano/react-native-mapbox-gl#531]
This is using the latest master branch (it works fine on 5.1.0)

![screenshot_20170410-224815](https://cloud.githubusercontent.com/assets/339763/24890811/f5f1801a-1e3f-11e7-8896-1ed649cd1295.png)

**Comment by chriscohoat** [comment]
I'm having the same issue. It seems to happen for me if the `<MapView>` is conditionally created (and then goes away):

```
{ rowIsSelected && (
              <View>
                <View style={styles.rowMap.outerContainer}>
                  <View style={styles.rowMap.innerContainer}>
                    <MapView ...
```

I suspect keeping a reference to MapView somewhere in the instance scope may keep the null object reference from happening, but I'm waiting to attempt that. May try 5.1.0 in the meanwhile.

**Comment by butchmarshall** [comment]
Yes. I should have put that in the original bug.

It triggers when ex-navigator pops a view containing a map.

**Comment by butchmarshall** [comment]
Huh, this does not seem to occur on the latest master.

Did this [commit](https://github.com/mapbox/react-native-mapbox-gl/commit/182c76edbb7b4499f349b1d5c169715dcb577910) fix it?
