### ISSUE TITLE
can it support large many points?

### ISSUE THREAD

**Issue by xiaogu-space** [nitaliano/react-native-mapbox-gl#532]
for example can it support   >100 000 markers ?

**Comment by butchmarshall** [comment]
Not through annotations. See #491.

I found you have to use custom mapbox styleUrls in order to support something like this.

**Comment by xiaogu-space** [comment]
But I don't very know what is the "custom mapbox styleUrls",is there a link?

**Comment by butchmarshall** [comment]
[Mapbox Style URL Documentation](https://www.mapbox.com/help/define-style-url/) is pretty good.

Basically, you create an account in mapbox studio.  From there, you can use that account to generate a map containing all your data. 

From this map you get a "style url" which you can then use to render the custom view in your &lt;MapView styleURL={...} /&gt;

**Comment by xiaogu-space** [comment]
Ok thanks
