### ISSUE TITLE
showsUserLocation - custom image?

### ISSUE THREAD

**Issue by butchmarshall** [nitaliano/react-native-mapbox-gl#534]
Custom images for user locations would be great.

I saw it referenced in #317 but could not find an issue opened specifically for it.

**Comment by nitaliano** [comment]
For version 6 of this repo depending on the functionality that you desire you could.

1. Use a `ShapeSource` with a `SymbolLayer` and update the geojson source everytime the user location changes.
2. Use a `PointAnnotation` if you need custom views with animations, and update the coordinate on the annotation anytime the user location changes.
