### ISSUE TITLE
setVisibleCoordinateBounds on componentDidMount() does not set the map boundaries

### ISSUE THREAD

**Issue by markhaasjes** [nitaliano/react-native-mapbox-gl#535]
I want to set the boundaries of my map based on the annotations I'm showing. 
When I call:
```javascript
this._map.setVisibleCoordinateBounds(latitudeSW, longitudeSW, latitudeNE, longitudeNE, 0, 0, 0, 0, true);
``` 
on `componentDidMount()` the map remains on its initial position (based on the `initialCenterCoordinate` and `initialZoomLevel`). 

When calling `setVisibleCoordinateBounds()` with for example tapping on a button the boundaries are updated and the map updates it position.

Am I doing something wrong, or is this a bug?

**Comment by jackfengji** [comment]
You can temporary use https://github.com/waijule/react-native-mapbox-gl/commit/87aef7f1d3c17514d7a468ae4e15139981255be5 to fix this issue. But I have opened another issue which is the root cause of this one.

**Comment by markhaasjes** [comment]
@jackfengji thanks for referring to that temporary fix. What is the issue number with that cause?

**Comment by biks152207** [comment]
@markhaasjes @jackfengji has anyone solved this issue

**Comment by markhaasjes** [comment]
I did not check if the bug was fixed due to the fact that my project is paused. I'll close this issue and as soon as I see this bug again I'll reopen it.
