### ISSUE TITLE
Unit tests are failing

### ISSUE THREAD

**Issue by markhaasjes** [nitaliano/react-native-mapbox-gl#536]
I'm running unit test and they are failing because of 'mapStyles' that cannot be found. It seems that `MapboxGLManager` is not defined somehow.

```javascript
// node_modules/react-native-mapbox-gl/index.js:19:26
const { mapStyles, userTrackingMode, userLocationVerticalAlignment, unknownResourceCount } = MapboxGLManager;
```

```
 FAIL  src/components/MapBoxContainer/index.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'mapStyles' of undefined

      at Object.<anonymous> (node_modules/react-native-mapbox-gl/index.js:19:26)
      at Object.<anonymous> (src/components/MapBoxContainer/index.js:4:26)
      at Object.<anonymous> (src/components/MapBoxContainer/index.test.js:6:7)
```

Does someone have a working test?

**Comment by joaosilva05** [comment]
+1

**Comment by nitaliano** [comment]
For anyone having this problem you would need to create a mock, this is what I'm doing for my tests in version 6 of the repo https://github.com/mapbox/react-native-mapbox-gl/blob/v6/__tests__/__mocks__/react-native-mapbox-gl.mock.js

**Comment by silvestreh** [comment]
@nitaliano so, for the particular case of `mapStyles`, we'd have to mock something like…

```javascript
import { NativeModules } from 'react-native';

NaviveModules.MapboxGLManager = {
  mapStyles: {}
};
```

Am I right?

**Comment by silvestreh** [comment]
No, I was not right 😂. Your file worked just fine. Thanks @nitaliano
