### ISSUE TITLE
[iOS] Incompatible with React Native 0.44: missing React/RCTConvert+MapKit.h

### ISSUE THREAD

**Issue by iamtommcc** [nitaliano/react-native-mapbox-gl#545]
React Native 0.44 removes the deprecated MapView component, which means `React/RCTConvert+MapKit.h` has been deleted.

Trying to build a project with this lib on RN 0.44 yields several `React/RCTConvert+MapKit.h` errors.

**Comment by jjzazuet** [comment]
I'm getting the same error. Any suggestions? Thanks!

**Comment by ada-lovecraft** [comment]
As indicated in the released notes for React 0.44:  
> Breaking changes
Remove MapViewIOS
48f30ec - @mkonicek
`<MapView />` was deprecated for a while, in this release it is removed from react-native.

`react-native-mapbox-gl` is unavoidably -broken- as of React-Native 0.44

**Comment by digitaldavenyc** [comment]
@8-uh Do you know of a manual work around for this?

**Comment by digitaldavenyc** [comment]
I fixed the library headers myself, works now.

**Comment by ada-lovecraft** [comment]
@digitaldavenyc Would you be willing to share the solution?

I've been attempting to use the MapBoxGL.js in a webview and it's proving to be... unworthy.

**Comment by digitaldavenyc** [comment]
@8-uh The errors show up in XCode during a build. you need to fix all imports from the react library 

ex: change `#import "RCTBridgeModule.h"` to `#import <React/RCTBridgeModule.h>`

This is due to the breaking changes in RN 0.44

**Comment by ada-lovecraft** [comment]
@digitaldavenyc I've done that.. and it always comes down to not having the `RCTConvert+MapKit.h" file that React pulled from the Library with 0.44

**Comment by digitaldavenyc** [comment]
You might want to try fixing the import in the file `RCTConvert+Mapkit.h` for `#import <React/RCTConvert.h>`

**Comment by digitaldavenyc** [comment]
I'm going to submit a PR that fixes all this tomorrow because frankly modifying library code manually without a fork isn't the best idea.

**Comment by MrVisitor** [comment]
@digitaldavenyc, Your PR does not solve the problem. When I make these changes, I have an error "Cannot read property 'mapStyles' of undefined"

**Comment by linamm** [comment]
@digitaldavenyc, thanks for the post, I am running into similar problem, have you submitted a PR for this?

**Comment by henrikra** [comment]
@iamtommcc Can you close this if this is fixed?
