### ISSUE TITLE
React Native 0.44

### ISSUE THREAD

**Issue by igor9silva** [nitaliano/react-native-mapbox-gl#549]
Have it stopped working on React Native 0.44?

**Comment by digitaldavenyc** [comment]
+1 for this ... I have 150 issues in react-native-mapbox-gl due to the breaking changes in React Native 0.40+

**Comment by markhaasjes** [comment]
Maybe change this request into updating the latest version of RN? This is 0.45 right now.

**Comment by henrikra** [comment]
@igor9silva Can this be closed?

**Comment by igor9silva** [comment]
I haven't gave it a try after #552, but I think it's OK.
