### ISSUE TITLE
Make RCTMapboxGL extends MGLMapView directly instead of making it a subview

### ISSUE THREAD

**Issue by jackfengji** [nitaliano/react-native-mapbox-gl#556]
Is there any specific reason that we make `MGLMapView` as a subview of `RCTMapboxGL`? This causes the real `MGLMapView` not being initialized until layoutSubview is called in `RCTMapboxGL`. So actually all map operations are not available in `componentDidMount` lifecycle which causes #535 .

I checked Airbnb's MapView for google/apple map. They are just using `AirMap` for the real mapview and it inherits the `MKMapView`.

**Comment by jackfengji** [comment]
There's also causing touch events being injected by annotations only. In original iOS SDK, you can pan map even if you touches in an annotation, but this is not possible anymore in RN SDK.

**Comment by nitaliano** [comment]
This is going to be fixed for version 6.0 of the repo. It is a complete rewrite of the current codebase it's currently under https://github.com/mapbox/react-native-mapbox-gl/tree/v6 and is just starting to be worked on.

Subclassing MGLMapView is already done along with the delegate methods living in the manager.
https://github.com/mapbox/react-native-mapbox-gl/blob/v6/ios/RCTMGL/RCTMGLMapView.h
https://github.com/mapbox/react-native-mapbox-gl/blob/v6/ios/RCTMGL/RCTMGLMapView.m
https://github.com/mapbox/react-native-mapbox-gl/blob/v6/ios/RCTMGL/RCTMGLMapViewManager.m

**Comment by jackfengji** [comment]
Good to know this. Then this issue can be closed.
