### ISSUE TITLE
Android incorrectly propogating scroll event

### ISSUE THREAD

**Issue by ColinTS** [nitaliano/react-native-mapbox-gl#561]
With scrollEnabled set to false and rotateEnabled set to true, the map correctly does not scroll, but as soon as I begin rotating the screen, scrolling is incorrectly enabled. Is there a fix for this?

Also, is there a fix for replacing the pinch rotate gesture with a left to right swipe gesture?

**Comment by nitaliano** [comment]
Closing this out as we just merged in our `v6` rewrite. If this exists in the new version feel free to reopen.
