### ISSUE TITLE
Use react style props instead of setters

### ISSUE THREAD

**Issue by kormang** [nitaliano/react-native-mapbox-gl#564]
Why couldn't we use props instead of setters for coordinates, pitch, and other properties?
For example instead of:
`this._map.setCenterCoordinate(lat, long)`
we could use:
`<MapView centerCoordinate={{latitude, longitude}} />`

It conforms to react philosophy, and makes it easier to update coordinates in react environment.

Keeping initialCenterCoordinate property, even something as simple as this:
```javascript
componentWillReceiveProps(newProps) {
    if (this.props.centerCoordinate && newProps.centerCoordinate &&
      (this.props.centerCoordinate.latitude !== newProps.centerCoordinate.latitude ||
      this.props.centerCoordinate.longitude !== newProps.centerCoordinate.longitude)) {
      this.setCenterCoordinate(newProps.centerCoordinate.latitude,
        newProps.centerCoordinate.longitude,
        newProps.animatedCoordinateChange)
    }
.
.
.
}
```

...could do the job if placed in `react-native-mapbox-gl/index.js`.

**Comment by nitaliano** [comment]
This is how version 6 of the repo is implemented closing out
