### ISSUE TITLE
Custom annotation throws cast error

### ISSUE THREAD

**Issue by CptFabulouso** [nitaliano/react-native-mapbox-gl#569]
When I try to implement custom annotation following the documentation I am getting en error "com.mapbox.reactnativemapboxgl.ReactNativeMapboxGLManager cannot be cast to com.facebook.react.uimanager.ViewGroupManager".
In console I also get error "Warning: Native component for "RCTMapboxAnnotation" does not exist"

I tried it also with the example project and still got the error, render method looks like this:

```
<View style={styles.container}>
        <MapView
          ref={map => { this._map = map; }}
          style={styles.map}
          initialCenterCoordinate={this.state.center}
          initialZoomLevel={this.state.zoom}
          initialDirection={0}
          rotateEnabled={false}
          scrollEnabled={true}
          zoomEnabled={true}
          showsUserLocation={false}
          styleURL={Mapbox.mapStyles.streets}
          userTrackingMode={this.state.userTrackingMode}
          annotations={this.state.annotations}
          annotationsAreImmutable
          onChangeUserTrackingMode={this.onChangeUserTrackingMode}
          onRegionDidChange={this.onRegionDidChange}
          onRegionWillChange={this.onRegionWillChange}
          onOpenAnnotation={this.onOpenAnnotation}
          onRightAnnotationTapped={this.onRightAnnotationTapped}
          onUpdateUserLocation={this.onUpdateUserLocation}
          onLongPress={this.onLongPress}
          onTap={this.onTap}
        >
          <Annotation
            id="annotation1"
            coordinate={{latitude: 37.5, longitude: -122.2}}
            style={{alignItems: 'center', justifyContent: 'center', position: 'absolute'}}
          >
            <View style={{width: 100, height: 100, borderWidth: 4, borderColor: 'blue', borderRadius: 50, backgroundColor: 'white', flex: 1, justifyContent: 'center', alignItems: 'center'}}>
              <Text>React View</Text>
            </View>
          </Annotation>
        </MapView>
        <ScrollView style={styles.scrollView}>
          {this._renderButtons()}
        </ScrollView>
      </View>
```
Annotation component is imported
`import Mapbox, { MapView, Annotation } from 'react-native-mapbox-gl';`

I am using version:
"react-native": "0.44.0",
"react-native-mapbox-gl": "^5.1.0",

running on Android, not tested on iOS

**Comment by groggy84** [comment]
me too

**Comment by zaguini** [comment]
+1

**Comment by zaguiini** [comment]
Upgrading to 5.2.0 (installing via Github instead of NPM) fix the issue.

**Comment by CptFabulouso** [comment]
Thanks a lot.
For anyone else, Iam not sure how to install via github the proper way, but I uninstalled mapboxgl, added line to package.json "react-native-mapbox-gl" : "git://github.com/mapbox/react-native-mapbox-gl.git", and ran npm install, which then installed the 5.2.0 version

**Comment by zaguiini** [comment]
`npm install git+https://github.com/mapbox/react-native-mapbox-gl.git --save`
