### ISSUE TITLE
Hot reloading on Android causes empty result set from getOfflinePacks()

### ISSUE THREAD

**Issue by atarsha** [nitaliano/react-native-mapbox-gl#570]
in ReactNativeMapboxGLModule.java, `initializeOfflinePacks()` is called in `setAccessToken()` however, setAccessToken returns before initializeOfflinePacks is called if `initialized` is already true.

I'm not sure why, but initialized STAYS true through a hot reload. Maybe a problem with my environment, or maybe something unique to Android? I would appreciate it if somebody who is a little more familiar with Android could chime in and offer some input, as well as somebody else testing this on Android to see if the problem is me, or this repository.

RN 0.44.2
React 16.0.0-alpha.6

Thanks!

**Comment by henrikra** [comment]
Is this solved?

**Comment by atarsha** [comment]
No it is not.

**Comment by nitaliano** [comment]
Closing this out as we just merged in our `v6` rewrite. If this exists in the new version feel free to reopen.
