### ISSUE TITLE
There is no street name

### ISSUE THREAD

**Issue by barbarossusuz** [nitaliano/react-native-mapbox-gl#572]
I am using default Mapbox.mapStyles.streets style, i tested many other devices but there is no street name at all ,street names not showing at any zoom level. 

<img width="506" alt="screen shot 2017-06-20 at 09 53 54" src="https://user-images.githubusercontent.com/21311371/27321364-a90a0e6c-55a2-11e7-813f-e41a95dc951b.png">

<img width="509" alt="screen shot 2017-06-20 at 09 51 01" src="https://user-images.githubusercontent.com/21311371/27321358-a37f27f2-55a2-11e7-866d-d5dcbede9f44.png">

tested on android 5.0, 5.1 and 7.1
"react-native": "0.44.0",
"react-native-mapbox-gl": "^5.1.0",

**Comment by henrikra** [comment]
Did you solve this?

**Comment by barbarossusuz** [comment]
No, unfortunately,  i didn't.

**Comment by nitaliano** [comment]
Closing this out as we just merged in our `v6` rewrite. If this exists in the new version feel free to reopen.
