### ISSUE TITLE
Suggestion: get bounds from screen coordinates

### ISSUE THREAD

**Issue by sethvincent** [nitaliano/react-native-mapbox-gl#574]
It would be useful to get bounds for an area based on screen coordinates.

I've implemented this for android in a fork using `getBounds` and `queryRenderedFeatures` as inspiration: https://github.com/sethvincent/react-native-mapbox-gl/blob/field-data/android/src/main/java/com/mapbox/reactnativemapboxgl/ReactNativeMapboxGLManager.java#L409

Usage example:

```js
onTap = (e) => {
  const x = e.screenCoordX;
  const y = e.screenCoordY;

  const rect = {
    top: y - 50,
    right: x + 50,
    bottom: y + 50,
    left: x - 50
  };

  this._map.getBoundsFromScreenCoordinates(rect, (bounds) => {
    console.log("bounds from screenCoords", bounds);
  });
}
```

> (`this._map` is the MapView ref)

My usecase was to select a large area around a map tap. It could be used in other ways as well.

The `bounds` array is the same shape as what's returned by the `getBounds` method.

I modeled the `rect` options object after the `rect` object that's passed to `queryRenderedFeatures`.

I'd be happy to open a PR for this, as well as get input on improvements or alternate approaches.

**Comment by nitaliano** [comment]
In `v6` bounds are returned in region change event
