### ISSUE TITLE
<Annotation> blocking drag, support for pointerEvents="none"?

### ISSUE THREAD

**Issue by butchmarshall** [nitaliano/react-native-mapbox-gl#575]
The `<Annotation />` tag is blocking the drag event on the map - is it possible to support pointerEvents="none"?

**Comment by vbuch** [comment]
You wouldn't want pointerEvents="none" in a lot of cases. This would cause inability to handle presses.

**Comment by butchmarshall** [comment]
Yes you're correct.  Basically it would be nice if <Annotation /> behaved similar to the annotations array.

**Comment by martsie** [comment]
Having the same issue here, with custom annotations the map becomes unusable because if the user initiates a drag or zoom with their finger accidentally over an annotation the map doesn't respond.

**Comment by nitaliano** [comment]
Closing this out as we just merged in our `v6` rewrite. If this exists in the new version feel free to reopen. I would also recommend using sources and layers as annotation views are being phased out.
