### ISSUE TITLE
Custom Annotations are not positioned correctly

### ISSUE THREAD

**Issue by alixaxel** [nitaliano/react-native-mapbox-gl#579]
Running React Native 0.45.1 and Android 8.0 *(API version 26).

Following on the example provided:

```html
<View style={styles.container}>
  <MapView
    ref={map => { this._map = map; }}
    style={styles.map}
    initialCenterCoordinate={this.state.center}
    initialZoomLevel={this.state.zoom}
    initialDirection={0}
    rotateEnabled={false}
    scrollEnabled={true}
    zoomEnabled={true}
    logoIsHidden={true}
    showsUserLocation={true}
    compassIsHidden={true}
    styleURL={Mapbox.mapStyles.dark}
    annotations={this.state.annotations}
  />
  <Annotation
    id="annotation1"
    coordinate={{latitude: 37.5, longitude: -122.2}}
    style={{alignItems: 'center', justifyContent: 'center', position: 'absolute'}}
  >
    <View style={{width: 100, height: 100, borderWidth: 4, borderColor: 'blue', borderRadius: 50, backgroundColor: 'white', flex: 1, justifyContent: 'center', alignItems: 'center'}}>
      <Text>React View</Text>
    </View>
  </Annotation>
</View>
```

The coordinate for the custom `Annotation` should put it somewhere in Palo Alto, California.

However, it seems to always be absolutely positioned in `(0,0)` of the viewport:

![screenshot_1499809443](https://user-images.githubusercontent.com/262782/28092309-22d0c258-6693-11e7-9d6c-5fd7ea8d3297.png)

Even while panning the map to a total different location, the annotation remains fixed in the viewport:

![screenshot_1499809500](https://user-images.githubusercontent.com/262782/28092330-3792eeaa-6693-11e7-806c-6176d8f7060f.png)

According to the API docs:

> **Known Bugs** Annotation views do not position correctly unless they have the following style props: `style={{alignItems: 'center', justifyContent: 'center', position: 'absolute'}}`.

The style properties are there however I still can't get the desired behavior out of it.

Is this a known issue and are there any workarounds?

**Comment by vbuch** [comment]
@alixaxel are you using this master branch or something else? With master markers are positioned properly for me. I had to merge @rmevans9's fix for displaying images but positioning seems to be fine.

https://github.com/mapbox/react-native-mapbox-gl/compare/master...vbuch:master

**Comment by alixaxel** [comment]
@vbuch I was actually running 5.1.0 (the latest version published on NPM).

I just tried updating to the latest revision in the master branch and the results were the same, until I tried changing the element structure - in 5.1.0 I was getting a `ReactNativeMapboxGLManager cannot be cast to ViewGroupManager` error if `Annotation` was a child of `MapView` element, so I just assumed it was supposed to be on the same level.

With the following structure and on 5.2.0 it actually seems to work as expected:

```html
<View ...>
  <MapView ...>
    <Annotation ...>
      <View...>
        <Text>React View</Text>
      </View>
    </Annotation>
  </MapView>
</View>
```

Thanks for the heads up!

**Comment by vbuch** [comment]
Mentioning 5.2.0 confused me as there is no such release. I guess you meant `master`. Glad to help.

Have you tried using a TouchableHighlight or TouchableWithoutFeedback in the custom annotations? Does it work for you or should I post a new issue?

**Comment by alixaxel** [comment]
@vbuch Yeah, 5.2.0 is the current master as per the [package.json](https://github.com/mapbox/react-native-mapbox-gl/blob/3df91c52448a77fa9972cf8147eaf6a9f513a2e8/package.json#L4).

I tried `TouchableHighlight` but in that case the annotation is simply not rendered on the map.

**Comment by zaguiini** [comment]
+1, cast error

EDIT: Upgrading to 5.2.0 via Github fixes it, but NPM version is 5.1.0... Fix that and people will be good to go.

**Comment by henrikra** [comment]
@alixaxel Is this still an issue?

**Comment by alixaxel** [comment]
@henrikra Not on 5.2.0, but the README is still mentioning the un-scoped NPM package (at version 5.1.0). Since it no longer affects us, I'm gonna close the issue. :)
