### ISSUE TITLE
Simple install

### ISSUE THREAD

**Issue by tmcw** [nitaliano/react-native-mapbox-gl#58]
The ideal install for this module is:

```
npm install --save react-native-mapbox-gl
```

This should install the node module, load the mapbox gl native dependency, and compile it so you can immediately `require('react-native-mapbox-gl')`. Let's figure out what needs to happen to get there.

**Comment by bsudekum** [comment]
pods is about as close as we're going to get https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/install.md#use-cocoapods
