### ISSUE TITLE
Build Failed??

### ISSUE THREAD

**Issue by chc200** [nitaliano/react-native-mapbox-gl#585]
Are you guys planning on fixing this issue?  Also I see the version number got pushed to 5.2.0 to fix the RN .40 headers issue... however in npm the newest version is 5.1.0.  Is this going to be fixed and bumped to the new version?

**Comment by nolan-m** [comment]
Set your dependency version pointed to master and it should work for you.  Really annoying that they haven't pushed a new build to npm.

**Comment by chc200** [comment]
Could you give me an example of that? I never had to do this before so not really sure how to.

**Comment by nolan-m** [comment]
` npm install mapbox/react-native-mapbox-gl --save`
 or editing package.json to be
`"react-native-mapbox-gl": "github:mapbox/react-native-mapbox-gl#bf741d5"`

**Comment by henrikra** [comment]
@chc200 Can you close this if everything is ok? :D

**Comment by nitaliano** [comment]
Closing this out as we are publishing to npm again
