### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by nivoc** [nitaliano/react-native-mapbox-gl#590]
What is the Status of this Projekt? I can see some patches but no Version-Bumps or statments about new React Native Versions. The Examples do not work with the npm packages. If I understand it correct it could work with master but not if I take the npm-package as written in the Documentation.

Mapbox can you please keep a clean dependency status like: This Projekt does need React Native Version X and does not work with the most recent Version... This would save many visitors a lot ot time....

**Comment by carocad** [comment]
I am also a bit concerned about this. In particular because I just encountered a crash in my project that has already been solved in the master branch but the last release was on November last year !

Could you please make an official release? that would help a lot :)

**Comment by dorthwein** [comment]
why can react-native not have a decent map options maintained

**Comment by rubelux** [comment]
We should request MapBox to support RN

**Comment by gvenk** [comment]
A few months ago MapBox was looking for a RN developer and I understood one has been found. I don't know if he/she has started yet, but I hope this project will get out of the experimental state very soon ;-)

**Comment by henrikra** [comment]
@zugaldia Hey when we are getting more resources as you talked here https://github.com/mapbox/react-native-mapbox-gl/pull/587#issuecomment-318050632

**Comment by nitaliano** [comment]
Hi, my name is Nick and I’m going to be doing all things React Native here at Mapbox. I’m excited to jump in and build a strong foundation for flexible, customizable Mapbox maps in React Native. We are working on a plan for the future of the repo and we will be sharing an outline here very soon. Until then I’ll be going through all the open issues and pull requests to get a grasp of the current state of the project, and see what pull requests we should merge in right away. 

Don’t hesitate to share a bit more about how you’re using our tools, either by leaving a comment or by reaching out directly (nick.italiano@mapbox.com). I’m excited to hear what you’re building, what challenges you run into with our maps on React Native, and your number 1 feature request.

**Comment by atarsha** [comment]
Hey @nitaliano! Welcome!

I for one am very excited to hopefully finally see a more responsive involvement in the repo from the managers of it, so that those of us using it for our apps/companies can do so efficiently, and without requiring everybody to fork.

There are quite a few PRs open, many more than a month old (one is mine) and I think getting those handled would be the biggest thing. A combination of a few of those PRs really get the repo back to a good working state, and all that really leaves is cleaning up of the issues section to get this repository back to order.

Thanks, and again, welcome!

**Comment by henrikra** [comment]
@nitaliano Great to hear! I think most required PR are https://github.com/mapbox/react-native-mapbox-gl/pull/600 and https://github.com/mapbox/react-native-mapbox-gl/pull/587
Since without them mapbox causes warnings and crashes with latest React Native

**Comment by nitaliano** [comment]
@henrikra both of those PRs have been merged in

**Comment by henrikra** [comment]
Nice! Could you do a new release?

**Comment by nitaliano** [comment]
Yup I'll make a release later today

**Comment by davidroman0O** [comment]
Hope it will be more stable in the next weeks :p

**Comment by nitaliano** [comment]
Closing this out
