### ISSUE TITLE
Can we add a geocoder control on this map？ 

### ISSUE THREAD

**Issue by HuiguangChu** [nitaliano/react-native-mapbox-gl#591]
Can we add a control like google map did/ we can search an address on this map？

**Comment by maxence-machu** [comment]
Hi, 
You have to add a custom View with a TextInput, then [Geocode the address with MapboxAPI](https://www.mapbox.com/geocoding/) with or the [GoogleMaps Geocoding API](https://developers.google.com/maps/documentation/geocoding/intro) and render the result with an Annotation on the map (marker)
