### ISSUE TITLE
Color stops in property function not rendering

### ISSUE THREAD

**Issue by j1mie** [nitaliano/react-native-mapbox-gl#592]
I've set up a simple map with some color stops in Mapbox studio, which has a population number for each feature.

The map renders perfectly in Mapbox studio, however when I view the map style using MapView component, only the first color stop is visible. Is this expected behaviour? Thanks

<img width="1187" alt="screen shot 2017-07-23 at 23 26 38" src="https://user-images.githubusercontent.com/12685163/28503437-b3f9fece-6ffe-11e7-83d2-b1b5f11be549.png">

![screenshot_20170723-232718](https://user-images.githubusercontent.com/12685163/28503472-4f0f7fe2-6fff-11e7-971a-8f04813f9e31.jpg)

**Comment by henrikra** [comment]
What do you mean by:
> only the first color stop is visible
Can you be more specific? :D

**Comment by j1mie** [comment]
Hi @henrikra I'm referring to color stops used in Mapbox studio (https://www.mapbox.com/mapbox-gl-js/style-spec/#function-stops). You can define these in mapbox studio to visualise ranges in numbers. 

In the first image above, you're seeing two stops: 0 === white, 100 === pink. This renders well in mapbox studio and using the gl javascript api, but only renders as white using react-native-mapbox-gl. That make sense?

**Comment by nitaliano** [comment]
@j1mie runtime and data driven styling in supported in our `v6` rewrite, it was not supported in the experimental versions previous to it.
