### ISSUE TITLE
mapbox/mapbox.h file not found

### ISSUE THREAD

**Issue by zayar** [nitaliano/react-native-mapbox-gl#593]
I just install it but build fail because of 'Mapbox/Mapbox.h file not found in ios.

I tried to install both iOS (manually) and CocoaPods

**Comment by henrikra** [comment]
I did fresh install with RN 0.46 and RNMapboxGL 5.2.0 and it worked. What else you tried?

**Comment by alexaung** [comment]
I tried with 
"react-native": "0.46.3",
"react-native-mapbox-g": "5.2.0".

But got the same error for fresh install.

**Comment by henrikra** [comment]
What have you done so far? Did you do all steps in manual way? Also did you rebuild the app (not just refresh) when everything was done? Be more specific :D

**Comment by JClackett** [comment]
Did all the steps as per the documentation, and getting same error.

Am using the same versions of react-native/mapbox as alexaung

<img width="680" alt="screen shot 2017-07-31 at 16 02 30" src="https://user-images.githubusercontent.com/12549124/28781241-b67caa46-7609-11e7-9497-162eb3687d1f.png">

**Comment by henrikra** [comment]
Please make fresh repo and try to install iOS manually and send link for it. This way we can see your problem :)

**Comment by JClackett** [comment]
Managed to get it working, must have not installed correctly..

**Comment by henrikra** [comment]
@JClackett Great please close the issue :)

**Comment by danieljvdm** [comment]
This has been happening to me over the past few days. It works for a day and then randomly stops working and it's driving me nuts. I've tried manually linking as well as through coccoapods, and they all work for awhile until they stop working after changing nothing to do with the library or the Xcode project.

**Comment by henrikra** [comment]
Looks like for some reason `Mapbox.framework` disappears  from node_modules so it gives error `mapbox/mapbox.h file not found`. Proper fix for this would be to always include `Mapbox.framework` like the PR https://github.com/mapbox/react-native-mapbox-gl/pull/595 is doing

**Comment by henrikra** [comment]
@zayar @alexaung @danieljvdm Please check that your `Mapbox.framework` exists at `node_modules/react-native-mapbox-gl/ios/Mapbox.framework`. If it does not there is your problem :)

**Comment by danieljvdm** [comment]
Yeah this is the issue. I think it's related to whenever you run `npm install` or `yarn install` it's refreshing the modules and deleting the framework for some reason, so I have to uninstall and reinstall every time.

**Comment by studyroz** [comment]
I encountered the same issue after adding `use_frameworks!` and `pod install` in my project.

Removing the line `use_frameworks!` fixes this. But this isn't the right way to fix this.
