### ISSUE TITLE
Component 'RCTMapboxGL' re-registered bubbling event 'topLongPress' as a direct event

### ISSUE THREAD

**Issue by ManAnRuck** [nitaliano/react-native-mapbox-gl#602]
I get this error with Expo and pod install

![simulator screen shot 08 08 2017 15 10 36](https://user-images.githubusercontent.com/2183135/29073397-cb34a9c8-7c4b-11e7-9a5c-08d0de371e91.png)

```shell
exp init mapbox
cd mapbox
npm install --save react-native-mapbox-gl
```

add to app.json
```json
{
   "expo": {
    "ios": {
      "bundleIdentifier": "com.mycompany.myappname"
    },
    "android": {
      "package": "com.mycompany.myappname"
    }
   }
 }
```

```shell
exp detach
```

add `pod 'RCTMapboxGL', :path => '../node_modules/react-native-mapbox-gl/ios'` to ./ios/Podfile

```shell
cd ios
pod install
```

```shell
cd ..
react-native link
```

Change `Header Search Paths` https://github.com/mapbox/react-native-mapbox-gl/issues/495#issuecomment-306078125
<img width="1129" alt="bildschirmfoto 2017-08-08 um 15 14 05" src="https://user-images.githubusercontent.com/2183135/29073545-52641686-7c4c-11e7-8b8e-45d9b3a5d010.png">

```json
{
  "dependencies": {
      "expo": "^19.0.0",
      "react": "16.0.0-alpha.12",
      "react-native": "https://github.com/expo/react-native/archive/sdk-19.0.0.tar.gz",
      "react-native-mapbox-gl": "^5.2.0"
    }
}
```

**Comment by lucasbento** [comment]
@ReggaePanda: did you manage to fix it? I'm having the same problem, not using Expo.

**Comment by nitaliano** [comment]
Closing this out as we just merged in our `v6` rewrite. If this exists in the new version feel free to reopen.
