### ISSUE TITLE
Import PropTypes from "prop-types"

### ISSUE THREAD

**Issue by Gp2mv3** [nitaliano/react-native-mapbox-gl#604]
In RN 0.47, PropTypes is not in react anymore.

Thus, we have to replace imports from:
`import {PropTypes} from 'react'` to `import PropTypes from 'prop-types';`.

Can someone confirm ? If it's the case I can create the pull request.

**Comment by henrikra** [comment]
There is already one #587

**Comment by Gp2mv3** [comment]
Perfect then ! I close this issue.
