### ISSUE TITLE
Offline caching crashes on Android - OfflineRegionStatus.getCompletedResourceSize()

### ISSUE THREAD

**Issue by josenaves** [nitaliano/react-native-mapbox-gl#606]
The app crashes during the download of offline package.
After crash, I could note that the download is in progress.

08-17 13:54:21.655 19813 20421 V com.mapbox.mapboxsdk.http.HTTPRequest: [HTTP] Request was successful (code = 200).
08-17 13:54:21.725 19813 20414 V com.mapbox.mapboxsdk.http.HTTPRequest: [HTTP] Request was successful (code = 200).
08-17 13:54:21.727 19813 20439 V com.mapbox.mapboxsdk.http.HTTPRequest: [HTTP] Request was successful (code = 200).
08-17 13:54:21.728 19813 20418 V com.mapbox.mapboxsdk.http.HTTPRequest: [HTTP] Request was successful (code = 200).
08-17 13:54:21.885 19813 20416 V com.mapbox.mapboxsdk.http.HTTPRequest: [HTTP] Request was successful (code = 200).
08-17 13:54:21.889 19813 20420 V com.mapbox.mapboxsdk.http.HTTPRequest: [HTTP] Request was successful (code = 200).
08-17 13:54:21.896 19813 20421 V com.mapbox.mapboxsdk.http.HTTPRequest: [HTTP] Request was successful (code = 200).
08-17 13:54:21.930 19813 20439 V com.mapbox.mapboxsdk.http.HTTPRequest: [HTTP] Request was successful (code = 200).

Tablet: LGV490
Android: 7.1.2

08-17 13:27:50.068 15425 15425 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.mapbox.mapboxsdk.offline.OfflineRegionStatus.getCompletedResourceSize()' on a null object reference
08-17 13:27:50.068 15425 15425 E AndroidRuntime: at com.mapbox.reactnativemapboxgl.ReactNativeMapboxGLModule.serializeOfflineRegionStatus(ReactNativeMapboxGLModule.java:334)
08-17 13:27:50.068 15425 15425 E AndroidRuntime: at com.mapbox.reactnativemapboxgl.ReactNativeMapboxGLModule._getOfflinePacks(ReactNativeMapboxGLModule.java:360)
08-17 13:27:50.068 15425 15425 E AndroidRuntime: at com.mapbox.reactnativemapboxgl.ReactNativeMapboxGLModule.flushListingRequests(ReactNativeMapboxGLModule.java:259)
08-17 13:27:50.068 15425 15425 E AndroidRuntime: at com.mapbox.reactnativemapboxgl.ReactNativeMapboxGLModule$OfflineRegionsInitialRequest$1.onStatus(ReactNativeMapboxGLModule.java:287)
08-17 13:27:50.068 15425 15425 E AndroidRuntime: at com.mapbox.mapboxsdk.offline.OfflineRegion$2$1.run(OfflineRegion.java:305)
08-17 13:27:50.068 15425 15425 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:751)
08-17 13:27:50.068 15425 15425 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:95)
08-17 13:27:50.068 15425 15425 E AndroidRuntime: at android.os.Looper.loop(Looper.java:154)
08-17 13:27:50.068 15425 15425 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6186)
08-17 13:27:50.068 15425 15425 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
08-17 13:27:50.068 15425 15425 E AndroidRuntime: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
08-17 13:27:50.068 15425 15425 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
08-17 13:27:50.076 2360 2436 W ActivityManager: Force finishing activity com.dispatchr/.MainActivity

**Comment by aferrerallu** [comment]
Hi @josenaves, did you fix this? i'm having the same problem

**Comment by josenaves** [comment]
@aferrerallu the issue is not happening anymore. 
I'm not using the same tablet (LGV490) since it has a non-stable ROM (LineageOS)
My app uses Mapbox version 5.2.0 and it is working good on Android Emulator and other devices (Android 7.x).
