### ISSUE TITLE
Add typescript definition types

### ISSUE THREAD

**Issue by madroneropaulo** [nitaliano/react-native-mapbox-gl#608]
Can we add typescript support by adding ts definition types directly to this repo? I wrote them, and I would prefer to have them in this repo, rather than on definitelyTyped.

**Comment by madroneropaulo** [comment]
I figured out, that it's not a good practice to have the types in the same repo, unless the package itself is written in typescript, as it adds complexity when versioning, and it adds useless typing imports. https://github.com/mapbox/react-native-mapbox-gl/pull/613/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R38 I'll just push to DefinitelyTyped https://github.com/DefinitelyTyped/DefinitelyTyped/issues/19147

**Comment by henrikra** [comment]
Actually it is a good practice to add types to the same repo: https://www.triplet.fi/blog/three-ways-to-provide-typescript-type-definitions-to-3rd-party-libraries/
Can you reopen your PR for types? :)

**Comment by madroneropaulo** [comment]
@henrikra Yeah I didn't know that back then :) Anyway I wrote that like half year ago and I'm not sure if these types are still valid. I stopped working with that repo, Sorry :( I can take a look next weekend if you still need the types.

**Comment by henrikra** [comment]
Yes that would be super awesome!
