### ISSUE TITLE
Blinking markers

### ISSUE THREAD

**Issue by mattimononen** [nitaliano/react-native-mapbox-gl#614]
On my app I've lot of markers and I display only the ones that are inside of the visible bounding box because adding all of them requires too much initial processing time. When user drags the map or zooms I check the bounding box again and update annotations. It seems like updating the markers will re-draw all the them again causing annoying blinking effect after zooming/panning. I think that the markers that remain the same (same id?) shouldn't be re-drawn again. 

Video: https://goo.gl/photos/GMzpwXiYadF2JhhX7

**Comment by gregoireLem** [comment]
I have the same issue, which seems to be only on android

**Comment by benjdlambert** [comment]
@gregoireLem @mattimononen, maybe you could try making the `key` prop the same as the `id`. That should stop the flashing, as React will re-use that view instead of re-rendering.

**Comment by nitaliano** [comment]
Closing this out as we just merged in our `v6` rewrite. If this exists in the new version feel free to reopen. I would recommend using sources and layers and annotation views are being phased out.
