### ISSUE TITLE
iOS preinstall failing due to broken link to mapbox-gl-native iOS SDK + temporary fix

### ISSUE THREAD

**Issue by GeospatialMax** [nitaliano/react-native-mapbox-gl#615]
I just did a fresh install on my system and noticed that the iOS preinstall step failed.

My assumption is that it is due to this broken link: https://mapbox.s3.amazonaws.com/mapbox-gl-native/ios/builds/mapbox-ios-sdk-$VERSION-dynamic.zip

I was able to fix the script by replacing the curl command in https://github.com/mapbox/react-native-mapbox-gl/blob/master/scripts/download-mapbox-gl-native-ios.sh#L16 with:
`
curl -sSL https://github.com/mapbox/mapbox-gl-native/releases/download/ios-v$VERSION/mapbox-ios-sdk-$VERSION-dynamic.zip > temp.zip
`

Don't know if these links are stable though and meant to be included in build scripts.

Obviously this is only a temporary fix as every fresh install will overwrite with the current version from npm.

**Comment by nitaliano** [comment]
I just tried the s3 link and it is working from the bash script and when I goto it directly.  Could you try it out again?

**Comment by GeospatialMax** [comment]
Correct, seems to be working again. Probably just a hickup in S3. Guess can be closed now.
