### ISSUE TITLE
initializeOfflinePacks - correct API.md 

### ISSUE THREAD

**Issue by josenaves** [nitaliano/react-native-mapbox-gl#617]
As I noted, initializeOfflinePacks is not public.

Then it is not possible to call it. 

Please, remove it from API.md documentation.

**Comment by StasDoskalenko** [comment]
I guess NPM package is outdated while git repo is moved forward

**Comment by lesserj** [comment]
@nitaliano It'd be nice if you could publish the latest 5.2.1 branch as a github release so we can reference that version with NPM or Yarn.  The last release version is 5.2.0 from June 15th.  Thanks.

**Comment by nitaliano** [comment]
@lesserj I tagged it for now https://github.com/mapbox/react-native-mapbox-gl/tree/5.2.1.

I'm going to close this out.
