### ISSUE TITLE
Document adding a custom style

### ISSUE THREAD

**Issue by bsudekum** [nitaliano/react-native-mapbox-gl#62]

**Comment by akabab** [comment]
Hey, I'm trying to use a custom style I made on mapbox studio, based on your documentation in MGLMapView.h:

```
@param styleURL The map style URL to use. Can be either an HTTP/HTTPS URL or a Mapbox map ID style URL (`mapbox://<user.style>`). Specify `nil` for the default style.
```

cannot manage to make it work doing so:
`styleURL={'mapbox://akabab.0374f250'}`

I'm getting this error:
`[ERROR] {2}{Map}[Setup]: loading style failed: The requested URL was not found on this server.`

any idea? thanks you

**Comment by bsudekum** [comment]
@akabab A custom style made in mapbox studio will not work, it must be made with with our yet to be released GL editor. Until it is released, you will have to create the GL style from hand. I'd say the best way to do this is load up [mapbox gl js](https://www.mapbox.com/mapbox-gl-js/examples/), point to a local style and make small incremental changes to it.

**Comment by akabab** [comment]
Ok, I think I got it, gonna do that. By the way great job, I might definitly use it, is it still in developpement/improvement (new features comming out (editor release date) ?). I will try to help as possible, hopefully contributing.
