### ISSUE TITLE
Disabling "You Are Here"

### ISSUE THREAD

**Issue by jbamford** [nitaliano/react-native-mapbox-gl#620]
We have a react native app with many pins on a map. When a users position is close to one of the pins they cannot click on the pin due to the message "You Are Here" having a higher clickable priority. How can we disable the clickable "You Are Here" area of the map? 

Thank you

**Comment by atarsha** [comment]
To add to this, on Android, custom annotations are not receiving the tap event at all while the user's location indicator is shown. The user's location should really be the lowest priority for consuming tap events.

**Comment by nitaliano** [comment]
Closing this out as we just merged in our `v6` rewrite. If this exists in the new version feel free to reopen.
