### ISSUE TITLE
Image Overlay

### ISSUE THREAD

**Issue by StasDoskalenko** [nitaliano/react-native-mapbox-gl#621]
Hi, everyone!
Is it possible to create something like in WEB library already done? 
https://www.mapbox.com/mapbox-gl-js/example/image-on-a-map/

For now custom annotations doesn't support dynamic scaling/rotating within the viewport. 
Thanks!

**Comment by nitaliano** [comment]
I believe that just made it's way into gl-native, so once it hit's the native SDKs we'll work on getting that into this repo, all we have for now is a `RasterSource` and `RasterLayer`.

**Comment by akshaysharma21** [comment]
> I believe that just made it's way into gl-native, so once it hit's the native SDKs we'll work on getting that into this repo, all we have for now is a `RasterSource` and `RasterLayer`.

Hey, did this image overlay ever make it into the react-native-mapbox-gl?
