### ISSUE TITLE
Error when `npm install` due to permission issue on Mac

### ISSUE THREAD

**Issue by unionx** [nitaliano/react-native-mapbox-gl#622]
I tried to install by `npm install react-native-mapbox-gl` and get this error:

```
{ Error: Command failed: "/Users/unionx/workspace/status-react/node_modules/react-native-mapbox-gl/scripts/download-mapbox-gl-native-ios.sh" 3.3.1
/bin/sh: /Users/unionx/workspace/status-react/node_modules/react-native-mapbox-gl/scripts/download-mapbox-gl-native-ios.sh: Permission denied

    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:545:12)
  killed: false,
  code: 126,
  signal: null,
  cmd: '"/Users/unionx/workspace/status-react/node_modules/react-native-mapbox-gl/scripts/download-mapbox-gl-native-ios.sh" 3.3.1' }
```

I find when `node download-mapbox-gl-native-ios-if-on-mac.js`, node will spawn a new process with different use and group then cause installation failure.
This issue may cause #593.

**Comment by atarsha** [comment]
I ran into this issue recently too. It's not a Mapbox problem, it's a problem with your NPM installation. Once I resolved that, it started working.

I ended up having to uninstall npm and node then install both using Homebrew.
`brew install node`

**Comment by nitaliano** [comment]
@unionx `nvm` is also a good option to manage different versions of node.  If you install through brew make sure you do a sudo less install.

Going to close this out for now.

**Comment by unionx** [comment]
Yes, brew reinstall node solved the issue. Thx.
