### ISSUE TITLE
Status of 5.x.x

### ISSUE THREAD

**Issue by edwardgalligan** [nitaliano/react-native-mapbox-gl#624]
Not sure if an issue is the right place for asking general questions; apologies if not.

Reading the various updates on v6 ([here](https://github.com/mapbox/react-native-mapbox-gl/pull/618/commits/4696df34ec59872b79778ee64c2d5f016f3e740e), [here](https://github.com/mapbox/react-native-mapbox-gl/pull/619/), and [here](https://github.com/mapbox/react-native-mapbox-gl/wiki/V6-Suggestions)) I'm looking forward to seeing that come to fruition, but I'm wondering what the shorter term plans for this repo are up until v6 is ready.

I see there seems to be continuing activity on merging fixes - e.g. as indicated by [this comment](https://github.com/mapbox/react-native-mapbox-gl/pull/553#issuecomment-327539190) but are there concrete plans for a 5.2.2+ release?

**Comment by nitaliano** [comment]
@lucideer for the short term mostly bugfix PRs will be merged in and branch tags and npm releases will happen when they make sense. All feature development should be focused on v6.

**Comment by edwardgalligan** [comment]
Hi @nitaliano, thanks for replying. Bugfixes are pretty much what I was referring to, yes.

We've been using Mapbox in an RN project and don't really need any extra features beyond what it offers right now (yet), but we're just trying to figure out whether to stick with it given the current stability issues or to switch to another mapping solution(s) in the interim (until v6 is released).

**Comment by edwardgalligan** [comment]
Perhaps it would be good to distil my question here a little bit:

Will Mapbox be doing further work on 5.x.x. before 6 is released, or are you only accepting voluntary/3rd-party PRs and ceasing all internal dev on 5.x.x to focus on v6?

**Comment by nitaliano** [comment]
Correct, we are focusing all development on the new version.  If we do submit a PR for 5.x.x it will only be a bugfix.

**Comment by edwardgalligan** [comment]
> If we do submit a PR for 5.x.x it will only be a bugfix.

This is all I was asking. As I said above, not immediately interested in new features. Does this mean you are now working internally on bugfixes for 5.x.x (you've only said "if" which seems to indicate you are not)?

**Comment by vijayst** [comment]
When will v6 be released?

**Comment by nitaliano** [comment]
@lucideer yes we are currently not focusing on bugfixes unless something critical is brought to our attention like it doesn't work with a newer version of react-native we will jump in and help fix it.

@vijayst Within the next two months is a fair bet.  We will be releasing alphas and betas throughout this process and expect to see the first alpha later this week or early next week.
