### ISSUE TITLE
Turn by turn navigation

### ISSUE THREAD

**Issue by aboeglin** [nitaliano/react-native-mapbox-gl#627]
Hi,

I know for now there's no turn by turn support for the v5. I have checked the roadmap of v6 and didn't see any mention of it. Is there any plan to add such a functionality ? I saw the native SDKs propose that functionality and advertise it as "Add turn-by-turn navigation to your app in under five minutes".

To contributors :
I don't have much experience in bridging native modules, I have a bit of experience on android, and worked on ios quite a while ago but with some effort I could get up to date with objective-c. If anyone could point me in the right direction and help me get started I could take on such a feature. 
Another question, what would be the effort for integrating such a feature ?

**Comment by nitaliano** [comment]
@aboeglin we have experimented with react native and the navigation sdk internally, but we have no official plans on supporting it as of now. Our main focus is to stabilize this repo and get the rewrite out there. 

The navigation sdk components would not be part of this repo, you could imagine a world like this

**react-native-mapbox-gl**
* This repo provides all the mapping components (Mapview, Sources, Layers, Markers)

**react-native-mapbox-navigation**
* This repo would provide services navigation services like (Directions, Estimated Arrival time, ...etc)
* NavigationModal (Custom/Drop In)
* Common navigation ui components

Adding the drop in UI is pretty straight forward to do in react native(following that same pattern that the RN modal implements), but the downside is there would not be much that would be customizable. Wrapping the whole navigation sdk would be a huge undertaking and would be better off handled once this repo is in a better state.

**Comment by j1mie** [comment]
@nitaliano Hi, enjoying using the project so far. Saw you mentioned a rewrite, can you share any timelines / roadmaps for this? Thanks!

**Comment by RWOverdijk** [comment]
@nitaliano Is there any eta on navigation? I'd love to use this in my next app.

**Comment by nitaliano** [comment]
@RWOverdijk there is nothing officially planned yet. I'll bring it up internally again and see where we land on it and let you know.

**Comment by RWOverdijk** [comment]
@nitaliano Awesome! A guide as to how to use the directions api would do as well. I can implement instructions myself (and perhaps even make it a component for react native).

**Comment by nitaliano** [comment]
@RWOverdijk we just did a blog post recently https://blog.mapbox.com/adding-directions-to-the-react-native-store-locator-kit-ade759bd824e and the store locator kit makes use of the directions API https://github.com/mapbox/store-locator-react-native.

Here is a link to our main API documentation - https://www.mapbox.com/api-documentation/#directions

We have a prebuilt JS SDK that also works on RN here is a link to the directions documentation https://github.com/mapbox/mapbox-sdk-js/blob/master/API.md#getdirections

Let me know if you need more information I would be happy to help

**Comment by clarktank** [comment]
@nitaliano Any updates on this FR. It would be really cool to have a turn by turn navigation out of the box!

**Comment by engelzero** [comment]
Turn by turn navigation would be sick af for this.

**Comment by rheng001** [comment]
I agree! This would be great.

**Comment by terryttsai** [comment]
Hi, we want to integrate turn-by-turn navigation in our react native app as well!

**Comment by maks171293** [comment]
+1

**Comment by juergengunz** [comment]
+1

**Comment by dsall** [comment]
+1

**Comment by paul019** [comment]
+1

**Comment by n0emis** [comment]
+1

**Comment by luisRubiera** [comment]
+1

**Comment by nitinsh99** [comment]
+1

**Comment by legend27sg** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by gino8080** [comment]
+1

**Comment by irwangunardi** [comment]
+1

**Comment by ayushnawani** [comment]
I am also waiting for this feature

**Comment by RekarBotany** [comment]
Any news for this feature?

**Comment by dorshay6** [comment]
+1

**Comment by claudioviola** [comment]
+1

**Comment by spotelf13** [comment]
@nitaliano senpai where is this feature at dawg? 😂

**Comment by daywong1119** [comment]
+1

**Comment by patrick-stevenok** [comment]
+1

**Comment by trignodev-manish** [comment]
+1

**Comment by jethromayuk** [comment]
+1

**Comment by 113408** [comment]
Why wouldn’t you try to add the native modules directly to your React Native app ? There is a quick guide over here : https://medium.com/@113408/turn-by-turn-navigation-using-react-native-and-mapbox-eb42c79a0a77

**Comment by cosmin-petrescu** [comment]
+1

**Comment by kevinegstorf** [comment]
+1

**Comment by CyntaxDotDev** [comment]
+1

**Comment by nitish1099** [comment]
+1

**Comment by lidio601** [comment]
+1

**Comment by dancomanlive** [comment]
Any update ???

**Comment by Yingi** [comment]
> Why wouldn’t you try to add the native modules directly to your React Native app ? There is a quick guide over here : https://medium.com/@113408/turn-by-turn-navigation-using-react-native-and-mapbox-eb42c79a0a77

Only for IOS. How about for Android?????????? Android Please!!!!!!!

**Comment by DavidKHahn** [comment]
Any updates for the Android? We'd love support on React Native navigation!

**Comment by swaxtic** [comment]
any update for android now?
