### ISSUE TITLE
Altitude and zoomLevel are mutually exclusive with MapView.easeTo()

### ISSUE THREAD

**Issue by lucasbento** [nitaliano/react-native-mapbox-gl#628]
I'm receiving this warning with the following piece of code:

```js
this.map.easeTo({
  latitude: 52.3574873,
  longitude: 4.8635023,
  zoomLevel: 20,
}, true);
```

Specifying the `altitude` also doesn't help, not sure why it is showing up.

![image](https://user-images.githubusercontent.com/6207220/30263597-d43295c2-96d5-11e7-8186-838622f7a9c1.png)

**Comment by henrikra** [comment]
API says:
>The altitude refers to the viewing altitude of the camera. It's a replacement for zoomLevel, hence zoomLevel and altitude must not be specified at the same time.

**Comment by lucasbento** [comment]
@henrikra: thank you, just made me find out that I was spreading an object that had `altitude` on it!
