### ISSUE TITLE
IOS offline doesn't work

### ISSUE THREAD

**Issue by zoranmarjanovic** [nitaliano/react-native-mapbox-gl#629]
react-native-mapbox 5.2.0, addOfflinePacks doesn't work there is no errors, just called success with null parameter, also getOfflinePacks never execute callback. Android works pretty fine. Any help?

**Comment by nitaliano** [comment]
Are you using the npm package? If so it's out of date try this tag https://github.com/mapbox/react-native-mapbox-gl/tree/5.2.1

**Comment by nitaliano** [comment]
Closing this out as we just merged in our `v6` rewrite. If this exists in the new version feel free to reopen.
