### ISSUE TITLE
Animated moovement on update annotation coordinates

### ISSUE THREAD

**Issue by gregoireLem** [nitaliano/react-native-mapbox-gl#633]
Hello guys, is it possible to see an anotation mooving when updating his coordinates ? ( Like we can see uber's car mooving) 

thanks for helping

**Comment by henrikra** [comment]
@nitaliano I would also like to know how can we animated annotations to new position :)

**Comment by aboeglin** [comment]
It works, just make sure you provide new position data to your annotation and don't mutate it.

**Comment by gregoireLem** [comment]
thanks, it's working fine on ios but all markers are blinking on android at every update. Do you have any idea to avoid this ?

**Comment by gregoireLem** [comment]
@aboeglin When I try, it's just jumping from the first coordinate to the second. Is this normal ? What I want to see is the annotation that is mooving from the first to the second coordinate. Is it possible ? 
thanks

**Comment by nitaliano** [comment]
I'll add an example for doing this in the v6 alpha with a ShapeSource and SymbolLayer it should be the same idea though.

* Get two points
* Interpolate between the points with some easing function
* Update the coordinate each step of interpolation

Ideally I've been messing around with the idea of adding some sort of Animated API to v6 to limit bridge passes

**Comment by henrikra** [comment]
This is great news!!

**Comment by nitaliano** [comment]
I just added a PR that has an example for how to animate a circle layer along a line layer using the Animated API https://github.com/mapbox/react-native-mapbox-gl/pull/705
