### ISSUE TITLE
Brand New Install for Android Crashes On Initial Load

### ISSUE THREAD

**Issue by systemlevel** [nitaliano/react-native-mapbox-gl#637]
I just started with react-native-mapbox-gl with a fresh install.  I have installed the mapbox for android by following the manual instructions located here: https://github.com/mapbox/react-native-mapbox-gl/blob/master/android/install.md

I have attempted loading the example app located here: https://github.com/mapbox/react-native-mapbox-gl/blob/master/example.js

As well as my own simplified version just using the basic `<MapView />  `

In each case, the app crashes on initial load.  See screenshot for what happens.  Has anyone had this issue?  I went through previous list of issues and it looks like some had mentioned issues related to the new Android SDK but those issue seem like they have been resolved.  So it's not clear to me why this is crashing on initial load.

<img width="644" alt="screen shot 2017-09-18 at 5 05 31 pm" src="https://user-images.githubusercontent.com/894983/30569165-760af4d2-9c96-11e7-8ec4-c3ccf5c35b75.png">

**Comment by nitaliano** [comment]
Are you using npm, if so what version? or are you using master?

**Comment by matthieupinte** [comment]
I think I had the same pb here... but with iOS.
Using the last install `5.2.2` with the `@mapbox` npm namespace... follow all install info.

When I try start the app with `react-native run-ios`, after `Build succeeded`, the app launch but stop instantly.
When I try start it with Xcode.. the app launch and stop instantly, but I got a :
<img width="904" alt="screen shot 2017-09-19 at 11 00 25 am" src="https://user-images.githubusercontent.com/2217014/30584405-e5fc2200-9d29-11e7-95ad-61be32381062.png">
from `RCTCxxBridge.mm`

My `package.json` :
```
{
  "name": "MyApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "testwatch": "jest --watch --notify",
    "testcov": "jest --coverage",
    "lint": "eslint app __tests__",
    "build_doc": "documentation build App/** -f md -o documentation.md",
    "serve_doc": "documentation serve App/**",
    "testflight": "fastlane ios beta"
  },
  "dependencies": {
    "@mapbox/react-native-mapbox-gl": "^5.2.2",
    "color": "^2.0.0",
    "raven-js": "^3.14.0",
    "react": "^16.0.0-alpha.12",
    "react-native": "^0.48.3",
    "react-native-extended-stylesheet": "^0.6.0",
    "react-native-linear-gradient": "^2.3.0",
    "react-native-router-flux": "^4.0.0-beta.21",
    "react-redux": "^5.0.3",
    "redux": "^3.6.0"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "documentation": "^4.0.0-beta.18",
    "eslint": "^3.18.0",
    "eslint-config-standard": "^10.0.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^4.0.0",
    "eslint-plugin-node": "^4.2.2",
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-react": "^6.10.2",
    "eslint-plugin-standard": "^2.2.0",
    "jest": "19.0.2",
    "react-native-mock": "^0.3.1",
    "react-test-renderer": "~15.4.1",
    "sinon": "^2.1.0"
  },
  "jest": {
    "preset": "react-native",
    "moduleNameMapper": {
      "^image![a-zA-Z0-9$_-]+$": "GlobalImageStub",
      "^[@./a-zA-Z0-9$_-]+\\.(png|gif)$": "RelativeImageStub"
    },
    "testRegex": "(/__tests__/.*|\\.(test|spec))\\.(ts|tsx|js)$",
    "setupFiles": [
      "./test.conf.js"
    ],
    "testPathIgnorePatterns": [
      "/.history/",
      "/node_modules/"
    ],
    "coveragePathIgnorePatterns": [
      "/node_modules/",
      "/.history/",
      "./test.conf.js"
    ]
  }
}
```

will rollback on `v5.2.0` cause `5.2.1` doesn't work/build.

**Comment by systemlevel** [comment]
@nitaliano Yes, I installed react-native-mapbox-gl using npm.  I was using an older version of npm version 3.10.10 the first time I attempted to run `<MapView />`.  

I then upgraded to the newest npm version 5.4.2 and tried doing a brand new install of react native via `react-native init`.

With the brand new react-native project in place and in a working state, I did an `npm install --save react-native-mapbox-gl`

I then did a `react-native link` and verified that the files had been updated according to the manual installation steps as outlined here: https://github.com/mapbox/react-native-mapbox-gl/blob/master/android/install.md

I loaded the example application once again referenced here:  https://github.com/mapbox/react-native-mapbox-gl/blob/master/example.js

I was hopeful at first because the first thing I saw was an error asking me to put in my mapbox public key.  After putting in the mapbox public key and trying it again I ended up with the same issue as the attached screenshot in the first message of this thread and reattached here (s2h_devices this time).

<img width="644" alt="screen shot 2017-09-21 at 4 24 07 pm" src="https://user-images.githubusercontent.com/894983/30721685-7de898ac-9eea-11e7-95fa-0aa9488b323c.png">

**Comment by systemlevel** [comment]
As a quick addition to the last post I also attempted to update what the automatic link had done to the settings.gradle file.  

In the installation instructions the manual install version says to add the following to the settings.gradle:

```
include ':reactnativemapboxgl'
project(':reactnativemapboxgl').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-mapbox-gl/android')
```
Results in: ` Project with path ':react-native-mapbox-gl' could not be found in project ':app'.`

This differs from what `react-native link` generates:

```
include ':react-native-mapbox-gl'
project(':react-native-mapbox-gl').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-mapbox-gl/android')
```

I attempted both versions and still am unable to have mapbox load without crashing the android emulator.

**Comment by systemlevel** [comment]
One other clarification - I may have misinterpreted your question.  The version of react-native-mapbox-gl I'm using is:

`"react-native-mapbox-gl": "^5.2.0"`

**Comment by systemlevel** [comment]
Hi @nitaliano, just curious if you have any ideas what to try to fix this issue right off hand.  Do you have any initial suggestions you would try?

**Comment by nitaliano** [comment]
@systemlevel I would try `@mapbox/react-native-mapbox-gl@5.2.3-alpha1` we did a npm scope change so `v6` would be under the mapbox org. I can also setup an example project for you and push it to Github if that would be helpful?

**Comment by systemlevel** [comment]
@nitaliano, I'm still not having any luck.  I've attempted a brand new project through `react-native init `and started fresh.  I used `@mapbox/react-native-mapbox-gl@5.2.3-alpha1` but now both ios and android versions do not build.  

In ios I'm getting the same issue as #645 and I've attempted the solution proposed there but still will not build successfully.

In android the build fails with the following message:

```
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources
/Users/darren/Sites/s2h_native/android/app/build/intermediates/res/merged/debug/values-v24/values-v24.xml:3: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
    
/Users/darren/Sites/s2h_native/android/app/build/intermediates/res/merged/debug/values-v24/values-v24.xml:4: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
    
/Users/darren/Sites/s2h_native/android/app/build/intermediates/res/merged/debug/values-v24/values-v24.xml:3: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

/Users/darren/Sites/s2h_native/android/app/build/intermediates/res/merged/debug/values-v24/values-v24.xml:4: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.


:app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

Can you push an example project that successfully builds for both android and ios?  That might prove to be useful.  We have a marketing campaign starting soon so I'm under the gun.

**Comment by nitaliano** [comment]
@systemlevel for android open up your build.gradle file and update `compileSDKVersion` and `targetSDKVersion` to `25`. React native init puts android SDK 23 instead of the newest one. Here is an example for the `v6` branch https://github.com/mapbox/react-native-mapbox-gl/blob/v6/example/android/app/build.gradle#L93

For iOS can you post a screen shot of the libraries you have linked under build phases and your Header and Framework search paths?

**Comment by systemlevel** [comment]
@nitaliano, looks like you nailed the problem.  Thank you for that suggestion.  In summary, here are the two items that you recommended that solved this issue:

1) Use `npm install @mapbox/react-native-mapbox-gl@5.2.3-alpha1 --save` when installing react-native-mapbox.
2) Ensure that in the android `build.gradle` file that both `compileSDKVersion` and `buildToolsVersion` are set to 25 (mine was set to version 23)

At this point the Android mapview is appears to be running correctly.  Thank you for your help.
