### ISSUE TITLE
why onOpenAnnotation is calling onChangeUserTrackingMode ?

### ISSUE THREAD

**Issue by gregoireLem** [nitaliano/react-native-mapbox-gl#640]
Hi, when I am in userTrackingMode.follow, and I tap an annotation, it automatically fires onChangeUserTrackingMode methode (only on IOS). Is there a way to avoid this ?

thanks

**Comment by nitaliano** [comment]
Closing this out as we just merged in our `v6` rewrite. If this exists in the new version feel free to reopen.
