### ISSUE TITLE
Map overlaying other map on Android

### ISSUE THREAD

**Issue by carljoachim** [nitaliano/react-native-mapbox-gl#641]
I am using several Mapviews in my React Native app. For iPhone everything works fine, but for Android the map on the frontview reappears as an overlay in another view.

**Comment by MindFreeze** [comment]
This happens to me too and I can interact with the map below but the one on top is static.
I doubt anyone will fix this in v5 but we can hope it will not be a problem in the upcoming v6.

**Comment by vantuh** [comment]
Same issue. How we can solve that?
I'm using react-navigation and I have to get current routeName with redux and hide previous map (like set that style to display: 'none' or something like that).
Frankly speaking I know that this soultion looks awful, but I don't know how i can solve that in another way.
Can anyone help us with that?

**Comment by carljoachim** [comment]
I managed to work around this issue by opening my fullscreen maps (in different views) in Modals.

**Comment by nitaliano** [comment]
Closing this out as we just merged in our `v6` rewrite. If this exists in the new version feel free to reopen.

**Comment by iorena** [comment]
Encountering this problem in 6.0.1
