### ISSUE TITLE
Super slow performance on initialization

### ISSUE THREAD

**Issue by danieljvdm** [nitaliano/react-native-mapbox-gl#642]
I'm on v 5.2.2 (iOS).

On render of my map view my UI thread drops massively, sometimes to 1fps. In release mode it's slightly better but causes very noticeable lag when the screen it is on is pushed. I've also tested setting a timeout for it to render and when it does render (after the rest of the screen) it locks up the UI thread for a second or two and frame rate plummets. 

Scroll performance is also super laggy once the component is rendered. 

Here is my code:

```
const getAnnotation = (coordinate: Coordinate): Annotation => ({
  id: '1', // doesn't matter, only using one
  type: 'point',
  coordinates: [coordinate.latitude, coordinate.longitude],
});

const Map = ({ coordinate }: Props) =>
  <MapView
    style={{ height: 200 }}
    initialCenterCoordinate={coordinate}
    initialZoomLevel={13}
    annotations={[getAnnotation(coordinate)]}
  />;
```

**Comment by nitaliano** [comment]
When you mean push are you referring to a navigation push? If so which one.
What version of xcode are you using?

**Comment by danieljvdm** [comment]
I'm referring to a navigation push (react-navigation) but I don't think it matters based on what I said above about the `setTimeout`.

I'm on Xcode 9 - not sure what that has to do with anything though.

**Comment by nitaliano** [comment]
There is an issue with xcode 9 iOS 11 simulators currently.

Checkout these issues
https://github.com/mapbox/mapbox-gl-native/issues/9959
https://openradar.appspot.com/radar?id=6138518606708736
https://twitter.com/stroughtonsmith/status/910203896332783616

One way to work around it is to use a 10.3.1 simulator.

**Comment by danieljvdm** [comment]
So I'm aware of these issues, but the issue also exists on my device. It's far more drastic on the simulator due to the GL issues, but this view that is being pushed has absolutely no performance issues without the map, but causes fps drops when rendered.

**Comment by danieljvdm** [comment]
So on further investigation it seems that the first time load is the big issue. Once that happens, every further render is at 60fps. But the first drops to 30 or less. Is there a way I can preload Mapbox GL? I can provide a video if you want.

**Comment by nitaliano** [comment]
I'll debug it and see if anything weird is going on. With the current sdk there is not going to be a sane of preloading it.

Honestly your best bet is going to be using our officially supported `v6` branch once it's ready as it won't have the same type of performance issues as our experimental `v5` branch.

**Comment by danieljvdm** [comment]
Makes sense. What is the ETA of v6?

**Comment by StasDoskalenko** [comment]
@nitaliano hey! Could you please push 5.2.3-alpha1 code to the git to resolve Android issue? Thanks!

**Comment by nitaliano** [comment]
Closing this out as we just merged in our `v6` rewrite. If this exists in the new version feel free to reopen. If you notice this on release builds feel free to reopen

**Comment by bojanaleksa** [comment]
Noticed a very slow load on android, both test and production, ios fine
mapbox version 6.1.3
White screen shows for 2 - 15sec, then map loads tile by tile, always lower tiles first, if important. Also noticed slower rendering time when app has already been opened and closed. First time around after installation it's sometimes fast, sometimes slow, but after that always slow.
Tried with most basic example, android versions 7.0 and up.
Thanks

**Comment by neopit** [comment]
I just bump my React native project on 0.57.4, Xcode 10.1 and iOS 12 and the map initialization is very slow on my computer and never finish on my real device (iPhone7).

Any idea of the issue ?

**Comment by seeya** [comment]
I'm facing the same issue. On development it loads slightly faster. When I build on android and ios on a release build, the map tiles seems to load very quickly but hangs afterwards. In terms of hang I mean the UI thread is blocked, I cannot press any buttons on my screen but the map can still be panned. After about 15 seconds or sometimes it crashes the map will be loaded. 

I'm using `mapbox 6.1.3` and react native `0.57.1`. It is really unusable with the random crashes.
Any idea how to fix this?

**Comment by designervoid** [comment]
Any ideas how to fix it on the simulator?

**Comment by systemlevel** [comment]
@designervoid this repo is no longer actively maintained. This is the community-maintained version: https://github.com/react-native-mapbox-gl/maps

**Comment by designervoid** [comment]
@systemlevel oh yeah i mean that repo
