### ISSUE TITLE
linker command failed with exit code 1 

### ISSUE THREAD

**Issue by gregoireLem** [nitaliano/react-native-mapbox-gl#645]
After unlink & folowing the ios install i got this error in xcode. Any clues ?

<img width="664" alt="capture d ecran 2017-09-25 a 12 03 46" src="https://user-images.githubusercontent.com/31652880/30807713-5299392c-a1fb-11e7-92f2-0fe8e28bf268.png">

thanks

**Comment by nitaliano** [comment]
Did you also embed `Mapbox.framework` into the xcode project from `@mapbox/react-native-mapbox-gl/ios/Mapbox.framework`?

**Comment by gregoireLem** [comment]
yes ! 
![capture d ecran 2017-09-25 a 19 23 14](https://user-images.githubusercontent.com/31652880/30821884-2979cc92-a227-11e7-9967-96a11d54ce7f.png)

**Comment by matthieupinte** [comment]
Hie,
Done the same... before I was using `5.2.0` (working well) and tried to upgrade and install last one `5.2.3-alpha1`, following install steps, ending with :
```
ld: framework not found Mapbox
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Done all steps... sorry, maybe I missed something when I "unlink" the old version of my project.
But looks like the same as @gregoireLem issue ;)

**Comment by nitaliano** [comment]
Go into your application target under `Build Settings` search for `FRAMEWORK_SEARCH_PATHS` and try adding this line `$(PROJECT_DIR)/../node_modules/@mapbox/react-native-mapbox-gl/ios`.

**Comment by gregoireLem** [comment]
Yes that was it ! Thanks @nitaliano

**Comment by nitaliano** [comment]
Great glad it helped, I'll update the install instructions today. I'll leave this open until then.

**Comment by ghost** [comment]
Adding the above suggested `$(PROJECT_DIR)/../node_modules/@mapbox/react-native-mapbox-gl/ios` to framework search paths seems to then give me an error `framework not found XCTest`

Any suggestions please? 

Thanks very much!

**Comment by nitaliano** [comment]
@michaelstokes would you be able to post an example repo with your issues so i can pull it down and see what needs to be updated?

**Comment by ghost** [comment]
Thanks for the response @nitaliano Sure, its just the project has gotten considerably large and might be difficult to replicate to such extent.

Just a bit confused by the issue after trying both CocoaPods and manual approaches. 

What might cause a thing to result in not finding a framework? 

I've attached some more images relating to my linked libraries, framework and header search paths

![screen shot 2017-12-11 at 17 10 20](https://user-images.githubusercontent.com/7087915/33846170-ad740ac8-de9d-11e7-8163-cbb4d3fc5344.png)
![screen shot 2017-12-11 at 18 02 28](https://user-images.githubusercontent.com/7087915/33846172-ada17f80-de9d-11e7-8f66-e8d55cefcada.png)
![screen shot 2017-12-11 at 18 03 04](https://user-images.githubusercontent.com/7087915/33846173-aed722c4-de9d-11e7-9ff7-53f520304d0e.png)

**Comment by ghost** [comment]
Update #860 seems related to libc++abi.dylib: terminating with uncaught exception of type NSException (lldb)
