### ISSUE TITLE
Missing support for custom annotation anchor / centerOffset

### ISSUE THREAD

**Issue by hannta** [nitaliano/react-native-mapbox-gl#646]
With current implementation is is not possible to set custom annotation coordinate point location (anchor), it is always set to center of the custom annotation. If you have e.g. typical marker style annotation and want to set the coordinate point to bottom of the custom annotation, you need to add empty space to bottom of the annotation to shift the actual marker up.

This hack has side effects, empty space receives touch events etc..

Mapbox native (Android & iOS) sdk's support setting custom annotation coordinate point, it would be very helpful to bring this feature to react-native implementation.

**Android**
- Current implementation sets `anchor` to always center: [ReactNativeMapboxGLView](https://github.com/mapbox/react-native-mapbox-gl/blob/76faba2362421ef28309daf3f6c586c7cc0070ee/android/src/main/java/com/mapbox/reactnativemapboxgl/ReactNativeMapboxGLView.java#L263) 
- Bring `anchor` from native sdk to react native implementation. 

**iOS**
- Native iOS sdk has annotation `centerOffset`, [documentation](https://www.mapbox.com/ios-sdk/api/3.6.3/Classes/MGLAnnotationView.html#/c:objc(cs)MGLAnnotationView(py)centerOffset), but it is not used in react native implementation.
- Bring `centerOffset` from native sdk to react native implementation.

**Comment by henrikra** [comment]
```diff
if ([subview isKindOfClass:[RCTMapboxAnnotation class]]) {
    RCTMapboxAnnotation * annotation = (RCTMapboxAnnotation *) subview;
    annotation.map = self;
+    annotation.centerOffset = CGVectorMake(0, -40);
    [_map addAnnotation:annotation];
    [_reactSubviews insertObject:annotation atIndex:atIndex];
}
```

I tried adding this to `RCTMapboxGL.m` on line 141 and it actually moved the annotation to right direction for us. 🎉  Now would be nice if someone with better Objective C skills than me @nitaliano  could make it so that I can `centerOffset` from props like this: 
```js
<Annotation
  id="myMarker"
  coordinate={...}
  centerOffset={{x: 0, y: -40}}
>
  {/* custom stuff here */}
</Annotation>
```
Maybe android after that? :)

**Comment by nitaliano** [comment]
This is implemented now on https://github.com/mapbox/react-native-mapbox-gl/pull/677. It's called `anchor` and you can give it an x,y value from [0, 1] which starts in the top left hand corner of the annotation.
