### ISSUE TITLE
[iOS] Touch does not go through custom marker on 2nd render

### ISSUE THREAD

**Issue by henrikra** [nitaliano/react-native-mapbox-gl#647]
Gif of the problem is here: https://imgur.com/a/GoHzi
Reproduction repo here: https://github.com/henrikra/mapbox-custom-annotations

When I render custom marker without condition statement aka markers are rendered once then my touch events go through the marker which is good thing. But when my condition is true so that the second marker is rendered to the map my touches does not go through the markers at all! This is preventing me from dragging the map around which is very annoying.

In example code when `toMarker` is rendered both markers prevent touch event through them!

```js
<MapView>
  <Annotation
    id="fromMarker"
    coordinate={{
      latitude: fromLocation.location.lat,
      longitude: fromLocation.location.lon,
    }}
  >
    {/* stuff */}
  </Annotation>
  {this.state.toLocation && (
    <Annotation
      id="toMarker"
      coordinate={{
        latitude: toLocation.location.lat,
        longitude: toLocation.location.lon,
      }}
    >
      {/* stuff */}
    </Annotation>
  )}
</MapView>
```

Tell me if you need more info @nitaliano

**Comment by henrikra** [comment]
@1ec5 @nitaliano @bsudekum I have now added GIF and reproduction repo so the bug is very clear:) Tell me guys if you need more info ;)

**Comment by henrikra** [comment]
@jackfengji Can you check this out since you have touched the ios annotations the last :)?

**Comment by martsie** [comment]
This is a similar issue to https://github.com/mapbox/react-native-mapbox-gl/issues/575 and https://github.com/mapbox/react-native-mapbox-gl/issues/559 where touches aren't being propagated to the mapview at all.

**Comment by henrikra** [comment]
I think @nitaliano fixed these problems in v6 :)

**Comment by nitaliano** [comment]
Closing this out as we just merged in our `v6` rewrite. If this exists in the new version feel free to reopen.
