### ISSUE TITLE
How to scale map based fixed center point?

### ISSUE THREAD

**Issue by znacloud** [nitaliano/react-native-mapbox-gl#648]
when doubleclick to scale map ,how could I make the map scale with a fixed center rather than  click  position?

**Comment by Gp2mv3** [comment]
I'm also interested by that ! On Android it seems a double click zooms in center but the pinch to zoom isn't zooming to the center of the screen/map.

**Comment by nitaliano** [comment]
You could try to intercept those events and call `this.map.zoomTo` but there's really not much that can be done to achieve this without a hack
