### ISSUE TITLE
Unable to find libRCTMapboxGL.a

### ISSUE THREAD

**Issue by stdavis** [nitaliano/react-native-mapbox-gl#651]
I'm unable to complete step 4 of the [iOS install instructions](https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/install.md) because `libRCTMapboxGL.a` isn't an option. What am I missing?

![image](https://user-images.githubusercontent.com/1326248/30979068-c1264fa2-a439-11e7-8379-5cbe0ee5c5a6.png)

**Comment by stdavis** [comment]
Or is it `libRCTMGL.a`? I added that one but my build is still failing so I'm not sure that it's correct or not.

![image](https://user-images.githubusercontent.com/1326248/30979655-84694946-a43b-11e7-8a46-ff3e696fad9c.png)

**Comment by stdavis** [comment]
OK. Updated some imports similar to #495 and now I'm getting:
![image](https://user-images.githubusercontent.com/1326248/30980046-dd260e2e-a43c-11e7-9c46-c78103b38e67.png)

**Comment by nitaliano** [comment]
@stdavis this seemed to help others https://github.com/mapbox/react-native-mapbox-gl/issues/645#issuecomment-332608863

**Comment by stdavis** [comment]
That is the key. Thanks!

**Comment by nitaliano** [comment]
Great glad it helped! closing this out.
