### ISSUE TITLE
How to port react native map to the web ?

### ISSUE THREAD

**Issue by dancomanlive** [nitaliano/react-native-mapbox-gl#653]
Is there a way to get the same map as from react native to the web, with all it s data? Thanks!

**Comment by nitaliano** [comment]
Mapbox GL is supported on the web, and you can do everything on the web that you can do on the mobile platform - https://www.mapbox.com/mapbox-gl-js/api/.

As for sharing the component code with this repo that is unsupported and would require use of [react-native-web](https://github.com/necolas/react-native-web) and we would need to write the underlaying bridge code to Mapbox GL JS.
