### ISSUE TITLE
v6: can't get the example code to run

### ISSUE THREAD

**Issue by jliebrand** [nitaliano/react-native-mapbox-gl#656]
Hi there, first of all congrats on getting v6 to Alpha! 

Unfortunately, I've not had a lot of luck getting it working. The example out of the box gave me the following error:
react/rctbundleurlprovider.h not found

After a bit of poking, I found suggestions I should run react-native upgrade to upgrade the project to react-native 0.47.2.  After doing that, it changed a bunch of files, but now It fails with:
'UIView+React.h' file not found

in RCTMGLMapView.m

Any tips would be most welcome!

**Comment by nitaliano** [comment]
This is something I have patched locally I'll push it today.

Open the example app in Xcode and go to the **Libraries** folder. 
* Click on **RCTMGL.xcodeproj**
* Click on target **RCTMGL**
* Goto the **Build Settings** tab
* Search for HEADER_SEARCH_PATHS
* Update to `$(SRCROOT)/../../../react-native/React`.

Try running from Xcode and it should work now.

**Comment by nitaliano** [comment]
@jliebrand I just pushed the changes with some more features. I did a fresh clone and everything is working. Let me know how it goes.

**Comment by jliebrand** [comment]
Thanks! That looks a lot better now - builds out of the box. 

It does still run in to an error though - on startup I get the standard red error screen with:

TransformError: /Users/xxx/react-native-mapbox-gl/example/index.ios.js: Unexpected token ) (While processing preset: "/Users/xxx/react-native-mapbox-gl/example/node_modules/babel-preset-react-native/index.js")

I'll try to debug this my end given the timezones, and update this bug if I find anything useful

**Comment by jliebrand** [comment]
Seems to be an issue with babel-preset-react-native 3.0.0... Downgrading to 2.1.0 resolves the problem:
```
npm install --save-dev babel-preset-react-native@2.1.0
```

(Not sure that's the actual best solution, but it unblocks me for now :-) )

**Comment by nitaliano** [comment]
What version of node are you running? I just tested it there must be an issue with babel-preset-react-native 3.0.0, it runs on node 8 for me. I'll give 4.0.0 a try and if that doesn't work I'll go back to 2.1.0

**Comment by jliebrand** [comment]
I'm running v6.11.1
(used to be on 8, but that caused some other problem in some other area that I can't quite remember now - so stuck on 6)

**Comment by nitaliano** [comment]
Going to close this out. I'll publish another alpha today that has a different preset that works with node 6 and up
