### ISSUE TITLE
[IOS] Error when update custom annotations

### ISSUE THREAD

**Issue by tayathorn** [nitaliano/react-native-mapbox-gl#660]
I've got this error when I update array for render custom annotation.

**In android, it's work perfectly but in `IOS` got this error.**

![simulator screen shot oct 6 2017 3 22 33 pm](https://user-images.githubusercontent.com/31066087/31269444-a4b7379c-aaaa-11e7-84f1-bf432781862b.png)

This error also appeared when I set annotation state after Mapview rendered. It's only work when I update my state in `componentDidMount()`

Here is some of my code:

```React Native
constructor(props) {
    super(props)

    this.state = {
      annotations: [],
    }
}

componentDidMount() {
    this.setState({
      annotations: AnnotationsData
    })
}

onTap = (location) => {
    let { latitude, longitude } = location

    let id = `${latitude}${longitude}`

    let obj = {
      id,
      lat: latitude,
      lng: longitude
    }

    this.setState({
      annotations: [...this.state.annotations, obj]
    })
}
```

Versions:
```
"dependencies": {
    "react": "16.0.0-alpha.12",
    "react-native": "0.48.4",
    "react-native-mapbox-gl": "5.2.0",
  },
```

**Comment by henrikra** [comment]
Update to latest version https://www.npmjs.com/package/@mapbox/react-native-mapbox-gl
Latest version is 6.0.0-alpha3 where this bug is already fixed
