### ISSUE TITLE
[Android] When showsUserLocation is true custom annotations don't receive touch event

### ISSUE THREAD

**Issue by henrikra** [nitaliano/react-native-mapbox-gl#661]
If you set `showsUserLocation` to `true` on `MapView` and use custom markers inside of `MapView` the marker can't receive any touch events on Android. Therefore adding `TouchableOpacity` etc is useless. 

Hot fix for this is to set `showsUserLocation={false}` which is not ideal. 

React Native: 0.48.4
react-native-mapbox-gl: ^5.2.3-alpha1

Example code:
```js
<MapView 
  showsUserLocation={true}
>
  <Annotation
    id="badAssMarker"
    coordinate={...}
  >
    <TouchableOpacity onPress={() => this.showTimePicker('departure')}>
      <View style={{width: 75, height: 75, backgroundColor: 'red'}}>
        <Text >
          Hello there
        </Text>
      </View>
    </TouchableOpacity>
  </Annotation>
</MapView>
```

**Comment by nitaliano** [comment]
Yes unfortunately this is a problem with the current marker implementation.  I'm working on the `v6` implementation right now and this is what the API will look like. Instead of having the custom view add the onPress the native code will handle this for us similar to how it's handled in react-native-maps.

```
<MapboxGL.PointAnnotation 
      id='annotation1'
      onPress={() => console.log('YAYY!')}
      style={{ width: 65, height: 65 }}
      coordinate={[lng, lat]}>

     <View style={....} />

</MapboxGL.PointAnnotation>
```

**Comment by nitaliano** [comment]
Closing this out as we just merged in our `v6` rewrite. If this exists in the new version feel free to reopen.
