### ISSUE TITLE
[v6] MapboxGL.requestPermissions() not response anything at first time

### ISSUE THREAD

**Issue by YKK101** [nitaliano/react-native-mapbox-gl#662]
I'm using v6.0.0-alpha3.
after I click "allow" location service nothing response there, but when I kill the app and open it again the requestPermissions() is resolved as isGranted = true, but no userAnnotation on the map

here is some of my code
````
async componentDidMount() {
    if (isPlatformAndroid()) {
      await MapboxGL.requestPermissions()
      .then(({isGranted}) => {
        console.log('isgrant ', isGranted)
        this.setState({
          isUserLocationPermitted: isGranted,
        })
      })
      .catch(err => {
        console.log('err ', err)
        this.setState({
          isUserLocationPermitted: false,
        })
      })
      console.log('here')
      this.setState({ isRender: true })
    } else {
      this.setState({
        isUserLocationPermitted: true,
        isRender: true,
      })
    }
  }
````

**Comment by nitaliano** [comment]
What props are you setting on the MapView?

**Comment by YKK101** [comment]
Here is my render function
```
render() {
    const { isRender, isUserLocationPermitted } = this.state
    console.log('render ', this.state)
    return (
      isRender ? (
        <MapView
          style={{flex: 1}}
          centerCoordinate={MAP_CENTER_COORDINATE}
          styleURL={MAP_STYLE_URL}
          zoomLevel={MAP_DEFAULT_ZOOM}
          minZoomLevel={MAP_MIN_ZOOM}
          maxZoomLevel={MAP_MAX_ZOOM}
          attributionEnabled={false}
          logoEnabled={false}
          showUserLocation={isUserLocationPermitted}
        />
      ) : (
        <View />
      )
    )
  }
```

and config file
```
export const MAP_STYLE_URL = MapboxGL.StyleURL.Light
export const MAP_CENTER_COORDINATE = [100.531339, 13.7270137]
export const MAP_DEFAULT_ZOOM = 18
export const MAP_MIN_ZOOM = 15
export const MAP_MAX_ZOOM = 20
```

**Comment by nitaliano** [comment]
I just took a look and see what's going wrong. Try setting the userTrackingLocation for now to Tracking or Compass to work around it.  I'll push a fix for it tomorrow.

**Comment by nitaliano** [comment]
@YKK101 would you be able to try this branch out? https://github.com/mapbox/react-native-mapbox-gl/tree/bugfix/662 it has the fix on there. You'll need to update your code to call a new method `requestAndroidLocationPermissions` which returns a `boolean`.

```
const isGranted = await MapboxGL.requestAndroidLocationPermissions();
```

Let me know how it goes and I'll publish a new version to npm

**Comment by YKK101** [comment]
Great, It's works now
thanks a lot @nitaliano

**Comment by nitaliano** [comment]
Going to close this out I'll publish a new alpha today

**Comment by GuillotJessica** [comment]
@nitaliano the link  [ https://github.com/mapbox/react-native-mapbox-gl/tree/bugfix/662](https://github.com/mapbox/react-native-mapbox-gl/tree/bugfix/662) return 404
