### ISSUE TITLE
Are offline packs persistent?

### ISSUE THREAD

**Issue by frantisek-dobrota** [nitaliano/react-native-mapbox-gl#664]
Hey guys, I am thinking about using this api in one of my projects and I cannot find out if the offline packs are persistent? If not, is there any way how to save these packs into asyncstorage and then load them? Lets say, I would like to let users to download some packs if necessary, save them and have them in a memory even if the user close/reinstall the app - is this possible? Thanks

**Comment by atarsha** [comment]
That is exactly how offline map packs work. They are persistent.

**Comment by nitaliano** [comment]
What @atarsha said. Going to close this out.
