### ISSUE TITLE
undefined is not an object (evaluating 'MapboxGLManager.mapStyles')

### ISSUE THREAD

**Issue by arefed-zz** [nitaliano/react-native-mapbox-gl#665]
I am trying to render the mapExample provided in the repository, but I receive the above error. when I looked into the index.js in the react-native-mapbox-gl library I realized that the NativeModules imported from react-native is an empty object. 
also I receive 'Warning: Native component for "RCTMapboxAnnotation" does not exist' the expo as well. I have checked the linking and it is dne correctly according to the install instructions. any idea on this?

**Comment by landonmr** [comment]
same here

**Comment by nitaliano** [comment]
@arefed when NativeModules is an empty object that means the native code for react native has not been linked.

I would also suggest that you use our v6 alpha, it has a built in example application https://github.com/mapbox/react-native-mapbox-gl/tree/v6
