### ISSUE TITLE
[v6] Support for sourceLayerID 

### ISSUE THREAD

**Issue by karlguillotte** [nitaliano/react-native-mapbox-gl#669]
Hi, 

I am wondering for the support for `sourceLayerID` has been implemented in layer components. I am having some issues with it, but before digging more I want to confirm it is. 

If it is, I will send a PR to add it as example. 

Thanks!

**Comment by nitaliano** [comment]
Yup that is supported.

Here is an [example](https://github.com/mapbox/react-native-mapbox-gl/blob/v6/example/src/components/FlyTo.js#L74)
