### ISSUE TITLE
[v6] SymbolLayer with style property textOffset

### ISSUE THREAD

**Issue by karlguillotte** [nitaliano/react-native-mapbox-gl#671]
Hi,

Trying to use the `textOffset` on a `SymbolLayer` and it does not work. Below is a screenshot of the error.

![image](https://user-images.githubusercontent.com/744011/31686988-c9576b4a-b33c-11e7-8838-59597ace6a32.png)

Here is my style object:

```
const styles = Mapbox.StyleSheet.create({
    clusterLabel: {
        textSize:12 ,
        textColor: BLACK,
        textHaloColor: WHITE,
        textHaloWidth: 1,
        textField: '{point_count}',
        textOffset: [2, 2],
    }
})
```

I wanted to test with the demo application, but I ran into issues with a `babel-preset-react-native` transformation trying to start it. 

Thanks!

**Comment by nitaliano** [comment]
Theres's a bug with the version of `babel-preset-react-native` in the demo app, if you switch to node 8 it will run.

I'll look into textOffset and probably the rest of the SymbolLayer styles to make sure they're working correctly.

**Comment by nitaliano** [comment]
I already see the problem. Some offsets require `NSValue` that is a `CGVector` others require `NSArray<NSNumber *> *`.

**Comment by karlguillotte** [comment]
Thanks @nitaliano ! Ready to test as soon as you have a patch.

**Comment by nitaliano** [comment]
@karlguillotte I added the fix for this on the PR that fixes the iconImage token not working. https://github.com/mapbox/react-native-mapbox-gl/pull/674. Let me know how it goes.

**Comment by karlguillotte** [comment]
It is working! Thanks @nitaliano.

**Comment by nitaliano** [comment]
The fix has been merged into the v6 branch closing out
