### ISSUE TITLE
heatmap layer in react native

### ISSUE THREAD

**Issue by benjaminkoetting** [nitaliano/react-native-mapbox-gl#672]
in the example app there is earthquake clustering shown, how to transform it that it will shown as heatmap like you do it in your js example under:

https://www.mapbox.com/mapbox-gl-js/example/heatmap-layer/

**Comment by nitaliano** [comment]
GL JS is slightly ahead of native GL and it has a specific layer called Heatmap.  That will make it into the mobile platform in the coming months. The best you can do for now is add a blur to the `CircleLayer`

**Comment by bemazo** [comment]
@nitaliano thanks for your answer, one question: how snapchat creates the heatmap? Do they created a new layer, inside the mapbox ios sdk documentation there is no heatmap layer, too?
