### ISSUE TITLE
[v6][ios] can't set iconimage from sprite

### ISSUE THREAD

**Issue by YKK101** [nitaliano/react-native-mapbox-gl#675]
I have 2 question about symbol iconImage

-------------------------------

1st

I've try using symbol iconImage from styleUrl's sprite and It's work on android
but on iOS, I've got this warnning

![screen shot 2560-10-19 at 4 21 16 pm](https://user-images.githubusercontent.com/12131753/31763801-93fd8174-b4e9-11e7-9d93-512504af095a.png)

--------------------------------

2nd
Can I set iconImage anchor to 'bottom'.
I found that I can set iconOffset, but I don't know iconImage width & height

**Comment by nitaliano** [comment]
@YKK101 

1. This is currently a bug on iOS and this PR fixes the issue https://github.com/mapbox/react-native-mapbox-gl/pull/674. Check https://github.com/mapbox/react-native-mapbox-gl/issues/668 for discussion.

2. `iconOffset` is going to be your best option for doing so currently. In the GL JS codebase there is a property called `iconAnchor` it has not made it's way to the mobile platform yet.
