### ISSUE TITLE
Migrate 5.2.3 alpha to MGL Native Android 5.2.0-beta.2 - onMapReady callback never invoked 

### ISSUE THREAD

**Issue by StasDoskalenko** [nitaliano/react-native-mapbox-gl#676]
Hey guys!
I'm duplicating my issue from here https://github.com/mapbox/mapbox-gl-native/issues/10223

Hi guys! I've tried upgrade to 5.2.0.
here is my code which works fine with 5.1.4!

```java
private void setupMapView() {
_mapOptions.camera(_initialCamera.build());
_mapView = new MapView(this.getContext(), _mapOptions);
_manager.addView(this, _mapView, 0);
_mapView.addOnMapChangedListener(this);
_mapView.onCreate(null);
_mapView.getMapAsync(this);
}

@Override
public void onMapReady(@NonNull final MapboxMap mapboxMap) {
    //WE NEVER GETS HERE
    if (_mapView == null) { return; }
    _map = mapboxMap;
    ...
 }
```

Thanks!

I've also tried to set styleUrl as:
`_mapOptions.styleUrl(Style.SATELLITE_STREETS);`

**Comment by nitaliano** [comment]
You could try setting the styleURL on the MapView instead of doing it in the options, it might trigger a different codepath.

**Comment by StasDoskalenko** [comment]
@nitaliano thanks for the reply!
I've tried:

```java
private void setupMapView() {
        _mapOptions.camera(_initialCamera.build());
        _mapView = new MapView(this.getContext(), _mapOptions);
        _manager.addView(this, _mapView, 0);
        _mapView.setStyleUrl(Style.SATELLITE_STREETS); // <<<
        _mapView.addOnMapChangedListener(this);
        _mapView.onCreate(null);
        _mapView.getMapAsync(this);
}
```

Still no luck :(

**Comment by StasDoskalenko** [comment]
What I've discovered is that only these events are fired:
Map change listener: 0
Map change listener: 3
Map change listener: 0
Map change listener: 3

**Comment by StasDoskalenko** [comment]
Also when debugging onMapChange (in MapView library file) breakpoint is never invoked too - that
s strange!

**Comment by StasDoskalenko** [comment]
Also tried with v6 version - same result. :(

https://monosnap.com/file/bdnLGnp96S5Brqq0gNoXGuNoyKMgKg

**Comment by nitaliano** [comment]
I'll look into getting the 5.2.0 beta to work later this week. I believe that the gl-core team added async rendering for Android which improves performance so now assumptions that have been made about callback timing will for sure be off. I will let you know what I find out

**Comment by StasDoskalenko** [comment]
@nitaliano awesome, thanks! 
I'll try to fight it too. If I find something - I'll let you know

**Comment by nitaliano** [comment]
Just wanted to update this, I'm seeing the same exact issue as you and only map change events 0, 3 are being fired.

I think what I'm going to do next is create an Android app without RN and see if I can repo it at all.

**Comment by nitaliano** [comment]
I was actually able to get everything working again by adding a `OnAttachStateChangeListener` and listening for when the react view attaches to the window, from there I call `setStyleUrl` and `reflow` and all the examples in `v6` seem to start working again.

```java
public void init() {
        final OnAttachStateChangeListener attachStateChangeListener = new OnAttachStateChangeListener() {
            @Override
            public void onViewAttachedToWindow(View v) {
                setStyleUrl(mStyleURL);
                reflow();
                removeOnAttachStateChangeListener(this);
            }

            @Override
            public void onViewDetachedFromWindow(View v) {

            }
        };
        addOnAttachStateChangeListener(attachStateChangeListener);
}
```

**Comment by StasDoskalenko** [comment]
@nitaliano Thanks, man!!! I get it to work with 5.2.3 alpha.  Modified setupMapView() function and added relayout method from v6.

____
And I just want to say. That is in 5.2.3 was a good implementation for a big amount of markers - all markers were passed via the state. So it's more performant that every marker as a single view. 1 bridge instance vs thousands. Just curious do you plan to implement annotations management via state like in 5.x ???

**Comment by nitaliano** [comment]
@StasDoskalenko we do not. Annotation view are being phased and we should be using a `SymbolLayer` for that, it's infinitely more performant than Annotation views will ever be and they don't shake when you move the map.
