### ISSUE TITLE
[v6] Polyline?

### ISSUE THREAD

**Issue by stephenheron** [nitaliano/react-native-mapbox-gl#678]
Hi,

I am having a look at v6 and I noticed that markers are being implemented.

I was wondering is support for polylines on the roadmap? 

Thanks,
Stephen

**Comment by nitaliano** [comment]
@stephenheron Polylines and Polygons are already supported. Use a `ShapeSource` to provide the GeoJSON and use the `LineLayer` if you want a polyline and a `FillLayer` if you want a polygon. I can provide you with examples if you would like?

**Comment by stephenheron** [comment]
Hi @nitaliano 

Thanks for the quick reply!

I had a look at the LineLayer but I am tad confused on how to pass it the latitudes and longitudes of the points of my line. A quick example or just pointing me in the right direction would be fantastic. 

Thanks,
Stephen

**Comment by nitaliano** [comment]
Here is some example code that is rendering a smiley face https://github.com/mapbox/react-native-mapbox-gl/blob/v6/example/src/components/GeoJSONSource.js. You can see how we use GeoJSON for everything here is a link to the spec https://tools.ietf.org/html/rfc7946. LineString = Polyline.

Example LineString Feature
```
{
  "type": "Feature",
  "geometry": {
    "type": "LineString",
    "coordinates": [
      [
        -44.912109375,
        57.183901858312
      ],
      [
        -33.662109375,
        52.749593726741
      ],
      [
        -26.54296875,
        58.76820015924
      ],
      [
        -18.45703125,
        53.120405283107
      ],
      [
        -10.810546875,
        59.445075099047
      ]
    ]
  }
}
```

I'll add a polyline example to it and let you know when I submit the PR.

**Comment by stephenheron** [comment]
Hi @nitaliano 

I got it working, my line was already in GeoJSON. 

Previously I was parsing the geoJSON to get the Lat/Lng points and then using them to draw a polyline. Just being able to feed in GeoJSON directly is handy and seems to be a tad snappier as I am not having to loop over the geoJSON.

Thanks and keep up the great work,
Stephen

**Comment by subhankarbhattacharjee** [comment]
Hello @nitaliano 
How to show direction between these two coordinates in react-native mapbox?
Can you please help me as I am new in react-native and mapbox .

    import React, { Component } from 'react';
    import { View, StyleSheet, Image } from 'react-native';
    import Mapbox from '@mapbox/react-native-mapbox-gl';

    Mapbox.setAccessToken(  'mykey');

    const coordinates = [
      [-73.98330688476561, 40.76975180901395],
      [-73.96682739257812, 40.761560925502806]
    ];

    export default class MyComponent extends Component<{}> {

      constructor (props) {
        super(props);  
        this.state = {
          coordinates: coordinates
        };
      }

      renderAnnotation (counter) {
        const id = `pointAnnotation${counter}`;
        const coordinate = this.state.coordinates[counter];
        const title = `Longitude: ${this.state.coordinates[counter][0]} Latitude: ${this.state.coordinates[counter][1]}`;
        return (
          <Mapbox.PointAnnotation
            key={id}
            id={id}
            title='Test'
            coordinate={coordinate}>

            <Image
              source={require('./common/images/marker2.png')}
              style={{
                flex: 1,
                resizeMode: 'contain',
                width: 40,
                height: 40
              }}
            />       
          </Mapbox.PointAnnotation>
        );
      }

      renderAnnotations () {
        const items = [];

        for (let i = 0; i < this.state.coordinates.length; i++) {
          items.push(this.renderAnnotation(i));
        }

        return items;
      }

      render () {
        return (
          <View style={{flex: 1}}>
            <Mapbox.MapView
            ref={(c) => this._map = c}
            style={{flex: 1}}
            zoomLevel={19}
            showUserLocation={true}
            userTrackingMode={1}
            centerCoordinate={this.state.coordinates[0]}>
              {this.renderAnnotations()}
            </Mapbox.MapView>
          </View>
        );
      }
    }

    const styles = StyleSheet.create({
      container: {
        flex: 1
      },
      map: {
        height: 400,
        marginTop: 80
      },
      annotationContainer: {
        width: 30,
        height: 30,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'white',
        borderRadius: 15
      },
      annotationFill: {
        width: 30,
        height: 30,
        borderRadius: 15,
        backgroundColor: 'blue',
        transform: [{ scale: 0.6 }]
      }
    });

**Comment by mubasher-tkxel** [comment]
Hi! can we add onPress event for each line on LineString?

**Comment by mubasher-tkxel** [comment]
Hi! can we add onPress event for each line on LineString? My use case is that I want to send details of the line that is pressed to another screen via navigation. 
In react native maps, Polyline has onPress event. Can we achieve that functionality in mapbox as well?
