### ISSUE TITLE
[v6] - Question on how to use VectorSource to bring in an mbtileset hosted on mapbox

### ISSUE THREAD

**Issue by jliebrand** [nitaliano/react-native-mapbox-gl#679]
I've got a quick question, as i'm clearly missing something. I have my own tileset, which contains a handful of layers of data, each with a bunch of properties. I'd like to add a style layer to my map showing one of these layers, using data driven styling. But I don't understand where I link the FillLayer with the layer inside the tileset?

Assume I have a mbtileset called my_tileset uploaded to my mapbox account. Let's say that tileset has four data layers (with ids 'one', 'two', 'three', 'four'). And lets assume layer 'two' has properties including one called 'myPropertyName'.

Given the pseudocode below, where would I link myLayer to the mbtileset layer 'two' ? Or am I not using the VectorSource as intended?

```
const styles = MapboxGL.StyleSheet.create({
  myLayerStyle: {
    fillColor: MapboxGL.StyleSheet.source({
      0: 'green',
      2: 'orange',
      3: 'yellow'
    }, 'myPropertyName', MapboxGL.InterpolationMode.Categorical)
  }
});
...
          <MapboxGL.VectorSource
              id='my_tileset'
              url='mapbox://liebrand.my_tileset'>
            <MapboxGL.FillLayer id='myLayer' style={styles.myLayerStyle} />
          </MapboxGL.VectorSource>
```

**Comment by jliebrand** [comment]
I tried adding the sourceLayerID to the FillLayer (similar LineLayer) but that caused an exception to be thrown

**Comment by jliebrand** [comment]
Updating the title of this bug - I also tried using the LineLayer (as that does have the sourceLayerID) but that causes exceptions to be thrown as well, so I'm clearly not linking to my mapbox hosted tileset correctly (?)

**Comment by jliebrand** [comment]
Just wondering if there's any thoughts on this. Should it be possible to create a line/fill layer from an mbtileset hosted on mapbox with the v6 branch? Or is it simply not quite supported yet?

**Comment by nitaliano** [comment]
@jliebrand `sourceLayerID` is the correct way of doing it, the FillLayer is just missing the prop and there's just a bug when setting the url on the `VectorSource`. I have a working copy locally and I'll submit a PR for it shortly.

**Comment by jliebrand** [comment]
Ah sweet - thanks!

**Comment by nitaliano** [comment]
@jliebrand I added the fix to this https://github.com/mapbox/react-native-mapbox-gl/pull/674. I'll work on getting it merged in today. There is also a custom vector source example now using `FillLayer`.

**Comment by jliebrand** [comment]
Nice one!  Will try to get that working first thing tomorrow morning my time!

**Comment by nitaliano** [comment]
Great! The fix has been merged into the `v6` branch. This is the example https://github.com/mapbox/react-native-mapbox-gl/blob/v6/example/src/components/CustomVectorSource.js

**Comment by jliebrand** [comment]
Works brilliantly, thanks!
