### ISSUE TITLE
[v6] - pitch and rotate gestures too easily triggered

### ISSUE THREAD

**Issue by jliebrand** [nitaliano/react-native-mapbox-gl#681]
I'm not sure if this is a react-native-mapbox-gl issue, or the underlying ios sdk issue?

But on my iPad Pro, I find it's very easy to accidentally trigger a pitch gesture when i'm actually trying to pinch zoom. Similarly, when I try to rotate, it occasionally starts to pitch rather than rotate. And sometimes it doesn't do anything when I try to rotate (until I drag the map around a bit).

In general, the pinch/rotate/pitch gestures seem "off".

PS. is there anyway to turn pitch and rotate gestures off, until this gets a little more love?

**Comment by nitaliano** [comment]
The iOS sdk controls the gestures and I believe they are just `UIGestureRecognizer` under the hood.

You can set `scrollEnabled`, `pitchEnabled`, `rotateEnabled`. Here is a link to all the map props https://github.com/mapbox/react-native-mapbox-gl/blob/v6/docs/MapView.md
