### ISSUE TITLE
[v6] [Android] onRegionDidChange event not firing

### ISSUE THREAD

**Issue by frankrowe** [nitaliano/react-native-mapbox-gl#682]
`onRegionDidChange` event does not work on Android. Tested using the Show Region Did Change page in examples.

Update: Seems to work on double tap to zoom, but not on drag or pinch.

**Comment by nitaliano** [comment]
What version of Android is this happening on? I just tested on a API 26 emulator and I'm seeing the event being fired.

**Comment by frankrowe** [comment]
I have tested on API 23 and API 26 emulators, not getting the event on either.

**Comment by frankrowe** [comment]
^ So that PR fixes it, but I'm not sure if it's correct because the event fires while the map is being dragged, instead of once at the end of the drag. not sure if that is intended behavior :man_shrugging:

**Comment by nitaliano** [comment]
ha, that looks good to me, thanks for the PR! I would be interested in seeing how many times that event fires during a fly to and if it causes any performance issues for the RN bridge

**Comment by nitaliano** [comment]
Closing out fix has been merged into the `v6` branch
