### ISSUE TITLE
iOS installation docs say to use the scoped npm install

### ISSUE THREAD

**Issue by martsie** [nitaliano/react-native-mapbox-gl#685]
Currently the installation docs at https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/install-cocoapods.md say to use the scoped package: `npm install --save @mapbox/react-native-mapbox-gl` however when going to npm's package page for that it says that it corresponds to the v6 alpha version (https://www.npmjs.com/package/@mapbox/react-native-mapbox-gl) to which the rest of the documentation in the master branch does not.

**Comment by nitaliano** [comment]
@martsie we're going to try and get the `v6` branched merged into `master` late next week, so this will be a non-issue soon enough.
