### ISSUE TITLE
Yarn vs npm (yarn: not found)

### ISSUE THREAD

**Issue by MindFreeze** [nitaliano/react-native-mapbox-gl#687]
Installing with `npm i @mapbox/react-native-mapbox-gl` produces `yarn: not found`. It fails because of `yarn run fetch:ios:sdk`. 

Can you make this more agnostic? Otherwise I have to install yarn **only** because of mapbox. Maybe at least do this for npm published versions.

P.S. I am not even going to use the ios SDK. My project is android only, so this is double annoying.

**Comment by nitaliano** [comment]
yea, I'll switch everything to just npm for the next npm release.

**Comment by nitaliano** [comment]
Updated to use only npm in this PR https://github.com/mapbox/react-native-mapbox-gl/pull/705. Another npm release will be going out with that tomorrow.
