### ISSUE TITLE
selectAnnotationAnimated not working in onUpdateUserLocation

### ISSUE THREAD

**Issue by joshbg2k** [nitaliano/react-native-mapbox-gl#69]
I'm having a lot of trouble firing off selectAnnotationAnimated in the onUpdateUserLocation. I'm not trying to do anything crazy, just open up an annotation when the user is close to a point. It gives me EXC_BAD_ACCESS errors. Here is some code:

```
  onUpdateUserLocation(location) {
    var current_lat = location.latitude;
    var current_long = location.longitude;
    this.setCenterCoordinateAnimated(mapRef, current_lat, current_long);
    var locations = this.getInitialState();
    var locations = locations.annotations;

    for (var i = 0; i < locations.length; i++) {
        var distance_from_point = this.distance(current_lat, current_long, locations[i].latitude, locations[i].longitude)
        if (distance_from_point < .01) {
            // you are close to a pin on the map, so do something
            this.selectAnnotationAnimated(mapRef, i);
        }
    }
  }
```

Other methods seem to work just fine. Anyone have any idea why I'm having issues with this one? I've barely modified the example, so there's not much going on here that isn't going on there.

**Comment by joshbg2k** [comment]
This method works on a different machine. You can probably close this issue.

**Comment by bsudekum** [comment]
:+1: re-open if this issue comes back up.
