### ISSUE TITLE
[v6] - not sure how to get current bounds of map?

### ISSUE THREAD

**Issue by jliebrand** [nitaliano/react-native-mapbox-gl#691]
Not sure if this is just missing on the MapView at the moment, but how can I get to the bounds of the current view? mapbox GL JS has "getBounds", should MapView have the same?

And on a similar note, shouldn't the onRegionDidChange return the bounds, rather than a point? (I'm assuming it's returning the centre point?)

**Comment by MindFreeze** [comment]
See #684

**Comment by nitaliano** [comment]
Yup absolutely the MapView will have a getBounds function and the region object is also going to be updated to include the bounds. I'm actually adding it in my PR for offline support.  For now geoViewport is your best option.

**Comment by jliebrand** [comment]
Thanks guys

**Comment by nitaliano** [comment]
I've added support for this on https://github.com/mapbox/react-native-mapbox-gl/pull/696
