### ISSUE TITLE
[v6] Can I set content inset of map viewport?

### ISSUE THREAD

**Issue by YKK101** [nitaliano/react-native-mapbox-gl#693]
I have some component absolute in front of mapview. and I want to add some top padding to mapview to move the compass icon down, but the props **_contentInsets_** is removed. 
Can you suggest me other way to do something like this

**Comment by nitaliano** [comment]
`contentInsets` will be added to the `MapView` I plan on doing a bulk update this week adding some more props to the MapView. If there are any other props that you would like to see let me know.

**Comment by nitaliano** [comment]
I've added support for `contentInset` in https://github.com/mapbox/react-native-mapbox-gl/pull/696
