### ISSUE TITLE
[v6] React native Warnings 

### ISSUE THREAD

**Issue by kristfal** [nitaliano/react-native-mapbox-gl#695]
After installing `react-native-mapbox-gl`, I'm getting the following warning on iOS app launch:

`Warning: Base module "View" does not exist`

and 

```
Module MGLModule requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.
```

Both warnings show multiple times on initial app startup. In the case of the base modul warning, the error is thrown in `MapView.js:19`

```js 
const RCTMGLMapView = requireNativeComponent(NATIVE_MODULE_NAME, MapView, {
  nativeOnly: { onMapChange: true, onAndroidCallback: true },
});
```

Besides these error messages, things work well.

**Comment by nitaliano** [comment]
Warnings have been addressed in https://github.com/mapbox/react-native-mapbox-gl/pull/705

**Comment by nitaliano** [comment]
Going to close this out feel free to reopen if that PR does not fix the issue. I'm merging it in today.
