### ISSUE TITLE
[v6] Add user initiated flag to regionDidChange callback

### ISSUE THREAD

**Issue by kristfal** [nitaliano/react-native-mapbox-gl#697]
In order to keep redux state in sync with map camera state and without risking recursive loops, we'll need to know if it is a user initiated or programmatic event that triggered the region change.

Similar [GL-JS issue](https://github.com/mapbox/mapbox-gl-js/issues/1975), see [this blog post](https://blog.mapbox.com/mapbox-gl-js-in-a-reactive-application-e08eecf0221b) for a bit of backstory.

Addition: We should also be able to track if regionDidChange is triggered by userTrackingMode updates

**Comment by nitaliano** [comment]
This is a great idea! I will look into getting this in the SDK

**Comment by henrikra** [comment]
This is on very high priority for us too! 🌿

**Comment by hannta** [comment]
Any news on this @nitaliano, I think this would be very useful feature for many use cases.

**Comment by nitaliano** [comment]
I'm going to start looking into this next week. This is a very important feature IMO, I've wanted this feature in every app that I've built with this SDK so far. Once we finish adding support for being able to snapshot the map this is next the feature in line

**Comment by nitaliano** [comment]
Does anyone have any opinions on what this will look like. I was thinking we just follow what GL JS has done and add an `originalEvent` property. Curious what others thought could go into the object at a minimum I was thinking

```
{
   type: 'zoom|rotate|pan|...' unsure what the event names will be
}
```

**Comment by nitaliano** [comment]
I have a path forward on this I prototyped an idea to get this information into the region change events, expect a PR to land for this in the next few days.

**Comment by henrikra** [comment]
Wow nice!

**Comment by nitaliano** [comment]
WIP PR is out https://github.com/mapbox/react-native-mapbox-gl/pull/867 feedback would be greatly appreciated let's get this right. I'm eager to get this in so we can start focusing on location support

**Comment by kristfal** [comment]
@nitaliano Had a look, and this is perf! With this, it's now possible to work around the location differences between Android and iOS as well. 

I do have one thought about `regionDidChange` and redux integration: Right now, using fitBounds with padding results in a regionDidChange that represents the derived viewport bounds and center, not the set bounds. This makes things tricky to track, say if we want to update the camera position by changing just the padding and reversing that change afterwards.

I'm wondering: Would it make sense if regionDidChange returned the original camera props for fitBounds, with the padding as a separate key rather than the derived center and bounds?

**Comment by nitaliano** [comment]
Closing this out since we just merged the PR into master.

@kristfal would adding a field called `contentInsets: [top, right, bottom, left]` to the region change be helpful?

**Comment by kristfal** [comment]
@nitaliano Yeh, perf, that would make things a lot easier to track. I'll open a new issue. Thanks for looking at it.
