### ISSUE TITLE
[v6] RegionDidChange behaves differently on iOS and Android

### ISSUE THREAD

**Issue by kristfal** [nitaliano/react-native-mapbox-gl#698]
On iOS, regionDidChange fire after the user interaction is complete. On Android, regionDidChange fire for each frame during the user interaction gesture.

**Comment by nitaliano** [comment]
The Android SDK fires these for every region change and the iOS SDK fires these once the camera has become idle. I have thought about implementing this behavior to the Android side, just as long if it's not a sloppy and brittle ideally we want all of these events to fire the same amount of times on both platforms.

**Comment by kristfal** [comment]
That makes totally sense. I remember we experienced a similar problem with gl-js a while back ago (touch events fired move-end events on each animation frame, whiledrag events fired at end of theanimation). Our temporary workaround was to debounce the callback to something like 10 animation frames. It proved sufficiently stable until a proper fix was done on the lib side.

While this issue is slightly different, I think we could explore to debounce the android callback on the JS side and file an issue in the native lib. Let me know if you are up for PRs yet.

**Comment by nitaliano** [comment]
@kristfal I plan on merging the big `v6` PR into master at the end of this week and once it's in master start sending as many PRs as you would like.

**Comment by nitaliano** [comment]
Closing this out we just merged a PR in to throttle the change event and fire on camera idle instead of when we receive the map change event like the iOS SDK does
