### ISSUE TITLE
[v6] Differences in iOS and Android userLocation behavior

### ISSUE THREAD

**Issue by kristfal** [nitaliano/react-native-mapbox-gl#699]
Hey,

noticed a couple of differences in iOS and Android user location behavior:

1) prop showUserLocation defaults to `true` for iOS and `false` for Android. If not set, iOS will show the location marker while Android will not. When explicitly set, both platforms behave the same.

2) While toggling between track states, iOS will re-center the map at the user's location while Android does not. Android will only update the map location on geolocation ticks.

3) Map gestures resets trackMode on iOS, while Android retains its set trackMode even after user input.

Other potential improvements:

a) Receive user location, bearing and heading on geolocation callbacks or through `regionDidChange` callbacks when initiated by a geolocation update.
b) Expose tintColors for user location markers
c) Reintroduce userLocationVerticalAlignment

**Comment by nitaliano** [comment]
1. I actually fixed this yesterday I was using a `boolean` in Android when I should have been using a `Boolean` so I can tell if the user set the value or not.
2/3. Will look into the differences, both the iOS and Android camera behavior pretty different so hopefully we can chip away at normalizing them.

**Comment by nitaliano** [comment]
Closing this out in favor of https://github.com/mapbox/react-native-mapbox-gl/issues/881

**Comment by nitaliano** [comment]
WIP PR is out https://github.com/mapbox/react-native-mapbox-gl/pull/897 that fixes these issues

**Comment by nitaliano** [comment]
Location PR has been merged into master
