### ISSUE TITLE
Abstract into a module

### ISSUE THREAD

**Issue by bsudekum** [nitaliano/react-native-mapbox-gl#7]
- remove `pod install`
- bundle all mapboxGL header files in project

**Comment by bsudekum** [comment]
working on this here: https://github.com/bsudekum/react-native-mapbox-gl/tree/module

Issue is that currently this project is an app and it needs to be a framework so it's `.a` can be exported.

**Comment by 1ec5** [comment]
Ah yes. Since Swift only works with frameworks as opposed to static libraries, CocoaPods repackages the .a inside a framework.
