### ISSUE TITLE
Add Line/Shape Example

### ISSUE THREAD

**Issue by joshbg2k** [nitaliano/react-native-mapbox-gl#70]
We're looking into how to draw lines for routing, but there doesn't seem to be an example. This would be extremely helpful.

**Comment by bsudekum** [comment]
This is coming. Still working through design decisions here https://github.com/mapbox/react-native-mapbox-gl/pull/66

**Comment by joshbg2k** [comment]
Great, looking forward to it.

**Comment by bsudekum** [comment]
All done, see https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/example.js
