### ISSUE TITLE
Is possible take a ScreenShot of the Map?

### ISSUE THREAD

**Issue by Jose4gg** [nitaliano/react-native-mapbox-gl#700]
Reference: 
https://github.com/airbnb/react-native-maps#take-snapshot-of-map

**Comment by dorthwein** [comment]
+1 - or maybe render the map as a static PNG so that we can use another library to take the screen capture.  Right now https://github.com/gre/react-native-view-shot doesn't seem to capture the GL view on Android ;(

**Comment by nitaliano** [comment]
It's currently not implemented in the react-native SDK. There is support for this in the Android SDK and the iOS SDK is adding support for this in it's next release which should be out within a month.  Once that's released I'll work on adding this feature to the RN SDK

**Comment by dorthwein** [comment]
Thanks @nitaliano - I know y'all are swamped - any thoughts on time frame by chance?

**Comment by berkaytheunicorn** [comment]
@dorthwein did you find any workaround?

**Comment by dorthwein** [comment]
Negative - I’ve heard on the street the guy dedicated to react-native with MapBox is pretty much a killer (in a good way) so we opted to disable the feature, move on until he has time to circle back to it which he commented on above I think.

~DFO~

**Comment by nitaliano** [comment]
The iOS SDK just dropped with support for snapshotting, so next week I'll start working on adding support for it in the RN SDK

**Comment by nitaliano** [comment]
I'll be updating this ticket with progress https://github.com/mapbox/react-native-mapbox-gl/issues/818 expect it to hit in our next release `6.0.2`
