### ISSUE TITLE
[v6] Align feature query API with js and native SDKs

### ISSUE THREAD

**Issue by kristfal** [nitaliano/react-native-mapbox-gl#701]
Hey,

this SDK returns no features when the third argument in `queryRenderedFeaturesInRect` and `queryRenderedFeaturesAtPoint` is empty. The [JS SDK](https://www.mapbox.com/mapbox-gl-js/api/#map#queryrenderedfeatures) and [native SDKs](https://www.mapbox.com/ios-sdk/api/3.6.4/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(im)visibleFeaturesAtPoint:) returns all layers when no layers are defined in their equivalent query methods. These should probably align.

**Comment by nitaliano** [comment]
Yup, agreed will post back once I PR is in

**Comment by nitaliano** [comment]
I just tested this out it seems Android is doing the right thing and returning all features, and on iOS I'm passing in an empty `NSSet` which is for some reason making the call return no features if I switch it to `nil` then it will work as expected. The fix for this will be in `6.0.1`

**Comment by nitaliano** [comment]
Fixed in https://github.com/mapbox/react-native-mapbox-gl/pull/731
