### ISSUE TITLE
[v6] PropType validation warning on textFont arrays

### ISSUE THREAD

**Issue by kristfal** [nitaliano/react-native-mapbox-gl#707]
When using the following declaration:

```js
textFont: ['DIN Offc Pro Medium'],
```
The PropType validation errors for textFont. For some reason, the following propType validator makes the above example pass:

```js
  textFont: PropTypes.oneOfType([
    PropTypes.object,
  ]),
```

Idk if this is a PropTypes bug or if the value is transformed before it is validated.

**Comment by nitaliano** [comment]
I believe that prop type passes because `(typeof [] === 'object') === true` and since `(typeof [] === 'array) === false` we'll have to switch that proptype to maybe be an instance of

**Comment by nitaliano** [comment]
The fix for this is in https://github.com/mapbox/react-native-mapbox-gl/pull/705 going to close this out.
