### ISSUE TITLE
custom markers

### ISSUE THREAD

**Issue by iSimar** [nitaliano/react-native-mapbox-gl#71]
Are custom markers available yet? 

Regards,

**Comment by bsudekum** [comment]
Not available yet, but this should happen. Seems like it should not be too hard, ref [mapbox-gl-native example](https://www.mapbox.com/mapbox-gl-ios/examples/marker-image/).

**Comment by iSimar** [comment]
Awesome, looking forward to it. Thanks

**Comment by iSimar** [comment]
Question - are you going to be making it custom per annotation (what I need) or just one custom marker for the whole map view?

**Comment by bsudekum** [comment]
It will be per annotation.

**Comment by iSimar** [comment]
Awesome, thanks!

**Comment by albertwchang** [comment]
+1 on custom markers/annotations.

**Comment by cyprusglobe** [comment]
+1

**Comment by bsudekum** [comment]
Done in 0.4.0

**Comment by akabab** [comment]
can't find how to setup a custom icon marker, is it released?

**Comment by bsudekum** [comment]
@akabab https://github.com/mapbox/react-native-mapbox-gl/blob/master/example.js#L44-L48

**Comment by akabab** [comment]
oh yeah! thx!

**Comment by Edison4mobile** [comment]
I wanna to add custom icons inside mapview.
In this github, i saw custom icon feature. but the icon path is static value. how can I show dynamic custom icons in mapview?
Thanks
