### ISSUE TITLE
Project with path ':@mapbox_react-native-mapbox-gl' could not be found in project ':app'.

### ISSUE THREAD

**Issue by dungnguyen10989** [nitaliano/react-native-mapbox-gl#710]
I've init a new project, after run 'npm install --save @mapbox/react-native-mapbox-gl@5.2.3-alpha1', in index.js :  ' import MapBox from '@mapbox/react-native-mapbox-gl ' and run project after link library, but always received the same error : unable to resolve module `@mapbox/react-native-mapbox-gl`, module does not exist in the module %projectname% or in these directories.
![screenshot from 2017-11-06 15-08-13](https://user-images.githubusercontent.com/30271788/32431063-7c53c4e2-c304-11e7-9f14-7f2002e77d80.png)
I've open android project by android studio, build.gradle(app) can not compile @mapbox/react-native-mapbox-gl project, it throws out the error : Unable to find module with Gradle path ':@mapbox/react-native-mapbox-gl' (needed by module 'app'.) , and does not project named @mapbox/react-native-mapbox-gl exists in current solution.
Where was I wrong ? and how can i integrate this library for my app ?

**Comment by nitaliano** [comment]
@dungnguyen10989 Hi I would recommend you use our `v6` version, it's going to be merged into master this week.  https://github.com/mapbox/react-native-mapbox-gl/tree/v6

**Comment by dungnguyen10989** [comment]
@nitaliano : thanks for your suggestion, i will try again with v6 and feedback later
