### ISSUE TITLE
Custom annotations not always visible on android

### ISSUE THREAD

**Issue by hannta** [nitaliano/react-native-mapbox-gl#711]
- I have two semi complex custom annotations on map.
- I zoom map to markers using `setVisibleCoordinateBounds`
- If markers are far from each others (= map is zoomed out) markers are not always visible when the animation ends.
- If I touch the map (move it a bit) markers comes to visible.

Im able to reproduce this on `5.2.3-alpha1` and `6.0.0-beta1`

**Comment by nitaliano** [comment]
I'll look into it. Most likely needs a `reflow` method call once the camera goes idle. 

@hannta I'm curious is this something you cannot accomplish with sources and layers?

**Comment by hannta** [comment]
@nitaliano My custom annotations are basically `PointAnnotation`'s with custom views insides. They have also click listeners etc. I was in assumption that for these kind of annotations you should use `PointAnnotation` component?

**Comment by nitaliano** [comment]
It depends on if you can recreate the view using layers, for most cases I don't actually need a View and the performance increase gains are well worth it.

**Comment by hannta** [comment]
I think in my case it is much easier to use views and as I have only two annotations, there should not be performance issues.

@nitaliano did you happened to have time to check, does the `reflow` fix the issue in sdk side?

**Comment by nitaliano** [comment]
Yes, the reflow does help but there still seem to be some cases in the native SDK that will keep them invisible until you move the map(mostly with user's zooming out manually). I'll have the the reflows fix in the next release early next week.

**Comment by nitaliano** [comment]
@hannta let me know if this help https://github.com/mapbox/react-native-mapbox-gl/pull/737

**Comment by hannta** [comment]
Thanks @nitaliano! Can you make (beta?) release with that pr #737?

**Comment by nitaliano** [comment]
Would you be able to point to that branch in your package.json? I'll do a beta release once I get a few more fixes into master

**Comment by nitaliano** [comment]
I published 6.0.1 are you still seeing this issue?

**Comment by hannta** [comment]
Thanks @nitaliano unfortunately I haven't had time to test this very comprehensively but at least it is working better now 👍

**Comment by nitaliano** [comment]
Closing this out. Reopen if you're still seeing this, master has a ton of improvements for annotations

**Comment by rudra0713** [comment]
Hi, I am facing a similar issue. I have a Mapview component and inside that two PointAnnotation with custom view, (my own vehicle icon inside a Touchable opacity).  Both of the markers render fine in IOS but in Android, only one of them gets rendered. If I remove the custom view, then everything works out fine with defaults markers. I do not have any sort of animation. I only used fitBounds method first but then removed that too. But no luck.

**Comment by ancyrweb** [comment]
Still happening in 6.1.0-beta.
When I zoom using zoomTo, the markers tends to disappear until i move a little bit.

**Comment by ancyrweb** [comment]
Moreover i've also noticed that when an annotation is out of the view of the camera, it sometimes disappear and doesn't show off again until I zoom in.
It failed to spot a condition on which this happens. Even with a simple annotation containing a text it still happens :(

**Comment by ancyrweb** [comment]
After digging i've found the problem.
I was using the same React key for a component that was supposed to be new. In other terms, instead of rerendering my PointAnnotation, it would just update it.
The problem is that `RCTMGLMapView` keeps a map of annotations referenced by Annotation ID. Whenever a marker change it's ID, it's de-facto not recognized anymore and therefore is not rendered.

2 possible solutions : 
* Make sure that every children has a unique ref (use the same unique key both for the ref and the Annotation ID)
* Implement a mechanism that allow the  `RCTMGLMapView:mAnnotation` to be updated when a PointAnnotation ID changes

@nitaliano if you opt for the second solution let me know and i'll fill a PR (for Android, at least) :)
