### ISSUE TITLE
If I use react-map-gl ,could I import mapbox-gl  

### ISSUE THREAD

**Issue by wangchen9074** [nitaliano/react-native-mapbox-gl#714]
import MapGL, { SVGOverlay }  from 'react-map-gl';
import mapboxgl from 'mapbox-gl';
I want to know  the MapGL and the mapboxgl   are the same object ?

**Comment by nitaliano** [comment]
@Wwangchen I believe you have the wrong repo this is the react native one. If you're asking if react-map-gl and react-native-mapbox-gl have the same interface they do not.
