### ISSUE TITLE
Inconsistent layer property spelling

### ISSUE THREAD

**Issue by 1ec5** [nitaliano/react-native-mapbox-gl#717]
[LineLayer](https://github.com/mapbox/react-native-mapbox-gl/blob/543e9cca1e4e718378dcf5ea8af2fe016ed6fd32/docs/LineLayer.md) and similar documentation refers to layer properties in camelCase in the “Name” column but in kebab-case in the “Disabled By” column. Which spelling is correct in JavaScript?

/cc @nitaliano

**Comment by nitaliano** [comment]
@1ec5 great catch! Everything should be camel case.

**Comment by nitaliano** [comment]
Fixed in https://github.com/mapbox/react-native-mapbox-gl/pull/720
