### ISSUE TITLE
[v6] Android example application does not build

### ISSUE THREAD

**Issue by butchmarshall** [nitaliano/react-native-mapbox-gl#718]
Everything installs and npm start works, this is under Ubuntu 16.04

When trying to run-android I get:

react-native run-android
Scanning folders for symlinks in [...]/react-native-mapbox-gl/example/node_modules (8ms)
Android project not found. Maybe run react-native android first?

git clone https://github.com/mapbox/react-native-mapbox-gl.git
Cloning into 'react-native-mapbox-gl'...
remote: Counting objects: 6051, done.
remote: Compressing objects: 100% (151/151), done.
remote: Total 6051 (delta 121), reused 182 (delta 84), pack-reused 5784
Receiving objects: 100% (6051/6051), 13.16 MiB | 22.07 MiB/s, done.
Resolving deltas: 100% (3397/3397), done.
Checking connectivity... done.
butch@work-desktop:~/workspace$ cd react-native-mapbox-gl/
butch@work-desktop:~/workspace/react-native-mapbox-gl$ cd example/
butch@work-desktop:~/workspace/react-native-mapbox-gl/example$ npm install

> react-native-mapbox-gl-demo@0.0.1 preinstall [...]/react-native-mapbox-gl/example
> npm run pack:gl

> react-native-mapbox-gl-demo@0.0.1 pack:gl [...]/react-native-mapbox-gl/example
> ./scripts/npm_pack_rngl.sh

Moving into 
Attempting to pack react-native-mapbox-gl
mapbox-react-native-mapbox-gl-6.0.0-beta2.tgz
npm WARN deprecated @turf/nearest@4.7.3: Module has been renamed to @turf/nearest-point
npm WARN deprecated @turf/line-distance@4.7.3: Module deprecated in favor of @turf/length
npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated

> @mapbox/react-native-mapbox-gl@6.0.0-beta2 preinstall [...]/react-native-mapbox-gl/example/node_modules/@mapbox/react-native-mapbox-gl
> npm run fetch:ios:sdk

> @mapbox/react-native-mapbox-gl@6.0.0-beta2 fetch:ios:sdk [...]/react-native-mapbox-gl/example/node_modules/@mapbox/react-native-mapbox-gl
> node ./scripts/download-mapbox-gl-native-ios-if-on-mac.js 3.6.4

> react-native-elements@0.16.0 postinstall [...]/react-native-mapbox-gl/example/node_modules/react-native-elements
> opencollective postinstall

                   Thanks for installing react-native-elements 
                 Please consider donating to our open collective
                        to help us maintain this package.

                           Number of contributors: 102
                              Number of backers: 10
                             Annual budget: US$ 1,804
                             Current balance: US$ 851

      Donate: https://opencollective.com/react-native-elements/donate

> react-native-mapbox-gl-demo@0.0.1 postinstall [...]/react-native-mapbox-gl/example
> node ./scripts/set_access_token.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN react-native@0.49.5 requires a peer of react@16.0.0-beta.5 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1222 packages in 29.841s
butch@work-desktop:~/workspace/react-native-mapbox-gl/example$ npm start

> react-native-mapbox-gl-demo@0.0.1 start [...]/react-native-mapbox-gl/example
> node node_modules/react-native/local-cli/cli.js start

Scanning folders for symlinks in [...]/react-native-mapbox-gl/example/node_modules (8ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   [...]/react-native-mapbox-gl/example 

React packager ready.

Loading dependency graph, done.

react-native run-android
Scanning folders for symlinks in [...]/react-native-mapbox-gl/example/node_modules (8ms)
Android project not found. Maybe run react-native android first?

**Comment by nitaliano** [comment]
Try opening it in Android Studio first to generate your gradle files.

**Comment by josenaves** [comment]
@butchmarshall , in my case, I created the accesstoken file and had to change gradlew file to turn it an executable.
Then, I had to open the android project on Android Studio. Several updates and fixes before, 

I also changed my project build.gradle file to have this:

        classpath 'com.android.tools.build:gradle:2.2.3'


and gradle-wrapper.properties to be like this:

distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip

**Comment by josenaves** [comment]
@butchmarshall here is a gist

https://gist.github.com/josenaves/572bd26ceea80974ca388c9de4d4f93c
