### ISSUE TITLE
Enhancement Request:  Actionable Annotations/markers

### ISSUE THREAD

**Issue by albertwchang** [nitaliano/react-native-mapbox-gl#72]

**Comment by bsudekum** [comment]
@achang28 what do you mean by actionable? There are event 2 handlers handlers on annotations:
- `onOpenAnnotation`
- `onRightAnnotationTapped`

**Comment by albertwchang** [comment]
I believe at the time of submitting this issue such instructions weren't available. If I was wrong, my apologies. Will close out

**Comment by bsudekum** [comment]
:+1: no worries
