### ISSUE TITLE
[v6] Silly question: which native sdk is used?

### ISSUE THREAD

**Issue by jliebrand** [nitaliano/react-native-mapbox-gl#722]
Hi there,

I was going to see which version of android native sdk is used and see if I could update it to test this gestures bug:
https://github.com/mapbox/mapbox-gl-native/issues/8403#issuecomment-343130357

But whereas I kinda expected there to be a dependency on mapbox-gl-native in the package.json, all I can see is references to installing the iOS sdk?  Where is the Android SDK being pulled in, and which version is being used right now?

**Comment by nitaliano** [comment]
Gradle pulls it in. We are on the latests stable Android release 5.1.4 https://github.com/mapbox/react-native-mapbox-gl/blob/master/android/rctmgl/build.gradle#L31
