### ISSUE TITLE
[v6] Pitch seems to work in iOS but not on Android

### ISSUE THREAD

**Issue by jliebrand** [nitaliano/react-native-mapbox-gl#724]
I use the following bit of code:
```
    this.mapbox.setCamera({
      heading: 23,
      pitch: 60,
      zoom: 15,
      duration: 500
    });
```

Which seems to work ok on iOS, but on android it does not pitch the camera

**Comment by nitaliano** [comment]
@jliebrand this is fixed in `6.0.2`

**Comment by jliebrand** [comment]
Nice one, thanks!

**Comment by lilykaiser** [comment]
Assuming this can be fixed, closing! Please re-open if this is still an issue
