### ISSUE TITLE
[v6] Pitch with a float heading crashes on ios

### ISSUE THREAD

**Issue by jliebrand** [nitaliano/react-native-mapbox-gl#725]
The following piece of code caused a crash on iOS (sorry didn't get the callstack but thought I'd raise it anyway). Will add stack traces etc if i see this again (although right now, i'm just rounding the heading to a number to work around this issue)

```
    this.mapbox.setCamera({
      heading: 23.3,
      pitch: 60,
      zoom: 15,
      duration: 500
    });

```

**Comment by josenaves** [comment]
@jliebrand The documentation about setCamera is wrong.

You should use something like that:

``` 
        this.MBMap.setCamera({
          stops: [ {
             heading: 23.3,
            pitch: 60,
            zoom: 15,
            duration: 500
          } ]
        });
```

**Comment by jliebrand** [comment]
Both APIs seem to work. And as it happens, I can not reproduce the crash now. So I'll close this and re-open a new bug if/when I ever see the crash again
