### ISSUE TITLE
[v6] Tapping on custom callout also selects point annotation hidden below it

### ISSUE THREAD

**Issue by mlandauer** [nitaliano/react-native-mapbox-gl#726]
I have a custom callout (show below) which has a `TouchableHighlight` in it.

![image](https://user-images.githubusercontent.com/2221/32620396-c495562e-c5d1-11e7-9db6-0aa5bcb7fec9.png)

When the callout is tapped the callback for `TouchableHighlight` is called as expected. That's all good.

However, if there is a point annotation immediately underneath the callout where I tapped that will get selected. When I tap the callout, the callout disappears and a different callout pops up for the newly selected annotation. The overall effect is very jarring and strange.

Is there anything I can do to stop this behaviour? Is this a bug or is this expected behaviour?

**Comment by nitaliano** [comment]
Would you mind posting a video? I'm not have much luck getting the touch event to go through the callout onto the map.

**Comment by nitaliano** [comment]
Actually, I am able to reproduce this it's wasn't happening on Android but I just tried iOS and it's happening

**Comment by mlandauer** [comment]
@nitaliano ah sorry yes I should have said this is on iOS. I take it a video isn't necessary anymore as you've reproduced the problem.

**Comment by nitaliano** [comment]
I fixed this locally, will be out in the next release early next week.

**Comment by mlandauer** [comment]
@nitaliano so awesome. thank you!

**Comment by nitaliano** [comment]
Thanks for reporting it! I'll comment back here when I send out the PR

**Comment by nitaliano** [comment]
PR is out https://github.com/mapbox/react-native-mapbox-gl/pull/730
