### ISSUE TITLE
[v6] setCamera documentation is wrong

### ISSUE THREAD

**Issue by josenaves** [nitaliano/react-native-mapbox-gl#727]
The documentation about setCamera is wrong.

We always need to define a config object that contains a **stops** _property array_

``` 
        this.MBMap.setCamera( {
          stops: [ {
             heading: 23.3,
            pitch: 60,
            zoom: 15,
            duration: 500
          } ]
        } );
```

**Comment by nitaliano** [comment]
There is a fork in the code that checks if there are stops https://github.com/mapbox/react-native-mapbox-gl/blob/master/javascript/components/MapView.js#L458 so you can also use an object.
