### ISSUE TITLE
[v6] Ordering of rendering of annotations different than v5 - causes pins to look like they are floating

### ISSUE THREAD

**Issue by mlandauer** [nitaliano/react-native-mapbox-gl#728]
As you can see the order in which the images are rendered is different in v5 and v6. v5 shows correct behaviour, I think, where the images are rendered from the top of the screen down to the bottom of the screen so that lower images are always rendered over the top of images that are higher up.

With v5 of the library:
![image](https://user-images.githubusercontent.com/2221/32624839-90f61bb6-c5de-11e7-95d7-921b6ee5aad0.png)

With v6 of the library:
![image](https://user-images.githubusercontent.com/2221/32624748-4767fbfe-c5de-11e7-90d1-def4dfa7bb5c.png)

In v5 I used `annotationImage`. In v6 I created a custom annotation with an `<Image>` component in it.

```
      <MapboxGL.PointAnnotation
        id={props.campsite._id}
        title={shortenName(props.campsite.name)}
        coordinate={[ props.campsite.position.lng, props.campsite.position.lat ]}
      >
        <Image
          style={{height: 82.5, width: 29.6}}
          source={{
            uri: (props.campsite.starred ? 'starred_map_pin' : 'default_map_pin')}
          }
        />
      </MapboxGL.PointAnnotation>
```

**Comment by nitaliano** [comment]
@mlandauer have you looked into using a `ShapeSource` with a `SymbolLayer`?

**Comment by mlandauer** [comment]
@nitaliano For every pin I have a callout that gets displayed with more information that's clickable as in #726 so I don't think `SymbolLayer` is going to work for me. Is that right?

**Comment by nitaliano** [comment]
Annotations are being phased out in favor of sources and layers. Yes, callouts wouldn't work with it but you could always just slide another view on. I believe the Android SDK has already deprecated MarkerViews.

This issue is fixed in https://github.com/mapbox/react-native-mapbox-gl/pull/732
