### ISSUE TITLE
[v6] Out-of-view annotations can get stuck in the top-left-hand corner of the map

### ISSUE THREAD

**Issue by mlandauer** [nitaliano/react-native-mapbox-gl#729]
See this little movie I made that demonstrates the problem. Look in the top left hand corner of the map and see what happens as the map is zoomed out and back in.

https://youtu.be/OHZfSpskuLU

As you can see there are some annotations which end up stuck in the top left hander corner. As you zoom and all the annotations come into view you end up with nothing stuck in the top left hand corner. The strange thing is when you zoom back in you don't get the annotations that are out of view being stuck in the corner again.

**Comment by nitaliano** [comment]
@mlandauer I haven't been able to reproduce this, would you be able to provide some code?

**Comment by mlandauer** [comment]
@nitaliano Here you go: https://github.com/mlandauer/thats-camping-react-native/blob/mapbox-v6/src/components/CampsiteMap.tsx

**Comment by nitaliano** [comment]
I'm still having trouble reproducing this issue, I'm wondering if this was a side effect of another bug. Would you be able to test this out again with `master`?

**Comment by mlandauer** [comment]
I'll have a go at testing against `master` now.

**Comment by mlandauer** [comment]
@nitaliano unfortunately this problem is still there when I update to the latest `master` (0e17f89c69d7688381705072d3660bbdc48e80d4)

To be safe I restarted the bundler and did a clean build. I definitely picked up the latest changes because I can see that the problems I reported in #728 and #726 are now fixed!

**Comment by nitaliano** [comment]
@mlandauer I'm going to close this out I haven't been able to reproduce this. `master` has tons of annotation improvements and the latest native SDKs, so maybe that will resolve the issue
