### ISSUE TITLE
Enhancement Request: Map Directions

### ISSUE THREAD

**Issue by albertwchang** [nitaliano/react-native-mapbox-gl#73]
Allow ability to have map show directions, and map path from start to destination, along with distance away, and estimated ETA.

**Comment by sslash** [comment]
+1

**Comment by n1te1337** [comment]
+1

**Comment by 1ec5** [comment]
Would it make sense for all that to be in one monolithic component? For what it’s worth, in Cocoa Touch, the full turn-by-turn navigation experience would have to be implemented as at least one UIViewController, rather than a single standalone UIView, which is what this component provides.

**Comment by 1ec5** [comment]
Note that Mapbox’s geocoding and directions APIs are already compatible with `fetch()`, since they return JSON. However, to represent the route, you’d have to manually build a polyline annotation based on the returned geometry data.

**Comment by bsudekum** [comment]
You can add directions via the mapbox directions api https://www.mapbox.com/developers/api/directions/

It will not be directly added to this module. Check out https://github.com/mapbox/mapbox-sdk-js to add it.

**Comment by juanwall** [comment]
+1
