### ISSUE TITLE
[v6] Application crashes when changing map style in a map with shape objects

### ISSUE THREAD

**Issue by hernanmateo** [nitaliano/react-native-mapbox-gl#736]
Mapbox version: 6.0.0
React Native version: 0.49.3

I'm trying to switch between map styles in a Mapbox.MapView with a Mapbox.ShapeSource object with custom styles:

```js
render() {  
    var mapType = OUTDOOR_MAP_STYLE_URL;
    if (this.state.mapType == "satellite") {
      mapType = Mapbox.StyleURL.Satellite;
    } else if (this.state.mapType == "night") {
      mapType = Mapbox.StyleURL.Dark;
    }

    return (
      <View style={{backgroundColor: "white", flex: 1}}>
          <Mapbox.MapView
            ref={(c) => this._map = c}
            id="mainMapView"
            style={styles.map}
            maxZoomLevel={20}
            showUserLocation={true}
            styleURL={mapType}
            onDidFinishLoadingMap={this._onMapLoaded.bind(this)}
            >
              <Mapbox.ShapeSource id='userLocationShape' shape={point}>
                 <Mapbox.CircleLayer id='userLocationInnerCircleCnt' style={innerCircleStyle}/>
              </Mapbox.ShapeSource>
          </Mapbox.MapView>)
}
```
When I try to change the mapType, the application crashes in RCTMGLStyle.m line 1052. In the case that I remove the shape object styles (it does not matter if it is a line or a circle, etc ...) the map changes its style without crashing but the shapes disappears from the view.

**Comment by nitaliano** [comment]
I have this working locally now, the fix will be in next weeks release

**Comment by nitaliano** [comment]
@hernanmateo PR is out let me know how it goes - https://github.com/mapbox/react-native-mapbox-gl/pull/753

**Comment by lucasbento** [comment]
@nitaliano: PR works fine, just approved it! 😄

**Comment by nitaliano** [comment]
Has been merged into master closing out

**Comment by lucasbento** [comment]
@nitaliano: do you know when you will release `6.0.1`?

**Comment by nitaliano** [comment]
@lucasbento I'm going to do a release at the end of every week unless an urgent bugfix is needed, so I'll publish `6.0.1` this Friday.

**Comment by lucasbento** [comment]
@nitaliano: alright, thanks!
