### ISSUE TITLE
userLocationVerticalAlignment missing from V6

### ISSUE THREAD

**Issue by RNMBuser** [nitaliano/react-native-mapbox-gl#743]
Previously, it was possible to state where on the screen the user location will be displayed.

**Comment by nitaliano** [comment]
It's going to be added to our `6.0.1` release this week.

**Comment by nitaliano** [comment]
I'm going to hold off on putting this into `6.0.1` Android is moving towards using the `LocationLayerPlugin` and there is not native support for this field. I will add the native code needed to do this on Android it will take more time.

**Comment by RNMBuser** [comment]
It'll be of great help if you could let it into 6.0.1, even if it's not done and not documented yet, since I need it urgently for an iOS app.

**Comment by hernanmateo** [comment]
Hi @RNMBuser @nitaliano,
I have also added this functionality to my [fork](https://github.com/hernanmateo/react-native-mapbox-gl) (from release/6.0.1), you can choose between three vertical positions (iOS only):

```
Mapbox.UserLocationVerticalAlignment.Top
Mapbox.UserLocationVerticalAlignment.Center
Mapbox.UserLocationVerticalAlignment.Bottom
````
It is documented on the MapView docs.

ex.

```js
<Mapbox.MapView
            ref={(c) => this._map = c}
            id="mainMapView"
            zoomLevel={this.state.initialZoomLevel}
            style={styles.map}
            maxZoomLevel={22}
            showUserLocation={true}
            styleURL={mapType}
            userLocationVerticalAlignment={Mapbox.UserLocationVerticalAlignment.Bottom}
            >
</Mapbox.MapView>
````
I hope that Mapbox adds this functionality soon to the official repository

**Comment by nitaliano** [comment]
Closing this out in favor of https://github.com/mapbox/react-native-mapbox-gl/issues/881
