### ISSUE TITLE
Cannot set heading and centerCoordinate together when animated=true

### ISSUE THREAD

**Issue by RNMBuser** [nitaliano/react-native-mapbox-gl#744]
Changing centerCoordinate moves the map, so it's more then just "Initial center coordinate on map".  That's great!
Changing heading rotates the map, so it's more then just "Initial heading on map". That's great too!

Changing both does work, and just the coordinates are changed.

**Comment by devstepbcn** [comment]
Have you tried with async await funcs?

**Comment by hernanmateo** [comment]
Have you tried with async await funcs?

**Comment by nitaliano** [comment]
You'll want to use `this.map.setCamera` for this, you can set multiple properties at once, and add stops
