### ISSUE TITLE
[v6] zoomEnabled?

### ISSUE THREAD

**Issue by stephenheron** [nitaliano/react-native-mapbox-gl#745]
Hi,

It looks as if in V6 the zoomEnabled prop is no longer available. 

Is it going to return? 

Thanks,
Stephen

**Comment by razor1895** [comment]
Just set `minZoomLevel `  and `maxZoomLevel ` to the same number should solve your problem

**Comment by henrikra** [comment]
@nitaliano I think you forgot to close this?

**Comment by nitaliano** [comment]
Yes! Thanks for reminding me
