### ISSUE TITLE
mbtiles or geopackage support?

### ISSUE THREAD

**Issue by geospatialmapmashup** [nitaliano/react-native-mapbox-gl#746]
Can't find any documentation about loading your own data offline.
Does the React Native MapBox GL support Mbtiles and GeoPackage Raster and Vector Datasets?

**Comment by nitaliano** [comment]
We support whatever is possible to do with the native SDKs, so when you set `MapView.styleURL`, `ShapeSource.url`, `RasterSource.url`, and `VectorSource.url` it's just a direct pass through to the native SDK method calls. I'm not 100% sure if the native SDKs support GeoPackages, if they do and there is a bug in the RN repo we can fix them to add support. This is what we have documented for creating offline packs https://github.com/mapbox/react-native-mapbox-gl/blob/master/docs/OfflineManager.md
