### ISSUE TITLE
[iOS] Could not install the module via CocoaPods

### ISSUE THREAD

**Issue by sroze** [nitaliano/react-native-mapbox-gl#747]
I have an issue while installing the module on an application without MapBox installed at the first place, following the [cocoapods guide](https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/install.md#using-cocoapods).

```
$ pod install
[...]

[!] Unable to find a specification for `Mapbox (= 3.6)` depended upon by `react-native-mapbox-gl`
```

I made the installation working by manually updating the file `node_modules/@mapbox/react-native-mapbox-gl/react-native-mapbox-gl.podspec` and applying the following change:
```patch
-  s.dependency 'Mapbox', '3.6'
+  s.dependency 'Mapbox-iOS-SDK', '3.6'
```

**Comment by nitaliano** [comment]
@sroze we're not going to fully support pods until `6.0.1` and we merged in a PR last week that added that on master and there is this PR https://github.com/mapbox/react-native-mapbox-gl/pull/741 that will finish off the support.

**Comment by sroze** [comment]
Coolio. Thanks @nitaliano, I'll follow the PR then.

**Comment by glarivie** [comment]
@sroze thanks

**Comment by williamdarkocode** [comment]
can anyone post a pic of the code in their PodFile? What does it look like?
