### ISSUE TITLE
v6 Custom images as annotations?

### ISSUE THREAD

**Issue by olofd** [nitaliano/react-native-mapbox-gl#748]
Hi!
Thanks for updating this library. I hope we will get a stadier stream of updates going forward now.
And that MapBox will start to officially support this package. That would be great! 🎉 .

In < v6 you could have custom images over annotations, is this supported in v6?
If not, I would like to to a feature request!

Thanks

**Comment by devstepbcn** [comment]
You can put an object image inside a PointAnnotation, like this:

```js
        <Mapbox.PointAnnotation
              key={id}
              id={id}
              title={name}
              anchor={{ x: 0.5, y: 1 }}
              coordinate={[location.longitude, location.latitude]}>
              <Image source={{uri: icon}}  style={{width: width, height: height}}/>
        </Mapbox.PointAnnotation>
```

**Comment by nitaliano** [comment]
Yup what @devstepbcn mentioned is the correct way of handling it.

**Comment by olofd** [comment]
Thanks. Works!
