### ISSUE TITLE
[v6] PointAnnotation not updating on new coordinate

### ISSUE THREAD

**Issue by lucasbento** [nitaliano/react-native-mapbox-gl#750]
I'm re-rendering the component every time that I retrieve a new location, everything works well except the `<PointAnnotation />` not updating its position.

This was working on version `< 6`.

**Comment by lucasbento** [comment]
I'm using this as follows:

```jsx
<Mapbox.PointAnnotation
  id="my-id"
  coordinate={[-122.156047,37.38816025]}
/>
```

No mystery there, added some logs and everything is updating fine until `PointAnnotation` calls the native component.

cc @nitaliano, any idea of what's happening?

**Comment by nitaliano** [comment]
I'm stupidly not updating the coordinate correctly, it will be fixed in our next release `6.0.1` this week.

**Comment by nitaliano** [comment]
@lucasbento PR is out https://github.com/mapbox/react-native-mapbox-gl/pull/754

**Comment by lucasbento** [comment]
@nitaliano: great, thanks for replying so fast.

**Comment by lucasbento** [comment]
@nitaliano: is there a way to make the point transition nicely between a coordinate and the other? Like https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/DriveTheLine.js does, making the point move in the map instead of these flickery changes:

![map](https://user-images.githubusercontent.com/6207220/32770647-ab248ec4-c920-11e7-9dac-8684052e581d.gif)

**Comment by nitaliano** [comment]
You need to interpolate between the the current coordinate and the coordinate you are going to update to. The Animated API makes this much easier, we would need to make it an Animated component as well like so https://github.com/mapbox/react-native-mapbox-gl/blob/master/javascript/index.js#L86

I do have future plans to make an `Annotation` component that would move all this logic to the SDK and you would just need to define a config
