### ISSUE TITLE
Add Expo example

### ISSUE THREAD

**Issue by lucasbento** [nitaliano/react-native-mapbox-gl#751]
[Expo](expo.io) apps are easier to run (since it can be done through a simple URL and the Expo app) than git cloning the repository and running the current example.

**Comment by josenaves** [comment]
I can be wrong but I don't think it is possible right now. This is because Mapbox has native code. 
This can only happens if Expo team adds Mapbox support into their framework.

**Comment by lucasbento** [comment]
@josenaves: I believe you are right.

Perhaps @brentvatne can give us a light on this.

**Comment by brentvatne** [comment]
this doesn't work with expo unfortunately. it would be nice to have support one day -- can you create a feature request on https://expo.canny.io/feature-requests @lucasbento? the only way to use it now is to "detach" your project

**Comment by nitaliano** [comment]
@brentvatne Hi, I'm the one maintaining this repo, would love to get this into Expo and I can provide as much support as needed.

@lucasbento @josenaves  Here is the ticket https://expo.canny.io/feature-requests/p/add-mapbox-gl-support

**Comment by ide** [comment]
Apologies if this derails the conversation, Expo has a GL implementation in JS (similar to WebGL) -- if Mapbox has a WebGL implementation that doesn't depend on DOM things, it might run on Expo.

**Comment by lucasbento** [comment]
> Here is the ticket expo.canny.io/feature-requests/p/add-mapbox-gl-support.

Awesome!

**Comment by josenaves** [comment]
Trending now :+1: 

https://expo.canny.io/feature-requests

**Comment by nitaliano** [comment]
I'm going to close this out, I'll PR an update to the readme with the expo feature request link

**Comment by ToJen** [comment]
It's possible to eject a `create-react-native-app` and still have access to Expo. Use `npm run eject` in the root of the app. It prompts a few options, go with the one that says use ExpoKit.

**Comment by xmuskrat** [comment]
This appears to have fallen off the expo roadmap today.   Is anybody else working on support for this in expo?   See https://expo.canny.io/feature-requests/p/add-mapbox-gl-support

I saw a sandbox for this earlier.  https://snack.expo.io/@bacon/mapbox-gl  and I was wondering if is there an easy way to port mapbox gl to expo via expo-three plugin?   If there was an organized effort somewhere, I would be open to contribute.
