### ISSUE TITLE
v6 Custom callout is not rendered on android

### ISSUE THREAD

**Issue by olofd** [nitaliano/react-native-mapbox-gl#752]
This renders fine on iOS, but renders nothing on android:

```js
    return (
      <MapboxGL.Callout title={annotation.title}>
        <View style={styles.calloutContainer}>
          <Text>TestingTesting</Text>
        </View>
      </MapboxGL.Callout>
    );
```

**Comment by nitaliano** [comment]
What styles are you putting on it? Checkout the styles I use for the default callout https://github.com/mapbox/react-native-mapbox-gl/blob/master/javascript/components/Callout.js#L9
