### ISSUE TITLE
ShapeSource + LineLayer doesn't seem to work with `properties` on shape

### ISSUE THREAD

**Issue by lucasbento** [nitaliano/react-native-mapbox-gl#757]
The following code works:

```jsx
const shape = {
  type: 'Feature',
  properties: {},
  geometry: {
    type: 'LineString',
    coordinates: [myLongitude, myLatitude],
  },
}

// ...

<Mapbox.ShapeSource
  id="myRoute"
  shape={shape}
>
  <Mapbox.LineLayer
    id="routeFill"
    style={layerStyles.route}
  />
</Mapbox.ShapeSource>
```

But if you remove the `properties` entry on `shape` the polyline doesn't show up and no error is thrown.

I'm following the same structure stated in https://github.com/mapbox/react-native-mapbox-gl/issues/678#issuecomment-338052779.

**Comment by nitaliano** [comment]
The GeoJSON spec requires properties on Feature objects, so it's most likely failing validation. You could also try passing in the Geometry object if you don't want it to be a feature

Here is a link to the spec - https://tools.ietf.org/html/rfc7946
