### ISSUE TITLE
Warning from peer dependency

### ISSUE THREAD

**Issue by henrikra** [nitaliano/react-native-mapbox-gl#759]
I am getting `warning "@mapbox/react-native-mapbox-gl@6.0.0" has incorrect peer dependency "react@16.0.0-alpha.12".` with Mapbox 6.0.0 and RN 0.49.0 and React 16.0.0-beta.5

**Comment by nitaliano** [comment]
I added the fix for the warning on https://github.com/mapbox/react-native-mapbox-gl/pull/761 going to close this out it will be in `6.0.1`

**Comment by henrikra** [comment]
Why the peer dependency is there in the first place?
