### ISSUE TITLE
A problem with the installation?

### ISSUE THREAD

**Issue by mtimofiiv** [nitaliano/react-native-mapbox-gl#76]
I followed the instructions here: https://github.com/mapbox/react-native-mapbox-gl/blob/master/install.md

However, I still get this in my debugger:

`Warning: Native component for "RCTMapboxGL" does not exist`

The only irregularity during the steps was that for step 4, the file `libRCTMapboxGL.a` doesn't actually exist - possibly renamed to `libMapboxGL.a` (as this is the only `*.a` file in that directory)?

**Comment by bsudekum** [comment]
Interesting. Ususally this happens if you don't follow the install steps properly. Can you take a screenshot  of your table of contents and your build phase? IE:

![](https://cldup.com/96uoN2Yj95.png)

Also, what version of react-native/react-native-mapbox-gl are you using?

**Comment by mtimofiiv** [comment]
I am using the latest version of this module, `0.4.1`, node version `iojs-2.0.0` and react-native version `0.10.0`.

I have retraced my steps and re-added all the components as was shown in the documentation. Here's the build phase:

![screen shot 2015-09-04 at 1 28 53 pm](https://cloud.githubusercontent.com/assets/428948/9682671/35bce594-5309-11e5-87db-5260d76f266d.png)

However, now my build is failing and spits out the following errors:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_MGLAccountManager", referenced from:
      objc-class-ref in libRCTMapboxGL.a(RCTMapboxGL.o)
  "_OBJC_CLASS_$_MGLAnnotationImage", referenced from:
      objc-class-ref in libRCTMapboxGL.a(RCTMapboxGL.o)
  "_OBJC_CLASS_$_MGLMapView", referenced from:
      objc-class-ref in libRCTMapboxGL.a(RCTMapboxGL.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by bsudekum** [comment]
@1ec5 have you seen this issue before?

**Comment by 1ec5** [comment]
After step 1, I wound up with a node_modules/react-native-mapbox-gl/ directory that contains not only RCTMapboxGL/ but also RCTMapbox/. Both folders are a mixture of Mapbox GL for iOS 0.5.1 and Mapbox iOS SDK 2.0.0 (see #87). How did this happen?

**Comment by bsudekum** [comment]
Can you upgrade to 0.4.2 and see if the error still persists?

**Comment by sslash** [comment]
not sure if this is related, but installation failed for me too (ios, and node 2.1.0). However if I changed the last step in the installation process (header_search_path) to:

![skjermbilde 2015-10-31 kl 13 20 35](https://cloud.githubusercontent.com/assets/1174520/10863602/aed74212-7fd2-11e5-9743-f05d5858da88.png)

it worked
