### ISSUE TITLE
[Question]Store data when user interacts with map

### ISSUE THREAD

**Issue by StevanCakic** [nitaliano/react-native-mapbox-gl#762]
I am building a mobile app that collects data from a map and store it and shows that stored data from some data source .json.  I'm trying to find a way to store data when you, for example, click on the map or you draw a polygon, etc. Should I create API, for example with NodeJS for that or is there any simpler solution for that?

This is an example what I want: https://openlayers.org/en/latest/examples/vector-esri-edit.html

Can you suggest any way for this?

Thanks

**Comment by nitaliano** [comment]
You have a few options
* Mapbox has a dataset API https://www.mapbox.com/api-documentation/#datasets
* You can use Firebase and store all the geometry objects as features -https://tools.ietf.org/html/rfc7946. Firebase could be cool if you want a realtime map
* You can always roll your and store this in a DB and put an API in front of it.
