### ISSUE TITLE
MapView centerCoordinate prop documentation

### ISSUE THREAD

**Issue by hannta** [nitaliano/react-native-mapbox-gl#763]
MapView `centerCoordinate` prop documentation says: "Initial center coordinate on map [lng, lat]"

But isn't that more than just **initial** center coordinate? If I update `centerCoordinate` after map is loaded, map center is also changed.

**Comment by nitaliano** [comment]
Yes, I can update the docs for this as it does work. In the future I do think it would be best to use the  `setCamera` method as future releases of the native SDK's are going to allow us to animate multiple camera properties at the same time, so you'll be able to make the camera do some cool things that you wouldn't get by just setting the property

**Comment by henrikra** [comment]
@nitaliano So `centerCoordinate ` should be deprecated?
