### ISSUE TITLE
undefined is not an object (evaluating 'MapboxGL.UserTrackingModes')

### ISSUE THREAD

**Issue by fzf** [nitaliano/react-native-mapbox-gl#765]
Steps to reproduce:

`create-react-native-app AwesomeProject`
`npm run eject` chose either regular react-native or expokit
~~`npm install @mapbox/react-native-mapbox-gl --save`~~ this fails on Mapbox dependency needs the switch to Mapbox-iOS-SDK
`git clone https://github.com/mapbox/react-native-mapbox-gl.git` into `node_modules/@mapbox`
add `pod 'react-native-mapbox-gl', :path => '../node_modules/@mapbox/react-native-mapbox-gl'` to Podfile
add `<MapboxGL.MapView/>` to `render` in `App.js`

Run app.

I really hope there is something that I am missing here, seems like that should work.

**Comment by nitaliano** [comment]
@fzf cocoa pods won't work until we merge in https://github.com/mapbox/react-native-mapbox-gl/pull/741
