### ISSUE TITLE
[HELP] Error building on Android

### ISSUE THREAD

**Issue by Jose4gg** [nitaliano/react-native-mapbox-gl#767]
If I add the new Mapbox package to my app/build.gradle I receive this error:

Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/arch/core/internal/SafeIterableMap$Entry.class

Any help?

**Comment by nitaliano** [comment]
Can you post your android/build.gradle and app/build.gradle? I would also try to clean the project and rebuild

**Comment by Jose4gg** [comment]
I saw the problem basically I have to exclude `android.arch.core` module from the mapbox project.

**Comment by ghost** [comment]
Hello, I'm having a similar issue and was wondering if you could help, please, https://github.com/mapbox/react-native-mapbox-gl/issues/785

Thanks very much!

**Comment by luskin** [comment]
I am also having the same issue, @Jose4gg would you please post your solution to this?
