### ISSUE TITLE
`queryRenderedFeaturesAtPoint` doesn't seem to work for `LineLayer`

### ISSUE THREAD

**Issue by lucasbento** [nitaliano/react-native-mapbox-gl#769]
I'm trying the following code:
```js
  handleOnMapPress = async ({ geometry }) => {
    console.log(await this.map.queryRenderedFeaturesAtPoint(geometry.coordinates))
  }

// ... render()

<Map onPress={this.handleOnMapPress} />
```

Which doesn't return the `LineLayer` even though I am clicking on it. It only returns the stuff around the `LineLayer`:

![image](https://user-images.githubusercontent.com/6207220/32841297-392989dc-ca1a-11e7-9ad8-9aa8d93c13ff.png)

cc @nitaliano.

**Comment by nitaliano** [comment]
Follow this example https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/QueryAtPoint.js#L42 the native SDK is expecting it to be pixel coordinates not a latlng

**Comment by lucasbento** [comment]
@nitaliano: thanks for answering, how do I specify that I need it to return only on `LineLayer`?

Specifying `['LineString']`/`['LineLayer']`/`['MultiLineString']`, all together and `['==', 'type', 'LineString']`, none of them seem to work, it keeps returning all the map rendered features.

**Comment by lucasbento** [comment]
@nitaliano: can you give some light on this?

**Comment by nitaliano** [comment]
@lucasbento here are some [docs](https://www.mapbox.com/mapbox-gl-js/style-spec/#other-filter)(scroll to bottom anchor link is broken) from the style spec that might help shed more light on filtering.

When you are preforming a filter it is only checking the properties of the feature, so using the feature below I would only be able to filter on it's `name` property. 
```
{
   "type": "Feature",
   "geometry": { ... },
   "properties": {
      "name": "example"
   }
}
```

To get around this we have to special properties `$id` which if you pass an id down with your feature you could filter based on id, and if you wanted to filter on similar GeoJSON types you would use `$type`, so for what you're trying to do you could use this filter
```
['==', '$type', 'LineString']
```
it will return all LineString and MultiLineString at the given point.

If you wanted to narrow down your query even further(also helps with performance) I would add layerID's that I want to query.
```
this.map.queryRenderedFeaturesAtPoint([screenX, screenY], null, ['layerID1', 'layerID2'])
```
and that will return only hits in those layers.

I've also submitted a PR https://github.com/mapbox/react-native-mapbox-gl/pull/793 that adds support for an `onPress` on `VectorSource` and `ShapeSource` components. This will always do the query on the native side for you also eliminating 1 RN bridge pass to further improve performance.

**Comment by HikingDev** [comment]
Hi,

i've set a filter to LineLayer id and query RenderedFeaturesAtPoint.
The returned Features differ slightly from the actual GeoJson Source.
Furthermore i'd like to understand how exactly the returned items are chosen or how many.

Below are the actual GeoJson coordinates.
The Screenshot shows the logged returned coordinates. 
I dont exactly see a correlation between returned values and actual Source.
The last image highlights the returned coordinates after a click on the start of the Line.
`  
{
                "type": "LineString",
                "coordinates": [
                    [
                        -116.4669810,
                        32.5897410,
                        889.15
                    ],
                    [
                        -116.4670280,
                        32.5899350,
                        886.93
                    ],
                    [
                        -116.4671850,
                        32.5900520,
                        883.79
                    ],
                    [
                        -116.467830,
                        32.5902960,
                        876.62
                    ],
                    [
                        -116.4678750,
                        32.5906040,
                        874
                    ],
                    [
                        -116.4676770,
                        32.5910890,
                        870.3
                    ]
]}
`
![image](https://user-images.githubusercontent.com/5518190/33761666-244ee5f0-dc0a-11e7-8b1b-1fb6c2308d66.png)

![image](https://user-images.githubusercontent.com/5518190/33761700-40f16cd2-dc0a-11e7-952d-6e38abce76bb.png)

**Comment by nitaliano** [comment]
@roesneb `queryRenderedFeaturesAtPoint` returns a FeatureCollection of Features based on zIndex order, so if you click on a line without any filtering it will returns all Features at that point in zIndex order.

The native SDK is returning it as a `MultiLineString` due to how it's being rendered most likely. If you add properties to your feature they would also be returned up to you. Further more we've added an `onPress` handler to both `VectorSource` and `ShapeSource` components
