### ISSUE TITLE
Updating user-location in background

### ISSUE THREAD

**Issue by christocracy** [nitaliano/react-native-mapbox-gl#77]
I've created a sophisticated [background-geolocation](https://github.com/christocracy/react-native-background-geolocation) plugin (ported from my popular [Cordova plugin](http://transistorsoft.github.io/cordova-background-geolocation/) which intelligently monitors the user's movement-state and only engages `locationManager` when device is determined to be moving (and stops `locationManager` when the device has stopped).

Because my plugin sets `NSLocationAlwaysUsageDescription`, `react-native-mapbox-gl` will keep `locationManager` updating the location **even when the device goes to the background**, which kills the battery in a short time, of course.  This is what my plugin resolves.

In spite of what [this link](https://www.mapbox.com/guides/first-steps-gl-ios/#background-location) says.

> How does background location data affect device battery usage? We determined that background 
> location data is not a significant hit to the battery through extensive testing. You can read about how we 
> tested the battery on the blog.

After over 2 years experience creating Android/iOS background geolocation code, keeping `locationManager` always running in background **WILL** certainly kill the battery in a very short time.

This is what my plugin resolves.

A simple (very raw) solution in `RCTMapboxGL.m` goes like this:

```
- (void)createMap
{
    [MGLAccountManager setAccessToken:_accessToken];
    _map = [[MGLMapView alloc] initWithFrame:self.bounds styleURL:_styleURL];
    _map.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
    _map.delegate = self;
    _map.userTrackingMode = MGLUserTrackingModeFollow;
    [self updateMap];
    [self addSubview:_map];
    [self layoutSubviews];

    // Solution:  Listen to pause/resume events so we can start/stop locationManager
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(onSuspend:) name:UIApplicationDidEnterBackgroundNotification object:nil];
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(onResume:) name:UIApplicationWillEnterForegroundNotification object:nil];
}

- (void) onSuspend:(NSNotification*)notification
{
    // Stop updating location.  
   _map.showsUserLocation = NO;
}
- (void) onResume:(NSNotification*)notification
{
     // Restore updating locations
    _map.showsUserLocation = YES;
}

Thoughts?
```

**Comment by bsudekum** [comment]
I think this looks good. @christocracy want to make this into a PR?

**Comment by christocracy** [comment]
I'll clean it up, add required logic and do a PR.

On Monday, August 10, 2015, Bobby Sudekum notifications@github.com wrote:

> I think this looks good. @christocracy https://github.com/christocracy
> want to make this into a PR?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mapbox/react-native-mapbox-gl/issues/77#issuecomment-129657042
> .

## 

Snet form Gmail Mobile

**Comment by friedbunny** [comment]
@christocracy The place to submit this fix would be upstream in [mapbox/mapbox-gl-native](https://github.com/mapbox/mapbox-gl-native), sticking it someplace in [platform/ios/MGLMapView.mm](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/MGLMapView.mm).

**Comment by christocracy** [comment]
Ok, I'll swim upstream then.

**Comment by byroncoetsee** [comment]
I realise this might be old but incase anyone might have missed this, I feel I should put it out there... This does work but only if the user agrees to Location Permission request before... When testing this method (Using Swift 1.2, iOS 8, XCode 6, iPhone 6), I get the Permission Request window opening up continuously every second. open close open close etc.

Anyone else had this issue?

**Comment by bsudekum** [comment]
@byroncoetsee confirmed, I can take a look at this bug this weekend.
