### ISSUE TITLE
[v6] Any plans for cluster properties on VectorSource?

### ISSUE THREAD

**Issue by jliebrand** [nitaliano/react-native-mapbox-gl#770]
I noticed the ShapeSource allows for point clustering. Any chance to get that enabled on the VectorSource also? (eg I have a dataset hosted on mapbox as an mbtileset, and I would like the points to cluster)

**Comment by nitaliano** [comment]
VectorSource does not support clustering currently only the ShapeSource allows clustering in the native SDKs. ShapeSource does accept a URL as well so if you do have a geosjon dataset on a server you can use it
