### ISSUE TITLE
[Question] Zoom Control

### ISSUE THREAD

**Issue by StevanCakic** [nitaliano/react-native-mapbox-gl#771]
Hi, 

there is no built-in zoom control buttons, for example, ZoomControl component? Do I need to create these buttons from scratch?

Thanks

**Comment by nitaliano** [comment]
Yup, you can pitch and double tap to zoom in and out by default. If you need to move or zoom to a certain location you need to add a custom button on top of the map and call the camera methods on the MapView. If you want a prebuilt button I would recommend https://react-native-training.github.io/react-native-elements/API/buttons/ or https://github.com/oblador/react-native-vector-icons#iconbutton-component

**Comment by ToJen** [comment]
Try this:
```javascript
<ZoomButton
  style={styles.zoomButton}
  color={'blue'}
  onPress={() => {
    this.map.getZoom().then((zoom) => {
      console.log(zoom)
      this.map.zoomTo(zoom+1)
    })
  }}
/>
/**********************************/
import React from 'react'
import { TouchableOpacity } from 'react-native'
import { Icon } from 'react-native-elements'

const ZoomButton = (props) => {
  const { onPress, color, style, name } = props

  return (
    <TouchableOpacity
      activeOpacity={0.7}
      style={style}
      onPress={onPress}
      >
      <Icon
        name={name}
        type='material-icons'
        size={40}
        color={color}
        raised
        containerStyle={{width: 50, height: 50, borderRadius: 31}}
        />
    </TouchableOpacity>
  )
}

export default ZoomButton

```

**Comment by DennisMuchiri** [comment]
Hi @ToJen  that was very helpful although am getting an error when i set button name that the prop for name format is not valid
