### ISSUE TITLE
[v6]  Error while updating property 'shape' of a view managed by RCTMGLShapeSource - Failed to allocate

### ISSUE THREAD

**Issue by butchmarshall** [nitaliano/react-native-mapbox-gl#774]
This is on v6 master branch - randomly happens.

![image](https://user-images.githubusercontent.com/339763/32928294-3b432aec-cb1f-11e7-87bb-6e44b9a68573.png)

**Comment by nitaliano** [comment]
How large is the dataset that you're passing over the bridge? I've never tried this yet, but when the dataset becomes too large we can't pass it over the bridge so you can store the data in a json file and use RN fetch blob to pass a URL to the file over the bridge and let the native code handle it from their. ShapeSource has a url property on it.

**Comment by butchmarshall** [comment]
The data set is very large.

I'll try the blob+url - thanks!

**Comment by nitaliano** [comment]
Yea, let me know how it goes. If it doesn't work I'll make sure we add support to work with RN fetch blob

**Comment by butchmarshall** [comment]
Disregard my previous message -  It works perfectly!

file:///data/user/0/com.snow_trails/files/polylines_1.json

I shouldn't submit bug reports at midnight.

**Comment by nitaliano** [comment]
@butchmarshall great! glad it's working I'm going to close this out
