### ISSUE TITLE
Android crash: java.lang.NoClassDefFoundError timber.log.Timber 

### ISSUE THREAD

**Issue by henrikra** [nitaliano/react-native-mapbox-gl#775]
Some of our users are having this kind of crash and it points to Mapbox SDK. Do you have any idea why this would happen @nitaliano ?

Crash happened with: Samsung SM-T315 (Android 4.4.2)

```
java.lang.NoClassDefFoundError timber.log.Timber 
    HTTPRequest.java:113 com.mapbox.mapboxsdk.http.HTTPRequest.onResponse
    RealCall.java:141 okhttp3.RealCall$AsyncCall.execute
    NamedRunnable.java:32 okhttp3.internal.NamedRunnable.run
    ThreadPoolExecutor.java:1112 java.util.concurrent.ThreadPoolExecutor.runWorker
    ThreadPoolExecutor.java:587 java.util.concurrent.ThreadPoolExecutor$Worker.run
    Thread.java:841 java.lang.Thread.run
```

**Comment by nitaliano** [comment]
@tobrun have you ever seen the above error before?

**Comment by henrikra** [comment]
I don't think I have seen it before. Now we got this error on Samsung GT-S7580 (Android 4.2.2) too

**Comment by tobrun** [comment]
A `NoClassDefFoundError` means that the [Timber](https://github.com/JakeWharton/timber) dependency wasn't available at runtime (while it was available at compile time). This is rather strange as we haven't run into this issue upstream in [mapbox-gl-native](https://github.com/mapbox/mapbox-gl-native/).

Capturing from multiple SO posts, as [this one](https://stackoverflow.com/questions/32576482/java-lang-noclassdeffounderror-on-android-4-4-or-lower), that this occurs on older devices when not configuring [multi-dex](https://developer.android.com/reference/android/support/multidex/MultiDex.html) correctly. Can someone validate if this is enabled? and if so, is correctly integrated?

**Comment by henrikra** [comment]
Here are OS versions our users are getting the crash:
![image](https://user-images.githubusercontent.com/12229968/33244052-3c276090-d2f9-11e7-987f-41dcc0061ea8.png)

So this has something to do with their old Android version?

**Comment by nitaliano** [comment]
@henrikra how are you enabling multidex in your app?

**Comment by henrikra** [comment]
You mean this `multiDexEnabled true` in `app/build.gradle`? Yes

**Comment by tobrun** [comment]
And do you have 'MultiDex.install(this);' in your application object?

**Comment by henrikra** [comment]
@tobrun Haven't ever heard of this :O

**Comment by nitaliano** [comment]
@henrikra you also might want to add the support library as well https://developer.android.com/studio/build/multidex.html

**Comment by nitaliano** [comment]
@henrikra are you still having this issue?

**Comment by henrikra** [comment]
@nitaliano Yeah. Last time was yesterday

**Comment by nitaliano** [comment]
Did you add this to your application

```java
@Override
protected void attachBaseContext(Context base) {
  super.attachBaseContext(base);
  MultiDex.install(this);
}
```

and this to your mainfest
```xml
<application name=".MyApplication"
```

and give the support library for multidex a try?

**Comment by henrikra** [comment]
Problem found! According to the docs https://developer.android.com/studio/build/multidex.html you have to add `compile 'com.android.support:multidex:1.0.1'` to the dependencies and add
```java
@Override
protected void attachBaseContext(Context base) {
   super.attachBaseContext(base);
   MultiDex.install(this);
}
```
to your `MainApplication.java`

But ONLY IF your minSdkVersion is set to 20 or lower and you want multidex enabled. Our is 16 :P Thanks for the debugging help guys!

**Comment by raquezha** [comment]
> Problem found! According to the docs https://developer.android.com/studio/build/multidex.html you have to add `compile 'com.android.support:multidex:1.0.1'` to the dependencies and add
> 
> ```java
> @Override
> protected void attachBaseContext(Context base) {
>    super.attachBaseContext(base);
>    MultiDex.install(this);
> }
> ```
> 
> to your `MainApplication.java`
> 
> But ONLY IF your minSdkVersion is set to 20 or lower and you want multidex enabled. Our is 16 :P Thanks for the debugging help guys!

yeah this solves my problem
