### ISSUE TITLE
Question: Lower Android API levels support (v6) ?

### ISSUE THREAD

**Issue by vieraleonel** [nitaliano/react-native-mapbox-gl#776]
Hi,

Are you planning on lowering the Android API Support? Currently API 25 (7.1) and up, only owns 3.3% of the total android users. [Android Report - Dashboard](https://developer.android.com/about/dashboards/index.html)

Or maybe I'm getting version support wrong?

Thanks

**Comment by hannta** [comment]
> Or maybe I'm getting version support wrong?

`minSdkVersion` is 16, which excludes only ~3,2% of the devices.

**Comment by nitaliano** [comment]
Yup, minSdkVersion is 16

**Comment by vieraleonel** [comment]
Excelente thanks
