### ISSUE TITLE
[QUESTION] Is It possible get this component (Arrow user location) for user location?

### ISSUE THREAD

**Issue by Jose4gg** [nitaliano/react-native-mapbox-gl#778]
![image](https://user-images.githubusercontent.com/17036072/32950120-96c26246-cb7b-11e7-9ced-168582cf455f.png)

I want the icon of the arrow with the heading instead of the normal point, Is there a way to do this?

**Comment by nitaliano** [comment]
Set your `userTrackingMode={MapboxGL.UserTrackingModes.FollowWithHeading}` and that should update to that icon

**Comment by Jose4gg** [comment]
Thanks man, @nitaliano I tested that and didn't work for me, but now I know the reason, if I pass a number 3 to the property it shows me the heading but if I use the constant it does not, the reason is the constant is returning a number 2 not a number 3, I don't know which is wrong the constant or the MapView component but definitely there is a bug there.

**Comment by Jose4gg** [comment]
One more thing, If I move the map to that mode the annotation gets reset and I lose the annotation, Is there a way to lock the mode even if the user moves the screen?

**Comment by nitaliano** [comment]
ah right it's `FollowWithCourse`....`FollowWithHeading` is the blue dot with the arrow not the nav icon

**Comment by nitaliano** [comment]
@Jose4gg the user tracking is going to be fixed with this PR https://github.com/mapbox/react-native-mapbox-gl/issues/814, it won't remove the navigation icon anymore.
