### ISSUE TITLE
[QUESTION] Callout without PointAnnotation

### ISSUE THREAD

**Issue by kaynz** [nitaliano/react-native-mapbox-gl#779]
Hey guys,

thanks for this great library. I just switched over from react-native-maps.

I would like to have Callouts (e.g. labels) on my map without PointAnnotations. Is this possible?

I already tried to make the PointAnnotation invisible with opacity and visibility stuff but it didn't work. 
Thanks!

**Comment by nitaliano** [comment]
Depending on what you need it to look like you can achieve something like this with a SymbolLayer. Would you be able to post a screen of what it would look like?

**Comment by kaynz** [comment]
@nitaliano 
![adb_2017-11-17_18-07-50](https://user-images.githubusercontent.com/12952835/32959636-86ff40a8-cbc2-11e7-8833-d62b5c0cdb51.png)

**Comment by kaynz** [comment]
I checked out your examples but couldn't figure out how to achieve this. It doesn't seem to be possible to set a text per feature in SymbolLayer, right?

**Comment by nitaliano** [comment]
You can your styles have access to your feature properties

Let's say you have this feature collection, you can see each feature has a property `name`
```javascript
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "name": "Test 1"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -118.828125,
          37.16031654673677
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Test 2"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -124.8046875,
          33.43144133557529
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Test 3"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -128.32031249999997,
          51.83577752045248
        ]
      }
    }
  ]
}
```

and for the style you can access that property by using a token string
```javascript
const styles = MapboxGL.StyleSheet.create({
   textSymbol: {
      textField: '{name}'
   }
})
```

**Comment by kaynz** [comment]
Thanks. Is it possible to register onPress events for the symbols in the spacesource?

**Comment by nitaliano** [comment]
Follow this example - https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/QueryAtPoint.js#L44

You can query the features rendered on the map with a point or bbox. I'll be releasing a PR this week that adds support for an onPress on a ShapeSource, so I'll query under the hood for the user

**Comment by stdavis** [comment]
This got me as far as adding text labels to the map:
![image](https://user-images.githubusercontent.com/1326248/37933632-04efae8e-3109-11e8-8358-ff9b17f81da7.png)

But what about adding the callout box underneath the text? Can I add anything more than text to the box like a button or an entire component? I'm looking to build something like this:
![image](https://user-images.githubusercontent.com/1326248/37933682-2aa6f48e-3109-11e8-9e20-c2a34e18f50f.png)

**Comment by stdavis** [comment]
@nitaliano Any ideas?

**Comment by edenkras** [comment]
@stdavis Did you managed to add anything more than text?

**Comment by stdavis** [comment]
No. We decided to just navigate to a different view when the point is pressed rather than showing a popup.
