### ISSUE TITLE
[QUESTION] Capture all touch events

### ISSUE THREAD

**Issue by kaynz** [nitaliano/react-native-mapbox-gl#782]
Hi, another question:

Your MapView captures onPress and onLongPress. Is it possible to capture onPressIn events, too?

This does not work:
`<TouchableWithoutFeedback onPressIn={foo}>
<MapboxGL.MapView/>
</TouchableWithoutFeedback>`

Docs: https://facebook.github.io/react-native/docs/touchablewithoutfeedback.html

**Comment by nitaliano** [comment]
Those are not supported on in the native SDK, it's possible to add support for we would have to add the native event listeners ourself.

As for the `TouchableWithoutFeedback` I would try

```javascript
<TouchableWithoutFeedback onPressIn={...}>
   <View style={{ flex: 1 }}>
      <MapboxGL.MapView style={{ flex: 1 }} ... />
   </View>
</TouchableWithoutFeedBack>
```

**Comment by kaynz** [comment]
Thanks. Unfortunately  your suggestion does not work. Are you going to add the native event listeners? If you're looking for a use-case: I want to switch to `UserTrackingModes.None` whenever the map is dragged.
