### ISSUE TITLE
[v6 master] Crash nativeGetLayer  in NativeMapView.java - MapboxGL.SymbolLayer / MapboxGL.CircleLayer

### ISSUE THREAD

**Issue by butchmarshall** [nitaliano/react-native-mapbox-gl#784]
Good:

```
render() {
	const geoJson = { type: 'FeatureCollection', features: [] };

	return (
		<MapboxGL.ShapeSource shape={geoJson}>
			<MapboxGL.LineLayer />
		</MapboxGL.ShapeSource>
	);
}
```

Crash:
```
render() {
	const geoJson = { type: 'FeatureCollection', features: [] };

	return (
		<MapboxGL.ShapeSource shape={geoJson}>
			<MapboxGL.SymbolLayer  />
			<MapboxGL.LineLayer />
		</MapboxGL.ShapeSource>
	);
}
```

```
render() {
	const geoJson = { type: 'FeatureCollection', features: [] };

	return (
		<MapboxGL.ShapeSource shape={geoJson}>
			<MapboxGL.SymbolLayer  />
		</MapboxGL.ShapeSource>
	);
}
```
```
render() {
	const geoJson = { type: 'FeatureCollection', features: [] };

	return (
		<MapboxGL.ShapeSource shape={geoJson}>
			<MapboxGL.CircleLayer  />
		</MapboxGL.ShapeSource>
	);
}
```

![image](https://user-images.githubusercontent.com/339763/32976799-0e5043d4-cbed-11e7-81a2-f877224f148e.png)

**Comment by butchmarshall** [comment]
If I add an `id={"something"}` to the `MapboxGL.SymbolLayer` it no longer crashes.

**Comment by kaynz** [comment]
Yea, same here. And even more: My SymbolLayer doesn't show anything. Same for you?

**Comment by nitaliano** [comment]
Source ID's are required unless you are working with the `composite` source which is a source provided for you from mapbox when using our style urls.  Layer ID's are required and they can point to a layer on the map you want to manipulate or it can be a brand new layer you want to add to the map.

@kaynz if you post some code of what type of data you're putting into your source, and the props you're putting on your source and layer I'll be able to help.

This is a good example to follow https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/CustomIcon.js
