### ISSUE TITLE
MapboxGL.ShapeSource doesn't allow overlap

### ISSUE THREAD

**Issue by lucasgray** [nitaliano/react-native-mapbox-gl#786]
So I'm upgrading from 5.0.0 to 6.0.0 and playing around with the new methods and features. I'm building an augmented reality game where resources appear on the map, which can be gathered by going to that location.

I use custom images and was able to pull them successfully using the new `MapboxGL.ShapeSource` element.  I've noticed using this strategy that the annotations now behave much differently.  I understand the whole concept of having Points disappear when they overlap, and the clustering.  I've been able to include the clustering and I'm a fan.  

However, I think ideally for my use case when super zoomed out I would get clusters, then at a certain zoom threshold, I would rather see all images (overlapping if necessary).  Have you guys thought about this at all?  Is there a property I'm missing?  

Thanks!

**Comment by lucasgray** [comment]
Scratch that, I found `iconAllowOverlap: true`

**Comment by jsina** [comment]
@lucasgray I have the problem when I'm zooming out the map only one marker on screen. here is the details and screenshot. I've actually use `iconAllowOverlap: true` on my style but the problem is not solved.
here is my [issue](https://github.com/mapbox/react-native-mapbox-gl/issues/1235)
