### ISSUE TITLE
How do I add/remove and show/hide a layer at runtime?

### ISSUE THREAD

**Issue by RNMBuser** [nitaliano/react-native-mapbox-gl#789]
Can this layer reference a source layer in the styleURL?
I tried to use the RasterLayer visibility, with no success.
I will appreciate an example!

**Comment by nitaliano** [comment]
@RNMBuser you can add/remove layers and sources by just removing them as children of your MapView. I'll look into RasterLayer visibility

**Comment by nitaliano** [comment]
@RNMBuser Fix is out in this PR https://github.com/mapbox/react-native-mapbox-gl/pull/846 and it matches the style spec so in your styles you can do

```
{ visibility: 'visible' }
```

or 

```
{ visibility: 'none' }
```

**Comment by nitaliano** [comment]
Closing this out since the fix has been merged into master

**Comment by ansarikhurshid786** [comment]
I am new in react native mapbox. I was using mapbox gl js. 

I have done using mapbox gl js for website.  
hide 
`oMap.setLayoutProperty("layerid", 'visibility', 'none');`
show 
`oMap.setLayoutProperty("layerid", 'visibility', 'visible');`

how can i do using react native mapbox gl? 

@nitaliano

**Comment by ansarikhurshid786** [comment]
@nitaliano can you help me to change layer visibility at run time?
