### ISSUE TITLE
tiles property missing from RasterSource

### ISSUE THREAD

**Issue by RNMBuser** [nitaliano/react-native-mapbox-gl#790]
The [example](https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/WatercolorRasterTiles.js) uses the url property instead.

**Comment by nitaliano** [comment]
Are you referring to wanting the ability to point to a JSON file that conforms to the [tilejson-spec](https://github.com/mapbox/tilejson-spec/) so you can load data locally?

**Comment by lilykaiser** [comment]
Did we get any more info about this issue? If not, we should close for now.
