### ISSUE TITLE
Remote url images in a symbol layer

### ISSUE THREAD

**Issue by scottsampson** [nitaliano/react-native-mapbox-gl#792]
I am having trouble adding a remote absolute url image to symbol layers.  I have icons working just fine from a local source but remote sources just aren't working.  I was able to get remote urls to work from annotations but I feel this isn't proper and from what I can see I can't add an annotations to a layer to zIndex above/below other layers. 

Here are the important parts of my code:

```
iconImages = {
      pinIcon: pinIcon,
      mallIcon: mallIcon,
      branch_29: "http://www.example.com/img.jpg"
    }

...........

    <MapboxGL.ShapeSource
      id='symbolLocationSource2'
      shape={this.state.featureCollection}
      images={iconImages}
      sourceLayerID="PixxyLayer2"
      >
      <MapboxGL.SymbolLayer id="Pixxy2Layer" style={[pixxyMapStyles.icon]}  />
    </MapboxGL.ShapeSource>
    
............
    
    const pixxyMapStyles = MapboxGL.StyleSheet.create({
      icon: {
        iconImage: '{icon}',
        iconAllowOverlap: true,
        iconSize: MapboxGL.StyleSheet.source({
          'pinIcon': 1,
          'mallIcon': 1.2,
          'branch_29': 1,
        }, 'icon', MapboxGL.InterpolationMode.Categorial),
      }
    });
```

Is there anything above that needs to be fixed or do you have an example of a remote source image working in a symbol layer?

**Comment by nitaliano** [comment]
@scottsampson is this happening on both iOS and Android?

**Comment by scottsampson** [comment]
@nitaliano Just iOS for me.  I have not created an Android version of the app yet.

**Comment by scottsampson** [comment]
@nitaliano, figured it out.  The iconImages object should have the uri key for any remote url.  Here is an example:

```
iconImages = {
      pinIcon: pinIcon,
      mallIcon: mallIcon,
      branch_29: { uri: "http://www.example.com/img.jpg" }
    }

**Comment by nitaliano** [comment]
Great glad it's working, I'm going to close this out

**Comment by tarunasosa22** [comment]
const featureCollection = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      id: '9d10456e-bdda-4aa9-9269-04c1667d4552',
      properties: {
        icon: 'https://docs.mapbox.com/mapbox-gl-js/assets/popup_debug.png',
        special_business_image: 'https://docs.mapbox.com/mapbox-gl-js/assets/popup_debug.png',
        category_icon: 'https://docs.mapbox.com/mapbox-gl-js/assets/popup_debug.png',
      },
      geometry: {
        type: 'Point',
        coordinates: [-117.20611157485, 52.180961084261],
      },
    },
    {
      type: 'Feature',
      id: '9d10456e-bdda-4aa9-9269-04c1667d4552',
      properties: {
        icon: 'https://docs.mapbox.com/mapbox-gl-js/assets/popup_debug.png',
        special_business_image: 'https://docs.mapbox.com/mapbox-gl-js/assets/popup_debug.png',
        category_icon: 'https://docs.mapbox.com/mapbox-gl-js/assets/popup_debug.png',
      },
      geometry: {
        type: 'Point',
        coordinates: [-117.205908, 52.180843],
      },
    },
    {
      type: 'Feature',
      id: '9d10456e-bdda-4aa9-9269-04c1667d4552',
      properties: {
        icon: 'https://docs.mapbox.com/mapbox-gl-js/assets/popup_debug.png',
        special_business_image: 'https://docs.mapbox.com/mapbox-gl-js/assets/popup_debug.png',
        category_icon: 'https://docs.mapbox.com/mapbox-gl-js/assets/popup_debug.png',
      },
      geometry: {
        type: 'Point',
        coordinates: [-117.206562, 52.180797],
      },
    },
    {
      type: 'Feature',
      id: '9d10456e-bdda-4aa9-9269-04c1667d4553',
      properties: {
        icon: 'https://docs.mapbox.com/mapbox-gl-js/assets/popup_debug.png',
        special_business_image: 'https://docs.mapbox.com/mapbox-gl-js/assets/popup_debug.png',
        category_icon: 'https://docs.mapbox.com/mapbox-gl-js/assets/popup_debug.png',
      },
      geometry: {
        type: 'Point',
        coordinates: [-117.206862, 52.180897],
      },
    },
    {
      type: 'Feature',
      id: '9d10456e-bdda-4aa9-9269-04c1667d4555',
      properties: {
        icon: 'https://docs.mapbox.com/mapbox-gl-js/assets/popup_debug.png',
        special_business_image: 'https://docs.mapbox.com/mapbox-gl-js/assets/popup_debug.png',
        category_icon: 'https://docs.mapbox.com/mapbox-gl-js/assets/popup_debug.png',
      },
      geometry: {
        type: 'Point',
        coordinates: [-117.205862, 52.180697],
      },
    },
  ],
};

icon: {
    iconImage: ['get', 'special_business_image'],

    iconSize: [
      'match',
      ['get', 'special_business_image'],
      'special_business_image',
      1.2,
      'airport-15',
      1.2,
      /* default */ 1,
    ],
    iconAllowOverlap: true,
  },
  matchParent: { flex: 1 },
{featureCollection.features.map((item, index) => {
          console.log("ITEMM--->", Object.keys(item.properties)[1].toString(), item.properties)
          return (
            <Images
              images={{ example: Object.keys(item?.properties)[1].toString() }}
              onImageMissing={(imageKey) => {
              }}
            >
            </Images>
          )
        })}
         <ShapeSource id="exampleShapeSource" shape={featureCollection}>
          <SymbolLayer id="exampleIconName" style={styless.icon} />
        </ShapeSource>
