### ISSUE TITLE
[Android] onRegionDidChange fires when screen is unmounted

### ISSUE THREAD

**Issue by henrikra** [nitaliano/react-native-mapbox-gl#794]
I noticed that on Android when the current screen (that is containing the map component) is unmounted the map will still emit `onRegionDidChange` event for no reason. This is not happening on iOS. So iOS is fine.

**Comment by henrikra** [comment]
@nitaliano Do you need more info for this? :D

**Comment by nitaliano** [comment]
I tested this in the example application using `6.0.2` and I'm not seeing a region change being fired anymore while the component is unmounting. Mind taking a look?

**Comment by hannta** [comment]
Looks like this is now fixed 👍
