### ISSUE TITLE
[offline] getPack does not show download status

### ISSUE THREAD

**Issue by josenaves** [nitaliano/react-native-mapbox-gl#799]
I'm working on an offline mode for my app. It downloads several map packs (vector and raster).

For some unknown reason, the download of some packs are not finished (with no error callbacks).

So, I'd like to get some information about a specific map pack. For that, I tried to use 
```
MapboxGL.offlineManager.getPack(name)
```

It returned something like that:
```
{ pack: { 
    metadata: '{"name":"SFO_SATELLITE_0"}',
    bounds: [ [ -121.530762, 38.61687 ], [ -121.536255, 38.612578 ] ] 
  }, _metadata: null }
```

Is it possible to have download status on getPack result ?

**Comment by nitaliano** [comment]
I believe we have access to this information on the native side. We can for sure add this to the pack object

**Comment by josenaves** [comment]
It would be great to have it on JS side. I can help doing a PR to Android.

**Comment by nitaliano** [comment]
@josenaves if you do want to give it a go I would be happy to do the iOS portion on a branch with you

**Comment by josenaves** [comment]
:+1:  Sure thing @nitaliano ! You can count on me for Android implementation.

**Comment by nitaliano** [comment]
@josenaves closing this out in favor of https://github.com/mapbox/react-native-mapbox-gl/issues/829 since there a few tickets with offline packs requests we can have the discussion in one place

**Comment by josenaves** [comment]
:+1:
