### ISSUE TITLE
Can't get ShapeSource to Render a Line

### ISSUE THREAD

**Issue by greatwillow** [nitaliano/react-native-mapbox-gl#800]
I am currently implementing a geo-tracking functionality which would display a line indicating where the user has been.  Having been through some trial and error, I haven't yet been able to get anything showing on the map using ShapeSource.  I am just wondering if I am missing something.  I haven't been able to get the examples working (another potential issue/ deprecated dependencies with Turf etc.), so haven't been able to play with them, though have been following their code structure quite closely without any results.  Being a new user to this library, I am wondering first if I'm using the correct branch (master), or should I be using your V6 branch for my project.  My code is as follows:

1. Rendering function (note here that makeLineString is the same Turf.js helper function as that used in the DriveTheLine example):

```
  _renderRoute() {

      const myCoords = [
        [45.50399833333333, -73.5896],
        [45.50390000000001, -73.58979833333333],
        [45.5035, -73.59059833333335],
        [45.503099999999996, -73.5913],
        [45.50279999999999, -73.59179999999999],
        [45.502698333333335, -73.59199833333334],
        [45.50279999999999, -73.5929],
        [45.50289833333333, -73.59329833333332]
      ]

      const line = makeLineString(myCoords)

      console.log('====================================');
      console.log("LINE IS ", line);
      console.log('====================================');

          return (
            <MapboxGL.Animated.ShapeSource id="routeSource" shape={line}>
              <MapboxGL.Animated.LineLayer
                id="routeFill"
                style={layerStyles.route}
              />
            </MapboxGL.Animated.ShapeSource>
          );

  }
```

2. Console log statement of the above:

![screen shot 2017-11-23 at 4 08 17 pm](https://user-images.githubusercontent.com/15651001/33188534-8f46b2c8-d068-11e7-96d7-3366b7d7c979.png)

3. My layer styles
```
const layerStyles = MapboxGL.StyleSheet.create({
  route: {
    lineColor: "blue",
    lineWidth: 10,
    lineOpacity: 0.84
  },
});
```

This is a simplistic variation of what I want to do, so not sure if I'm missing something here.  I am running short on time for this project so any quick help is appreciated.  Thanks!

**Comment by nitaliano** [comment]
Are your coordinates in [longitude, latitude] order? You should also use master or the latest npm version 6.0.0

**Comment by greatwillow** [comment]
Thank-you @nitaliano !  Yes, that was it!  Got the coordinates reversed.  I'm new to GeoJSON and so must have skipped past this thinking that it was a norm to use latitude first.  Thanks for your help and your great work on the project!
