### ISSUE TITLE
com.facebook.react.bridge.JSApplicationIllegalArgumentException

### ISSUE THREAD

**Issue by henrikra** [nitaliano/react-native-mapbox-gl#804]
New crash that our users are getting. Using `react-native-mapbox-gl` 6.0.0

```
com.facebook.react.bridge.JSApplicationIllegalArgumentException Error while updating property 'coordinate' of a view managed by: RCTMGLPointAnnotation 
    ViewManagersPropertyCache.java:95 com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp
    ViewManagerPropertyUpdater.java:129 com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty
    ViewManagerPropertyUpdater.java:48 com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps
    ViewManager.java:34 com.facebook.react.uimanager.ViewManager.updateProperties
    NativeViewHierarchyManager.java:125 com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties
    UIViewOperationQueue.java:96 com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute
    UIViewOperationQueue.java:815 com.facebook.react.uimanager.UIViewOperationQueue$1.run
    UIViewOperationQueue.java:922 com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches
    UIViewOperationQueue.java:47 com.facebook.react.uimanager.UIViewOperationQueue.access$2100
    UIViewOperationQueue.java:982 com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded
    GuardedFrameCallback.java:31 com.facebook.react.uimanager.GuardedFrameCallback.doFrame
    ReactChoreographer.java:136 com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame
    ChoreographerCompat.java:107 com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame
    Choreographer.java:941 android.view.Choreographer$CallbackRecord.run
    Choreographer.java:755 android.view.Choreographer.doCallbacks
    Choreographer.java:687 android.view.Choreographer.doFrame
    Choreographer.java:929 android.view.Choreographer$FrameDisplayEventReceiver.run
    Handler.java:751 android.os.Handler.handleCallback
    Handler.java:95 android.os.Handler.dispatchMessage
    Looper.java:154 android.os.Looper.loop
    ActivityThread.java:6334 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    ZygoteInit.java:886 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
    ZygoteInit.java:776 com.android.internal.os.ZygoteInit.main


Caused by: java.lang.reflect.InvocationTargetException
    Method.java:-2 java.lang.reflect.Method.invoke
    ViewManagersPropertyCache.java:83 com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp
    ViewManagerPropertyUpdater.java:129 com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty
    ViewManagerPropertyUpdater.java:48 com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps
    ViewManager.java:34 com.facebook.react.uimanager.ViewManager.updateProperties
    NativeViewHierarchyManager.java:125 com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties
    UIViewOperationQueue.java:96 com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute
    UIViewOperationQueue.java:815 com.facebook.react.uimanager.UIViewOperationQueue$1.run
    UIViewOperationQueue.java:922 com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches
    UIViewOperationQueue.java:47 com.facebook.react.uimanager.UIViewOperationQueue.access$2100
    UIViewOperationQueue.java:982 com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded
    GuardedFrameCallback.java:31 com.facebook.react.uimanager.GuardedFrameCallback.doFrame
    ReactChoreographer.java:136 com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame
    ChoreographerCompat.java:107 com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame
    Choreographer.java:941 android.view.Choreographer$CallbackRecord.run
    Choreographer.java:755 android.view.Choreographer.doCallbacks
    Choreographer.java:687 android.view.Choreographer.doFrame
    Choreographer.java:929 android.view.Choreographer$FrameDisplayEventReceiver.run
    Handler.java:751 android.os.Handler.handleCallback
    Handler.java:95 android.os.Handler.dispatchMessage
    Looper.java:154 android.os.Looper.loop
    ActivityThread.java:6334 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    ZygoteInit.java:886 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
    ZygoteInit.java:776 com.android.internal.os.ZygoteInit.main


Caused by: java.lang.NullPointerException Attempt to invoke virtual method 'int android.view.View.getWidth()' on a null object reference 
    RCTMGLPointAnnotationAdapter.java:38 com.mapbox.rctmgl.components.annotation.RCTMGLPointAnnotationAdapter.getView
    RCTMGLPointAnnotationAdapter.java:23 com.mapbox.rctmgl.components.annotation.RCTMGLPointAnnotationAdapter.getView
    MarkerViewManager.java:510 com.mapbox.mapboxsdk.annotations.MarkerViewManager.invalidateViewMarkersInVisibleRegion
    MarkerViewManager.java:468 com.mapbox.mapboxsdk.annotations.MarkerViewManager.update
    MarkerView.java:338 com.mapbox.mapboxsdk.annotations.MarkerView.setPosition
    RCTMGLPointAnnotation.java:125 com.mapbox.rctmgl.components.annotation.RCTMGLPointAnnotation.setCoordinate
    RCTMGLPointAnnotationManager.java:64 com.mapbox.rctmgl.components.annotation.RCTMGLPointAnnotationManager.setCoordinate
    Method.java:-2 java.lang.reflect.Method.invoke
    ViewManagersPropertyCache.java:83 com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp
    ViewManagerPropertyUpdater.java:129 com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty
    ViewManagerPropertyUpdater.java:48 com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps
    ViewManager.java:34 com.facebook.react.uimanager.ViewManager.updateProperties
    NativeViewHierarchyManager.java:125 com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties
    UIViewOperationQueue.java:96 com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute
    UIViewOperationQueue.java:815 com.facebook.react.uimanager.UIViewOperationQueue$1.run
    UIViewOperationQueue.java:922 com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches
    UIViewOperationQueue.java:47 com.facebook.react.uimanager.UIViewOperationQueue.access$2100
    UIViewOperationQueue.java:982 com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded
    GuardedFrameCallback.java:31 com.facebook.react.uimanager.GuardedFrameCallback.doFrame
    ReactChoreographer.java:136 com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame
    ChoreographerCompat.java:107 com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame
    Choreographer.java:941 android.view.Choreographer$CallbackRecord.run
    Choreographer.java:755 android.view.Choreographer.doCallbacks
    Choreographer.java:687 android.view.Choreographer.doFrame
    Choreographer.java:929 android.view.Choreographer$FrameDisplayEventReceiver.run
    Handler.java:751 android.os.Handler.handleCallback
    Handler.java:95 android.os.Handler.dispatchMessage
    Looper.java:154 android.os.Looper.loop
    ActivityThread.java:6334 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    ZygoteInit.java:886 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
    ZygoteInit.java:776 com.android.internal.os.ZygoteInit.main
```

**Comment by nitaliano** [comment]
What this error looks like it's saying is the View itself is null when it's trying to get the views width.  Do you happen to have more info like is the app in the background are the annotation views offscreen?

**Comment by ndballantyne** [comment]
The following occurs with app in foreground, off-screen annotations loaded, while moving map around. Our component updates (and reloads annotations) after map bounds change. If we disable the component update the error goes away (though we then have separate issues with map freezing).


`11-29 14:20:26.939  3118  3118 E AndroidRuntime: FATAL EXCEPTION: main
11-29 14:20:26.939  3118  3118 E AndroidRuntime: Process: com.myapp, PID: 3118
11-29 14:20:26.939  3118  3118 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.mapbox.rctmgl.components.annotation.RCTMGLPointAnnotation.getWidth()' on a null object reference
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at com.mapbox.rctmgl.components.annotation.RCTMGLPointAnnotationAdapter.getView(RCTMGLPointAnnotationAdapter.java:40)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at com.mapbox.rctmgl.components.annotation.RCTMGLPointAnnotationAdapter.getView(RCTMGLPointAnnotationAdapter.java:25)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at com.mapbox.mapboxsdk.annotations.MarkerViewManager.invalidateViewMarkersInVisibleRegion(MarkerViewManager.java:510)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at com.mapbox.rctmgl.components.mapview.RCTMGLMapView$1.onCameraIdle(RCTMGLMapView.java:279)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at com.mapbox.mapboxsdk.maps.CameraChangeDispatcher.onCameraIdle(CameraChangeDispatcher.java:65)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at com.mapbox.mapboxsdk.maps.MapGestureDetector.onTouchEvent(MapGestureDetector.java:201)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at com.mapbox.mapboxsdk.maps.MapView.onTouchEvent(MapView.java:277)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.View.dispatchTouchEvent(View.java:9294)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.app.Activity.dispatchTouchEvent(Activity.java:2765)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.View.dispatchPointerEvent(View.java:9514)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5996)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6048)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
11-29 14:20:26.939  3118  3118 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:670)`

**Comment by nitaliano** [comment]
@henrikra are you still seeing this issue with master? This PR made a ton of improvements to annotation views on Android https://github.com/mapbox/react-native-mapbox-gl/pull/852

**Comment by henrikra** [comment]
When you make new release of mapbox I can test it out and observe if these are gone :)

**Comment by nitaliano** [comment]
`6.0.2` is released

**Comment by henrikra** [comment]
I will reopen if I see this again :)
