### ISSUE TITLE
example not accurate

### ISSUE THREAD

**Issue by GuillotJessica** [nitaliano/react-native-mapbox-gl#808]
react-native-mapbox-gl/example/src/components/YoYo.js 
this.state.zoomLevel is not called,
but is changed in different functions.
if I do
eg this.state.zoom:13
zoomLevel={this.state.zoom}
it returns undefined is not an object
it returns
same for coordinates, I give it an array but says I give it a type string...
also, react-native-mapbox-gl/blob/master/docs/MapView.md
in /Utils l80
```
export function toJSONString (json = '') {
  return JSON.stringify(json);
}
```

userTrackingMode expect number default MapboxGL.UserTrackingModes.None The mode used to track the user location on the map
What number?
The doc says:
       

>  // user tracking modes
>         Map<String, Integer> userTrackingModes = new HashMap<>();
>         userTrackingModes.put("None", LocationLayerMode.NONE);
>         userTrackingModes.put("Follow", LocationLayerMode.TRACKING);
>         userTrackingModes.put("FollowWithCourse", LocationLayerMode.NAVIGATION);
> userTrackingModes.put("FollowWithHeading", LocationLayerMode.COMPASS);

What do I miss?
Kind regards,
Jessica

**Comment by nitaliano** [comment]
What version of RN are you using? Those issues should not appearing on the newer versions of RN for prop-type warnings

**Comment by GuillotJessica** [comment]
react": "16.0.0-alpha.12",
    "react-native": "0.47.2",
    "@mapbox/react-native-mapbox-gl": "^6.0.0",

**Comment by nitaliano** [comment]
I would try updating to a newer version of RN, it's helped others something above 0.48.

**Comment by GuillotJessica** [comment]
here's my new versions
    "react": "16.0.0",
    "react-native": "0.50.4",
warn are gone

**Comment by GuillotJessica** [comment]
There is some other miswriting
[MapView.md](https://github.com/mapbox/react-native-mapbox-gl/blob/bf1ce26495dff3234c9266fb8964b4ad2d9f1543/docs/MapView.md#flytocoordinates-duration)
says :
flyTo(coordinates[, duration])
but expect :
this.map.flyTo([lng, lat])
so should be  :
flyTo([coordinates], duration)
am I right?
Jessica

**Comment by nitaliano** [comment]
@GuillotJessica normally with docs the brackets mean the parameter is optional, so
`flyTo(coordinates[, duration])` means duration is optional not that it is an array
