### ISSUE TITLE
Update annotation image

### ISSUE THREAD

**Issue by vitaminwater** [nitaliano/react-native-mapbox-gl#81]
I'm trying to update an annotation's image when it is selected.

So I added a `onTapAnnotation` handler, but when I try to update the state of my react view, it breaks complaining that I'm trying to mutate an immutable object.

**Comment by kouya0219** [comment]
+1

**Comment by tmcw** [comment]
@vitaminwater please reopen this issue if you can provide a more precise bug report - what's the error message in full?
