### ISSUE TITLE
Fitbounds animation looks odd when zooming out

### ISSUE THREAD

**Issue by cglacet** [nitaliano/react-native-mapbox-gl#810]
When the current area is smaller than the final one, the animation looks like its sliding then zooming out whereas in the JS version its nice ans smooth (both happens simultaneously and not linearly). Am I missing something or is it intended?

**Comment by nitaliano** [comment]
It's using a parametrized camera check this issue for reference https://github.com/mapbox/react-native-mapbox-gl/issues/758#issuecomment-344585646 there is a workaround in the ticket that will eventually be added added as the real config. Closing this out as a duplicate and we can track this in the ticket I posted above.

**Comment by cglacet** [comment]
I'm not quite sure to understand what you suggested, I tried this: 

```jsx
this.map.setCamera({
  duration: 2000, // ms
  mode: Mapbox.CameraModes.Ease, // 'Flight', 'Ease', 'None'
  bounds: {
    padding: padding,
    ne: bbox[0],
    sw: bbox[1],
  },
});
```

But it gives the apparent same result. I managed to achieve something that looks a bit closer to what mapbox JS does by doing this ugly thing: 

```jsx
let viewportsize = [640, 480];
let center, zoom;
({center, zoom} = geoViewport.viewport([bbox[0][0],bbox[0][1],bbox[1][0],bbox[1][1]], viewportsize));
await this.map.zoomTo(zoom, 1000);
this.map.moveTo(center, 500);
```

Of course it's not smooth at all since the camera pan happens after zooming out. Is there a way to mix two camera moves together? (Allowing to move and zoom out simultaneously for example.)

**Comment by nitaliano** [comment]
ah sorry misunderstood, you can try
```
this.map.setCamera({
  centerCoordinate: [lng, lat],
  zoom: 12,
})
```
