### ISSUE TITLE
[ANDROID] Mapbox map freeze when back the map after receive call, replay a messenge or standby phone.

### ISSUE THREAD

**Issue by vzlprojects** [nitaliano/react-native-mapbox-gl#811]
Hello! I have a app with mapbox.
when i receive a call or messenge and back the map, the gps dont work and the map freeze... 
I have to restart the map to go back to normal. Please help!

Thanks!

The app...
![c](https://user-images.githubusercontent.com/34045136/33294820-4495954a-d3ca-11e7-9531-8538bb2cc8c2.png)

**Comment by nitaliano** [comment]
I can look into it, what version of Android are you running?

**Comment by vzlprojects** [comment]
Thanks for the answer! 7.0 (nougat). Samsung S8. there will be some way for the map and gps to continue tracking while I read a message, for example...

**Comment by vzlprojects** [comment]
please, see the vídeo: https://www.youtube.com/watch?v=OZAI5U3W7OQ 

I minimized the app and wrote a message. when I return to the app / mapbox, the map zoom does not work and gps is inactive. I have to restart the map to return to normal.

**Comment by nitaliano** [comment]
This looks exactly like this issue checkout the gif https://github.com/mapbox/react-native-mapbox-gl/issues/798#issuecomment-346689956 are you using react-navigation by any chance?

**Comment by vzlprojects** [comment]
Sorry for the delay answering your question. I'm using an Activity and a layout with a MapView and some other elements... 
For the location I'm using "com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.3.0-SNAPSHOT"

**Comment by vzlprojects** [comment]
Same....
https://github.com/mapbox/mapbox-gl-native/issues/9254

**Comment by kristfal** [comment]
Hey,

In an effort to clean out old outstanding tickets, I'm closing this one. This is a very old bug report. I'd recommend reinstalling from master and re-open the issue if the problem still persists.
