### ISSUE TITLE
[v6] setCamera zoomLevel doesn't set zoom level

### ISSUE THREAD

**Issue by butchmarshall** [nitaliano/react-native-mapbox-gl#813]
The zoom level remains fixed when calling setCamera (pitch, centerCoordinate, and duration all work fine).

```
map.setCamera({
	centerCoordinate: [44,76],
	zoomLevel: 16,
	pitch: 120,
	duration: 500,
});
```

**Comment by nitaliano** [comment]
@butchmarshall the camera config calls it `zoom` instead of `zoomLevel`

**Comment by butchmarshall** [comment]
Ah! Thanks!  Works like a charm!

Note: [docs](https://github.com/mapbox/react-native-mapbox-gl/blob/master/docs/MapView.md) should be updated.
