### ISSUE TITLE
[ANDROID] Mapbox crashing the APP

### ISSUE THREAD

**Issue by Jose4gg** [nitaliano/react-native-mapbox-gl#814]
After Mapbox ask for permissions on Android the app starts crashing itself continuously.  

`11-28 13:11:28.309  5043  5043 E UncaughtException: java.lang.AbstractMethodError: abstract method "boolean com.google.android.gms.common.api.Api$zze.zzaax()"
11-28 13:11:28.309  5043  5043 E UncaughtException: 	at com.google.android.gms.common.api.GoogleApiClient$Builder.build(Unknown Source)
11-28 13:11:28.309  5043  5043 E UncaughtException: 	at com.mapbox.services.android.telemetry.location.GoogleLocationEngine.<init>(GoogleLocationEngine.java:38)
11-28 13:11:28.309  5043  5043 E UncaughtException: 	at com.mapbox.services.android.telemetry.location.GoogleLocationEngine.getLocationEngine(GoogleLocationEngine.java:43)
11-28 13:11:28.309  5043  5043 E UncaughtException: 	at com.mapbox.services.android.telemetry.location.GoogleLocationEngineFactory.supply(GoogleLocationEngineFactory.java:17)
11-28 13:11:28.309  5043  5043 E UncaughtException: 	at com.mapbox.services.android.telemetry.location.LocationEngineProvider.initAvailableLocationEngines(LocationEngineProvider.java:44)
11-28 13:11:28.309  5043  5043 E UncaughtException: 	at com.mapbox.services.android.telemetry.location.LocationEngineProvider.<init>(LocationEngineProvider.java:23)
11-28 13:11:28.309  5043  5043 E UncaughtException: 	at com.mapbox.services.android.telemetry.MapboxTelemetry.registerLocationUpdates(MapboxTelemetry.java:481)
11-28 13:11:28.309  5043  5043 E UncaughtException: 	at com.mapbox.services.android.telemetry.MapboxTelemetry.setTelemetryEnabled(MapboxTelemetry.java:426)
11-28 13:11:28.309  5043  5043 E UncaughtException: 	at com.mapbox.services.android.telemetry.MapboxTelemetry.loadUserPreferences(MapboxTelemetry.java:396)
11-28 13:11:28.309  5043  5043 E UncaughtException: 	at com.mapbox.services.android.telemetry.MapboxTelemetry.initialize(MapboxTelemetry.java:178)
11-28 13:11:28.309  5043  5043 E UncaughtException: 	at com.mapbox.services.android.telemetry.MapboxTelemetry.initialize(MapboxTelemetry.java:125)
11-28 13:11:28.309  5043  5043 E UncaughtException: 	at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:55)
11-28 13:11:28.309  5043  5043 E UncaughtException: 	at com.mapbox.rctmgl.modules.RCTMGLModule$1.run(RCTMGLModule.java:245)
11-28 13:11:28.309  5043  5043 E UncaughtException: 	at android.os.Handler.handleCallback(Handler.java:751)
11-28 13:11:28.309  5043  5043 E UncaughtException: 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-28 13:11:28.309  5043  5043 E UncaughtException: 	at android.os.Looper.loop(Looper.java:154)
11-28 13:11:28.309  5043  5043 E UncaughtException: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
11-28 13:11:28.309  5043  5043 E UncaughtException: 	at java.lang.reflect.Method.invoke(Native Method)
11-28 13:11:28.309  5043  5043 E UncaughtException: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
11-28 13:11:28.309  5043  5043 E UncaughtException: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

**Comment by Jose4gg** [comment]
If I select `DENY` the app starts perfectly

**Comment by hernanmateo** [comment]
I don't know your exact situation, but I pass through a similar issue by importing some google play services packages in the build.gradle file:

```
dependencies {
    [...]
    compile 'com.google.android.gms:play-services-base:+'
    compile 'com.google.android.gms:play-services-location:+'
    compile 'com.google.android.gms:play-services-maps:+'
}
```

**Comment by GuillotJessica** [comment]
@hernanmateo 
I copy the following line into Android/App/build.gradle and get the following error during build to the simulator :
`com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: Cannot merge new index 66297 into a non-jumbo instruction!`
Did you do anything else in that matter
Thx,
Jessica

**Comment by GuillotJessica** [comment]
So I did [this ](https://stackoverflow.com/questions/26515378/dexindexoverflowexception-issue-after-updating-to-latest-appcompat-and-support-l) [or this in french](http://tutos-android-france.com/multidex-depasser-limite-65536-methodes/) the build is successful but the app crash instantly
did I miss something?

**Comment by hernanmateo** [comment]
Try to enable dexOptions/jumboMode in your app/build.grade file

```
[...]
android {
    [...]
    dexOptions {
        jumboMode true
    }
}
```

**Comment by GuillotJessica** [comment]
@hernanmateo it works fine thx 🥇

**Comment by nitaliano** [comment]
@Jose4gg It does sound like certain deps are colliding I would recommending doing what @hernanmateo mentioned above
