### ISSUE TITLE
[Question] Drawing geometry on map

### ISSUE THREAD

**Issue by StevanCakic** [nitaliano/react-native-mapbox-gl#815]
Hi,

I have a question. What is the simplest and most efficient way to draw different geometry shapes on the map, like points, polygons, lines, etc. ? I know for https://github.com/mapbox/mapbox-gl-draw but is there anything like this but for drawing on mobile? Thanks

**Comment by nitaliano** [comment]
There is no draw package out yet, but there are plans to have one. Do you need to be able to edit the vertices for your use case?

**Comment by StevanCakic** [comment]
I need 3 types of shapes: points, lines/ multi lines, and polygons. What I want to do with this:

-allow a user to draw (insert) those shapes and when the user hits some submit button this shapes will be inserted in some .json or database
- allow the user to update those shapes from that data source (move vertices for multiple lines and polygons, moving points, etc.)
- allow the user to delete  those shapes (for example on the shape that user clicks)

Can I help/contribute somehow?

**Comment by nitaliano** [comment]
@StevanCakic I think we'll be in a better place once we open up a repo drawing repo to start with contributions. One thing that this repo needs to do before we can create a drawing library is being able to drag layers on the map, which is slightly more complicated than being able to drag regular Views.

**Comment by andela-cofor** [comment]
Can we draw lines on react native mapbox from one geo point to another ?

**Comment by kooscode** [comment]
Any update on when we can draw polygons on a map with React Native SDK ?

**Comment by Schabaani** [comment]
Any update for drawing polygons yet?
I want to send some points to map and it draws points.

**Comment by rcstanciu** [comment]
Any updates on drawing polygons?

**Comment by gino8080** [comment]
bump :)

**Comment by delkant** [comment]
Is it possible to draw polygons on a map with React Native SDK ?

**Comment by njoromyke** [comment]
Any feedback for this issue?
