### ISSUE TITLE
Generate new style props for iOS(3.7.0) and Android(5.2.0)

### ISSUE THREAD

**Issue by nitaliano** [nitaliano/react-native-mapbox-gl#819]
More style props have been added in the recent agua release so we need to pull in the updated style-spec.json and run our generate script

New style props
* iconAnchor
* iconPitchAlignment
* circlePitchAlignment

**Comment by StasDoskalenko** [comment]
hey @nitaliano ! Thanks for a great job! Will you add ImageSource for georeferenced overlays support?

**Comment by nitaliano** [comment]
Yes you can follow this ticket https://github.com/mapbox/react-native-mapbox-gl/issues/817
