### ISSUE TITLE
Annotations disappear when popped back to view

### ISSUE THREAD

**Issue by vitaminwater** [nitaliano/react-native-mapbox-gl#82]
When I have a view with a mapview, and I push another view on top of it with the navigator, if I pop back to the view containing the mapview, all annotations are gone.

Only thing I see in xcode's logs is: `Can't find sprite named 'com.mapbox.sprites.marker0'`, 'marker0' being one the ids of my annotations.

**Comment by robipresotto** [comment]
+1

**Comment by olofd** [comment]
+1

**Comment by bsudekum** [comment]
Do you think you could make a sample like https://rnplay.org/apps/YmkqXg or put a little sample code here so I can check this bug out?

**Comment by olofd** [comment]
@bsudekum The easiest way to recreate for me is to just rotate the device. canät do that on the playground it seams.

**Comment by olofd** [comment]
It has something to do with the properties set in updateMap(). When I change the code in layoutSubViews to:
- (void)layoutSubviews
  {
  NSLog(@"Layout subviews");
  if(_annotations.count == 0){
      [self updateMap];
  
  }
  _map.frame = self.bounds;
  }

The annotations stays after a device-rotation.
