### ISSUE TITLE
[v6] MapboxGL.offlineManager information about pack size

### ISSUE THREAD

**Issue by butchmarshall** [nitaliano/react-native-mapbox-gl#820]
v5 had 

```
{
	countOfResourcesExpected: [...],
	maximumResourcesExpected: [...],
	countOfResourcesCompleted: [...],
	countOfBytesCompleted: [...]
}
```

Does v6 have this information to expose?  It would be useful to show the users the amount of data being downloaded.

**Comment by nitaliano** [comment]
Yes we can expose that info we have access to it on the native side

**Comment by nitaliano** [comment]
@butchmarshall closing this out in favor of https://github.com/mapbox/react-native-mapbox-gl/issues/829 there are some other tickets requesting more information being added to offline packs so we can move the discussions over there.
