### ISSUE TITLE
[Android] App crashes when annotation is selected 

### ISSUE THREAD

**Issue by josenaves** [nitaliano/react-native-mapbox-gl#823]
I'm using the latest version (master).
Android emulator 7.1.1.

11-29 15:11:45.621  4732  4732 E AndroidRuntime: FATAL EXCEPTION: main
11-29 15:11:45.621  4732  4732 E AndroidRuntime: Process: com.dispatchr, PID: 4732
11-29 15:11:45.621  4732  4732 E AndroidRuntime: java.lang.IllegalStateException: A catalyst view must have an explicit width and height given to it. This should normally happen as part of the standard catalyst UI framework.
11-29 15:11:45.621  4732  4732 E AndroidRuntime: 	at com.facebook.react.uimanager.MeasureSpecAssertions.assertExplicitMeasureSpec(MeasureSpecAssertions.java:24)
11-29 15:11:45.621  4732  4732 E AndroidRuntime: 	at com.facebook.react.views.view.ReactViewGroup.onMeasure(ReactViewGroup.java:117)
11-29 15:11:45.621  4732  4732 E AndroidRuntime: 	at android.view.View.measure(View.java:19857)
11-29 15:11:45.621  4732  4732 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
11-29 15:11:45.621  4732  4732 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
11-29 15:11:45.621  4732  4732 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
11-29 15:11:45.621  4732  4732 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
11-29 15:11:45.621  4732  4732 E AndroidRuntime: 	at android.view.View.measure(View.java:19857)
11-29 15:11:45.621  4732  4732 E AndroidRuntime: 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
11-29 15:11:45.621  4732  4732 E AndroidRuntime: 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
11-29 15:11:45.621  4732  4732 E AndroidRuntime: 	at android.view.View.measure(View.java:19857)
11-29 15:11:45.621  4732  4732 E AndroidRuntime: 	at com.mapbox.mapboxsdk.annotations.MarkerViewManager.ensureInfoWindowOffset(MarkerViewManager.java:602)
11-29 15:11:45.621  4732  4732 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.AnnotationManager.selectMarker(AnnotationManager.java:288)
11-29 15:11:45.621  4732  4732 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.MapboxMap.selectMarker(MapboxMap.java:1563)
11-29 15:11:45.621  4732  4732 E AndroidRuntime: 	at com.mapbox.rctmgl.components.mapview.RCTMGLMapView.selectAnnotation(RCTMGLMapView.java:393)
11-29 15:11:45.621  4732  4732 E AndroidRuntime: 	at com.mapbox.rctmgl.components.annotation.RCTMGLPointAnnotation$1.run(RCTMGLPointAnnotation.java:182)
11-29 15:11:45.621  4732  4732 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
11-29 15:11:45.621  4732  4732 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-29 15:11:45.621  4732  4732 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
11-29 15:11:45.621  4732  4732 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
11-29 15:11:45.621  4732  4732 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-29 15:11:45.621  4732  4732 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
11-29 15:11:45.621  4732  4732 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by nitaliano** [comment]
does your custom view have a width and height on it?

**Comment by josenaves** [comment]
Do you mean, my annotations ? 
Yes, they have width and height set.
For the map, I'm setting only the width (percentage).

**Comment by GuillotJessica** [comment]
send your code to have a look

**Comment by josenaves** [comment]
I think it's an issue here on my side. I'll try to get more details before close this one.

**Comment by nitaliano** [comment]
@josenaves This PR might fix this issue as I've not seen it since 🤞. https://github.com/mapbox/react-native-mapbox-gl/pull/852

I noticed, this happens when we are recycling the views(pan the annotations off screen, pan back in select) on the native side and React Native has no idea this is happening, causing the crash. What I do now is override the onMeasure since we know our width and height and set that directly

**Comment by josenaves** [comment]
I think the issue was on my side. A workmate has fixed the issue.

<MapboxGL.PointAnnotation
  key={ id }
  id={ id }
  title={ title }
  coordinate={ coordinate }
  selected={ i === this.state.currentAnnotationIndex }
  onSelected={ feature => this.onAnnotationSelected(i, feature) }
  onDeselected={ () => this.onAnnotationDeselected(i) }
>

The issue went away removing this line:
  selected={ i === this.state.currentAnnotationIndex }

**Comment by nitaliano** [comment]
Cool, closing this out

**Comment by josenaves** [comment]
:+1:
