### ISSUE TITLE
Crash when adding a new marker (annotation)

### ISSUE THREAD

**Issue by salttis** [nitaliano/react-native-mapbox-gl#83]
Using the same code as the example and when trying to add a new marker the application crashes.

XCode error:
`<Error>: CGContextDrawImage: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
libc++abi.dylib: terminating with uncaught exception of type mbgl::util::SpriteImageException: Sprite image dimensions may not be zero`

Versions:
React Native 0.10.0
React Native Mapbox GL 0.4.1

Adding width and height values to the `addAnnotations` method in the example does not fix the error.

**Comment by miracle2k** [comment]
Had the same problem, the fix was for me to copy the annotation structure from the example. In particular, it seems the annotationImage needs to be provided.

**Comment by bsudekum** [comment]
@3bola Could I check out the code? Perhaps @miracle2k is the fix?

**Comment by salttis** [comment]
The error occured in the example code. I think this fixed it: https://github.com/mapbox/react-native-mapbox-gl/commit/b593541ba1ac34332012738abd03ab3909a95dfd
