### ISSUE TITLE
v6 Custom callouts not opening after zoom [iOS]

### ISSUE THREAD

**Issue by olofd** [nitaliano/react-native-mapbox-gl#830]
I use MapboxGL.PointAnnotation with MapboxGL.Callout to render custom callouts.
They render fine in the simulator and do always open there (Even though the simulator is slow)
On device they work and open as they should before I zoom.
After zoom the more and more start to not open at all.

After a couple of minutes the nearly never open at all.

Video to demonstrate issue:
https://www.youtube.com/watch?v=6LcK3dqtuK8

**Comment by josenaves** [comment]
I can note the same behavior on Android (version 6.0.2-rc1)

**Comment by nitaliano** [comment]
Going to look into this for the `6.0.3` release

**Comment by kwoumn3** [comment]
+1, I am experiencing the same behavior on iOS

**Comment by kristfal** [comment]
Hey,

In an effort to clean out old outstanding tickets, I'm closing this one. This repository is no longer maintained by Mapbox, so if you do have a PR that fixes this issue, we'd be happy to accept it.
