### ISSUE TITLE
Choropleth with MapboxGL

### ISSUE THREAD

**Issue by kylesziv** [nitaliano/react-native-mapbox-gl#833]
I'm using `MapboxGL.ShapeSource` and `MapboxGL.FillLayer` and I'm trying figure out how to create a choropleth map. I'm successfully loading a GeoJSON file and I can paint a single color just fine. With the web version of Mapbox GL, I was able to set a property which Mapbox would use as the color property for each geometric shape. Is there something similar that I can do with this package?

**Comment by kristfal** [comment]
Hey, you can use data driven styling here as well to solve that problem.  

However, there is currently a bug that prevents style interpolation with non-integer keys, so you’ll need to define your colors as integer numbers in your data, and then map those integers back to the colors you want in your style. I think there is an example of this in the examples app, if not, lemme know and I’ll show you.

**Comment by kylesziv** [comment]
Ahh! I found the example and got this working in my project. Thank you for your help!

**Comment by dror-developer** [comment]
@kylesziv please share the example here also.
