### ISSUE TITLE
[Android] First region change fire location [0, 0]

### ISSUE THREAD

**Issue by SandeshBG** [nitaliano/react-native-mapbox-gl#837]
I am trying to implement map view with custom annotation to point current location in Android. I want a feature like when region changes, annotation also changes along with that. But I have problem with onRegionIsChanging. onRegionIsChanging is invoked with some delay and its not providing any coordinates or any other data. It is just giving me empty object. onRegionWillChange is not at all invoked on map drag. However onRegionDidChange is invoking on map drag, but this is having another problem. First time when map loading completes its invoked with coordinates [0,0] and after that if I drag it is giving me the coordinates. So what is the solution for this? When it returns [0,0] coordinates my annotation disappears.

I am using 
react native 0.50.4
react 16.0.0
react-native-mapbox-gl  6.0.1

**Comment by nitaliano** [comment]
I would ignore coordinates that return at [0, 0](chances of getting a coordinate at [0, 0] without any decimal places is near impossible). Android and iOS native SDK's behave differently right now with these events, this repo will eventually have this type of stuff sorted out in the future

**Comment by kaynz** [comment]
@nitaliano The main problem @SandeshBG describes is that the very first callback of onRegionDidChange returns coordinates at [0,0], no matter where your map actually is. It could be at [50,7] and onRegionDidChange would return [0,0].

**Comment by nitaliano** [comment]
@kaynz I see thanks for commenting back. Reopened

**Comment by nitaliano** [comment]
This is fixed in `6.0.2`

**Comment by kaynz** [comment]
Hi @nitaliano, thank you.

Well, yeah, there's no more [0,0] because there is no onRegionDidChange() when map is finished loading. I would expect an initial onRegionDidChange after map is finished loading, so is the current behaviour correct?

**Comment by SandeshBG** [comment]
Are those onRegionIsChanging and onRegionWillChange working now?

**Comment by nitaliano** [comment]
@kaynz I see what you're saying I will do another npm publish today that fixes this atleast. iOS does fire this once the map is loaded. I had to move this out of the natural flow because the Android SDK will report this at earlier times and far more often than the iOS SDK, so I'll manually fire this in `onMapReady` in the native code

@SandeshBG are you trying to implement drag support with the map events?

**Comment by nitaliano** [comment]
The region not being sent up on load for Android is fixed in this PR https://github.com/mapbox/react-native-mapbox-gl/pull/897

**Comment by nitaliano** [comment]
PR has been merged into master and we are now sending the first region event
