### ISSUE TITLE
Accept array of coordinates in `fitBounds`/`setCamera`

### ISSUE THREAD

**Issue by lucasbento** [nitaliano/react-native-mapbox-gl#839]
I have to center a polyline of a route, the route can have multiple coordinate points and look like this:

![image](https://user-images.githubusercontent.com/6207220/33601336-3578c6e4-d9ac-11e7-86ee-f74a2660e14a.png)

It sort of starts and finishes in the same point so I have to find the farthest coordinate (loop through the coordinates and calculate their distances) and do `fitBounds(firstPoint, farthestPoint)`, it would be awesome if `fitBounds` would accept an array and center everything by its own.

@nitaliano: if it's not possible, do you have any suggestion on how to do this faster?

**Comment by lucasbento** [comment]
My solution didn't work for some cases with strange routes, ended up using [bound-points](https://github.com/mikolalysenko/bound-points) which works nice!

**Comment by kristfal** [comment]
For general geo processing, I'd recommend [Turf JS](turfjs.org). In this particular case, bbox or bbox-polygon would also have solved your issue.

**Comment by nitaliano** [comment]
@lucasbento you should use turfjs for this you can think of it as underscore for anything geo related. It's highly optimized and using turf means you can share code between mobile and web.

These are quick links to the two functions that @kristfal described above that will be able to solve this issue for you.

http://turfjs.org/docs#bbox
http://turfjs.org/docs#bboxPolygon
