### ISSUE TITLE
OnSelected and OnDeselected PointAnnotation behavior issues

### ISSUE THREAD

**Issue by jstopchick** [nitaliano/react-native-mapbox-gl#841]
This issue was encountered on Android 6.0.1.

I am using the Mapbox example code for "ShowPointAnnotation" and I see that it includes using onSelected and onDeselected callbacks.  In the example if I omit these and the callout, and only include the PointAnnotations when clicking on the map, callbacks still appear to be bound to the PointAnnotations.  

This can be duplicated by taking the MapboxGL example and removing the onSelected  callback, the onDeselected callbacks, and the callout, then creating a point on the map.  After creating the point, if the user clicks on the point, no callout appears as expected, however the next click on the map is the onDeselected handler, not the onPress handler.

Is this behavior expected?  And if so, is there a way to progmatically remove the PointAnnotation/Callout?  I've also tried removing the point annotation from the feature collection state, however if the callout is active and showing, then removing the Annotation in this way prevents the onDeselected handler from firing, and in turn the MapView's onPress method becomes unavailable until I click on another point and then click off that point.

**Comment by nitaliano** [comment]
@jstopchick this PR https://github.com/mapbox/react-native-mapbox-gl/pull/852 fixes the onPress issue. Also to answer your question this is not expected behavior I will add the other fixes to the PR I posted

**Comment by nitaliano** [comment]
@jstopchick I've added the other changes to the PR so it should work as expected now. I'll close this out once we merge it into master

**Comment by nitaliano** [comment]
Closing this out fix has been merged into master

**Comment by nCheck** [comment]
currently using 6.1.3 version. After you click on it once, it doesn't fire again. to quickly fix this, just kill the app and start again.
