### ISSUE TITLE
undefined is not an object (evaluating 'MapboxGL.UserTrackingModes') 

### ISSUE THREAD

**Issue by KevinHu2014** [nitaliano/react-native-mapbox-gl#843]
Getting the error on iOS by following the sample from the official website.

![simulator screen shot - iphone 8 - 2017-12-06 at 17 17 12](https://user-images.githubusercontent.com/7204070/33653985-b03e8d0c-daa9-11e7-9db8-c2612b243da4.png)

## Environment 
React Native 0.47.2
@mapbox/react-native-mapbox-gl   6.0.1

[](https://www.mapbox.com/help/first-steps-react-native-sdk/)

## Sample Code 
```
import React, { Component } from 'react';
import { StyleSheet, View } from 'react-native';
import Mapbox from '@mapbox/react-native-mapbox-gl';

Mapbox.setAccessToken('<access-token>');

export default class App extends Component<{}> {
  render() {
    return (
      <View style={styles.container}>
        <Mapbox.MapView
            styleURL={Mapbox.StyleURL.Street}
            zoomLevel={15}
            centerCoordinate={[11.256, 43.770]}
            style={styles.container}>
        </Mapbox.MapView>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});
```

Thanks

**Comment by nitaliano** [comment]
You need to link the native code to your projects follow these guides https://github.com/mapbox/react-native-mapbox-gl/blob/master/README.md#installation-guides

**Comment by KevinHu2014** [comment]
@nitaliano I have been using V5 in my project.
Does upgrading to V6 requires relinking the native code?

**Comment by KevinHu2014** [comment]
By relinking it still cause the same error.
`TicoService[8775:316123] *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: undefined is not an object (evaluating 'c.UserTrackingModes')', reason: 'Unhandled JS Exception: undefined is not an object `

**Comment by nitaliano** [comment]
Yes, v6 is a complete rewrite

**Comment by KevinHu2014** [comment]
@nitaliano 
While relinking the Library , I ran into another error. 
Any Ideas on this one?

Thanks!
<img width="546" alt="2017-12-07 1 08 08" src="https://user-images.githubusercontent.com/7204070/33674697-2f91a35a-daeb-11e7-9a63-c2c625e5cc8a.png">

**Comment by nitaliano** [comment]
Did you also re embed Mapbox.framework?

**Comment by KevinHu2014** [comment]
Yes

**Comment by nitaliano** [comment]
Update your header search paths to point to Mapbox.framework https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/install.md#add-framework-header-search-paths.

I just ran through the steps on a clean project and got it up and running so it must be something between the old and new config

**Comment by KevinHu2014** [comment]
@nitaliano Thanks for the help.
It's something between the old and new config.
And by Update your header search paths would do the trick.

Thanks again.

**Comment by ghost** [comment]
Similiar issue over at https://github.com/mapbox/react-native-mapbox-gl/pull/741#issuecomment-347038647 but more related to build and error with `framework not found mapbox` via CocoaPods install, Manual install has issues additionally more me.

Update https://github.com/mapbox/react-native-mapbox-gl/issues/860 seems related to `libc++abi.dylib: terminating with uncaught exception of type NSException (lldb)`

**Comment by MrHazimAli** [comment]
does version 6.0.2 require manual installation ? after updating I got linker error even after following update header search path and added the script.

**Comment by tetreault** [comment]
I've done both manual linking and cocoapods method. cocoapods method produces the same error as OP. Manual linking produces a different error: 

<img width="1426" alt="screenshot 2018-05-30 09 11 36" src="https://user-images.githubusercontent.com/5934354/40734351-295c8c58-6406-11e8-8d8e-86e5aec44eb9.png">

Misc Info: 
    "@mapbox/react-native-mapbox-gl": "^6.1.2-beta2",
    "react": "16.3.1",
    "react-native": "0.55.4"

**Comment by tetreault** [comment]
ignore the above! such a stupid mistake... to anyone reading this: after you do the cocoapods installation method, make sure you rebuild the project. The instructions specify it, but my brain is clearly having a tough day today!

**Comment by derren7532123** [comment]
HI Guys, anyone can help me solve this problem?
![33653985-b03e8d0c-daa9-11e7-9db8-c2612b243da4](https://user-images.githubusercontent.com/43113530/48302192-2795f800-e534-11e8-9363-12f135b79154.png)

import React from 'react';

import {
  View,
  Text,
  Platform,
  Modal,
  FlatList,
  Image,
  TouchableOpacity,
  StatusBar,
  StyleSheet,
} from 'react-native';

import MapboxGL from '@mapbox/react-native-mapbox-gl';
import StoreLocatorKit from '@mapbox/store-locator-react-native';
import LinearGradient from 'react-native-linear-gradient';
import Icon from 'react-native-vector-icons/MaterialIcons';

import places from '../../assets/places.json';

import {
  purpleTheme,
  blueTheme,
  greenTheme,
  grayTheme,
  neutralTheme,
} from '../themes';

const IS_IOS = Platform.OS === 'ios';
const MAPBOX_ACCESS_TOKEN = 'pk.eyJ1IjoiZGVycmVuNzUzMiIsImEiOiJjam9iZmZldDcwOXdjM3hwNTdjMmdzM2M0In0.IkwKElTlrMPxQmLBtIO0Hg';

const ThemeList = [
  {
    name: 'Blue Theme',
    theme: blueTheme,
    // image: require('../assets/blue_button_image.png'),
  },
  {
    name: 'Purple Theme',
    theme: purpleTheme,
    // image: require('../assets/purple_button_image.png'),
  },
  {
    name: 'Green Theme',
    theme: greenTheme,
    // image: require('../assets/green_button_image.png'),
  },
  {
    name: 'Gray Theme',
    theme: grayTheme,
    // image: require('../assets/gray_button_image.png'),
  },
  {
    name: 'Neutral Theme',
    theme: neutralTheme,
    // image: require('../assets/neutral_button_image.png'),
  },
];

const styles = StyleSheet.create({
  matchParent: {
    flex: 1,
  },
  mapHeader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 120,
    backgroundColor: 'transparent',
  },
  mapGradient: {
    flex: 1,
    height: 120,
  },
  mapHeaderText: {
    fontSize: 24,
    color: 'white',
    alignSelf: 'center',
    position: 'relative',
    top: -60,
  },
  backArrow: {
    position: 'absolute',
    top: 32,
    left: 24,
  },
});

class App extends React.Component {
  constructor (props) {
    super(props);

    this.state = {
      isGranted: IS_IOS,
      activeTheme: null,
      initialLocation: [-77.034084, 38.90],
    };

    this.onDismiss = this.onDismiss.bind(this);
    this.renderThemeItem = this.renderThemeItem.bind(this);
  }

  async componentWillMount () {
    if (!IS_IOS) {
      const isGranted = await MapboxGL.requestAndroidLocationPermissions();
      this.setState({ isGranted: isGranted });
    }
    MapboxGL.setAccessToken(MAPBOX_ACCESS_TOKEN);
  }

  onDismiss () {
    StatusBar.setBarStyle('dark-content');
    this.setState({ activeTheme: null });
  }

  renderThemeItem ({ item, index }) {
    const marginTop = index === 0 ? 16 : 8;
    const marginBottom = 8;

    const style = {
      flex: 1,
      height: 120,
      marginTop: marginTop,
      marginBottom: marginBottom,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: item.theme.primaryColor,
    };

    return (
      <TouchableOpacity onPress={() => this.setState({ activeTheme: item.theme })}>
        <View style={style}>
          <Image source={item.image} style={{ width: 130, flex: 1 }} />
        </View>
      </TouchableOpacity>
    );
  }

  renderThemeList () {
    return (
      <View style={{ flex: 1 }}>
        <View style={{ alignItems: 'center', justifyContent: 'center', height: 60 }}>
          <Text style={{ marginTop: 8, fontWeight: 'bold', fontSize: 16 }}>Tap a theme</Text>
        </View>
        <FlatList
          data={ThemeList}
          keyExtractor={(item) => item.name}
          renderItem={this.renderThemeItem} />
      </View>
    );
  }

  renderMap () {
    if (!this.state.activeTheme) {
      return null;
    }

    StatusBar.setBarStyle('light-content');

    return (
      <Modal
        visible={!!this.state.activeTheme}
        animationType='slide'
        transparent
        onRequestClose={this.onDismiss}>
        <View style={styles.matchParent}>
          <StoreLocatorKit.MapView
            simulateUserLocation
            accessToken={MAPBOX_ACCESS_TOKEN}
            theme={this.state.activeTheme}
            centerCoordinate={this.state.initialLocation}
            featureCollection={places}
            zoomLevel={13}
            style={styles.matchParent} />

          <View style={styles.mapHeader}>
            <LinearGradient
              style={styles.mapGradient}
              colors={['black', 'transparent']} />

            <Icon
              name='keyboard-backspace'
              size={28}
              onPress={this.onDismiss}
              style={styles.backArrow}
              color='white' />

            <Text style={styles.mapHeaderText}>Store Locator</Text>
          </View>
        </View>
      </Modal>
    );
  }

  render () {
    if (!this.state.isGranted) {
      return null;
    }
    return (
      <View style={styles.matchParent}>
        {this.renderThemeList()}
        {this.renderMap()}
      </View>
    );
  }
}

export default App;

**Comment by jt3k** [comment]
I have the same problem. Is there a clear answer how to fix this step by step for newbies?

**Comment by josepaulodelacruz** [comment]
Same error for me, I'm using react native with expo, I can't seem to understand the installation procedure. How can I link it to expo?

**Comment by jt3k** [comment]
@josepaulodelacruz Searching for issues says that you won't be able to link with expo

**Comment by NathanNovak** [comment]
I am having the same issue but Mapbox.GL is not involved in this project.  I used it on a different project.  Can anyone help with that?

**Comment by DenisShvetz** [comment]
The CocoaPods installation doesn't work well.
Please follow the Manual Installation in the ReadMe. It works for me.
https://github.com/nitaliano/react-native-mapbox-gl/blob/master/ios/install.md
