### ISSUE TITLE
Example app does not work on Android because of a syntax error in MainActivity.java

### ISSUE THREAD

**Issue by bcalik** [nitaliano/react-native-mapbox-gl#844]
When I try to run the example directory in Android. It gives an error says;
```
/private/var/files/www/mobile/mapbox/example/android/app/src/main/java/com/react-native-mapbox-gl-demo/MainActivity.java:1: error: ';' expected
package com.react-native-mapbox-gl-demo;
                 ^
/private/var/files/www/mobile/mapbox/example/android/app/src/main/java/com/react-native-mapbox-gl-demo/MainApplication.java:1: error: ';' expected
package com.react-native-mapbox-gl-demo;
                 ^
2 errors
:app:compileDebugJavaWithJavac FAILED
```

When I look at these files, you can see that the package name contains dash so it gives a syntax error.

<img width="773" alt="screen shot 2017-12-06 at 17 12 05" src="https://user-images.githubusercontent.com/9222368/33665640-b02bcfc4-daa8-11e7-9793-4de928db9b7f.png">

**Comment by nitaliano** [comment]
This is the package name that is in the example application https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/android/app/src/main/java/com/rnmapboxglexample/MainActivity.java#L1. what you posted above is different is this your own example app?

**Comment by bcalik** [comment]
Ok this is weird.

The file on the screenshot is this file: https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/android/app/src/main/java/com/rnmapboxglexample/MainApplication.java

But somehow, the package name did not match for me.
I may have done something wrong from Android Studio.

**Comment by nitaliano** [comment]
did you run any commands with the react native cli?
