### ISSUE TITLE
Clustering does not work in Android

### ISSUE THREAD

**Issue by bcalik** [nitaliano/react-native-mapbox-gl#845]
I tried to run the exact code in [EarthQuakes](https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/EarthQuakes.js) example.

As you can see from the screenshot below, it is working in iOS but not on Android.
Clusters are not visible.

You can see the code from the link.

<img width="839" alt="screen shot 2017-12-06 at 17 24 18" src="https://user-images.githubusercontent.com/9222368/33666366-d59cfa4c-daaa-11e7-98b6-1f416025dab3.png">

**Comment by nitaliano** [comment]
It's an issue on 6.0.1 master is fixed already

**Comment by bcalik** [comment]
@nitaliano Master branch currently does not work on Android. So I can't test it to confirm. I only see an empty space instead of map.

**Comment by bcalik** [comment]
I guess the fix is this commit: https://github.com/mapbox/react-native-mapbox-gl/commit/5f252c7657c8df5a07d94acff4e666d3285d3435
I cherry-picked it, and I can confirm its working well now.

But the latest master branch doesn't work, fyi. @nitaliano
