### ISSUE TITLE
[Android] prop showUserLocation={true} overrides map centerCoordinate

### ISSUE THREAD

**Issue by kristfal** [nitaliano/react-native-mapbox-gl#848]
Using the following props on initialization:

```js
<MapboxGL.MapView showUserLocation={true} centerCoordinate={[0,0]}/>
```

The map will init at the centerCoordinate, but instantly move to the user's location, effectively overriding the center coordinate prop. The camera should only move when `userTrackingMode` is set to a non-default option.

In addition, the map should update its camera when `userTrackingMode` is toggled to one of the active options on Android. It currently doesn't, while iOS does.

**Comment by nitaliano** [comment]
I would do everything location based with this https://facebook.github.io/react-native/docs/geolocation.html and a custom layer for the time being until I jump into to making these perform the same cross platform.

You might be able to reuse this layer https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/common/PulseCircleLayer.js

**Comment by kristfal** [comment]
Tops,

I totally get that, I'd consider this low pri as well. Once #697 lands, we should be able to do a proper geolocation implementation on the JS side.

**Comment by kaynz** [comment]
> I would do everything location based with this https://facebook.github.io/react-native/docs/geolocation.html and a custom layer for the time being until I jump into to making these perform the same cross platform.

That's a really bad idea (at least for android). The google location sdk is working much better than the geolocation api. That's the reason why airbnb does not use geolocation api in their library: https://github.com/react-community/react-native-maps

**Comment by nitaliano** [comment]
For the long term we are going to use the native SDKs to handle the geolocation stuff for us except they both behave differently right now so what I'm recommend is if something needs to work cross platform at the moment use the geolocation from RN instead

**Comment by kristfal** [comment]
Closing this one. If we want proper cross-platform behaviour, we'll should handle geolocation camera and location updates from the RN side.
