### ISSUE TITLE
[Android] MapView ContentInset not working

### ISSUE THREAD

**Issue by kristfal** [nitaliano/react-native-mapbox-gl#849]
The following props works as expected on iOS, where the compass is moved 64 px down from its initial position. However, it doesn't affect the compass on Android:

```js
      <MapboxGL.MapView
        compassEnabled={true}
        contentInset={[64, 12, 12, 0]}
      / >
```

**Comment by nitaliano** [comment]
Is this with the latest master? The new asynchronous rendering from the c++ thread might have messed up the timing here

**Comment by kristfal** [comment]
Hey, this is on the `typed-style-items` branch.

**Comment by nitaliano** [comment]
Cool, that was branched off lastest master

**Comment by nitaliano** [comment]
Fix is in this PR https://github.com/mapbox/react-native-mapbox-gl/pull/951 we just had to scale the content insets by the devices pixel ratio, so it will now match what it looks like on iOS

**Comment by nitaliano** [comment]
Merged into master
