### ISSUE TITLE
Timing issue, annotations do not render if street name layer has delay

### ISSUE THREAD

**Issue by miracle2k** [nitaliano/react-native-mapbox-gl#85]
When the Mapbox control is rendered, I can see that it first loads the layer with the streets, then it loads a layer with the street names.

What happens is that in many cases, where loading the street name layer seems to take a bit longer, the annotations are not rendered. After I zoom into the map, the annotations appear. If I zoom into the map before the street name layer is rendered, the annotations again do not disappear.

This seems to be some sort of timing issue, and happens quite frequently for me.

Using React 0.10, react-native-mapbox-gl@0.4.1

**Comment by bsudekum** [comment]
Yes, this is a known issue in mapbox-gl-native: https://github.com/mapbox/mapbox-gl-native/issues/1675#issuecomment-137892304

**Comment by bsudekum** [comment]
This should be fixed in 0.4.2.
