### ISSUE TITLE
Is it mandatory to use android SDK 26 or higher?

### ISSUE THREAD

**Issue by hecontreraso** [nitaliano/react-native-mapbox-gl#853]
Android SDK 26 is pretty recent, and according to the [install guide](https://github.com/mapbox/react-native-mapbox-gl/blob/master/android/install.md) we need to put this SDK version. I tried to use mapbox with SDK 23, but it didn't work.

Is there any way to use mapbox with a previous version?

**Comment by nitaliano** [comment]
@hecontreraso for `compileSdkVersion` you should put `26` but you can change the `targetSdkVersion` to be `23`
