### ISSUE TITLE
scroll event propagation

### ISSUE THREAD

**Issue by Tennen** [nitaliano/react-native-mapbox-gl#856]
I have a MapView in a vertical ScrollView, when I scroll the map, and the scroll action has a vertical speed, the ScrollView will start to scroll. It seems to be a problem of scroll event propagation on android.
the version I use now is 6.0.1, but I didn't face this problem in v5.2.1.
I tried using PanResponder but it doesn't work.
does any one know how to solve it?
```
<KeyboardAwareScrollView>  
    <MapboxGL.MapView  
          rotateEnabled
          scrollEnabled
          zoomEnabled
          logoEnabled={false}
          compassEnabled
          ref={(mapRef) => {
            this.mapRef = mapRef;
          }}
          style={styles.map}
          centerCoordinate={this.state.center}
          zoomLevel={this.state.zoom}
          showUserLocation={false}
          userTrackingMode={this.state.userTrackingMode}
          onDidFinishLoadingMap={this.fitBounds}
        >
</KeyboardAwareScrollView>
```

I override the onTouchEvent of RCTMGLMapView and requestDisallowInterceptTouchEvent, it works
I will take a PR

**Comment by Tennen** [comment]
fixed by this [pr](https://github.com/mapbox/react-native-mapbox-gl/pull/861), close.

**Comment by fnusneha** [comment]
This PR causes a different issue though. Since the onTouchEvent() blindly requests to disallow intercept, even when the map is completely static, scroll events get captured in the map, and parent doesn't scroll. Outside the map, the parent container scrolls normally.

Could this be changed to a conditional disablement, where if the map is static, this does not happen?

**Comment by chfight** [comment]
I added refreshControl in ScrollView. RefreshControl is appeared when I pull the map, and the map doesn't move. 
This problem only happened in android. 
Can you help me?
