### ISSUE TITLE
textFont

### ISSUE THREAD

**Issue by jsaguiar** [nitaliano/react-native-mapbox-gl#859]
I have a `SymbolLayer` and I want to put the font bold. Since you don't provide a `fontWeight` prop I was thinking in achieving the same result using your `textFont` prop:
According to this: 
[fonts]( https://github.com/react-native-training/react-native-fonts
)
I should be able to  use `textFont: ["HelveticaNeue-Bold"]` or even `textFont: ['Arial']` but both fails

**Comment by kristfal** [comment]
Map fonts behave differently than RN fonts. You'll need to add your intended [FontStack](https://www.mapbox.com/mapbox-gl-js/style-spec/) to the map source style before you can use them in `SymbolLayers`. To do so:

1) Create your custom map style on mapbox.com and add any font you'd like to use in the map
2) Use your custom map style in RN 
3) Use `textFont` as you describe in new layers
