### ISSUE TITLE
Can't run example in branch v6 and can't run Mapbox SDK in a new project

### ISSUE THREAD

**Issue by AndreaZanuccoli** [nitaliano/react-native-mapbox-gl#862]
I follow the instructions in the git to run the example in v6 branch of the git, when i run 'npm i' it's result the following error:
`> react-native-mapbox-gl-demo@0.0.1 preinstall C:\Users\zanu9\WebstormProjects\react-native-mapbox-gl-6\example
> npm run pack:gl

> react-native-mapbox-gl-demo@0.0.1 pack:gl C:\Users\zanu9\WebstormProjects\react-native-mapbox-gl-6\example
> ./scripts/npm_pack_rngl.sh

"." non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-mapbox-gl-demo@0.0.1 pack:gl: `./scripts/npm_pack_rngl.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-native-mapbox-gl-demo@0.0.1 pack:gl script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zanu9\AppData\Roaming\npm-cache\_logs\2017-12-12T08_26_28_685Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-mapbox-gl-demo@0.0.1 preinstall: `npm run pack:gl`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-native-mapbox-gl-demo@0.0.1 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zanu9\AppData\Roaming\npm-cache\_logs\2017-12-12T08_26_28_733Z-debug.log`

**Comment by nitaliano** [comment]
@andreamazz use `master` instead of `v6` the README was outdated I just opened a PR to remove switch to the `v6` branch
