### ISSUE TITLE
onDidFinishRenderingMap is not called

### ISSUE THREAD

**Issue by henrikra** [nitaliano/react-native-mapbox-gl#863]
`onDidFinishRenderingMap` is not called on Android at all. On otherhand `onDidFinishRenderingMapFully` is firing 🤔

**Comment by nitaliano** [comment]
The Android SDK doesn't seem to fire all the events that we get in the iOS SDK

**Comment by henrikra** [comment]
Which are those?

**Comment by nitaliano** [comment]
I'll post a list here, recently I've been logging all the statements trying to figuring out why we don't get the events bubbling up to us, I've debugged all the way to the C++ and we just never see certain events. Even the case with the region did change that's also suppose to fire once, but on Android it fires anytime the camera moves. 

The end goal here will be using the iOS SDK as the source of truth and start polyfilling the Android side of things to make this stuff work better cross platform. We might also stop exposing events that don't work cross platform.

**Comment by nitaliano** [comment]
@henrikra what version are you on? I'm actually seeing the events work way better in SDK 5.2.0. It seems like every event is firing now but the one that you mentioned, full log dump https://gist.github.com/nitaliano/f3d03bd846d176abadfaef3e15a1ffef

**Comment by henrikra** [comment]
We are using 6.0.1

**Comment by hernanmateo** [comment]
As far as I know I'm receiving this events on Android and mapbox 6.0.2:
```
    REGION_WILL_CHANGE
    REGION_WILL_CHANGE_ANIMATED
    REGION_IS_CHANGING
    REGION_DID_CHANGE
    REGION_DID_CHANGE_ANIMATED
    DID_FINISH_LOADING_MAP
    WILL_START_RENDERING_FRAME
    DID_FINISH_RENDERING_FRAME
    DID_FINISH_RENDERING_FRAME_FULLY_RENDERED
    DID_FINISH_RENDERING_MAP_FULLY_RENDERED
    DID_FINISH_LOADING_STYLE
    
    DID_FAIL_LOADING_MAP? (I have not been able to check this because it never fails :))
```
And not receiving (just the ones I need to load content quickly):
```
    WILL_START_RENDERING_MAP
    WILL_START_LOADING_MAP
````

**Finally I have observed that events with value 15 are received but they are not handled**

**Comment by nitaliano** [comment]
@henrikra I'm going to close this out. I would file this bug with gl-native there doesn't seem like there is anything we can do to get the event to fire in this repo
