### ISSUE TITLE
[Android] onRegionDidChange is called 7 times on initial map render

### ISSUE THREAD

**Issue by henrikra** [nitaliano/react-native-mapbox-gl#864]
To reproduce make default MapView and add `onRegionDidChange` with console.log and look that on logs the event is called 7 times 😭 . Do you have @nitaliano any idea?

**Comment by nitaliano** [comment]
Yup, it just fires on every region change. I'm throttling it in my PR that will add if a user made the region change or not

**Comment by nitaliano** [comment]
I just added a console.log to the `ShowRegionDidChange` example and it's no longer being called 7 times and it's throttled in `6.0.2` mind seeing if you see the same results?

**Comment by jsaguiar** [comment]
@nitaliano "I'm throttling it in my PR that will add if a user made the region change or not" I would to love this! Is this available in current version?

**Comment by kaynz** [comment]
@jsaguiar Yes.

**Comment by nitaliano** [comment]
Closing this out as it is fixed in master
