### ISSUE TITLE
Update to Mapbox Maps Android SDK 5.2.1

### ISSUE THREAD

**Issue by henrikra** [nitaliano/react-native-mapbox-gl#868]
Can you please update Android SDK to 5.2.1? It fixes lots of bugs https://github.com/mapbox/mapbox-gl-native/releases/tag/android-v5.2.1
For example many of our users are getting this crash https://github.com/mapbox/mapbox-gl-native/issues/10303 which has been fixed in Android SDK 5.2.1 so this React Native wrapper should use it too :) @nitaliano

**Comment by nitaliano** [comment]
Yup we can get this into master today

**Comment by henrikra** [comment]
Super 💥

**Comment by nitaliano** [comment]
PR is out https://github.com/mapbox/react-native-mapbox-gl/pull/871 closing this out
