### ISSUE TITLE
Upgrade to Mapbox iOS SDK 2.0.0

### ISSUE THREAD

**Issue by 1ec5** [nitaliano/react-native-mapbox-gl#87]
Mapbox GL for iOS has been renamed Mapbox iOS SDK and reversioned as 2.0.0. There are changes other than the name change in 2.0.0. This component should be built atop the new version, to facilitate upgrading to future versions that actually do have significant changes.

/cc @bsudekum @incanus

**Comment by bsudekum** [comment]
After upgrading to `2.0.0` I'm getting the following error:

```
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lMapbox
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lMapbox is not an object file (not allowed in a library)
```

`libMapbox.a` is linked properly.

**Comment by 1ec5** [comment]
Can you push your changes to a branch so I can see what's going on on the react-mapbox-gl-native side?

**Comment by bsudekum** [comment]
Fixed via https://github.com/mapbox/react-native-mapbox-gl/pull/89
