### ISSUE TITLE
[Android] Map details are taking too long to display

### ISSUE THREAD

**Issue by josenaves** [nitaliano/react-native-mapbox-gl#870]
I could note that map details (street style) are taking too much to display when I'm downloading map packs for offline mode.

When the map packs are already downloaded, I cannot see that behaviour.

**When the map shows up**
![image](https://user-images.githubusercontent.com/137637/33950605-fe3b558e-e013-11e7-8df2-9a0aae22f1de.png)

**After some seconds**
![image](https://user-images.githubusercontent.com/137637/33950816-7c0822e4-e014-11e7-9fe0-41c59ff47076.png)

**Comment by nitaliano** [comment]
This was also reported by another developer, will take a look into it.

**Comment by onitzschke** [comment]
@nitaliano this issue is not fixed yet?

**Comment by kristfal** [comment]
Hey,

In an effort to clean out old outstanding tickets, I'm closing this one. 

We've not found any differences between the way the RN lib handles offline packs and the native libs. If you think something should be done, I propose posting in the upstream native lib repo. 

Regardless, best practice is to download offline packs when the user is aware of it, such as adding a loading indicator or toast.
