### ISSUE TITLE
flyTo doesn't exists?

### ISSUE THREAD

**Issue by CYB3RL1F3** [nitaliano/react-native-mapbox-gl#875]
Hello,

I have a real problem with your API.

I try to use the methods flyTo and zoomTo but it seems not to exists.

I setup the view like this : 
```

<MapView
        ref={mapView => { this.mapView = mapView }}
        withRef
        animated
        style={{flex: 1}}
        initialCenterCoordinate={{
          longitude: this.props.coordinates.longitude,
          latitude: this.props.coordinates.latitude - 0.0003
        }}
        initialZoomLevel={this.props.zoom}
        styleURL={this.props.dark ? this.darkStyleURL : this.styleURL}
        attributionButtonIsHidden
        logoIsHidden={true}
      >
         {/* my annotations */}
 </MapView>

```
and try to access that way : 

`this.mapView.flyTo(newCoordinates);`

But I get "flyTo is not a function".

In your demos you have this.map.flyTo, but never explained if "this.map" is a ref of the mapView (like I did) or something else ? Documentation about this method is absolutely not clear.

In the console "flyTo", "moveTo" and "zoomTo" seem not existing in the mapView object.

Could you help me ?
Thanks a lot

**Comment by nitaliano** [comment]
@CYB3RL1F3 Refs are built into React https://reactjs.org/docs/glossary.html#refs so it's just referring to the React component which has those methods on it `MapboxGL.MapView` what version of the repo are you using? The props that you posted being added to the Map are different than our v6 API

**Comment by nitaliano** [comment]
Closing this out, just post back in here and I'll keep responding

**Comment by sharadkatre19** [comment]
I am getting the same error. I have created reference same as is the example. The other function like getZoom(), getCenter() are working fine but when I try to use fitBounds()/ moveTo()/ flyTo()

It gives the same error:
**... is not a function**

**Comment by nixolas1** [comment]
So the camera methods should be run on the <Camera ref=... ? not the MapView?
Cant get this working either.

**Comment by jomaint** [comment]
Kinda hackish but I did it this way: 

``` 
this.setState({
    jumpTo: {
        center: [lng,lat],
        zoom: 13
    }
})
```

```
render() {
    ...
    let extraCameraProps = {};
    if (this.state.jumpTo) {
        extraCameraProps.centerCoordinate = jumpTo.center;
        extraCameraProps.zoomLevel = jumpTo.zoom;
        extraCameraProps.animationDuration = 1000;
    }
    return (
        <MapboxGL.MapView ...>
            <MapboxGL.Camera
                {...extraCameraProps}
                followZoomLevel={12}
                animationDuration={2000}
                followUserLocation={false} />
        </MapboxGL.MapView>
    );
}
```
