### ISSUE TITLE
Offline region limitations

### ISSUE THREAD

**Issue by jessisena** [nitaliano/react-native-mapbox-gl#877]
Hi,

I'm trying to use the offline functionality. For that, I've created a style in Mapbox Studio, that is consuming my own tileset source (this tileset is big, about 340MB, and the style has around 657 layers.).

When I’m using  this style online, I can visualize it from my app without any problem, but when I try to create an offline region with it, it is not working, even though if the bounds of the region are small ones, and the zoom levels are only 1 or 2. When the app tries to download the area I get a 404 Error:

`OfflinePack {pack: {…}, _metadata: null} {name: "1513001797722", message: "HTTP status code 404"}`

I've tried to create smaller styles from the same tileset source, with less layers and/or layers with less information, and in some cases it has worked. I've been reading about the offline limitations in the "Help" section but  it doesn't say anything about a limitation of the layers in the style. It only talks about a tile ceiling limitation (of 6.000 tiles), and in my tests I'm not exceeding it.

Anybody else has experimented something similar, or has any other information about it? (limititations, etc)

This is my style, in case somebody wants to try it:
mapbox://styles/geostarters/cjb6oaftb2rsb2rnujha17o30

And this is how I declare the offline region:

```
const options = {
    name: name, //this.state.name,
    styleURL: STYLE_SOURCE_URL, 
    bounds: [[2.19177, 41.91045], [0.81848,  41.23238]],//[[neLng, neLat], [swLng, swLat]]
    minZoom: 10,
    maxZoom: 13,
  };
```

```
  // start download
  MapboxGL.offlineManager.createPack(
    options,
    (offlineRegion, downloadStatus)=>console.log(offlineRegion, downloadStatus.percentage),
    (offlineRegion, err) => console.log(offlineRegion, err)
  );
```

Thanks,

**Comment by nitaliano** [comment]
I will try it and let you know what happens.

@jessisena I just tried your style url and I can't get anything to render, did you happen to make it public? When I try one of my custom style urls I am seeing it and I see the offline region being created. The 404 is coming from our backend saying that it can't find the resource, so I would be interested in getting your style url to work locally so I can debug it further

**Comment by jessisena** [comment]
Hi,

Thanks for trying it! I've just checked it again, and it's public. Actually, it seems that the "share url", is working too:

`https://api.mapbox.com/styles/v1/geostarters/cjb6oaftb2rsb2rnujha17o30.html?fresh=true&title=true&access_token=pk.eyJ1IjoiZ2Vvc3RhcnRlcnMiLCJhIjoiMGNxekwxayJ9.sE1YC8Zxwzjh4CQeZiZN_g#10.3/42.166617/1.883839/167`

And this is my code in the app, to see my style online:

```
    <View style={styles.container}>
      <MapboxGL.MapView
          zoomLevel={7}
          centerCoordinate={[1.89230, 42.12620]}
          style={styles.matchParent}
          onDidFinishLoadingMap={this._onDidFinishLoadingStyle}
          styleURL= {STYLE_SOURCE_URL}> 
      </MapboxGL.MapView>
    </View>
```

Take into account that my tileset only has info from Catalonia (Spain). So, you need to center the map in a very concrete area, otherwise you are not going to be able to see anything.

Can you see something if you use my style, with my centerCoordinate params ([1.89230, 42.12620])?


And here's a screenshot of my style, from my device:
![example_style](https://user-images.githubusercontent.com/3327279/34037668-fe2336a8-e189-11e7-9586-85459727b975.jpg)


If you need anything else to make the test, just tell me.

Thanks!

**Comment by jessisena** [comment]
Hi Nick, 

have you been able to try it? I've just received an email from the support department with a more detailed explanation about the use limitations, and definitely that is not the problem.

I'd really appreciatte any idea about how to solve this problem, in order to be able to use this SDK in my project.

Thanks!

**Comment by nitaliano** [comment]
@jessisena I haven't been able to look into it again yet. I've set some time aside to look into it tomorrow I will let you know what I find.

**Comment by kristfal** [comment]
Hey,

in an effort to clean out old tickets, I'm closing this one. This library is no longer maintained by Mapbox, but we're more than happy to accept PRs to fix your issue.
