### ISSUE TITLE
Remove old package from npm?

### ISSUE THREAD

**Issue by henrikra** [nitaliano/react-native-mapbox-gl#882]
I mean could this be removed? https://www.npmjs.com/package/react-native-mapbox-gl

**Comment by nitaliano** [comment]
Eventually it could be I wouldn't want to remove it just yet in case people are still using that in their projects.

**Comment by henrikra** [comment]
What about at least adding info that it is deprecated use xxx instead?

**Comment by nitaliano** [comment]
Just got access to the old npm repo it shall be updated

**Comment by nitaliano** [comment]
Added a message to the top of the old package https://www.npmjs.com/package/react-native-mapbox-gl
