### ISSUE TITLE
react-native link support

### ISSUE THREAD

**Issue by digitaldavenyc** [nitaliano/react-native-mapbox-gl#886]
The installation for this library has always been quite error prone, it's the most problematic library we deal with by far. Simplifying the build and supporting `react-native link` would really improve the overall developer happiness using RNMBGL. Is this planned in any future releases?

**Comment by nitaliano** [comment]
rnpm does not work out of the box unfortunately we would need some post scripts to run after `react-native link` to allow us to do some custom steps which rnpm just does not support. That said once have more time we will look into making the install steps as easy as possible.

**Comment by nitaliano** [comment]
PR has been open for this https://github.com/mapbox/react-native-mapbox-gl/pull/1123
