### ISSUE TITLE
queryRenderedFeaturesAtPoint for MapboxGL.LineLayer?

### ISSUE THREAD

**Issue by butchmarshall** [nitaliano/react-native-mapbox-gl#887]
Is it expected that queryRenderedFeaturesAtPoint does not work when querying for a MapboxGL.LineLayer?  It works fine for me when querying for MapboxGL.CircleLayer.

queryRenderedFeaturesInRect does find a MapboxGL.LineLayer, but how are we supposed to know how big to make our hitbox without knowing the size of the line?

**Comment by nitaliano** [comment]
The default hitbox on the onPress for the ShapeSource is `44x44` pixels, which Apple recommends as a hitarea(just needs to be large enough for a finger). Anytime you're interacting with the layers on the Map I would recommend using queryRenderedFeaturesInRect an queryRenderedFeaturesAtPoint really only works well with a mouse.
