### ISSUE TITLE
Callback onFlyToComplete never triggered

### ISSUE THREAD

**Issue by nlindroos** [nitaliano/react-native-mapbox-gl#890]
`flyTo` seems to execute perfectly, the completion callback never gets called however. Tested on both iOS and Android, the callback gets triggered on neither. Let me know if you need further info.

```jsx

flyTo = () => {
  this.map.flyTo([24.941487, 60.170918]);
}

flyToComplete = () => {
  console.warn('flyToComplete');
}
```
```jsx
<TouchableOpacity style={{marginTop: 50}} onPress={this.flyTo}>
  <Text>Fly</Text>
</TouchableOpacity>
<MapboxGL.MapView
  ref={(ref) => { this.map = ref; }}
  style={{flex: 1, alignSelf: 'stretch'}}
  onFlyToComplete={this.flyToComplete}
/>
```

```json
"@mapbox/react-native-mapbox-gl": "^6.0.1",
"react-native": "0.50.4",
```

**Comment by nitaliano** [comment]
We've moved away from callbacks and all map methods return a promise now you can just use async await on the method calls.

https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/FlyTo.js#L53

**Comment by nlindroos** [comment]
OK, cool. Thanks for your response!
