### ISSUE TITLE
[ANDROID] v6.0.1 and v6.0 map is black

### ISSUE THREAD

**Issue by GuillotJessica** [nitaliano/react-native-mapbox-gl#891]
Hello,
my map turned black for no reason
I checked the MapboxGL.setAccessToken [there](https://api.mapbox.com/v4/mapbox.emerald/page.html?access_token=<accessToken>) and it work fine
I haven't edit the map for a while
I turned it to v6.0.1 afterward to implement the 
` textureMode={true}`
but doesn't change a bit to this black map
here is my package.json regarding the issue

> 
>     "@mapbox/react-native-mapbox-gl": "^6.0.1",
>     "react": "16.0.0",
>     "react-native": "0.50.4",
I have no idea what to do and where to look at...
any idea is most welcome

**Comment by nitaliano** [comment]
texture mode support is only in master not 6.0.1

**Comment by GuillotJessica** [comment]
you mean 6.0.2-rc1 ?

**Comment by nitaliano** [comment]
@GuillotJessica texture mode support was just merged in recently and has not gotten an npm publish yet. We will be publish a new version to npm by the EOD today `6.0.2`. For the black screen I have seen that calling the offlineManager and something in the SDK get's stuck, and you'll see a black screen afterwards. That has since been resolved in gl-native and should be resolved on current master

**Comment by GuillotJessica** [comment]
thanks a lot for helping resolving my issues anyway, hope for the the soonest,
got it back on track by downgrading to 6.0.0

**Comment by nitaliano** [comment]
@GuillotJessica `6.0.2` is published now. Also I ran into a black screen on the older version and noticed the logs were saying I wasn't connected to the internet. I restarted `adb kill-server` and closed out the sim, went into Android Studio cleaned the project and built it again and the problem went away.

**Comment by butchmarshall** [comment]
Yep, I had a initial app load which was calling `MapboxGL.offlineManager.getPacks();`

Every map load was getting a black screen.  Everything works when this method is not called.

**Comment by hampelm** [comment]
I'm experiencing the same issue as @butchmarshall on 6.0.2: if I have a component that calls `MapboxGL.offlineManager.getPacks()`, the next map I try to instantiate will be entirely black. If I disable the `getPacks` call, maps load correctly.  When I downgrade to 6.0.1, it works as expected. 

A snip of the component that loads the offline map packs in the (highly likely) chance I'm just using it incorrectly: 

```
class OfflineMaps extends Component {
  constructor(props) {
    super(props)
    this.state = {
      loading:      true,
      offlinePacks: [],
      error:        false,
    }

    this.handleAdd = this.handleAdd.bind(this)
    this.getPacks = this.getPacks.bind(this)
  }

  ...
  getPacks() {
    this.setState({
      loading: true,
    })
    MapboxGL.offlineManager
      .getPacks()
      .then(response => {
        this.setState({
          loading:      false,
          error:        false,
          offlinePacks: response,
        })
      })
      .catch(error => {
        this.setState({
          error,
        })
      })
  }

  componentDidMount() {
    this.getPacks()
  }
  ...
}
```

**Comment by nitaliano** [comment]
@hampelm you're not doing anything wrong I can reproduce this behavior and I'm actively looking into it today

**Comment by nitaliano** [comment]
Potential fix is out in this PR https://github.com/mapbox/react-native-mapbox-gl/pull/949 if anyone wanted to give it a test

**Comment by hampelm** [comment]
Thank you for the quick response! I'm on deadline for a project this afternoon but will give it a shot asap.

**Comment by williamdarkocode** [comment]
Is this issue solved?!
