### ISSUE TITLE
[iOS]Annotation points are being rendered below the Raster Layer 

### ISSUE THREAD

**Issue by grantyi** [nitaliano/react-native-mapbox-gl#893]
In the latest version of the master branch, annotation points on iOS are being rendered below the raster layer despite being rendered after the layer. This does not occur on Android.  
![img_0030](https://user-images.githubusercontent.com/6563972/34182397-11f6a374-e4e4-11e7-96cf-b61309a9885c.jpg)

**Comment by nitaliano** [comment]
thanks for reporting, one question are those points from the `RCTMGLPointAnnotation` or `SymbolLayer` component?

**Comment by grantyi** [comment]
They are RCTMGLPointAnnotations. I ended up switching to using SymbolLayers and they work perfectly

**Comment by nitaliano** [comment]
@grantyi SymbolLayers are the way to go, Annotation Views are more of a legacy API but we want them to work as expected thanks again for reporting!

**Comment by kristfal** [comment]
Hey,

in an effort to clean out old tickets, I'm closing this one.
