### ISSUE TITLE
Please do not use this package!

### ISSUE THREAD

**Issue by JedrzejMajko** [nitaliano/react-native-mapbox-gl#894]
This package is broken.

It is very slow, breaks react constantly (multiple renders are done at the same time), do not allow more than one map at the same time, can hang <<on idle>> if too many points were displayed before (memory issues), same events on ios and android behaves differently... everything is in CLOSED issues.

We tested it on database with over 5000 points that were rendered 30 at any given area.

Unfortunately, they way issues for this package are managed (if new version arrives, old issues are closed without checking) is flawed and created environment that is unsuitable for anything else than hobby use.

Hope you can improve someday.

**Comment by nitaliano** [comment]
Please in the future post constructive issues to not only help track down bugs but it will benefit other members in the community that might be running into a similar issue.

We have two examples of rendering well over 5000 datapoints
* First example is done with clustering - https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/EarthQuakes.js
* Second example is done with data driven styling an this has an extremely large dataset being rendered to the screen https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/DataDrivenCircleColors.js

As for not being able to put multiple Maps at one time it's totally possible we even have an example of rendering two maps at once.
https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/TwoByTwo.js

If you're referring to them being stacked on top of each other this is an Android distinction between View types I would recommend you read more into them [GLSurfaceView](https://developer.android.com/reference/android/opengl/GLSurfaceView.html) and [TextureView](https://developer.android.com/reference/android/view/TextureView.html) to learn about the pros and cons of each View type. GLSurfaceView give's you insane performance benefits, but you cannot have two GLSurfaceView on top of each other in one Activity and React Native runs in a single Activity. To get around this we also have support for a TextureView will will function more similar to what you see on iOS. With current master all you need to do is set `textureMode={true}` on the MapView and they stack.

There are some differences between some events and location behaviors between both platforms and that is somethings we are actively fixing, and the location fixes will be landing in a PR this week.

For the issues I can understand the frustration with us closing out all the `v5` issues, but that was an unsupported codebase(mentioned in the README) and we will not be spending anytime supporting an old version of the codebase that was never officially supported. `v6` is a complete rewrite of the library and we actively work on those issues, so if you're running into any issues feel free to post them with reproduction steps.

You can also check our [releases](https://github.com/mapbox/react-native-mapbox-gl/releases) to see what's moving in each release and we break down what bugfixes, feature, and breaking changes have been made per release. We also have [Github project boards](https://github.com/mapbox/react-native-mapbox-gl/projects) setup so you can see what will make it into a release once we plan it.

Also make sure that you are using the Mapbox scoped npm package https://www.npmjs.com/package/@mapbox/react-native-mapbox-gl. There is another one floating around without the Mapbox npm scope from a time when this was not under the Mapbox org.

If you need any help with implementation details feel free to ping me on Discord or Gitter would be happy to help 😄
