### ISSUE TITLE
attributionEnabled docs are inadequate

### ISSUE THREAD

**Issue by friedbunny** [nitaliano/react-native-mapbox-gl#898]
The docs for the `attributionEnabled` prop say how to circumvent the iOS SDK’s attribution-disabled exception without actually telling the developer why it exists. The docs here should tell developers _why_ they need to add the plist flag, not just that they should.

More background here: https://github.com/mapbox/react-native-mapbox-gl/issues/291#issuecomment-189669989

https://github.com/mapbox/react-native-mapbox-gl/blob/f3b8c8f35db2f35c3058a9eb54ea8f7958e33622/docs/docs.json#L1279

/cc @nitaliano

**Comment by nitaliano** [comment]
@friedbunny thanks for opening

If you ever had time to review more of the iOS parts of the repo it would be much appreciated!
