### ISSUE TITLE
RasterLayers are rendered at wrong zoom level on iOS

### ISSUE THREAD

**Issue by RNMBuser** [nitaliano/react-native-mapbox-gl#899]
1. It seams that MapboxGL.RasterLayer uses the wrong (to low!) zoom level. 

2.  RasterLayer  must be nested inside a RasterSource tag. If they are side by side, nothing is rendered (try to move MapboxGL.RasterLayer outside the source!).

3. sourceID has no effect. It doesn't matter what you set it: if the layer is inside the source tag, it'll be rendered. If not, it will not. Also, it cannot reference a source on the stylesheet.

`

    import React, { Component } from 'react';
    import MapboxGL from '@mapbox/react-native-mapbox-gl';
 
    const accessToken = 'MY_TOKEN';
    MapboxGL.setAccessToken(accessToken);

    export default class AAMapMB extends Component {
    render() {

        return (
            <MapboxGL.MapView
                style={this.props.style}
                zoomLevel={5.2}
                centerCoordinate={[-75.789, 41.874]}
            >
                <MapboxGL.RasterSource id="osm" url="https://a.tile.openstreetmap.org/{z}/{x}/{y}.png">
                    <MapboxGL.RasterLayer id='osmLayer' sourceID='osm' />
                </MapboxGL.RasterSource>    
            </MapboxGL.MapView>
        );
    }
    }`

**Comment by nitaliano** [comment]
Layers need to be inside of sources by default and the sourceID is passed down from the Source parent to the layer so it's not something you would need to set.

Sorry, I'm not sure I'm following would you mean by using the wrong zoom level and it cannot reference a source on the stylesheet Would you mind going into more detail?

**Comment by RNMBuser** [comment]
1. Suppose I have a stylesheet that contains a few Raster sources. I wish to alternate between the raster layers, and select the layer I want.

Do we have any access to the visibility of the layers? What I tried to do is have a layer in RN that references the sources on the stylesheet. This seams impossible. Do you have a suggestion?

2. The MB style sheet separates between sources and layers, but we do not. This may have an impact on vector styles that use several sources. I suggest seperating them. 

3. I tried to run the above example, but the resolution is very low. Could you please try to run it?

**Comment by kristfal** [comment]
Hey,

in an effort to clean out old tickets, I'm closing this one. You should be able to toggle visibility of raster layers by using the visible prop on the source.
