### ISSUE TITLE
Setting a coordinates to jump to

### ISSUE THREAD

**Issue by joshbedo** [nitaliano/react-native-mapbox-gl#9]
Wondering if a property already exists to jump to a location or specific coordinates. I want to add a search bar at the top where a user can enter coordinates and the map will jump to them. If its not already implemented i would like to help but need some guidance :)

**Comment by bsudekum** [comment]
@joshbedo Not yes, still need to implement this. In my head it will look something very similar to how it's happening in react-native with passing an [object through on the region param](https://github.com/facebook/react-native/blob/master/React/Views/RCTMapManager.m#L45-L48).

**Comment by 1ec5** [comment]
`MKMapView` lets you to set the coordinates using a `MKCoordinateRegion` struct, which `MGLMapView` doesn’t support yet (mapbox/mapbox-gl-native#1092). However, `MGLMapView` does have [`-setCenterCoordinate:animated:`](https://github.com/mapbox/mapbox-gl-native/blob/master/include/mbgl/ios/MGLMapView.h#L102) and [`-setCenterCoordinate:zoomLevel:animated:`](https://github.com/mapbox/mapbox-gl-native/blob/master/include/mbgl/ios/MGLMapView.h#L122). To support [inspectables in Interface Builder](https://github.com/mapbox/mapbox-gl-native/wiki/Installing-Mapbox-GL-for-iOS#using-interface-builder), Cocoa developers can import MGLMapView+IBAdditions.h and set the [`latitude`, `longitude`, and `zoomLevel`](https://github.com/mapbox/mapbox-gl-native/blob/master/include/mbgl/ios/MGLMapView%2BIBAdditions.h#L20-22) properties individually. These properties would be very easy to wrap for React Native support.

**Comment by 1ec5** [comment]
Looks like @bsudekum addressed most of this request in #11: the center coordinates can be customized, but not the zoom level yet.

**Comment by bsudekum** [comment]
Going to leave this issue open. https://github.com/bsudekum/react-native-mapbox-gl/pull/11 does not allow for animation and requires a full redraw.

**Comment by bsudekum** [comment]
done

**Comment by ookoy023** [comment]
jhvjh
