### ISSUE TITLE
Annotation image doesn't update 

### ISSUE THREAD

**Issue by cmhsu** [nitaliano/react-native-mapbox-gl#90]
I'm setting annotation image based on a attendees property. different attendee counts gets different annotation images. However, this only works when the app loads. The MapboxGLMap component has annotations={this.state.annotations} as a property. 

I'm setting this.state.annotations to an empty object, and then re-fetching the annotations from a database after an attendee count change. However, the map displays the exact same annotation images as before. It only changes when I reset the app. Is there a fix for this? I can see all the annotations disappear for a split second when I set this.state.annotations to an empty object. Then a split second later the map adds all the annotations back, but with the exact same annotation images instead of the updated images.

**Comment by bsudekum** [comment]
Can you update to [`react-native-mapbox-gl@0.4.2`](https://github.com/mapbox/react-native-mapbox-gl/releases/tag/0.4.2) and see if the error still persists?

**Comment by cmhsu** [comment]
So I updated, and the error is still there.

**Comment by bsudekum** [comment]
You're going to have relink `node_modules/react-native-mapbox-gl/RCTMapboxGL.xcodeproj`.

**Comment by cmhsu** [comment]
Sorry I meant the marker error is still there. The markers don't change to the new marker images.

**Comment by cmhsu** [comment]
Has anyone else experienced this?

**Comment by incanus** [comment]
Are you using different `id` properties for the annotations in question?

**Comment by cmhsu** [comment]
Yup I'm setting each annotation's id to its unique MongoDB id.

**Comment by cmhsu** [comment]
I fixed this issue by unmounting the map completely based on a state variable. Looks like you can't edit the annotation image unless you unmount and remount the whole map.

**Comment by incanus** [comment]
> Yup I'm setting each annotation's id to its unique MongoDB id.

Any annotations with the same image should be using the same id for max performance. This ties id to image texture uploaded to the GPU. 

That said, I'm not sure offhand if what you are seeing in this project is planned or not, but in core Mapbox GL, it is not yet intended to be able to change imagery for an annotation at runtime — it would require a remove and re-add.

**Comment by bsudekum** [comment]
Fixed in https://github.com/mapbox/react-native-mapbox-gl/pull/131
