### ISSUE TITLE
onRegionDidChange isUserInteraction: false on first map move

### ISSUE THREAD

**Issue by hannta** [nitaliano/react-native-mapbox-gl#901]
When I first time move the map, event `onRegionDidChange` is fired but the property `isUserInteraction` is `false`. Even I swipe the screen to move the map myself.

If I make some map "manipulation", like calling `setCamera` before the first map move, this issue is not reproducing. So it looks like always first `onRegionDidChange` event is triggered with `isUserInteraction: false`, no matter what was the actual cause of the map move.

react-native-mapbox-gl: 6.0.2
react-native: 0.50.3
device: android

**Comment by nitaliano** [comment]
I'm assuming this is happening due to android not sending the very first region event

**Comment by nitaliano** [comment]
This is fixed in this PR https://github.com/mapbox/react-native-mapbox-gl/pull/897

**Comment by nitaliano** [comment]
Merged into master, closing out feel free to reopen if you run into any issues
