### ISSUE TITLE
MapBox missing streets and blocks in map

### ISSUE THREAD

**Issue by SandeshBG** [nitaliano/react-native-mapbox-gl#902]
I want to use a mapbox for a map based application. But mapbox is missing few small streets in certain areas. It is not showing blocks and building correctly as in google map. What is the solution to this?

**Comment by nitaliano** [comment]
You would be able to add those street names to OpenStreetMaps and they would be able to flow into our system. Have you ever used it before?

**Comment by SandeshBG** [comment]
No, I have never used OpenStreetMaps before. Thanks for the help..

**Comment by nitaliano** [comment]
I'll look for some tutorials this could actually be good to have in the README

**Comment by nitaliano** [comment]
@SandeshBG give this a try https://www.mapbox.com/feedback/
