### ISSUE TITLE
[Offline] getPackStatus() function visibility

### ISSUE THREAD

**Issue by josenaves** [nitaliano/react-native-mapbox-gl#904]
The current implementation of getPackStatus() is only accessible through OfflineManager (using createPack progressListener callback - solved in issue [829](https://github.com/mapbox/react-native-mapbox-gl/issues/829))

It would be very good if we could access the status directly. For instance, I need to check if all map packs were successfully downloaded. I cannot depend on that callback.

What do you think @nitaliano ?

**Comment by nitaliano** [comment]
You should be able to achieve this by doing

```
const packs = await MapboxGL.offlineManager.getPacks();

for (let pack of packs) {
    const status = await pack.status();
}
```

**Comment by kristfal** [comment]
Closing as issue is resolved.
