### ISSUE TITLE
[ANDROID] App crashes when kill the app using task manager and try to open it again

### ISSUE THREAD

**Issue by Jose4gg** [nitaliano/react-native-mapbox-gl#906]
I have a very weird behavior right now. I'm using react-native-navigation and this package, right now when I close the app using the task manager and try to open it again it crashes. The weird thing is that it only happen if I render the Map just one time, if I don't render the map I can kill the app, open it again and everything works fine, but if I render the map, kill the app, try to open it again I receive a react-native-navigation white screen because of a Timeout to open the app. 

My thoughts are maybe the map don't get kill completely when the component is dismounted. Any thoughts on this?

**Comment by Jose4gg** [comment]
Similar Issue: #878

**Comment by parkdcom** [comment]
@Jose4gg  Does this issue still occur when you add textureMode={true} to your MapView?

I was experiencing the exact same issue you described above. If it does, we have some chance of fixing this problem without turning textureMode on.

**Comment by Jose4gg** [comment]
I don't have that property added. @getconcar

**Comment by parkdcom** [comment]
No I mean you should try adding that property and see if you're still experiencing the bug.

**Comment by Jose4gg** [comment]
That makes my Mapview goes blank for no reason... @getconcar

**Comment by nitaliano** [comment]
@Jose4gg try master now, it seems like updating the Mapbox Android SDK fixed this issue. I just tried this on my Pixel with 6.0.2 and it crashes. With master I cannot reproduce it.

**Comment by nitaliano** [comment]
closing this out this is not an issue anymore
