### ISSUE TITLE
Annotations sometimes does not load at startup, until you zoom

### ISSUE THREAD

**Issue by olofd** [nitaliano/react-native-mapbox-gl#91]
Can this be a issue upstream?
https://github.com/mapbox/mapbox-gl-native/issues/1675

Annotations will not load.
Even more prominent if you remove the 100ms delay the library has in place for updating
annotations.

**Comment by bsudekum** [comment]
yep this is an upstream issue and will be fixed when mbgl-native v3.0.0 is incorporated.

**Comment by bsudekum** [comment]
This has been fixed.
