### ISSUE TITLE
Any way to use maxBounds?

### ISSUE THREAD

**Issue by max-prokopenko** [nitaliano/react-native-mapbox-gl#911]
Is there any way to use maxBounds to limit the map? It's available in mapbox-gl-js, but I couldn't find any information about it for react-native-mapbox-gl

Or is there any other way to limit map to a certain area?

**Comment by kaynz** [comment]
Please check #498

**Comment by max-prokopenko** [comment]
@kaynz Thanks for the reply! 

The solution provided in #498 doesn't really solve the issue, as a user is able to scroll as far as they want even with the minZoomLevel set.

Here is an example of what I'm trying to achieve https://www.mapbox.com/mapbox-gl-js/example/restrict-bounds/  

Any ideas?

**Comment by nitaliano** [comment]
This is something we can look into adding as a feature, there is no property in gl-native like in gl-js to restrict the bounds like this. What we can do in the native code is before we move the camera check the the bounds we are going to move to our valid like this example for iOS https://www.mapbox.com/ios-sdk/examples/constraining-gestures/ so the api will be similar to gl-js from the JS API of this repo and we polyfill the functionality on the native side

**Comment by nitaliano** [comment]
Closing this out in favor off https://github.com/mapbox/react-native-mapbox-gl/issues/498
