### ISSUE TITLE
error while installing  yarn add @mapbox/react-native-mapbox-gl

### ISSUE THREAD

**Issue by PManager1** [nitaliano/react-native-mapbox-gl#919]
![image](https://user-images.githubusercontent.com/1026325/34471026-9694b914-eef2-11e7-9d6e-2759739cd97d.png)

ya is my shortcut for comand yarn add 
![image](https://user-images.githubusercontent.com/1026325/34471027-9c30040a-eef2-11e7-9b5b-f112572161c5.png)

![image](https://user-images.githubusercontent.com/1026325/34471038-bf3cc47e-eef2-11e7-9c42-4408b75c0aee.png)

**Comment by mtt87** [comment]
What version of `node` are you running?
If you install it with `npm` does it work?

I use `yarn 1.3.2` as well and didn't have this issue 🌱

**Comment by nitaliano** [comment]
I just tried as well and I'm not seeing the issue. I'm running

```
node - 8.1.2
npm - 5.0.3
yarn - 1.3.2
```

I would try to remove your `node_modules`, `package-lock.json`, and `yarn.lock` and try to install again
