### ISSUE TITLE
Support for Android

### ISSUE THREAD

**Issue by tiagofassoni** [nitaliano/react-native-mapbox-gl#92]
Now that React-Native for Android has been launched, are there any plans to support it?

**Comment by bsudekum** [comment]
Yep, will begin work soon.

**Comment by tiagofassoni** [comment]
Thanks!

**Comment by mvaivre** [comment]
Amazing, can't wait!

**Comment by bsudekum** [comment]
All done, check it out

**Comment by tiagofassoni** [comment]
Thanks!
