### ISSUE TITLE
offlineManager : I don't have any clue how to use it...

### ISSUE THREAD

**Issue by CYB3RL1F3** [nitaliano/react-native-mapbox-gl#926]
Hello,

Refering to the documentation, I understood how to create a pack, and how to get it, but there is something missing in the documentation or something I don't really get : how to use it with a map ?

I mean, I don't have any clue about the moment when I have to call it, etc... I tried in the render method, but it crashes... Anyway, the idea is to create a pack if the app is online, and retrieve it when it is off.... But I don't know if I have to give any property the <Mapbox.MapView> to load the offline map or something, which moment do I call the getPacks, and what do I do with the result, etc... :/  

I tried to find examples, but didn't find any concrete one... 

Could someone explain me how to use it concretely ?

Thanks a lot...

**Comment by nitaliano** [comment]
@CYB3RL1F3 we have a gitter channel if you want to join it to ask any questions about the repo https://gitter.im/react-native-mapbox-gl/Lobby?source=orgpage.

When you actually create an offline pack, you don't need to do anything to use it that is taking care of for you automatically. When you're creating a pack what is happening is we our downloading the vector tiles from our backend APIs and then storing them locally on the device in combination with a database, so at a high level if you navigate to that region you'll be able to see those tiles while offline without needed to do anything.

You can follow along in this example for where best to use it in the code https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/CreateOfflineRegion.js

I'm going to close this out, but feel free to comment back in this issue to continue the discussion if I did not fully answer your question.

**Comment by 386sx** [comment]
Sorry for reopening this but to me the documentation is not really clear. Is it true that without an 'enterprise' plan you can just create offline packs with up to 6000 tiles? Is there any other way of creating a layer like on mapbox-gl or leaflet with locally stored tiles? (in best case vector tiles)
