### ISSUE TITLE
Get user coordinates

### ISSUE THREAD

**Issue by MrHazimAli** [nitaliano/react-native-mapbox-gl#928]
Is there possible ways to retrieve user current location coordinate that will give latitude and longitude ?

**Comment by nitaliano** [comment]
@MrHazimAli you can do this for now https://github.com/mapbox/react-native-mapbox-gl/issues/854#issuecomment-350609512 I'm not sure if this repo should be sending location updates over the bridge, it could overload it if not handled properly.

**Comment by MrHazimAli** [comment]
Thanks @nitaliano
