### ISSUE TITLE
Support local mbtiles raster, vector or elevation/terrain tiles?

### ISSUE THREAD

**Issue by geospatialmapmashup** [nitaliano/react-native-mapbox-gl#929]
Does this library only work with MapBox hosted data or does it work with your own MBTILES local on the device. MBTILES (SQLite 3 Database) with tile_data blob containing either PNG/JPG Raster Imagery or GZipped PBF Vector Tiles or PNG Elevation Tiles?
Need Offline Disconnected for Marine/Nautical, Aviation and Offroad/OHV, Hiking, Biking, etc

**Comment by nitaliano** [comment]
@geospatialmapmashup out of the box no, you can follow along in this ticket for more information https://github.com/mapbox/mapbox-gl-native/issues/7471
