### ISSUE TITLE
clang: error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by dagatsoin** [nitaliano/react-native-mapbox-gl#93]
Hello,

I can build the test app on the simulator but not on the target device (an iPhone 4S iOS 9)

```
ld: '/Users/vikti/Library/Developer/Xcode/DerivedData/AwesomeProject-bhbftzvtsmqvqvafdragoesyqcns/Build/Products/Debug-iphoneos/libRCTMapboxGL.a(RCTMapboxGL.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7

clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

What could be wrong?

**Comment by bsudekum** [comment]
Looks like you're hitting a bitcode error. Can you follow the suggestions here and see if this fixes the error? http://stackoverflow.com/questions/30848208/new-warnings-in-ios9

**Comment by dagatsoin** [comment]
Ok, this one work. I think it would be necessary to add it to the tutorial.

Now I have another error (opened in another issue). Why is this so complicated to switch from the simulator to a real device (I know, because this IS complicated...)

**Comment by dnazarov** [comment]
I've reproduced this error when install from CocoaPods. CocoaPods makes a project with Enable Bitcode=No. Set Enable Bitcode=No at the main project resolves the problem.
