### ISSUE TITLE
Add TypeScript Support

### ISSUE THREAD

**Issue by nitaliano** [nitaliano/react-native-mapbox-gl#932]
The JS portion of this codebase is rather small, but updating it to use [flow](https://flow.org/) will help make the code more self documenting and will improve the information that we have about our data types when generating documentation

**Comment by hannta** [comment]
How about supporting typescript? I think there should be at least typescript typing's included in this lib.

**Comment by nitaliano** [comment]
@hannta if enough people want typescript support we can add support for it

**Comment by maxencehenneron** [comment]
Definitely using typescript in my project. Always added the definitions for the functions I needed manually but I would like to have a typescript support

**Comment by BurnedChris** [comment]
Typescript would be great to have for this project, unless someone would want to work on a @types file for this project?

**Comment by henrikra** [comment]
Typescript has so much more than Flow. Check for example why big company Lyft chose TS over Flow: https://eng.lyft.com/typescript-at-lyft-64f0702346ea

**Comment by nitaliano** [comment]
I love how all comments and likes for this issue are related to Typescript. One of my main concerns with using Typescript directly is we use react-docgen to help generate our docs, and it's going to be even more important once we release our html docs, Typescript is not supported out of the box.

**Comment by henrikra** [comment]
With Typescript you don't need HTML docs :P

**Comment by nitaliano** [comment]
I'm going to hold off on supporting flow for now, I've been using TypeScript more and it has been growing on me and I'm seriously thinking about moving the codebase over to TypeScript instead of flow. We would just pick another library to help us generate docs, it's not a good enough argument to hold us back from using it.

Does anyone have any strong feelings of flow over typescript?

**Comment by henrikra** [comment]
We have been using TS for some time now and it has the best so far in my JS career <3

**Comment by edwardgalligan** [comment]
Currently using react-native-mapbox-gl in a Typescript project, and maintaining custom local typings was a (very very mild) annoyance with the 6+ update (since https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mapbox__react-native-mapbox-gl doesn't exist).

To see official support would be absolutely lovely.

**Comment by ctaggart** [comment]
I need TypeScript definition files for this project. @edwardgalligan could you create a PR to here or paste in a gist? Did you build on the previous PR? https://github.com/mapbox/react-native-mapbox-gl/pull/613/files

**Comment by edwardgalligan** [comment]
@ctaggart on hiatus until May but will take a look what I have locally and upload something as soon I can. They weren't based on @madroneropaulo's work so there'll be overlap/combination most likely.

**Comment by pinpong** [comment]
TypeScript +1

**Comment by nitaliano** [comment]
We'll officially support TypeScript, only one person so far as asked for flow support and I also prefer TypeScript more now after using it more 😄 

I won't be actively developing anything for this repo until June but once I come back I can help out with the current efforts to add support for this. 

For anyone that does attempt to write type definitions for layers and their style properties we are autogenerating all of the code from the style spec https://github.com/mapbox/react-native-mapbox-gl/blob/master/scripts/templates/styleMap.js.ejs so in theory this should be very easy to also include a template to autogenerate the type definitions for the layers and styles. Then when we upgrade to the newest native sdks we only need to run `npm run generate` to get the updated type definitions instead of having to hand write them

**Comment by epileftro85** [comment]
So, this is already implemented or still waiting?

**Comment by orta** [comment]
I've started by mapping the prop types as recommended in https://github.com/mapbox/react-native-mapbox-gl/pull/1526 - happy to have someone get those prop types into the components.

**Comment by kristfal** [comment]
We'll be accepting PRs for typescript and flowtype. Please keep them coming @orta or anyone else! I'll close this ticket in an effort to reduce old open tickets.
