### ISSUE TITLE
[IOS] Requesting user location from Mapbox SDK

### ISSUE THREAD

**Issue by kimhafr** [nitaliano/react-native-mapbox-gl#934]
Hi! After adding MapBox we get the popup requesting the user to approve us using their location before the javascript-app is finished loading on the device. We suspect that it is the Mapbox iOS SDK that does this. Can you confirm that there is nothing in the SDK that triggers this behaviour? The app should not request permission until the user opens a view with a map in it right? (Where showUserLocation=true) (not testet on Android)

**Comment by nitaliano** [comment]
Where are you setting `MapboxGL.setAccessToken`? We have a telemetry service that runs in the background that could be triggering it https://github.com/mapbox/react-native-mapbox-gl/issues/878#issuecomment-354802730

**Comment by friedbunny** [comment]
As far as the native iOS maps SDK is concerned, location permission is only ever requested in response to a user’s location potentially being displayed on a map. See [this code](https://github.com/mapbox/mapbox-gl-native/blob/ios-v3.7.2/platform/ios/src/MGLMapView.mm#L4582-L4617) for that logic.

**Comment by kimhafr** [comment]
Thanks for the quick reply! We figured out what was wrong, and it was not Mapbox. Closing this

**Comment by mahipalsingh-syt** [comment]
hi @kimhafr i'm facing same issue in my reactnative app , can you please help what was the cause in your case ?

**Comment by kimhafr** [comment]
Sorry, this was to long a ago and I'm not working on the same project atm.
