### ISSUE TITLE
Should buildToolsVersion be 26.0.1 or higher

### ISSUE THREAD

**Issue by KevinHu2014** [nitaliano/react-native-mapbox-gl#935]
https://github.com/mapbox/react-native-mapbox-gl/blob/5def6977f1714d9b7737beec1c24f986718ed380/example/android/app/build.gradle#L94

**Comment by KevinHu2014** [comment]
It seems the example code use "23.0.1" .

**Comment by nitaliano** [comment]
I was under the impression that React Native needs to use build tools `23.0.1` if that is not the case we can update it to the correct version

**Comment by KevinHu2014** [comment]
@nitaliano  Does mapbox works fine on Android 8 ?

**Comment by nitaliano** [comment]
Yes, it should I do a good amount of testing on an Android 8 emulator

**Comment by nitaliano** [comment]
@KevinHu2014 everything seems to run fine when I up the example project to use `26.0.1` I'll make a PR for it thanks for pointing it out

**Comment by maqen** [comment]
Is build tools `26.0.1` needed for `react-native-mapbox-gl`
?

Really don't understand, would like to feature lowest possible version in my app and as @nitaliano I was under the [impression](http://facebook.github.io/react-native/docs/0.53/getting-started.html#2-install-the-android-sdk) that react native (`0.53.3`) need `23.0.1`?

Anyone can clear this out?

**Comment by nitaliano** [comment]
@maqen React Native works fine with newer versions this is the only thing that must point to `23.0.1` https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/android/app/build.gradle#L144

**Comment by kristfal** [comment]
We now support build tools 28.0.0, the same as the latest release of RN.
