### ISSUE TITLE
Tileset from custom style not working in app

### ISSUE THREAD

**Issue by fmelp** [nitaliano/react-native-mapbox-gl#936]
Hi there, I uploaded a custom tileset to mapbox studio and everything is showing up and working fine there, but the custom tiles do not show up in my app. I am using the right custom style url and all, it's just not showing up at all. Is there a different way I should be doing this or is it not implemented with react-native?

**Comment by fmelp** [comment]
`    const rasterSourceProps = {
      id: 'droneImage',
      url: 'mapbox://fmelp.dydx0mma',
      tileSize: 256,
    };

    return (
        <View style={{flex: 1}}>

          <View style={{flex: 1}}>
            <MapboxGL.MapView
              logoEnabled={false}
              showUserLocation={true}
              style={{flex: 1}}
              ref={map => { this.map = map; }}
              heading={20}
              onDidFinishLoadingMap={this.zoomToNextHole.bind(this)}
              centerCoordinate={[CLUBHOUSE_COORDS.longitude, CLUBHOUSE_COORDS.latitude]}
              showUserLocation={false}
              compassEnabled={false}
              rotateEnabled={false}
              // zoomEnabled={false}
              // scrollEnabled={false}
              pitchEnabled={false}
              styleURL={'mapbox://styles/fmelp/cjc7rxppx68cz2rnweoh24273'}
            >
                <MapboxGL.RasterSource {...rasterSourceProps}>
                  <MapboxGL.RasterLayer
                    id='droneImage'
                    sourceID='droneImageSource'
                   />
               </MapboxGL.RasterSource>
              <CartIcon />
              <DistanceIcons />`

**Comment by fmelp** [comment]
`    const rasterSourceProps = {
      id: 'droneImage',
      url: 'mapbox://fmelp.dydx0mma',
      tileSize: 256,
    };`

`            <MapboxGL.MapView
              logoEnabled={false}
              showUserLocation={true}
              style={{flex: 1}}
              ref={map => { this.map = map; }}
              heading={20}
              onDidFinishLoadingMap={this.zoomToNextHole.bind(this)}
              centerCoordinate={[CLUBHOUSE_COORDS.longitude, CLUBHOUSE_COORDS.latitude]}
              showUserLocation={false}
              compassEnabled={false}
              rotateEnabled={false}
              // zoomEnabled={false}
              // scrollEnabled={false}
              pitchEnabled={false}
              styleURL={'mapbox://styles/fmelp/cjc7rxppx68cz2rnweoh24273'}
            >
                <MapboxGL.RasterSource {...rasterSourceProps}>
                  <MapboxGL.RasterLayer
                    id='droneImage'
                    sourceID='droneImageSource'
                   />
               </MapboxGL.RasterSource>
              <CartIcon />
              <DistanceIcons />
            </MapboxGL.MapView>`

**Comment by fmelp** [comment]
`            <MapboxGL.MapView
              logoEnabled={false}
              showUserLocation={true}
              style={{flex: 1}}
              ref={map => { this.map = map; }}
              heading={20}
              onDidFinishLoadingMap={this.zoomToNextHole.bind(this)}
              centerCoordinate={[CLUBHOUSE_COORDS.longitude, CLUBHOUSE_COORDS.latitude]}
              showUserLocation={false}
              compassEnabled={false}
              rotateEnabled={false}
              // zoomEnabled={false}
              // scrollEnabled={false}
              pitchEnabled={false}
              styleURL={'mapbox://styles/fmelp/cjc7rxppx68cz2rnweoh24273'}
            >
                <MapboxGL.RasterSource {...rasterSourceProps}>
                  <MapboxGL.RasterLayer
                    id='droneImage'
                    sourceID='droneImageSource'
                   />
               </MapboxGL.RasterSource>
              <CartIcon />
              <DistanceIcons />
            </MapboxGL.MapView>`

**Comment by fmelp** [comment]
`  render() {
    const rasterSourceProps = {
      id: 'droneImage',
      url: 'mapbox://fmelp.dydx0mma',
      tileSize: 256,
    };

    return (
        <View style={{flex: 1}}>

          <View style={{flex: 1}}>
            <MapboxGL.MapView
              logoEnabled={false}
              showUserLocation={true}
              style={{flex: 1}}
              ref={map => { this.map = map; }}
              heading={20}
              onDidFinishLoadingMap={this.zoomToNextHole.bind(this)}
              centerCoordinate={[CLUBHOUSE_COORDS.longitude, CLUBHOUSE_COORDS.latitude]}
              showUserLocation={false}
              compassEnabled={false}
              rotateEnabled={false}
              // zoomEnabled={false}
              // scrollEnabled={false}
              pitchEnabled={false}
              styleURL={'mapbox://styles/fmelp/cjc7rxppx68cz2rnweoh24273'}
            >
                <MapboxGL.RasterSource {...rasterSourceProps}>
                  <MapboxGL.RasterLayer
                    id='droneImage'
                    sourceID='droneImageSource'
                   />
               </MapboxGL.RasterSource>
              <CartIcon />
              <DistanceIcons />
            </MapboxGL.MapView>
          </View>
          {this.showHoleInfo()}
          {this.showDistanceInfo()}
          {/* <HoleSelect />
          <NavButtonHolder /> */}
        </View>

    );
  }
}`

**Comment by nitaliano** [comment]
Are you positive they are not vector tiles?

**Comment by savv** [comment]
I am also having trouble getting raster sources + layers to work.

I can get them to work with a style URL and _without_ and RasterSource:
```
        <Mapbox.MapView
            zoomLevel={2} id="map"
            styleURL="mapbox://styles/savvopoulos/XXXX"
            style={{flex: 1}}>
        </Mapbox.MapView>
```

But I can't get them to work with a RasterSource and without a styleURL:
```
        <Mapbox.MapView
            zoomLevel={2} id="map"
            style={{flex: 1}}>
          <Mapbox.RasterSource id="customSource" url="mapbox://savvopoulos.XXXXX">
            <Mapbox.RasterLayer
              id="customLayer"
              sourceLayerID="layer_name_in_mapbox"
             />
          </Mapbox.RasterSource>
        </Mapbox.MapView>
```
Whereas I was able to do the latter with a VectorSource and FillLayer.

**Comment by fmelp** [comment]
Sorry guys, I still can't figure it out...
Tried what @savvopoulos said about just having the style URL
and also to use VectorSource and FillLayer

this is my code for the latter
const rasterSourceProps = {
      id: 'droneImage',
      url: 'mapbox://fmelp.dydx0mma',
      tileSize: 256,
    };
.
.
.
<MapboxGL.VectorSource {...rasterSourceProps}>
                  <MapboxGL.FillLayer
                    id='droneImage'
                    sourceID='droneImageSource'
                  />
</MapboxGL.VectorSource>

**Comment by fmelp** [comment]
is the problem the fact that the style was created using mapbox studio?

**Comment by savv** [comment]
@fmelp when you say that you couldn't get it to work, what do you mean? Does the map show, without the style?

**Comment by fmelp** [comment]
@savvopoulos the underlying satellite theme seems to be working, but my custom raster layer that shows up in studio not showing up in the app..

**Comment by sheub** [comment]
I have similar problem here,  the tilesets that I have uploaded from .geojson data are shown in the Mapbox studio, but not when I use a basic example with mapboxgl.js library. 
Also, I have used the `Download` function from the Mapbox studio to get the `style.json` file of my maps, and I see only the entries and styles from the basic layer; I can't see any layers from the my custom tilesets.

**Comment by sheub** [comment]
Ok, Sorry my mistake... I simply didn't press the `publish` button from Mapbox studio to update the style data. Now the map is shown all right... :blush:
