### ISSUE TITLE
Get the current map zoom level.

### ISSUE THREAD

**Issue by mtt87** [nitaliano/react-native-mapbox-gl#938]
I have a use case where I wanted to press a cluster and zoom the map by `(currentZoom + 2)` but I realised that it's not possible at the moment to retrieve the current `zoomLevel`.

mapbox-gl-js has this method for example:
https://www.mapbox.com/mapbox-gl-js/api/#map#getzoom

It would be great to have it, probably on the `ref` `this.map.getZoom()`

**Comment by nitaliano** [comment]
`getZoom` support has been merged into master
