### ISSUE TITLE
Add onRegionIsChanging to Android and bring in line with the other change map handlers

### ISSUE THREAD

**Issue by kristfal** [nitaliano/react-native-mapbox-gl#939]
`onRegionIsChanging` should return the same information as `onRegionDidChange` and `onRegionWillChange`. Right now, it just returns an empty object.

Update: `onRegionIsChanging` doesn't seem to fire at all on Android.

**Comment by dpyeates** [comment]
Hello, any idea when this will be looked at? For info the 'update' bit on this ticket is also raised in #1116

**Comment by sasogeek** [comment]
Hello, any update on this? onRegionIsChanging doesn't have the same behavior on android as on ios. It doesn't fire on android unless map is flicked, but I have a use case where the map is simply dragged, regardless of drag speed.

**Comment by kristfal** [comment]
This is working fine in latest master.
