### ISSUE TITLE
Compiling for target device : Undefined symbols for architecture armv7:   "_RCTSetLogFunction"

### ISSUE THREAD

**Issue by dagatsoin** [nitaliano/react-native-mapbox-gl#94]
Following a bitcode error [https://github.com/mapbox/react-native-mapbox-gl/issues/93] I got this error preventing to compile on a target device (iphone 4S)

Xcode 7
OSX : 10.10.4
iPhone 4s (iOS 9.0.2)

```
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/Developer/Library/Frameworks'
Undefined symbols for architecture armv7:
  "_RCTSetLogFunction", referenced from:
      -[AwesomeProjectTests testRendersWelcomeScreen] in AwesomeProjectTests.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by dagatsoin** [comment]
And here it is [https://github.com/facebook/react-native/issues/2685#issuecomment-142626306].
We need to disable dead code striping for the debug release on the target device.

I think it will be really useful to also add this to the tutorial. It seams to happens with xcode 7.

**Comment by ltempier** [comment]
ok dude
