### ISSUE TITLE
Add getCenter and getZoom methods

### ISSUE THREAD

**Issue by kristfal** [nitaliano/react-native-mapbox-gl#940]
We currently have `getVisibleBounds`. We should also expose `getCenter` and `getZoom`.

**Comment by nitaliano** [comment]
I mentioned this in our Gitter channel yesterday I think the plan going forward will be to expose all the methods that GLJS exposes on our RN component for the MapView, so we'll have things like `getCenter` `getZoom` `getRotation` `getPitch`
