### ISSUE TITLE
Cannot see current position, even with `showUserLocation={true}`.

### ISSUE THREAD

**Issue by joshuapinter** [nitaliano/react-native-mapbox-gl#944]
I am running 6.0.2 and have even tried the `cross-platform-location` branch but neither work. 

I'm calling the map with: 

```js
<MapboxGL.MapView 
    showUserLocation={true}
/>
```

![device-2018-01-11-122933](https://user-images.githubusercontent.com/180819/34843280-3d4044e2-f6cb-11e7-958f-f8cf3192a499.png)

I see the map and I can interact with it but there's no current user location. My location services are all on because I can get my location coordinates outside of the MapboxGL Mapview. 

Any ideas what I'm missing here?

**Comment by nitaliano** [comment]
I'm assuming this is Android? Are you calling this https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/App.js#L139?

**Comment by joshuapinter** [comment]
@nitaliano Hi Nick. Thanks for your response. Yes, it's on Android and yes I'm calling that. `isGranted` is `true`.

**Comment by nitaliano** [comment]
how are you grabbing the current location?

**Comment by joshuapinter** [comment]
I do this with a native bridge like so: 

```java
googleApiClient = new GoogleApiClient.Builder(activity)
                .addApi(LocationServices.API)
                .addConnectionCallbacks(this)
                .addOnConnectionFailedListener(this)
                .build();

googleApiClient.connect();
```

Important note here, the stand-alone Google Maps app shows my currently location just fine.

Also if I run this in an emulator it works fine.

**Comment by nitaliano** [comment]
The repo is using the LostLocationEngine internally maybe that is causing a conflict, would you be able to throw a minimal repo together and I can debug it?

**Comment by joshuapinter** [comment]
I'm not sure if you'll be able to debug this because it seems to be device dependent. I launched the debug build on a different tablet and it seems to work just fine. Really confused here. Let me know if there's anything I can try to get more information for you.

**Comment by nitaliano** [comment]
hmm what device and Android version is it not working on?

**Comment by joshuapinter** [comment]
The device is an obscure rugged tablet called a HiDON 7": 

http://www.ruggedtabletspcfactory.com/hidon-7-inch-4g-fdd-lte-android-nfc-rugged-android-tablets-ip68-fullyrugged-tablet-pc-computer-p-2888.html

And it's running Android 5.1 (API 23).

**Comment by nitaliano** [comment]
I see I probably won't be able to get may hands on that device. Maybe something is coming up in Logcat? Could post a gist with the log dumps(with no filters selected) and I can look it over to see if anything seems out of wack

**Comment by joshuapinter** [comment]
I'll see if I can get react-native-maps working and if that works then I'll circle back and get some logs for you. Very odd because this worked fine pre 6.0.0.

**Comment by joshuapinter** [comment]
Hey @nitaliano, I wanted to update you with something. I rolled back to version 5.2 of the library and everything works really well on all the devices I've tested, including the weirdo HiDON. 

![device-2018-01-12-122003](https://user-images.githubusercontent.com/180819/34891545-2bb7d67c-f793-11e7-8b91-12ac03788aeb.png)

It seems like something fishy is going on with version 6, even thought that's the "officially supported" one. 

I'm going to hold off on upgrading for now.

**Comment by nitaliano** [comment]
@joshuapinter glad you got something working, it could also be differences in the native Android SDKs that are used pre 6.0 and now. I have verified on all my devices 5.0.0 and up that it is working as expected.

I'm going to close this out for now since there are no steps I can take to reproduce this issue, if you do end getting around to sending me the logs I would love to see them.

**Comment by daFelix** [comment]
Hello @joshuapinter , Im kinda new into RN can you tell me how do you rollback the version to 5.2.0?

Thanks in advance!

**Comment by joshuapinter** [comment]
@daFelix You'll want to do two things: 

1) Use this in your `package.json` file: 

`"react-native-mapbox-gl": "5.2.0"`

2) Use this link when browsing the code repo because it's locked to tag 5.2.0:

https://github.com/mapbox/react-native-mapbox-gl/tree/5.2.0

Follow the install instructions, etc. provided for version 5.2.0 only. They are very different so  make sure.

**Comment by devantic** [comment]
Same problem with 6.1.0. Thanks @joshuapinter, changed `package.json` to 5.2.0 and it works!
