### ISSUE TITLE
Draw Circle With Radius in Meters not Pixels

### ISSUE THREAD

**Issue by EricPKerr** [nitaliano/react-native-mapbox-gl#945]
The current method of drawing a circle on the map uses [`<MapboxGL.CircleLayer />`](https://github.com/mapbox/react-native-mapbox-gl/blob/master/docs/CircleLayer.md) but the method for passing in `circleRadius` appears to be in pixels.  I would like to draw a 10-mile circle (only the border is a stroke color and the 'fill' is transparent) - is that possible?

I've looked into passing in a GeoJSON type=Circle shape into `<MapboxGL.ShapeSource shape={...}>` but haven't been able to get that to work correctly.

Any way to accomplish this?

**Comment by nitaliano** [comment]
Your best bet would be creating a polygon in GeoJSON that is a circle and displaying it as a FillLayer. Since the CircleLayer is based off of a center point we don't have anyway to achieve this with a CircleLayer. You can try this out http://turfjs.org/docs/#circle to help you form a circle. I've had to do this on the web before, so it might take some tweaking to help round the edges of the polygon

**Comment by EricPKerr** [comment]
@nitaliano yes, the circle would be a 10-mile radius around a center point.  The CircleLayer works as intended (around the center point) it just accepts the radius in pixels rather than distance.  Is that not how it's intended to be used?

**Comment by nitaliano** [comment]
Yea, pixels are the intended behavior, styles are just visualize they are not suppose to represent real world coordinates. Your source is what represents the real world coordinates, anytime you see a mapping library render a circle it's actually converting it to a polygon like I mentioned above.

**Comment by EricPKerr** [comment]
Cool - the turfjs implementation works fine. Thanks for your help.

**Comment by Amalp** [comment]
@nitaliano 
@EricPKerr 
I achieved this using **shapeSource** with a **LineLayer** and  **http://turfjs.org/docs/#circle**

the output is given below
![polygongrey](https://user-images.githubusercontent.com/14848054/38734988-13f6a7b2-3f45-11e8-94d7-4b98c6de4232.png)

**How can i achieve the circle i need help round the edges of polygon ?**

the code is given below
```

import React, { Component } from 'react';
import { View, Text,StyleSheet } from 'react-native';
import {Spinner} from 'native-base';
import Mapbox from '@mapbox/react-native-mapbox-gl';
import MapboxGL from '@mapbox/react-native-mapbox-gl';
import MapboxClient from '@mapbox/react-native-mapbox-gl';
import circle from '@turf/circle'


Mapbox.setAccessToken('pk.eyJ1IjoiYW1hbHAiLCJhIjoiY2pkdTZ0M3ZpMnFsYzJ2amc0ZnRjZXRhMCJ9.8PFRuAdcjb7OMHAQHiW5fA');

var center = [76.343981,10.279141];
var radius = 10;
var options = {steps: 10, units: 'kilometers', properties: {foo: 'bar'}};
 
const layerStyles = MapboxGL.StyleSheet.create({
  route: {
    lineColor: 'grey',
    lineWidth: 3,
    lineOpacity: 0.84,
    lineDasharray: [2,2],
  },
 
});

export default class App extends Component {


  constructor(props) {
    super(props);
    this.state = {
      latitude: 41.596,
      longitude: 1.542,
    };
  }

  componentDidMount() {
    console.log(JSON.stringify(circle(center, radius, options)) + 'ama')
  }
  
  render() {
    return (
      <View style={styles.container}>
        {
          this.mapView()
        }
      </View>
    );
  }

  mapView(){
    return(
      <Mapbox.MapView
        styleURL={Mapbox.StyleURL.Street}
        zoomLevel={10}
        centerCoordinate={[ 76.343981,10.279141]}
        style={styles.container}>
     <MapboxGL.ShapeSource id='routeSource' shape={circle(center, radius, options)}>
        <MapboxGL.LineLayer id='routeFill' style={layerStyles.route} belowLayerID='originInnerCircle' />
      </MapboxGL.ShapeSource>
      </Mapbox.MapView>
    )
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  
});
```

**Comment by nolangray15** [comment]
If you increase the steps to something like 50 it will look much rounder

**Comment by CyrusZei** [comment]
remember to remove the API key

**Comment by Myzel394** [comment]
Is there a new method to do this? Because @Amalp's code snippet doesn't work anymore :/

**Comment by payucads** [comment]
@Myzel394 hey buddy! I got this solution to work for me. I just feed it the center coordinates from the parent component, but you can do that part however you want. Basically, I have two layers, one for fill and one for stroke, but if you don't need one of them, just delete it. Hopefully it helps. Btw this was done with the latest version of Mapbox for RN.

```javascript
import MapboxGL from '@rnmapbox/maps';
import React from 'react';
import circle from '@turf/circle';

function Radius(props) {
  let radius = 1.6;
  let options = {units: 'kilometers', properties: {foo: 'bar'}};

  const layerStyles = {
    route: {
      lineColor: '#2DC87D',
      lineWidth: 1.5,
      lineDasharray: [2, 2],
    },
  };

  if (!props.center) {
    return null;
  }

  return (
    <MapboxGL.ShapeSource
      id="radiusSource"
      shape={circle(props.center, radius, options)}>
      <MapboxGL.FillLayer
        id="radiusFill"
        style={{fillColor: 'rgba(45, 200, 125, 0.1)'}}
      />
      <MapboxGL.LineLayer
        id="radiusOutline"
        style={layerStyles.route}
        aboveLayerID="radiusFill"
      />
    </MapboxGL.ShapeSource>
  );
}

export default Radius;
```
