### ISSUE TITLE
dynamically render multiple ShapeSource components inside a MapView?

### ISSUE THREAD

**Issue by glennverschooren** [nitaliano/react-native-mapbox-gl#948]
Hey,

I have a question about the following use case:
A user can toggle multiple layers and show them on a map.
<img width="727" alt="schermafbeelding 2018-01-12 om 18 11 02" src="https://user-images.githubusercontent.com/3251519/34890911-f8b669e6-f7d3-11e7-94b7-387f73718e92.png">

To do this I'm rendering a shapeSource component for each layer the user activates.
Each layer has a feature collection that can be rendererd by the ShapeSource component.

The problem is that this setup isn't working properly. 

Is this the way I should dynamicly render multiple ShapeSource components inside the MapView?
I have found this [example](https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/EarthQuakes.js) but it only shows how to render one static ShapeSource component.

I Just need to be sure what I'm doing is correct because then there should be a problem with my code :)

```
class Map extends Component {
	...
	
	renderActiveLayers(activeLayers) {
	
		return activeLayers.map((activeLayer, i) => {
			const cluster = get(activeLayer, "config.mapbox.cluster", {});
			const layerProps = get(activeLayer, "config.mapbox.layer.props");
			
			return (
				<MapboxGL.ShapeSource
					id={activeLayer.config.id}
					shape={activeLayer.features} // feature collection
					cluster
					clusterRadius={55}
					clusterMaxZoom={14}
				>
					// cluster counter layer
					<MapboxGL.SymbolLayer
						id={"pointCount-" + i}
						style={cluster.count.style} />
					
					// cluster circle layer
					<MapboxGL.CircleLayer
						id={}
						belowLayerID={"pointCount-" + i}
						filter={["has", "point_count"]}
						style={cluster.points.style} />
					
					// symbol layer layout config for all features in the
					// features collection
					<MapboxGL.SymbolLayer
						id={"marker-" + i}
						filter={["!has", "point_count"]}
						style={layerProps.style} />
					
				</MapboxGL.ShapeSource>
			)
		});
	}
	
	render() {
		...
		<MapboxGL.MapView
			style={...mapview.styles}
			{...this.props.mapConfig}
		>
			{this.renderActiveLayers(activeLayers)}
		
		</MapboxGL.MapView>
	}
}

```

**Comment by nitaliano** [comment]
@glennverschooren yes, it looks correct and you can update the visibility through it's style properties. I can work on adding an example of this to the example application

**Comment by glennverschooren** [comment]
@nitaliano Thank you for your quick reply! That example would be very nice!

So what you're saying is that I can toggle de visibility from the SymbolLayer and keep the ShapeSource rendered inside the map?

Because now I dynamically add and remove layers from the activeLayers and rerender them inside the map.

**Comment by nitaliano** [comment]
@glennverschooren yes exactly I think that might be an easier way of handling it instead of adding and removing layers from the ShapeSource. Dynamically adding and removing layers is also a valid way of handling this so it would be a matter of preference here.

**Comment by jsina** [comment]
@nitaliano I'm loading multi location on map with `ShapeSource` and `SymbolLayer`. but when the `zoomLevel` lower than 10 or 9 the map only shows one of the symbol. how could I solve it?
