### ISSUE TITLE
"Use of undeclared identifier" errors during Xcode building

### ISSUE THREAD

**Issue by AndreaZanuccoli** [nitaliano/react-native-mapbox-gl#950]
When i try to build my project in Xcode it shows the following errors inside MGLModule.m:

`Use of undeclared identifier 'MGLCirclePitchAlignmentMap'; did you mean 'MGLCircleScaleAlignmentMap'?`
`Use of undeclared identifier 'MGLCirclePitchAlignmentViewport'; did you mean 'MGLCircleScaleAlignmentViewport'?`
`Use of undeclared identifier 'MGLIconAnchorCenter'; did you mean 'MGLTextAnchorCenter'?`
`Use of undeclared identifier 'MGLIconAnchorTop'; did you mean 'MGLTextAnchorTop'?`
`Use of undeclared identifier 'MGLIconAnchorBottom'; did you mean 'MGLTextAnchorBottom'?`
`Use of undeclared identifier 'MGLIconAnchorLeft'; did you mean 'MGLTextAnchorLeft'?`
`Use of undeclared identifier 'MGLIconAnchorRight'; did you mean 'MGLTextAnchorRight'?`
`Use of undeclared identifier 'MGLIconAnchorTopLeft'; did you mean 'MGLTextAnchorTopLeft'?`
`Use of undeclared identifier 'MGLIconAnchorTopRight'; did you mean 'MGLTextAnchorTopRight'?`
`Use of undeclared identifier 'MGLIconAnchorBottomLeft'; did you mean 'MGLTextAnchorBottomLeft'?`
`Use of undeclared identifier 'MGLIconAnchorBottomRight'; did you mean 'MGLTextAnchorBottomRight'?`
`Use of undeclared identifier 'MGLIconPitchAlignmentAuto'; did you mean 'MGLTextPitchAlignmentAuto'?`
`Use of undeclared identifier 'MGLIconPitchAlignmentMap'; did you mean 'MGLTextPitchAlignmentMap'?`
`Use of undeclared identifier 'MGLIconPitchAlignmentViewport'; did you mean 'MGLTextPitchAlignmentViewport'?`

**Comment by nitaliano** [comment]
make sure you have the latest `Mapbox.framework` in your node_modules try a fresh install, those enums were added in `3.7.+` which leads me to believe you have an older version of `Mapbox.framework` in your project
