### ISSUE TITLE
Problems with Mapbox.PointAnnotation

### ISSUE THREAD

**Issue by marcossk8** [nitaliano/react-native-mapbox-gl#954]
Good day, I have a problem wanting to put a for in <MapboxGL.PointAnnotation />
1- A single point is shown, whereas more than one should be displayed
2- That point, when doing more zoom or less moves to another direction

{this.state.cloneSucursales.map(marker => (
             
             <Mapbox.PointAnnotation
               key='pointAnnotation'
               id='pointAnnotation'
               coordinate={[parseFloat(marker.longitud), parseFloat(marker.latitud)]}>
 
               <View style={styles.annotationContainer}>
                 <Icon
                   name='ios-pin'
                   color={Colores.principal}
                   style={styles.annotationFill}
                 />
               </View>
               <Mapbox.Callout
                 title= 'asd'
                 />
             </Mapbox.PointAnnotation>
               ))}

**Comment by marcossk8** [comment]
{this.state.cloneSucursales.map(marker => (
             
             <Mapbox.PointAnnotation
               key='pointAnnotation'
               id='pointAnnotation'
               coordinate={[-64.1641829, -31.43152]}>
 
               <View style={styles.annotationContainer}>
                 <Icon
                   name='ios-pin'
                   color={Colores.principal}
                   style={styles.annotationFill}
                 />
               </View>
               <Mapbox.Callout
                 title= 'asd'
                 />
             </Mapbox.PointAnnotation>
               ))}

**Comment by nitaliano** [comment]
you're using the same `key` and `id` for every annotation try making them unique and it will render all of them

**Comment by marcossk8** [comment]
@nitaliano I was missing that, thanks

**Comment by nitaliano** [comment]
glad you got it working closing this out
