### ISSUE TITLE
VectorSource use local specification

### ISSUE THREAD

**Issue by samdelacruz** [nitaliano/react-native-mapbox-gl#959]
Is it possible to use a local TileJSON configuration, rather than specifying a `url` prop on `VectorSource`?

It would be useful for integrating custom/third party vector tile servers which may not have a config JSON already available, or may have dynamically generated tile source URLs.

**Comment by nitaliano** [comment]
@samdelacruz I haven't tested this out yet with our RN SDK but this could work. If you have a json file that conforms to our tile spec https://www.mapbox.com/vector-tiles/specification/ and you use react-native-fetch-blob to find the url to that file and add it as a `url` prop to your VectorSource in theory it should work. Without that config file there is no other way to get this working, you would be able to supply a url to RasterSource for custom tiles, but that's the best you'll be able to do
