### ISSUE TITLE
Move attribution and Mapbox watermark

### ISSUE THREAD

**Issue by alexisohayon** [nitaliano/react-native-mapbox-gl#96]
Hi,

Is there a way to move the info / watermark from the bottom to the top corner?

Thanks :)

**Comment by bsudekum** [comment]
done in https://github.com/mapbox/react-native-mapbox-gl/pull/178

**Comment by ferdicus** [comment]
Sorry, I don't see how the changes apply to the issue - maybe I'm missing something:
Move !== Remove

Thanks

**Comment by VinzGhyz** [comment]
Any more info on this? Would be useful for us to be able to move it ever so slightly

**Comment by vladoski** [comment]
I have the same problem. Moving the attribution is kinda easy. Instead the Watermark is not. I'm able to remove it but not moving it on the right top corner.
