### ISSUE TITLE
Run Script path 

### ISSUE THREAD

**Issue by timrc** [nitaliano/react-native-mapbox-gl#962]
Please update install.md for iOS and remove `"` from `Run Script` section

Adding ` "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Mapbox.framework/strip-frameworks.sh"` to `Run Script` is failing to build the image.

Removing quotes from it `${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Mapbox.framework/strip-frameworks.sh` works fine.

**Comment by nitaliano** [comment]
will do thanks for pointing it out

**Comment by timrc** [comment]
Thanks, that'd be nice.

I also have another issues using MapBox.
I did follow the Run Script phase and add the script to Build Phase, app builds fine and runs.
But when I try to upload it to the App Store, I get the following errors.

![screen shot 2018-01-18 at 16 20 44](https://user-images.githubusercontent.com/3773639/35113901-f5a91612-fc7a-11e7-9f51-6b5f2304cb4e.png)

I suppose the script should strip out invalid archs, but doesn't seem to.

There is no script added in the example that's provided.

**Comment by nitaliano** [comment]
That strip frameworks script is being used in our test iOS app(not RN) and many customers are using without an issue, so I have my doubts that it's the script that is causing the problem. I'm wondering if the script is actually being run, I'll add it to the example app for consistency but that's not something we ever plan on trying to release to the store

**Comment by nitaliano** [comment]
I'm not seeing the build fail with the quotes around the script, mind sending me a screen shot of your build phases?

**Comment by timrc** [comment]
Here are screen shots where mapbox is being set in build phases:

## run script
<img width="1346" alt="screen shot 2018-01-19 at 06 56 30" src="https://user-images.githubusercontent.com/3773639/35138369-1909350e-fce6-11e7-94da-ec8b7801c625.png">

## embed frameworks
<img width="1328" alt="screen shot 2018-01-19 at 06 56 25" src="https://user-images.githubusercontent.com/3773639/35138373-1ccd11d8-fce6-11e7-8cbb-9513978f3bb7.png">


## Link binaries with libraries
<img width="1238" alt="screen shot 2018-01-19 at 06 56 58" src="https://user-images.githubusercontent.com/3773639/35138379-232b03aa-fce6-11e7-8fa1-e9a55b9761b2.png">

## all / collapsed
<img width="501" alt="screen shot 2018-01-19 at 06 59 22" src="https://user-images.githubusercontent.com/3773639/35138410-4bbf0dc0-fce6-11e7-8942-78b4e7a0afd2.png">

**Comment by nitaliano** [comment]
Give this a try.

under shell you want it to say `/bin/sh` and the textarea underneath that input box is the bash script that will be run

![screenshot 2018-01-19 09 47 51](https://user-images.githubusercontent.com/1761993/35164109-e4b590a0-fcfd-11e7-9506-ed95d5b96237.png)

**Comment by timrc** [comment]
Thanks, all good.
Please ignore my initial comment for this issue it would be good to add this to the example so there are no confusions for others.

**Comment by nitaliano** [comment]
@timrc I added it to the example today, sorry for the confusion, and glad you got it working!
