### ISSUE TITLE
Use a predefined svg icons from mapbox studio

### ISSUE THREAD

**Issue by Pierre-Green** [nitaliano/react-native-mapbox-gl#963]
Hello i would like to know if it is possible to use the mapbox style images in the PointAnnotation or any equivalent. Thank you 👍 

![image](https://user-images.githubusercontent.com/14202305/35044867-2f0b2312-fb92-11e7-921b-a29c528347f1.png)

Using last version of mapbox-gl

**Comment by nitaliano** [comment]
Yes, it's possible to use those svgs with a SymbolLayer. Let's say we have an svg icon named 'airport'

you can refer to it by name using the iconImage style property
```
const styles = MapboxGL.StyleSheet.create({
  symbol: {
    iconImage: 'airport'
  }
});
```

then you would need to render it using a Source with a SymbolLayer so
```
<MapboxGL.ShapeSource id='testSource' ...>
    <MapboxGL.SymbolLayer id='testLayer' style={styles.symbol} />
</MapboxGL.ShapeSource>
```
