### ISSUE TITLE
Changes needed for gradle 3.0.1 compatibility

### ISSUE THREAD

**Issue by pacamara** [nitaliano/react-native-mapbox-gl#975]
Some minor changes are needed for gradle 3.0.1 compatibility: in android/build.gradle:
* Remove the `buildToolsVersion`, gradle now specifies a default and the current value conflicts with that.
* Declare dependencies using `api` not `compile` per https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#new_configurations

We are currently hacking these changes with a script in status.im, and would rather it is fixed upstream. Thanks!

Parent issue: https://github.com/status-im/status-react/issues/3037

**Comment by nitaliano** [comment]
Will this have any complications with apps that are created with `react-native init`?

**Comment by pacamara** [comment]
Yes, it turns out to be a breaking change for apps authored with `react-native init`, requiring manual changes to the generated code to fix. Please see https://github.com/react-native-community/react-native-svg/issues/581#issuecomment-359192907  A solution could be to provide a separate gradle 3 tag?

**Comment by nitaliano** [comment]
I personally hate being on an older version of gradle and would love to get this into master instead of it being on a tag. Someone opened a PR on react native to upgrade gradle recently https://github.com/facebook/react-native/pull/17747 would like to see what happens with this PR before attempting to create a gradle3 tag

**Comment by msand** [comment]
I very much agree here. Developing and debugging native code for android has improved significantly with the version changes in my PR. Requiring manual changes or monkey-patching for all newcomers just to get the same benefits seems counter productive, unless there are actual blocking changes which need to be fixed anyway instead.

**Comment by nitaliano** [comment]
@pacamara it doesn't appear like the PR I mentioned above will be merged in anytime soon, and I will also need gradle3 in an upcoming app so when I do that I'll cut a gradle3 tag for people to use

**Comment by pacamara** [comment]
@nitaliano Got it, thanks Nick.

**Comment by johncadengo** [comment]
Is this still an open issue? What version of gradle is compatible?

**Comment by kristfal** [comment]
We're now aligned with RN59, so this should now longer be an issue.
