### ISSUE TITLE
Is access_token required for self-hosted maps?

### ISSUE THREAD

**Issue by EugenePisotsky** [nitaliano/react-native-mapbox-gl#979]
Hello,

I use self-hosted style and maps, but when i run Android app, i see the following error:

`Using MapView requires setting a valid access token. Use Mapbox.getInstance(Context context, String accessToken) to provide one.`

Is access_token always required? Or i'm doing something wrong?
iOS works fine

**Comment by nitaliano** [comment]
Yes you always need an access token to work with our SDK

**Comment by jussirantala** [comment]
Why?

**Comment by awdhootlele** [comment]
Having same problem here. The mapbox-gl-native has a [PR merged which removes need of access token](https://github.com/mapbox/mapbox-gl-native/pull/12001) Is that not yet added in RNMapboxGL ?

**Comment by frownbreaker** [comment]
I saw the PR  was merged into mapbox-gl-native
Does the issue exist for iOS as this PR says Andriod only?
