### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by ninamanalo** [nitaliano/react-native-mapbox-gl#98]
I built my project with react native mapbox 0.4.2 in XCode 7.0.1 and this shows:

<img width="790" alt="screen shot 2015-10-14 at 11 22 06 am" src="https://cloud.githubusercontent.com/assets/8219419/10474183/160767f2-7266-11e5-8ce5-c258471547f9.png">

Any ideas? Thanks in advance.

**Comment by bsudekum** [comment]
This is an install issue. Double check https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/install.md
