### ISSUE TITLE
onRegionWillChange isUserInteraction always false

### ISSUE THREAD

**Issue by EricPKerr** [nitaliano/react-native-mapbox-gl#980]
This is potentially related to https://github.com/mapbox/react-native-mapbox-gl/issues/901 but it appears that the `isUserInteraction` on the `onRegionWillChange` callback is always false (when user drags/pinches/etc).  This was tested and verified with the **6.0.3-rc1** release.

**Comment by henrikra** [comment]
Yeah I just noticed this too! When I start to move map with my finger it calls `onRegionWillChange` correctly but `event.properties.isUserInteraction` is always false. If I try `onRegionDidChange` it knows when the map is moved by user interaction correctly. I am using Mapbox `6.0.2`

**Comment by EricPKerr** [comment]
@henrikra yes, the `onRegionDidChange` seems to have been fixed up well with the other recent location issues/PRs, but am noticing different/incorrect behavior with WillChange.

**Comment by sandroferrari** [comment]
I'm using mapbox `6.1.1` on Android and the `event.properties.isUserInteraction` still always false in `onRegionWillChange` event.

**Comment by EricPKerr** [comment]
@henrikra @sandroferrari @nitaliano `isUserInteraction` is still always false always with `onRegionWillChange` callback on iOS and Android in **6.1.2-beta**.

**Comment by kormang** [comment]
6.0.3, not always but most of the time on Android in `onRegionDidChange`

**Comment by EricPKerr** [comment]
@nitaliano I figured out the cause of this issue, but am not sure how to fix it.

In [RCTMGLMapViewManager.m](https://github.com/mapbox/react-native-mapbox-gl/blob/548b91c66eb56bdd3e63071922de7ab2936e2474/ios/RCTMGL/RCTMGLMapViewManager.m) there are 3 relevant methods:

[Line 427: shouldChangeFromCamera](https://github.com/mapbox/react-native-mapbox-gl/blob/548b91c66eb56bdd3e63071922de7ab2936e2474/ios/RCTMGL/RCTMGLMapViewManager.m#L427)

[Line 486: regionWillChangeAnimated](https://github.com/mapbox/react-native-mapbox-gl/blob/548b91c66eb56bdd3e63071922de7ab2936e2474/ios/RCTMGL/RCTMGLMapViewManager.m#L486)

[Line 498: regionDidChangeAnimated](https://github.com/mapbox/react-native-mapbox-gl/blob/548b91c66eb56bdd3e63071922de7ab2936e2474/ios/RCTMGL/RCTMGLMapViewManager.m#L498)

The `regionWillChangeAnimated` and `regionDidChangeAnimated` correspond to the two events in JS.  Natively, both call `NSDictionary *payload = [self _makeRegionPayload:mapView animated:animated];` to build the callback event payload object, which has the `isUserInteraction` property on it.

The problem is: The `regionWillChangeAnimated` is getting called *before* the `shouldChangeFromCamera` method, which sets `isUserInteraction = YES;`.  That shouldChange method gets called a few times until the animation stops and DidChange fires (where isUserInteraction is correct).

Any ideas?  Thank you!

**Comment by EricPKerr** [comment]
It looks like this could implement the `regionWillChangeWithReason` delegate method (?) instead of the current `regionWillChangeAnimated` and look to see if it was a user gesture or programmatic to set the `isUserInteraction` boolean properly: https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/src/MGLCameraChangeReason.h

I don't know how to do this though since none of the core Mapbox `CameraChangeReason` constants above are in this project.  Help?
