### ISSUE TITLE
[Android] - SymbolLayer icon glitches

### ISSUE THREAD

**Issue by mdnmdn** [nitaliano/react-native-mapbox-gl#985]
With Android, using a SymbolLayer in a ShapeSource: with a shape with several points the icons behave in a strange ways going to b/w and disappearing.

The expected result is (on iOS):
![iphone_6_-_11_1](https://user-images.githubusercontent.com/441198/35229256-3ab8d024-ff93-11e7-8771-9946ed69a1d4.png)

The android result is:

![android_emulator_-_nexus_5x_api_27_5554](https://user-images.githubusercontent.com/441198/35229308-5c9e8558-ff93-11e7-8cd1-05f44a5c85d8.png)

Panning and pinching the correct icons magically appear (and disappear again):

![jan-22-2018 16-44-41](https://user-images.githubusercontent.com/441198/35229570-05cb872a-ff94-11e7-8ecf-f72be02edb23.gif)

```<MapboxGL.MapView ...  >
  <MapboxGL.ShapeSource
      id="symbolLayerSource"
      shape={featureCollection}
      images={{
              blue: blueStar,
              yellow: yellowStar,           
      }} >
        <MapboxGL.SymbolLayer id='symbol' style={mapStyles.parameterIcon} />
</MapboxGL.ShapeSource>
```

To test:

- Sample project: [https://github.com/mdnmdn/RN-mapbox-play](https://github.com/mdnmdn/RN-mapbox-play)
- Source file: [SingleShapeSource.js](https://github.com/mdnmdn/RN-mapbox-play/blob/master/src/SingleShapeSource.js)
- [Sample data](https://github.com/mdnmdn/RN-mapbox-play/blob/master/data/sample.json)
Versions:

- RN version: 0.50.3
- mapbox: 6.0.2
- Android: several versions including 8.x

**Comment by nitaliano** [comment]
This issue might need to be filled in gl-native I'll test it out and see where the bug is happening

**Comment by atarsha** [comment]
I am experiencing the same behavior on Android emulator, but so far not the case on any physical devices.

**Comment by tobrun** [comment]
ticket tracking this upstream in https://github.com/mapbox/mapbox-gl-native/issues/10829

**Comment by kristfal** [comment]
This should be fixed in master. Please reopen if the problem still persists.
