### ISSUE TITLE
SymbolLayer with parametrized remote images

### ISSUE THREAD

**Issue by mdnmdn** [nitaliano/react-native-mapbox-gl#986]
Starting from the example [ShapeSourceIcon.js](https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/ShapeSourceIcon.js) from the official repository, we try to use remote (load from http) icons but without success.

The expected result is :

![iphone_6_-_11_1](https://user-images.githubusercontent.com/441198/35232133-ff837240-ff9a-11e7-8ad1-3788f341ce0e.png)

The actual result is:

![iphone_6_-_11_1](https://user-images.githubusercontent.com/441198/35232112-ed2abe96-ff9a-11e7-89f8-781bc7590cbd.png)

We used the same technique of the cited example: in the shape the icon symbol is defined like a feature collection of elements like:
```
{
  type: "Feature",
  id: "id2",
  properties: {
     icon: "blue",
  },
  geometry: {
    type: "Point",
    coordinates: [
       7.666482466692096,
      45.100378356355066
    ]  
  }
}
```

Using the _properties.icon_ to define the icon type.

the mapbox configuration is managed like:

```
const remoteIcon = 'https://findicons.com/icon/download/97199/circle_orange/48/png';
// ...
<MapboxGL.MapView ...  >
  <MapboxGL.ShapeSource
      id="symbolLayerSource"
      shape={featureCollection}
      images={{
              blue: remoteIcon,
              yellow: remoteIcon,           
      }} >
        <MapboxGL.SymbolLayer id='symbol' style={mapStyles.parameterIcon} />
</MapboxGL.ShapeSource>
```
The style used is:

```
const mapStyles = MapboxGL.StyleSheet.create({
  parameterIcon:{
    iconImage: '{icon}',
    iconSize: IS_ANDROID ? 1 : 0.5,
  },
  remoteIcon:{
    iconImage: remoteIcon,
    iconSize: IS_ANDROID ? 1 : 0.5,
  },
});
```
if the iconImage value is not parametrized but fixed (see the _remoteIcon_ style) it works correctly.

To test:

- Sample project: [https://github.com/mdnmdn/RN-mapbox-play/  branch: err-with-mixed-icon-sources](https://github.com/mdnmdn/RN-mapbox-play/tree/err-with-mixed-icon-sources)
- Source file: [ParametrizedRemoteSymbols.js](https://github.com/mdnmdn/RN-mapbox-play/blob/err-with-mixed-icon-sources/src/ParametrizedRemoteSymbols.js)
- [Sample data](https://github.com/mdnmdn/RN-mapbox-play/blob/master/data/sample.json)

Versions:

- RN version: 0.50.3
- mapbox: 6.0.2
- Android: several versions including 8.x

**Comment by nitaliano** [comment]
I bet it's not properly making the HTTP request in this case thanks for reporting!

**Comment by atarsha** [comment]
Any idea on a fix for this? I also need this functionality. I'm experiencing the same thing on iOS. (still trying a few tweaks to see if I can get it to work, but so far, no go.

**Comment by atarsha** [comment]
Found the solution here: https://github.com/mapbox/react-native-mapbox-gl/issues/792 Works on iOS. Should be verified on Android, then this should be closed.

**Comment by nitaliano** [comment]
Closing this out since we're using the react native image loader it accepts `{ uri: ... }` and we should be able to render remote images this way
