### ISSUE TITLE
local style JSON on Android

### ISSUE THREAD

**Issue by RNMBuser** [nitaliano/react-native-mapbox-gl#987]
On iOS it's easy: just include the file as a resource, don't forget to include it in "Copy Bundle Resources", in Build Phases, and reference it in the JSX without and prefix (i.e. no "asset://" etc., just the name".

How do I do it in Android?

**Comment by nitaliano** [comment]
You can leave the json file where you keep your other assets for JavaScript and use react-native-fetch-blob to give you the correct URL to pass down to the native code

**Comment by RNMBuser** [comment]
Thanks a lot! I'll be really thankful if you could post some demo code here.
EDIT: tried using RNFetchBlob.fs.asset(path). Doesn't work.

**Comment by nitaliano** [comment]
Can you post your JSON style in here

**Comment by RNMBuser** [comment]
I also tried placing the JSON style on a web server and using a web URL. On iOS it works, on Android it doesn't. Using the constant MapboxGL.StyleURL.Street works  and shows a map. 

Here's the style JSON:

{
  "version": 8,
  "name": "Raster Tiles",
  "sources": {
    "raster1": {
        "type": "raster",
        "tiles": [
          "https://a.tiles.mapbox.com/v4/mapbox.outdoors/{z}/{x}/{y}.png?access_token=MY_KEY"
        ],
        "tileSize": 256,
        "maxzoom": 15
      }
  },
  "layers": [{
      "id": "baseRaster",
      "type": "raster",
      "source": "raster1",
      "minzoom": 0,
      "maxzoom": 22
    }
  ]
}

**Comment by sironjuh** [comment]
Any particular reason why you would not want to use the asset:// here?
We are using locally hosted mapstyle both on iOS and Android, and it works just fine with:

 styleURL="asset://map_style.json"

File is placed on app/src/main/assets/ folder on Android and added as resource on iOS.

**Comment by RNMBuser** [comment]
This works well (I don't know why it didn't work before). Thanks!

**Comment by bottle-rocket-11** [comment]
Hey guys, I have the exact same issue.  I can access a JSON file with URL="asset://file_name.json" on iOS just fine but it just does not work on Android;

File is placed on app/src/main/assets/ folder on Android and added as resource on iOS.

**Comment by ansarikhurshid786** [comment]
@hugopretorius72 I have opposite problem. in my case working in android and not working in ios. can you explain how to add in ios?
