### ISSUE TITLE
Cannot set pitch and zoomLevel for MapView on IOS

### ISSUE THREAD

**Issue by niallfarrell91** [nitaliano/react-native-mapbox-gl#990]
When I set the pitch and zoomlevel on my Mapview it seems to fail to zoom to the correct level, leaving the mapview zoomed out completely. 
This works fine on Android and only seems to occur on IOS.
Am I setting this correctly, or how could I set both the pitch and zoomlevel?

My code
<Mapbox.MapView
          ref={(c) => this.map = c}
          styleURL={Mapbox.StyleURL.Outdoors}
          zoomLevel={14}
          centerCoordinate={[lakeLong, lakeLat]}
          pitch={90}
          style={styles.mapContainer}>
</Mapbox.MapView>

**Comment by onitzschke** [comment]
I'm using this feature without any issue. Closed due inactivity.
