### ISSUE TITLE
Cannot set MetaData on a new OfflinePack

### ISSUE THREAD

**Issue by atarsha** [nitaliano/react-native-mapbox-gl#991]
In V5 it was possible to set additional metadata on an offline pack. This was very useful for various reasons.

Looking at https://github.com/mapbox/react-native-mapbox-gl/blob/bf1ce26495dff3234c9266fb8964b4ad2d9f1543/javascript/modules/offline/OfflineCreatePackOptions.js#L13 it looks like adding a parameter on the _makeMetadata() method and passing `options.metadata` to it from the constructor, you could add it to the property.

**Comment by nitaliano** [comment]
Yea, this has come up a few times, and it will be added back. If you need to store data now I recommend using AsyncStorage and using the pack name as the key to store your data. I'll update this ticket once we add it back. The native code is already setup to handle the unstructured data the JS side just needs to be updated

**Comment by nitaliano** [comment]
Closing this out as fix has been merged into master
