### ISSUE TITLE
V5 -> V6 upgrade: is onUpdateUserLocation supported?

### ISSUE THREAD

**Issue by jjzazuet** [nitaliano/react-native-mapbox-gl#994]
Hi. Like the title says, I'm porting an app from `react-native-mapbox-gl` V5 to V6, but it seems that `MapView` no longer exposes this callback, and I can't find documentation regarding access to the current user location.

Are there any workarounds or alternatives?

Thank you for an awesome plugin!

**Comment by nitaliano** [comment]
We'll eventually expose this for now you can use https://facebook.github.io/react-native/docs/geolocation.html

**Comment by jjzazuet** [comment]
Ok thanks!

**Comment by jjzazuet** [comment]
Sorry, one more question. When this api call is re-introduced, will you folks stick to the previous location schema object, defined as:

```
"direction": {"type": "number"},
"horizontalAccuracy": {"type": "number"},
"latitude": { "$ref": "schema-types.json#/latitude" },
"longitude": { "$ref": "schema-types.json#/longitude" },
"magneticHeading": {"type": "number"},
"pitch": {"type": "number"},
"trueHeading": {"type": "number"},
"verticalAccuracy": {"type": "number"},
"zoomLevel": {"type": "number"}
```

Or, will it expose the location as defined by the geolocation api (which Facebook exposes in RN), defined as:

```
[NoInterfaceObject]
interface Coordinates {
    readonly attribute double latitude;
    readonly attribute double longitude;
    readonly attribute double? altitude;
    readonly attribute double accuracy;
    readonly attribute double? altitudeAccuracy;
    readonly attribute double? heading;
    readonly attribute double? speed;
};
```

I ask since I need to consider a migration path for my database schemas in case you decide to change the schema. Thanks!

**Comment by jjzazuet** [comment]
Also, should I reopen a new issue to track this? Thanks!

**Comment by nitaliano** [comment]
@jjzazuet we have this PR open for Android and I'll be implementing the iOS portion of it https://github.com/mapbox/react-native-mapbox-gl/pull/1011, I'll reopen this to track it

**Comment by nitaliano** [comment]
Support for this has been merged into `master` https://github.com/mapbox/react-native-mapbox-gl/pull/1011 this will appear in `6.0.4` going to close this issue out.
