### ISSUE TITLE
[Android] Centering after working differently on 6.0.3-rc1?

### ISSUE THREAD

**Issue by henrikra** [nitaliano/react-native-mapbox-gl#996]
After we updated to `6.0.3-rc1` looks like `userTrackingMode` or `showUserLocation` is working differently.

We are asking for location permissions on Android first. Then after allowing we just enabled `userTrackingMode` to `true` and looks like that alone centered to user location. But after updating that is not the case. Also with new version I tried to set `userTrackingMode` to Follow after location permissions. But that did not work either.

So has `userTrackingMode` or `showUserLocation` been edited between 6.0.2 and 6.0.3?

**Comment by nitaliano** [comment]
Yes, it's been updated to behave like the iOS SDK so there is no inconsistencies in behavior between platforms.

@henrikra if you have a control and you want to zoom in on the user location I would not use `userTrackingMode` for that unless you are really tracking the users location, you can use https://facebook.github.io/react-native/docs/geolocation.html#getcurrentposition to get the current position and you can use one of the zoom methods to zoom to the location

**Comment by nitaliano** [comment]
closing this issue out, if there is an issue here that I'm not realizing please reopen
